### ISSUE TITLE
User who completed training still listed as 'incomplete'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#10]
This user completed the training on January 27: https://en.wikipedia.org/wiki/Special:Contributions/Lvaugh4

Staging properly lists this user as having completed the training: http://dashboard-testing.wikiedu.org/courses/Louisiana_State_University/Biology_4125:_Prokaryotic_Diversity_(Spring_2015)

Production seems otherwise up to date about this user's contributions, but lists them as "Training Incomplete": http://dashboard.wikiedu.org/courses/Louisiana_State_University/Biology_4125:_Prokaryotic_Diversity_(Spring_2015)

**Comment by ragesoss** [comment]
Another instance, this time with Production correctly indicating that user Abbeykobrien completed the training (on January 19) but Testing incorrectly listing them as not having completed it.

http://dashboard-testing.wikiedu.org/courses/University_of_Pittsburgh/Art_Since_1945_(Spring_2015)
http://dashboard.wikiedu.org/courses/University_of_Pittsburgh/Art_Since_1945_(Spring_2015)

**Comment by ragesoss** [comment]
One more, where the user (Jakdsmith) completed the training on Feb 4. Both testing and production show edits from this course that happened later than the completion of the training.

http://dashboard.wikiedu.org/courses/University_of_Massachusetts_Amherst/Writing_as_Communication_COMM375_(Spring_2015)
http://dashboard-testing.wikiedu.org/courses/University_of_Massachusetts_Amherst/Writing_as_Communication_COMM375_(Spring_2015)

**Comment by ragesoss** [comment]
Hmm... All these examples have resolved themselves. I'm leaving this open for now, though, as I think we still have some reliability issues to work out around training completion.

**Comment by ragesoss** [comment]
Here's a case where the issue is present. Many of the students listed as incomplete actually completed their training early in the course, as one of their first edits:

http://dashboard.wikiedu.org/courses/California_Maritime_Academy/LIB100.2_-_Information_Fluency_in_the_Digital_World_%28Spring_2015%29

However, staging has a more accurate record, so maybe the switch to the new method of checking for training has already resolved this.

**Comment by ntdb** [comment]
These discrepancies were resolved with d144065d5894c40f0df266f80dff88eb0651316c and the tools changes made at that time.
