### ISSUE TITLE
For edit-a-thons (at least), dashboard should give user info about when to expect updated stats

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1005]
A common question / point of confusion is why edits aren't showing up yet during edit-a-thons. The dashboard should make it obvious to users that data gets pulled in periodically and it may take a while to show up.

Ideally, it could show actual info about how long the update cycle takes (based on the latest one) and/or when to expect the next update.

**Comment by Ladsgroup** [comment]
:+1:

**Comment by keer25** [comment]
Design for displaying the message : How about a info icon that opens a popup message on hovering over it.

**Comment by ragesoss** [comment]
@keer25 yes, something like that would make sense.

**Comment by keer25** [comment]
The constant update that happens every 15 minutes pulls revisions and hence except for article views and commons uploads all other metrics get updated every 15mins.? What about articles creates? How often is it updated?

**Comment by ragesoss** [comment]
`ConstantUpdate` runs every 15 minutes, but it exits immediately if another instance of that process is already running. Currently, updates are taking about 4 hours each on Wiki Ed production, and 8 hours each on Programs & Events Dashboard. The update process reports the time the update took to the logging service Sentry — see the `Raven.capture_message` call in `BatchUpdateLogging`.

One way to handle this could be to also record that update time somewhere else — such as using Rails.cache — and then use that to show the user a) how long each update usually takes, and b) when the last update finished.

**Comment by ragesoss** [comment]
An update on this... Currently, `ConstantUpdate` updates take about 15 minutes on Wiki Ed production, and about 2 hours on P&E Dashboard. `DailyUpdate` takes about 1 hours on Wiki Ed, and 4 hours on P&E.

We now have a `Setting` model which could be used to keep track of update data, such how long each of the last 10 constant and daily updates took and which update started most recently when.

**Comment by mauditecandela** [comment]
I'm checking this issue for my next contribution, but tbh I think it is to backend-ish for me to properly understand. I have several questions regarding the issue, and I would like to understand them better as it's a relevant topic at the art+feminism program. 

- I was checking the Setting model but I am unable to find the Service table. Why? I mean, is not part of the database yet? 
- What do you mean with using the Setting model in order to keep track of the updated data? Something like creating some methods that are searching for the last updates (e.g. Rails.cache.fetch('Update finished')) and counts the avge time an update needs to finish?
- About the UI, I thought it could be added to the hover bubble at articles.cross_wiki_tracking. What do you think?

Please let me know if you prefer me to ask you via slack or email.
Thanks!!!

**Comment by ragesoss** [comment]
Either here or slack are best.

There is no `Service` table. What is that in relation to?

For using the Setting model, I was imagining something like this: a Setting record with a key like `data_cycle` or `recent_updates`, with the value being a hash that holds everything we need to give users an idea of how long it should take to update: when each of the last X updates took and how long each took, and when the current update (of which kind) started.

For UI, I think it should at least be accessible from the home tab somewhere, as those stats the first point of entry for users wondering why the dashboard isn't reflecting their work yet.

**Comment by mauditecandela** [comment]
I meant 'Setting' table, not Service, sorry. 

My first thought regarding this (spoiler: basic questions to come): 
1) We could create a last_update method at Settings Model that fetch the last updates and calculates the time left for the next update. Would you add all this information to the ':values' parameter from Settings model?
2) We could add this last_update method to log_end_of_update method at 'BatchUpdateLogging' so it gets called everytime the update takes place. If not, somewhere else I am not aware of?
3) How should we test this? Should I just run the dashboard for some time and manually wait for updates?

Please let me know if this fits your proposal or if I am totally lost.
Thanks :)

**Comment by ragesoss** [comment]
The table is called `settings`, per Rails convention, corresponding to the `Setting` model.

I don't think we want to cram all this into the `Setting` model itself, since this behavior would be focused on one particular Setting record. We probably want a new class to handle updating the record (which could be called from relevant places in BatchUpdateLogging methods). Then the class could be tested independently of the update process itself.

**Comment by mauditecandela** [comment]
- About the table, yes, it was a misunderstanding, sorry. 
- About the model, should we locate the record in a module in lib, for example? This way could be imported and used e.g. in BatchUpdateLogging. 
- Would you write the info in the settings table, btw? 
- I've seen that all the logs are written to Sentry, right? Is there any way of accessing them?

Maybe I am asking too much but I am trying very hard to understand. So what I understood so far is that the new module would create a new Class that could have different methods, that we could call from BatchUpdateLoggin or ConstantUpdate, for example. We would then calculate the avge time the last 10 updates (Constant Update + Daily Update) took and save this time in a hash, together with the date of the last update (the last one of them two).

**Comment by mauditecandela** [comment]
Meanwhile I added an UI fix with a general warning, that I think can already help the user :)

**Comment by ragesoss** [comment]
> About the model, should we locate the record in a module in lib, for example? This way could be imported and used e.g. in BatchUpdateLogging.

I think SpecialUsers presenter is a good exemplar for how it could be done; it also exists to provide access to data in a particular Setting record. Since this will probably be a class that we will want to use for both writing and reading, though, it probably makes sense to keep in in app/models (as a plain, non-ActiveRecord model).

> Would you write the info in the settings table, btw?
Yes. The Settings table is designed to be very flexible about the data it stores; basically, you can any raw data — strings, numbers, arrays of strings and numbers — into a hash and save it. It would probably even be convenient to store the same log we send to Sentry.

> I've seen that all the logs are written to Sentry, right? Is there any way of accessing them?

I have access to them, but they are not publicly viewable. Here's what a typical one looks like:

```
[
 2017-10-19 16:25:42 UTC - Ready to update 340 courses,
 2017-10-19 16:25:42 UTC - Importing revisions and articles for all courses,
 2017-10-19 16:26:35 UTC - Matching assignments to articles and syncing titles,
 2017-10-19 16:26:39 UTC - Importing wp10 scores for all en.wiki revisions,
 2017-10-19 16:26:52 UTC - Checking for plagiarism in recent revisions,
 2017-10-19 16:26:53 UTC - Updating views for newly added articles,
 2017-10-19 16:26:53 UTC - Updating ratings for new articles,
 2017-10-19 16:26:53 UTC - Backfilling Commons uploads for needs_update courses,
 2017-10-19 16:26:53 UTC - Updating ArticlesCourses cache,
 2017-10-19 16:28:53 UTC - Updating CoursesUsers cache,
 2017-10-19 16:31:20 UTC - Updating Course cache,
 2017-10-19 16:35:30 UTC - Finished updating cached values,
 2017-10-19 16:35:30 UTC - Updating greeting status of ungreeted students,
 2017-10-19 16:39:11 UTC - Generating AfD alerts,
 2017-10-19 16:39:19 UTC - Generating discretionary sanctions alerts,
 2017-10-19 16:39:21 UTC - Generating DYK alerts,
 2017-10-19 16:39:21 UTC - Generating course alerts,
 2017-10-19 16:39:34 UTC - Generating survey response alerts,
 2017-10-19 16:39:34 UTC - Update finished
]
```

> Maybe I am asking too much but I am trying very hard to understand. So what I understood so far is that the new module would create a new Class that could have different methods, that we could call from BatchUpdateLoggin or ConstantUpdate, for example. We would then calculate the avge time the last 10 updates (Constant Update + Daily Update) took and save this time in a hash, together with the date of the last update (the last one of them two).

Yes, something like that. I think it would make sense to keep completion times for both the last 10 Constant updates and the last 10 Daily updates, as well as:
* the logs for the last Constant and last Daily
* the completion time of the last Daily and last Constant
* the start time and type of the currently-running update.

**Comment by mauditecandela** [comment]
I added a new presenter (in my Fork https://github.com/mauditecandela/WikiEduDashboard/commit/edbb22ee45055b47783f2fe93e4f03b61096451f) to access the data in the Setting record (fetch the data and update it). I will continue working on the cache and calculation, but a review would be very appreciated :) Thanks!

**Comment by mauditecandela** [comment]
Sorry for the github Spam. I closed the PRs and will reopen them once I have a more stable solution. Sorry again!

**Comment by ragesoss** [comment]
No worries!

**Comment by mauditecandela** [comment]
Another PR for this issue: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1484

**Comment by mauditecandela** [comment]
@ragesoss I will continue with this issue for my first day at Outreachy if you don't have anything against it. ^^

**Comment by ragesoss** [comment]
@mauditecandela sounds good.  We should also find some time to meet soon.

**Comment by mauditecandela** [comment]
@ragesoss sure. I wrote you on slack :) Let me know about your schedule.

**Comment by ragesoss** [comment]
Done.
