### ISSUE TITLE
Sorting Activity by chars added/removed is not ordered intuitively 

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#101]
If I sort by characters added on the Activity tab of a course, it will start from the highest negative numbers, then go down to -1, then start from teh highest positive numbers and go down to zero.

I think that the two most useful sorting patterns would be:
- Sorting by magnitude (highest to lowest on first click)
- Sorting in number order (high to zero to negative)

Either would be preferable to the current sort order. Ideally, that sorter would cycle from magnitude to number order to reverse magnitude to reverse number order.

**Comment by ntdb** [comment]
Updated to sort by number order in a1d06a8ebe1e32355c388fb79987c758c4b8fbec.

**Comment by ntdb** [comment]
Enhancement will be to allow sorting by magnitude (absolute value of characters added/removed).

**Comment by ragesoss** [comment]
This is currently implemented in the `recent_edits.js` reducer, with a call to `sortByKey` from `model_utils.js`.

An option for sorting by absolute value could be added to `sortByKey`.
