### ISSUE TITLE
Convert ERB templates to HAML

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1021]
We switched to .haml files as the default for new Rails templates quite a while ago, but we still have a number of .erb templates that have not been updated to .haml format. Converting these files would be a big win for consistency.

There are a number of tools available to do this. Converted files should be checked for accuracy in a working development environment — make sure they still load properly and look right.

To get started on this, you'll need to set up a development environment. Follow the setup instructions here, and let us know if you run into any problems: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md

- [ ] views/analytics/index.html.erb
- [ ] views/analytics/_campaign_stats.html.erb
- [ ] views/analytics/_monthly_report.html.erb
----
- [ ] views/article_finder/index.html.erb
- [ ] views/article_finder/results.html.erb
- [ ] views/article_finder/row.html.erb
----
- [x] views/courses/show.html.erb
- [ ] views/courses/_campaign_courses.html.erb
- [ ] views/courses/_header_stats.html.erb
- [ ] views/courses/_row.html.erb
- [ ] views/courses/_user_courses.html.erb
----
- [ ] views/errors/file_not_found.html.erb
- [ ] views/errors/incorrect_passcode.html.erb
- [ ] views/errors/internal_server_error.html.erb
- [ ] views/errors/login_error.html.erb
- [ ] views/errors/unprocessable.html.erb
----
- [ ] views/recent_activity/index.html.erb

**Comment by Wowu** [comment]
I'll work on this issue.

**Comment by ragesoss** [comment]
@Wowu great! Let me know if you have any questions, either in this thread or via IRC in the freenode #wikimedia-ed channel.
