### ISSUE TITLE
If answer is changed to survey condition question, answers to dependent conditional question are lost

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1031]
Create a three question survey:

1. required radio question with options **a** and **b**
2. optional checkbox question with answers **one** and **two** and a followup question, conditional on answering **a** to the first question
3. Final non-conditional question (necessary to work around #836)

Now take the survey:
1. Click **a** for the first question
2. Answer the second question, including both checkbox and followup
3. Skip the third question and submit.

This works.

Now delete the answers (`Rapidfire::Answer.destroy_all; Rapidfire::AnswerGroup.destroy_all`) and take it again:
1. Click **b** then click **a** (or any series of changes that ends up with **a** in the end, but involves click **b** at least once)
2. Answer the second question, including both checkbox and followup
3. Skip the third question and submit.

In this case, the followup answer is saved, but the checkbox choices are not. They all come through as unselected in the params.

**Comment by ragesoss** [comment]
@mattfordham Quick primer on setting up a survey (since the flow is not super obvious):

1. make yourself an admin (`permissions = 1`)
2. go to /surveys
3. create a survey
4. go to /surveys/rapidfire/question_groups
5. create a question group
6. create questions in the question group
7. return to /surveys, edit the survey, edit questions groups for the survey, and add the question group
8. mark the survey as 'open'
9. go to /surveys/:survey_id to take the survey.

If you get an error on step 9, make sure your account is part of at least one course. If not, create one and then it should work.

**Comment by mattfordham** [comment]
Like all good bugs, this took forever to find and the solution was a very small change. In a nutshell, the code that "reset" the associated conditional questions was wiping out the *potential* values of the checkboxes. 

Will leave open until you confirm.

**Comment by ragesoss** [comment]
@mattfordham thanks! can you undo the schema change?

**Comment by ragesoss** [comment]
Nevermind, took care of that. Confirming now...

**Comment by ragesoss** [comment]
Yep!

**Comment by mattfordham** [comment]
Great! Sorry that schema thing slipped in there :|
