### ISSUE TITLE
Layout is broken on Windows

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#105]
Probably only since today, because of new SVGs.

**Comment by ntdb** [comment]
This is an issue with our icon font generation. Running the same SVGs through Icomoon produces excellent results in all browsers. I'll substitute Icomoon fonts for now.

**Comment by ntdb** [comment]
Bug resolved in f4cd5350987bbb1fec58f3867408328f28c5642f. Future enhancement will be to streamline our icon font generation.
