### ISSUE TITLE
Automatic setting of campaign slug strips out non-ascii characters

### ISSUE THREAD

**Issue by MusikAnimal** [WikiEducationFoundation/WikiEduDashboard#1062]
https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1061/files#diff-3a66787b6a08c01093eeba8750b23592R129

`\w` only matches ascii word characters. Letters in other scripts will get stripped out

**Comment by ragesoss** [comment]
@MusikAnimal do you have a chance to tackle this one?
