### ISSUE TITLE
Admins should be able to mark an Alert as 'resolved'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1068]
We have assorted types of Alert records that get created in different situations. For some, like deletion alerts and 'continued activity' alerts, it would be helpful if admins could indicate that the issue has been dealt with, and then the system would create a new alert if the alert conditions come up again. For example, if an article is nominated for deletion, then that gets resolved and it is not deleted, but later it gets renominated, the system would again create a new alert about that. Or if course dates are extended to include student activity after the initial end date, but then there is even more activity after the new end date, the system would issue another alert.

**Comment by MrWilhelm** [comment]
If I am not wrong, reason for alerts not triggering for the second time, this line on ContinuedCourseActivityAlertManager;

```next if Alert.exists?(course_id: course.id, type: 'ContinuedCourseActivityAlert')```

I think we can add another alert manager to lib/alerts which checks for existing alerts and deletes if there is any. And then we can add a callback to Course model after updating course date which calls existing alert. We can also use this manager to expire Alerts when needed like when article resolved.

 @ragesoss

**Comment by ragesoss** [comment]
@MrWilhelm you're correct about where the system looks to avoid triggering an alert twice. We don't want to delete old alerts, though. I think we'd instead want to do some thing like add a `resolved` column, defaulting to `false`, to the Alert records. Then we'd do something like add `resolved: false` to that `Alert.exists?` call. (It also needs a UI to mark an alert resolved.)

If you're interested in working on this, I suggest starting with the case of `ArticlesForDeletionAlert`.

**Comment by MrWilhelm** [comment]
So is this how I should do it;

- Create migration to add alerts resolved boolean column default false
- Add resolve action for alerts controller to update resolved column
- Add button to resolve alerts.

Can we add something like '?resolved=true' parameter to the end of the link sent with email, then we can resolve alert on page load automatically?
