### ISSUE TITLE
Diff Viewer shows only one column, on left, if all changes are new paragraphs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1088]
When there are no 'minus' paragraphs to show, then the whole table shifts so that added content is on the left.

As of now, that's the case with the Dodd-Frank article here: https://dashboard.wikiedu.org/courses/Northeastern/Advanced_Writing_in_the_Business_Administration_Professions_-_online_%28Fall_2016%29/articles

![screen shot 2016-12-19 at 1 02 19 pm](https://cloud.githubusercontent.com/assets/848483/21324151/70fd4e9c-c5d5-11e6-9b39-a475c00abe3a.png)

**Comment by dnahol** [comment]
Hi, @ragesoss! I'm new to this repo. I'm assuming you would like the 'plus' columns to always be on the right, as they are here?

<img width="1197" alt="Screen Shot 2019-11-05 at 6 26 00 AM" src="https://user-images.githubusercontent.com/2976514/68216194-628b0a00-ff95-11e9-9794-9f2bd9862594.png">

**Comment by dnahol** [comment]
Apparently changing the colspan from 2 to 4 of the .empty-diff element on the left changes the issue. Does that look like an acceptable solution that won't break anything else?

Screenshot in Firefox Devtools
<img width="1160" alt="Screen Shot 2019-11-05 at 7 24 26 AM" src="https://user-images.githubusercontent.com/2976514/68221010-94a06a00-ff9d-11e9-85f9-60666cda26ec.png">

**Comment by dnahol** [comment]
@ragesoss what do you think?

**Comment by dnahol** [comment]
@ragesoss  @khyatisoneji Should we close this issue?

**Comment by khyatisoneji** [comment]
Yes
