### ISSUE TITLE
Setting up a development environment in Windows is not documented

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1097]

**Comment by markspolakovs** [comment]
Initial thoughts from reading, without having tried the instructions:

 * RVM doesn't exist on Windows, use RubyInstaller or RailsInstaller
 * No xcode for Git, use Git for Windows
 * Can't `brew install` MySQL, use XAMPP
 * `zeus` isn't a thing on Windows

I'll try running through the instructions tomorrow, this is just my initial read.

**Comment by ragesoss** [comment]
@markspolakovs thanks! Someone else got started with this using RubyInstaller, and got a fair ways through it, but hasn't posted notes yet.

**Comment by markspolakovs** [comment]
Also, zeus depends on the gem `pty`, which isn't available on Windows. I'll see if I can get in a PR to not install zeus on Windows.

**Comment by markspolakovs** [comment]
Also, for some reason, running `guard` gives me the message ` Rails NOT started, check your log files.` Running `rails s` directly works fine.

**Comment by markspolakovs** [comment]
Created pull requests with my results and changes I needed to make. See above.
