### ISSUE TITLE
Dashboard does not retain sorting on page reload

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#11]
If I sort the global dashboard (eg, by number of students) then visit one of the individual courses, then press 'back' and return to the global dashboard, my place on the page is retained but the sorting order is reset to default... meaning that place on the page is useless and a little bit counterproductive.

Sorting state should be retained if I return to a page.

**Comment by ragesoss** [comment]
Firefox does retain the sorting, and so does IE. Chrome is the only browser I've tested that does not.

**Comment by ntdb** [comment]
This could be handled using JS routing when the home page is converted to React. Until then, it's totally browser-dependent.

**Comment by ragesoss** [comment]
Now this doesn't work in Firefox either. Converting the homepage to React would be a nice improvement, eventually.

**Comment by ragesoss** [comment]
I don't think this is solvable in isolation, and may or may not make sense if the design changes enough for it to be solvable, so closing.
