### ISSUE TITLE
Improve ordering of Campaign lookup when adding a campaign to a course/program

### ISSUE THREAD

**Issue by erikaherzog** [WikiEducationFoundation/WikiEduDashboard#1124]
When adding **Campaign** to **Program**, scrolling through the drop-down Campaign list at the PlusSymbol click option, it's a bit jumbled together.

- Could Campaign choices within drop-down auto-A-Z alphabetize?

– Erika

**Comment by ragesoss** [comment]
@erikaherzog It's now ordered from from newest to oldest. Next time you need to add campaigns, let me know whether it seems practical this way.
