### ISSUE TITLE
Campaign description: Markup not displaying

### ISSUE THREAD

**Issue by erikaherzog** [WikiEducationFoundation/WikiEduDashboard#1127]
For **Campaign: AfroCROWD**

Markup is not displaying as it should. Seeing code instead of bold and links.

It looks like both the main Campaign description as well as the Program description are not displaying markdown correctly.

[https://outreachdashboard.wmflabs.org/campaigns/afrocrowd/overview](https://outreachdashboard.wmflabs.org/campaigns/afrocrowd/overview "https://outreachdashboard.wmflabs.org/campaigns/afrocrowd/overview")

– Erika

**Comment by ragesoss** [comment]
Whoops. We forgot to do markdown handling for the campaign pages. Should be easy to fix.

**Comment by ragesoss** [comment]
@MusikAnimal do you have a chance to tackle this one too?
