### ISSUE TITLE
Uploads > Files Uploaded to Wikimedia Commons - not populating

### ISSUE THREAD

**Issue by erikaherzog** [WikiEducationFoundation/WikiEduDashboard#1133]
It looks like for this event
https://outreachdashboard.wmflabs.org/courses/Wikimedia_New_York_City/Wikipedia_Day_2017_@_Ace_NY/overview

Wikimedia Commons images are not being counted

Uploads > Files Uploaded to Wikimedia Commons

There are 47 associated images with this event:

https://commons.wikimedia.org/wiki/Category:Wikipedia_Day_16_NYC

– Erika

**Comment by ragesoss** [comment]
It looks the nightly update process that imports commons uploads has failed for the last two nights. I'll look into it soon.

**Comment by ragesoss** [comment]
I ran the image import process, and it looks like it's showing good data now. It shows 28 instead of 47, but I'm guessing the difference is images that were uploaded earlier and added to the category, like this one: https://commons.wikimedia.org/wiki/File:Ace_Hotel_2016_01.jpg
