### ISSUE TITLE
Underscores in usernames are not replaced by spaces

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1136]
When users are created by username, an underscore does not get replaced by a space, and in this case, no revisions get pulled in for the user.

Should be an easy fix in `UserImporter.new_from_username`

**Comment by commitshappen** [comment]
I believe I've solved this issue. Just need help with the pull request, as this is my first Github contribution.

**Comment by ragesoss** [comment]
Fixed via eb1ba5896ed3e2ffe0c3c839c99980dec9c48e96
