### ISSUE TITLE
Ukrainian characters in Campaign URL

### ISSUE THREAD

**Issue by erikaherzog** [WikiEducationFoundation/WikiEduDashboard#1137]
It looks like for two campaigns I started the URL is showing null instead of the name of the campaign.

https://outreachdashboard.wmflabs.org/campaigns/___2016/programs
Карыстальнік Група Беларусь 2016 Programs

Карыстальнік Група Беларусь 2017 Programs
https://outreachdashboard.wmflabs.org/campaigns/___2017/programs

– Erika

**Comment by ragesoss** [comment]
This is issue #1062
