### ISSUE TITLE
Uploads - Wikimedia Commons images

### ISSUE THREAD

**Issue by erikaherzog** [WikiEducationFoundation/WikiEduDashboard#1138]
For Wikipedia Day 2017, it looks like there were quite a few images that were uploaded are not uploaded:

https://outreachdashboard.wmflabs.org/courses/Wikimedia_New_York_City/Wikipedia_Day_2017_@_Ace_NY/uploads

You can see 46 are listed here:

https://commons.wikimedia.org/wiki/Category:Wikipedia_Day_16_NYC

But the Outreach Dashboard for the event's Overview only lists 28.

– Erika

**Comment by ragesoss** [comment]
@erikaherzog were any of those missing ones uploaded during the event? The first ones I checked in the category had been uploaded in December, and were just added to the category afterwards.

**Comment by ragesoss** [comment]
I'll reopen this and look into it further if you find any images that didn't show up on the dashboard but were uploaded during the event.
