### ISSUE TITLE
Editors Display: Admin not showing up under Editors

### ISSUE THREAD

**Issue by erikaherzog** [WikiEducationFoundation/WikiEduDashboard#1139]
Two questions:

- Would it be possible to have the admins to the course also show up in the Editors? It is problematic to not have the admins and their contributions not listed

- Oftentimes I will add user names and they are already signed up to the course -- but if I do a Ctrl+F I don't see their names listed. Is this happening to anyone else?

– Erika

**Comment by ragesoss** [comment]
> Would it be possible to have the admins to the course also show up in the Editors? It is problematic to not have the admins and their contributions not listed

At this point, no, that's not possible. There are some complications around doing that. For many types of events — including the Wiki Ed classroom program — we don't want to count contributions from the organizers. They are often experienced editors who swamp the contributions of the newcomers, and who doing their regular editing activities during the event. The system currently enforces each user only having one role in a program, so the same user can't be both facilitator and editor in the same program.

> Oftentimes I will add user names and they are already signed up to the course -- but if I do a Ctrl+F I don't see their names listed. Is this happening to anyone else?

@erikaherzog Can you provide a link to the course and the username(s) where you had this happen?

**Comment by ragesoss** [comment]
Please reopen if this comes up again, and/or if you have specific details I can look into.
