### ISSUE TITLE
Editors not populating

### ISSUE THREAD

**Issue by erikaherzog** [WikiEducationFoundation/WikiEduDashboard#1148]
Had a workshop event today and although more than 4 people registered for course via Outreach Dashboard, they aren't appearing under the editor list.

This is a huge problem. Need this basic functionality, to be able to see editors somewhat instantly. 

And now I can't follow up with the editors now to see their edits, and have no way to gather their user names now.

https://outreachdashboard.wmflabs.org/courses/Wikimedia_New_York_City/Broadly_@_VICE/students

Please advise. 

– Erika

**Comment by ragesoss** [comment]
It looks like the end date was set to 2017-01-18 13:00 EST, meaning that it was marked to end yesterday. Since the program was already ended, it would not allow users to join.

**Comment by erikaherzog** [comment]
Ugh. Gads. Sorry. I'll adjust. #EndUserIssue #obvs....

Again, apologies.

– Erika

**Comment by erikaherzog** [comment]
@ragesoss Is there a way to recover user names for those who registered? I mean, during the event this afternoon people definitely registered. No way to fix this?

**Comment by ragesoss** [comment]
@erikaherzog if you know exactly when, we could look at the user creation logs on meta (which is where the login form sends people) for that time, and I can look on the dashboard database to see if any logged in there, if the usernames look familiar.

The flow works like this:

1. User clicks 'create account' from the dashboard
2. User is sent to Wikipedia to create an account
3. User is sent to OAuth page to authorize the dashboard to log in with their account
4. User click Allow and is redirected to the dashboard, specifically to the program enroll URL they started from
5. User clicks 'Join'

At step 4, they will have a user record in the dashboard database, and at step 5 they will be associated with the course.

**Comment by erikaherzog** [comment]
I looked here -- and wasn't succesful -- https://en.wikipedia.org/w/index.php?title=Special:Log/newusers

But you're saying it would show up on Meta instead?

Anything you can provide I'd be grateful. This is a hard lesson learned. I was creating way too many Programs at once and obviously got my dates cornfused.

The folks at the Wiki Workshop today definitely did that flow.

**Comment by erikaherzog** [comment]
It was for this workshop:

https://en.wikipedia.org/wiki/Wikipedia:Meetup/NYC/2017-01_Broadly_Workshop

14:00 to 15:00 is when they would've registered..... so +5 would be 19:00 to 20:00?

**Comment by erikaherzog** [comment]
Is this it?
https://meta.wikimedia.org/w/index.php?title=Special%3ALog&type=newusers&user=&page=&year=&month=-1&tagfilter=&hide_thanks_log=1&hide_tag_log=1

**Comment by ragesoss** [comment]
I was mistaken, they would have created their accounts from en.wiki.

**Comment by erikaherzog** [comment]
Right. Okay, I've pinged the woman in charge of the event -- they are going to DC so it may take her time to get back to me. I've tried going through both but haven't had great luck. The only plus was that I had them all write at least a sentence on their User pages so they will be blue. So less to parse through.

Thanks for the follow up Sage. Apologies for being such a dumbass. :-)

**Comment by ragesoss** [comment]
@erikaherzog I emailed you with some data from the dashboard, my best guess as to which users.
