### ISSUE TITLE
It should be hard to miss if a course is ended when a user tries to join it

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1149]
If a course has already ended, users will not be able to join. The fact that it has ended should be clear to users *before* they try to create accounts and/or click 'Join'. One scenario this should help fix is if the dates of an edit-a-thon were entered incorrectly; participants should be able to easily notice the problem and tell the organizers.

We can probably do this via changes to the `EnrollCard` component.

**Comment by arreche** [comment]
Steps to enroll in a course:
1. A student opens a course URL containing an enroll code.
2. The page prompt to join in the course
3. A notification is displayed indicated when the student tries to join in the course.

![joining to an ended course](https://cloud.githubusercontent.com/assets/459813/23206300/0acf961e-f8e5-11e6-8b2b-838a9e2817ad.gif)

**Comment by arreche** [comment]
@ragesoss How will the user notice that this course is already ended?

**Comment by arreche** [comment]
This is my proposal:
- Not displaying the embedded dialog which prompts to join a course.
- Disabling the `join` button in the actions pannel.
- Displaying another text in that button. i.e. `Enrollment is closed`

What do you think?

**Comment by ragesoss** [comment]
> What do you think?

I suggest instead:
* Replacing the message in the embedded dialog (from `EnrollCard`) with one noting that the course has ended. This dialog is triggered by having `?enroll` in the URL, which usually means the user got there by following an enroll link from email or another site. This is the only situation where we need to highlight the 'course has ended' situation.
* Removing the `join` button in the Actions (without replacement)
