### ISSUE TITLE
Course creation workflow broken

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#115]
As of recently the course creation workflow doesn't work. When you click "Create new course", you just get Lorem ipsum, instead of the wizard. (549ff29654d4526a0f39c86559040f504780902e is the last commit that touched course_creator.cjsx)

@dmak78 Can you look into it? I started to write a feature spec for course creation, and I got stuck on this.

**Comment by dmak78** [comment]
@ragesoss This appears to be something Nate was working on yesterday; I'll do my best to track down the problem.

**Comment by dmak78** [comment]
@ragesoss found the issue and about to push a fix for ya. will close this issue when committed. yeah!

**Comment by ragesoss** [comment]
@dmak78 It's stuck now at the "Create my course!" button.

**Comment by dmak78** [comment]
This one has been driving me bonkers. This is all stemming from some changes Nate made yesterday and I cannot for some reason get both the first page of the wizard AND subsequent pages to show with the changes he made. I am able to get one or the other working. So, in the meantime, I am reverting back to before he made the changes. As far as I can tell this doesn't break anything and at least allows one to go through the whole wizard flow.

Will close this issue when fix is commited.

**Comment by ragesoss** [comment]
@dmak78 I still cannot proceed past "Create my Course!" on the course details view.

**Comment by dmak78** [comment]
@ragesoss Can you please try again. It is working for me. There is a bit of a lag between hitting Create and going to the next page, which I can address as a UX concern, but I am getting no errors and the course creation process moves alone to the next screen for me. 

Also, please be aware that I have to move onto another project for the rest of today and will not be able to address any new concerns until Monday at this point.

**Comment by ragesoss** [comment]
@dmak78 thanks much, Kevin. I'll check it out and report back. Talk to you next week!

**Comment by dmak78** [comment]
You're welcome! yeah let me know if its totally broken for you. The lag does concern me, like something isnt totally working as expected, but don't want to get you stuck with the flow not working. ;-)

**Comment by ragesoss** [comment]
@dmak78 Okay, I think the problem was that I was using a (case variant of a) title that was already in my database. Using a different title, it worked. The lag is pretty major, though. Thanks much!

**Comment by dmak78** [comment]
@ragesoss Yeah, I expect alot of this I can address on Monday; I am supposed to do some better validation on the Wizard form so I think some of this will be involved in that process as well so there is better UX overall. Yes!
