### ISSUE TITLE
Users starting from an enroll link often end up logged in but not enrolled

### ISSUE THREAD

**Issue by erikaherzog** [WikiEducationFoundation/WikiEduDashboard#1151]
In general, the signup flow for new users is a bit brittle, and it's not uncommon for users to end up accidentally failing to join the course/program they are participating in.

This is a tricky problem given the limitations of the mediawiki oauth and account creation processes. There might be ways to work around it, such as by creating a temporary user account for a user when they start from an enroll link. On the design side, we still need some kind of explicit 'Join this course/program' action that the user takes, as well as some kind of confirmation that the user successfully joined. But perhaps the intent-to-join step could be moved to before OAuth login.

----
[original description]

I did a workshop today and saw the two editors I was onboarding sign up via the Outreach Dashboard. But tonight when I went to check the dashboard I didn't see the editors listed.

I went in and manually added them after the event but I'm not sure what is happening. I literally saw them sign in via Dashbaord, as that's how they created their accounts.

https://outreachdashboard.wmflabs.org/courses/Wikimedia_New_York_City/Lenny_TtT_@_Lenny_Letter/students

Am I doing something wrong here?

– Erika

**Comment by ragesoss** [comment]
It sounds like they created accounts, but didn't finish up by joining the program. Please let me know which steps you definitely saw them get through.

----

The flow works like this:

1. User clicks 'create account' from the dashboard
2. User is sent to Wikipedia to create an account
3. User is sent to OAuth page to authorize the dashboard to log in with their account
4. User click Allow and is redirected to the dashboard, specifically to the program enroll URL they started from
5. User clicks 'Join'

At step 4, they will have a user record in the dashboard database, and at step 5 they will be associated with the course.

**Comment by ragesoss** [comment]
@erikaherzog In case this didn't reach you without a mention of your username... ^

**Comment by ragesoss** [comment]
I think this should be largely fixed now, with the current flow no longer requiring that final 'Join' click after the user successfully logs in (if they started from an enroll link).
