### ISSUE TITLE
Admins should be able to search for users by email

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1164]

**Comment by MrWilhelm** [comment]
Should we create another admin page like feedbacks, alerts etc., which lists and search users? Or should we include it anywhere else?

Also, do we need something like typeahead(https://twitter.github.io/typeahead.js/) or just basic search with a button?

**Comment by ragesoss** [comment]
@MrWilhelm I think a `/users` index page would make a lot of sense for this (added the the admin nav like the others).

Typeahead would be nice if it's easy to add, but just a basic search with a button would be fine.

Another nice-to-have feature would be a way to get a list of all the instructors in the system.

**Comment by MrWilhelm** [comment]
I have started tests and some implementation and send it soon.

However I'm not sure about scope of the search. I did something like this, but depends on it, we can create separate query builder on lib, but for now it is simple class method on model. Query is something like:

```ruby
User.('lower(email) like ?', 'search_term%')
```

**Comment by ragesoss** [comment]
Sounds good to me.

**Comment by ragesoss** [comment]
Implemented in #1170
