### ISSUE TITLE
On-wiki course pages should show all instructors, not just first

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1175]
The course details templates used for on-wiki course pages currently uses 'instructor_username' and 'instructor_realname' parameters, which shows the first (ie, first enrolled) instructor/facilitator. (See `WikiCourseOutput#course_details`.)

Support should be added for any number of additional instructors. This should be done with new parameters, so that the templates will remain backwards-compatible on-wiki. Here's the en.wiki template: https://en.wikipedia.org/wiki/Template:Course_details

**Comment by aSquare14** [comment]
I'd like to work on this. Would be helpful if you tell me what exactly backwards-compatible means !

**Comment by ragesoss** [comment]
Backward-compatible means it should use the same mediawiki template parameters it currently uses, but also add additional ones. That way, if the template gets updated to use the new parameters then it will show additional instructors, but if a call to the same template just has the old parameter, it will keep the current behavior.

**Comment by enelesmai** [comment]
Hello @ragesoss is this issue already solved?

**Comment by ragesoss** [comment]
@enelesmai this is not already solved.
