### ISSUE TITLE
Dashboard should detect, and create alerts for, blocked edits

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1176]
Occasionally, automated edits from the dashboard are blocked. This can happen either because of an autoblock, where-in subsequent users of the same IP as an initial blocked user get automatically blocked, or because of a range block that affects the IP of the dashboard's server (which is currently on Linode).

Blocked edits should trigger an alert with an email to the dashboard's `technical_help_staff` user, but only up to once per day. (We don't want an email flood during such a blockage incident.)

**Comment by ragesoss** [comment]
Failed edits and their error codes are handled in `lib/wiki_response.rb`.

The relevant error codes are `blocked` and `autoblocked`.

**Comment by hin101** [comment]
Do we have a queue table for alerts or do we need to create one and reset it once the email has been sent?

**Comment by ragesoss** [comment]
For similar email alerts, we've used the Alerts model (which has many specific types for various kinds of alerts). Here's a recent one I added: bc4d13f6dbb7818de3ce3d090d576ba84ced0568

Something like that would work here, although should probably be done asyncronously via a sidekiq worker.
