### ISSUE TITLE
Wikis should be validated to ensure they exist

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1184]
`Wiki` currently has a basic validation for new records based on a list of language codes and projects. However, not all project/language codes actually exist. For example, `dk.wikipedia.org` does not exist; it redirects to `da.wikipedia.org`. Invalid wikis result in data not being fetched and lots of noise in the Sentry logs for all the API failures when when `Replica` cannot connect to the (nonexistent) database.

At the time of creation, each wiki should be validated via a ping to its API.

**Comment by ragesoss** [comment]
* During validation before a new `Wiki` record is created, ping the corresponding API to confirm that it exists. If not, catch the network error and raise an `InvalidWiki` error.

**Comment by FedericoEsparza** [comment]
https://youtu.be/d-8MafzIxIU?t=52m2s Some discussion and point voting in the 2017-02-21 AV Americas Scrum recording. _(Link bookmarks and directs to the starting time)_
