### ISSUE TITLE
System should detect and alert new users who don't have email enabled on their Wikipedia accounts

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1185]
Forgetting passwords is a very common issue for instructors and students, and if they don't have a Wikipedia email enabled, they won't have any options besides abandoning their account and making a new one.

A good way to implement this might be to trigger something during onboarding to check whether wiki email is enabled, and show a warning message … probably an extra screen highlighting the problem and explaining the solution with a link to the mediawiki preferences page … if not.

**Comment by FedericoEsparza** [comment]
https://youtu.be/d-8MafzIxIU?t=44m2s Some discussion and point voting in the 2017-02-21 AV Americas Scrum recording.

**Comment by ragesoss** [comment]
We have an email that goes out to students who don't have their Wikipedia email enabled. That's been okay... I'm not sure whether a UI message that does the same thing will help much or not. I'm going to close this on the theory that we've done as much as we reasonably can.
