### ISSUE TITLE
Improve styling and relevant info shown in AlertsList

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1187]
* The resolve link should be a button.
* Instead of showing either 'N/A' or the resolve link, that column should show a check mark or similar indicator if the alert is resolved, and should show nothing at all if it is unresolvable.

**Comment by FedericoEsparza** [comment]
https://youtu.be/d-8MafzIxIU?t=36m10s Some discussion and point voting in the 2017-02-21 AV Americas Scrum recording.

**Comment by FedericoEsparza** [comment]
https://youtu.be/mPfZ1szbekU?t=5m40s Some discussion and point voting AGAIN (by accident) in the 2017-03-08 AV Americas Scrum recording. (*Link directs to the starting time of the relevant discussion*)

**Comment by FedericoEsparza** [comment]
https://youtu.be/FTXQLL8eZUo?t=6m5s Extended discussion in the 2017-03-15 AV Americas Scrum recording. (*Link directs to the starting time of the relevant discussion*)
