### ISSUE TITLE
There is a significant delay after clicking "Create my Course!"

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#119]

**Comment by ntdb** [comment]
Is this still an issue? If so, are there any particular input values or a specific browser that seem to be associated with the problem? Cannot reproduce in FF or Chrome on Mac.

**Comment by ragesoss** [comment]
I can't replicate any more locally. There was a delay of maybe a second and a half or two seconds when I just tried on staging, but that's in the okay range.
