### ISSUE TITLE
Too long assignment titles cause MySQL errors

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1197]
Putting in a very long assignment title results in an error in MySQL. Too-long titles should be caught and handled earlier in the data flow, with a sensible error message presented to the user.

**Comment by ragesoss** [comment]
@keer25 You asked:

> It will be helpful if someone can suggest where the the create and update actions of the AssignmentsController are triggered

These get called via the javascript frontend. The starting point is the AssignButton component: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/components/students/assign_button.jsx#L284

Submitting the input for a new assignment triggers the `assign` function of that component, which does some validation, then triggers a confirmation dialog, which triggers the `onConfirm` function, which triggers `ServerActions.addAssignment`, which triggers `API.createAssignment`, which does a POST to `/assignments.json`, which gets routed (via `routes.rb`) to the create method of AssignmentsController.

**Comment by sejalkhatri** [comment]
Control Flow: 
/assets/javascripts/components/students/assign_button.jsx handles the Assign button submit action and calls assign() method onSubmit which updates the store and calls for a server action.

From /javascripts/utils/api.js createAssignment method is called which redirects control to assignments_controller, where lib/assignment_manager.rb is imported and used to update the assignment model.
