### ISSUE TITLE
Horizontal overflow when an instructor tries to create an available article

### ISSUE THREAD

**Issue by arun1595** [WikiEducationFoundation/WikiEduDashboard#1205]
## Steps to reproduce:

1. Login as an instructor
2. Create a course and try to add a new available article.
3. You can find the popup causing a horizontal overflow.

### Screenshot

![overflow](https://cloud.githubusercontent.com/assets/7039523/23436802/d95a2764-fe31-11e6-85a4-7caacf2b8531.png)

**Comment by coleworsley** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by ragesoss** [comment]
@coleworsley go for it! Let me know if I can help with anything.
