### ISSUE TITLE
Update how Article #rating data is imported: use the new PageAssessments API

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1208]
Currently, `RatingImporter` gets article ratings by calling `WikiApi.get_article_ratings`, fetching the text of the talk page and using regular expressions (in `ArticleClassExtractor`) to figure out what the rating of an article is.

This only works for English Wikipedia, and is potentially subject to error if the format of common WikiProject templates changes.

The new PageAssessements API provides structured data about article ratings, is available for all languages: https://en.wikipedia.org/w/api.php?action=query&prop=pageassessments&titles=Selfie

`RatingImporter` and related code should be rewritten to use this new API, so that rating data can be imported from every language version of Wikipedia (and Wikivoyage, but it looks like not other projects).

**Comment by keer25** [comment]
PageAssessments API also works only only for English Wikipedia (I referred to [here](https://meta.wikimedia.org/wiki/Community_Tech/PageAssessments). But it has structured data so it will be good to update to PageAssessments API

**Comment by ragesoss** [comment]
Done via #1245
