### ISSUE TITLE
Invalid course URL can be created by putting only whitespace for school/institution

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1219]
There should be some validation on both the frontend in the course creation screen and on the `Course` model.

**Comment by medhabansal** [comment]
@ragesoss Is it okay if we disallow leading whitespaces in the front-end check?

**Comment by medhabansal** [comment]
@ragesoss Requesting review: [pull request](https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1233)

**Comment by ragesoss** [comment]
> @ragesoss Is it okay if we disallow leading whitespaces in the front-end check?

Yes, that sounds reasonable.

**Comment by medhabansal** [comment]
@ragesoss The edit-update flow is allowing the title to be edited to accept blank values, and creating as well as updating invalid slug. No error is being displayed in this case(errors encountered earlier were from courses with bad first slugs). 
![edit_page_screenshot](https://cloud.githubusercontent.com/assets/10144999/24325235/4227793c-118c-11e7-9e5e-61c67e308cdc.jpg)

Should I create a PR with the appropriate changes?
