### ISSUE TITLE
Cannot use mouse to position cursor in timeline block on Firefox

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#122]
On Firefox (testing on Linux and Windows), I cannot use the mouse to click a specific place in the text area of a timeline block. It seems like the drag-and-drop functionality is overriding it.

**Comment by ntdb** [comment]
This is caused by a [known bug in Firefox](http://stackoverflow.com/questions/21680363/prevent-drag-event-to-interfere-with-input-elements-in-firefox-using-html5-drag). Temporary, dirty workaround to follow.
