### ISSUE TITLE
If user submits a program via the CourseCreator with an invalid wiki, fixing the problem and resubmitting does not work

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1226]
Submitting an invalid wiki should be caught on the frontend and it should put the course creator back into a state where it can be submitted again.

**Comment by ragesoss** [comment]
To replicate this bug:
* In config/application.yml set default_course_type to 'GenericCourse'
* Log in and Click 'Create a New Program' from the home page, then 'Create New Program'
* Fill out the form, and enter an invalid langauge code (like 'abcd') in the Home Language field
* Submit, which will trigger an error notification
* Replace the language code with a valid one (like 'es') and click Submit again
* The page will freeze, and the course will not be created

**Comment by ragesoss** [comment]
One good fix for this, which would also address cases like users typing in `wikipédia` (which causes an error instead of being interpreted as 'wikipedia'), would be to change the text entry to a picklist of available projects.

**Comment by chicocvenancio** [comment]
I ran into this as I incorrectly interpreted "primary language" as including the language variant.
For me it did not even show an error notification, only noticed what the problem was through developer tools.

**Comment by arun1595** [comment]
I haven't been able to spend time on this. Anyone interested in tackling this issue can work on top off my [PR](https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1250) or start from scratch.
