### ISSUE TITLE
Available Articles should be sorted alphabetically

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1244]
The 'Available Articles' section shows up on the Articles tab of a course; instructors can add articles that are available to the students to choose as their assignments.

Currently, the list is ordered arbitrarily, probably by assignment id. It ought to be sorted alphabetically by default.

The place to start is the AvailableArticles component: `app/assets/javascripts/components/articles/available_articles.jsx`.

**Comment by lopezabegaillyn** [comment]
Hi @ragesoss, can you take a look if this issue is already solved? Thanks.

**Comment by Sharan-ram** [comment]
@ragesoss i would like to work on this issue if its still open

**Comment by ragesoss** [comment]
Please do! Let me know if you have any questions.

**Comment by testa19** [comment]
@ragesoss please see PR.
are there any tests needed? (i'm not so good at testing)

**Comment by ragesoss** [comment]
Fix with that commit.
