### ISSUE TITLE
Users should be able to cycle through diffs in the Activity view

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1286]
A 'Next' button and/or keyboard shortcut would make this list of diffs much more useful.

**Comment by Kachulio1** [comment]
I would love to take this.

**Comment by ragesoss** [comment]
For more context, here's a typical activity page for a course: https://dashboard.wikiedu.org/courses/University_of_Oklahoma/Cold_War_Science_(Spring_2018)/activity

Clicking the +/- button in the last column of one of the table rows will open up the DiffViewer component. To view another diff, you currently have to close the DiffViewer and then click a different row to reopen it with the new diff.

The idea here is to make to more efficient to go through each of the diffs in the Activity tab quickly.

**Comment by ragesoss** [comment]
To test this locally, you need a course with some imported data. See https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/user_roles.md#populating-a-course-with-data
