### ISSUE TITLE
500 error from directory permissions after deployment to staging

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#129]
After I deployed the latest version with new i18n hooks for javascript, visiting the staging server gave this error:

Stacktrace (most recent call first):

  fileutils.rb:250:in `mkdir'
    Dir.mkdir path
  fileutils.rb:250:in `fu_mkdir'
    Dir.mkdir path
  fileutils.rb:224:in `block (2 levels) in mkdir_p'
    fu_mkdir dir, options[:mode]
  fileutils.rb:222:in `reverse_each'
    stack.reverse_each do |dir|
  fileutils.rb:222:in `block in mkdir_p'
    stack.reverse_each do |dir|
  fileutils.rb:208:in `each'
    list.map {|path| remove_tailing_slash(path)}.each do |path|
  fileutils.rb:208:in `mkdir_p'
    list.map {|path| remove_tailing_slash(path)}.each do |path|
  i18n/js/middleware.rb:35:in `save_cache'
    FileUtils.mkdir_p(cache_dir) unless File.exists?(cache_dir)
  i18n/js/middleware.rb:63:in `verify_locale_files!'
    save_cache(new_cache)
  i18n/js/middleware.rb:10:in `call'
    verify_locale_files!
  warden/manager.rb:35:in `block in call'
    @app.call(env)
  warden/manager.rb:34:in `catch'
    result = catch(:warden) do
  action_dispatch/middleware/request_id.rb:21:in `call'
    @app.call(env).tap { |_status, headers, _body|
headers["X-Request-Id"] = env["action_dispatch.request_id"] }
  rack/methodoverride.rb:21:in `call'
    @app.call(env)
  rack/runtime.rb:17:in `call'
    status, headers, body = @app.call(env)
  active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
    response = @app.call(env)
  rack/sendfile.rb:112:in `call'
    status, headers, body = @app.call(env)
  raven/integrations/rack.rb:54:in `call'
    response = @app.call(env)
  rails/engine.rb:514:in `call'
    app.call(env)
  rails/application.rb:144:in `call'
    super(env)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in
`process_request'
    status, headers, body = @app.call(env)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:141:in
`accept_and_process_next_request'
    process_request(headers, connection, socket_wrapper, @protocol == :http)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:109:in
`main_loop'
    hijacked = accept_and_process_next_request(socket_wrapper, channel, buffer)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler.rb:455:in
`block (3 levels) in start_threads'
    handler.main_loop(set_initialization_state_to_true)

I bypassed the problem by creating the requested directory and doing chmod 777 on staging, but I assume the same issue would happen again every time there's a new release.

**Comment by ntdb** [comment]
It appears that the directory creation is not overwritten on deploy. The parallel problem (`Permission denied @ rb_sysopen - public/javascripts/i18n.js`) has been resolved by moving the generation of i18n.js translation files out of the application scope and into the development environment. This means we have to regenerate the i18n.js files whenever they're changed but keeps Capistrano from needing to modify the file system on deploy.

We'll need to reproduce the steps mentioned above (creating the directory and doing a chmod 777 or similar) for production before we deploy this evening.
