### ISSUE TITLE
Expanding the length of the list of activities (Activity tab)

### ISSUE THREAD

**Issue by JoalpeBrasil** [WikiEducationFoundation/WikiEduDashboard#1295]
On the P&E Dashboard, the list of activities only shows last ~50 edits; the possibility to show more than that should be available, as cohorts might be much larger than 50 students

**Comment by ragesoss** [comment]
Having an option to load a larger number of activities would be pretty easy to implement; just add a button the Activity view, and pass a parameter for the max activities to fetch... more or less.

**Comment by mauditecandela** [comment]
Hi! I have been having a look to this issue. Where's the activity view rendered? Do you mean the activity_table.jsx? I am having problems finding the limit of rows shown. Any hint is super welcome! Thanks a lot :)

**Comment by ragesoss** [comment]
@mauditecandela in broad strokes, the data flow is:
* user navigates to the activity tab, which renders RevisionHandler component
* as it mounts, that component initiates fetching the revisions
* api.js makes a call to the course_controller show revisions endpoint, which renders `app/views/courses/revisions.json.jbuilder`. That's the file that sets the limit of 50.
* the frontend receives the set of revisions and puts it in RevisionStore
* the RevisionsList component renders all the revisions in the store.

**Comment by mauditecandela** [comment]
@ragesoss thanks a lot for the explanation. 

I was having a look and I have some questions regarding this:
- Would you render all the list of revisions from the server and then show only 50 in the UI? Or add different calls based on user interaction?  I don't know how many activity could be displayed if I don't limit it from the model directly, and if that would slow down the application. What do you think?
- I also had a look to both /ui_actions.js and /server_actions.js. TBH, I don't have a very clear overview yet on how to create new actions. I will continue reading about Flux, but if you have any hint that could help me it would be very appreciated. 

Of course if you think this is not the right approach let me know :) And thanks again!

**Comment by ragesoss** [comment]
@mauditecandela I think the way to handle it will be something like:
* add a 'limit' param to the controller, and use that (with a default of 50) to generate the json list.
* add some kind of UI for using the limit. Have a look at `recent_edits_handler.jsx` for an example of something similar (a check box that affects the 'scoped' param on a query).

The component itself should be able to continue with the current behavior of rendering every revision that is in the store; for both performance and simplicity, we I think it'll make sense for the limit to continue to be handled on the server, in the query that pulls the records from the database.

**Comment by mauditecandela** [comment]
PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1446

**Comment by mauditecandela** [comment]
@ragesoss new commit with some changes:
- I limited the set_limit function to revisions endpoint in the courses controller
- I relocated the server_actions and api functions more accordingly

Right now this fix only shows 50 or 100 activities. I am thinking of generating a +50 show_more, so each time the button is clicked would show 50+ activities until all of them are shown. What do you think?

**Comment by ragesoss** [comment]
@mauditecandela Good idea. I think increasing by 100 or 200 each time make sense (including the first time you click 'more'); the use case is for very active courses that may have a lot more than 100 recent edits.
