### ISSUE TITLE
Numbers always sort to the top for course names

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#13]
If I sort the list of course names either ascending *or* descending, the course that starts with a number is always at the top. I would expect that reversing the sort order would reverse the entire list.

**Comment by ragesoss** [comment]
Nate Bailey on January 15, 2015 at 6:01 PM:

"The algorithm built into the library we're using for sorting always places numerical values on top (123ABC -> 321CBA). I can change this but it will require replacing/digging into the algorithms so I'll save it for later."

**Comment by ntdb** [comment]
I found another kind soul who did the algorithm work for me, just had to integrate his changes.

**Comment by ragesoss** [comment]
Sweeeet.
