### ISSUE TITLE
Users don't expect 'back' button in browser to immediately exit the wizard

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#131]
If I'm in the middle of the wizard, the back button will immediately take me to the previous page, and my progress through the wizard will be lost. A better behavior would be to take me one step back in the wizard.

**Comment by ntdb** [comment]
I spent a little bit of time on this. I found a good solution that is blocked by an existing issue with React-Router (https://github.com/rackt/react-router/issues/1046). Will revisit when resolved.

**Comment by ragesoss** [comment]
In the meantime, can we throw up a confirmation alert to give the user a chance to not abandon their progress through the wizard?

**Comment by ntdb** [comment]
@ragesoss The issue is that I'm unable to reliably block react-router from executing the action to move the browser back. This means I can't hijack the event or even pause it to give a confirmation. I'll give this another look later today if I can to see if I can come up with an interim solution.

**Comment by ragesoss** [comment]
Okay. It's not that big of a deal, and worst case we can just let the user know ahead of time that this will happen.

-Sage

**Comment by ntdb** [comment]
Just to clarify, this issue has to do with a browser's back button, not part of our UI.

**Comment by AmitJoki** [comment]
Is this issue still unresolved? If yes, I'd like to work on it.

**Comment by ragesoss** [comment]
@AmitJoki Yes, this is still unresolved. I'm not sure what it will take to fix it, but it should be possible with the version of React Router that we use, I think.

**Comment by AmitJoki** [comment]
@ragesoss I was thinking of using PushState API and using this, we could, I think also persist the form data across navigation.

**Comment by ragesoss** [comment]
@AmitJoki Cool. I don't know anything about PushState, but feel free to give it a try. If you can find a solution to this, it will definitely be appreciated by users of the app.

**Comment by AmitJoki** [comment]
Cool. Will start working on it.

**Comment by ragesoss** [comment]
Set your default course type to `ClassroomProgramCourse` in application.yml. Then when you create a new course, you'll go from course creator directly to the assignment wizard (`[course path]/timeline/wizard`, which has a number of steps. If you press back on your browser (as opposed to 'Previous' button on the screen) then you'll go back to `/course_creator` and it will be blank.

**Comment by AmitJoki** [comment]
@ragesoss I did the changes in `application.yml`. I now, don't have the login option and every attempt at creating a course returns me back to the index page in the following URL: `http://localhost:3000/course_creator?campaign_slug=game_of_thrones`

**Comment by ragesoss** [comment]
Sounds like broken javascript.

**Comment by AmitJoki** [comment]
Yeah, it shows: `Cannot find module "react-confetti"` may be I should run `yarn` again?

**Comment by AmitJoki** [comment]
@psinghal20 Yeah. I just ran it. May be there should be a way to display a breaking changes changelog when we pull in from the master so we can know what's changed and what's to be done. But I guess there's no way to do that?

**Comment by psinghal20** [comment]
I guess we can but will require regular maintenance, what are your views @ragesos?

**Comment by AmitJoki** [comment]
Maintaining a `CHANGELOG.md` for breaking changes would be a start. People could look into the `changelog.md` everytime they pull in from upstream and be up to date with what's transpired.

**Comment by psinghal20** [comment]
Well but then in our case the change log will only end up having changes in the dependencies we use. The changelog is meant for breaking changes between each version of the project. Currently, we don't release versions or milestones for our project and it is in continuous development and being deployed on production simultaneously. A changelog, in my opinion, is not something we need.
