### ISSUE TITLE
Training Libraries index should have links directly to individual trainings

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1330]
It currently names them, but does not link to them.

**Comment by vdineva** [comment]
Created a PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1336
Attaching a screenshot of before and after. One thing I wasn't quite sure about is if the default underline for the link should be there and about the spacing between the 'Instructors' and 'Students' and the block below them. I'd be more than happy to address any visual changes
BEFORE
![1330-before](https://user-images.githubusercontent.com/791418/28571253-ffa5bafe-710f-11e7-95d6-4f46d6647d12.png)
AFTER:
![1330-after](https://user-images.githubusercontent.com/791418/28571258-035d8172-7110-11e7-8201-5e39f9011aec.png)

**Comment by ragesoss** [comment]
@vdineva Thanks! I think the newly introduced spacing between the header and the list of modules should be removed. The link styling looks good.
