### ISSUE TITLE
In Chrome, out of order points in Students Taught graph

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1341]
On Chrome (but not Firefox, or Safari), this page shows a glitchy Students Taught graph: https://dashboard.wikiedu.org/users/Amyc29

It looks like the points are not in the normal order, so the line connecting them zips back and forth.

![out of order](https://user-images.githubusercontent.com/848483/28887098-c349c5ac-7770-11e7-899e-9177dbc9a33f.png)

Any ideas, @sejalkhatri?

**Comment by sejalkhatri** [comment]
I'll look into it.

**Comment by ragesoss** [comment]
Looks like this got fixed, possibly via the Vega upgrade.
