### ISSUE TITLE
Convert remaining McFly Flux actions/stores to Redux

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1342]
We currently have a mix of older McFly-based Flux stores (in `app/assets/javascripts/store`) and a Redux store built from reducers (in `app/assets/javascripts/reducers`). We want to transition to using Redux for everything.

The easier ones are the Flux stores that don't use the generic StockStore as the basis. `ConfirmationStore`, `DidYouKnowStore`, `UserCoursesStore`, and some others are among the easier ones. `CourseStore` is a non-StockStore one that is fairly complex, especially because it receives so many different actions. Ultimately, with StockStore, I think we should implement each of the specific stores individually, with only the explicit actions required, rather than trying to re-implement the generic model store like StockStore does.

**Comment by jyoti0208** [comment]
@ragesoss I would like to work on this.

**Comment by ragesoss** [comment]
@jyoti0208 cool. Once you've poked around a bit, you should note which one(s) you're working on. One at a time is probably best.

**Comment by jyoti0208** [comment]
@ragesoss I have to convert all McFly-based Flux stores to the redux store?

**Comment by ragesoss** [comment]
@jyoti0208 that's the ultimate goal, but it can be done one store at a time.

**Comment by KarmaHater** [comment]
@jyoti0208 @ragesoss Could I also work on this? Maybe, I start with `DidYouKnowStore` ?

**Comment by KarmaHater** [comment]
@jyoti0208 Here is the pull request for the DidYouKnow reducer. 

https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1434

I will move onto `UserCoursesStore` I expect to be done by October 11, 2017 :)

**Comment by KarmaHater** [comment]
I just finish UserCourseStore.

@ragesoss 

https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1448

**Comment by ragesoss** [comment]
Done!
