### ISSUE TITLE
DiffViewer does not work for Wikidata

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1347]
The button should not be shown for Wikidata items.

**Comment by ragesoss** [comment]
The button no longer shows up for Wikidata items. Nicer would be for the DiffViewer to work for them.

**Comment by heysusgarcia** [comment]
If no one has started on this I can take it! I think I know what I need to do to get the DiffViewer to work for wikidata.
