### ISSUE TITLE
on-wiki course pages should include course stats

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1350]
Although they would go out of date quickly, it would still make sense to mirror the basis course stats to the wiki versions.

This would require:
* some on-wiki template work to display the stats
* adjustments to `WikiCourseOutput` to include the stats
* an action button on course pages to manually trigger a wiki update without any other changes to the course

**Comment by mit-27** [comment]
Hello @ragesoss , I would like to work on this issue could you send me slack invite on meetsuthar64@gmail.com . Thank you

**Comment by Poison-Iveey** [comment]
Hi @ragesoss , if this issue is still open, I would like to work on it. Can you elaborate on how I can go about to reproduce the desired outcome?

**Comment by ragesoss** [comment]
@Poison-Iveey hmm... now that I return to this issue 7 years later, I think I'd prefer not to add this feature to the codebase.

**Comment by Poison-Iveey** [comment]
Okay then
