### ISSUE TITLE
Campaign 'Articles' tab should show more detail about each article

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1360]
In particular, characters added — and sorting by that value — would be very nice.

**Comment by testa19** [comment]
Hi
There is same feature implemented on Course's Articles page. See example: https://dashboard.wikiedu.org/courses/Ohio_University/Writing_for_Biologists_(Spring_2017)/articles

Would it be better to reuse the same logic(? or React code)?
Or is there anything against that?

**Comment by ragesoss** [comment]
@testa19 it would be rather more complicated to do it in React, because unlike the course pages, the Campaign pages don't currently use any React. It would be nice to port them to React at some point, but it's a fair bit of work.

**Comment by testa19** [comment]
Sage, is there some kind of _articles_cources_ relation is needed for Compaign model (_like has_many :articles, -> { distinct }, through: :courses_) to get the view and characters count.
Or we should just use `article.articles_courses.where(course_id: @campaign.courses)`

`       - @campaign.articles.includes(:wiki).order(:title).each do |article|`
`          %tr
              %td.title
                = link_to full_title(article), article_url(article)
              %td
                = article.articles_courses.where(course_id: @campaign.courses).sum(&:character_sum)
              %td
                = article.articles_courses.where(course_id: @campaign.courses).sum(&:view_count)
              %td
                %small
                  = "#{article.wiki.language}.#{article.wiki.project}" `
   ?

**Comment by ragesoss** [comment]
@testa19 very good question!

I think adding an articles_courses relation for Campaign would make the most sense. This page may have very large numbers of articles, so it's going to be important to avoid introducing any N+1 queries.

So you probably want to add a Campaign.articles_courses scope, and do something like @campaign.articles_courses.includes(:articles). Then you can rewrite that view to iterate over the articles_courses, but each AC will already have the Article record loaded without any additional queries.

**Comment by testa19** [comment]
Thanks for advice!
Now there is `@campaign.articles_courses.includes(article: :wiki).order('articles.title')` for querying.

I have another question:
I've madde some changes to campaign JS ('/assets/javascripts/') for sorting on the page to work but it seems like it is not loading (js from public is (?)). 
There could be an issue of me using ubuntu VM on Windows host with shared folder and some guard/smth-else is not working properly.
Or is there some asset related task i should run to update the script?

**Comment by testa19** [comment]
Ok, seems i can get where the issue is: i had used `gulp build` at project setup because of `gulp` returned an error.
Will dig a bit in this derection.

**Comment by testa19** [comment]
Hi @ragesoss 
I think i've finished it
Please take a look https://github.com/testa19/WikiEduDashboard/commit/c04caffeb94387e8fe50a6e1c2105d222e376a17

**Comment by ragesoss** [comment]
@testa19 cool! please open a pull request, and make sure the CI build passes.
