### ISSUE TITLE
Slashes in course slug are not handled properly

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#137]
If I use a school with a slash in it, this results in an inaccessible course page.

**Comment by ntdb** [comment]
We're pushing the limits of our ability to intelligently parse routes already, supporting slashes in any part of the course slug will be very difficult to maintain. How essential is this?

**Comment by ragesoss** [comment]
It's not essential at all. We can make / an illegal character. We need to delete the broken course in production too.

**Comment by ntdb** [comment]
Sounds good. Will leave this open until we get some proper validation on course creation for invalid characters.

**Comment by ntdb** [comment]
I'll go ahead and mark this as closed. See #172 for further validation improvements.
