### ISSUE TITLE
When adding a new instructor/facilitator, user should be able to enter an optional 'role' field

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1376]
The role, if present, would show up along with each name. This way, we can tell whether someone is participating as a TA, librarian, co-instructor, or some other role, without needing to email them to find out.

We'll need need to add a field to `CoursesUsers`, allow the extra field in `JoinCourse` and adjust the frontend as well.

**Comment by bcb37** [comment]
This is something I might be able to tackle. It would require a database migration, no?
Also, should the possible values for the 'role' field be constrained? And the adjustments to the front end would just involve displaying the role with other user info for instructors/facilitators (nothing like the ability to search/group/refine the definition per role, etc.)?

This seems like a relatively straightforward task, but I am a newcomer. Is there a reason I might not want to take this on?

**Comment by ragesoss** [comment]
@bcb37 yes, it will require a migration. I think leaving it unconstrained is what we want; it's main purpose is so that we can easily tell who is doing what in cases where there is, eg, an instructor and a TA, but the exact titles and use cases will vary too widely, and we don't need to do anything programmatically with that data except display it.

The frontend part would involve both displaying the role and having a way for users to input the role when they are adding another non-student to the course. It's *relatively* straightforward, but it touches both Rails and React code and will require wrapping your head around the data flow for both of those.

**Comment by bcb37** [comment]
Well I can make a branch and give it a shot. I'm not a complete stranger to React or Rails.

**Comment by ragesoss** [comment]
@bcb37 great! please ask if you get stuck or have questions.

**Comment by bcb37** [comment]
Hi, I'm making my way through this and I've noticed that there already exists a field on `CoursesUsers` called 'role'. It appears to be an integer that corresponds to one of "Visitor", "Student", "Instructor", "Campus Volunteer", etc. It doesn't seem to have been added recently and doesn't quite correspond to the feature described above, since its value determines the user's access to functions. The feature under discussion here would just be a descriptive text field, right? Would it make sense to try to come up with a different name for it, or am I just looking in the completely wrong place?

**Comment by ragesoss** [comment]
@bcb37 you're right. Maybe call the new field `role_description`.

**Comment by bcb37** [comment]
Ok, if I understand this, there are only two page types that will be affected: 

- The course pages for all courses (Where, under __Details__, there's a list of instructors - editable if you're an admin) - in fact, it looks like you can add instructors, but not ever remove them, so maybe there's a place I didn't see?
- The user pages for each user, under the __Course Details__ for each course, where it will be displayed but not be editable.

And the data in question will be a text field in the `CoursesUsers` table.

Anything missing from this?

**Comment by ragesoss** [comment]
You can remove instructors also, you just have to first click the 'plus' button as if you were adding one, and then a list of removable ones will appear.

The user page for each user need not be changed, although it could be.

One other thing... after conversations with my team today, we realized that we also want to prompt for full name alongside role. (Name is already in the CoursesUsers table.) But that could be dealt with in a separate issue.

**Comment by ragesoss** [comment]
@bcb37 this issue has become a high priority for my team, so I'm planning to take it on early next week. If you've made any headway on it, you can open and WIP pull request and I'll see if I can incorporate it.

**Comment by ragesoss** [comment]
Resolved with 6be5f9d4eba67c81303c47b9e27a8be41d65cfae
