### ISSUE TITLE
For Classroom Program CourseCreator, form should ask for class level

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1377]
We want to know whether a course is introductory, advanced undergraduate, or graduate-level, so that this info can be automatically pushed to Salesforce.

**Comment by alpha721** [comment]
I would like to take up the issue if no ones working on it.

**Comment by alpha721** [comment]
I would like to take up the issue if no ones working on it.
@ragesoss

**Comment by ragesoss** [comment]
Go for it.

**Comment by mercykinoti** [comment]
@ragesoss I'm interested in working on this issue

**Comment by ragesoss** [comment]
Cool. Looks like alpha721 has moved on.

**Comment by ragesoss** [comment]
Done with bfc68484b1a1619a5a9191a92d121406f3c064ff and subsequent commits.
