### ISSUE TITLE
Many buttons are not links, making them inaccessible to screen readers

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#138]
A bunch of the interface buttons (but not all) are `<div>` instead of `<a>`, so they are not clickable via screen reader. These include "Create my Course!", all the wizard options, Edit on the timeline and Overview and elsewhere, and the + buttons.

**Comment by ntdb** [comment]
Used semantic `<button>` tags for this. [For reference.](http://formidablelabs.com/blog/2014/05/08/anchors-buttons-and-accessibility/)

**Comment by ragesoss** [comment]
The wizard options are still not clickable via screen reader.
