### ISSUE TITLE
For courses with no passcode, 'Join' button in Available Actions should not request a passcode

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1380]
This means we'll need to let the frontend know that the password is blank, in the cases where the password has been removed.

**Comment by ihsavru** [comment]
Hi! I am a newcomer and would like to work on this issue.

**Comment by ragesoss** [comment]
Hi @ihsavru! Great. This is a relatively straightfoward change to describe, but it will probably touch both the server and client code in a few places, so don't hesitate to ask if you have any questions or want any clarification about how the system works.

**Comment by ihsavru** [comment]
@ragesoss I am having trouble setting it up locally on my machine. Is this the right place to ask :sweat_smile: ?

**Comment by ragesoss** [comment]
@ihsavru You can post specific problems you're having with the setup process here: https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/1351

I also sent you a slack invite where you can post any questions you have; a few folks there can probably help out.

**Comment by alpha721** [comment]
@ragesoss I figured that the some changes have to be made in `self_enrollment_controller.rb` but I am not able to find the code which requests the passcode on the front end. Can you give a slight hint as to where I should be looking.

**Comment by ragesoss** [comment]
The frontend does not currently know anything about the password (unless the user is an admin or instructor). I think the way to handle it will be to add an attribute to send through course.json in the case where there is no password: `app/views/courses/course.json.jbuilder`. This is the main course object that gets passed through most of the frontend.

Set passcode to empty string if the course password is not present, and then use that on the frontend in the join course action flow.

**Comment by alpha721** [comment]
` # If course has no passcode set, treat any submission as valid.
    return true if @course.passcode.blank?`
should this still hold?

**Comment by ragesoss** [comment]
I think so. Where is that from?

**Comment by alpha721** [comment]
` def passcode_valid?
    # If course has no passcode set, treat any submission as valid.
    return true if @course.passcode.blank?
    params[:passcode] == @course.passcode
  end`
its from `self_enrollment_controller.rb`.

**Comment by ragesoss** [comment]
Yeah, that should be fine still. Enrolling without a passcode works, it's just the 'Join course' action modal that doesn't handle it elegantly because it doesn't know that the course requires no password.

**Comment by alpha721** [comment]
![wiki](https://user-images.githubusercontent.com/18638840/30615999-5ef5fdaa-9dae-11e7-8a4e-2b01ca5adf93.png)

**Comment by ragesoss** [comment]
change the course type to 'Generic Course', save, and refresh the page. Then you'll be allowed to remove the passcode.

**Comment by mauditecandela** [comment]
I would like to pick this as my next issue. ^_^

**Comment by ragesoss** [comment]
Done.
