### ISSUE TITLE
Plain text versions of alert emails have incorrect links if apostrophe is present

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1383]
For example, the alert email for a course like this one: https://dashboard.wikiedu.org/courses/Queen's_University/Critical_Appraisal,_Research_and_Lifelong_Learning_(Fall_Term_1)

The link in plain text ends up being just https://dashboard.wikiedu.org/courses/Queen even though the one in html works fine.

**Comment by asmigos** [comment]
It could be resolved by using `%27` instead of the apostrophe ( ' ) in the link .

**Comment by asmigos** [comment]
It could be resolved by using %27 in place of the apostrophe `'` in the link

**Comment by asmigos** [comment]
It could be resolved by using `27%` in place of the apostrophe `'` in the link .

**Comment by asmigos** [comment]
should i work on it ?

**Comment by ragesoss** [comment]
Yeah, some kind of necessary url encoding is not happening in the plain-text emails. Feel free to work on this @asmigos. A good place to start will be the mail previews, 'localhost:3000/rails/mailers', which come from `/spec/mailers/previews`.

**Comment by heysusgarcia** [comment]
Hi @asmigos are you going to take this issue? Otherwise, I'd be happy to work on it.

**Comment by asmigos** [comment]
Yeah @heysusgarcia i am taking this issue .

**Comment by srish** [comment]
@ragesoss If no one is currently working on this issue, then feel free to assign it to me. Also, is it a newcomer-friendly task to start with on this project?

**Comment by ragesoss** [comment]
This was a bug in the `premailer` gem: https://github.com/premailer/premailer/issues/375

We've updated `premailer`, so it's fixed.
