### ISSUE TITLE
Create `SpecialUsers` presenter to fetch users in special system-wide roles

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1385]
Currently, we use ENV variables to identify some specific user roles like classroom_program_manager who receive certain types of emails.

Instead of using ENV, those usernames should be set in a `Setting` record, and accessed via a new `SpecialUsers` class. Then all the places that currently use ENV to get a specific user can use that instead.

(Moving that config data to the `Setting` record will pave the way to create a UI for changing those users.)

**Comment by alpha721** [comment]
Hi, I am a first time contributer.
I would like to take up this issue if no one else is working on it.

**Comment by BellPepperLab** [comment]
Hi ragesoss,

Can it be achieved by adding a "role" column to the user table and then creating an ENUM with all user roles in the user model.

**Comment by ragesoss** [comment]
There are many possible ways, but in this case the setting more represents a system-wide setting rather than a trait for a particular user. The idea here is to refactor the way configuration settings are accessed to move them from the appllcation.yml into a `Setting` record in the database. The benefits includes: 1. no changes to the database schema are necessary, and 2: because these are system-wide settings, they will probably make more sense and be easier to deal with in the long run if they get treated as `Setting` records.

**Comment by testa19** [comment]
@ragesoss hi
So is it should be like this:

./presenters/special_user
```
class SpecialUser
  def self.classroom_program_manager
    User.find(Setting.first.value[:classroom_program_manager])
  end
end
```

Somewhere in code:
`staffer = SpecialUser.classroom_program_manager`
?

Second question:
How are settings stored in `Settings` table? What are the contents of the `key` property?

**Comment by ragesoss** [comment]
The `key` property is basically the name of the setting, so in this case, it might be 'special_users', which you would use to find it. And then the `value` would be a hash of all the roles and usernames, so something like 
```ruby
{ classroom_program_manager: 'Username 1', another_special_user_role: 'Username 2' }
```

**Comment by testa19** [comment]
@ragesoss So would there be a Settings record and searching would be:
`Setting.find_by(key: :special_users).value`

And should there be a presenter SpecialUser:
```
class SpecialUser
  def self.classroom_program_manager
    username = Setting.find_by(key: :special_users).value[classroom_program_manager]
    User.find_by(username: username)
  end
end
```

Or is there some kind of god practise of dealing with these tipes of tasks?

**Comment by ragesoss** [comment]
That looks like the right approach, except that 'key' is a string, so do 'special_users' instead. Probably it should also automatically create that setting if it doesn't exist. So 'find_or_create_by(key: 'special_users').
