### ISSUE TITLE
BlockedEditAlert should include block data

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1387]
Currently we send the block data that we get from MediaWiki through Raven to Sentry, but we don't include it in the BlockedEditAlert that we email to Wiki Ed staff.

It would be very useful to save that data on the Alert record (requires a new db field) and send it in the email. That way the email would include enough info for someone to get the block sorted out. This is particularly important for when the dashboard's IP address gets blocked because of a student with a bad username; the user affected by the block will not necessarily be the one who was actually blocked, and it's hard to track down who was blocked without that block data.

**Comment by mattwarren10** [comment]
What file(s) is the block data that we get from MediaWiki referenced? What would you want the new attribute in the `alerts` table to be called? `block_data`?

**Comment by ragesoss** [comment]
Nothing so specific as `block_data`, since the Alert table holds all the different alert types. Maybe `details`, as a serialized Hash.
