### ISSUE TITLE
Cannot add users to a course if they are not in our database already

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#139]
We want to be able to add any existing Wikipedia user to a course, even if they aren't yet in our system.

**Comment by ragesoss** [comment]
I suggest that we disable instructors/admins being able to enroll other users, for the time being. In addition to this bug, it is also confusing usability-wise. Instructors will try to add users by their real names, not realizing that the intention is to add Wikipedia user accounts.

**Comment by ntdb** [comment]
Related to #128

**Comment by ntdb** [comment]
Adding a wiki_id to a course which is not already in our database should trigger a Replica API call to get the info we need for that user's account.

**Comment by ragesoss** [comment]
Fixed with de87d692e3f7df24194f08d051c59c389db36e01
