### ISSUE TITLE
Real name field can have leading/trailing whitespace

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1391]
This should be removed for consistency.

Real names are set via the /onboarding flow.

**Comment by testa19** [comment]
Does adding simple before save callback to User model is ment?
before_save do
  self.real_name = self.real_name.squish
end

**Comment by ragesoss** [comment]
I would rather sanitize it at the controller level instead of adding a callback. Empty is not the problem; it's things like ` My name `.

**Comment by asmigos** [comment]
Hello, 
I am new-comer,
This could be resolved by using `.trim` method

**Comment by testa19** [comment]
@ragesoss so is it just simple private method for Onboarding controller like below that is called by  onboard action:
```
validate_params
**sanitize_real_name**
@user = current_user
set_new_permissions
```
```
def sanitize_real_name
  params[:real_name] = params[:real_name].squish
end
```
?

**Comment by ragesoss** [comment]
Yes, something like that should work.
