### ISSUE TITLE
Update ArticleViewer to use whocolor for all available languages

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1394]
The whocolor API now supports Basque (`eu`) as well as English Wikipedia. `ArticleViewer` should work for Basque as well, in a way that will be easy to extend to more languages as the number supported by whocolor grows.

----
https://api.wikiwho.net/

**Comment by jyoti0208** [comment]
I am working on implementing this feature.

**Comment by jyoti0208** [comment]
I am not able to find ArtcleViewer on any page.
I have created a dummy campaign on my local as `http://localhost:3000/courses/Wiki/React_Training_(first)/articles`
Also, there is article_viewer.jsx in common, So if I modify anything to this file which page will get change?

**Comment by ragesoss** [comment]
@jyoti0208 Have you done the steps of populating the course with data? https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/user_roles.md

**Comment by jyoti0208** [comment]
Yes, I have 2 new users as participants and run the update routine.
Also, I am getting this page `http://localhost:3000/courses/Wiki/React_Training_(first)/articles`
 Is this the Article viewer page?

**Comment by ragesoss** [comment]
@jyoti0208 I just noticed that now German and Turkish are available too. :)

**Comment by ragesoss** [comment]
All available languages are set now, and it should be trivial to add more as they are available.
