### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1395]
1. redirect /404 and /500 to the prettier error pages, like this: https://gist.github.com/scaffeinate/651f57ef8aa74c115ed6c5cd0fbba440#file-routes-rb

2. Move error rescues from ApplicationController to a RescueControllerErrors module

We currently have a few rescues in the ApplicationController. These should be moved into a module; see the technique used in `Errors::RescueDevelopmentErrors`, and for more background see https://medium.com/rails-ember-beyond/error-handling-in-rails-the-modular-way-9afcddd2fe1b

That will lay the groundwork for customizing the errors from different situations so that we can provide better error messages, especially for json errors.

3. Add different behaviors for html vs json for all of the error situations currently in ApplicationController

Replace most of the cases where `InvalidAuthenticityToken` is raised with a custom error. The app should provide appropriate messages, depending on the specific problem, whether not being logged in, or not being admin, or not being an instructor, or not being a course participant, or something else.

One key case to deal with is when a user is logged out. Currently, if that happens (such as if the user logs out in one tab and then tries to take an action in another) then the course pages will render the unhelpful error message "Unauthorized."

**Comment by jstoebel** [comment]
I'm new to this project and would like to take a crack at it.

**Comment by ragesoss** [comment]
That came out nicely!
