### ISSUE TITLE
View and revision discrepencies between instances

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#14]
The totals for characters added and total views are somewhat off for the same set of courses:

As for now, staging shows for the Spring 2015 cohort:
- 56 WikiEdu Courses
- 921 Student Editors
- 505 have completed training
- 103K Characters Added
- 783K Article Views

Production, for the same set of courses in that cohort:
- 56 WikiEdu Courses
- 923 Student Editors
- 497 have completed training
- 101K Characters Added
- 639K Article Views

The number of editors is different because of issue #9. The training completion numbers are different because of issue #10 (possibly combined with #9). #9 might explain the small difference in characters added as well — or it might now. But the article views difference seems rather more significant, and I'm not sure of the source. It could be related to the extra data that staging has for the Fall 2014 cohort.

**Comment by ragesoss** [comment]
I think at one point I spotted a change to the time bounds on revision pulls: instead of going based on the latest known revision from any user in the course, and only pulling later edits, it switched to special-casing users with 0 revisions on the assumption that they might have just been added to the course, and so in that case, pulling revisions all the way from the start of the course.

So, some discrepency may come from users who had made edits before joining the course (but after the course began) and who didn't get added to the course roster until after others had started editing... and before the above change went into effect.

After the role refactor, the number of editors has syncronized. I think the training completion may syncronize after the next update of staging (806 on production vs 801 on staging, but with several recent student editors who completed training since the last complete update on staging). Characters added is still very close to being in sync but not quite there: 1.41M vs 1.42M.

The big discrepency remains the views, which now stands at 11.7M on staging vs 14.4M on production. I know that there have been some disruptions in service for the views, with data being missing for several days (and so returning values of 0), but I don't know why that would affect one instance more than the other. The view data pipeline is something we can look at more deeply when we have a chance. Maybe we can regenerate just the view data at some point.

**Comment by ntdb** [comment]
Our update tasks use existing data as the basis for pulling new data. This means that if an API call fails and creates incorrect data that the data can be irreparably inaccurate until the database is reset. We should add failsafes for this case and, probably, start our data sets from scratch on staging when time permits.

**Comment by ragesoss** [comment]
We don't keep the instances closely in sync any more, so this isn't going to be an actionable issue.
