### ISSUE TITLE
Convert `article_url`, `full_title`, and `escaped_full_title` in ArticleHelper into Article instance methods

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1402]
I often find myself wanting to get the url or full title of an article by calling `article.url` or `article.full_title`, etc.

Let's replace those `ArticleHelper` methods with instance methods on `Article`. This will require changes to every place in the app that currently calls those methods.

**Comment by unnatii** [comment]
I would like to take this up as my first issue

**Comment by alpha721** [comment]
@unnatii are u still working on this issue , because otherwise I would be happy to take it up.

**Comment by mauditecandela** [comment]
@unnatii and @alpha721 are you both still working on this issue? I find it very interesting and therefore I will be happy to take it up if you are not still working on it :)

**Comment by mauditecandela** [comment]
@ragesoss I created a first proposal for this issue, you can see it in 18e9bd4. All my local tests pass. I am not sure if I should transfer the namespaces constant to the article.rb model or if I should keep them at article_helper.rb. What do you think?
