### ISSUE TITLE
For course slugs, multiple internal spaces should be collapse into one space

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1404]
MediaWiki automatically treats links and page names with multiple consecutive spaces as just one space, which can cause a mismatch between the course page names on the dashboard and on-wiki.

During slug generation in `CourseCreator` (and in renaming via `Details`), multiple spaces should be condensed into one.

**Comment by alpha721** [comment]
I think, adding `slug = slug.gsub(/\s+/, ' ')` in `def slug` should solve the problem.  Am I going in the right direction?

**Comment by ragesoss** [comment]
@alpha721 I think this is best handled on the frontend first, since we already do a lot of similar cleanup there. The key places are in the `CourseUtils` javascript file: `slugify()` and `cleanupCourseSlugComponents()`.

There are tests for these as well, so a good place to start would be to run `jest --watch`, then modify the inputs for those functions in `course_utils.spec.js`, and then fix `CourseUtils` to make the tests pass again.

**Comment by alpha721** [comment]
I have opened PR #1405 . I have tried to followed through what you suggested. Please let me know if I did it the right way or not. (This is my first attempt at fixing an issue, so please let me know if I am doing anything wrong)

**Comment by ragesoss** [comment]
I think the only loose end for making sure we clean up all these fields is to apply `cleanupCourseSlugComponents()` from within saveCourseDetails() in details.jsx, which will apply the same sanitization when those fields are changed for an existing course.
