### ISSUE TITLE
Article titlle should not say 'null' for Wikidata items, etc

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1407]
When an article is shown that has a wiki with no language attribute, such as wikidata or multilingual wikisource, the dashboard shows 'null' as the language code. Instead, should omit the language code in this case.

![null](https://user-images.githubusercontent.com/848483/30607158-e873999c-9d28-11e7-9e37-57646f6cff61.png)

**Comment by mauditecandela** [comment]
I would like to pick this as my first issue :)

**Comment by mauditecandela** [comment]
Hi! I would like to pick this as my first contribution to the program but unfortunately cannot reproduce the bug. Could someone help me? Thanks.

**Comment by ragesoss** [comment]
You can reproduce it by creating a course, adding a user who has been active in Wikidata (e.g., Ragesoss if you set the course to start about a month ago), adding an available article from Wikidata to connect the course to that wiki, and then visiting [course page]/manual_update.

**Comment by mauditecandela** [comment]
I created a PR for a possible fix.

**Comment by testa19** [comment]
@mauditecandela Hi
Could it be simple check for `null `or `undefined ` in `shouldShowLanguagePrefix()`?
seems like it is the place responsible for "should omit the language code in this case"

`if (!this.props.article.language) { return false; }`

or 
`if (this.props.article.language == undefined) { return false; }`
`== null` returns `true` if `this.props.article.language` is also `undefined`
`== undefined` returns `true` if `this.props.article.language` is also `null`

**Comment by mauditecandela** [comment]
@testa19 indeed that was a better solution as it's more consistent with the logic of the whole article.jsx and prevents for false positives. I already did a commit for it and it's already added to my PR :) https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1413

**Comment by testa19** [comment]
@mauditecandela there could be a bug introduced with your previous commits - so Travis CI build failed.
I'm not a specialist in git PRs: i would get rid of previous commits and left only the last meaningfull one.

And seems like `!this.props.article.language` does that check for `null` and `undefined`. Try to play in dev cosole in a browser.

**Comment by ragesoss** [comment]
You can look at the CI build log to see the error. In this case, it's a javascript eslint error: `Unexpected whitespace before semicolon  semi-spacing`.

**Comment by mauditecandela** [comment]
Thanks a lot you both for the feedback! I will try the solution @ragesoss proposed in https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1413#issuecomment-332241174 and if not fix this another approach. I will also check the tests to make sure nothing breaks 😅
