### ISSUE TITLE
Add footer on P&E Dashboard noting that all contributions are CC-BY-SA 4.0

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1414]
We need a footer to note the license of contributions, since we don't send P&E users through the onboarding screen that says that for Wiki Education Dashboard.

This can be a new partial, similar to the existing Wiki Ed one, that only displays for P&E dashboard.

**Comment by majakomel** [comment]
I'd like to work on this
