### ISSUE TITLE
Disable Survey cloning

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1428]
There's a link to clone a survey, but 'deep_cloneable' does not work like we would need it to for the `has_and_belongs_to_many` relationship; it doesn't end up creating any new records except the `Survey` itself. To be useful, it would need to clone the QuestionGroups and Questions as well.

Instead, let's remove the links and code for cloning surveys.

**Comment by mauditecandela** [comment]
@ragesoss while waiting for more info about the updates, I decided to take a look at this issue. I deleted some code, but I am not sure if I took care of all the links. If you think it's correct, I will prepare a PR. :)

**Comment by ragesoss** [comment]
@mauditecandela that looks right. If you open a PR, you'll see a few specs fail; those will need to be edited or deleted (depending on whether they mainly testing the deleted feature, or are just using that feature in passing).

**Comment by ragesoss** [comment]
@mauditecandela here's the build from @yeli-buonya's incomplete PR for the issue: https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/282999356

Survey admin spec is failing; you'll need to edit that spec to not try to clone a survey (but still do all the other steps that are tested in that spec)

**Comment by mauditecandela** [comment]
fixed! 😄
