### ISSUE TITLE
Calendar widget extends past visible / scrollable area for small windows

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#143]
The calendar widget can pop up in a way that is not accessible in some cases. The scroll bar does not take into account the widget, so on a small window, it can extend past the edge of the visible area.

**Comment by ntdb** [comment]
Can you take a screenshot of the specific behavior you're trying to avoid? There are lots of options for mitigating this but I want to make sure I don't over-engineer something.

**Comment by ragesoss** [comment]
Here's the issue that has come up. The browser window is small enough that it does not extend below the course creator. The scroll bar lets me scroll to the bottom of that modal to access all the content. However, the calendar widget extends below the the scrollable area and it is impossible to access it. In this screenshot, I've scrolled down as far as possible.

![screenshot from 2015-06-29 10-48-48](https://cloud.githubusercontent.com/assets/848483/8414383/81b9e560-1e4c-11e5-85e9-1432aa1379b6.png)
