### ISSUE TITLE
Allow course edits to be disabled for a single course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1440]
Probably this could be done the same way we handle enabling/disabling timelines, with another entry in the course flags.

See https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/1b66177d705d1836340ca7612b478f570c1c59f2

**Comment by vzhz** [comment]
Hello @ragesoss, I'm applying to this summer's Outreachy session, and I am interested in working on this issue.

**Comment by ragesoss** [comment]
@vzhz hi! Send me an email (sage at wikiedu.org) and I can send you an invite to the development slack channel for this project.

**Comment by vzhz** [comment]
Will do!

**Comment by vzhz** [comment]
@ragesoss, I notice there is [an "edit" toggle that is part of the timeline being turned on and off](https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/1b66177d705d1836340ca7612b478f570c1c59f2#diff-309e9ba7ca4bd789f6bbc1455e0ed28cR268) already. I'm considering if it would be best to replace this line with one that calls a modular "course edits" toggle, but I want to make sure I understand if the two outcomes are functionally the same. Where can I see the way this works now? I haven't used wiki courses.

**Comment by ragesoss** [comment]
@vzhz enabling/disabling the timeline should be independent of 'course edits'. This new setting would replace `Course#wiki_edits_enabled?`, which is currently statically defined for each subclass of `Course`.  `Course#timeline_enabled?` is something that only affects the frontend, determining whether or not to show the Timeline tab.

Here's an example of a course with edits enabled (but without timeline enabled): https://outreachdashboard.wmflabs.org/courses/Museu_Paulista/Olhares_sobre_o_Museu_Ipiranga

The course title links to the wiki page for it (which gets automatically updated by the dashboard, whenever the description is edited or the user table changes).

It may be helpful to trace what happens when a course gets updated:

* In CoursesController#update, the course record is changed and then UpdateCourseWorker gets called.
* UpdateCourseWorker is a background job that calls WikiCourseEdits with the `update_course` action.
* WikiCourseEdits first checks to see if course edits are enabled (and several other checks), exiting immediately if not.
* If course edits are enabled, it executes the `update_course` method, generating a wikitext version of the course and then posting that to Wikipedia (overwriting the previous wiki version, if any).

This change will involve both adding a new control on the frontend, like the TimelineToggle, which will update a course flag... and also updating the CoursesController to handle that update, and changing the Course model and/or its subclasses to update `wiki_edits_enabled?`.

**Comment by vzhz** [comment]
Hello @ragesoss, I've made some progress:
- spent some time familiarizing myself with the codebase (thank you for the link to the course, that helped me understand expectations), and
- added (on my local copy) a flag for course edit

Before I continue, I have a question: I see that 'course.wiki_edits_enabled?' has several subclasses (ie. `classroom_program_course`). Should edits be enabled on each of these subclasses or only the course class?
Thank you!

**Comment by ragesoss** [comment]
I think it can be done by removing the methods on the subclasses and implementing it in `Course` in a way that handles every relevant situation.

**Comment by ragesoss** [comment]
Resolved with e9cc94bf9e4490f206364e15bc13878e2e5f6473 and 62f5fb1007976af148c83396951a21053b916f45
