### ISSUE TITLE
Javascript errors don't include source file line numbers in stack trace

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1445]
It's harder than it should be to track down the source of errors, because even in a development environment, the console stack traces use the compiled javascript rather than the source files.

There should be some sort of configuration that will make source mapping work better for our build pipeline.

**Comment by heysusgarcia** [comment]
@ragesoss i will look into this one. Was it working at some point?

**Comment by ragesoss** [comment]
Go for it! It was never working before, but it's something available in the
dev environments of many projects. Not really sure how to make it happen
though.

**Comment by heysusgarcia** [comment]
i created PR #1470
