### ISSUE TITLE
Improve behavior of 'see more' button on Activity tab

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1451]
The 'See More' button at the end of the revisions list allows the user to fetch a larger number of revisions beyond the default of 50. It should only be shown if the limit is already the number of revisions being shown; it should not appear if there are fewer available revisions than the limit (and it should not appear while new revisions are being fetched, before they return).

It may make sense to do this *after* converting RevisionStore to Redux, because with the current data flow, `RevisionsHandler` doesn't know how many are in the store.

**Comment by mauditecandela** [comment]
@ragesoss I am working in this issue as my next one, but I need to understand better reducers vs stores. So right now I am doing some research. Any tips are welcome (besides the official Redux Documentation).

**Comment by ragesoss** [comment]
@mauditecandela this was the most useful resource for me to wrap my head around Redux: https://egghead.io/courses/getting-started-with-redux

Redux is a particular way to implement stores in React; it combines all the different parts of the application state into a single store, rather than having separate stores for different parts of it. Our redux store is created by coming all the reducer functions in `reducers`, while the older stores (using the deprecated library McFly) are in `stores`.

**Comment by mauditecandela** [comment]
@ragesoss I think this is done...
