### ISSUE TITLE
Upgrade enzyme to version 3

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1452]
The enzyme javascript testing library has a breaking change for version 3; it looks like we need to add additional configuration in the form of an 'adapter' to make enzyme work.

Edit package.json to change enzyme to the latest release, then run `yarn`, then run `jest` to see the error messages, then make the `jest` tests pass again.

**Comment by ragesoss** [comment]
https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md

**Comment by sljohnson32** [comment]
@ragesoss Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by ragesoss** [comment]
@sljohnson32 cool, go for it. How did you find your way to this project?

**Comment by sljohnson32** [comment]
@ragesoss Awesome!  I am a student at Turing School of Software & Design in Denver and we have a project to contribute to an open source project.  Our instructor @brittanystoroz gave us this repo as an option.

**Comment by ragesoss** [comment]
Thanks much. @brittanystoroz, how did *you* find your way to this project?

**Comment by brittanystoroz** [comment]
@ragesoss Haha I honestly don't remember, I made a lot of pleas on twitter for people to help me find good open-source projects for my students to work on, which is really difficult. Someone must have linked me to it on one of those threads.
