### ISSUE TITLE
On-wiki course page shows the instructor with the first User record, rather than the first CoursesUsers record

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1459]
On-wiki course pages (from `WikiCourseOutput`) list only the first instructor. (See also #1175) This 'first' instructor is not necessarily the first one enrolled in the course, but it should be.

Also, the real name is fetched from the User record. It should instead by fetched from the CoursesUsers record.

**Comment by aSquare14** [comment]
I'd like to work on this issue.

**Comment by ragesoss** [comment]
@aSquare14 great! would like me to set up a GCI task for it?

**Comment by aSquare14** [comment]
By GCI do you mean Google Code In?  Because if you do, I'm not eligible for
GCI, I'm a sophomore at college(not in the age gap 13-17) . I'm just
getting started with Open Source and have a keen interest in learning and
exploring. :D

**Comment by mariahajmal** [comment]
@ragesoss Hi, Is this fixed? If not, can you please assign it to me

**Comment by ragesoss** [comment]
Yeah, it looks like this did get fixed incidentally via https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/1d0268c84e0d579831e951e1d5a31a3e6a011552
