### ISSUE TITLE
On the My Dashboard Page, displaying the Archived courses in a way to make the newest information available first.

### ISSUE THREAD

**Issue by sejalkhatri** [WikiEducationFoundation/WikiEduDashboard#1472]
Work involves changing the order of the courses from newest to oldest.
![archived](https://user-images.githubusercontent.com/14351471/31851758-c74ed626-b689-11e7-859e-50e7fb743258.png)

**Comment by appleJax** [comment]
Is there a difference between courses and programs? Whenever I try to create a program, it takes me to a page for creating a new course. Also, was this fixed in #1483 ?

![archived_courses](https://user-images.githubusercontent.com/13618860/32648894-c478058a-c5ac-11e7-8996-cf659dd70ad4.png)

**Comment by ragesoss** [comment]
Programs and courses are synonyms. One instance of the dashboard mainly uses "course", and the other "program". I don't think this would have been fixed by the other patch. Not 100% sure though.
