### ISSUE TITLE
Investigate using rspec-retry for intermittently failing specs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1476]
This might make our travis-ci builds more reliable.

https://github.com/NoRedInk/rspec-retry

**Comment by pjht** [comment]
I think the gem is defunct, as when I add it to the Gemfile and run `bundler`, I get this error:
Could not find gem 'rspec-retry' in any of the gem sources
listed in your Gemfile.

**Comment by Aeropio** [comment]
@ragesoss can you please elaborate more on this issue?

**Comment by wulanseruniati** [comment]
Hi,
I’ve successfully integrated rspec-retry into our test suite to improve stability for intermittently failing specs, particularly on CI. I'll be creating a pull request shortly to merge these changes. Please let me know if you have any feedback or additional requirements! Also, if possible, could I get an invitation to join the team's Slack channel? I’d love to stay in the loop and collaborate more easily with everyone. Thanks in advance!

**Comment by ragesoss** [comment]
@wulanseruniati let me know your email address and I can send you an invite to the Slack.

**Comment by ragesoss** [comment]
7 years later, I think this too blunt of a solution to the intermittent test failures; I'd rather spend more time on the individual failing tests before trying this.

**Comment by wulanseruniati** [comment]
> @wulanseruniati let me know your email address and I can send you an invite to the Slack.

My email address is wulanseruniati@gmail.com . I look forward to joining the Slack channel. Thanks!
