### ISSUE TITLE
On Debian Firefox, In surveys, input focus styling is not good

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1478]
The dotted line around a square region is not what we want. A focus highlight that matches the rest of the design would be best.

![focus outline](https://user-images.githubusercontent.com/848483/32182249-701f9ee6-bd53-11e7-9e4b-690b467f262a.png)

Set up a survey (via `/surveys` with an admin account) with a question group and some questions of various types, then preview it to see the issue.

The styling for surveys is spread across `/app/assets/stylesheets/survey_modules`

**Comment by appleJax** [comment]
Has this been fixed already? I can't reproduce the issue.

Chrome:
![chrome](https://user-images.githubusercontent.com/13618860/32264431-e1b435b4-be9b-11e7-9ce8-00c59852f8cd.png)

Safari:
![safari](https://user-images.githubusercontent.com/13618860/32264438-e80a9b6a-be9b-11e7-9b16-8d61e8e3456b.png)

Firefox:
![firefox](https://user-images.githubusercontent.com/13618860/32264442-ed66ab76-be9b-11e7-9d6f-052633dc35a1.png)

**Comment by ragesoss** [comment]
@appleJax thanks! This seems to be OS-dependent. I get it on Firefox on Debian (but not on Chromium on Debian).

**Comment by Kirti2502** [comment]
Hi, I am an Outreachy applicant. Can I take up this issue?

**Comment by ragesoss** [comment]
@Kirti2502 sure, go for it.

**Comment by UmerMIB** [comment]
Hi there, can you help navigate this survey form in the app? I didn't find a way to reach this survey form

**Comment by aniketsh22** [comment]
Hello, Is this issue still open? Can I work on it?

**Comment by ragesoss** [comment]
@aniketsh22 yes, it's still open. Feel free to work on it.

**Comment by sofiyanpathan** [comment]
Hi, can i work on it?

**Comment by ragesoss** [comment]
> Hi, can i work on it?

Go for it.

**Comment by thekavikumar** [comment]
Is the issue still open? If so, can I work on it?

**Comment by ragesoss** [comment]
Yes, it's still open. Go for it.

**Comment by Smita-Maurya** [comment]
Hello @ragesoss ,I request you to please allow me to work on this issue.

**Comment by ragesoss** [comment]
> Hello @ragesoss ,I request you to please allow me to work on this issue.

Sure, go for it.

**Comment by thekavikumar** [comment]
Also, can we set this up in WSL or does it require a VM?

**Comment by ragesoss** [comment]
@thekavikumar yes, you can set it up with WSL 2.

The docs have a file that covers the setup steps. Basically, the focus outline for the selected survey answer in the first screenshot demonstrates the bug. As you see from other screenshots, you might or might not be able to replicate it on your version of Firefox. I just tested it out and can no longer replicate it on my current version of Firefox, so I'm going to go ahead and close this issue; it must be something that only happened in older versions, and it's not important enough to try to figure out exactly why.
