### ISSUE TITLE
Google Code-In 2017: Setup Wiki Education Dashboard and run tests

### ISSUE THREAD

**Issue by feelfreelinux** [WikiEducationFoundation/WikiEduDashboard#1493]
[The Wiki Education Dashboard](https://github.com/WikiEducationFoundation/WikiEduDashboard) is a web application that supports Wikipedia education assignments, provides data and course management features for groups of Wikipedia users — instructors, students, and others — who are working on a common Wikipedia project.

- [Create fork](https://help.github.com/articles/fork-a-repo/) of WikiEducationDashboard on github
- [Follow setup instructions to run WikiEducationDashboard on your machine](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md)
- [Execute unit tests](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/testing.md)
- Provide screenshot of running dashboard, and document any problems 
problems you have encountered while installing dashboard.

**If you have any issues with setting up, feel free to request slack channel invite by contacting sage@wikiedu.org, and/or join `wikimedia-ed` IRC channel on freenode**

**Comment by takidelfin** [comment]
[There](https://github.com/takidelfin/gci-task-wikiedudashboard) is my task documentation. Errors are at the end of the readme.md
:wave:

**Comment by ragesoss** [comment]
@takidelfin took a quick look, and that's awesome! That'll be really helpful for others trying to set up on recent Windows, I think, and we can incorporate some of it into our setup and troubleshooting docs.

**Comment by takidelfin** [comment]
feel free to do this :)

**Comment by refeed** [comment]
Hi,

Here is my repository about setup Wiki Education dashboard and run tests, dashboard screenshot, and errors that I encountered are documented here: https://github.com/refeed/WikiEduDashboard-setup-debian9-fish  :)

**Comment by ragesoss** [comment]
@refeed excellent!

That's a suprising set of spec failures. The admin spec one is a feature spec that occasionally fails on travis-ci as well.

The course creation and course page ones look like they might be related to timezone and locale (language), respectively.  What timezone are you in, and what is the default language setting of your computer? We might be able to shore those specs up to work in any timezone / locale.

The last one, I'm not sure about. If you run just that training tool spec, does it pass?

**Comment by refeed** [comment]
@ragesoss My computer uses UTC time and my time is UTC+7, my default language is english with en_US.UTF-8 locale.
```
refeedmain@RHCOMP ~> sudo hwclock --debug
[sudo] password for refeedmain: 
hwclock from util-linux 2.29.2
Using the /dev interface to the clock.
Last drift adjustment done at 1501078076 seconds after 1969
Last calibration done at 1501078076 seconds after 1969
Hardware clock is on UTC time
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
...got clock tick
Time read from Hardware Clock: 2017/12/02 02:26:57
Hw clock time : 2017/12/02 02:26:57 = 1512181617 seconds since 1969
Time since last adjustment is 11103541 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2017-12-02 09:26:56.710604+0700
refeedmain@RHCOMP ~> locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Executing training tool spec individually still failing
```
refeedmain@RHCOMP ~/G/WikiEduDashboard (master)> rspec ./spec/features/training_tool_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
...............F  HTML screenshot: file:///home/refeedmain/GitHub/WikiEduDashboard/tmp/screenshots/screenshot_2017-12-02-09-54-21.317.html
  Image screenshot: file:///home/refeedmain/GitHub/WikiEduDashboard/tmp/screenshots/screenshot_2017-12-02-09-54-21.317.png


Failures:

  1) Training 'Editing Basics' module lets the user go from start to finish
     Failure/Error:
       expect(TrainingModulesUsers.find_by(
         user_id: 1,
         training_module_id: training_module.id
       ).completed_at).not_to be_nil
     
       expected: not nil
            got: nil
     # ./spec/features/training_tool_spec.rb:176:in `go_through_module_from_start_to_finish'
     # ./spec/features/training_tool_spec.rb:165:in `block (4 levels) in <top (required)>'

Finished in 1 minute 48.42 seconds (files took 7.65 seconds to load)
16 examples, 1 failure

Failed examples:

rspec ./spec/features/training_tool_spec.rb:164 # Training 'Editing Basics' module lets the user go from start to finish

Coverage report generated for RSpec to /home/refeedmain/GitHub/WikiEduDashboard/coverage. 1092 / 9798 LOC (11.15%) covered.
```
The screenshot from the tmp dir:
![screenshot_2017-12-02-09-54-21 317](https://user-images.githubusercontent.com/20320125/33511095-98bddde6-d747-11e7-906d-944763b0d215.png)
