### ISSUE TITLE
Update X time ago shows up underneath MyArticles component

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1497]
@mauditecandela I just noticed this (at an A+F editathon today).

It should be above MyArticles.

![update an hour ago](https://user-images.githubusercontent.com/848483/32985215-82b41b38-cc6a-11e7-90c7-d22eb325241c.png)

**Comment by mauditecandela** [comment]
Should be fixed by #1502
