### ISSUE TITLE
Sentry events should be sent asyncronously

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1503]
See https://docs.sentry.io/clients/ruby/config/

This will involve creating a simple Sidekiq worker to perform the sending, and configuring Raven to use it in the raven initializer.

**Comment by alpha721** [comment]
Hi @ragesoss  , I would like to give this issue a try. Any hints are super welcome :)

**Comment by ragesoss** [comment]
@alpha721 the 'async' section in the link above has a clear example. Look at `app/workers` to see how other Sidekiq workers are implemented.

Sentry in configured in `config/initializers/raven.rb`
