### ISSUE TITLE
AvailableArticles title formatting is buggy for non-EN programs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1513]
For example, on this program, the articles have an 'en:' prefix even though they are not English Wikipedia articles: https://outreachdashboard.wmflabs.org/courses/%D0%9A%D0%BE%D0%BD%D0%BE%D1%82%D0%BE%D0%BF%D1%81%D1%8C%D0%BA%D0%B5_%D0%BC%D0%B5%D0%B4%D0%B8%D1%87%D0%BD%D0%B5_%D1%83%D1%87%D0%B8%D0%BB%D0%B8%D1%89%D0%B5/%D0%97%D0%B0%D1%80%D1%83%D0%B1%D1%96%D0%B6%D0%BD%D0%B0_%D0%BB%D1%96%D1%82%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B0/articles

This is because `CourseUtils.articleFromAssignment` (called from `AvailableArticle`) falls back to 'en' and 'wikipedia' rather than the language and project from `defaultWiki`.

Fix that CourseUtils function and add unit test(s) for this bug.

(Reported here: https://phabricator.wikimedia.org/T181357 )

**Comment by bcb37** [comment]
I think I've got a handle on this one, but there are a couple tests that call `CourseUtils.articleFromAssignment` with only the first argument ('article'), so those fail if I'm trying to dereference `defaultWiki.langauge` in the method. There don't seem to be any places in the actual non-test codebase where that method is called that way, but I don't want to change the tests if something depends on it being able to be called with just one argument. Would it be legit to do that?

**Comment by ragesoss** [comment]
Yeah, if the test interface doesn't match how it's used throughout the app, then you should change the test.

**Comment by bcb37** [comment]
I just tried to do a pull request, but the CI failed on a formatting issue. Should I try it again?
