### ISSUE TITLE
Add i18n support for training module page titles, 'next page' buttons, and breadcrumb links

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1514]
We currently have some untranslated parts of the interface for training modules.
![basque slide](https://user-images.githubusercontent.com/848483/33285552-7f2eec5a-d367-11e7-837f-bdc70dc99482.png)

**Comment by ragesoss** [comment]
See also https://phabricator.wikimedia.org/T182132

**Comment by bcb37** [comment]
Hi, I've got most of these interface items able to be translated, but the module and slide names  (on the breadcrumbs and table of contents) seem like they have to come from the training content itself. It's not clear to me how the dashboard finds that content. When I run it locally, it doesn't present translated training content, even when the rest of the UI is translated, through calls to `I18n.t()`. Does it have to come from the meta wiki? (I noticed that the `training_loader` spec maybe forces that to be the case by hardcoding "none" into the yml path) Also: I have tried it with `enable_wiki_trainings` set to both true and false.

**Comment by ragesoss** [comment]
@bcb37 the training content all gets rendered in React. `app/views/trainging_modules/show.json.jbuilder` passes the content for a module, including all the translations, to the client. Accessing the correct translation happens in `app/assets/javascripts/training/components/training_slide_handler.jsx` (and you'll see there that it doesn't use the translations for the quizzes, which it should do as well).

To load some translated content locally, you need to both set `enable_wiki_trainings` and specify the wiki pages to load from in application.yml, then you must reload the content by going to `/reload_trainings?module=all`.

**Comment by ragesoss** [comment]
Done!
