### ISSUE TITLE
Convert react classes to stateless functional components

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1518]
These components don't use any React class features, and so could be converted into pure functions:

- [x] /app/assets/javascripts/components/app.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1519
- [x] /app/assets/javascripts/components/activity/recent_activity_handler.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1520
- [x] /app/assets/javascripts/components/articles/article_list.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1521
- [x] /app/assets/javascripts/components/articles/available_article_list.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1521
- [x] /app/assets/javascripts/components/articles/salesforce_media_buttons.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1522
- [x] /app/assets/javascripts/components/common/course_link.jsx -https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1523
- [x] /app/assets/javascripts/components/common/list.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1523
- [x] /app/assets/javascripts/components/common/loading.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1523
- [x] /app/assets/javascripts/components/common/popover.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1523
- [ ] /app/assets/javascripts/components/high_order/conditional.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1524
- [x] /app/assets/javascripts/components/onboarding/index.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1525
- [x] /app/assets/javascripts/components/overview/inline_users.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1525
- [x] /app/assets/javascripts/components/revisions/revision_list.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1525
- [x] /app/assets/javascripts/components/timeline/orderable_block.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1525
- [x] /app/assets/javascripts/surveys/components/BarGraph.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1525
- [x] /app/assets/javascripts/training/components/training_app.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1525
- [x] /test/components/overview/my_articles.spec.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1525
- [x] /test/components/timeline/block.spec.jsx - https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1525

You can find plenty of examples of such components in the app already, such as `app/assets/javascripts/components/overview/course_stats.jsx`.

Leave a comment about which file you're working on. Each conversion should be possible by only changing that single file only, although you should feel free to refactor the props interface if you see a need for it.

**Comment by arun1595** [comment]
I am working on converting `App` class component to a stateless functional component.

**Comment by ragesoss** [comment]
All of the ones that were detected automatically, except for Conditional which doesn't seem to be actually possible to convert, are done. There are more that could be converted with a bit of work, but we don't need a tracking issue for them; we'll convert them as they come up if it seems helpful.
