### ISSUE TITLE
For Wiki Ed ask new instructors how they heard about Wiki Ed

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1529]
This could probably be done in the /onboarding flow. Maybe create an Alert and email someone each time it happens.

**Comment by alpha721** [comment]
"Maybe create an Alert and email someone each time it happens." Should it ask the new instructors this question via mail? As, in the same way some websites ask for account activation for first time sign up? @ragesoss

**Comment by ragesoss** [comment]
The Alert email is something intended for Wiki Ed staff, and would happen after the user submits an answer as part of the onboarding flow.

**Comment by AmitJoki** [comment]
@ragesoss can you point me to some example where Alert is created to send to the WikiEd staff? Like, how do I send an alert to a wiki ed staff?

**Comment by ragesoss** [comment]
See `lib/alerts`. In particular, `unsubmitted_course_alert_manager` does something similar.
