### ISSUE TITLE
If authorship highlighting data fetching fails, ArticleViewer should re-fetch upon re-open

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1547]
Fetching data from whocolor may occasionally fail. When that happens, closing diff viewer and reopening it should trigger another attempt at fetching the data. Currently, a user would need to refresh the page to try again.

**Comment by khyatisoneji** [comment]
Hi @ragesoss , I would like to work on the issue. Please provide details as to how to replicate this issue.

**Comment by ragesoss** [comment]
You'll first need to create a course with some articles edited, see https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/user_roles.md#populating-a-course-with-data

Then, you can replicate a failing API call by changing the whocolor URL in ArticleViewer component to something that returns:
a) some json that does not include an `html` element, eg, `https://jsonplaceholder.typicode.com`
b) a 404 or non-json response, which currently isn't handled at all and doesn't even result in the 'course not fetch' message as it should.

**Comment by khyatisoneji** [comment]
@ragesoss , I have added a course to my local database.
I have also made the changes as specified in ArticleViewer component, but I am not able to see this issue (404 message).

Can you please tell me which specific url to navigate to, if I were to replicate this issue?

**Comment by ragesoss** [comment]
You can make the whocolor api return a 404 if you just, for example, remove the 'r' from 'whocolor: `https://api.wikiwho.net/${this.props.article.language}/whocolo/v1.0.0-beta/${this.props.article.title}/`

That will just make the frontend display the loading message forever, rather than show an error message like it should.

**Comment by khyatisoneji** [comment]
@rageross, I was able to re-create the issue.

Should we handle this by having an error function in the Ajax request?
Then, in this function we can write logic to display error message.

**Comment by ragesoss** [comment]
Sounds good.

**Comment by khyatisoneji** [comment]
@ragesoss, is there any component that we have for displaying error?

I initially thought of having it as a function, but I think that it would be better to have it as a component as it can be used elsewhere.

**Comment by ragesoss** [comment]
@khyatisoneji I was thinking it should be handled the same way as the other whocolor failure mode, by setting the 'legendStatus' that gets passed to ArticleViewerLegend as 'failed'.

We have a general system for displaying error messages, by sending a addNotification redux action that will end up rendering the message in the Notifications component. But for this particular component, I think it makes more sense to keep all the state within the ArticleViewer, since it's already a very stateful component and has a decent method for displaying the error already.

**Comment by khyatisoneji** [comment]
@ragesoss , I tried setting this.state.whocolorFailed to true and thus legendStatus that was passed to ArticleViewerLegend is failure state.

The screen still displays loading screen with "could not fetch authorship data" , and the same is mentioned in the ArticleViewerLegend's render function.

The screen looks like this. Is that ok?
<img width="1008" alt="screen shot 2018-01-28 at 9 58 41 pm" src="https://user-images.githubusercontent.com/31898080/35484511-c9eb87ae-0476-11e8-9e4b-a23b06f36a9f.png">

**Comment by ragesoss** [comment]
Which failure causes that? The legend in that state is fine, if there is a failure.

The article body should only show that loading animation if the original article html from Wikipedia hasn't loaded; there shouldn't be any loading animation if only the whocolor query failed.

**Comment by khyatisoneji** [comment]
I made changes to both **wikiUrl** and **whocolorUrl** function to make requests to random sites.

Is the wikiUrl function not expected to fail? In that case the screen only shows **could not fetch authorship data**

<img width="1210" alt="screen shot 2018-01-28 at 10 23 35 pm" src="https://user-images.githubusercontent.com/31898080/35484721-ff82c23a-0479-11e8-8121-86e0126dee59.png">

**Comment by ragesoss** [comment]
Cool. The wikiUrl one is unlikely to fail, but of course it might
occasionally. I don't think we need any special handling for that, though.

**Comment by khyatisoneji** [comment]
Just a few ending remarks:

There are three functions that are making AJAX request:

1. fetchUserIds 

2. fetchWhocolorHtml

3. fetchParsedArticle



Error callback cases:

1. when fetchParsedArticle returns an empty article, we turn status as 'failed'. So as this function can throw error, here we should add the error callback function.

2. fetchUserIds on error will not change the status and thus, no callback should be added.

3. fetchWhocolorHtml should have a error callback, so I have added it.

**Comment by ragesoss** [comment]
I think that sounds reasonable. Please open a PR. :-)
