### ISSUE TITLE
Add i18n support for (history) and (article development) links in Articles tab

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1549]
These strings in article.jsx and article_graphs.jsx are currently hardcoded to English. They should use i18n with the messages added to the locale file.

**Comment by alpha721** [comment]
Hi, @ragesoss , I would like to work on this issue. Can I give it a try?

**Comment by alpha721** [comment]
Hi, @ragesoss can I give this one a try?

**Comment by ragesoss** [comment]
Yes, please do.
