### ISSUE TITLE
Purpose of block type picklist is not clear to users

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#155]
The Class/Assignment/Milestone/Custom picklist is confusing to users, and the editing interface does not label that box (for example, with "block type").

Custom should maybe be replaced by a blank option, since all it does is remove the label.

It might be interface overkill, but this would make more sense to users if we labeled the box, and added a popover explaining what it is for. The reason this might be relevant would be if we start doing additional things with the different data in different kinds of blocks, such as showing a view that just has the Assignments and their due dates, or just the Milestones and their dates. (I think the latter may be something we want to build into the overview, to give users a high-level sense of where they are in the course.)

This probably needs some design input before we move on it.

**Comment by ntdb** [comment]
Short term design fix: add "Type" label to the picklist.

**Comment by rileywho** [comment]
See solution on issue #156
