### ISSUE TITLE
Drag-and-drop timeline rearrangement feature is hard to use, not discoverable enough

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#156]
In user tests so far, the drag-and-drop has not worked very well. It's very hard to move a block more than about 1 week at a time.

It's actually not possible, as far as I can tell, to drag a block into an empty week. (The workaround is to create a new block in that week, then drag the other block to it, then delete that new block.)

Users often do not realize that blocks can be dragged around at all, and end up going the copy-and-paste route to try to rearrange their timeline.

Broadly, I think the right approach is probably to separate rearranging and content-editing into separate interfaces, so that you see a more condensed, trello-like view for arranging blocks, and no drag-and-drop while editing text. This needs design input.

**Comment by ragesoss** [comment]
Another subissue: If a block is added to a week that already has many blocks, it may show up in the middle of the existing blocks, instead of at the end as expected.

**Comment by ntdb** [comment]
Short term design fixes: scale up blocks on hover, add drag handle to blocks

**Comment by rileywho** [comment]
Design solution. Lots of changes. 

- Add handles to the top left
- Add "Block Type" title to the dropdown box
- Move grading to the left of the block title
- Decrease spacing between the title inputs and the paragraph box
- Add 15px to the bottom of each block. This will help each block look detached and movable. See issue #268 

![screen_shot_2015-08-04_at_2_16_51_pm_png___100___layer_6__rgb_8____](https://cloud.githubusercontent.com/assets/2120466/9074068/3ba746d6-3abb-11e5-856d-3399ca5b0e7d.png)

**Comment by ragesoss** [comment]
This will probably help, but the bigger issue of how hard it is to do serious rearranging of blocks — dragging a block from the beginning to the end, for example — is still something we'll need to tackle.

**Comment by ntdb** [comment]
@ragesoss quite right, I got resolve happy. :)

**Comment by ragesoss** [comment]
@thenickcox @bmathews @rileywho

Great work on this. It's a huge step forward. We can close this as soon as we merge the timeline branch to master.

**Comment by rileywho** [comment]
@ragesoss Thanks!

**Comment by thenickcox** [comment]
:tada:
