### ISSUE TITLE
Campaigns should have a default program type

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1561]
For A+F, we want each program created from the campaign page to be Editathon type, instead of the current default 'BasicCourse' type. That way, the 'update statistics' button will show up for all of the A+F events without extra steps on the part of organizers.

To do this, we'll probably need to:
* Add a new field to the Campaign record
* Pass the type to the frontend via campaign/show.json.builder
* Set the type in the course creator's store(s) when that data is received

I will try to do some preparation for this shortly, because this will go more smoothly if we have the course store in CourseCreator converted to redux first, and I have some work in progress on that.

**Comment by ragesoss** [comment]
@mauditecandela

**Comment by mauditecandela** [comment]
@ragesoss I would like to work on this topic, ping me once you've finished converting the course store ;)

**Comment by mauditecandela** [comment]
@ragesoss  I am working on this. I have one question: maybe we should create a CourseTypeSelector similar to CourseLevelSelector and use it in the Course Creator to allow the instructors to modify the Default Course Type if they want to. What do you think?

**Comment by ragesoss** [comment]
@mauditecandela I think such a selector makes sense (we already have a CourseTypeSelector component, used in Details, and it can probably be reused). I suggest doing that as a separate follow-up PR, though, once this issue is implemented.
