### ISSUE TITLE
On course details editing view, campaign selector should autocomplete and be better sorted by default

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1569]
See https://phabricator.wikimedia.org/T183630

**Comment by alpha721** [comment]
Hi @ragesoss , I would like to try working on this issue. Can you please elaborate a little?

**Comment by alpha721** [comment]
Is this issue regarding "edit details" part of the page after a course is created? If that is so, I can't seem to find the campaign selector option. If not , any help to isolate the error would be very much welcome :). 
Also,please let me know, if you would prefer me to ask questions on slack or here.

**Comment by ragesoss** [comment]
@alpha721 slack is usually good.

To see the issue, you need to be logged in as an admin. Then, in 'edit details' mode after the course is created, you should see the Campaigns item with a button to add/remove campaigns.

![campaigns button](https://user-images.githubusercontent.com/848483/34998978-53206468-fa95-11e7-8405-28c9c9e1a00b.png)

I think the ideal way to fix this will be to replace CampaignStore with a campaigns reducer, do the sorting there, and use `react-select` (already in use elsewhere in the app) to provide autocompletion.

**Comment by alpha721** [comment]
Hi, @ragesoss, I want to change campaign store with a reducer , but I am still not sure if I understand all the things in the stockstore completely . Is there  any previous fix that I can use as an example? Thanks.

**Comment by ragesoss** [comment]
@alpha721 stock store is basically a general-purpose store for receiving sets of model data (like a list of users, or a list of campaigns). It implements of a bunch of different actions that it can respond to, but the most important ones are a) receiving data from the server and storing it, and b) sorting the items.

Typically, each individual store that uses StockStore only uses a small portion of the functionality that StockStore provides. In the case of CampaignStore, it's actually using a fair amount, most of it indirectly through the PopoverButton component.

Now that I take a look, this is more complex that I thought, because it will require significantly rewriting `PopoverButton` as well... and maybe LookupWrapper too.

Here's a recent redux conversion of a StockStore instance: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1644

**Comment by ragesoss** [comment]
@alpha721 I think @mauditecandela and I are going to try to tackle this one.

**Comment by alpha721** [comment]
@ragesoss, okay, no problem. Is there any other issue that you would like me to take up? Please let me know.

**Comment by ragesoss** [comment]
Done!
