### ISSUE TITLE
Replica article queries should be broken into multiple queries when the URI is too long

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1575]
`Replica` is the class for fetching data from copies of the Wikimedia databases. It's a PHP service that connects to the wmflabs replica databases: https://github.com/WikiEducationFoundation/WikiEduDashboardTools

One failure mode it has is querying for lots of article titles, which can result in a URI that is too long and causes an error. This mainly happens with queries for languages with non-latin scripts, where the URI encoding of article titles makes for much longer URIs. We currently work around this by special-casing the languages that have caused errors, and fetching fewer articles per query for those languages. See `ArticleStatusManager#articles_per_replica_query`.

A better approach would be to update `Replica` to handle breaking up large queries into smaller ones when necessary, based on URI length.

Another option, which might be even better, would be to use POST instead of GET requests and send the article titles as data rather than part of the URI. That would probably require making changes to the wmflabs replica endpoint tool.

**Comment by psinghal20** [comment]
Hi @ragesoss, I would like to take on this issue next if it is up for grabs! I also feel it would be better to use POST for the requests and thus changes on the wmflabs replica endpoint tool would be required.
