### ISSUE TITLE
Admin course rows should be right-clickable to open in a new tab

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1577]
On the dashboard home page for a logged-in admin, the list of that user's courses is rendered with `views/dashboard/_admin_courses` and `_admin_course_row`. This creates a sortable table, and there's a jquery function in `app/assets/javascripts/utils/course.js` that makes each row into a clickable link.

However, these rows don't otherwise behave like links... you can't right-click to bring up a context menu and open it in a new tab, and mousing over doesn't show you where the target is.

This can probably be fixed with some combination of adding real anchor links, CSS tricks, and/or changes to the jquery data-link function.

**Comment by psinghal20** [comment]
Hi, If nobody is working on this, can I take up this issue?

**Comment by ragesoss** [comment]
Go for it. :-)

**Comment by psinghal20** [comment]
Hi, I tried accessing the page for a logged in admin user but still, the _course_row views is getting rendered not the _admin_course_row. I gave my account permissions by using the steps mentioned in the user_roles docs. Can you help me with this?

**Comment by ragesoss** [comment]
Hmm... giving your user record `permissions = 1` should have been enough, if you saved the record and refreshed the home page. Do you see the `admin` link at the top?

If so, have you created any courses that are "strictly current" (as in, already started and not yet ended, and that have been added to a campaign)? Those should be the ones that show up with the _admin_course_row template.
