### ISSUE TITLE
Campaigns should be able to select "no passcode" as the default

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1592]
Currently, a campaign with no set default passcode will result in new programs that have a random passcode. That's normally what we want, but there will be cases where a campaign wants the default to be programs that don't have a passcode (like Art + Feminism).

Add an option to campaigns for 'no passcode', and make it work.

**Comment by mauditecandela** [comment]
What about a checkbox for the no passcode as default? Something like
Default passcode: __________________ [ ] No passcode
If the campaign has set the "No passcode" as true the Default would be no passcode.

**Comment by ragesoss** [comment]
Yes,I think that makes sense. The data flow side of it is where it gets slightly more complicated, since Rails will generally treat `nil` and an empty string the same way, in terms of forms, but I'd rather avoid adding another column to the Campaigns table just for that option if possible.

**Comment by mauditecandela** [comment]
I think I understood wrong on Friday. You are right: 
When setting a default passcode as blank, then it doesn't get overwriten by the default passcode, and the system. So yes, the option would be to create an exception that will work overwriting the passcode as "" when creating a new program. 
For the UX I would still add a checkbox or something similar to make it clearer and easier for the user.
