### ISSUE TITLE
Enable more rubocop rules and fix the violations

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1593]
Rubocop has recently been added to the travis-ci build, and the builds will now break if there are rubocop offenses. But to make that happen, we had to disable many cops that we ought to be using but that have violations in the codebase. These are configured in the "Temporary exceptions" section of [.rubocop.yml](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/.rubocop.yml).

These should be re-enabled, and the resulting violations fixed, with one commit per rule. Some will be harder than others. Please leave a comment if you are taking on one of these, and post any questions that come up while fixing the violations. In some cases, we may discover that it's actually best to keep the rule disabled (and just move it from the "Temporary exceptions" section of the config to the "Permanent exceptions" section).

**Comment by psinghal20** [comment]
Hi, I would like to work on this if nobody is working on it.

**Comment by ragesoss** [comment]
Sure. Pick a rule and note it here.

**Comment by psinghal20** [comment]
I am currently working on line length rule.

**Comment by ragesoss** [comment]
@psinghal20 cool.

In cases where it doesn't really improve anything to keep under 100 characters for a line — like really long strings that don't need to be read to understand the code — you should feel free to disable the rule inline for that violation, rather than break things up just to satisfy the rule.

**Comment by ragesoss** [comment]
@alpha721 yes, certainly. One PR per rule, please.

**Comment by maryam21** [comment]
Hi @ragesoss , I would like to work on this issue as well.

**Comment by ragesoss** [comment]
@maryam21 cool, just let us know which rule you're working on.

**Comment by maryam21** [comment]
I will work on Naming/PredicateName.

**Comment by maryam21** [comment]
Enable predicate name and fix violations #1690
