### ISSUE TITLE
Upgrade lodash to version 4

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1599]
Lodash is sometimes used globally from vendor.js, and that one we probably want to leave alone. But the version from package.json is used where lodash is explicitly imported, and that's the one we can and should upgrade.

This will require some updates for functions that change names between these versions, such as replacing `_.sum` with `_.sumBy` in `grading.jsx`.

**Comment by psinghal20** [comment]
Hi, I would like to work on this issue. Can you give me any pointers on how to start with this issue?

**Comment by ragesoss** [comment]
@psinghal20 the steps involved would be:

* in `package.json`, change the lodash version to the latest one.
* run `yarn` to update to the new version
* Go through the codebase and evaluate each of the places where lodash functions are used (by searching for `_.`)
* Use the [lodash changelog](https://github.com/lodash/lodash/wiki/Changelog#v400) to identify which function names and/or usage needs to be changed, in files that do `import _ from 'lodash';`.
* Make sure all the tests are still passing afterwards.
