### ISSUE TITLE
WikiCourseEdits#enroll_in_course should replace the default sandbox template if present

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1600]
`WikiCourseEdits#enroll_in_course` makes several edits, including one edit that adds a custom template to the user's "/sandbox" user subpage. This is done to preempt the default template that gets added if the user clicks the Sandbox link from their personal tools on Wikipedia (and which steers users to Articles for Creation, which we want to spare them from).

Improve this method so that, if the default sandbox template is already present, it will be replaced instead of just adding the custom template to the page.

**Comment by alpha721** [comment]
Hi, @ragesoss, I would like to work on this issue.

**Comment by AmitJoki** [comment]
How to check if a default sandbox page is already present and what is the function to replace it?

**Comment by Aeropio** [comment]
@ragesoss how can i reproduce this from UI?

**Comment by ragesoss** [comment]
This can't be reproduced directly, without enabling wiki edits in your development environment.

I would recommend using a test-first approach to this: write a test for the wiki page output when the wiki text includes the default template, `{{user sandbox}}`, and ensure that the output replaces that with the appropriate dashboard sandbox template.

This feature is currently part of the too-complex `WikiCourseEdits#enroll_in_course`, but it should probably be factored out to a new class, similar to `WikiUserpageOutput`, and then tested similarly to the tests for that and `WikiAssignmentOutput`.

**Comment by Aeropio** [comment]
ok i will look into this

**Comment by shashwatkathuria** [comment]
I am working on this issue.
