### ISSUE TITLE
In Students tab, users should be sortable by draft space characters added

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1612]

**Comment by psinghal20** [comment]
Hi, I would like to work on this. Can you brief me a little more about this issue?

**Comment by ragesoss** [comment]
@psinghal20

On the the Students tab of a course page, there's a table of users and info about what they've contributed:

![students tab](https://user-images.githubusercontent.com/848483/35241214-9816ad78-ff6a-11e7-8953-291f27d977dd.png)

This table is sortable, and in the case of the 'characters added' column, it includes three values in the same column, for the respective amount of content the user has added to different types of Wikipedia pages. There is a sorting dropdown at the top right, which can be used to choose sorting by "MS Chars Added" — mainspace, aka articles — or "US Chars Added" — userspace, aka user pages and sandboxes. Sorting by the third value, the characters added to Wikipedia's "Draft" namespace, is not an option, but it should be.
