### ISSUE TITLE
Campaign Default Passcode text field should hide after clicking another option

### ISSUE THREAD

**Issue by mauditecandela** [WikiEducationFoundation/WikiEduDashboard#1613]
At creating a new Campaign, when clicking on "Customize passcode" a text field to enter a Default Passcode appears. This text should be hidden again after clicking on another option (Random Passcode or No Passcode), to not generate confusion to the users.

Note: This behaviour is generated by Jquery at assets/javascripts/campaigns.js so it probably should be fixed by changing the Jquery there.

**Comment by psinghal20** [comment]
Hi @mauditecandela , are you working on this issue? I would love to take a stab at it if it is up for grabs.

**Comment by ragesoss** [comment]
@psinghal20 go for it
