### ISSUE TITLE
Unable to bundle install

### ISSUE THREAD

**Issue by khyatisoneji** [WikiEducationFoundation/WikiEduDashboard#1622]
I am using Ruby 2.5.0 on Windows 10 to run the repo.

When I run the command bundle install, I get the following:
```
Fetching gem metadata from https://rubygems.org/..........
Fetching https://github.com/halfdan/piwik-ruby-tracking.git
error: unable to stat just-written file .travis.yml: No such file or directory
error: unable to stat just-written file Gemfile: No such file or directory
error: unable to stat just-written file Gemfile.lock: No such file or directory
error: unable to stat just-written file MIT-LICENSE: No such file or directory
error: unable to stat just-written file README.rdoc: No such file or directory
error: unable to stat just-written file Rakefile: No such file or directory
error: unable to stat just-written file init.rb: No such file or directory
warning: unable to unlink 'lib': Directory not empty
fatal: cannot create directory at 'lib': Directory not empty
Git error: command `git reset --hard 34a3d3c8d25fa3323f054d887c64a7e249b07e58`
in directory
C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/piwik-ruby-tracking-34a3d3c8d25f
has failed.
```

I tried to delete the cache folder multiple time, but it didn't solve the issue.

I searched about "unable to stat just-written file" issue but didn't find anything conclusive.

Is someone else facing this issue on Windows?

**Comment by khyatisoneji** [comment]
The error log doesn't show the same thing every time. It also gives the following output as well:

```
Fetching gem metadata from https://rubygems.org/..........
Fetching https://github.com/ragesoss/omniauth-mediawiki.git
error: unable to stat just-written file spec/spec_helper.rb: No such file or directory
fatal: Could not reset index file to revision 'c64e52a08881e61d185c150818f8e13c62082a74'.
Git error: command `git reset --hard c64e52a08881e61d185c150818f8e13c62082a74`
in directory
C:/Ruby25-x64/lib/ruby/gems/2.5.0/bundler/gems/omniauth-mediawiki-c64e52a08881
has failed.
If this error persists you could try removing the cache directory
'C:/Ruby25-x64/lib/ruby/gems/2.5.0/cache/bundler/git/omniauth-mediawiki-1b693e91f3f5fbe801432bcbb94a7fc84ab78e9a'


```

**Comment by ragesoss** [comment]
Interesting. It looks like it's having trouble with github-based gems only?

Try commenting out all the github sources in Gemfile and running it again. (That will break the app, but at least it might narrow down the problem you're having.)

More info about your system would also be helpful... how are you running Ruby? In a linux subsystem, or via rubyinstaller, or something else?

**Comment by khyatisoneji** [comment]
Hi, 

Thank you for your reply,

I tried removing git repositories from gem file and it worked,

Also, I'm running Ruby 2.5.0 from Ruby devkit as mentioned in the documentation;
Windows:
Use RailsInstaller
Install Ruby DevKit.

**Comment by ragesoss** [comment]
Hmm... apparently Ruby 2.5 support is still a work in progress for Ruby DebKit: https://rubyinstaller.org/downloads/

I suggest using Ruby 2.4 instead. You'll need to change the version at the top of the Gemfile (and not include Gemfile or Gemfile.lock changes any time you make a commit) but otherwise, the app should still work the same way as on 2.5.

**Comment by khyatisoneji** [comment]
I tried this with Ruby 2.4.3, but it still gives the same error;

```
C:\Users\KHYATI\Documents\GitHub\WikiEduDashboard>C:\Ruby24-x64\bin\bundle install
Fetching https://github.com/halfdan/piwik-ruby-tracking.git
warning: unable to unlink 'lib/generators/piwik_analytics': Directory not empty
fatal: cannot create directory at 'lib/generators/piwik_analytics': Directory not empty
Git error: command `git reset --hard 34a3d3c8d25fa3323f054d887c64a7e249b07e58`
in directory
C:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/piwik-ruby-tracking-34a3d3c8d25f
has failed.
If this error persists you could try removing the cache directory
'C:/Ruby24-x64/lib/ruby/gems/2.4.0/cache/bundler/git/piwik-ruby-tracking-e1865758c285ac15fbb00c662370429900e06843'

```

**Comment by ragesoss** [comment]
Hmm... I'm not sure what is going on there. It's talking about linking so maybe that has to do with creating symlinks to the version-specific gem files? I'm not sure how RubyInstaller does that kind of thing, but it might be from leftover files from your Ruby 2.5 attempts.

Sorry I can't be more helpful.
