### ISSUE TITLE
Use 'oj' instead of 'json' for Ruby json parsing

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1632]
`oj` is a faster json parser than the Rails default `json` gem: https://github.com/ohler55/oj

It's also now used by the i18n gem if available, the app uses a lot of i18n, so switching to it might result it a measurable performance improvement.

**Comment by ragesoss** [comment]
The main thing will be to find all the places that call `JSON` in the ruby code and replace those with appropriate calls to `Oj`.

**Comment by psinghal20** [comment]
Hi, @ragesoss can I work on this as well? The Rubocop rules issue is a little time-consuming. I will continue working on both these issues simultaneously if it is okay.

**Comment by ragesoss** [comment]
Yeah, sure. The rubocop thing should be done one PR per rule, and definitely don't treat it like you have to do all of them. They are too nice of tasks for newcomers to spend them all one person. :-)

**Comment by psinghal20** [comment]
Thanks! I have been through a couple of those, will save the remaining for the newcomers :smile:
