### ISSUE TITLE
Markdown images do not translate properly to wikitext

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#164]
In some cases, users may want to include an image (such as from Wikimedia Commons) in their course description. Pandoc does not handle this well, resulting in invalid wikitext image markup.

**Comment by ntdb** [comment]
Added the logic to do the image cleanup. The caveat is that images from anywhere other than Wikimedia Commons will not work and the alt text alone will be displayed.
