### ISSUE TITLE
Courses should be taggable

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#165]
We need the ability to flag courses that have certain characteristics. The single use case we need for the upcoming term is whether a class is working on medicine or psychology articles (yes, maybe, or no).

This is information that gets collected by the researchwrite wizard, but we don't retain or do anything with that information. The system should be able to add a medicine/psychology tag to a course via the wizard, and admins should also be able to manually add such tags.

**Comment by ntdb** [comment]
Thinking through this, I'm not sure that a tag system is the proper solution for the medicine/psychology use case in particular. Tags are generally binary: a model either has a tag or it doesn't. That covers the "yes" case, implicitly but indefinitely covers the "no" case, and doesn't apply to the "maybe" case.

Consulting with Riley and Ivan on this to see what we can come up with.

**Comment by ragesoss** [comment]
The idea there was to tag "medicine" and "maybe medicine", so separate
binary tags for each of those situations.

**Comment by ntdb** [comment]
From a data architecture perspective I don't love that approach (those options should be mutually exclusive by design) but it certainly seems like the best short-term solution. On it!

**Comment by ntdb** [comment]
Implemented this for the wizard such that tag models have a 'tag' and a 'key' that helps to maintain exclusivity when appropriate.

Front-end component allowing admins to edit these coming soon.
