### ISSUE TITLE
Limit course articles.json results for programs with huge numbers

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1656]
There are some P&E Dashboard programs with huge numbers of articles edited, such as this one: https://outreachdashboard.wmflabs.org/courses/CIS-A2K/Wikidata_India_Workshop

The `articles.json` query takes a very long time, and the app can't render so many articles without problems either.

The easiest solution would be to limit the query to some reasonable value (~500) and to show a message for courses with more than the lmit of articles edited to note that only that many are being shown.

**Comment by AmitJoki** [comment]
Where should the message be shown? Is there any utility for showing such messages?

**Comment by ragesoss** [comment]
The easiest way to handle the message would probably be to use the Notifications component. Search the code for places that use `addNotification` (in particular, search for `this.props.addNotification`).
