### ISSUE TITLE
Course overview should surface high-level information about course structure and progress

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#166]
The overview should give users a sense for which stage a course is at, and what needs to be done next.

As a starting point, one approach could be to include all the Milestones alongside the Description text, with a visual indication of which Milestones have already passed and which are still upcoming.

Later, it could incorporate more of the metrics we already know about courses, such as the number of expected students vs. the number actually enrolled (maybe with a prompt to update the expected number, if the date for the "students enrolled" milestone is already passed), training completion numbers, and number who have made userspace edits, and the number who have more than X characters of mainspace edits.

**Comment by ntdb** [comment]
Short term design solution: add Milestone Module to overview showing Week # and milestone description.

**Comment by rileywho** [comment]
Design solution for the sidebar Milestone module.
Previous weeks will have their opacity reduced. 

![screen shot 2015-08-04 at 12 38 31 pm](https://cloud.githubusercontent.com/assets/2120466/9070673/d14273f2-3aa5-11e5-8295-5253db933e8f.png)

Code behind the addition. (Was built with the inspection editor)
![screen shot 2015-08-04 at 12 38 46 pm](https://cloud.githubusercontent.com/assets/2120466/9070680/e361b1e2-3aa5-11e5-83e8-42531693458c.png)

**Comment by ragesoss** [comment]
Not sure what else we'd do with this one at present. We hit most of the objectives I had initially.
