### ISSUE TITLE
On /recent-activity pages, outbound links in the table row components should open in a new tab

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1664]
On the recent edits, Did You Know, and plagiarism pages, all the outbound links currently don't open in a new tab like they ought to.

**Comment by mauditecandela** [comment]
@AmitJoki AFAIK and remember, you don't need to add any seed data to get started. You can locally test your changes writing a react test and running jest --watch. Here more info about the test: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/testing.md

**Comment by AmitJoki** [comment]
@mauditecandela ah fine. I am new to the codebase and wanted to know what the outbound links are and which property is assigning those links so I could change them.

**Comment by mauditecandela** [comment]
I think @ragesoss can explain a bit more about that, I am not sure what does he means :)

**Comment by ragesoss** [comment]
Look at docs/user_roles.md for some info on getting example data into your environment.  That will be the easiest way to replicate this issue locally.

**Comment by AmitJoki** [comment]
@ragesoss thanks will look into it!
