### ISSUE TITLE
Add filtering by project to Articles Edited table

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1686]
The Articles Edited table may contain edits from multiple wikis. For example: https://dashboard.wikiedu.org/courses/University_of_North_Carolina_at_Chapel_Hill/Helping_Giving_Away_Psychological_Science_(Spring_2018)/articles

It would be useful to be able to filter it (with controls that only show up if there are multiple wikis present) to show one wiki at a time.

This will depend on ArticleStore being converted to redux first; then we can handle it pretty much just like the redux todo example plus a `reselect` selector.

**Comment by psinghal20** [comment]
@ragesoss I would like to work on this issue. As the article store is based on `StockStore`, I think it would be a major step towards migration to Redux. I think all the stores utilizing the stock store can be converted to redux easily if one is converted successfully.
I plan to: 
- Move all the stock store utilities in a common `stock_utils.js`.
- We can also separate the sorting functionality using the `sortByKey` method from `model_utils` as we do for recent_edits.
- Make separate reducers, constants for every store utilizing the StockStore. (I can make separate PRs for every store)

I will start with the `ArticleStore` required for this particular issue. We can add a selector with the sorting selector available on Articles tab. As the article state also has the project field, we can easily implement a state-based filtering on the client side.

**Comment by ragesoss** [comment]
Sounds good. Don't implement more for Stock Utils than you need. Much of
StockStore is not needed.

-Sage

**Comment by psinghal20** [comment]
I will start working on this issue again. I found that Amit Joki was working on the conversion of ArticleStore in one of his PR so I figured that I should wait for him to complete his conversion.
