### ISSUE TITLE
Activity tab does not show all recent activity

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#171]
See for example: http://dashboard-testing.wikiedu.org/courses/University_of_Oregon/African_American_Women%27s_History_%28Spring_2015%29/activity

There are no mainsapce edits shown, and the most recent edit is from 04-03. However, the students have been active (and working heavily in mainspace) through mid-June: http://dashboard-testing.wikiedu.org/courses/University_of_Oregon/African_American_Women%27s_History_%28Spring_2015%29/students

@ntdb This is an important bug, but not an urgent one. We can tackle this after the wizard / course page stuff that is more relevant for instructors setting up courses over the summer.

**Comment by ntdb** [comment]
This turned out to be a quick fix: the activity wasn't properly ordered by date. It's still limited to the 50 most recent revisions.
