### ISSUE TITLE
replace jquery-ujs with rails-ujs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1710]
`rails-ujs` is what is now maintained within rails core, and it does not depend on jquery.

This blog post has a section on rails-ujs that may be helpful: https://medium.com/@coorasse/goodbye-sprockets-welcome-webpacker-3-0-ff877fb8fa79

**Comment by psinghal20** [comment]
@ragesoss As the previous PR for this issue was closed, I tried taking this on. I hope it is okay.
