### ISSUE TITLE
CampaignEditable generates a warning

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1715]
For CampaignEditable in edit mode, I get this console warning:
```
Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>. See CampaignEditable > Popover > tbody > Select > div.
```

**Comment by psinghal20** [comment]
@ragesoss The thing is we can not keep a div element as a child of a tbody element. It must always be a tr element and tr element can only have a td element as a child. The warning is due to rigid structure of table element in HTML.

**Comment by mauditecandela** [comment]
@psinghal20 thanks for the hint. I will work on this today
