### ISSUE TITLE
Home wiki for a course should be changeable

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1741]
Currently, the home wiki for a course is set at the time of course creation, and cannot be changed. It would be useful to allow instructors/facilitators to change this.

**Comment by psinghal20** [comment]
@ragesoss I would like to work on this issue. I have found that wiki_title from basic_course model and home_wiki.base_url is used to generate the Wiki URL needed. To allow the change in Wiki URL we can change the wiki_title from basic_course which would require a change in slug field in the Course model or we can add a URL field in the course model and change that when the user needs to change the Wiki URL. I would prefer the second way ie. adding a URL field in the course model as slug field is used in several places such as alerts and surveys.

**Comment by ragesoss** [comment]
I think you could just implement a universal version of `Course#wiki_title` and remove the type-specific implementations.

Basically, a course should have a wiki title if it has edits enabled and the home wiki has edits enabled. Otherwise, it should return nil.

**Comment by ragesoss** [comment]
Yes, that sounds good.
