### ISSUE TITLE
Error message for no default campaign is unhelpful

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1749]
After you finishing setting up a dev environment initially, loading the app will result in an error message about no campaigns. It actually means that the default campaign does not exist, so even if you create a campaign you will not necessarily fix this problem.

The handling of this error in `RescueDevelopmentErrors` should just create the default campaign, instead of displaying an error message.

**Comment by AmitJoki** [comment]
What will be the parameters of this default campaign?

**Comment by ragesoss** [comment]
Basically, the slug needs to match `ENV['default_campaign']`. If it does that, it should just work.

**Comment by AmitJoki** [comment]
Where should it redirect after creating the default campaign in the rescue block?
