### ISSUE TITLE
Create new Course type for Wikimedia Commons upload campaigns

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1764]
Some events are specifically focused on commons. Users should be able to select Commons as the home wiki, so that edits from other wikis do not get pulled in.

This will require converting `CommonsWiki` to a database-backed normal `Wiki`.

**Comment by AmitJoki** [comment]
Can you please elaborate a bit? `CommonsWIki` inherits from `Wiki`, which is database backed, and since it is STI, we have already got `type: CommonsWiki` attribute on the Wiki table.

Am I missing something?

**Comment by ragesoss** [comment]
CommonsWiki inherits from Wiki, but is actually not database-backed itself. It's always used via `CommonsWiki.new`.

**Comment by AmitJoki** [comment]
That creates a `Wiki` record with type`CommonsWiki` right? Are you saying `CommonsWiki` should have its own database and not share Wiki's?

**Comment by ragesoss** [comment]
No, the idea would be to adapt Wiki to allow commons.wikimedia.org to be created as a regular Wiki record rather than a hard-coded subclass.

**Comment by AmitJoki** [comment]
Okay now I get it.
