### ISSUE TITLE
DatePicker reduces the value of input field by one when it goes out of focus

### ISSUE THREAD

**Issue by psinghal20** [WikiEducationFoundation/WikiEduDashboard#1767]
In DatePicker component, when the input field goes out of focus, it reduces its value by one day.
Step to reproduce the bug:
- Start creating a new course
- In the course start dates, select a date and then bring the date input field out of focus. You will see that the value of the input field is reduced by one of what you selected.
- Again, bring the input field in focus but don't change its values this time. Bring it out of focus to find that the value is again reduced by 1.

**Comment by ragesoss** [comment]
This is probably the same bug as #1234. It's related to timezones and translating from local time to UTC, and going from start-of-day for the course start and end-of-day for the course end, or some subset of those things.

**Comment by ragesoss** [comment]
Closing as duplicate. Please reopen if this is actually a different bug from #1234.
