### ISSUE TITLE
'Join' confirmation message should set expectations for activity tracking

### ISSUE THREAD

**Issue by srish** [WikiEducationFoundation/WikiEduDashboard#1768]
In the edit-a-thon (that I attended at SFMOMA recently) guidelines, it was mentioned that an editor should keep their dashboard window open in a browser tab as this helps track their edit activity on Wikipedia. 

If this is true, then a popup could be displayed at the top of the app window when a user logs in for the first time in the dashboard at an event. I noticed that many participants didn't read the guidelines at first, and didn't keep their tab open while they were editing. As the edit count in the dashboard does not update in real time, they were not sure if their edits were tracked or not.  

A message explaining how the participants' edit activity will be tracked might help add clarity.

**Comment by ragesoss** [comment]
@srish there's no need to keep the dashboard window open. Once a user joins an event on the dashboard, their edits will be tracked. I think keeping the window open was just suggested so that users can easily see the stats during the event (but not in real time, and only if they refresh).

**Comment by srish** [comment]
@ragesoss WOW! This is helpful to know. Thanks!

**Comment by ragesoss** [comment]
This can probably be done by expanding the `courses.join_successful` interface message to include more details about what the dashboard does.
