### ISSUE TITLE
For Editathons, dashboard stats should refresh automatically

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1769]
Now that we have a quick update cycle for short-running events, it will be practical to auto-refresh the course stats while a user has the overview page open. Re-fetching the course every 5 minutes or so might be all it takes to do that.

**Comment by vzhz** [comment]
I'd be happy to work on this next, if it isn't addressed by @AmitJoki 's fix on #1772 .
