### ISSUE TITLE
Setup script for yum/dnf based distributions

### ISSUE THREAD

**Issue by tuxology** [WikiEducationFoundation/WikiEduDashboard#1786]
It would be nice to have this for supporting Fedora. I will take this up. Feel free to assign me

**Comment by psinghal20** [comment]
Hi @tuxology, there is a setup script supporting Debian-based systems using `apt` as the package manager, I think they can provide you with a great starting point for the fedora-setup script. I think some of the code can be reused from there.

**Comment by tuxology** [comment]
@psinghal20 Thanks. I took that as a ref. Testing on a clean Fedora VM now
