### ISSUE TITLE
Containerize the application for easy setup 

### ISSUE THREAD

**Issue by tuxology** [WikiEducationFoundation/WikiEduDashboard#1787]
I was trying WikiEduDashboard, but it takes sometime to get all prerequisites for a dev setup on some distributions such as Fedora. It may be nice to containerize the build (preferably docker) for easy setup. We can also add a make target to build the docker image locally and run it. In addition, publish/maintain an image on dockerhub also. I can take a stab at it.

**Comment by ragesoss** [comment]
That would be amazing! I've spent a little bit of time playing around with trying to containerize it, but never got far enough for it to be useful.

**Comment by psinghal20** [comment]
Hi @tuxology, sorry for intruding but if you feel like pushing this task to someone else, I am up to work on it. I have been planning to learn more about docker but never got the start. Seems like a great opportunity to me.

**Comment by tuxology** [comment]
@psinghal20 I started with the dockerfile already. Trying to polish and shine :sparkles: my docker skills as well :wink:  But there is no dearth of new TODOs!  If @ragesoss  agrees, what we can do is file a new issue for preparing a Vagrant setup to create a reproducible dev/deploy environment for people who want to work on VMs or provision the app eventually on their own infra. This can be an addition to the scripts we already have. Can be a quick task as well. Shameless plug, but here is a small Vagrant ref I wrote sometime back : https://thenewstack.io/vagrant-developers-researchers/

**Comment by johncoleman83** [comment]
How is this update going?  What stage would the docker images/containers be used for?  Development?

**Comment by tuxology** [comment]
@johncoleman83 Sorry, I got context switched between other stuff and didn;t keep my promise :disappointed: I have a basic Dockerfile ready for testing. Was having some issues in the DB container (where I have to install and initialize the DB) I am trying to either separate the app/DB containers or would just put them in same container for testing. Expect some updates on this Sunday (1st April)

**Comment by yunjuc** [comment]
Hi, her is a quick intro to everyone. John is my friend and there is a docker hackathon coming up. We want to take the ideas of using docker to create a dev environment to compete, thus the questions.

**Comment by johncoleman83** [comment]
Thanks @tuxology... @yunjuc, I think for the docker hackathon we should wait for @tuxology updates & or use his branch if he isn't merging to master.  There might be a need to have this finished before the hackathon as well.  But there may be a chance to build off of their start of using docker.

**Comment by johncoleman83** [comment]
p.s. @tuxology I've had more success with DB's in their own containers (that's with mysql).  @yunjuc, I think you should definitely wait for these updates because they are doing exactly what you wanted to start.

**Comment by tuxology** [comment]
@johncoleman83 @yunjuc I have included a Dockerfile and a pre-built image to test with in #1844. Its pretty easy to use and spins up a dashboard. In the next iteration, I'd move the DB creation & migration part to a separate script to initilizae DBs independently of the app. I propose we get this in first though and then incrementally update it such that we have a dev/test as well as a deploy setup all containerized.  /cc @ragesoss
