### ISSUE TITLE
Extract user registration and enrollment functions from MassEnrollmentController into a service

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1796]
MassEnrollmentController has code to take a list of usernames and a course, and add all the users to the course, creating the users if they do not already exist in the database.

This should be extracted into a service object.

**Comment by ragesoss** [comment]
Also, the service object can be put to use in `setup/populate_dashboard.rb`. Not being able to call the controller method from that script while I was writing it was the motivation for this issue.

**Comment by srish** [comment]
I am almost done working on this issue, most likely will send PR tomorrow!
