### ISSUE TITLE
Implement ORES histogram plots in javascript

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1801]
Currently, we have some graphs that illustrate the distribution of ORES scores before and after a course or campaign. This is shown for individual courses on the Articles tab, the ORES tab for campaigns, and can also be generated with some customized parameters via `/analytics`.  All these plots are currently done with `HistogramPlotter`, which uses `Rinruby` to generate the graphs with `R`.

HistogramPlotter is more or less a giant hack, because I knew how to make the specific kinds of plots I wanted with R and ggplot2 — kernel density estimates — and Rinruby was the quickest way to connect R and Ruby.

The plots come out as PNGs, and the system has been unreliable. We could probably instead build a component that takes (more or less) the same data, and generate the plots client-side. (Vega.js, used elsewhere in the dashboard, is one option for doing so.) This would simplify the infrastructure, make the plots feel more like a normal part of the UI, provide a foundation for making the graphs interactive, and fix #1794 (if we don't find a fix for it sooner).

**Comment by psinghal20** [comment]
Hi @ragesoss, I would like to work on this issue next if no one is working on this. Currently, when I tried to access the ORES plots for a campaign in my master branch, I met with a 500 internal server error and the similar tech stack error as you mentioned on the other issue. Can you please elaborate more on the graphs that we are using as I am not much familiar with R and the particular estimates we are using. Any resources will help. I looked into the Vega examples and found that the Probability density function graph might be able to solve our problem.

**Comment by ragesoss** [comment]
A local 500 might be because you need to install ggplot2 in your R
environment.

**Comment by ragesoss** [comment]
Here's the Vega feature that looks like it's the relevant thing: https://vega.github.io/vega/examples/probability-density/

Basically, it's a smoothed histogram. `HistogramPlotter` uses R to do something similar, plotting two overlapping distributions: ORES wp10 aggregate scores before and after (either before edits from a course, or before edits during a campaign). (HistogramPlotter can do it as either a histogram, or a density distribution.)

Here are examples of the current graphs.

Density:
![spring_2017-ores-0-density](https://user-images.githubusercontent.com/848483/37617299-fa2e15ba-2b6f-11e8-9c0d-a9f78b7318c6.png)

Histogram:
![spring_2017-ores-0](https://user-images.githubusercontent.com/848483/37617262-dcf946d6-2b6f-11e8-99f4-b3ecbb994ac5.png)

HistogramPlotter uses a CSV of article data that includes the 'before' and 'after' scores. The idea here is to pass that same data to the frontend, and create similar graphs client-side instead. (Probably with two overlapping plots, one of the 'before' and one of the 'after'.)

**Comment by psinghal20** [comment]
Thanks for the info. I will take a look at the mentioned vega example for clarity. Will update you on my progress as soon as possible.
