### ISSUE TITLE
Add ability to view and set SpecialUsers via /settings

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1802]
Some users have specific unique roles on the Dashboard, such as being the recipients of certain emails. These roles are stored in the `special_users` Setting record, and are accessible via the `SpecialUsers` presenter.

The super-admin-accessible `/settings` page should display these special users and allow them to be set or changed.

**Comment by bekicot** [comment]
I'm currently working on this, do you mind to assign this to me?

**Comment by ragesoss** [comment]
@bekicot we don't usually use the 'assign' feature, but thanks for taking this on!

**Comment by ragesoss** [comment]
done!
