### ISSUE TITLE
Convert `/alerts_list` to React

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1803]
The /alerts_list view could be converted to React and reuse the new AlertsList component from Campaigns, which just a little extra work to allow it to do the additional things that /alerts_list currently does. Instead of linking to individual alerts, it can receive all the data for each alert, and render it view clicking a single alert or somesuch.

**Comment by chrisnorwood** [comment]
I'm digging into this one — quick question: are you interested in keeping the Search Bar (Multi-select + sort) for the "administrative alerts list", or just the list itself ?  The search & sort is pretty tightly coupled with some "campaign alerts list" specifics, in its current state
