### ISSUE TITLE
Provide a convenient way to switch between 'Wiki Education' and 'Programs & Events' configurations

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1804]
There are a number of different configuration options in the dashboard, mostly accessed via the `Features` presenter.

Many of these things — get help button, open course creation, language switcher, onboarding, default course type — no longer really need to be configurable independently. They are all one way on P&E Dashboard and another way on Wiki Education dashboard.

There should be basically one setting a developer can change to switch between the two configurations for all these things.

**Comment by AmitJoki** [comment]
Can you provide some sort of pseudo code as to how you're expecting to call the switch?

**Comment by ragesoss** [comment]
Probably the simplest option would just be to replace many of the ENV config variables in application.yml with a single one, `wiki_education = 'true'`. So to switch, you would change that value in application.yml.

**Comment by AmitJoki** [comment]
Where can I find Programs and Dashboard `application.yml` file?

**Comment by ragesoss** [comment]
There isn't one.

disable_help?, disable_onboarding?, disable_onboarding?, wiki_trainings?, enable_language_switcher?, enable_account_requests? ... should all be true for P&E Dashboard and false for Wiki Education Dashboard.

enable_get_help_button?, wiki_ed? ... should be false for P&E Dashboard and true for Wiki Education Dashboard.
