### ISSUE TITLE
User stats query does not work when username includes `&`

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1828]
This user, for example: https://outreachdashboard.wmflabs.org/users/Here&elsewhere

The username comes through as just `Here`, causing an error in the controller:

```
NoMethodError: undefined method `courses' for nil:NilClass
  from app/controllers/user_profiles_controller.rb:46:in `public_courses'
  from app/controllers/user_profiles_controller.rb:29:in `stats'
```

Either the username needs to be URI-encoded (on the javascript side), or the query can be done with POST.

To replicate this, add user `Here&elsewhere` to a course locally, and then visit `/users/Here&elsewhere`.

**Comment by psinghal20** [comment]
@ragesoss We can encode the username using `encodeURIComponent` method. I checked locally, worked fine. If you think using POST method is better alternative than I can try that instead.

**Comment by ragesoss** [comment]
@psinghal20 `encodeURIComponent` is fine with me.
