### ISSUE TITLE
"This course has no X" don't explain enough, and don't come from locales

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#183]
Some of the default "this course has no X" messages are not specific enough, like "This course has no articles" for the articles edited list. The uploads one is another case where some unpacking of what "uploads" means will be very helpful, since new instructors may think that uploads is for students to upload assignment files to be evaluated by an instructor (since that is what common learning management systems have).

@ntdb If you hook up the messages into the locale, I'll update the copy.

**Comment by ntdb** [comment]
@ragesoss The none and loading copy for frontend lists (assignments, articles, uploads, revisions) can now be updated by modifying the 'none' and 'loading' keys in the locale config.
