### ISSUE TITLE
Expected students input field in Edit details modal disappears when the input field is empty

### ISSUE THREAD

**Issue by psinghal20** [WikiEducationFoundation/WikiEduDashboard#1830]
When a user manually tries to enter the number of expected students in the input field, if the input field gets empty, the input disappears.
It maybe caused because the `expected_students` field value getting `null` in `details` component.
**ScreenShot**:
![expectedstudentsissue](https://user-images.githubusercontent.com/23720731/37631398-8803b756-2c0f-11e8-8be0-9a26002a72c4.gif)

**Comment by yunjuc** [comment]
I'll take a look at tihs.
