### ISSUE TITLE
RatingImporter.update_all_ratings is too slow

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1834]
Currently, the RatingsImporter.update_all_ratings step of `DailyUpdate` is quite slow on Programs & Events Dashboard, taking about 4 hours. I'm not sure, but I suspect there may also be memory bottlenecks from loading too many Article records into memory at once.

The main thing that will help would be to use threads to update the ratings concurrently. See, for example, RevisionScoreImporter.

**Comment by tuxology** [comment]
Since there is a `performance` tag on this, I have a moral imperative to try fixing this. In other words, I am on this 😉 Also, I will find why the loads were slow. Can you assign this to me?

**Comment by ragesoss** [comment]
Great! The individual loads are not particularly slow, I don't think... there are just a whole lot of them done in serial during the `DailyUpdate` process. I can assign this once you accept the invite to the github team.

**Comment by FatimaJaffal** [comment]
@ragesoss I think this is not resolved yet, no? If so, I would like to work on this.

**Comment by ragesoss** [comment]
@FatimaJaffal yes, it's not resolved yet. Go for it!

**Comment by FatimaJaffal** [comment]
@ragesoss any idea how can I re-assign it?

**Comment by ragesoss** [comment]
It doesn't need to be assigned.

**Comment by FatimaJaffal** [comment]
@ragesoss I will start working on it, thank you!

**Comment by prathamVaidya** [comment]
@ragesoss by using threads, you mean using sidekiq `perform_async` approach, right?

**Comment by ragesoss** [comment]
@prathamVaidya no, in this case I was referring to using Ruby Threads to execute multiple requests in parallel. I'm not sure how up-to-date this issue is, however; the code has changed significantly in the meantime. I don't think this is a major bottleneck currently, although changes in the meantime have removed the logging that would show how long this is taking in production. I'm closing it, as I believe it's no longer a problem.
