### ISSUE TITLE
Replace jquery-uls with a simpler dropdown language selector

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1842]
We're using a forked version of the Wikimedia jquery universal language selector to let users choose their locale. However, the global jquery dependency is not ideal, we can't easily update it because it relies on bootstrap class names that we changed in our fork, and we don't really need the full complexity of it. A simpler language dropdown selector would fine, and would let us cut out the separate jquery-uls.js script.

Something like the pageviews tool uses, including the link to translatewiki, would do nicely: https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&range=latest-20&pages=Cat|Dog

**Comment by srish** [comment]
I would like to work on this issue, and I've started to understand the code flow a bit.

**Comment by srish** [comment]
I am a bit stuck on this issue! So, following the same approach as Pageviews does, I considered writing a function in `/language_switcher.js`, make it extract all available languages (from `/i18n/ `) and then populate them in the drop-down selector. As a first step, I tried using the npm package glob. But, I am running into the following error: `Module not found: Error: Can't resolve 'fs' in '../Projects/WikiEduDashboard/node_modules/glob'
`

I'm wondering:
* First, is this the right approach I am following?
* If so, have we encountered such errors in the past while using a package that has fs dependency? What am I missing here?

**Comment by ragesoss** [comment]
@srish if you push your WIP to github, I can take a look.

There will be many ways of doing this. 

To recap the overall set of things going on:
* language_switcher.js uses jQuery to load and configure the language switcher and define the behavior when a language is selected. This is included in main.js, so it happens once when the page is loaded.
* uls_box.jsx is a React component that reloads/reconfigures it every time time it gets re-rendered. I believe this is a workaround so that it is able to work from within the React-based navbar, even if the page gets resized and the navbar switches from desktop to mobile layout.
* nav.jsx is the navbar, and it controls whether to include the uls-trigger button to which the language switcher attaches. (Language switcher is not present on the Wiki Education configuration.)

The approach I suggest would be:
* remove language_switcher.js and uls_box.jsx altogether
* create a new component, like `language_picker.jsx`, and insert that in place of the uls-trigger button in nav.jsx.
* As far as I can tell, none of our i18n files have the the names of the languages. ([Here](https://github.com/wikimedia/jquery.uls/blob/master/src/jquery.uls.data.js) is the ULS file where the code->name mapping is defined, as far as I can tell. Maybe [this module](https://github.com/meikidd/iso-639-1) or something similar could be used instead for that mapping.)
* To get the list of available languages, the easiest way is probably to rely on Rails: `I18n.available_locales` provides an array of language codes. We similarly make the list of wiki languages and projects available to the frontend in `app/views/shared/_head.html.haml`. You could make this available to the JS `I18n` global like this: `  I18n.availableLocales = #{raw I18n.available_locales.map(&:to_s)}`. (Took me a while to figure that out.)

**Comment by srish** [comment]
@ragesoss This information was much helpful! I've made some progress on this issue and my changes are currently [cooking up here](https://github.com/WikiEducationFoundation/WikiEduDashboard/compare/master...srish:language-selector). 

I've to do a few more things before sending the pull request:
* Include `Help translate` in the options 
* Add an icon beside the language selector
* Modify the test cases in `language_switcher_spec.rb`
* And perhaps some refactoring

**Comment by ragesoss** [comment]
Done!
