### ISSUE TITLE
Generate alerts when a student moves a page from User: or Draft: space into mainspace

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1843]
* Query for recent move log, since start of previous update cycle: https://en.wikipedia.org/w/api.php?action=query&list=logevents&letype=move&leend=2018-03-29T14:33:10Z&lelimit=500&lenamespace=118
* Match those against usernames from current courses (`User.current.pluck(:username)`)

**Comment by Adjoa** [comment]
Gonna be working on this. :+1:

**Comment by Aeropio** [comment]
@ragesoss  , Hello I am current outreachy applicant and wants to work on this issue, please let me know the steps to reproduce this in my local and also can you assign this to  me?

**Comment by ragesoss** [comment]
We got this in the form of the new de-userfying edit alert monitor.
