### ISSUE TITLE
Replace multiendpoint CoursesController#show action with separate actions for each

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1852]
A high proportion of traffic goes through the the `show` action, which is responsibile for variably rendering many different course-specific JSON views (see `SHOW_ENDPOINTS`).

Performance monitoring tools treat these all as the same endpoint, so it's not easy to single out performance problems with a single view.

Pulling the whole set of `show` endpoints to a separate namespaced sub-controller, and then making explicit actions for each one would probably be the best way to fix this. See also #1417

**Comment by jstoebel** [comment]
I'm going to take a stab at this one
