### ISSUE TITLE
When stats for a course are updated, there should be a visual indication of the update

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1853]
Some courses — editathons while they are going on, in particular — automatically refresh the stats while the home tab is open.

It would be nice to add some subtle visual indication when the stats change. I'm not sure what that would look like exactly. Maybe some CSS animation of the stats that fades out within a second or two. (It should only happen if the stats actually change, not when the stats get refreshed but did not change.)

**Comment by yunjuc** [comment]
How can I simulate the data update? I tried to add new editors to a course and ran `rake batch:update_constantly` but nothing changed?

**Comment by ragesoss** [comment]
@yunjuc there are two parts to this.

On the server, the stats need to actually change; that normally only happens if there are additional Wikipedia edits that happened since the previous update, but you can simulate it by directly modifying the `Course` record in the rails console. For example, `Course.last.update(article_count: 101)`.

On the browser side, if the 'home' tab of a course is open, it will request new course stats from the server every 5 minutes. You can change the interval to something short for testing in the `details.jsx` component. Then, shortly after you do an update to the `Course` record in the rails console, you should see the change in the browser.

**Comment by ragesoss** [comment]
@yunjuc `update_constantly` is a little different than it was a few months ago; it's no longer what fetches new data for courses. The easiest way to do that for a single course is to add `/manual_update` to the end of the base URL. The way we do it now on the server is via `rake batch:schedule_course_updates`; that puts all the courses that need to be updated into the Sidekiq job queue, but those jobs won't run unless you also start the right sidekiq workers to process them. (This reminds me that the sidekiq rake task needed an updated to account for this new course update architecture, which I just pushed a fix for.)

**Comment by yunjuc** [comment]
Ok, I'll try that. I'm also trying to find a way to re-format 1000 to 1k on the frontend. Right now it's done with `number_to_human` but the 'k' can't be animated because it's not a number.

**Comment by yunjuc** [comment]
Also, the `byte_added` count doesn't format the number so it runs long and overlaps with next number sometimes, like this one:
https://outreachdashboard.wmflabs.org/courses/Wikidata/Wikidata_WikiProject_India

**Comment by ragesoss** [comment]
@yunjuc the campaigns are currently all done server-side, but change the numbers for one of the courses should be all it takes to change the campaign numbers.

**Comment by yunjuc** [comment]
That's weird, I updated article edited count in one course, but the number is not updated on the campaign page. Maybe it's my database, it has been acting weird. 

I ran the setup script last week and my localhost changed from wikiedu dashboard to program & event dashboard with some old data carried over. I'll figure out what happened after I finish this.

**Comment by ragesoss** [comment]
There is a new setting in application.yml, `wiki_education = 'true'`, which controls whether it will be the Wiki Education Dashboard configuration or the Programs & Events Dashboard configuration.

But the campaign page should show numbers based on the courses in that campaign. `app/views/courses/_header_stats.html.haml` is the template that renders the aggregate stats for a campaign, and it does that by summing the numbers from the `Course` records. (See also `CoursesPresenter`, which is the `presenter` from that template.)

**Comment by yunjuc** [comment]
How can I insert a piece of jQury code into course page? I was able to add it to the campaign page, but can't figure out how to do it with course page.

**Comment by ragesoss** [comment]
I'm not sure exactly, but I think the generally idea would be to call some jQuery from a React component lifecycle callback, such as `componentDidMount`. That way it runs after the React component has already been rendered into the DOM, so that jQuery can find it and modify it. See https://reactjs.org/docs/integrating-with-other-libraries.html

However, I don't think this kind of thing should be done with jQuery for a React-based page. As much as possible, we want to have only React be responsible for DOM manipulation. (I also don't know jQuery well, and want to avoid adding new jQuery-based features since I'm not confident in maintaining it.)
