### ISSUE TITLE
Campaign Alerts list is not shown on mobile

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1856]
When it switches to mobile layout, the list just disappears: https://outreachdashboard.wmflabs.org/campaigns/artfeminism_2018/alerts

**Comment by wendyyuchensun** [comment]
Hi @ragesoss, I'm Wendy, a web developer from Taiwan. I came across this issue few days ago and found that I can fix it. I've created a [pull request](https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1859). Hope it helps!

**Comment by ragesoss** [comment]
Thank you! Does this affect the Articles list on a course page? I imagine
that class was reused here for convenience but was initially designed for a
different table.

**Comment by wendyyuchensun** [comment]
@ragesoss Let me have a look. I'll get back to you asap. :)

**Comment by wendyyuchensun** [comment]
Hi @ragesoss, the Article list should be fine. It does not contain any `<Alert />` component, which is what I've changed.
