### ISSUE TITLE
If a week has no blocks, you cannot drag another block to that week

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#186]
Breaking this out from #156, since it's as not design-dependent.

**Comment by ntdb** [comment]
Fixing this will involve adding a new "dragTarget" that appears in edit mode inside empty weeks. This will include writing logic that allows blocks to be added to a week with `{ order: 0 }`.

**Comment by ragesoss** [comment]
No longer an issue with the new Timeline arrange interface.
