### ISSUE TITLE
+ icon for Wiki Ed staff does nothing if no staff are present

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#187]
Since Wiki Ed staff are just course volunteers who have (Wiki Ed) in their names, maybe, so there's no flow for adding them directly? Anyhow, it's a little confusing. We should either remove the button, or make it work for Wiki Ed staff. Probably removing the button is the simpler option.

**Comment by ntdb** [comment]
In the linked commit I fixed the broken functionality of the button; it only appear for Wiki Ed staff or site admins.
