### ISSUE TITLE
Notification banner doesn't display properly on the Training page

### ISSUE THREAD

**Issue by yunjuc** [WikiEducationFoundation/WikiEduDashboard#1878]
On program & event dashboard, the notification banner is off place and doesn't display properly on the Training page.
https://outreachdashboard.wmflabs.org/training

**Comment by ragesoss** [comment]
This is because the training layout uses a completely separate stylesheet. Copying over the relevant styles from the main css to one of the training css files will probably fix it.

**Comment by yunjuc** [comment]
How can I create a notification?

**Comment by RDenPen** [comment]
I am fairly new to open source, and am currently working on this issue. I've been trying to modify the _training.styl files in favor of the notification problem but I am having trouble seeing any changes take effect when I run tests

**Comment by yunjuc** [comment]
You mean you can't see the notification or you can't see the style changes you made to training page? 

If it's former, you need to uncomment the sitenotice in ```config/application.yml``` file to enable the notification. 

If it's later, _training.styl should be right file.

**Comment by ragesoss** [comment]
Changes to a `.styl` file will only show up after the CSS has been recompiled, which happens via `gulp`. If you aren't seeing the expected changes in your development environment, make sure `gulp` is running in a terminal. On each save, you should see messages related to recompiled files.
