### ISSUE TITLE
Upgrade react-burger-menu and fix styling

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1881]
It looks like there's a style regression when the `react-burger-menu` node module is updated to the latest version (2.5.0 as of now). Perhaps some CSS class names or html elements changed, breaking our styling of the 'questions' input.

Run `yarn upgrade react-burger-menu@2.5.0` (or later, if a newer version is available), then start `gulp` to build the assets, then fix the styling regression.

Set `wiki_education: 'true'` in `config/application.yml` to make sure the input shows up.

The relevant styling is probably in `app/assets/stylesheets/modules/_nav.styl`.

Current (good):
![good burger menu](https://user-images.githubusercontent.com/848483/40810498-c8615a40-64e2-11e8-8b2b-c266840cd3da.png)

2.5.0 (bad):
![bad burger menu](https://user-images.githubusercontent.com/848483/40810511-d0494132-64e2-11e8-824f-f8c720c4715b.png)

**Comment by sospinar21** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by ragesoss** [comment]
@sospinar21 nope, no one else is working on this. Go for it! Let us know if you have any questions.

**Comment by sospinar21** [comment]
I fixed the issue but I was wondering if I can fix the margin/padding so that the search icon is centered and there is no blue to the left of the search input

**Comment by ragesoss** [comment]
Sounds good. Please do.
