### ISSUE TITLE
Campaign > Articles table runs over container range

### ISSUE THREAD

**Issue by yunjuc** [WikiEducationFoundation/WikiEduDashboard#1883]
The article table under Campaign > Articles is out of the border on the live site, but looks normal on the local dev environment.
https://dashboard.wikiedu.org/campaigns/spring_2018/articles

**Comment by ragesoss** [comment]
Hmm... I guessing it's from long course names in the last column. Maybe we can make it wrap instead?

**Comment by RDenPen** [comment]
I made an edit to the modules/_tables.styl file so that the td children of the .table class each had a padding of 12px 9px, which seems to pull the article table away from the edge of the screen

**Comment by RDenPen** [comment]
trying to make the class course_title fit in the container using word-break instead of making the padding smaller on .table which hasn't had results, however adding word-break to .table makes does have effect

**Comment by ragesoss** [comment]
@RDenPen it looks like the main way to make sure the table fits in the container would be to use `table-layout: fixed`. See https://css-tricks.com/fixing-tables-long-strings/

However, it looks like it'll take a lot of tweaking to get the cell sizing working nicely with the fixed layout.

**Comment by RDenPen** [comment]
so I made it so the element table had a table-layout of fixed this didn't stop the articles from spilling over. I also applied word-break: break-all then the articles didn't run over the container range

**Comment by siwaniagrawal** [comment]
The issue has been solved? If not can I contribute to it?

**Comment by ragesoss** [comment]
It has not been solved and you're welcome to work on it.  It's not as easy as I thought at first though.

**Comment by siwaniagrawal** [comment]
Well, I can give it a try :)

**Comment by siwaniagrawal** [comment]
![articles](https://user-images.githubusercontent.com/35132729/45948735-c9aa6100-c016-11e8-8e71-8fdf1a50b53b.png)
Is this okay? Or should I make some more changes?

**Comment by ihsavru** [comment]
@siwaniagrawal The courses column looks good. It will be great if you could do the same thing to the Title column.

**Comment by siwaniagrawal** [comment]
Actually, I am inspecting it in the browser, Can you please guide me through the process of feeding the necessary resources so, I can recreate the same in my local.

**Comment by siwaniagrawal** [comment]
![alerts](https://user-images.githubusercontent.com/35132729/45968284-25441100-c04e-11e8-8697-ce5708d58ef7.png)
Actually, adding the text-wrap wasn't enough I had to resize the width.
Will this do? Or should I change it?

**Comment by ihsavru** [comment]
@siwaniagrawal [Setup](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md) the dashboard on your local machine if you haven't already. Populate your database with some courses having longer names.

**Comment by siwaniagrawal** [comment]
![article3](https://user-images.githubusercontent.com/35132729/45968802-91734480-c04f-11e8-9390-13bf1a206059.png)
I realized using text-wrap along wouldn't be enough so, had to resize the width.
will this do? Or should I make some more changes?

**Comment by ragesoss** [comment]
@siwaniagrawal that looks nice.

**Comment by siwaniagrawal** [comment]
Cool, I will raise a PR after populating the DB and recreating it in my local.

**Comment by Rish-av4** [comment]
I don't understand the problem statement. Like where is the problem? A little help would be appreciated.

**Comment by fillingtothemomo** [comment]
If this issue is still open, I would like to take it. @ragesoss

**Comment by ragesoss** [comment]
This is fixed, I think.
