### ISSUE TITLE
Add Assignment input should convert Wikipedia urls into article titles

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#191]
Many users will cut and paste a url from Wikipedia. The dashboard — ideally the frontend, immediately on paste — should convert Wikipedia page urls into article titles.

**Comment by ntdb** [comment]
My current solution for this is to assume that the page title always comes after "/wiki/" in the URL. This seems to hold true for the various languages I checked.

**Comment by ragesoss** [comment]
Yes. There are edge cases, but I'm not worried about covering those. But it should verify that it's a link to the same language version of Wikipedia. People are likely to put in links from other languages, and these should not be converted (until we support multiple wiki languages)

**Comment by ragesoss** [comment]
Actually, it ought to be fine if a link to another language Wikipedia got converted using the language code in this form: es:Seattle

**Comment by ntdb** [comment]
So it's ok to assign articles from other languages as long as we store the title as "<language code>:<article title>"?

**Comment by ragesoss** [comment]
Yes. At some point, we'll want to actually include the language along with the title in our database, and track activity on more than one language version. This is relevant because some students will be doing translation assignments that involve editing more than one language.

But in the meantime, just being able to index which articles on other languages students are assigned will be useful. (Links on Wikipedia like that redirect to other languages: https://en.wikipedia.org/wiki/es:Seattle )

**Comment by ntdb** [comment]
@ragesoss This raises several issues that we can discuss this afternoon. For now I'll push my fix for the original issue without any language considerations and open a new enhancement.
