### ISSUE TITLE
Use of local time zone retrieval is causing a test to fail

### ISSUE THREAD

**Issue by NickSchimek** [WikiEducationFoundation/WikiEduDashboard#1918]
The test `./spec/lib/alerts/overdue_training_alert_manager_spec.rb:23` only fails after 5pm PST due to the way the `overdue` method retrieves the current date. 

The computed_due_date is a UTC date and it's being compared against a local time zone date, hence it only fails when UTC and the dev's local date are not matched.

File: `lib/training_module_due_date_manager.rb`
```
  def overdue?
    !module_completed? && Date.today > computed_due_date
  end
```

Is it possible to use Date.current ?

**Comment by ragesoss** [comment]
Whoops!

Looks like changing it to `Date.current` causes a different spec in that file to fail (when local and UTC dates differ).

We could change `Date.today` to `Time.zone.now.to_date`, and make the same change in `training_module_due_date_manager_spec.rb`.

**Comment by ragesoss** [comment]
(This has never showed up in CI because it runs on systems set to UTC, I think.)

**Comment by NickSchimek** [comment]
hmmm interesting. I didn't get any additional failures in that file when changed to Date.current, although Time.zone.now.to_date is fine too
