### ISSUE TITLE
Campaign should be included in course pages on-wiki

### ISSUE THREAD

**Issue by urbanecm** [WikiEducationFoundation/WikiEduDashboard#1942]
Hello, 

it will be great if campaign(s) can be passed to the course templates. Cs.wikipedia wants to have them displayed. 

Thanks!

Best,
Martin Urbanec

**Comment by garry329** [comment]
Can anyone elaborate on this issue?

**Comment by ragesoss** [comment]
The idea is that each active course is part of one or more campaigns. Each active course can have a mirror page on Wikipedia that includes much of the same content as the dashboard course page; this is generated by `lib/wiki_course_output.rb`.

This task involves updating that content to include the campaign names. This would probably be done as an additional parameter in the course details template.

**Comment by garry329** [comment]
So i have added the campaigns of a particular course as a parameter in the course_details method.Can you please tell me @ragesoss sir what more needs to be done?
![screenshot 2019-01-24 at 9 23 07 pm](https://user-images.githubusercontent.com/20072704/51690418-a4f2e400-201e-11e9-8f4e-71e832657046.png)

**Comment by ragesoss** [comment]
@garry329 yes, that would probably work fine. Probably a space after the comma in the `join` would be better.

**Comment by garry329** [comment]
Ok @ragesoss sir, so i am opening a PR to close this issue.Can you please also look into issue #2385 and tell me what's required?
