### ISSUE TITLE
Refactor UsersController into multiple controllers

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1949]
`UsersController` is somewhat too large and does too many things. In particular, `enroll` action and all the private methods that support it ought to be moved to a new controller, such as `Users::EnrollmentController`.

Relatedly, MassEnrollmentController and SelfEnrollmentController could be moved under the `Users::` namespace.

See also #1417 for a similar issue, and #1932 for an example of this type of refactoring.

**Comment by LuanvP** [comment]
I'll take this 👌

**Comment by chalchuck** [comment]
Hey @LuanvP @ragesoss is there any progress on this issue? {If not, I could pick it}

**Comment by LuanvP** [comment]
Ah yes I did this a while ago but never put the PR in, thanks @chalchuck

**Comment by LuanvP** [comment]
The PR is open here but I haven't had time to track down all the errors, @chalchuck feel free to try and fix that one or simply do over. Sorry for the delay

**Comment by hardy1334** [comment]
@ragesoss  I'll like to work on it

**Comment by Aeropio** [comment]
Hello @hardy1334 @ragesoss , is this iisue still open ??

**Comment by hardy1334** [comment]
@Aeropio  I'm already working on it, you can try some other issue. If I feel like not working on it,I'll let u know

**Comment by Aeropio** [comment]
okay sure @hardy1334

**Comment by AmitJoki** [comment]
@hardy1334 are you on it?

**Comment by Oghenebrume50** [comment]
@ragesoss is this issue still open?

**Comment by ragesoss** [comment]
Yes, it's still open.
