### ISSUE TITLE
Add an ImageViewer component to display more information about the uploads

### ISSUE THREAD

**Issue by ihsavru** [WikiEducationFoundation/WikiEduDashboard#1963]
On clicking an upload, the ImageViewer component pops up and fetches and displays extra information about that particular upload.
<img width="788" alt="screen shot 2018-08-06 at 9 41 25 pm" src="https://user-images.githubusercontent.com/22816171/43729806-08755604-99c7-11e8-8538-853b622bd509.png">

**Comment by solaomosola** [comment]
Hello @ragesoss, I do React. I like to help.

**Comment by ragesoss** [comment]
@solaomosola hi, and thanks for the offer to help! @ihsavru already has a mostly-complete patch for this issue, #1969, but feel free to browse the other 'React'-tagged issues and if there's one you'd like to try out, just say so.

If you'd like an invite to the development Slack channel for this project, please let me know.

:-)
