### ISSUE TITLE
anchor links to specific timeline weeks should scroll to the relevant week once the timeline loads

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1968]
Currently, such anchor links don't work because the timeline data isn't part of the initial render.

**Comment by AmitJoki** [comment]
@ragesoss I'll work on this.

**Comment by ragesoss** [comment]
@AmitJoki great! I'm not sure what the best approach is, so if you find any good ways of doing this feel free to post here before you dive into implementation.

**Comment by AmitJoki** [comment]
@ragesoss well, I was thinking of using [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) which has got good [support](https://caniuse.com/#search=scrollIntoView)

There's also polyfill solution if some very old browsers need to be kept in mind.

**Comment by ragesoss** [comment]
@AmitJoki I think scrollIntoView will be fine. I'm not sure how to cleanly handle firing that at the correct time, though, as it would only work after the timeline has loaded and the weeks have rendered.

**Comment by AmitJoki** [comment]
@ragesoss I'd like to see the behaviour firsthand. The project setup seems to be different this time around. I created a campaign and a program (BasicProgram) but there was no Timeline element anywhere. Can you show me the link of the live website where this is happening so I can have a better idea (and how to bring it up in development?)

**Comment by ragesoss** [comment]
@AmitJoki timelines only appear if a course has the Timeline Enabled setting, or is a ClassroomProgramCourse (which is the default if you set `wiki_education: 'true'` in `application.yml`).

You should be able to first enable the timeline via 'Edit Details', and then add weeks and blocks on the timeline tab. (If you create a new course in wiki_education mode, you'll be sent through the assignment wizard which can set up a full timeline automatically.)

Here's an example: https://dashboard-testing.wikiedu.org/courses/Hogwarts/Advanced_Spells_and_Potions_(Summer_2017)/timeline#week-9
