### ISSUE TITLE
Courses should have 'submitted_at' data

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1977]
It would be useful for Wiki Education staff to be able to see when a given course was submitted.

**Comment by khyatisoneji** [comment]
@ragesoss can you please let me know some reference files in which I can look for this issue.

**Comment by ragesoss** [comment]
The place to start is the `Course` model, and the associated `courses` table in the database.

The easiest way to handle this might be to insert the time of submission into the `flags` field. Setting a course to 'submitted' already triggers several other actions, and adding this data to the course record could be done at the same time. This happens in the `handle_course_announcement` method within `CoursesController`.

**Comment by khyatisoneji** [comment]
I have added the field to schema and course model. I have also run `rake db:schema:load` to use the new schema.

Where should I set the submitted_at field? Currently I am adding it in `handle_course_announcement` where I am doing:
```
@course.update(submitted: true)
@course.update(submitted_at: DateTime.now)
```
Also please guide me as to how I can test if my change works.

**Comment by ragesoss** [comment]
@khyatisoneji I think rather than adding another column to the database table, we can get by with inserting the time of submission into the course `flags` hash, which is a flexible way to store miscellaneous data that we don't need to query. That will basically look like:

```ruby
@course.flags[:submitted_at] = Time.zone.now
@course.save
```

There are many possible ways to test this (and it might be a useful exercise for you to try several of them).

To test it manually, set your environment to wiki education mode in application.yml, then create a new course and then submit it. After submitting it, you can use a rails console to check whether the data was saved as expected: `Course.last.flags` should include the `:submitted_at` key with the timestamp.

Another option, probably more complex than we want in this case, would be to add a test in `courses_controller_spec`. This would involve an update action where a course gets set to submitted, and checking after the controller action that the data was set as expected in the database record.

The last option would be to add a check for the expected data to a feature spec. `course_creation_spec` already includes a scenario of submitting a course. That's probably what makes sense to do as part of the PR.

**Comment by ragesoss** [comment]
No. "Submitting" a course happens separately from creating it. It
represents an instructor saying they've configured and customized their
course and are ready for it to be reviewed and approved by Wiki Education
staff. Courses on the global instance of the Dashboard don't go through
this step at all.

**Comment by jeffblack360** [comment]
Right. I mentioned that in my previous comment above. I was testing and observed the Submitted field in the form to toggle it from 'no' to 'yes'. The `Course` model would then have the `before_save` callback that could interrogate the value and supplement the `flags` column accordingly with a `submitted_at` value.  Correct?

**Comment by ragesoss** [comment]
@jeffblack360 a callback like that would work technically, but it would separate the business logic for that value from the rest of the things that happen when a course is submitted, which are all in that `handle_course_announcement` method in CoursesController.

**Comment by jeffblack360** [comment]
@ragesoss Thank you for walking me through that and helping me to understand.  I appreciate it.

**Comment by jeffblack360** [comment]
@ragesoss I have the source-code change working and tested; however I need to prepare a unit-test. 

When/If an Admin toggles the `Course` `submitted` to `false` the `submitted_at` key lingers around in `flags`. 

- Should the use-case include removing that K/V pair from `flags` under that circumstance? 

- Should the ability to change Submitted from `yes` to `no` be allowed?

**Comment by ragesoss** [comment]
> When/If an Admin toggles the `Course` `submitted` to `false` the `submitted_at` key lingers around in `flags`.

This is fine. The purpose of keeping this data is so that, in rare cases when we want to know when a course was initially submitted, we can look it up.

>  
>     * Should the use-case include removing that K/V pair from `flags` under that circumstance?
> 

No, I think treating it as 'write once' will make sense here. That could be a little more explicit if it's called `initially_submitted_at`.

>     * Should the ability to change Submitted from `yes` to `no` be allowed?

Yes. In some cases, we need to do that (eg, if an instructor needs to make some further changes before we can approve the course).

If it's `intially_submitted_at` as I suggest above, then it should also keep the original timestamp, even when it gets re-submitted.

**Comment by jeffblack360** [comment]
@ragesoss Thanks for the added color.  I've made the changes you suggested regarding `initially_submitted_at`.  I'll ensure that the data doesn't change when the `submitted` is toggled from `yes` to `no` and back again. 
Let me know if you have any questions.

**Comment by jeffblack360** [comment]
@ragesoss Do you think it would make sense to maintain a `:submitted_at` K/V in `flags` that is updated whenever the `Course` is submitted, in addition to the `:initially_submitted_at` for initial submission?
`flags: {`
`:submitted_at=>Wed, 26 Sep 2018 17:22:28 UTC +00:00,`
`:initially_submitted_at=>Sat, 29 Sep 2018 11:50:20 UTC +00:00},`
`}`

Had the thought during testing activities and thought I'd get your thoughts.
Thanks!

**Comment by jeffblack360** [comment]
@ragesoss I wanted to confirm the desire to display the `initially_submitted_at` timestamp on the `Course` details page, correct?

**Comment by ragesoss** [comment]
@jeffblack360 No, I don't think it should be added to the Details layout, as it's a case of information overload. Maybe later we'll come up with a better way of displaying the rarely-needed extra data for a course without stuffing it into the Details, but for now just storing it in the database is good enough.

**Comment by ragesoss** [comment]
Storing both 'intially' and the most recent timestap (`submitted_at` and `initially_submitted_at`) sounds good.

**Comment by jeffblack360** [comment]
@ragesoss Thanks for the direction sir. I'll proceed with the DB-related alterations only.

**Comment by garry329** [comment]
Is there any work left to be done on this issue @ragesoss sir?I would like to work on this one if there is.

**Comment by Aeropio** [comment]
@ragesoss  is this issue still open?

**Comment by ragesoss** [comment]
@Aeropio yes, it's still open.

**Comment by Aeropio** [comment]
@ragesoss  i will take this issue, please assign it to me if not already assigned

**Comment by ragesoss** [comment]
Go for it. Just leave a note if you move on before it's closed. :)

**Comment by Aeropio** [comment]
@ragesoss I will leave a note once I start working on it

**Comment by ragesoss** [comment]
This was done via https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2652
