### ISSUE TITLE
Number of trained students no longer accessible to screen readers

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#198]
The dashboard used to include the trained students popover in a format that got picked up by screen readers, but now the trained student numbers can't be accessed like that.

**Comment by ntdb** [comment]
I can't find a cause for this: the popovers used to show trained student counts transition from `opacity: 0` to `opacity: 1` and so should always be visible to screen readers. Has this been observed on both the index page (all courses) and the course page?

**Comment by ragesoss** [comment]
Helaine reports that it's working now. Maybe some cached .js?
