### ISSUE TITLE
Hide filters and category search feature under advanced search settings in article finder

### ISSUE THREAD

**Issue by psinghal20** [WikiEducationFoundation/WikiEduDashboard#1983]
Search filters and category search options in article finder are suitable for advanced users and can be hidden under advanced search options to simplify the UI.

**Comment by khyatisoneji** [comment]
I   would like to work on this issue. Kindly assign it to me.

**Comment by psinghal20** [comment]
Hi @khyatisoneji, We don't generally assign issues to any particular person. I think the article finder component would be the only one that would require any changes.

**Comment by khyatisoneji** [comment]
@psinghal20 Can you please clarify on how the UI would change? The current screen looks like this.

<img width="1183" alt="screen shot 2018-09-17 at 12 36 50 pm" src="https://user-images.githubusercontent.com/31898080/45609658-76fd0200-ba76-11e8-897a-f12f1fff95e5.png">

Out of this, what fields should be removed from main screen and only available under show filters.

**Comment by psinghal20** [comment]
We would like the option of category search to be visible under an Advanced Search option to simplify the search process for the user. The field to switch to category search should be hidden under the advanced search option. We can replace the show filters with something like `Advanced Options` and add the category search under that.

The initial screen will show only the Search bar, Submit Button and Advanced Search Options button.

**Comment by khyatisoneji** [comment]
@psinghal20 I have made changes.

The usual interface looks like: 
<img width="1120" alt="screen shot 2018-09-18 at 9 00 48 pm" src="https://user-images.githubusercontent.com/31898080/45699326-5ec8d800-bb87-11e8-8935-d1c76de119ea.png">

Also, the search results look like:
<img width="1220" alt="screen shot 2018-09-18 at 8 58 01 pm" src="https://user-images.githubusercontent.com/31898080/45699363-6daf8a80-bb87-11e8-880c-666d82d79d06.png">

Would like to know your views before submitting a PR.

**Comment by psinghal20** [comment]
Yes, the layout is okay!
Few changes I would recommend:
- Increase the spacing between all the three fields. It is looking very cluttered right now.
- Align the submit button with the search bar
- Change the title of the button to something like `Advanced Options`
