### ISSUE TITLE
Toggle article viewer instead of opening article in new tab in article finder

### ISSUE THREAD

**Issue by psinghal20** [WikiEducationFoundation/WikiEduDashboard#1984]
Currently, on clicking the article name in article finder results, a new tab is opened with the article. To promote article viewer among our users, we can toggle the article viewer if any user clicks the article name. External link to the article page can be provided in the article viewer.

**Comment by hardy1334** [comment]
@psinghal20  Can you please explain in detail this issue,I'll like to work on it

**Comment by psinghal20** [comment]
@hardy1334 I think this issue has been already solved by the takidelfin. I forgot to close the issue.
