### ISSUE TITLE
finish converting CourseActions to Redux

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1988]
We're nearing the end of converting to Redux from a Flux framework.

The last remaining function in CourseActions is `deleteAllWeeks`, which is called from the Timeline component. It isn't event handled by any Flux store, except in the case of an API failure. It can be converted to a Redux action in `course_actions_redux.js`. After that, the entire file can be renamed to just `course_actions.js`, since the old course_actions.js file will be gone.

Also, instead of doing a complete page reload (as currently happens after the action resolves), the `timeline.js` reducer should reset the timeline.

**Comment by khyatisoneji** [comment]
I am submitting a pull request where I have added the deleteAllWeeks function to use redux. I have not yet renamed the course_actions_redux to course_actions. If the implementation looks correct, I can go ahead with that.
