### ISSUE TITLE
convert many ServerActions functions to redux

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1995]
As part of the migration from Flux to Redux, we need to rewrite all the remaining Flux actions as redux action creators. Several miscellaneous actions in ServerActions are not actually handled by Flux (except in the case of request failures) and can be easily converted to redux.

In particular, replace all the usages of:
* `ServerActions.deleteCourse`
* `ServerActions.updateSalesforceRecord`
* `ServerActions.notifyOverdue`
* `ServerActions.greetStudents`
* `ServerActions.remove(` (which can be replaced by a more specific redux action creator for the one place that uses it)

**Comment by khyatisoneji** [comment]
I will look into this.

**Comment by khyatisoneji** [comment]
I have two queries regarding this.

1. In remove function, we are using actionType as `${model.toUpperCase()}_MODIFIED`. Now this is only called with user model. Should we use the same actionType and only add USER_MODIFIED as actionType or should we change actionType to something else.

2. After changing flux functions to redux, I noticed that In `side_link_spec`, we are doing `global.sinon.stub(ServerActions, 'fetchTrainingModule');`. How will this change after we have replaced flux with redux?

**Comment by ragesoss** [comment]
@khyatisoneji 

1. The action type should be changed to something more specific, like USER_REMOVED.

2. The training-related functions will be converted as part of #1989 rather than this issue. That will likely involve passing the connected redux function to the SlideLink component, so in the spec we'll be able to pass a mock function instead of stubbing a global object like in the current spec. See `available_article.spec.js` and its use of `jest.fn()` for an example of this.

**Comment by khyatisoneji** [comment]
@ragesoss In `side_link.spec ` file, we are stubbing fetchTrainingModule as it will be called by `training_slide_handler` file.

As `training_slide_handler` component is a root level component, it imports the function and mapsItToProps on its own. So as it doesn't expect fetchTrainingModule to be passed as a prop, can we completely remove it?
