### ISSUE TITLE
Users should be able to toggle gradeables between points and percentages

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#200]
Some instructors already orient their syllabus around percentages, so it is more intuitive for them to also manipulate the grades in the timeline in those terms.

**Comment by ntdb** [comment]
@ragesoss I think percentages are definitely the most intuitive way to present grading. I'll adjust it to allow the total to be greater than 100% and present the inputs as percentages rather than points.
