### ISSUE TITLE
Add pageviews for articles under 'FIle Usages' in UploadViewer component

### ISSUE THREAD

**Issue by ihsavru** [WikiEducationFoundation/WikiEduDashboard#2003]
![](https://user-images.githubusercontent.com/22816171/43729806-08755604-99c7-11e8-8538-853b622bd509.png)
One possible way to achieve this would be how [GLAMorgan](https://tools.wmflabs.org/glamtools/glamorgan.html) does this. It uses [Pageviews data](https://wikimedia.org/api/rest_v1/#!/Pageviews_data/get_metrics_pageviews_per_article_project_access_agent_article_granularity_start_end) from the Wikimedia API.

**Comment by Cressence** [comment]
Hello @ihsavru ,I will like to look into this.
