### ISSUE TITLE
'Credit' column data overflows in the Uploads table

### ISSUE THREAD

**Issue by ihsavru** [WikiEducationFoundation/WikiEduDashboard#2004]
Under list-view of Uploads, sometimes the table overflows horizontally due to the Credit being too long for certain uploads in the list.
<img width="1680" alt="screen shot 2018-09-20 at 11 45 55 am" src="https://user-images.githubusercontent.com/22816171/45799384-f2ef8800-bcca-11e8-9982-0400fd7a6963.png">

Similar issue happens for Articles Table in campaigns, read more here: #1883

**Comment by ShivangiKakkar** [comment]
@ihsavru Hey, May I work on this issue?

**Comment by ihsavru** [comment]
@ShivangiKakkar Sure!

**Comment by siwaniagrawal** [comment]
![articles](https://user-images.githubusercontent.com/35132729/45948671-910a8780-c016-11e8-8085-c476fa572eba.png)
Is this okay? or should I make some more changes?

**Comment by siwaniagrawal** [comment]
Hey! @ihsavru  I was going through this issue, I inspected it in the browser and intend on adding required wraps. Can you please guide me through the process of adding necessary resources so, that I can access the respective page in my local.

**Comment by ShivangiKakkar** [comment]
@siwaniagrawal I am working on it :)

**Comment by siwaniagrawal** [comment]
oh okay :)

**Comment by ragesoss** [comment]
It's not just the 'Credit' column that can cause overflow. Another situation is that before the thumbnail has been fetched, the filename is shown in the first column, and that may be longer than the image width. So the 'Image' column is extra wide until the file is loaded, and this may cause the table width to jump several times, as the longest remaining filename changes.

Long filenames with no dashes can also cause the `File Name` column to be too wide without wrapping.

Here's a good page to see all that behavior: https://outreachdashboard.wmflabs.org/courses/Uffizi/WDG_-_AF_2018_Florence/uploads

Especially, eg, pages 4 and 5.

**Comment by Sanjana1308** [comment]
@ragesoss before:
![screenshot from 2018-09-25 23-41-03](https://user-images.githubusercontent.com/31213584/46034027-41fb4a00-c11d-11e8-913d-c4e8b30c2d9a.png)

Thank you for reviewing my pull request. As my prior observation, the upload column had either taken just long texts or links which were creating issues which I fixed. But , then I noticed the credit column  could take even images.
I tried to run it locally but I could not get the data to be uploaded so that I could test it. Could u help me with the data uploads locally so that I could work over that issue too?

**Comment by Sanjana1308** [comment]
fixed #2010 AFTER:

![screenshot from 2018-09-25 23-42-51](https://user-images.githubusercontent.com/31213584/46034954-84be2180-c11f-11e8-81b8-28395ae0c03a.png)

**Comment by helenatxu** [comment]
Hello is this issue already fixed? It appears as still Open...

**Comment by Sanjana1308** [comment]
It's open

**Comment by helenatxu** [comment]
Hello @Sanjana1308 are you still working on it?

**Comment by Sanjana1308** [comment]
No

**Comment by shipcy** [comment]
May I work on this issue?

**Comment by ragesoss** [comment]
@shipcy go for it

**Comment by mcastorena0316** [comment]
@ragesoss  hi, my name is Melissa and im from the new batch of Outreachy applicants. If this issue is still open, can I work on it please? Thanks!

**Comment by ragesoss** [comment]
@mcastorena0316 it's still open. Please post here if you start work on it (but please don't work on more than one issue at a time).

**Comment by mcastorena0316** [comment]
Yes i want to start working on this. I will work on one at the time. Thanks!

**Comment by tichnas** [comment]
Can I take up this issue if it's still available?

**Comment by ragesoss** [comment]
Yes (but please don't work on more than one issue at a time)

**Comment by tichnas** [comment]
@ragesoss  What exactly should be the solution for jumping table width (https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/2004#issuecomment-424097675)? The only possible solution I can think of is to give a Loading message until everything is set up.

**Comment by ragesoss** [comment]
A loading message would be okay, or the filename could be truncated to a safe length, or it could be made to wrap at a certain max width so that it won't cause overflow.

**Comment by tichnas** [comment]
@ragesoss If we wrap (or truncate) filename to a fixed width, it will also wrap on larger images where it's not required. What are your suggestions?

**Comment by ragesoss** [comment]
I don't think the overflow while images are loading is a big deal, compared to the screenshots where it's overflowing after loading is complete, from the Credit column.

But if it's wrapping rather than truncating, that should be able to take the width of the cell, so it shouldn't matter how large the images are.

**Comment by tichnas** [comment]
@ragesoss I think overflow after the content is loaded (in Credit column), is already solved (https://github.com/Sanjana1308/WikiEduDashboard/commit/b2765c525d73c4bffa6d8347dddf62f5335b4738). Is there anything else need to be done?
