### ISSUE TITLE
Add summary data to CourseQualityProgressGraph

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2007]
![vega plot](https://user-images.githubusercontent.com/848483/45903174-9c9f4980-bd9d-11e8-81d5-4f1aa0520bf0.png)

The Vega plot of before-and-after ORES data doesn't include some of the summary data that the R version of this plot had. In particular, it should show the mean score before and after.

This could be done either in Vega, or just calculated separately and displayed conventionally with React outside of the plot.

The best way to play around with it in Vega is to use the online Vega editor. [Here's a spec with some arbitrary data matching the latest version of the component](https://vega.github.io/editor/#/url/vega/N4KABGBEDuCWAmAXAFpAXGAjABlwGnCmQFNYBzZRdMAJn0MgAcBDeeWAOzOoFYCJIAZ3IdmAG0HUA2oQjBIogLbFqkAEbMO8OElR4oAN3EBXFRkwBffhDDylZqIMTFGk-ZCNjT1HLiuzbBWZlVWUUAHt4SHdPbwwmeAAzSAtCAF1rSHhmRGZpANAbGyCQ+MZwzkQ3AIFY4kkMGSKiwuaiyGYAJ0RYAGMxYgB9HsQB1QAhcU1EAC8VazaBcM76wbViROWHAGZMADoANgAOI8wFxcgtwUHmROdO6m2aPYAWHiPt87b1AE9na9Y8GIUQwLzBX2aHW6fQGg2MnTEqkoiFcaAA9GjiMY9nAANawRjA2DMPbLMhovGwNGTMTTObRGqQ3rheGCByQf6INEAUQAqoNKYNmayhnAUALGDhIIyIP5FrYZcUuj1+kMRmN4gBpcJOYyDZCwJzLWC48IM+VLFbXdabFY+A57I4HbYHCHtK43O7EB4YGjbPbYACcgbOioEaj+q0BwMemAA7G6ldDVXCEUjECjBOjMdjKYT2CSyRSTVTtbr9YbEMbTeaLZBhZ02apOTz+YKG2yBbBxdBJdhpfK5YtWvKoSrYer2QBZb24nJdbszZgAWkSxg4VVro49Nq21BeexDR2woYtUA9t3uPjjAe22BeifDkYBbBjvporrDUGVMKG8MR8TIqiGJYjiJb5sSpKdOSlJojOnRzrknSLiua4btUZ71iyjbsi2fJdviQrYZ2YrIBKUqKkObQjhcP4ppOqgAIK4j0ajhIMiScDWj7nlaawbHuvr+i8QafphF5ej6tCBnsNB8F+vz-Dcr4gmAYJHDxY6-qmAFEBmwE5mB+IQYW0HFviaLMax7GcRw3EKR2uH1Fy+HtsRordmRvYUYOiY0d8dETt2GpQAACswwhsVuFw7gJdrmDePDYAcgaaRJV6+g62w8C8p51hGSnRqpLwHA+CmBX+aaAfpWYgbm4FEqZMElmi4WRWammOc2zmtgRsBESKXY9n2A6LFRzT+ZCFXDMF7Jlogeq2fZ4l8bu8W0AecY0C8NBpXxl7etQNBHK8py7QpBVRip+4HGJdbTf+6aZtmoF5o1UHNRZ82LVxHUOe53VOL1bmDaR5H9pRfnlcmQWjNOmiwOEaidKh66bntqxrQ4mD7NscYnBjAKSUd-q4PemmXS+QLFeC0PjpVumQEBtWGW9BYfeZVJTgjSMo6uaMYXWXXxHhbYlgNOFDV5I2Q4qk3tNNDHxOM8JVCuc6MN24iwEuMyI9F3yxba2PPHGmCBudK1RsTmWHpgRxlZhlPKdT1D44790wwzT0Ga9DXs0WsEq90gjq8wmu5GIOvMHrf2YcLUCi31EskZ54OjW040tHT2lK1Amrh1rYiDII4R6+IgwABTEBwjBWswACUBuQkbglYNgjqBgcCYKelh1CXsSUHJb+XPi7b5gO8I+jg9VV6c9dVGQS72By1BcRxXpfl8X1e1-XTedQDIs9a54uOVL6ey-K8tJvTM1w0xLGwGxgymp0nThBu8y96tcUOH6exthHB4NPGK+0ba0H9GbUB3xnZFSOqVTSs9GbMxevVYyK8zKwSss-dib8P5f2bu0BOHIT5i0IufMG3kIa+Tljneis1H7WSIcUVu614yD2SqlH+1sMq0GeClC2FMx7wPMIGT49DYSPWqgvVm-tIKrwsjgqKh8RSAxcuQ-qlC07UIzs0LONgb4CEVow+IAB5LQXQhhkC6GoWALDLSYz-iTThw9Caej4R+PYmAcrCMKtdDAPBMB3Rnl7HSPsWZ+wwQHLBLULHZBWIMGxnQ7EOKgCQpOINJZUJlrQ6+ki1SmKgAAFRIIMAA6gaZwgwAByxAyAfzSZcX+xteAnT9C8HuVsiZ8LjB3HAcYQkXDgQEsAcYXhHG4ZhZBESXocCXiZDmsFSlDEqd2IYdSGlxyFkfROZDk7aOGj5MajI0gBHGpNEo7IsbNyENhXo7JyiVEFu0RAKMOCCFtIofI+TMKIB+ISVQzAyANPqTkb+mFOLEDEPABoYApDNKca09wbCVAZF7q4aQkBlCaGiI4RAQIDCQHRdMuFCKcUcDxUIAlxAiVnMHKc855xLn2CBcTCEdz4QPNUE89Cty3maE+csb5jQ6F-IBeyYFoKbHOCaVCmFZLEU9MOii8BV4SV1nCJixo2LiC4vcE4QlxKkGKopVSw1tLiWUUZUUC5jIrmqCBB87sPxbmly5Y8iofKOUCo+V8n5w4FL-MBfEJ1wh-lNOIAAD2cBuag8hhBkFEIzeA4RFDME4JXAA5FGwQvRxDECzU3Ax7QnAuDhQmkQ4hVBlsxSW4oYRkCRHjUIKtjNG3NvrQIdgThkJqGMD0T+8avwCDQr0QdlL4i4iBGk0dsBoWqSVfxZFI6oAaC0DoFALbE3JtUOu7QCAt2pDPMek5bR6U2Dtd8Vloaa7hp+B4lV9r3WdG5WUL16N7W+qFZ0EV8KxV1mDeyMNLrI0xprlQDAlak3VtDWmjNHBs25vzQMItKRNK1ora2mDjNMPoYUh21S0Hd3xEI-hzCPa3nPwHYjSdCozyjvXOO2jqhp0QoY5AeVi6+4PB4uGTQB7dDbrbXugTm7UCnoZVJ5oF7ZTMvtTeqAHBhXVp9e8n9f6miBvFSGqAIGI2aWjbGyDgQd2wb0-BzNOa80FrQ12-F5bhM4Zrc4OtmkyNQewyRqAZH7NZErH2mjQ6oOrs40xidqhlO-tU6Fs1nmzMpvnNmrGRapDYDSHsM19mBAWqJfFkToaktZpSw3NLGXcspC-JJ-RNrL3pEyDZgYZKCgKeCOyZDBb+UStUFHDgereP2veWQdk4nbmpvTZwFt2Rcg8o-W4KAXHFWoqpTx4lBiFB9AcG80wTKWvXra6oH4jX2OvO6-EXr-XblDfZCQcglArssi0NQbbxAOXjYQ8O0ci2A3XyyPOR1d7QPuC4wD51Eb7PyGm3kW9YPXXA-nTC0H97H0PGq0UWTdXbXyf26UdJ4QxDLC67p5p7Bd1vcs3RhFNz3AHQeBq9o12sUAGJu4HGIGoF4VKmfZRDPjK1tr6sMGYFG+o0h5DGgg3u8IGY03mpQ+147VK9ZaGjT4CwGrIADGG1oZrLRmnzrjSLLVy4Bh3CpZxMQjNmQE94+eRIiQ2QmewO4ZXQIo1q8FwIdNCFdeGK-Wd78Kw8gcsSB-P9kP-sw-veRyENdmQzpC6OYwjBpsOCMVAd38X5eqA62MeHC7VB1Bj6OV1WfOvxCO9n-PiOo+gb8z8Gg27s8V8VzEEwDhsB+Yt7pYj5mhDy+zdb5YWb9DFb-nZzS3ezEsF6KBzzReMAdx4GjzHNWsd7chEBoFQfbmh9l55qHSOXUo+L8UOPkQ0+KkgMn1Pn26yZ9M83jPreFsI8XUX+vTfy9QEr516vi79NXV69G8y8QpIBf889DB29qBO9J9YBLcnNvN+8C1B98dh9R9acJ8FIp8Z859AgF8wAl8V9ZRGRqsr1N8A8hAfhFA2JEQQ8w8ptI8oBeVNx1tz8E96MLgIN+5ODRxBBkBw408PBoD4hZ9X0xg-MH8E0n9IBc95hX8C94hls-NhB6R58RDaA-BNJS98CNC5IUV7dHdEC+9bsKAqALA-NTD7t1CvAHBl84CED8tnN4hjtUCbcR8wAx9jYsDIV4CxBp9mBZ8I0bC4hCDXgVC3lwhcQhCEsa0B8s0h9OgPCvCtgfDANwh8cehGBjDGZgAs1xhx8MBptjBFA9gTE4YLBKtpMBd19s5vgt8XDqDaDd8GCD8mCmA5tT8BB2DL9RxuCpJ08hABDdN5ACD6xYBxCVBJCv8wC5Dzc39VBVsVCdYhCCC6BYCFIdDRi9C+A7cHdiATNe8UFSAzCUhLCTjrDdDbDeAu8-Cci4iUCEi0CkiMDJI0ivs-CAigitjhDrjF9wiMNIjoj7iXD4jEjkjMDi1NIqxMiCQQSoA8jGI3iiicgSiyiwlJxKjiCwAV8yDPc8cOBOJuAoNUgLAgA).

Once you've figured out how to add the desired data to the Vega spec, those changes can be implemented in the version of the spec that is in the component.

**Comment by loalexandra** [comment]
Hi! I'd like to work on this issue. Can I?

**Comment by ragesoss** [comment]
Yes, please do. :)
