### ISSUE TITLE
Re-rendering of editors table in chrome

### ISSUE THREAD

**Issue by psinghal20** [WikiEducationFoundation/WikiEduDashboard#2012]
The Editors table for any course seems to re-render again and again when scrolled to bottom in chrome. This behavior was not observed in Firefox. The attached GIF shows the mentioned behavior for both browsers. It was most probably introduced when the sticky headers were introduced.

**Comment by ragesoss** [comment]
@psinghal20 this didn't come through as a GIF, just a single frame. I haven't been able to replicate the issue described. What version of Chrome did you see this in?

**Comment by ragesoss** [comment]
I did some work that reducers unnecessary rendering of the students components, but I don't know if that was related to the issue you observed or not. Anyhow, if you poke at this again, be sure to pull in the latest first.

**Comment by psinghal20** [comment]
@ragesoss Sorry for that! I thought I used a GIF. The issue still persists, I am attaching a video link here as it is much more visible in a video. https://drive.google.com/open?id=1OR6ct5-BDS1geJLd2DeqONp9OqFiz9hQ
