### ISSUE TITLE
Some test are failing when run in different timezone

### ISSUE THREAD

**Issue by Kachulio1** [WikiEducationFoundation/WikiEduDashboard#2032]
These are some of the tests that are failing when run in **East Africa Time (EAT)**

![screen shot 2018-10-04 at 10 52 58](https://user-images.githubusercontent.com/22243090/46460137-bdb36180-c7c3-11e8-9a0c-7b80f56422b4.png)

./spec/features/campaign_overview_spec.rb:212
./spec/features/campaigns_spec.rb:77
 ./spec/features/course_page_spec.rb:158
./spec/models/campaign_spec.rb:90
./spec/models/campaign_spec.rb:99
./spec/models/campaign_spec.rb:107
./spec/models/campaign_spec.rb:135

**Comment by chalchuck** [comment]
Hello @Kachulio1 @ragesoss please assign me to this issue.

**Comment by Kachulio1** [comment]
@chalchuck Great, you can work on the issue.

**Comment by ragesoss** [comment]
I think we've taken care of all the cases where this happened.
