### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [WikiEducationFoundation/WikiEduDashboard#2038]
First of all, thanks for Wiki Education Dashboard, and for everything else that the Wiki Education Foundation does.

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/WikiEduDashboard/pulls). I've ported the `nokogiri` one (#2037) across to this repo now because it's security related.

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having open source repos using Dependabot helps boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations, and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by ragesoss** [comment]
Thanks! I'll give it a try... just installed it.

I like the amount of detail in the PRs, with the changelogs and commits and so on... makes it super easy to review dependency changes.

**Comment by greysteil** [comment]
Awesome! I’ll try and pitch in and help review some of the initial ones. Thanks for giving it a try!
