### ISSUE TITLE
In 'Arrange Timeline' mode, long block titles break the layout for up/down buttons

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2058]
If a block title is very long, the buttons for moving a block up or down get squeezed to lines, and also overflow out of the block.

![button alignment](https://user-images.githubusercontent.com/848483/46630972-d3de5c00-cafa-11e8-9827-3b3b0bf30502.png)

Wrapping the title the same way it gets wrapped in normal mode would be better.

**Comment by cleverprogrammer402** [comment]
I will work on this issue

**Comment by shivanshbindal9** [comment]
@cleverprogrammer402 are you still working on this issue ?

**Comment by isunitha98selvan** [comment]
Can I work on this?

**Comment by ragesoss** [comment]
I'm pretty sure @cleverprogrammer402 is no longer working on it. @shivanshbindal9 @isunitha98selvan either of you should feel free to work on it. If you both find solutions, we can compare them; it's likely to be a pretty small change, so not too much work will go to waste.

**Comment by shivanshbindal9** [comment]
#2329 fixes this issue !! @ragesoss

**Comment by ragesoss** [comment]
I think this is taken care of now.
