### ISSUE TITLE
Upgrade Jeet to version 7

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2059]
We currently use Jeet 6.x to provide grid layouts in our CSS. Upgrading to the latest version will require some changes: the location of the files we need to import is different, and some of the functions that jeet provides are used in various stylesheets and need to be renamed (`cf()`, at least).

Migration guide: https://github.com/mojotech/jeet/wiki/Migrating-from-6-to-7

**Comment by aSquare14** [comment]
I would like to work on this @ragesoss :)

**Comment by hardy1334** [comment]
@ragesoss in this issue,we need to rename the functions for **jeet 7** and modify the import statements respectively, anything else ?

**Comment by hardy1334** [comment]
@ragesoss  I upgraded **jeet** version to **7.2.0** , css files compiled properly with no warnings or errors but the **grid layout** changes.

![screenshot from 2019-02-18 21-30-03](https://user-images.githubusercontent.com/31733278/52963017-b54f7200-33c4-11e9-93b0-a290bcbb3485.png)

**Comment by hardy1334** [comment]
#2516

**Comment by Tripathi-Vaibhav** [comment]
So after upgrading Jeet to 7.2.0 what exactly is the problem ?

**Comment by ragesoss** [comment]
Looks like this one is done, we just forgot to close the issue.

**Comment by Tripathi-Vaibhav** [comment]
Ok, No problem then.
Can you provide some basic bugs or issues in order to contribute to this project as I'm new to Wikimedia

**Comment by ragesoss** [comment]
This one you commented on might be a good place to start: https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/3643
