### ISSUE TITLE
In article finder, the numbers in the last two columns should be right-aligned

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2064]
For the pageviews, in particular, that will make it easier to compare numbers of different magnitudes.

Currently, they're left-aligned:

![alignment](https://user-images.githubusercontent.com/848483/46639168-7d344a80-cb19-11e8-9a9b-952ce15507bc.png)

**Comment by jaxgarry** [comment]
Hi!! 
I'd like to work on this. First timer here but I'll give it my best shot. Thanks!

**Comment by sagg155** [comment]
Hi!! 
How do i start fixing this bug ,i have cloned the repository in my local filestore.
So,which file should i see to fix this or from what part should i start knowing this issue.
Please help as i am a noob in open source.

**Comment by Jigar3** [comment]
I want to take this issue.

**Comment by Jigar3** [comment]
This is when aligned right
![right](https://user-images.githubusercontent.com/32068121/47444241-b0423380-d7d3-11e8-936b-d49412e9d210.png)

This is when aligned center
![center](https://user-images.githubusercontent.com/32068121/47444243-b0daca00-d7d3-11e8-9a7e-23a5cda3aa40.png)

Personally, I think center aligned is better.
What are your suggestions?

**Comment by ragesoss** [comment]
@Jigar3 I agree that, overall, the spacing looks nicer with center alignment; the whitespace is much more balanced that way.

The main idea here is that the pageviews should have their units aligned, because it makes it easier to compare numbers of different orders of magnitude. Since completeness score is almost always two digits, center alignment works fine there, but for the pageviews, I think the ideal layout would be keep the centering from second screenshot but to right-justify the values relative to each other.
