### ISSUE TITLE
Long page titles break the layout of UploadViewer

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2099]
Wrapping the page title should fix it.
![long article names in upload viewer](https://user-images.githubusercontent.com/848483/46887580-de5a6780-ce12-11e8-9fc2-e04ad2d7535d.png)

**Comment by DK308** [comment]
Hello is this issue available?

**Comment by ragesoss** [comment]
@DK308 yes, if you'd like to work on it, please go ahead.

**Comment by DK308** [comment]
Ok, I m going to solve this issue :)

**Comment by ragesoss** [comment]
@snehasi yes, please do! Sorry for the late reply; I've been on vacation and neglecting my inbox.

**Comment by utkarsh-raj** [comment]
Are you still working on the issue @snehasi ? If not, I would like to take up the issue @ragesoss ?

**Comment by twisted-sres** [comment]
Hey, I am an outreachy applicant, can I take this up?

**Comment by helenatxu** [comment]
Hello, I am an applicant for the Outreachy internship, can I take this issue for my first contribution?

**Comment by mariahajmal** [comment]
@ragesoss  Hi, Is this fixed? If not, can you please assign it to me

**Comment by kevinejiro** [comment]
Hi @ragesoss   This issue doesn't seem to be taken, can I work on it?

**Comment by ragesoss** [comment]
I believe this is partially fixed, but there there are some layout problems in some cases still. Feel free to explore it and make any improvements you can.

**Comment by Manasa2850** [comment]
@ragesoss can I work on this?

**Comment by ragesoss** [comment]
Yes, go for it.

**Comment by Manasa2850** [comment]
@ragesoss where exactly is this upload viewer? I created a campaign but I'm not quite sure how to proceed.

**Comment by ragesoss** [comment]
@Manasa2850 this can be seen on the Uploads tab of a course page (if the course has any uploads).

Try creating some example data (see the "Populate example data" section of setup.md) and then visiting http://localhost:3000/courses/Uffizi/WDG_-_AF_2018_Florence/uploads

**Comment by shipcy** [comment]
Can I take this issue?

**Comment by ragesoss** [comment]
@shipcy this one is already done.
