### ISSUE TITLE
secrets.yml should not be checked in

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#210]
According to this comment in the file,
```
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
```
it seems that we should not include the file in the repo, and the initial gulp compilation step or something should generate random secrets.

**Comment by ragesoss** [comment]
The way that we've set it up, it just references the environment variables. So we're not actually keeping any secrets in this file.

**Comment by adamwight** [comment]
Looks like we do keep secrets for a development environment, however.  If there are other assumptions like this, maybe we should recommend never exposing a development server to the public?

**Comment by thenickcox** [comment]
The only thing in there is our secret token, which [has security implications](http://daniel.fone.net.nz/blog/2013/05/20/a-better-way-to-manage-the-rails-secret-token/). We should regenerate that and move that into an environment variable, too.

**Comment by thenickcox** [comment]
@ragesoss We vote to close.
