### ISSUE TITLE
"Step 1 of ?" at the beginning of the wizard is confusing

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#212]
Perhaps we should either not show that at all until we know the number of steps, or we should use a visual representation of the steps instead of text, so that it can smoothly transition from two (known) steps to all the steps.

**Comment by ntdb** [comment]
My quick fix for this is to show "Step 1", "Step 2", "Step 3 of 6", for instance.

**Comment by ragesoss** [comment]
That's perfect, I think.
