### ISSUE TITLE
Assignment dates should be integrated into assignment type choice

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#215]
Choosing assignment dates is closely connected to assignment type, so it probably makes sense to have these take place during the same step. We also need to enforce a minimum assignment length for the 'researchwrite' assignment type.

**Comment by ntdb** [comment]
We spoke about this today and came to the conclusion that assignment dates (the weekday picker, the day picker, the course dates, and the assignment dates) should be presented in such a way that they are clearly course-level items. This probably means showing them immediately after (or as part of) the course creation flow and NOT showing them on subsequent openings of the Wizard ("Add Assignment").

**Comment by ragesoss** [comment]
Probably not going to do anything about the current design, unless we do a more general redesign of the wizard.
