### ISSUE TITLE
Fall 2014 data on production is not complete

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#216]

**Comment by ntdb** [comment]
The data starts right around the time that the backend jobs were first firing up. We had some code in place to pull old data but it definitely needs revisiting before letting it run again.

**Comment by ragesoss** [comment]
I'm not sure what I was thinking here, as we don't have a fall 2014 cohort in production at all. Did you remove that cohort, @ntdb, or was I just referring to something else (either staging, where it seems to be in order now except for listing zero articles created, but that's probably an artifact of the updates being stopped for old classes, or Spring 2015 on production, in which case it seems to have fixed itself).

**Comment by ragesoss** [comment]
Anyhow, I'm about to add the fall 2014 cohort to production and regenerate all the numbers for it.

**Comment by ntdb** [comment]
@ragesoss Perhaps the Fall 2014 cohort was still on production a month ago (it certainly was there at some point)? Not sure. :)

**Comment by ragesoss** [comment]
I think it was there only before we regenerated the whole database on production, which was much longer than one month ago.
