### ISSUE TITLE
The success messages in setup/win-setup.bat should check whether the command is really successful or not first

### ISSUE THREAD

**Issue by refeed** [WikiEducationFoundation/WikiEduDashboard#2171]
In https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/1012314716f98a58e3e84e01fb6689daffa0a1af/setup/win-setup.bat#L8-L10

I think, it's still not guaranteed whether the command `choco install ruby2.devkit --version 4.7.2.2013022403 -y ` (and the others as well) will run smoothly, if there's a problem such as connection problem, the command will be failed, and though the command is failed, it will still show the message `Ruby+devkit installed!`

In my opinion, the solution is, we should make the script checks whether the command is successful or not first, then the script should print a more appropriate message depends on which case is happened.

**Comment by ragesoss** [comment]
I think we're going to remove win.setup.bat instead, as it's currently easiest to get a dev environment in Windows by using Ubuntu with WSL 2.
