### ISSUE TITLE
Dashboard does not know or care when user's OAuth session has expired

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#218]
Many edits are not happening because OAuth sessions have ended. @ntdb This is top priority.

**Comment by ntdb** [comment]
On it!

**Comment by ntdb** [comment]
@ragesoss can you provide any specific examples for this? I can't find any evidence that Mediawiki OAuth tokens expire. I've also tested the case where a user explicitly revokes OAuth access for our application: it does lead to an exception (so I'll need to do some work to account for it) but Sentry has no records of this case.

**Comment by ragesoss** [comment]
I was told that this happens, but I'm not entirely sure. I'll ask around.
I've definitely seen cases where edits didn't happen, but there's no sentry
errors for those.

**Comment by ragesoss** [comment]
I'm still unclear about the details of this. There have certainly been cases where edits did not get made as expected, though. I'll start noting any new instance of that here, and hopefully we can narrow down the circumstances.

**Comment by ragesoss** [comment]
I'm now dubious about the title of this issue, but the symptom of edits that ought to happen and don't is still an important one that I want to isolate and fix.

**Comment by ragesoss** [comment]
I'm closing this, as we've got the edits that don't happen captured elsewhere, and no real evidence that this has actually happened to us.
