### ISSUE TITLE
Term field should have a default

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#219]
In most cases, whatever is coming next, Spring or Fall 201X, is what instructors will want to use here. Having a default will at least make the resulting page titles a little more consistent.

**Comment by ntdb** [comment]
Some ideas for implementation (no code): [erjjones/seasonsjs](https://github.com/erjjones/seasonsjs).

**Comment by ragesoss** [comment]
I think this is not worth doing, now that we have multiple course types to contend with.
