### ISSUE TITLE
Add more options for limiting/restricting Wikimedia projects used for tracking

### ISSUE THREAD

**Issue by Samwalton9** [WikiEducationFoundation/WikiEduDashboard#2198]
Per https://meta.wikimedia.org/wiki/Talk:Programs_%26_Events_Dashboard#An_option_to_hide_Wikidata - some programs may want to focus on only one Wikimedia project, or exclude a particular project.

**Comment by ragesoss** [comment]
This is on the radar, and something that we can hopefully get done sometime in the next six months or so. Here's the existing issue for it: https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/1301
