### ISSUE TITLE
Some alerts are not helpful

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#220]
Some of the simple information alerts — in particular, the success messages after adding a user to the course, and after adding a tag, are not necessary. The page updates to reflect the new information, so the popup could be removed without confusing users.

For some low-impact changes, we should probably do away with the entire confirmation dialog. Tags, in particular, could be done without requiring confirmation,

**Comment by ntdb** [comment]
I've removed the `confirm`s and `alert`s from tags and cohorts. Are there any other interactions you think we should dial back?

**Comment by ragesoss** [comment]
I think we can close it, and I'll open something new if/when we notice
something else.
