### ISSUE TITLE
Cloning doesn't work if new non-ASCII characters are added

### ISSUE THREAD

**Issue by Samwalton9** [WikiEducationFoundation/WikiEduDashboard#2230]
From [Meta](https://meta.wikimedia.org/w/index.php?title=Talk:Programs_%26_Events_Dashboard&oldid=18618003#Cloning_a_course_excludes_non-ASCII_characters):
- When a course is cloned (course_creator → clone an existing project) and then should be edited, it is impossible to edit or save ANY part of the text if any non-English characters are added. Those that were there earlier are fine and accepted.
- Since the courses are for official communication and promotion of Wikipedia in given language and Czech language has no transliteration rule for typical characters (šěčřžýáíéóťňďůú etc.) it is impossible to use the clone feature. This will definitely affect other non-English language users.
- The only way how to circumvent this is to create a new course and then to copy all the necessary data.
- Tested on Chrome version 69.0.3497.100 on Ubuntu 18.04/Linux

**Comment by Samwalton9** [comment]
Thanks Sage! Should this be live immediately, or do changes take some time to be pulled?

**Comment by ragesoss** [comment]
@Samwalton9 deployment is a manual process, but I just deployed so this is now live.
