### ISSUE TITLE
Convert all controller specs to request specs (or feature specs)

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2240]
Controller specs are no longer a part of Rails core, and *request* specs are the recommended replacement. We have a fairly large set of controller specs, and converting them to request specs may be relatively simple (and it would allow us to remover the controller specs gem).

Here's an example conversion of a trivial controller spec: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/155b0ee36032e9d6d32cdbf994889e4eac066121

Please convert one test file per commit. Before you take this on, post a comment to indicate which spec(s) you want to work on, to avoid duplication.

**Comment by aSquare14** [comment]
I'd like to work on this @ragesoss  !

**Comment by ankitkataria** [comment]
Hey @ragesoss! I would like to work on this issue. To start with I've changed the admin and alerts controller specs. I'll add more specs to the PR!
Also, I'd be grateful if I could get an invite of the Slack, looking forward to contributing to this project :smile:

**Comment by kammikulski** [comment]
@ragesoss hey! can I work on this issue? :smirk:


hello, @ankitkataria let me know, on which tests are you working on :wink:

**Comment by ankitkataria** [comment]
Hey @kammikulski Check my PR for the tests that I converted. [#2266](https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2266) :wink:
