### ISSUE TITLE
Improve layout of search bar in mobile phone screen.

### ISSUE THREAD

**Issue by aSquare14** [WikiEducationFoundation/WikiEduDashboard#2255]
The search bar is not proper. The search icon is in a new line. It can be reproduced by going to https://dashboard.wikiedu.org/campaigns/communicating_science/programs . 
![screenshot_20181129-161953](https://user-images.githubusercontent.com/22938709/49217152-dcfcf280-f3f2-11e8-8138-f36c5f95f496.png)

**Comment by shivanshbindal9** [comment]
@aSquare14 I would like to work on this issue!

**Comment by ragesoss** [comment]
@shivanshbindal9 go for it!

**Comment by shivanshbindal9** [comment]
#2320 fixed it!! @ragesoss

**Comment by shivanshbindal9** [comment]
#2321 Sorry, for the inconvenience . I have made all the changes. @ragesoss

**Comment by ragesoss** [comment]
Great, thanks!
