### ISSUE TITLE
Spiders visit /raw.json pages and cause errors

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#226]
See http://sentry.ragesoss.com:8080/wiki-ed/production/group/278/

**Comment by ntdb** [comment]
I suspect that this is due to the GoogleBot caching old JS for the page. I've secured access to Google Webmaster tools for the dashboard and will keep an eye on this going forward, it should just go away.

**Comment by ntdb** [comment]
It's been just about a week since this last popped up, I think it was just a case of a cached link in the GoogleBot JS renderer. All gone!
