### ISSUE TITLE
Talk page template does not get added if Article exists but Talk page doesn't

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#228]

**Comment by ntdb** [comment]
Reference: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/21a91da604772c8ee859bf75096499a26c508360/lib/wiki_edits.rb#L97-L148

**Comment by ntdb** [comment]
This could be the same issue as #237... hopefully the new error handling will reveal something helpful.
