### ISSUE TITLE
Move jquery-uls to the webpack config

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2312]
After a gradual process of removing other JS dependencies that used to be concatenated together into a vendor file (which was initially done with `bower`), all that we have left of this is jquery itself, which is put into the assets as 'jquery-uls.js`. This is currently just copied from the (specially-named) node modules directory where jquery gets imported, via the `jquery.uls.js` gulp task.

We can move one step closer to a webpack-only config (and maybe avoid some dev environment problems) if we get rid of this task, and instead use webpack to generate a jquery.js asset file.

This will involve:
* creating a jquery.js entry file in `app/assets/javascripts`
* removing the jquery-uls task from the gulp pipeline
* updating package.json to treat jquery as normal dependency instead of the current config that puts it in `@bower_components/jquery`
* adding the new jquery entry to the webpack config
* updating how jquery gets included in the haml view templates to use the new webpack output file

**Comment by devanshbatra04** [comment]
I would like to pick this issue up. My first.

**Comment by bhawna-singh** [comment]
@ragesoss I'm an outreachy applicant . Can I take up this issue if @devanshbatra04 is not working on it ?

**Comment by devanshbatra04** [comment]
@bhawna-singh yes sure go ahead, I got busy and could not get back. Have a look at my PR, should help.

**Comment by soumyaa1804** [comment]
I guess no one is working on it so I would like to take it up.

**Comment by ragesoss** [comment]
Great! The features specs should be a reliable indicator of whether it's
working properly.

**Comment by ragesoss** [comment]
This got taken care of as part of the complete switch off of webpack that Amit wrapped up in May.
