### ISSUE TITLE
Investigate replacing moment.js with date-fns

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2319]
date-fns is designed to be a more modular replacement for moment.js. Since we only use a small part of moment's functionality, we might be able to save a fair amount of bundle size if we switch. The biggest question is whether we'll be losing any i18n functionality.

**Comment by algomaster99** [comment]
Hey @ragesoss! I am a newcomer so I'm just giving my opinion. I think it will lose i18n functionality since only format function has i18n support in date-fns and this project has used many functions other than format.

**Comment by ragesoss** [comment]
I'm not sure where / if we use moment's i18n features, or how they get used. We have plenty of other i18n that isn't related to moment, but we need to survey how we use moment and what the date-fns alternatives would look like, including for i18n if necessary.

**Comment by hjhimanshu01** [comment]
Hey @ragesoss , I have used date-fns in development environment , though it reduces the build size considerably but I do think it doesn't support all the features of i18n till now.

**Comment by ragesoss** [comment]
@hjhimanshu01 thanks! So it looks like date-fns has some i18n support, but it's only available for a few languages so far. I'm also not clear on exactly what we're currently relying on in terms of moment's i18n, and how that would affect users.

**Comment by hjhimanshu01** [comment]
@ragesoss  , just skimmed through the components where moment was used , nowhere was the code exactly relying on the language or any other i18n feature which might cause a breaking change , I'm not sure exactly but I do think that date-fns might suffice the work .

**Comment by TheTrio** [comment]
This can be closed now
