### ISSUE TITLE
Notices (like the submit message) are easy to overlook

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#234]
Several instructors have not readily noticed the instructions in the notices that appear below the nav section of course pages.

In the case where a user makes changes to the timeline and then saves using the bottom save button, they do not get returned to the top of the page. This can lead to a sense of being lost, in terms of next steps.

In the longer term, we probably want to have a more sophisticated notification system. One option in the short term (which I'm not convinced is the right approach, but it might be) would be to make the notifications stick at the top of the screen (once they get that high), like the login/home bar.

This isn't a high priority right now, I just want to capture it as an issue.

**Comment by rileywho** [comment]
/* Note: This solution is still being thoroughly vetted but I wanted to share where I'm at.*/
Changes:
+ Remove course data summary if the course hasn't yet been approved
+ Green bar details:
- Total height: 80px
- Color: #BBDB94
- Text: Roboto, Normal, #000, font size: 17px
- Button: background #fff, color: #656e92

![screen shot 2015-08-04 at 5 49 57 pm](https://cloud.githubusercontent.com/assets/2120466/9075992/5884a878-3ad1-11e5-874f-6fee00cfd875.png)

**Comment by ragesoss** [comment]
I like this. It will work for the submit notice and the enrollment URL
notice, since in both cases there won't be any stats yet.

It won't work for other (not yet existing) notices that appear when a
course is already underway.

**Comment by ragesoss** [comment]
This looks great! I think it doesn't do enough to prevent the message being overlooked, though; I really like the idea of sticky header on scroll up as the next iteration. Not a priority for the time being, though.

**Comment by ragesoss** [comment]
Currently, we have the `Notifications` component as the first thing inside `app.jsx`, while the sticky nav header of course page is implement via `Affix` in `course.jsx`

On possible approach would be to shift the Notifications to live at the end of the nav, inside the `Affix` in `course.jsx`, and then add `Notifications` in the other higher level components are not part of the `Course` hierarchy in in the router (`router.jsx`).

Alternatively, the `Notifications` component in `app.jsx` could also be affixed, and then the one in `course.jsx` could be adjusted to play nicely with it.

**Comment by ragesoss** [comment]
* Move Notifications to course.jsx, in the nav section
* Add Notifications component to other routes besides Course
* Ensure that messages appear as expected on screen when screen is scrolled down (and they would be above the fold in the old design)

**Comment by FedericoEsparza** [comment]
https://youtu.be/d-8MafzIxIU?t=26m41s Some discussion and assignment in the 2017-02-21 AV Americas Scrum recording.

**Comment by FedericoEsparza** [comment]
https://youtu.be/d-8MafzIxIU?t=32m4s Further discussion. Same scrum.
