### ISSUE TITLE
Courses can be created with a space at the end

### ISSUE THREAD

**Issue by Samwalton9** [WikiEducationFoundation/WikiEduDashboard#2350]
[This](https://outreachdashboard.wmflabs.org/courses/Wikimedia_ZA/Afrikaans_Writing_Competition) course was initially created with an additional space at the end of the title, which meant the URL ended with an additional _. I've since renamed it, but presumably additional whitespace should be trimmed before course creation.

**Comment by garry329** [comment]
I have created a pull request which fixes this issue.I am new to wikimedia and open source contribution as well.This seemed like a good first issue to resolve.

**Comment by ragesoss** [comment]
There's already some client-side sanitation that is supposed to prevent this, but I'm not sure exactly how to replicate the trailing underscore bug... which I've seen a couple times recently. I'd love to know exactly what steps people are taking that causes that kind of situation.

**Comment by garry329** [comment]
This issue can replicated by adding a single space after course title or institute name in the course creation form.

**Comment by ragesoss** [comment]
Nice. I think this has been fixed and re-broken a couple times. I have a frontend fix ready, but we could do your backend patch as well just in case.

**Comment by ragesoss** [comment]
Okay, this now has re-fixed client-side sanitization along with new server-side sanitization just in case. I'm deploying the fix right now.
