### ISSUE TITLE
Create An Account Not Working From Instructors Dashboard

### ISSUE THREAD

**Issue by hardy1334** [WikiEducationFoundation/WikiEduDashboard#2353]
I have tried to Click on **Create an account** not working from Instructor's Dasboard but its not working,most of the time if a username entered is available,then I get the error **There was an error Couldn't create an account ** of the username I entered, and sometimes after entering username I see **_1**  in red color in the bottom of that card.    

![screenshot from 2019-01-05 20-45-33](https://user-images.githubusercontent.com/31733278/50725921-ab7ef180-112b-11e9-850a-f660aa5f6d52.png)

![screenshot from 2019-01-05 20-44-48](https://user-images.githubusercontent.com/31733278/50725929-b33e9600-112b-11e9-82c0-ffc9e4082785.png)

**Comment by ragesoss** [comment]
This feature requires that you have an OAuth consumer with account creation permission in order to actually create an account. It's not generally needed in development, unless you're working on that feature.
