### ISSUE TITLE
In supplementary onboarding for instructors, collect 'how you heard about us' details

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2362]
Currently, we have this question as a free text field, but the lack of structure makes it less likely to get useful details. We especially want to find out *who* referred them if it was a colleague, and what specific conference, workshop, etc, for the other common avenues.

Current version:

![supplementary form](https://user-images.githubusercontent.com/848483/50854970-6cbf8600-133b-11e9-95e9-b69c2c5f5b32.png)

This can probably continue to be stored as an OnboardingAlert.

## draft copy ##
How did you find out about Wiki Education?

* A colleague referred me (space to indicate colleague's name)
* Academic association (space to indicate which association)
* Conference (space to indicate which conference)
* University workshop (space to indicate workshop)
* Web search
* Other  (space to indicate where)

**Comment by hardy1334** [comment]
@ragesoss  I'll like to work on this issue
