### ISSUE TITLE
Super admins should be able to set the `default_campaign` via /settings

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2364]
Currently, the way to control the default campaign is to change it in `application.yml`.

This is something that should be controllable via the /settings UI instead.

It may require some caching to avoid needing to fetch a Setting record from the database on each query... possibly via another settings-related presenter that caches data as class variables.

**Comment by Cressence** [comment]
@ragesoss I would like to work on this but it seems like only super admins have access to the /settings path. Could you grant me access so I can work on this issue?

**Comment by ragesoss** [comment]
Set your User record to permissions: 3 to become a super admin.

**Comment by ragesoss** [comment]
This is done.
