### ISSUE TITLE
Add 'references added' stats to the Dashboard

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2385]
I'm not sure if this makes sense (or would be performant) for every course, or maybe just ones that opt-in, but we could get a mostly-accurate count of references added by using the ORES feature data that we already store for each article.

See https://meta.wikimedia.org/w/index.php?title=Talk:Programs_%26_Events_Dashboard&oldid=18784390#Using_the_Dashboard_for_#1Lib1Ref

**Comment by garry329** [comment]
So i looked into the features field stored in the revision model which contains a field indicating the no. of ref tags added in that revision.So we can find out the no .of references added by each user on each article from that.So, @ragesoss  sir can you give me  some clarity on how & where to represent this data?

**Comment by ragesoss** [comment]
Sorry, I must have missed this when you posted. Done now!
