### ISSUE TITLE
Custom name for courses

### ISSUE THREAD

**Issue by Aktron** [WikiEducationFoundation/WikiEduDashboard#2411]
Hi. Every course is always labeled as a course. This is great for educational courses, but confusing for participants of _every other activity tracked by the WikiEduDashboard_ What I would propose is a new label that can be added when creating a new course. It will give the user an option whether the activity is a course/contest/anything else. 

This basically means that "Course Activity" should be replaced with "$1 Activity" where $1 would be the value chosen in the way described above.

**Comment by ragesoss** [comment]
I'm not sure why I didn't remove the label altogether already, but I've just done that. Aside from the "course" language, it also doesn't provide any useful information as a label; the stats section is pretty self-explanatory.

I'll deploy the change soon.
