### ISSUE TITLE
Edits should never create an empty page

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2412]
In some cases, such as an assignment being added and then removed again before the edit job is run, the dashboard may create a page that doesn't exist already, but make it empty. Ideally, this should not happen; in such cases, it should just leave the page as a redlink.

**Comment by mcastorena0316** [comment]
@ragesoss  hi Sage,  Oureachy applicant here, can I work on this? Thanks and have wonderful weekend.

**Comment by ragesoss** [comment]
@mcastorena0316 go for it!

**Comment by mcastorena0316** [comment]
Hi @ragesoss  I am writing cause I have a few questions and  I want to understand more about this bug you are having.

I already clone and run in my local environment the application and do a little tryouts by myself. 

When I create a program, a page link appears so everyone can enroll in it.  If I tried to delete it directly from the program's page, it appears that I need to erase the campaign first, but when I enter directly to the campaign, I am able to remove it. 

I realize that when I remove it, I still am able to enter the course's link, even though it's already deleted. It this the bug you want me to work on? If not, can you please give me a little more info about it? I'm adding some pictures of it. Thanks! 

![Default Campaign Programs — Programs and Events Dashboard - Mozilla Firefox_008](https://user-images.githubusercontent.com/52794673/76133894-51541780-5fe0-11ea-8356-27040cb6745a.png)
![Default Campaign Programs — Programs and Events Dashboard - Mozilla Firefox_007](https://user-images.githubusercontent.com/52794673/76133896-51ecae00-5fe0-11ea-916c-c4cad0d50656.png)
![Test Program — Programs and Events Dashboard - Mozilla Firefox_006](https://user-images.githubusercontent.com/52794673/76133898-52854480-5fe0-11ea-86a4-58859e4243ab.png)
![Test Program — Programs and Events Dashboard - Mozilla Firefox_005](https://user-images.githubusercontent.com/52794673/76133899-52854480-5fe0-11ea-95bb-18c560738478.png)

**Comment by ragesoss** [comment]
Hi @mcastorena0316 !

This bug is referring to the edits to Wikipedia that the Dashboard makes. In particular, `WikiCourseEdits` makes edits on the wiki to reflect actions users take on the Dashboard, including the `update_assignments` method that posts templates to article talk pages when a student adds an article as their assignment. See the recent edits to this talk page for example: https://en.wikipedia.org/w/index.php?title=Talk:Education_in_Ontario&action=history

If a student adds an assignment, and then later removes it, the Dashboard will first make an edit adding a template to the talk page, and then later will make an edit removing that template. These edits are done through background jobs via Sidekiq.

The bug in this case is when a student adds an assignment, but then immediately removes it again, and the article they assigned doesn't even have a talk page yet (so adding the assignment should have started that talk page via the `update_assignments` action). If they remove the assignment before the job gets run in the sidekiq queue, then no template will be added via `update_assignments`. But the `remove_assignment` job (if it already started) may still execute, and since there's no template to remove, it will simply post an empty talk page... but that's different from a nonexistent page. So the talk page will exist on Wikipedia, but with no content and a useless edit in the history.

**Comment by Gaurav453** [comment]
Hey @ragesoss , Is  this  bug is still open and if yes should I try to fix this ?

**Comment by ragesoss** [comment]
@Gaurav453 go for it. It's still open.

**Comment by vaidehi44** [comment]
@ragesoss, seems like to reproduce this bug, I will have to first find an article which doesn't have a talk page. How can I find such an article?

**Comment by ragesoss** [comment]
I don't think it's necessary to have a live page without a talk page on Wikipedia production in order to fix this bug. While you won't be able to reproduce it in terms of configuring your dev environment to make live edits on Wikipedia — which you probably should not do anyway — you can still write a test for it by mocking the Wikipedia response for a non-existent page.

**Comment by ragesoss** [comment]
I think `WikiAssignmentOutput` is the place to start.

**Comment by vaidehi44** [comment]
https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/c722b4ccd37e6acf5bda04468289ddec83076d9c/lib/wiki_assignment_output.rb#L30-L38

@ragesoss, is this existing part of code related to this issue in some way?

**Comment by ragesoss** [comment]
Yes, this is closely related. There are a number of other situations where we already return `nil` from this method (which means, don't make an edit) because of the guard statements around here, but we don't handle the specific situation of trying to remove a template from a page that doesn't exist.

**Comment by gabina** [comment]
I'm working on this!

**Comment by gabina** [comment]
@ragesoss I opened a PR for this issue but have some concerns as I'm not entirely sure the PR addresses all the necessary changes. Appreciate your feedback whenever you have the time.
