### ISSUE TITLE
the message articles.views_added needs better plural support (or ignoring)

### ISSUE THREAD

**Issue by amire80** [WikiEducationFoundation/WikiEduDashboard#242]
The message needs proper plural support - many languages have more than just singular and plural. (Currently it doesn't even support English singular!)

On the other hand, if this is just a maintenance script message, then maybe it only needs to be English and then it should be added to "ignored" messages in translatewiki.

**Comment by ragesoss** [comment]
Thanks @amire80 (for this and the rest of the issues you reported)!

This one, and a few others, are maintenance script messages. How do I add such messages to the ignored ones on translatewiki?

**Comment by amire80** [comment]
- See the translatewiki repo in Wikimedia's Gerrit.
- Edit the file groups/Wikimedia/WikiEduDashboard.yaml.
- Search for 'ignored".
- Add the required keys.

**Comment by ragesoss** [comment]
Is this the right format, @amire80? https://gerrit.wikimedia.org/r/#/c/228995/

**Comment by amire80** [comment]
Looks sensible. I'll let @siebrand, @Nikerabbit or Raimond merge it.

**Comment by ragesoss** [comment]
Patchset 2 on gerrit covers all the maintenance script messages that I spotted.
