### ISSUE TITLE
In Timeline arrange mode, blocks with long titles have glitchy drag'n'drop behavior in Chrome

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2428]
Adjacent blocks with long titles that wrap end up overlapping slightly in arrange mode.

In Chrome (but not Firefox), dragging one of the overlapping blocks sometimes cause other blocks to shift position as well.

Part of the problem is likely the calculated pixel offsets (all the places that calculate based on multiples of `75`) in the default style for for the `Motion` element that wraps the reorderable block and elsewhere in a `Week` component.

**Comment by ragesoss** [comment]
Yeah, that would probably be better than the current situation, although truncating is likely to cause a bit of confusion in some cases.

If we go the truncation route, I think we should leave as much of the title in as will fit, least.

**Comment by bwreid** [comment]
Alright, after looking at the docs and the code a bit more, I think this connects with the problem from React Drag n Drop that I mentioned in PR #2273. Truncating does help with some of the dragging issues but sometimes the reordering of items ends up pushing other items around in unexpected ways. So weird that this is happening in Chrome and not Firefox.

I'm going to reference [this demo](http://chenglou.github.io/react-motion/demos/demo8-draggable-list/) for movement and see if I can't identify why this is happening.

**Comment by ragesoss** [comment]
Fixed with https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/efe92b07446f649ac226838fc489da71fe7efbd8
