### ISSUE TITLE
The messages assignments.assignees and assignments.reviewers need plural support

### ISSUE THREAD

**Issue by amire80** [WikiEducationFoundation/WikiEduDashboard#243]
If they will have proper support they won't need "(s)" in parentheses :)

**Comment by ragesoss** [comment]
These are column labels, so I think the solution is actually to just make it plural without parentheses.

**Comment by ragesoss** [comment]
Err... strike that. These are column labels, but each row can have 0, 1, or multiple users listed as reviewers or assignees. So the parentheses are used to signal to users that, even if a review is listed, it's possible to have multiple reviewers for that article.

I don't think there's a way to do plural support for this. It should just be translated in whatever way makes sense as a column label where each row can have have singular or plural entries.
