### ISSUE TITLE
Upgrade Rails to 6.0.0.beta1

### ISSUE THREAD

**Issue by faithngetich** [WikiEducationFoundation/WikiEduDashboard#2432]

**Comment by hardy1334** [comment]
I'll like to give it a short.

**Comment by faithngetich** [comment]
Hey, @hardy1334 I have a [PR ](https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2472)up for this. If you would like, we could pair on this issue else feel free to take it up. Let me know what works for you.

**Comment by hardy1334** [comment]
@faithngetich  ok,no problem as soon as i resolve it I'll let you know and we can pair it up if you want

**Comment by hardy1334** [comment]
@ragesoss  on Updating it to 6.0.0 beta1 following this blog [https://medium.com/@prrrnd/upgrading-to-rails-6-and-getting-started-with-action-text-7f50aafc8631](url) I updated but now when I run **guard** it gives error **`block in <class:Railtie>': Rails::SourceAnnotationExtractor is not a class/module (TypeError)** . I searched about it and as per [https://github.com/indirect/haml-rails/pull/150/files](url) we might need to upgrade **haml-rails** version to I guess _2.0.0_ [https://rubygems.org/gems/haml-rails/versions/2.0.0](url) which indeed requires updated **bundler** version. so shall I give that a short

**Comment by ragesoss** [comment]
Have you looked at the PR from faithngetich? It has the beta running successfully already. I think we're just in a `wait until the final release` stage of things with this.

**Comment by hardy1334** [comment]
@ragesoss  yeah I had looked at it , it works fine
