### ISSUE TITLE
Due date still visible when Block type is changed

### ISSUE THREAD

**Issue by shivanshbindal9** [WikiEducationFoundation/WikiEduDashboard#2452]
Once we change the block type of any block to "assignment" we can set its due date and it is shown alongside the Edit button. But as we change the type to any other type like "in class" or "milestone" still the due date is shown.
![issue](https://user-images.githubusercontent.com/35252539/52521458-70795c00-2c9d-11e9-8574-29bc4126d8e3.png)

**Comment by ragesoss** [comment]
Fixed.
