### ISSUE TITLE
Adding option to pause a program for instructors

### ISSUE THREAD

**Issue by hardy1334** [WikiEducationFoundation/WikiEduDashboard#2458]
@ragesoss  It's a good idea to add option to let instructors  pause a program,because if due to some reasons instructor wants to pause the program for some duration, and then continue the same course, he should be able to do that

**Comment by ragesoss** [comment]
Can you provide more detail on how you picture this working?

This is not a request we've gotten from any instructors or program leaders that I can remember.

**Comment by hardy1334** [comment]
@ragesoss  We can let instructors let pause a course for **n days** and then again continue.<br><br>
![dfl43cv](https://user-images.githubusercontent.com/31733278/52615694-14d8e980-2ebc-11e9-978b-72ccf8cf66ee.jpeg)

**Comment by ragesoss** [comment]
That sounds like a very complicated feature, if the idea is stop tracking edits during that paused period as well. Unless we hear from users who have a specific need for this, I think this isn't a feature that would be worth the extra complexity.
