### ISSUE TITLE
Minor typos while entering personal details in signup form

### ISSUE THREAD

**Issue by fliptrail** [WikiEducationFoundation/WikiEduDashboard#2459]
**Current State**
![screenshot from 2019-02-12 01-08-58](https://user-images.githubusercontent.com/40834245/52588627-ea0e7700-2e62-11e9-84a1-771e3bb43523.png)

**Proposed new state**
"First name and Last name:
Your real name is not public. It can only be seen by you, your instructor, and WikiEdu admins."

I would like to work on it.

**Comment by ragesoss** [comment]
I'm unclear: what are typos?

**Comment by boswellgathu** [comment]
@ragesoss @fliptrail meant grammatical errors

**Comment by ragesoss** [comment]
If you mean 'It is only seen' vs. 'It can only be seen', I think either is fine grammatically.

But I do notice one thing that should change: 'Wiki Ed' should be 'Wiki Education', as we've deprecated the use of 'Wiki Ed' as an abbreviation for the organization.

**Comment by mariahajmal** [comment]
@ragesoss Hi, Is this fixed? If not, can you please assign it to me

**Comment by bwreid** [comment]
@mariahajmal You're free to fix the change from 'Wiki Ed' to 'Wiki Education' if you like.

**Comment by mariahajmal** [comment]
> @mariahajmal You're free to fix the change from 'Wiki Ed' to 'Wiki Education' if you like.

@bwreid Please review and let me know if I missed anything. Thanks
