### ISSUE TITLE
Admins should be able to notice and act on requested accounts more easily

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2471]
On both production instances of the Dashboard now, we've got the requested accounts feature in use, but the biggest pain point seems to be account requests that never get processed; there are currently about 80 of them on Programs & Events Dashboard, likely because of cases where the program organizer didn't realize they needed to take action to create the requested accounts.

I'm not sure what the ideal fix for this is, but we need something to make it easy to act on the requested accounts that are pending.

**Comment by bwreid** [comment]
So we now have notifications for how many requested accounts are pending appearing on the main course page. If this is not sufficient and we need an additional way to notify instructors that these exist, the only other avenues we have would be email and/or notifying them via Wikipedia. It doesn't look like you need an email to sign up for a Wikipedia account but would that still be a reliable way to get in touch?

If so, we could likely do something similar to the Unsubmitted Course Alerts except for requested accounts.

**Comment by ragesoss** [comment]
We show them on an individual course page; I think the idea would be to highlight them in a system-wide way, so that an admin can notice when there's a requested account for a program they don't know about.

The recent change will probably take care of 80% of the problem for P&E Dashboard, but doesn't really help much for Wiki Education Dashboard, where the current best option is for staff to periodically check the campaign page for the current term (which links to the aggregate requests for all courses in that campaign).

**Comment by bwreid** [comment]
Thanks @ragesoss. So I think my current idea is to move another banner to the home page that will say something like "12 requested accounts pending." Then, it'll link to a new page that will aggregate all the requested accounts on one page.

**Comment by ragesoss** [comment]
@bwreid the home page (only), or the nav component?

This could be a good starting point for a notifications counter, if the nav does a query (for admins) of how many requested accounts there are.

**Comment by bwreid** [comment]
I was just thinking the homepage, but adding it to the nav would be great! I'll first start on just creating the new page and then will start to add to the nav.
