### ISSUE TITLE
Select component for setting the campaign does not use isMulti

### ISSUE THREAD

**Issue by bwreid** [WikiEducationFoundation/WikiEduDashboard#2498]
The implementation of the [campaign selection](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/components/overview/campaign_editable.jsx#L94-L103) appears like a multi-pick option but functionally acts like a dropdown in that you can only select one item at a time. 
![dropdown](https://user-images.githubusercontent.com/1316902/53039310-c84d5b00-3433-11e9-8147-fdfd5a1b5429.gif)
Is the intention here to make it look like you can type in it? It is possible to type in dropdowns as well.

**Comment by mariahajmal** [comment]
@bwreid Hi, I am an outreachy applicant. Can I work on this?

**Comment by shivanshbindal9** [comment]
@mariahajmal are you still working on this ?

**Comment by hjhimanshu01** [comment]
@mariahajmal @shivanshbindal9  if anyone's still working on this , please let me know , I have worked on a similar issue before and @bwreid ,  yes it is possible to search via typing in drop down . Can I take this up?

**Comment by mariahajmal** [comment]
Yes I have started working on this

**Comment by hjhimanshu01** [comment]
@mariahajmal , thanks , let me know if you need any help on this search . :)

**Comment by mariahajmal** [comment]
@bwreid I have edited the code but I am unable to find it on the website. Is it for instructor or student?

**Comment by ragesoss** [comment]
It's at the bottom of the Edit Details view. If you are an admin, or an instructor if the wiki_education setting is false, you should have access to it.
