### ISSUE TITLE
Change Subject field to a multi-select dropdown

### ISSUE THREAD

**Issue by bwreid** [WikiEducationFoundation/WikiEduDashboard#2499]
As a user creating a course, I want to be able to set my subject via a multi-select dropdown as opposed to having to enter free form text. At the same time, I want the option to be able to define my own subject if applicable. In general, the goal is to make course creation easier on the user and standardize our own data on the backend.

We should use the [react-select](https://react-select.com/) library to create the multi-select and can pull the list of subjects from the [wizard.yml](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/config/wizard/researchwrite/wizard.yml#L191) file.

**Comment by neozenweb** [comment]
Outreachy applicant here, waiting for an invite to contribute. I would like to take this up. Just forked and cloned the repo. Thanks.

**Comment by bwreid** [comment]
@neozenweb Now that you have things set up, I think this would be great feature to work on.

**Comment by neozenweb** [comment]
@bwreid  I have set up the dev on my localhost but cannot access course creator. The console shows a select statement for user=29 and the screen returns to the homepage. Here is the screenshot

![image](https://user-images.githubusercontent.com/37545009/53354866-c254ef80-38f5-11e9-8e2f-9ddd8cbe5873.png)

**Comment by neozenweb** [comment]
I have a few questions for this one:
1. I see that there is a separate course_level_selector.jsx component for the select element for the level. So for the subject, should I create a similar separate component or just use multi_select_field.jsx from the common components. 
2. How should I use the yaml file to populate this select field? Any examples in the code that have used this feature?
Thanks for your time.

**Comment by puthalalitha** [comment]
Hello I am an Outreachy student, and I would like to work on this issue. is it still open? I have my environment set up.

**Comment by bwreid** [comment]
@puthalalitha I believe this is still open, yes.

**Comment by puthalalitha** [comment]
I don't see a subject field in the current course/program creation flow. Below is the screen shot of that page. Am I doing something wrong? 
![Screen Shot 2019-10-16 at 9 30 23 PM](https://user-images.githubusercontent.com/43020183/66978557-41eb2680-f05f-11e9-8c70-bb36f963ceaf.png)

**Comment by ragesoss** [comment]
To see that version of the CourseCreator interface, you need to switch your development environment to `wiki_education: 'true'` mode in `application.yml`.

**Comment by puthalalitha** [comment]
Hi Sage Ross,

Thank you. Now I am able to see the CourseCreator interface. 

Thanks,
Lalitha

**Comment by katherine95** [comment]
@puthalalitha are you still working on this one?

**Comment by puthalalitha** [comment]
Yes, I am still working on this issue.

**Comment by tichnas** [comment]
Is this issue solved or can I take this up?

**Comment by ragesoss** [comment]
@tichnas you can take this up.

**Comment by puthalalitha** [comment]
Hi Sage Ross,

I am working on another project. I think I will not be able to continue with it as I am working on another project. 


Thank you,
Lalitha

**Comment by jonathan-richer** [comment]
I see that the course creation has been updated, but to edit the course, it's still a free form text input. I'll work on that if it's ok, and it so, please let me know if there's other places where it needs to be changed

Thank you

**Comment by UmerMIB** [comment]
Hi there, I am an outreach student, if this issue is still in a phase for development can I take it up?

**Comment by ragesoss** [comment]
> Hi there, I am an outreach student, if this issue is still in a phase for development can I take it up?

Yes, it's still open. Go for it! You might find it useful to look at #4018, which made some progress but wasn't merged.

**Comment by UmerMIB** [comment]
OK thanks

**Comment by ragesoss** [comment]
@vaidehi44 yes, it's open. Let me know if you get stuck on it.

**Comment by vaidehi44** [comment]
Thanks @ragesoss. I just had a doubt. It seems that dropdown has been implemented. So, I am supposed to enable multi-select and an option to set a user-defined subject, right?

**Comment by ragesoss** [comment]
@vaidehi44 you're right! I'm so sorry, I was wrong about this still being open. puthalalitha fixed it two years ago, and I missed closing it.
