### ISSUE TITLE
Improving UI of welcome page and add some validation

### ISSUE THREAD

**Issue by hardy1334** [WikiEducationFoundation/WikiEduDashboard#2517]
Once a new User enters his account , he see something like this 

![screenshot from 2019-02-23 21-49-36](https://user-images.githubusercontent.com/31733278/53288993-03de8100-37b6-11e9-93fe-180830083699.png)
 
- [ ] Its good to make its UI better.

- [ ]  User should answer atleast one of the two question asked in this

**Comment by hardy1334** [comment]
@ragesoss  can u have a look at it

**Comment by ragesoss** [comment]
This isn't specific enough to be actionable for the 'better UI' part. Do you have specific aspects that you had in mind that aren't good enough?

Having the questions be optional is intentional here.
