### ISSUE TITLE
Change passcode detail to be a link

### ISSUE THREAD

**Issue by bwreid** [WikiEducationFoundation/WikiEduDashboard#2520]
![image](https://user-images.githubusercontent.com/1316902/53359439-c9750100-38e7-11e9-8e59-981121c76d1c.png)

Most instructors don't need the passcode as much as they need the actual link to send out to students to enroll. When the details section is _not_ being edited, we should change the passcode from plain text to actually being the enrollment link. When editing, the regular fields should still show.

**Comment by twisted-sres** [comment]
Hey, I am an Outreachy applicant. Can I take this up?

**Comment by helenatxu** [comment]
Hello, I am an applicant for the Outreachy internship, can I take this issue for my first contribution?

**Comment by ragesoss** [comment]
@twisted-sres go for it! @helenatxu try that other one first?

**Comment by twisted-sres** [comment]
Hey, what are the steps to reproduce this?

**Comment by bwreid** [comment]
@twisted-sres If you create a course as an administrator, and then go to the course page, you should notice this navigation on the right-hand side. Let me know if you've created a course and you do not see it!

**Comment by hjhimanshu01** [comment]
@bwreid @ragesoss , shall I work on this if it's available?

**Comment by ragesoss** [comment]
@twisted-sres are you still working on this?

**Comment by ragesoss** [comment]
This is available. The discussion at #2556 will be useful for the next person to take it up.

**Comment by hardy1334** [comment]
@bwreid  @ragesoss  In this issue as for changing **Passcode** to **Enrollment Link**, so shall I need to remove Input of **passcode**  or something else from here.

![Screenshot from 2019-04-01 13-53-02](https://user-images.githubusercontent.com/31733278/55313619-d906dd00-5485-11e9-8954-407f5bc5c797.png)

**Comment by bwreid** [comment]
@hardy1334 You shouldn't need to remove the passcode field as instructors could still change it. The idea here is just to make it so that instead of copying the passcode, there is a link for instructors to use. Please check out Issue #2556 for more details.

**Comment by codingmamakaz** [comment]
@bwreid @ragesoss , Is this available? I'd like to try this one if it is.

**Comment by bwreid** [comment]
@codingmamakaz Yes, I believe this is still available! Thank you.

**Comment by katherine95** [comment]
Is this being worked on? I want to work on it as soon as possible

**Comment by ragesoss** [comment]
@katherine95 I don't think so. Go for it.

**Comment by AmitJoki** [comment]
Is this being worked on? I thought I could add it as a GCI task.

**Comment by ragesoss** [comment]
Sure, sounds good @AmitJoki

**Comment by urbanecm** [comment]
Hello @AmitJoki, could you please clarify the description a little bit? Keep in mind there is multiple codebases in GCI interface, so it is clear which codebase it is about. Also, I've removed the "is beginner" checkbox. Beginner tasks are far more simple, like "set up your dev environment" or "learn to use gerrit by sending a patchset". Thanks for mentoring this!

**Comment by AmitJoki** [comment]
@urbanecm sorry! I'll rephrase to make it specific. Also thanks for letting me know what a beginner task entails to, I'll be careful with that with the other tasks.

**Comment by Manasa2850** [comment]
Is this being worked on? Can I work on it?

**Comment by ragesoss** [comment]
We've already got an open PR for this that is probably going to be merged soon.
