### ISSUE TITLE
Add a question to course creation to obtain quarter/semester information

### ISSUE THREAD

**Issue by bwreid** [WikiEducationFoundation/WikiEduDashboard#2530]
On the "Create a New Course" form, for Wiki Education, we want to add a new form field that gathers whether or not the institution is on a quarter system or semester system. The field added should be a radio button with a label of **Academic System**, the only two options being **Semester** and **Quarter**. By default, **Semester** can be selected.

Check to make sure validation and cloning works!

**Comment by hardy1334** [comment]
But @bwreid  when user enters after creating account and if he chooses role of instructor ,I guess he is asked for what purpose he is here and how long does he intend to use this course. so,is it good idea to add this?

**Comment by ragesoss** [comment]
This is data we need for accurately analyzing the courses we're supporting.

**Comment by hardy1334** [comment]
okay, I got it @ragesoss
