### ISSUE TITLE
The message timeout needs correction and documentation

### ISSUE THREAD

**Issue by amire80** [WikiEducationFoundation/WikiEduDashboard#254]
The message currently says "A request to the %{api} API has timed out and will retried %{tries} times."

"will retried" is probably incorrect, but I'm not sure what will be correct, so it needs a correction from somebody who does.

It also has two parameters and both need documentation in qqq.

**Comment by ragesoss** [comment]
This is another message that isn't user-facing. It is used in error logging, and I added it to the ignored keys.
