### ISSUE TITLE
Within /article_finder, ArticleViewer permalink does not work

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2546]
The link feature in ArticleViewer is meant for the context of the Articles list. In ArticleFinder, it points to `/article_finder?showArticle=undefined`, which resets the article finder and does not display the article.

For ArticleViewer instances in the ArticleFinder, the link should not appear.

**Comment by helenatxu** [comment]
Can I try this one? I'm about to finish the other bug :)

**Comment by twisted-sres** [comment]
Hey, how do I reproduce this?

**Comment by bwreid** [comment]
@twisted-sres, I think @helenatxu might still be working on this one even though it's not listed here. Is that true, @helenatxu?

**Comment by ragesoss** [comment]
No, she's not.

@twisted-sres you can reproduce this by going to `/article_finder`, doing a search, clicking the title of one of the results to bring up the ArticleViewer, and then clicking the link icon next to the article title within the ArticleViewer.

**Comment by twisted-sres** [comment]
What is the link actually supposed to do?

**Comment by ragesoss** [comment]
@twisted-sres it was designed for use in the Articles tab of a course page, and lets you provide a link that opens a specific article: https://dashboard.wikiedu.org/courses/School_of_the_Art_Institute_of_Chicago/New_Histories_of_Chicago_Media_(Spring_2019)/articles?showArticle=51050930

**Comment by twisted-sres** [comment]
Okay, in the link you provided, when I click this icon, it takes me to the same page. Is it supposed to take me to it's wiki page?

**Comment by ragesoss** [comment]
No, it's working as intended. The idea is that it lets you share the ArticleViewer link, which (in the context of a course page) will load authorhsip highlighting data to show which parts of the Wikipedia article were written by which students in the course. The idea is that it's a shareable link that represents the state of the app: not just being on the Articles tab, but also having a specific article from the list open.

**Comment by hjhimanshu01** [comment]
@ragesoss , since this thread was inactive since days , fixed the issue , PR created.
