### ISSUE TITLE
ArticleFinder query parameters should be included in URL

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2547]
When an ArticleFinder query is executed, the URL should be updated with those parameters (search term, search type, and any thresholds for views or quality) so that the URL can be shared to replicate the query.

**Comment by hjhimanshu01** [comment]
Hello @ragesoss , May I work on this issue?

**Comment by tonynguyen111997** [comment]
Hi @hjhimanshu01, are you still currently working on this issue? If not I would like to pick it up.

**Comment by ragesoss** [comment]
@tonynguyen111997 it's still being worked on. See https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2550

**Comment by hjhimanshu01** [comment]
@ragesoss , PR merged for this issue.
