### ISSUE TITLE
In Course Dates interface, calendar should start at course start, not current month

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#255]
Currently, when I create a course that starts in a later month, then when I get to the Course Dates selection screen and click the meeting days, the calendar does not highlight those days... because it's showing the current month instead of the month containing the beginning of the course.

**Comment by ntdb** [comment]
Hm, would it be helpful to have it start at the course start or the current month, whichever is latest? That way instructors of courses that have already started would always be presented with the most relevant calendar.

**Comment by ragesoss** [comment]
Yes, that makes sense.
