### ISSUE TITLE
Users should be able to clear cached data for ORES plots

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2557]
`CourseOresPlot` is the frontend component for showing ORES "structural completeness" plots, which shows the aggregate change in ORES-estimated quality for the set of articles edited for a course or campaign.

Pulling together all the data needed for these plots — especially for large campaigns with perhaps thousands of articles — is a moderately expensive operation, and since some ORES data doesn't get refreshed more often than once per day, we cache the plot data on the server as a CSV file, and serve that up until the next day. (This is handled by `histogram_plotter.rb`.)

We often end up needing to get ORES data after adding a new course to a campaign, adding a new user to a course, and/or changing the dates of a course to get data for some specific timeframe. In this case, the cached data will be served unless it is manually deleted from the server.

`CourseOresPlot` should include a link to delete the cached data and refresh the plot, for cases like this.

**Comment by neozenweb** [comment]
@ragesoss I know that this is not labeled "newcomer friendly". But since no more of those are available, do you want me to try this one?

**Comment by ragesoss** [comment]
@neozenweb I recommend finishing up the WIP issue you've already started on first, but yeah, this one is relatively newcomer friendly. I didn't tag it as such because it involves both frontend and backend changes (and so requires an understanding of how the frontend and backend interact, and will involve changes to probably about 5 different files).
