### ISSUE TITLE
Update react-redux to v6

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2559]
A new version of react-redux has been released, but our build fails on it: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2558

The new version is probably compatible will our actual app code, but it has a new interface for `Context` and `Provider` that affects our tests. So many of the jest specs will need to be update to the new interface.

**Comment by hjhimanshu01** [comment]
@ragesoss @bwreid , just had a trial of this ,on running the tests bumped into an error 

``` FAIL  test/components/settings/add_admin_form.spec.jsx (20.485s)
    Method “props” is meant to be run on 1 node. 0 found instead.
at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1958:17)
      at ShallowWrapper.props (node_modules/enzyme/build/ShallowWrapper.js:1225:21)
      at ShallowWrapper.prop (node_modules/enzyme/build/ShallowWrapper.js:1445:21)
      at Object.prop (test/components/settings/add_admin_form.spec.jsx:38:49)
```

I'm basically passing the store to components via `<Provider store={store} ><Component /><Provider>` though Apparently , Shallow doesn't allows 2 components to be passed , so it just takes <Provider> component and returns the error (much harder to comprehend) . Any leads on how to proceed as Shallow is the last one left .

**Comment by ragesoss** [comment]
Have you looked at the v6 release notes? They seemed helpful in general, although there's no explicit upgrade guide: https://github.com/reduxjs/react-redux/releases

**Comment by hjhimanshu01** [comment]
@ragesoss , Yeah , referred them and many other docs , have opened a PR for the same , with work in progress , need your reviews on how to solve that particular issue.
