### ISSUE TITLE
Error when npm install

### ISSUE THREAD

**Issue by toniher** [WikiEducationFoundation/WikiEduDashboard#258]
I cannot finish npm install process. This is the error I get:

    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3
    npm ERR! code EPEERINVALID

    npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15

**Comment by ragesoss** [comment]
@ntdb, @adamwight, @thenickcox: have any of you run into this issue when trying to get your dev environment set up? Any ideas for what went wrong for Toni?

**Comment by ntdb** [comment]
Looks like this is the result of some [dependency version changes](https://github.com/nathanboktae/mocha-phantomjs/commit/297e1f2b06113886cb710647a4bc9ccc1dcf9dde) in these libraries. We're not actually using them but the easy fix seems to be updating them to the most recent versions (done: 1d7a594b2d2c9752fd93d5b11f6923f150a3b3fd).

@toniher let me know if you're able to run `npm install` with the latest from master.

**Comment by toniher** [comment]
It works! Thanks!
