### ISSUE TITLE
In Articles tab, navigation to Assigned Articles and Available Articles sections is hard

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2583]
This is what https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1950 tries to address, although there could be other possible solutions as well.

**Comment by bwreid** [comment]
What about just the following? I changed the style of the button to feel somewhat distinct from the "Get Help" button right above it. Clicking on each button would show the selected one. This also should narrow the screen any further.

![image](https://user-images.githubusercontent.com/1316902/54061296-1644bb80-41b5-11e9-816c-0ecf3e677aed.png)

For fanciness, I can try and add some transition effects.

**Comment by ragesoss** [comment]
works for me!
