### ISSUE TITLE
setup.md prerequisite requires wrong python version

### ISSUE THREAD

**Issue by tonynguyen111997** [WikiEducationFoundation/WikiEduDashboard#2584]
Hi, I'm an Outreachy applicant and I was wondering if I could make a PR to change the requirement from **python 3** to **python 3.5 or newer** in setup.md as my first "newcomer-friendly" contribution.

In setup.md it mentions having python 3 as a requirement, but when running python3 setup.py with Python 3.4.3 I ran into this error: 

![image](https://user-images.githubusercontent.com/36907562/53986636-98f54a00-40d3-11e9-956b-e23c00b552d0.png)

It says "AttributeError: 'module' object has no attribute 'run'

because the subprocess.run() function only exist in Python 3.5 and newer.

**Comment by ragesoss** [comment]
@tonynguyen111997 thanks! Please do open a PR for that.
