### ISSUE TITLE
Remove instructor-students from student counts and indicate them on the student list

### ISSUE THREAD

**Issue by ntdb** [WikiEducationFoundation/WikiEduDashboard#259]
Instructors who are also students in their own course are included in student counts and are shown normally in the student list. Let's remove them from the student counts and indicate their status visually on the student lists.

**Comment by ragesoss** [comment]
That change didn't have the expected effect. The fall 2015 cohort still says 5 students, but only one class (the one with a non-instructor enrolled as a student) has a non-zero student count. (Perhaps this is because the course has not started yet, so the caches are not being refreshed?)

**Comment by thenickcox** [comment]
Filter users with `CoursesUsers` for a course, but also a role 1 for a course.

**Comment by thenickcox** [comment]
The query for the `students` relationship [seems to already be taking `role` into account](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/models/course.rb#L47). I'm confused.
