### ISSUE TITLE
Upgrade react-dropzone to version 10

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2602]
The latest version of react-dropzone breaks the build: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2563

In particular, the test for the syllabus upload feature, which is the one place that uses this library, is failing.

Find out why, and fix it. It might require a code change, or it might require a change to the spec.

**Comment by mariahajmal** [comment]
@ragesoss Can I work on this?

**Comment by prionkor** [comment]
Upgraded on my local machine to dropzone `v10.1.9` the build process went nicely so does the tests. I am new to this repo so need to know which route does the dropzone appears so I can test if the upload working correctly.

So far no problem with `gulp`, `gulp build`.

Results from tests

```
Test Suites: 77 passed, 77 total
Tests:       264 passed, 264 total
Snapshots:   0 total
Time:        12.953s
Ran all test suites.
```

**Comment by ragesoss** [comment]
The test that breaks is one of the rspec browser tests: `syllabus_upload_spec.rb`

You should be able to test it manually by visiting a course page where you are the instructor and adding `?syllabus_upload=true` to the URL, which is the only way to access this feature.

**Comment by epleaner** [comment]
Hey, is this still needing work? I wasn't able to reproduce this locally using  react-dropzone@10.1.19 – test suite seems to be running green.

**Comment by epleaner** [comment]
Hey, is this being worked on? Happy to take a poke at it.

**Comment by ragesoss** [comment]
@epleaner go for it! Slack invite sent.

**Comment by ragesoss** [comment]
This is done.
