### ISSUE TITLE
Run gulp on server, remove built assets from repo

### ISSUE THREAD

**Issue by ntdb** [WikiEducationFoundation/WikiEduDashboard#261]
An ideal implementation will ignore specifically the following files/patterns and regenerate them by running `gulp build` on deploy via Capistrano.
* `/public/javascripts/main.js`
* `/public/javascripts/main-*.js`
* `/public/stylesheets/main.css`
* `/public/stylesheets/main-*.css`
* `/public/stylesheets/rtl/main.css`
* `/public/stylesheets/rtl/main-*.css`

**Comment by ntdb** [comment]
Note that we should also fingerprint `vendor.js`

**Comment by bmathews** [comment]
Fixed via a4bf6e8663fc54de657707f1c1b50ad8fd4c627d
