### ISSUE TITLE
Upgrade tinymce and @tinymce-react to latest versions

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2613]
It looks like tinymce version 5 has breaking changes — maybe just a change in location for the theme, or maybe more. See the gulp build errors here: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2607

Find and fix the cause of these errors with the new tinymce release, and manually test the timeline block editing feature where tinymce is used to check for differences in the user experience.

**Comment by hardy1334** [comment]
I'll like to work on it
