### ISSUE TITLE
Readme should document the commit pipeline

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#262]
In particular, it should cover the expectation that 'gulp build' be run before commits that change javascripts, and that main.js is fingerprinted and the newly built file needs to be added to git each time (and the old one is automatically deleted), so we need to take care not to check in a version that has no main.js at all.

**Comment by ntdb** [comment]
Reference #260 - the enhancement to make this a non-issue :)
