### ISSUE TITLE
Gradeables should have specific due dates, not just "in X weeks"

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#263]
Several instructors have noted that it's important to be able to give specific due dates, and that the "in X weeks" format is confusing and not useful for them.

If we can find a quick way to implement this without forcing changes on the timelines that already exist, then it would be good to make this change soon, before the majority of instructors build their Fall 2015 timelines. (If it's too big a change to squeeze in quickly, it should be done in time for the planning of Spring 2016 courses.)

**Comment by ntdb** [comment]
@ragesoss How about this: we can change the `block.duration` column to represent days instead of weeks. It'll be populated via a datepicker but if the block is moved to a different week then the due date will still be relative to that week. So a due date of 8/10 would become 8/17 if the block is moved one week down the timeline?

**Comment by ragesoss** [comment]
I like that, but can we do it in a way that won't affect people who have already set their due dates (or left the defaults) in the current format?

**Comment by ntdb** [comment]
Not cleanly. I'll think on it for an hour or so. The easiest solution would be to set the due date for existing blocks to the Monday of the previously chosen week.

**Comment by ntdb** [comment]
@ragesoss I have a low-impact idea for leaving existing due dates alone. Will work on implementing tomorrow.

**Comment by ntdb** [comment]
Resolved by a4e99d4a103ca2f99d386474ea9d54b9d9a0840c

Note that the day offset stored in the DB is calculated using the first day of the week according to ISO 8601 (Monday). This should mean that due dates are unaffected by a user's locale.

**Comment by ragesoss** [comment]
I also note that this will mean incompatible due dates when a user clones an assignment from a course that meets, eg, Monday-Wednesday into one that meets Tuesday-Thursday.

That's fine, it's just something we'll need to keep in mind and either tell users about or code a solution for when we implement assignment cloning.
