### ISSUE TITLE
Send DYK alerts to instructors

### ISSUE THREAD

**Issue by bwreid** [WikiEducationFoundation/WikiEduDashboard#2635]
### Current Behavior:
At the moment, DYK alerts only go to the content experts associated with a course.

### Desired Behavior:
In addition to content experts, send an email to the creator of the course/program.

### Related Files & Code:

* [dyk_nomination_monitor.rb](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/lib/alerts/dyk_nomination_monitor.rb)
* [dyk_nomination_monitor_spec.rb](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/spec/lib/alerts/dyk_nomination_monitor_spec.rb)

**Comment by Aeropio** [comment]
hello @bwreid : I would like to work on this issue, could you please assign this to me?

**Comment by Aeropio** [comment]
> ### Current Behavior:
> At the moment, DYK alerts only go to the content experts associated with a course.
> 
> ### Desired Behavior:
> In addition to content experts, send an email to the creator of the course/program.
> @bwreid Is creator of the course same as instructor?
> ### Related Files & Code:
> * [dyk_nomination_monitor.rb](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/lib/alerts/dyk_nomination_monitor.rb)
> * [dyk_nomination_monitor_spec.rb](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/spec/lib/alerts/dyk_nomination_monitor_spec.rb)

**Comment by bwreid** [comment]
Hi @Aeropio -- this would be a fine issue to work on, but I would first complete the other issue you started on. Unless you would like to skip that one and work on this instead?

**Comment by arpitadash** [comment]
Hello @bwreid, I'd like to work on this issue if it is still open.

**Comment by bwreid** [comment]
@arpitadash This commit was responded to relatively recently. If we don't hear from @Aeropio in the next day or so, please feel free to take it.

**Comment by Aeropio** [comment]
> Hi @Aeropio -- this would be a fine issue to work on, but I would first complete the other issue you started on. Unless you would like to skip that one and work on this instead?

Hi @bwreid I would like to skip the other issue and take this issue instead

**Comment by Aeropio** [comment]
Hello @bwreid : I am almost done with the implementation of this issue, but I am not sure how to test it, so can you please provide steps to test this?

**Comment by Aeropio** [comment]
Please review this PR
https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2659

**Comment by bwreid** [comment]
In addition to the above, we should actually format a new email that goes to the instructor. Right now, the format for the alert is not very user friendly. At the moment, let's get it so that a well formatted email goes to the instructor (the regular alert can go to the course experts). I can follow up with what exactly the text should be.

For example, you could look at the Course Approval email.

**Comment by Aeropio** [comment]
@bweird sure I will look at the course approval email

**Comment by Aeropio** [comment]
@bwreid @ragesoss https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2672 is the pull request for this issue, please review. NOTE: I have to still work on the formatting of email that goes to the instructor, is it fine if i create a new branch for this format task

**Comment by Aeropio** [comment]
> @bwreid @ragesoss #2672 is the pull request for this issue, please review. NOTE: I have to still work on the formatting of email that goes to the instructor, is it fine if i create a new branch for this format task

I had to close the previous PR which i opened for this task, as i messed up with git

**Comment by bwreid** [comment]
@Aeropio It looks like it was re-opened! Did you mean to do that?

If it could all be included in the same PR that would be great!

**Comment by Aeropio** [comment]
@bwreid yes the PR was reopened, could you please review it, I will meanwhile look for the formatting of email task

**Comment by Aeropio** [comment]
@bwreid can you please provide the text in the mail which goes to the course instructor?

**Comment by bwreid** [comment]
Hi @Aeropio, thanks for your patience. I think the following text should work.

---

Hello, <username>

The following article being worked on as a part of your course has received a [“Did You Know” nomination](https://upload.wikimedia.org/wikipedia/commons/e/ee/Classroom_handout_-_Submitting_an_article_to_the_Did_You_Know_process.pdf):
• <Article Title, with Link>

We recommend checking the submission and encouraging your student to monitor the nomination and respond to feedback. 

Thank you and please let us know if you need any support,
<signature>

**Comment by Aeropio** [comment]
@bweird thank you for providing the text
