### ISSUE TITLE
Editing block content is laggy Windows

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#264]
A few instructors have reported general difficulties with editing block content, and specifically lagginess between typing and the block content changing.

I can replicate this lag on Windows 8.1, on both Firefox and Chrome (on an ASUS x205). ~~Attempting to drag blocks is also particularly buggy — including an instance of a block sort of flashing in and out of place after being dropped — on Chrome.~~

~~The 'top priority' piece of this to do some preliminary investigation, and see if there are any obvious javascript problems that can be fixed to improve the experience. If the answer is 'no', then fixing this will be part of the broader revamp of the timeline editing and rearrangement UX that need to happen.~~

**Comment by ragesoss** [comment]
There's a certain form of bugginess with Firefox (on all OSes) that seems a little more common recently, or perhaps new: clicking around within an input field often does not work. Here's how one user described it:

> The issue arises if I want to make make more than one edit to a section. The first one will work, but then if I want to add or change sometime to a different part of the item in the block, it thinks I am wanting to go into drag and drop mode for the entire block. If I reclick on the type of assignment, I can return to editing.

**Comment by ragesoss** [comment]
The way it manifests for me is many failed clicks within the input box. If I position the cursor with one click, then type something, then click somewhere else to reposition the cursor, it doesn't actually move the cursor.

**Comment by ragesoss** [comment]
And once it gets in a state where clicks are failing, I also cannot highlight text with click and drag; instead it tries to drag the block. (This is very similar to #122)

**Comment by ntdb** [comment]
@thenickcox and I have traced this to a React conflict with my dirty fix for #122. We have a solution in mind and hope to get it deployed tomorrow.

**Comment by ragesoss** [comment]
@ntdb After this fix, I cannot use the mouse to position the cursor or select text in Firefox at all. (Tried on Windows and Debian.)

**Comment by ntdb** [comment]
@ragesoss the built JS had not incorporated the new react-dnd fork. Everything is working now. The one caveat for FF is that you must click into an input before you can drag to select text.

**Comment by ragesoss** [comment]
Confirmed, and deployed. I'm going to reopen and retitle this. The bugginess is taken care of, but the input lag is still an issue. The field takes ~1 second to respond to typing input, on a low-end Windows laptop.
