### ISSUE TITLE
Clicking "Prevent this page from creating additional dialogs" blocks subsequent confirmation dialogs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#270]
The confirmation alerts on students/enroll_button.cjsx (successfully enrolled,  or already enrolled) trigger abuse-prevent in browsers, offering a checkbox to the user to disable further popups. If checked, this blocks the required confirm dialog for subsequent enrollments (until the cookie is cleared).

Probably this should be solved with a general replacement of browser alerts with confirmation modals, which we probably want to do anyway at some point.

**Comment by ragesoss** [comment]
This particular case has been taken care of.

There are still some other situations that could trigger this, but they are edge cases and probably won't significantly break any features.

**Comment by ragesoss** [comment]
Nevermind. We didn't take care of this case yet.

**Comment by mattfordham** [comment]
@ragesoss Are you proposing the solution at the moment be the creation of a custom dialog? I'm not sure any other solution will be possible.

**Comment by ragesoss** [comment]
@mattfordham yes, that's right: a custom confirmation UI of some sort.

**Comment by mattfordham** [comment]
Cool. I think that's a good idea. That said, I don't think I'd be able to fit in my hours this week. If I get through the other priorities, I'd propose skipping over this and converting a few CJSX files. Sound ok?

**Comment by ragesoss** [comment]
Yep, sounds good.

**Comment by ragesoss** [comment]
Done!
