### ISSUE TITLE
Add an API for fetching details about users in a campaign

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2705]
Martin Urbanec requests an API that could be used by an on-wiki gadget, to show a list of students in current courses. "This API should give at least a) role b) course's name c) link to course."

This is basically the same data that we currently provide in the campaign `students` and `instructors` CSV endpoints (and they should maybe be refactored to share logic with this new API).

Basically, we should add an campaign `users.json` endpoint that returns an entry for each CoursesUsers record for nonprivate courses in the campaign, with optional parameters that would scope it by role (eg, only students) and limit it to strictly current courses.

**Comment by urbanecm** [comment]
I just got another gadget proposal, for that one, data about assignments would be appreciated. Could you please create an API for that too? Thanks!

**Comment by ragesoss** [comment]
@urbanecm you mean assignments for a whole campaign? We do have an API for the assignments for an individual course.

**Comment by urbanecm** [comment]
@ragesoss Yes, exactly. Or, at least, an API to get a list of courses, that'll allow me getting the same information from individual APIs. Since that can (probably will) be much slower than one API request, I still vote for APIs working the same way like the individual one for courses, but for whole campaign.

**Comment by ragesoss** [comment]
@urbanecm we just rolled out the first one: https://outreachdashboard.wmflabs.org/campaigns/studenti/users.json

**Comment by ragesoss** [comment]
@urbanecm also the assignments API: https://outreachdashboard.wmflabs.org/campaigns/studenti/assignments.json

Do those give you what you need?

**Comment by urbanecm** [comment]
Thanks @ragesoss! Yes, that should do.
