### ISSUE TITLE
Download Stats button gives error in console

### ISSUE THREAD

**Issue by hardy1334** [WikiEducationFoundation/WikiEduDashboard#2725]
When we click on **Download Stats** button and other buttons as well in a program it gives warnings cum errors in console,although it does not break but any functionality.

![Screenshot from 2019-04-04 23-54-32](https://user-images.githubusercontent.com/31733278/55579434-d92d0400-5735-11e9-8166-0008b720cef3.png)

**Comment by hardy1334** [comment]
@ragesoss  can u please have a look at this

**Comment by ragesoss** [comment]
Yep, looks like an HTML nesting error. The solution should probably be to replace whatever is using a `<p>` as the enclosing element with an appropriately sytled `<div>`, to fix the HTML structure be keep the visual layout unchanged.
