### ISSUE TITLE
Optionally limit or exclude articles/categories from user contributions

### ISSUE THREAD

**Issue by bwreid** [WikiEducationFoundation/WikiEduDashboard#2762]
This is tangentially related to Issue #2129.

We want a way to be able to either limit or exclude specific articles and/or categories from user contributions for a course. For example, the following scenarios should be possible:

* A course should be able to select specific articles and only edits to those articles will be counted towards the course's progress
* A course should be able to select specific articles and any edits to those articles will be excluded from the overall course's progress

These changes could be enacted on the course page or a new page, if appropriate.

**Comment by ragesoss** [comment]
I think this is done.
