### ISSUE TITLE
Track multiple wikis as a part of a program

### ISSUE THREAD

**Issue by bwreid** [WikiEducationFoundation/WikiEduDashboard#2764]
As part of the Programs & Events Dashboard, we'd like to be able to track multiple wikis as part of a program.

![image](https://user-images.githubusercontent.com/1316902/56171236-63c4fd00-5f99-11e9-98a5-b6367b059234.png)

This would allow us to track contributions across wikis.

**Comment by ragesoss** [comment]
Done!
