### ISSUE TITLE
UI issues with due date

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#278]
1. Calendar widget is not attached to the 'Due date' field.
2. Due date field cannot be cleared.
3. Due date changes to one day prior to the picked date. If I select August 10, after saving it will show August 10 for a moment and then change to August 9. If I edit again, it shows August 9. Maybe this has to do with timezone translation from the Moment stuff working on a 00:00 datetime?

**Comment by ragesoss** [comment]
Issues two (reopened as #340) and three have come up again.

**Comment by thenickcox** [comment]
If these are captured in another ticket, let's close this.

**Comment by thenickcox** [comment]
@ragesoss I'm not able to duplicate issue 3. What time was it when you did that?
