### ISSUE TITLE
"What's Changed"

### ISSUE THREAD

**Issue by ntdb** [WikiEducationFoundation/WikiEduDashboard#283]
The first development pass at the "What's Changed" feature will include queries that generate time-limited stats that mirror the stats currently shown at the top of each course page:

- ARTICLES CREATED
- ARTICLES EDITED
- TOTAL EDITS
- STUDENT EDITORS
- STUDENTS COMPLETED TRAINING
- CHARS ADDED
- ARTICLE VIEWS

Scoping these stats to the most recent 7 days gets us to MVP. In the future we'd like to be able to pass an arbitrary datetime range to the new endpoints.

**Comment by thenickcox** [comment]
@ragesoss Is this still valid?

**Comment by ragesoss** [comment]
Not really.
