### ISSUE TITLE
Enable Campus Volunteer on outreach dashboard

### ISSUE THREAD

**Issue by urbanecm** [WikiEducationFoundation/WikiEduDashboard#2840]
Wikimedia Czech Republic would appreaciate if Campus Volunteer functionality is enabled on Outreach Dashboard as well. The feature is already enabled in [WikiEdu Dashboard](https://dashboard.wikiedu.org/courses/North_Dakota_State_University/History_of_Psychology_(Fall_2014)), see [this image](https://user-images.githubusercontent.com/10050467/57390047-c33eb300-71bb-11e9-879b-fe221e768047.png).

**Comment by ragesoss** [comment]
Done!
