### ISSUE TITLE
Campaign organizers should be able to edit all courses assigned to given campaign

### ISSUE THREAD

**Issue by urbanecm** [WikiEducationFoundation/WikiEduDashboard#2841]
Campaign organizers should be able to edit all courses assigned to given campaign. That would free edu managers from needing to be admins, since the only purpose of the rights is to being able to edit anything. #1908 is very similar issue (maybe even #1471? not sure what that one is about, cc @sejalkhatri)

@ragesoss, maybe a good project for WMHack 2019?

**Comment by ragesoss** [comment]
Done!
