### ISSUE TITLE
Ordered lists and tables in course overview and timeline are not styled well

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#285]
In the styling for ordered lists, we don't show any numbers, even though markdown usually supports numbered lists in a simple way. Users have been trying to add ordered lists to their timelines.

**Comment by ragesoss** [comment]
Also, markdown tables completely break the layout.

**Comment by ragesoss** [comment]
@rileywho This is a high-value improvement that we could make pretty easily, once the design part if it is in hand.

**Comment by ragesoss** [comment]
Here's an example of a page that uses some of these features:

http://dashboard.wikiedu.org/courses/Stony_Brook_University/Health_Communication_%28autumn_2015%29/timeline

**Comment by ragesoss** [comment]
(A basic style for an HTML table will also be useful, but that could be a second-wave addition.)

**Comment by bmathews** [comment]
Looks like we can improve a lot of the base styles:

![image](https://cloud.githubusercontent.com/assets/848347/9554181/ea23833a-4d78-11e5-8a49-0871803db72b.png)

![image](https://cloud.githubusercontent.com/assets/848347/9554185/ef78ad10-4d78-11e5-9a06-148dfd699f9d.png)

**Comment by bmathews** [comment]
![image](https://cloud.githubusercontent.com/assets/848347/9747263/941c6b70-5631-11e5-88a6-636066b36196.png)
![image](https://cloud.githubusercontent.com/assets/848347/9747270/9c348c8e-5631-11e5-88c4-ba05732b270e.png)
