### ISSUE TITLE
Columns do not line up on home page course list

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#287]
After deploying to staging with the new Recent Activity column, I noticed that alignment of course title and recent activity numbers are not consistent. This seems to be determined by the content of the Student Editors column, the content of which has variable width.

**Comment by ntdb** [comment]
The proper solution to this is to replace the flexbox-based home page table with a real table, as we've already done with all course-page tables.

**Comment by ragesoss** [comment]
Duplicate of #314
