### ISSUE TITLE
ArticleFinder should fetch labels for Wikidata items

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2887]
ArticleFinder can be used for Wikidata, but the results are only Q numbers.

It should show the labels instead or in addition to Q numbers.

**Comment by shreyaansjain06** [comment]
Is this the error you are talking about that after changing to www.wikidata.org nothing is coming 
<img width="1434" alt="Screenshot 2022-02-23 at 1 35 35 PM" src="https://user-images.githubusercontent.com/86606251/155281271-1737ccf1-72a1-40f1-87e6-d470400c9e2b.png">

**Comment by ragesoss** [comment]
This issue is not about an error, it's just that the Wikidata items show up as Q numbers.

![Q numbers](https://user-images.githubusercontent.com/848483/155359357-bd3fba0b-f986-462c-9d4e-d0570730a8b2.png)

(Make sure your local code is up to date with the latest version. If you are not getting any results there and you have a console error, it may be a bug that was fixed in a later commit than you have locally.)

In contrast to Article Finder, when Q items show up on the Articles Edited list for a course, the frontend fetches the labels for each item so that they don't show up as Q numbers.

**Comment by shreyaansjain06** [comment]
I found that the article prop, which is passed to ArticleViewer in article_finder_row.jsx contains these Q in article.title when we change to www.wikidata.org. So for this I tried finding how this article is formed in action and reducer file but didn't got the idea of its working.

So can you please tell how the article is formed ?

**Comment by sanyud24** [comment]
Hey @ragesoss, can I work on this issue?

**Comment by ragesoss** [comment]
@sanyud24 sure, go for it!

**Comment by sanyud24** [comment]
@ragesoss created the PR, please review
