### ISSUE TITLE
Extract wiki language/project selectors into a reusable component

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2888]
We have several places in the UI that allow the user to select a wiki. The most relevant ones are ArticleFinder and AssignButton, which both have a show/hide link for changing the wiki. Similar but not quite the same is the home wiki selector in CourseCreator and Details.

At least the ArticleFinder and AssignButton ones, and possibly the others as well, should be extracted into a reusable component (or perhaps several components).

**Comment by AmitJoki** [comment]
I think this can be closed now.

**Comment by xiaobaioo7** [comment]
@ragesoss Can I take this one?

**Comment by ragesoss** [comment]
Sure, go for it.

**Comment by xiaobaioo7** [comment]
@ragesoss I started looking into the 2 components "ArticleFineder" and "AssignButton", but I am not sure about what these 2 components do. Can you give a brief explanation on what they do? Or a quick walkthrough or steps to get to these components will be really appreciated.

**Comment by bwreid** [comment]
Hi @xiaobaioo7! Thanks for the question.

The `ArticleFinder` component is just what it sounds like -- it manages the view that makes it easier for students and instructors to find available articles. In your screenshot above, your such on "Buddha" resulted in multiple articles that include "Buddha" in the title.

The `AssignButton` component is actually a bit different than what you've circled on the screenshot above. In the above screenshot, clicking the button "Add as an available article" will add the chosen article as a potential option for students to pick. You can see that list under the "Articles" tab.

The link that allows you to change the Wiki is in the above screenshot you've posted underneath the Search Bar where it says "en.wikipedia.org". You can also see it in the below screenshot under the My Articles section. This view is only available to you as a student/editor. This is also the `AssignButton` component.
![image](https://user-images.githubusercontent.com/1316902/66770605-eb1dfb00-ee6c-11e9-84de-47ae576c6f8e.png)
Does this answer some of your questions?

**Comment by xiaobaioo7** [comment]
Hi @bwreid, thank you for the information! This certainly helps 👍 

Correct me if I am wrong, the request here is to extract the piece like "en.wikipedia.org (Change)" from the mentioned components to its own reusable component, is that correct? 

As a side note (which may not relate to this issue), I encountered some issue when I clicked on the button "Add as available article" from the article finder page. I think I might know what's causing this issue, I created a separate issue to track this #3395 .

**Comment by bwreid** [comment]
Thanks for the additional issue, @xiaobaioo7 

Looking at this a bit more, it seems like we already do have a component titled `WikiSelect` as well as a `SelectedWikiOption`. @ragesoss , can you share a bit more in terms of what you were thinking for this refactor that is not already accomplished by these components?

**Comment by ragesoss** [comment]
Yeah, the idea here is that the we have this same set of functionality from WikiSelect and the toggle for showing in the input used together in several places. It looks like Wes actually already basically did the extraction with `SelectedWikiOption`, but it's not being used in `ArticleFinder`.

I guess what is left to do would be to refactor `ArticleFinder` to use `SelectedWikiOption` instead of re-implementing the 'change' button.

One little thing along the way to tweak as well: there should be a space between the wiki domain and the "(Change)" link.

**Comment by xiaobaioo7** [comment]
Thank you @ragesoss and @bwreid for the updates! I sent a PR to update component `ArticleFinder`.

The PR does not include changes for `CourseCreator` and `Details`. I marked the PR with [WIP] and will look into these 2 components next.

**Comment by xiaobaioo7** [comment]
Looking at the other 2 components `CourseCreator` and `Details`, it seems that they are already using `WikiSelect` component to render the wiki selection. Do we want to change their behaviors?

Some thought on the difference between `SelectedWikiOption` and `WikiSelect`: in addition to `WikiSelect`, `SelectedWikiOption` shows the selected wiki with a link to change it. Given that in both `CourseCreator` and `Details`, it may seem to make more sense to show the form (`WikiSelect`) instead of clicking a field to change since they are both in edit mode (creation and updating). What about your thoughts?

**Comment by ragesoss** [comment]
I think those other two components are fine as they are; in the context of a form with many other inputs, it's fine to just show the input without needing to toggle it open.
