### ISSUE TITLE
Lexeme edits on Wikidata are not imported

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2897]
In addition to mainspace, where Q items live, we should be importing the other Wikidata content namespaces: Property, Lexeme, and Query (and the associated talk spaces): https://www.wikidata.org/wiki/Help:Namespaces

Property, Lexeme and Query edits should count as articles edited.

**Comment by ragesoss** [comment]
@AmitJoki this is relevant for your project.

**Comment by AmitJoki** [comment]
@ragesoss noted. I will add this issue in my TODO list.

**Comment by ragesoss** [comment]
Done!
