### ISSUE TITLE
Popover fadeout animation stops when mouse leaves browser window

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#29]
The popovers have a fadeout animation. If I activate the popover and then move my mouse away from the associated element, then it starts to fade out. However, if I move my mouse quickly and end out leaving the browser window, then the popover animation stops... leaving a half-faded popover that sticks around even if I bring my mouse back into the window.

Sometimes the fadeout doesn't even go to completion if I move my mouse to other places on the same window... especially, activating other mouseover features like the row highlighting of the courses table.

This happens for me on Firefox on Linux, but not on Chrome. (I haven't yet tested on other OSes.)

-Sage
![screenshot from 2015-02-09 13 02 38](https://cloud.githubusercontent.com/assets/848483/6115859/8a025746-b05d-11e4-8014-df343db5545e.png)

**Comment by ntdb** [comment]
@ragesoss I can't reproduce this on OSX. Which version of Linux and FF? I'll put it low on the priority list but I could load up a VM to figure this out.

**Comment by ragesoss** [comment]
@ntdb FF 31.5 on Ubuntu 14.10 and Debian Jessie. If it's just a Linux problem, I'm fine with leaving it alone for a while. I'll test on Windows to see if it is reproducible there.

**Comment by ragesoss** [comment]
Seems to be limited to Linux. I can't reproduce on Windows 7.

**Comment by ntdb** [comment]
@ragesoss I'm using CSS3 transitions for those effects. Would you mind going to [this W3Schools page](http://www.w3schools.com/css/css3_transitions.asp) and seeing if you can reproduce the "pausing" behavior with their example?

**Comment by ragesoss** [comment]
@ntdb I cannot reproduce the issue on any of the examples from that page.

**Comment by ntdb** [comment]
@ragesoss good to know. Thanks!
