### ISSUE TITLE
Sometimes, add instructor window goes out of screen

### ISSUE THREAD

**Issue by urbanecm** [WikiEducationFoundation/WikiEduDashboard#2903]
I was sent this screenshot by Vojtěch Veselý, who reports the add instructor popup goes out of screen at some occasions (undetermined which occasions). 

![image](https://user-images.githubusercontent.com/10050467/58419065-d7beee80-8089-11e9-8e5d-9cd13377482d.png)

**Comment by ujjwalagrawal17** [comment]
Yup, I have also reproduced this issue. The modal is not responsive.  
<img width="1440" alt="Screenshot 2019-06-06 at 8 49 23 PM" src="https://user-images.githubusercontent.com/19607555/59045079-fea4ce00-889c-11e9-8c9b-bc6cb4649b8d.png">
<img width="537" alt="Screenshot 2019-06-06 at 8 51 54 PM" src="https://user-images.githubusercontent.com/19607555/59045080-ff3d6480-889c-11e9-8e10-e3186c1fcad1.png">

**Comment by codingmamakaz** [comment]
Hello! I'm an Outreachy applicant. I'd like to try this one.
