### ISSUE TITLE
Allow campaign organizers to update data for every course

### ISSUE THREAD

**Issue by urbanecm** [WikiEducationFoundation/WikiEduDashboard#2918]
Since #2841 was resolved, campaign organizers are able to edit every course in the campaign. It'll be useful if campaign organizers are also able to force data update for each course, just like they can edit it.

**Comment by ragesoss** [comment]
You mean, force a data update for all of them at once, or for any individual course?

What is the use case for this? Normally, courses will continue to be updated until they are over (and then for 30 days after that), so forced updates are rarely necessary.

**Comment by urbanecm** [comment]
For any individual course. I know it's rarely needed, but course instructors are able to do that and I don't know why campaign organizers shouldn't be able to do the same.

**Comment by ragesoss** [comment]
Hmm. I thought they would be able to. I'll double-check. The option only shows up once the program ends, since it's being updated already before then.

**Comment by ragesoss** [comment]
I think I found the bug.
