### ISSUE TITLE
Wizard progress should be saved

### ISSUE THREAD

**Issue by ntdb** [WikiEducationFoundation/WikiEduDashboard#293]
We would like to store the current state of the wizard (likely as a JSON string stored on the course table) to allow instructors to resume the wizard at a later date.

This is based on feedback that instructors may take days or even weeks to think through the questions and make their choices.

**Comment by AmitJoki** [comment]
Does the wizard refer to campaign creation wizard?

**Comment by ragesoss** [comment]
No, this is the assignment wizard, which launches after course creation if the dashboard is in the Wiki Ed configuration. I think, though, that our current ideas around this have changed a little.

**Comment by ragesoss** [comment]
I'm closing this, as I think instead of saving progress, we want to come up with a new system where the choices are saved after submission but instructors could go through the wizard a second time to change their choices, if they need to.
