### ISSUE TITLE
Day picker re-renders when a date is selected

### ISSUE THREAD

**Issue by ntdb** [WikiEducationFoundation/WikiEduDashboard#294]
The day picker (for choosing blackout dates, not the pop-up date picker) seems to be re-rendering whenever a date is picked. This manifests itself by resetting the picker to the current month whenever a date from a future month is selected. Confirmed in Chrome and FF on Mac.

![screen shot 2015-08-12 at 3 43 49 pm](https://cloud.githubusercontent.com/assets/2095463/9238650/f9ec2cf8-4108-11e5-8fa6-9e7771d1bb02.png)

**Comment by bmathews** [comment]
Fixed via 8bb0312.
