### ISSUE TITLE
Display "do not use IE" banner

### ISSUE THREAD

**Issue by urbanecm** [WikiEducationFoundation/WikiEduDashboard#2947]
Hello, in case an user uses IE, nothing is shown, even an error message, see screenshot below. Dashboard should say "do not use IE", or support IE.

![image](https://user-images.githubusercontent.com/10050467/59041182-6c8ace80-8878-11e9-8ab4-b9f69028ef01.png)

**Comment by ragesoss** [comment]
Which version of IE? We are supposed to have a browser support warning but it has not been reconfigured in a while.

**Comment by urbanecm** [comment]
This screenshot is from IE 11, User-Agent is `Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`.

**Comment by ragesoss** [comment]
Should be fixed after the next deployment.
