### ISSUE TITLE
Update tasks should run in Sidekiq

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2954]
Currently, we have some long-running server processes that get kicked off by cron jobs: `ConstantUpdate`, `DailyUpdate`, `ViewsUpdate`, and some others.

It would be better if Sidekiq managed all of these jobs. We could and should also break them up into the smallest feasible units; they could be scheduled in a single queue, the same way we currently do with course updates.

**Comment by ragesoss** [comment]
@bwreid this is in no way urgent, but if at some point you're looking for a change of pace and/or a task that lets you explore the job queue and update side of the system, this would be a good one.

**Comment by cyrillefr** [comment]
Hello @ragesoss, I would like to take one of these.
From reading issue #3194, and the code, DailyUpdate and ConstantUpdate have been done.
There is a lib/data_cycle folder with many update files. 
There is a training_update file. Coud it be a candidate to a Sidekiqation ?

**Comment by ragesoss** [comment]
Hmm... I think this is already done mostly. The training update could be moved to sidekick, and I think we could close the issue after that.

**Comment by cyrillefr** [comment]
Ok, so I will try to sidekiqing TrainingUpdate

**Comment by cyrillefr** [comment]
Hello @ragesoss,

I deduced at first from the `lib/data/cycle/training_update.rb` file that this process could be async.
But it does not appear in `config\schedule.yml`.

But it is executed here, in `app/controllers/training_controller.rb`:
```ruby
 def reload                                                                                                                                    
   render plain: TrainingUpdate.new(module_slug: params[:module]).result
```
in a classical sync way.
So, unless I miss something, this update might not need to run in a Sidekiq Job.

**Comment by ragesoss** [comment]
@cyrillefr you're correct that it's different from the other update processes in that it is not part of the regularly scheduled update cycles. Training updates are initiated on-demand via TrainingController.

In the `wiki_ed: true` configuration, the training update process consists of loading content from .yml files and updating the database with any changes from the last time it was run, and this is a very fast process.

In the `wiki_ed: false` configuration, the process entails making many API calls to meta.wikimedia.org to pull training content and translations from there, and then updating the database similarly. Especially when run on a large module, this can take a little while... long enough that there is some benefit to moving it to Sidekiq (so that it does not tie up a Rails process that is supposed to serve web traffic, potentially contributing to making the server unavailable during periods of high usage).

The tricky part here would be providing feedback to the user about any errors that occurred during the update. If there are misformatted training pages or pages with duplicate IDs on meta, that could trigger an error in the update process, which currently gets shown to the user via TrainingController#reload. So I think moving this to Sidekiq would require a more sophisticated way of keeping track of update results and showing them to users (such as list of the most recent training updates, their timestamps, and results, along with enqueued or running updates that haven't finished yet).

That would be a lot of work though, and probably isn't a high enough priority to justify it right now... I should close this task and add a new one for this, as it's about more than just moving a task to Sidekiq.
