### ISSUE TITLE
`Category` feature for ArticleScopedCourse should work with PetScan

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2978]
PetScan is a powerful query tool for generating large lists of articles that meet specific criteria (such as having certain templates, being in certain categories, etc): https://petscan.wmflabs.org/

It would be useful if, instead of specifying a single category or query, a PetScan query could be used to generate the set of articles instead... probably in the form of the `PSID` for the query. The dashboard could then fetch and parse the article list for that query to populate `article_titles`.

`Category#article_titles` is large enough to hold a few hundred thousand titles in each record, although that scale will probably break some other things for big sets. So how large a query can be handled is an open question.  It looks like categories as large as 20,000 have been used already on P&E Dashboard, so probably at least that large would be okay.

**Comment by khyatisoneji** [comment]
As far as my understanding,
For finding articles from the giving category(as a query), we are using MediaWiki API in article_finder_action.js to fetch articles for a query generated.

So need to use PetScan API instead of MediaWiki API?

**Comment by khyatisoneji** [comment]
The `https://petscan.wmflabs.org/` website does server side rendering inorder to calculate the psid. How do we know what is the api to call inorder to get the psid for given query parameters?

**Comment by ragesoss** [comment]
Done!
