### ISSUE TITLE
Course got created with null values that shouldn't be possible

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#298]
Have a look here:
* http://dashboard.wikiedu.org/courses/University_of_British_Columbia/ASTU_260_Knowledge_Dissemination_%28Summer_2015%29
* http://sentry.ragesoss.com:8080/wiki-ed/production/group/341/
* http://sentry.ragesoss.com:8080/wiki-ed/production/group/342/

**Comment by thenickcox** [comment]
Could this be related to #237?

**Comment by ragesoss** [comment]
I don't think #237 is related. With #237, the course is fully functional, and (for example) further edits to the timeline by other users work as expected and push the course updates to Wikipedia.

**Comment by ragesoss** [comment]
The user also created another course that doesn't even have a slug. (Course ids in our production database are 10065, 100066, and 10067. The last of these seems to be fine, and I think is the one that the instructor is using.)

I'm going to reach out to the user to learn more about what happened.

**Comment by ragesoss** [comment]
Also, I found that the title is undefined in course 10065, and so the Delete button doesn't work. For 10066, there's no way to even route to the course without a slug.

**Comment by ragesoss** [comment]
Okay, this only ever happened once, so I'm downgrading the importance.

**Comment by thenickcox** [comment]
Closed via 2cbf01e193036d279bbebdfc805955363dd955a1
