### ISSUE TITLE
Incomplete state of Articles Edited list is not obvious, when there are over 500 articles

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2990]
A course with more than 500 articles will only load the first 500 initially, and loading more is done with the 'See More' button at the end of the list. This is confusing if you're expecting to see a certain article in the top several (sorted by content added, or resorted some other way).

In cases where only a partial list of articles has been loaded, the count of loaded articles versus the total, along with the button to load more, should appear at the top of the list.

**Comment by thefifthisa** [comment]
Hey @ragesoss! Can I give this a try?

**Comment by ragesoss** [comment]
@thefifthisa go for it! Let us know if you have any questions.

**Comment by prionkor** [comment]
Any urls for such long courses? Helps checking the issue quickly.

**Comment by ragesoss** [comment]
@prionkor here's an example that has more than 500: https://outreachdashboard.wmflabs.org/courses/NeuroMat/Wikidata_Lab_XI_-_Estruturando_projetos/articles/edited

**Comment by prionkor** [comment]
Few observations: 

1. If "load more" button is moved to the top then when people goes to bottom they will have to scroll up again to load again.
2. If "load more" at the top then it will be problematic if articles started to load at the bottom. Users wouldn't know.

**Suggestion**

1. Pagination: Paginate after 10 (or more) articles in the list. Load on pagination click.
2. Scroll to new results onload: If pagination is not a option, users is needed to scroll to the result after new items are loaded. 
3. Need a loading state for the "See more" button.

Let me know what you think.

**Comment by ragesoss** [comment]
I think a loading state for the 'see more' button, combined with duplicating the button on top and bottom of the list, would be a relatively simple way to start.

**Comment by bharathjoshi** [comment]
Hey @ragesoss ! I have been on this issue for quite a time, found a way to duplicate the button but didn't get the essence of "loading state" for the see more button.
Another question I have is, how can I get the number of total articles ( in the context of adding the count of loaded vs count of total articles). The code has been using fetchArticles where we are giving the id and then the number. Not really being able to understand how the API works. Any insights?

**Comment by ragesoss** [comment]
@bharathjoshi we currently don't have anything that shows the total number, except that in most cases it will match the `articles_edited` value from the `course` state.

Currently, we determine whether or not to show the button via the `limitReached` value from the articles reducer, based on whether the number of articles received is less than the limit of the last fetchArticles query.

The API takes a course slug (called courseId in some places) and a limit of total articles, and returns the up to that many articles. The way the frontend works right now is that it first asks for 500 articles, and if a full 500 are received, it enables the See More button (because the limit is reached) and a See More request will bump up the limit and ask for (I think) 1000 articles... which then replace the original 500 articles. Then if full 1000 requested are received, the See More button remains enabled and the next time it will request  1500. (This isn't an efficient pagination strategy; it would be better to use offsets for real pagination, and combine the results of multiple requests in the reducer, but courses with thousands are articles are edge cases.)

**Comment by abhishekbvs** [comment]
I would like to work on this issue.

**Comment by bharathjoshi** [comment]
ok thanks for the help @ragesoss . will think of some effective implementation and will try to implement it.

**Comment by abhishekbvs** [comment]
![DeepinScreenshot_select-area_20191217201515](https://user-images.githubusercontent.com/32136294/71005635-ff4ed480-2109-11ea-8008-e35ca1ceb6e0.png)
@ragesoss Is this fine? I took the count of total articles from  `this.props.course.edited_count` and no of articles that are shown at that instant from `articleElements.length`.  For the purpose of testing, I just changed the limit to 10.  Can you just look into this and tell whether will this resolve the issue. Maybe I should align them properly.

**Comment by ragesoss** [comment]
@abhishekbvs that sounds reasonable. The alignment should definitely be fixed before it could be merged.
