### ISSUE TITLE
Add a JSON API for showing list of all active campaigns.

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/WikiEduDashboard#2997]
the current API is returning list of all campaigns but the API is not returning a JSON response. It is instead rendering a webpage.

**Comment by ujjwalagrawal17** [comment]
@ragesoss is it deployed in Outreach Programs server?

**Comment by ragesoss** [comment]
Not yet

**Comment by ragesoss** [comment]
@ujjwalagrawal17 this is live now.
