### ISSUE TITLE
Add a JSON API to get Profile Information, statistics. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/WikiEduDashboard#2998]
The Android client needs an API for showing profile information (information should be the same that is shown in the profile page of the website- https://outreachdashboard.wmflabs.org/users/Ujjwalagrawal17 ). Currently, there is no JSON API for fetching the details.

**Comment by bwreid** [comment]
Hi @ujjwalagrawal17. We currently have an API endpoint that gets most of the information on the Profile page. Is this sufficient?
https://outreachdashboard.wmflabs.org/user_stats.json?username=Ujjwalagrawal17

**Comment by ujjwalagrawal17** [comment]
I need profile picture URL, description, location and contributions_url similar to website.

**Comment by ujjwalagrawal17** [comment]
seems to be sufficient.
