### ISSUE TITLE
Add list of archived programs in Dashboard API

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/WikiEduDashboard#2999]
Link: https://outreachdashboard.wmflabs.org/dashboard.json

**Current Situation**: 
The API is only returning the list of active courses, not archived courses. 

**Expected:** 
The details of archieved programs should also be added. Same as what is shown in the screenshot. 

<img width="1439" alt="Screenshot 2019-06-19 at 9 00 52 PM" src="https://user-images.githubusercontent.com/19607555/59779186-6f081200-92d5-11e9-8b29-3fc76feae4f9.png">

**Comment by ragesoss** [comment]
Whoops! Just realized I never merged this after I coded it up two weeks ago.
