### ISSUE TITLE
Create a JSON API for assigning yourself articles for a course you are in

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/WikiEduDashboard#3036]
**Description:**
Create a JSON API for assigning yourself articles for a course you are in

**Comment by ragesoss** [comment]
This exists, a POST to /assignments.json. For example:

http://localhost:3000/assignments.json?title=Selfie&project=wikipedia&language=en&course_id=test/New_Wiz_Wiz&user_id=28&role=0

You just need to send the title, language, project, course slug as `course_id`, user id, and role (0 for assigned article, 1 for reviewing which you probably don't want to add support for at this point).
