### ISSUE TITLE
Add a JSON API to get list of my articles (articles assigned to me) in a course. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/WikiEduDashboard#3038]
**Description:**
Whenever we are opening the Dashboard website course page, if we are enrolled in the course, we see a list of all articles that are assigned to me in the course home page. We want to show the same to the users in the app.

**Comment by ragesoss** [comment]
@ujjwalagrawal17 on the web version, we use the entire set of assigned articles, and then filter client-side to isolate the ones belonging to the user for the MyArticles component. Could you use that approach as well?

Here's an example of the Assignments endpoint: https://dashboard.wikiedu.org/courses/School_of_the_Art_Institute_of_Chicago/New_Histories_of_Chicago_Media_(Spring_2019)/assignments.json

**Comment by ujjwalagrawal17** [comment]
Got it thanks.
