### ISSUE TITLE
Users's edits to Timeline are not saving

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#306]
For this course, the instructor has been able to make edits to the course description, but attempted edits to the Timeline are not going through; when the instructor returns to the Timeline after leaving, the content has reverted to what originally came out of the wizard.

No edit events from the instructor came through on Sentry for the timeline (unlike edits to course description and adding another instructor). I was able to make successful edits, without issue.

Here is the console log from when the instructor clicks Save on a timeline change:

```
Received tags
main-a435d2c8f2.js:7156 Received timeline
vendor.js:3 POST http://dashboard.wikiedu.org/courses/LaGuardia_Community_College/ENG103_Octavia_Butler's_Wild_Seed_(Fall_2015)/timeline.json 401 (Unauthorized)K.ajaxTransport.Z.cors.e.crossDomain.send @ vendor.js:3K.extend.ajax @ vendor.js:3(anonymous function) @ main-a435d2c8f2.js:7210lib$es6$promise$$internal$$initializePromise @ main-a435d2c8f2.js:10671lib$es6$promise$promise$$Promise @ main-a435d2c8f2.js:10962API.saveTimeline @ main-a435d2c8f2.js:7166Flux.createActions.saveTimeline @ main-a435d2c8f2.js:292Action.dispatch @ main-a435d2c8f2.js:10101React.createClass.saveChanges @ main-a435d2c8f2.js:2050executeDispatch @ main-a435d2c8f2.js:43789SimpleEventPlugin.executeDispatch @ main-a435d2c8f2.js:58030forEachEventDispatch @ main-a435d2c8f2.js:43777executeDispatchesInOrder @ main-a435d2c8f2.js:43798executeDispatchesAndRelease @ main-a435d2c8f2.js:43167forEachAccumulated @ main-a435d2c8f2.js:60051EventPluginHub.processEventQueue @ main-a435d2c8f2.js:43374runEventQueueInBatch @ main-a435d2c8f2.js:51740ReactEventEmitterMixin.handleTopLevel @ main-a435d2c8f2.js:51766handleTopLevelImpl @ main-a435d2c8f2.js:51852Mixin.perform @ main-a435d2c8f2.js:59006ReactDefaultBatchingStrategy.batchedUpdates @ main-a435d2c8f2.js:50184batchedUpdates @ main-a435d2c8f2.js:57177ReactEventListener.dispatchEvent @ main-a435d2c8f2.js:51946
main-a435d2c8f2.js:7220 Uncaught TypeError: Cannot read property 'message' of undefined
```

**Comment by ragesoss** [comment]
We should have logging in place now to catch this if it reoccurs. It may be the same root issue as #304.

**Comment by ragesoss** [comment]
I don't think the logging is catching the 401 errors. The production.log has many such 401s since we deployed the raven-js capture code earlier this week.

**Comment by ragesoss** [comment]
We now have the logging working properly, at least in cases where it doesn't hit the uri limit (which happens on some errors).

Since Friday, we have 13 failed saveTimeline events: http://sentry.ragesoss.com:8080/wiki-ed/production/group/411/

There are three courses among those 13 events:
* http://dashboard.wikiedu.org/courses/University_of_British_Columbia/ASTU260_(Summer_2015)/timeline
* http://dashboard.wikiedu.org/courses/SUNY_Plattsburgh/Cell_Biology_with_Lab,_Bio_401_(Fall_2015)/timeline
* http://dashboard.wikiedu.org/courses/Saint_Louis_University/Evolutionary_Biology,_3010-02_(Fall_2015)/timeline

**Comment by thenickcox** [comment]
I vote to close. Any failures will likely be different as a result of the work we've done.

**Comment by ragesoss** [comment]
A recent variation of this was closed yesterday with the disabling of `delete week` in arrange mode. But yeah, let's close this open something new when we see any additional instances of saveTimeline failure.
