### ISSUE TITLE
Campaign Articles view has bad layout, wrong text when no articles have been edited

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3089]
The placeholder text box doesn't span the whole row, and it refers to a course rather than the campaign.

![campaign with no articles](https://user-images.githubusercontent.com/848483/61069614-895b7a00-a3c1-11e9-888b-9ff6c354ef80.png)

**Comment by Kartik1397** [comment]
Hi @rageross , are you working on this issue? I would like to work on this issue.

**Comment by ragesoss** [comment]
@Kartik1397 go for it!
