### ISSUE TITLE
AssignButton does not respond to first click user navigates away and back while it is open

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3101]
This seems like a conflict between local and redux state for the popover button. It might only happen in cases like the new link button within the open state of AssignButton, where the link is in the popover and so does not trigger the click-on-outside callback to close it (and update the state to closed in the UI reducer).

**Comment by prionkor** [comment]
@ragesoss Could you Please add some details on how to reproduce the issue.

**Comment by ragesoss** [comment]
It should be something like this:

1. Create a course
2. Add yourself as a student
3. In the MyArticles section, click 'Assign myself an article'
4. Within the popover at the bottom, click 'Search Wikipedia for an Article'
5. Navigate back to the MyArticles tab
6. Click 'Assign myself an article' again. The first click does not open the popover, (I think) because the 'ui' reducer state has it marked as open (and so the click sets it to closed).

**Comment by Kartik1397** [comment]
@ragesoss Can I work on this?

**Comment by prionkor** [comment]
@Kartik1397 I am currently not working on this ticket so go ahead if @ragesoss agrees.

**Comment by ragesoss** [comment]
Go for it. :-)
