### ISSUE TITLE
Fix alignment of course titles

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#314]
![screen shot 2015-08-18 at 2 44 42 pm](https://cloud.githubusercontent.com/assets/702327/9343622/f471a326-45b7-11e5-90c7-3e5ce295aebc.png)

**Comment by thenickcox** [comment]
Digging into this a bit, it apparently has to do with the [`jusfify-content`](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/stylesheets/modules/_lists.styl#L46-L49) calls in the CSS.

**Comment by bmathews** [comment]
This is now fixed within the current flexbox implementation. At some point we'll probably want to switch this out for the List component.
