### ISSUE TITLE
Activity links to project namespace are incorrect for Commons and other projects

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3144]
For example [this page](https://commons.wikimedia.org/wiki/Commons:Featured_picture_candidates/removal/File:Credit-cards.jpg/2) is linked as https://commons.wikimedia.org/wiki/Wikipedia:Featured_picture_candidates/removal/File:Credit-cards.jpg/2

**Comment by ragesoss** [comment]
@AmitJoki this could be fixed by extending the work you did on adding support for namespaces 100, 102, and 106.

In this case, it's namespaces 4 and 5, which are `Wikipedia` for Wikipedia, and otherwise, `Project` will be a workable fallback.

**Comment by ragesoss** [comment]
Actually, I guess putting the optimal name for each possible project (Commons, Wiktionary, etc) will be the best way, and will fit with the way you implemented the other ones.

**Comment by AmitJoki** [comment]
Okay. I will work on this issue.

**Comment by AmitJoki** [comment]
@ragesoss I don't see namespace for Wikipedia in Commons here - https://commons.wikimedia.org/wiki/Help:Namespaces
