### ISSUE TITLE
Markdown url formatting gets escaped by closing parens in url

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#316]
This isn't how markdown is supposed to be have, but if a url has a closing parens, then it will escape the url formatting at that point (instead at the closing parens as it should, to encapsulated the whole link).

**Comment by bmathews** [comment]
This is a bug in the markdown parser we're using, and it doesn't look like it'll be fixed/released anytime soon, despite there being open pull requests that fix it. https://github.com/chjj/marked/issues/109
