### ISSUE TITLE
Available Articles should be configurable to allow multiple users to choose the same one

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3161]
### Current Behavior:
When an Available Article is selected, the `Assignment` record is updated with the user, and it no longer appears in the list of Available Articles.

### Desired Behavior:
The current behavior is the right one for some classes, but for others, it would be better to assign the article to the student without removing it from the list so that others can choose it as well. That would also facilitate large, shared lists of available articles that could be reused across semesters or even across multiple simultaneous courses.

**Comment by abhishekbvs** [comment]
- Can I know the type of classes where the current behaviour is fine?

- For other classes, Should I add an option while adding available articles to the program where user can have an option to select whether the articles can be edited by single or multiple editors?  

- Adding a modal after clicking Add as available article button which asks whether it should be edited by single or multiple editors in article finder tool. After selecting the right one, the article will be added to the list of available articles. (Is there any limit? If there is a limit we should provide an input box where the maximum no of editors who can work on the same article is also submitted)  

- After an article is added with enabling multiple users editing. Should It be separately shown in different table in available articles section or adding a column marking multiple users editing is enabled is fine?

- So a user can assign himself from the available list of articles and the remaining count i.e., max - count (no of editors who already assigned to that article) is also shown. If it is zero it is removed from the available list of articles and after that, It will not be listed in the available articles list.

**Comment by ragesoss** [comment]
Thanks @abhishekbvs .

I'll copy over my reply from email. Let me know if there's anything else that I didn't give enough clarity on.

----

The current behavior should be the default; I like the idea of having it be an option at the level of an individual article, though (which sounds like what you have in mind). I'm not sure what the simplest UI for that is; I don't like the idea of adding an extra modal, but a new choice within an existing modal is fine. Maybe there could be a toggle in the Article Finder when you're using that to select available articles, which will set whether it's available for one student or many.

I think we don't need a limit, just an option of allowing only one student to claim it, or to allow any number of students to claim it (in which case, it would stay on the list of available articles after being chosen).

It's already possible to have multiple users assigned to the same article (for example, if each user adds the title of the article directly), so this is just about the behavior of the available articles and whether they disappear from the list after being chosen.

**Comment by samuel-rosa** [comment]
This is a very much needed feature. I was looking for it for my class. Groups of students are required to improve a Wikipedia article and I would like to use the Dashboard for them to choose which article to work on.

Are there any improvements on this?

**Comment by ragesoss** [comment]
@samuel-rosa we're not working on it at the moment, but you can work around it in the meantime by having the first student in a group select one of the Available Articles, and then have others who will join the same group add the the same title as their assignment. The Dashboard has support for groups working together on the same article, it's just the 'Available Articles' feature that doesn't account for groups.

**Comment by samuel-rosa** [comment]
@ragesoss I guess that I have to create an Article Scoped Program to use that feature, right?

**Comment by ragesoss** [comment]
@samuel-rosa no, this will work for any type of program.

**Comment by ragesoss** [comment]
Done with https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/e0b6cf19d23f7a21ca691261c0f416481461209b
