### ISSUE TITLE
main.js not getting minified

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#320]
Even cached, it's 395K. That's just crazy.

![screen shot 2015-08-25 at 8 42 41 am](https://cloud.githubusercontent.com/assets/702327/9471540/b70a4fc6-4b05-11e5-9414-4af8d9927473.png)

**Comment by thenickcox** [comment]
Minifed, not mangled:

![screen shot 2015-08-25 at 8 59 09 am](https://cloud.githubusercontent.com/assets/702327/9472121/323e5c08-4b08-11e5-9b50-83cde5687aed.png)

Minified and mangled:

![screen shot 2015-08-25 at 9 02 50 am](https://cloud.githubusercontent.com/assets/702327/9472125/3d3ce4b2-4b08-11e5-841c-26da886f565c.png)

56% reduction in size, 29% reduction in time over the wire. Closed via f45cbf6c3c1884e7bebf868d94103d918bed3573

**Comment by thenickcox** [comment]
Also, 39% reduction in size of files overall, 29% decrease in page load time overall from cold cache.

**Comment by ragesoss** [comment]
Cool. We'll lose the readable stack traces on Sentry, though. Maybe at some point we should just do a sprint where we un-minify it for a couple of days and then try to fix as many of the errors as we can find.

**Comment by thenickcox** [comment]
Good idea. There's always a trade-off, isn't there?

**Comment by bmathews** [comment]
@ragesoss I just committed some build process improvements that add external sourcemaps for minified/production builds. Sentry _should_ be able to pick those up and report better stack traces.

**Comment by ragesoss** [comment]
@bmathews great!
