### ISSUE TITLE
Users should be able to update their email via their user profile page

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3210]
### Current Behavior:
The only way to edit your email is to go through `/onboarding` again, which is not discoverable.

### Desired Behavior:
Email should be one of the editable fields in the user profile edit view.

**Comment by katherine95** [comment]
@ragesoss I would like to take this up

**Comment by ragesoss** [comment]
Great! Let us know if you run into any trouble.

**Comment by Manasa2850** [comment]
@ragesoss I would like to work on this

**Comment by marklocklear** [comment]
@ragesoss looking at this one. Just so I'm clear, we are wanting to edit the user model (@user.email) and email preferences in the user profile (user_profile.email_preferences)?

**Comment by ragesoss** [comment]
@marklocklear I think I just had in mind updating @user.email.

The `user_profile.email_preferences` is, if I remember correctly, designed to let a user follow a link in a particular email and opt out of an further emails of that kind, but it's used very minimally and I don't think we need to be able to see or edit that from the profile page.
