### ISSUE TITLE
Activity is tracked after "Activity tracking end" timestamp

### ISSUE THREAD

**Issue by Ambrosiani** [WikiEducationFoundation/WikiEduDashboard#3228]
### What is happening?
Activity is tracked after the "Activity tracking end" timestamp.

### To Reproduce

1. Go to https://outreachdashboard.wmflabs.org/courses/Musikverket,_Nordiska_museet_och_Stockholms_kvinnohistoriska/Kvinnor_inom_scenkonst_och_mode/home
2. Activity tracking should end on 2019-08-16 23:59 CEST (see right-hand box)
3. Select the "Activity" tab in the top menu
4. Activity is still being tracked despite that we have moved beyond 2019-08-16 23:59 CEST

### Expected behavior
No tracked activity after 2019-08-16 23:59 CEST

### Additional context
This is related to (although it seems not exactly the same as) #1738 ("Editathons should only show statistics related to specific campaign")

**Comment by Ambrosiani** [comment]
ah I see! Yes, I still think the best way forward is to connect the activity tab content to the tracking end date. A quickfix before that might be to rename "activity tracking" to "statistics tracking" to clarify exactly what the dates relate to.

**Comment by ragesoss** [comment]
Yeah, calling the start/end dates "statistics tracking" would probably be a generally helpful change.

**Comment by ragesoss** [comment]
This works differently now... the Activity tab always shows recent activity without regard to the end dates, unless the 'Show Course Specific' feature is used. I think the current behavior is good.
