### ISSUE TITLE
Dashboard Home Page Enhancement 

### ISSUE THREAD

**Issue by rileywho** [WikiEducationFoundation/WikiEduDashboard#327]
Proposed change: Remove the colored background on the homepage.
The color used for actionable items (#656e92) is the same color used for backgrounds. This pattern could cause bigger issues on future features/tools. For the homepage specifically, removing the background helps the user quickly focus on the available actions ("Create a Course" and finding a course).

Header background: #f5f5f5
Header color: #656e92

![screen shot 2015-08-25 at 4 33 34 pm](https://cloud.githubusercontent.com/assets/2120466/9508794/ec54290a-4c0d-11e5-9828-1bf7d1e5fd1f.png)

![screen shot 2015-08-25 at 4 34 42 pm](https://cloud.githubusercontent.com/assets/2120466/9508793/e4c4ead0-4c0d-11e5-838d-b87a108c6b2f.png)

**Comment by rileywho** [comment]
@thenickcox @ragesoss thoughts?

**Comment by ragesoss** [comment]
@rileywho I think I like this. Will the green notification bars still look good with this?

**Comment by rileywho** [comment]
I believe so. Here's a quick mockup.

![wikihome](https://cloud.githubusercontent.com/assets/2120466/9526531/aa90e6ca-4c9e-11e5-8875-e3d48d5f0275.jpg)

**Comment by ragesoss** [comment]
@bmathews That commit breaks the styling on other pages. See http://dashboard-testing.wikiedu.org/courses/University_of_North_Carolina,_Chapel_Hill/CCO_History_140_-_The_World_Since_1945_%28Summer_2015%29

**Comment by ragesoss** [comment]
(The stats are the same color as the background, and the mouseover color for the course title doesn't work with the background.)

**Comment by bmathews** [comment]
Ahh! :-1: 

Thanks @ragesoss! Will revert and fix.

**Comment by ragesoss** [comment]
@bmathews I think it's a good change, we just need to update the rest of the stylings for a course page to go with this new header. (ping @rileywho )

**Comment by rileywho** [comment]
I'll work on a solution for the styling.

**Comment by bmathews** [comment]
No longer relevant.
