### ISSUE TITLE
Include shortened footnotes in references added counts

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3276]
The 'references added' feature uses ORES feature data to compare the number of references before and after a given edit. Specifically, it uses `feature.wikitext.revision.ref_tags`. This excludes refs that use the `{{sfn}}` (shortened footnote) template, which will undercount some articles or count some edits as removing refs when they are changing the ref format.

ORES now includes the shortened footnote count (`feature.enwiki.revision.shortened_footnote_templates`), so we should add that in to our calculations.

**Comment by ANURADHAJHA99** [comment]
@ragesoss Are we suppose to replace the `feature.wikitext.revision.ref_tags` with  `feature.enwiki.revision.shortened_footnote_templates` in various files?

**Comment by ragesoss** [comment]
It should not replace it; it should count the sum of both of those keys.

**Comment by ANURADHAJHA99** [comment]
@ragesoss I could not find `feature.enwiki.revision.shortened_footnote_templates` when I global searched? Also how to approach the solution of the problem

**Comment by ragesoss** [comment]
It's part of the `features` data that we import from ores.wikimedia.org, eg, https://ores.wmflabs.org/v3/scores/enwiki/?models=wp10&revids=782180234&features

**Comment by bwreid** [comment]
@ANURADHAJHA99 Sage can add more details, but I believe where the information from ORES is getting added is on [this line](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/08439925672920ce2e78dd8f47a4a9cc412a590f/lib/importers/revision_score_importer.rb#L121).

The `features` property on the `Revision` model is a hash and gets updated as such. Inside there is where you would find the `feature.enwiki.revision.shortened_footnote_templates` key after a revision has been updated with that data. Following where and how that file gets called should help to solving this issue.

**Comment by ANURADHAJHA99** [comment]
@bwreid Are we suppose to update the model_key,
`def model_key
    @model_key ||= @wiki.project == 'wikidata' ? 'itemquality' : 'articlequality'
  end` ? 
Thank you very much for your help.

**Comment by khyatisoneji** [comment]
No, you're supposed to update the `ref_tags` and `ref_tags_previous` to only one take `@ragesoss Are we suppose to replace the feature.wikitext.revision.ref_tags` but also `@ragesoss I could not find feature.enwiki.revision.shortened_footnote_templates`

**Comment by ANURADHAJHA99** [comment]
@khyatisoneji Can you please kindly explain? I am unable to comprehend. Sorry for the problem.

**Comment by ANURADHAJHA99** [comment]
@khyatisoneji Are we suppose to do the changes in `/WikiEduDashboard/spec/presenters/individual_statistics_presenter_spec.rb`? If not where are we suppose to update the file? Thank you

**Comment by khyatisoneji** [comment]
Currently, `ref_tags` and `ref_tags_previous` functions consider only `feature.wikitext.revision.ref_tags`,  as you can see in the function it only fetches ref_tags ( ` features[WIKITEXT_REF_TAGS]` ) from the hash
Now you need to add `features['feature.enwiki.revision.shortened_footnote_templates']` to `features[WIKITEXT_REF_TAGS]`
