### ISSUE TITLE
'Sign up' link should show username/email advice before sending users to Wikipedia

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3295]
We currently use a 'Sign up with Wikipedia' link to send new users to the Wikipedia account creation page and then return them to the Dashboard for OAuth login upon success.

To reduce the rate of students choosing bad usernames that they need or want to change later, and to improve the rate at which students put in an email to enable password recovery, the Dashboard should present some username advice — perhaps via a modal — before routing users to Wikipedia to create their accounts.

**Comment by ANURADHAJHA99** [comment]
@ragesoss How will the modal decide whether the username is bad, or is it a static modal that offers some pre-warning? Thank you for your help.

**Comment by ragesoss** [comment]
It would be a static modal that just includes some advice about choosing an appropriate username.

**Comment by ANURADHAJHA99** [comment]
@ragesoss What file do you need to edit? Thank you for help.

**Comment by ragesoss** [comment]
There are a couple of different places where people can reach the account creation workflow, but the main one for students would be the one rendered in `EnrollCard`; I suggest starting there: `app/assets/javascripts/components/enroll/enroll_card.jsx`

![enroll card](https://user-images.githubusercontent.com/848483/67435141-59b33500-f5a0-11e9-9560-e02010973b4e.png)

**Comment by ANURADHAJHA99** [comment]
@ragesoss Can I use the modal API from material UI?

**Comment by ANURADHAJHA99** [comment]
@ragesoss I started working on the file, that you you asked me to start with, however, our main concern is to render a static modal when the user is choosing a username, and I couldn't find any parameters in `enroll.jsx`, can you specify me the condition in `enroll.jsx` on the basis of which the modal should be rendered? I have created the modal, I am however confused about the condition?

**Comment by ragesoss** [comment]
I think basically the idea should be:

1. User clicks 'Sign up with Wikipedia'
2. Modal pops up with additional advice for choosing a username, and the button in that modal is what actually sends the user over to the Wikipedia account creation flow (which is what the 'Sign up' button itself does currently).

**Comment by ragesoss** [comment]
If you have `?enroll` at the end of a course page URL and you are not logged in, it should show the EnrollCard as in the screenshot.

**Comment by ANURADHAJHA99** [comment]
But we are supposed to click on 'Sign up with wikipedia', and it renders to a form that does not seem to be specified in 'enroll.jsx'.

**Comment by ANURADHAJHA99** [comment]
The doubt that I have is are the props related to the following screenshot. I had doubts with regard to the view of the following page. I do understand that I have to trigger the modal when the user chooses a username. Can you please clarify the code of `enroll.jsx`, if I am following the wrong. Thank you.

![Screenshot from 2019-10-26 20-27-49](https://user-images.githubusercontent.com/34815869/67621769-c17faf00-f830-11e9-8362-a6ffa0f00806.jpg)

**Comment by dnahol** [comment]
Hi @ANURADHAJHA99. Are you still working on this, or can I take a stab a it?

**Comment by abhishekbvs** [comment]
Can I work on this issue?

**Comment by ragesoss** [comment]
@abhishekbvs go for it

**Comment by Manasa2850** [comment]
@ragesoss can I work on this?

**Comment by ujjwalpathaak** [comment]
@ragesoss Please have a look at this
I added an intermediate modal in ```components/enroll/enroll_card.jsx```
I guess if this approach is fine it would be easy to add them in react components but i'd need to figure out a way to add them for server components.
[Screencast from 25-12-23 10:06:39 PM IST.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/92005669/3c4c0bdb-bdda-4496-878c-0c0b94b89946)

**Comment by ragesoss** [comment]
@ujjwalpathaak I think that approach looks fine.
