### ISSUE TITLE
Removed classes remain in cohort

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#33]
On production, there are only two classes in the "student groups pilot" cohort. 4 other classes — two at any given time — were previously part of that cohort in the last couple of days. All six courses are showing up on the dashboard right now: http://dashboard.wikiedu.org/courses?cohort=Student_Groups_Pilot

The same thing has not been happening on the community dashboard instance, educationdashboard.wmflabs.org, which has far fewer courses. I removed a course from one cohort and added it to another without issue. I didn't test simply removing a course, but that is something that previously worked on production.

I suspect that this an issue related to the update process, which takes much longer and breaks more often on production.

**Comment by ntdb** [comment]
@ragesoss whoops, I shouldn't have closed this yet. The referenced commit will resolve this issue if your suspicion (see d6dc43a) is correct.

**Comment by ragesoss** [comment]
Confirmed fixed.
