### ISSUE TITLE
Truncate course title page 

### ISSUE THREAD

**Issue by bmathews** [WikiEducationFoundation/WikiEduDashboard#333]
Desired behavior on left, current behavior on right:

![image](https://cloud.githubusercontent.com/assets/848347/9530390/5441c346-4cb4-11e5-813f-79e680c58a84.png)

**Comment by ragesoss** [comment]
We need to show the full title of a course (somewhere, at least, even if not everywhere). If we truncated it, then there would be nowhere in the interface to see the full title. I think the current behavior is okay. It disrupts the layout slightly, but not enough to worry about.
