### ISSUE TITLE
Add Pagepile option for Category tracking

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3357]
Pagepile is a tool for representing a static list of articles — both existing and not — on a single wiki: https://tools.wmflabs.org/pagepile/

This could be a very similar option to the PetScan one for a Category record on the Dashboard, except that instead of needing to be updated regularly, it would just need to be imported once since it is a static list. That would make for a convenient way to track progress on creating missing articles as well.

**Comment by khyatisoneji** [comment]
Have to add a button `Add PagePile id` just like `Add PetScan PSID` ?

**Comment by ragesoss** [comment]
Yes, I think that makes sense.
