### ISSUE TITLE
Course creation broken on master

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#337]
The latest builds, beginning probably with the rebuilding of assets that went with merging the jit_activity branch, are failing because you cannot proceed past the first panel of the Course Creator. This needs to be fixed before we can deploy anything new to production.

**Comment by thenickcox** [comment]
This is due at least in part to moving the Raven config into `application.yml`. I'm not able to get this set up properly, and I tried resetting my password on sentry.ragesoss.com to no avail.

**Comment by ragesoss** [comment]
Fixed with 396c8bb969c057b3d223d247c8d78022807ff6cb
