### ISSUE TITLE
Add option for instructors to randomly assign peer reviews to all students

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3377]

**Comment by mapra99** [comment]
Hello @ragesoss . Can I take this issue?

**Comment by ragesoss** [comment]
@mapra99 sure! It's not going to be trivial, and I'm not exactly sure what the best approach will be, but let us know if you have any questions.

**Comment by hardy1334** [comment]
@ragesoss  I'll like to work on this issue

**Comment by hardy1334** [comment]
@ragesoss  can you please ellaborate on the functionality part,what is to be done in it. I'm a bit confused, what do you mean by **peer reviews** here ?

**Comment by ragesoss** [comment]
This means an Assignment with the role `REVIEWING_ROLE`. From the frontend, this can be added right now either (as a student) from the My Articles section of the Home tab of a course, or (as an instructor) from the Students -> Article Assignments view, when a specific student is selected.

**Comment by hardy1334** [comment]
![Screen Shot 2020-04-16 at 12 16 30 AM](https://user-images.githubusercontent.com/31733278/79376300-95d7b900-7f77-11ea-98cc-8fde56c04635.png)

@ragesoss  You meant in the box where we can enter there should be option for another input box containing all the list of students as dropdown in it and then only **COURSE INSTRUCTOR** can assign it to the students enrolled in that particular course.Right ?

**Comment by ragesoss** [comment]
This feature would probably go on the 'Students' tab in the overview mode; there would be a button for the instructor that would randomly add a review for each assignment.

**Comment by hardy1334** [comment]
@ragesoss  For instructors, for a particular assignment randomly a student will be selected for reviewing an assignment. Right ?

**Comment by ragesoss** [comment]
Yes. It should be a different student than the one assigned to the article, and this feature should assign multiple reviewers to the same article depending on the `course.peer_review_count`.

**Comment by hardy1334** [comment]
ok, got it, I had a confusion about one scenario -
If all the students in the course are assigned one article then the next article which is to be assigned to the students, scenario for that would be that until all students are assigned the second article, a single student cannot be assigned the next article i.e third article

**Comment by ragesoss** [comment]
I'm not sure I understand. Can you write out the situation as an example in more detail?

**Comment by hardy1334** [comment]
![Screen Shot 2020-04-16 at 1 38 37 AM](https://user-images.githubusercontent.com/31733278/79383577-09cb8e80-7f83-11ea-8003-d6179df0b7bb.png)
 Flow should work like this - 
As soon as instructor clicks review that particular assignment should get assigned to random student. 
So What I meant above was - if in some scenario all the students enrolled in a course which have been randomly assigned articles are given an assignment for review, then the same student could be assigned multiple articles as well. Right ?

**Comment by hardy1334** [comment]
@ragesoss  what do you think of the above explanation

**Comment by ragesoss** [comment]
The idea here is that it should take one click (plus a confirmation) for an instructor to randomly assign the right number of peer reviews to all the student in their course.

The starting situation is (for example) that there are 10 students and each one is assigned a different article. Then the instructor clicks to randomly assign reviews, and every student gets assigned to review two different articles that classmates are working on.

If some students but not all already have reviews assigned, then it would count the already-assigned reviews toward the total number of reviews each student should have, so the end result (randomness aside) would be the same as if no reviews were assigned when the instructor used the feature.

**Comment by hardy1334** [comment]
@ragesoss  In the scenario where some students are assigned reviews so there **total number of reviews** will be maximum number of assignment a student is assigned. Something Like this - 

![Screen Shot 2020-04-18 at 2 40 56 AM](https://user-images.githubusercontent.com/31733278/79614402-12a49780-811e-11ea-8b6f-3b648ee7b4da.png)
