### ISSUE TITLE
Add troubleshooting for Windows in Docker setup document

### ISSUE THREAD

**Issue by xiaobaioo7** [WikiEducationFoundation/WikiEduDashboard#3378]
### Current Behavior:
At the moment, the ["Using Docker for development"](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/docker.md) document does not include troubleshooting section for Windows operating system. I ran into an issue with line ending format to run bash script during the process of building docker image. This seems to be caused by the incorrect Git configurations for line ending type and output conversion to achieve this task. (The default Git configurations will cause the line endings to be CRLF.) The issue caused the docker image build process to fail with error "./db_init.sh /bin/sh^M: bad interpreter: No such file or directory". 

### Desired Behavior:
Add support to the ["Using Docker for development"](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/docker.md) document to include troubleshooting section for common problems, in this case, the problem may relate to Windows operating system. Given this, future users of the document may refer to the troubleshooting section to gain better knowledge on setting up Docker for development.

### Related Files & Code:

* Add a troubleshooting section to the ["Using Docker for development"](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/docker.md) document. A sample common problem is to use Docker for Windows operating system, configure Git for core.eol (to be lf) and core.autocrlf (to be input)

### Additional context:

The following is more information about the environment where the issue occurred:
* OS: Windows 10 Pro 64-bit
* Git version: 2.7.2.windows.1
* Docker version: 19.03.1 (Docker Engine - Community) installed from Docker Desktop for Windows

FYI, when the issue occurred, I could run a new container in TTY session from the intermediate docker image. I was able to install dos2unix in the container and run the bash script file successfully from within.

**Comment by xiaobaioo7** [comment]
On a second note, this might not relate to the project, but rather a general problem with Linux docker containers on a Windows machine. Let me know if it makes sense to make the proposed changes. I can make these changes.

**Comment by ragesoss** [comment]
Yes, please do! Thanks for troubleshooting the setup documentation!

**Comment by xiaobaioo7** [comment]
Sure. FYI, I sent a PR. 

ps: not sure what's the best way to include reviewers or assignee for the PR. I added a cross reference to this issue in the PR.

**Comment by ragesoss** [comment]
Thanks. No need to add reviewers; we look at open PRs regularly as long as the tests pass. Here's an overview: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md#pull-request-process
