### ISSUE TITLE
Template error on enroll link

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#339]
This has been coming up a lot: http://sentry.ragesoss.com:8080/wiki-ed/production/group/278/

I'm not sure whether it's actually causing problems, or it's just an unhandled thing that doesn't cause user-facing errors. The high-priority part is to figure that out (and fix it if it is preventing users from enrolling).

**Comment by ragesoss** [comment]
This does seem to be preventing students from enrolling. I can't replicate it, though.

**Comment by thenickcox** [comment]
We have a lot of template errors because we're always returning JSON from controllers and not always rendering views, and I don't think that Nate always took the proper precautions to make Rails handle that correctly. I think most of the time, Rails will just swallow them if you're not reloading the page, which we rarely are. 

What process are you using to enroll?

**Comment by ragesoss** [comment]
I believe the users are trying to enroll via a course url with enrollment token, and creating accounts in some cases during the process. However, I haven't been able to replicate this error; it works just find with no errors when I've tested it.

**Comment by thenickcox** [comment]
In your priorities, you asked for an estimate on this. It's not really possible to estimate; I'm not sure why this is happening or what the fix would be. Like you, I wasn't able to duplicate this, so that makes it difficult to ballpark the time on a fix.

**Comment by ragesoss** [comment]
Exploring the Sentry logs more... most of the cases of that error are old ones, where spiders were hitting json endpoints that should not have been crawled. However, there are a handful of recent ones that seem to be from real users. The pattern that jumps out to me is the browser: Sentry reports one user on Linux / Firefox 10.0, and all the rest on OS = Other browser = Other.

The user agents are illuminating: Microsoft Office Word 2013, Drupal, and Firefox 10.0 account for all of the recent errors. I think the conclusion is that people are clicking links from weird places. Drupal is probably a Course Management System where a link got posted, and it tried to open it within the CMS maybe. And the other ones are probably links that people tried to open from within a Word doc of a syllabus that had the link.

**Comment by ragesoss** [comment]
The HEAD requests were hopefully the root of this. The same Sentry group has other events that aren't related to enrollment, but insofar as it related to enrollment, this issue may have been fixed via de8ea496e6c1d4dbe9e32c1541bf7bc760791ebe
