### ISSUE TITLE
Add as available article on "article finder" page gives 500 error.

### ISSUE THREAD

**Issue by xiaobaioo7** [WikiEducationFoundation/WikiEduDashboard#3395]
### What is happening?
On the 'article finder' page, in the search result for matching articles, when you click on 'Add as available article' for a selected article, an error shows up 'There was an error: This assignment already exists!'. The network tab in browser developer tool shows the call to (POST) 'http://localhost:3000/assignments.json?title=Buddhism&project=wikipedia&language=en&course_slug=HS%2FTest_program&user_id=&role=0' has a 500 error.

### To Reproduce
1. Go to 'Article Finder' page
2. Change wiki to 'en.wikipedia.org' (if you are using a different wiki)
3. Input 'Buddha' in the search bar and click on 'Submit'
4. Scroll down to the search result
5. Click on 'Add as available article' for any article
6. See error 'There was an error: This assignment already exists!'

### Expected behavior
The error should not show and the selected article should be added as available article.

### Screenshots
Please see the UI error in below screenshot:
![image](https://user-images.githubusercontent.com/19353500/66775951-122ef980-ee7a-11e9-977c-194f57b75fc8.png)

Please see the 500 status code for the XHR in browser developer tool in below screenshot:
![image](https://user-images.githubusercontent.com/19353500/66776022-4c989680-ee7a-11e9-9bb2-3d7d7b435d53.png)

### System Information

 - OS: Windows 10 Pro 
 - Browser: chrome
 - Browser Version: 77.0.3865.90 (Official Build) (64-bit)

### Additional context
This seems to only occur when the wiki is set to 'en.wikipedia.org'. While reproducing this in development environment, the Rails log indicates where the error was raised. It seems that the underlying issue was caused by the required file through a relative path cannot be referenced. Please see below for more details in the log:
![image](https://user-images.githubusercontent.com/19353500/66776580-89b15880-ee7b-11e9-8bbf-db525344b460.png)

If we change the reference through Rails.root, it seems to be working correctly.

**Comment by xiaobaioo7** [comment]
I can work on the fix if needed.

**Comment by ragesoss** [comment]
Thanks!
