### ISSUE TITLE
Logs for "update already running" have room for improvement

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#34]
When a rake task aborts because the previous one is already running, the logs could be more helpful in several ways:

* They are too verbose, including callback info that isn't necessary.
* They don't have a timestamp.
* I think they aren't necessarily accurate in reporting which task is already running, since they just output the name of their own task when they abort.

Also, is it the case that the update_daily task would get skipped for the day if an update_constantly task is running? At this point on production, we're back to generally skipping every other update because the previous one is taking too long.

**Comment by ntdb** [comment]
@ragesoss The update_daily and update_constantly tasks will not cause each other to be skipped. They can run simultaneously.

I'll look into improving the logs.

**Comment by ntdb** [comment]
Just to clarify a bit more, in [the batch task file](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/34c1eb4630650258d4f088382b3b117018eccd3d/lib/tasks/batch.rake) you'll notice that each task checks for the existence of a different .pid file before `begin`. In theory, all three tasks could be running at the same time, but never two of the same task.

For that reason there shouldn't be any inaccuracy in reporting which task is already running: those logs are generated when a task tries to run and finds that a previous iteration of the very same task is already running.

**Comment by ragesoss** [comment]
Yeah, I had noticed that different .pid thing at some point after asking the question. :)
