### ISSUE TITLE
clear button on Assignment due date field is misaligned, does nothing

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#340]
![screenshot from 2015-08-31 14-34-56](https://cloud.githubusercontent.com/assets/848483/9591058/925f4996-4fed-11e5-9cc4-43f5ef31a704.png)

**Comment by ragesoss** [comment]
See also the regression of another issue described in #278

**Comment by thenickcox** [comment]
Bummer. Another Firefox-only issue. Investigating further.

**Comment by thenickcox** [comment]
@ragesoss Actually, if this is Firefox-only, is it still highest priority?

**Comment by ragesoss** [comment]
@thenickcox no, but the other issue described in #278 still is.

**Comment by ragesoss** [comment]
and by 'other issue', I mean the thing where you put in one date, and it changes to the previous date after you save it... presumably because of moment and timezones and using a datetime instead of a date.

**Comment by thenickcox** [comment]
@bmathews This styling looks like it'll fix the alignment, but did you also confirm that it clears the due date? I think I remembered using the web inspector to get it lined up, but then it also didn't really function. This CSS-only fix fixes that?

**Comment by bmathews** [comment]
Yep! Previously the clickable portion was only the pseudo element, which
wasn't working in ff, but now it's the whole button and all is good.
