### ISSUE TITLE
Refactor componentWillMount and componentWillReceiveProps

### ISSUE THREAD

**Issue by dnahol** [WikiEducationFoundation/WikiEduDashboard#3478]
### What is happening?

componentWillMount and componentWillReceiveProps were producing warnings in the browser console, saying that use of the soon-to-be-depricated componentWillMount and componentWillReceiveProps has to be refactored and phased out. 

Commit [a0321daf12d62479d84eff5729dafce4089111bf](https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/3472/commits/a0321daf12d62479d84eff5729dafce4089111bf)
in PR #3472 renames these methods to the supported UNSAFE_ versions. 34 occurrences were replaced. 
 
The next step is to refactor these methods. 

### To Reproduce

1. Open dev code of project
2. Search whole project for UNSAFE_
3. See the React methods labeled UNSAFE_

### Expected behavior
A full refactor of the UNSAFE_ methods in accordance with the new React documentation.

### System Information

 - OS: MAC OS High Sierra Version 10.13.6
 - Browser Chrome Version 78.0.3904.70

### Additional context
From comment in PR #3472 
(This PR doesn't solve the issue, the conversation here explains the context)

> Hey @khyatisoneji, thanks for looking it over. I did notice the pre-existing warnings. Here is what I found. I am opening a separate issue to track that work: 
> 
> I looked at the errors and the React documentation. I tried changing `componentWillReceiveProps` in `app/assets/javascripts/components/revisions/diff-viewer.jsx` to `componentDidUpdate` and I am left with diffs that won't load. I tried the same for `app/assets/javascripts/components/common/article-viewer.jsx` with the same result.
> 
> I think that properly updating all the soon-to-be-deprecated `componentWillMount` and `componentWillReceiveProps` methods is going to be a separate refactoring using the new React version way of doing things. 
> 
> In the meantime, I ran this command from the documentation to rename such methods in `app/assets/javascripts`:
> 
> `npx react-codemod rename-unsafe-lifecycles` 
> 
> `componentWillReceiveProps()` -> `UNSAFE_componentWillReceiveProps()`
> `componentWillMount()` -> `UNSAFE_componentWillMount()`
> 
> 34 changes were made.
> 
> From [React Blog: Update on Async Rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)
> 
> > **Gradual Migration Path**
> > 
> > React follows semantic versioning, so this change will be gradual. Our current plan is:
> > 
> > **16.3:** Introduce aliases for the unsafe lifecycles, UNSAFE_componentWillMount, UNSAFE_componentWillReceiveProps, and UNSAFE_componentWillUpdate. (Both the old lifecycle names and the new aliases will work in this release.)
> > 
> > **A future 16.x release:** Enable deprecation warning for componentWillMount, componentWillReceiveProps, and componentWillUpdate. (Both the old lifecycle names and the new aliases will work in this release, but the old names will log a DEV-mode warning.)
> > 
> > **17.0:** Remove componentWillMount, componentWillReceiveProps, and componentWillUpdate . (Only the new “UNSAFE_” lifecycle names will work from this point forward.)
> >

**Comment by bwreid** [comment]
Closing this issue as it looks like a PR was merged for it.

**Comment by ragesoss** [comment]
I think the idea with this issue would be to do the refactoring work replace those now-renamed UNSAFE methods. They aren't going to throw up warnings any more, but they still represent cases where we're not handling side effects and data fetching the 'right' way for current React.

**Comment by dnahol** [comment]
Just added the first PR for this. I plan to do one per React component so that we can isolate any possible issues that come up with this refactor.
