### ISSUE TITLE
Loading element in diff_viewer should take up whole table width

### ISSUE THREAD

**Issue by dnahol** [WikiEducationFoundation/WikiEduDashboard#3482]
### Current Behavior:
From @ragesoss comment on #3472
> Cool! This looks like a nice improvement. I'm going to merge it now.
> 
> One way to improve it a little more will be to handle the Loading state better. After this change, the loading animation includes a border, which is a little distracting. 

### Desired Behavior:
From @ragesoss comment on #3472 
> Ideally, the loading animation should span the entire DiffViewer element instead of just the left portion.

### Related Files & Code:
app/assets/javascripts/components/revisions/diff_viewer.jsx

**Comment by ishantgupta777** [comment]
@ragesoss  I would like to work on this issue.

**Comment by DevanshKariya** [comment]
@ragesoss is this issue still open? I would like to work on it

**Comment by ragesoss** [comment]
@DevanshKariya yes, go for it.

**Comment by DevanshKariya** [comment]
@ragesoss Can you give some more info on this

**Comment by ragesoss** [comment]
Hm... it looks like this got fixed at some point, as there's no border on the DiffViewer loading element.

**Comment by DevanshKariya** [comment]
ok😅
