### ISSUE TITLE
When 'add/remove students' button is clicked, username input should get focus

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3501]
On the 'Students' tab of a course page, admins and instructors have an 'Add/Remove Students' button that opens a popover form where usernames of new students can be added.

This input box should grab focus when the popover opens, so that a user can immediately begin typing a username.

`enroll_button.jsx` is the place to start.

**Comment by Kartik1397** [comment]
@ragesoss Can I work on this?

**Comment by bwreid** [comment]
@Kartik1397 This is a perfectly good thing to work on. Thanks.  :)
