### ISSUE TITLE
Admins should be able to delete a Note from a Ticket

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3502]
The Ticket system allows for users to add a note to a ticket. It should also be possible to delete a note, for cases where one gets created by accident.

**Comment by AmitJoki** [comment]
Where are the tickets created @ragesoss also I found `TicketDispenser::Message::Kinds::NOTE` in two places, both being in specs, I might be missing something.

**Comment by bwreid** [comment]
@AmitJoki There is a separate repo that has the code for [TicketDispenser](https://github.com/WikiEducationFoundation/TicketDispenser).

**Comment by urbanecm** [comment]
Whcih tickets, @AmitJoki ? Could you clarify, please, by including information when I can find such tickets in the user (admin) interface?

Keep in mind students will have zero knowledge of your codebase and program. You can inspire by https://phabricator.wikimedia.org/T208532 as an example.

**Comment by ShcherbaDev** [comment]
Hi! I found out that localhost:3000/admin/dashboard is a ticketing page. But I'm having a 500 error when I'm trying to go to it:
![log](https://user-images.githubusercontent.com/29505891/70931413-11644080-2040-11ea-8b62-ac0d50048034.png)
My `ticket_dispenser_tickets` table:
![ticket_dispenser_tickets](https://user-images.githubusercontent.com/29505891/70931563-64d68e80-2040-11ea-84d0-c7923bf5dd73.png)
And here is the `ticket_dispenser_messages` table:
![ticket_dispenser_messages](https://user-images.githubusercontent.com/29505891/70931717-bd0d9080-2040-11ea-9181-0cdd36c57e8b.png)
Can you help me with this, please?

**Comment by AmitJoki** [comment]
From [this](https://github.com/WikiEducationFoundation/TicketDispenser/blob/master/app/controllers/ticket_dispenser/tickets_controller.rb#L5)2, it seems that there's no `tickets` parameter that's allowed by strong parameters either in TicketDispenser repository or in the TicketsController in this repository.

**Comment by hardy1334** [comment]
@ragesoss I'll to work on this issue

**Comment by hardy1334** [comment]
Can you guide me a bit on how can I create tickets so that I could understand the flow properly. I went to /tickets/dashboard route but I'm getting page not found on that route @ragesoss  @AmitJoki 

![output (14)](https://user-images.githubusercontent.com/31733278/75605936-ca013280-5b0d-11ea-9198-3781a6e74292.png)

**Comment by bwreid** [comment]
@hardy1334 Is your account set up as an administrator? This URL will only work if it is.

**Comment by hardy1334** [comment]
@bwreid It works fine now, I already did set up of my account as admin. Thanks for your reply
