### ISSUE TITLE
Add 'View as student' mode to course pages

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3503]
Instructors want to be able to see the interface as their students see it, which is especially important with the My Articles feature becoming more complex.

Ideally, this should let an instructor or admin pick a student in the course, and the interface would show up as if it were for that student.

**Comment by Kartik1397** [comment]
Hi @ragesoss, I like to work on this issue. Can you please provide some more details about this?

**Comment by ragesoss** [comment]
This one is pretty complex, but the basic idea is to have some kind of toggle to the interface for instructors, which would allow them to see the rest of the course page as their students would see it... so disabling edit buttons that are only available to instructors, and adding in features like MyArticles that only show up for students.

This might involve temporarily changing the `user` object that most of the course UI relies on for determining which permissions a user has. As a starting point, see `user_utils.js` and the places in the React components that look for the `isStudent` property.

**Comment by Kartik1397** [comment]
Is it ok? if I add 'View as student' button in navigation `course_navbar`

**Comment by ragesoss** [comment]
I think Home tab below the nav is probably a better place for it.

-Sage

**Comment by ragesoss** [comment]
I think the current situation where the instructor gets a My Articles section with a notice about it working the same way for students fixes 90% of the need for this. Probably not worth implementing a fuller version at this point.
