### ISSUE TITLE
ArticleViewer should add appropriate styling for Wikidata

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3507]
Wikidata items look terrible in ArticleViewer:

![article viewer wikidata](https://user-images.githubusercontent.com/848483/69078697-42c00100-09ed-11ea-9b85-56f19d7f978e.png)

We should add basic styles so that a Wikidata item looks similar in ArticleViewer to the way it looks on Wikidata (eg, https://www.wikidata.org/wiki/Q975 )

The place to start is probably `_article_viewer.styl`.

**Comment by AmitJoki** [comment]
Thanks! I'll draft a task on the GCI dashboard as well.

**Comment by n3rsti** [comment]
Can you link a page you put as image in issue description? I can't find that

**Comment by ragesoss** [comment]
Here's a similar example: https://outreachdashboard.wmflabs.org/courses/Wikimedia_CH,_EPFL/EPFL_and_WMCH_2019_-_Wikidata_and_Wikibase_intro_(November_13th_and_December_4th,_2019)/articles/edited?showArticle=56128756

**Comment by n3rsti** [comment]
Should it be responsive for smaller devices like ip5s?
