### ISSUE TITLE
Article Finder Row buttons not toggling

### ISSUE THREAD

**Issue by dnahol** [WikiEducationFoundation/WikiEduDashboard#3515]
`localhost:3000/courses/test/Short_test_(test)/article_finder`

### What is happening?

Buttons are not toggling and they are remaining disabled once article assigned, until reload.

In `article_finder_row.jsx`:

1. `this.props.assigned` is always `undefined` regardless of whether an article is assigned or not. 

2. According to the existing (pre-refactor) code, buttons in article rows should not be disabled when assigned; they should be toggled from `Assign` to `Unassign`.

### To Reproduce

1. Go to `localhost:3000/courses/test/Short_test_(test)/article_finder`
2. Search for an term in the search bar
3. Assign an article using the button
4. Instead of toggling to 'Unassign', the button will become disabled
5. Reload the page. Now all buttons will be 'Assign' and enabled, but still none will be toggled.

### Expected behavior
Buttons in article_finder_row should be toggling from 'Assign' to 'Unassign' when clicked. They  should only be disabled while an article is loading, then enabled again when article is done loading.

### Screenshots
![ArticleFinderToggle Issue](https://user-images.githubusercontent.com/2976514/69213904-5cab3200-0b1a-11ea-98e3-b88d3382f77a.gif)

### System Information

 - OS: MacOS High Sierra 10.13.6 (17G7024)
 - Browser Chrome 
 - Version 78.0.3904.97 (Official Build) (64-bit)

### Additional context
Bug found by @ragesoss and @dnahol while working on #3478 React Refactor, PR #3506 Article Finder

**Comment by shashwatkathuria** [comment]
I am working on this issue.
