### ISSUE TITLE
Duplicating edits on user/talk pages

### ISSUE THREAD

**Issue by bwreid** [WikiEducationFoundation/WikiEduDashboard#3519]
### What is happening?

The most recent PR (#3508) has introduced a bug where upon greeting the students, the template is added to the page even if there already is a template.

[For example.](https://en.wikipedia.org/wiki/User:Danielajbq) In that example, an edit was made by both the user and Elysia. In looking at the code, it seems like it should be fine. I tried reproduce the `.include?()` statement everything looked fine.

I'm a little uncertain of how to test this out while making sure it's not affecting Wikipedia, so I'd love your assistance on this.

**Comment by ragesoss** [comment]
Fixed with 9d538f8f616b9eefdeaaa42ed7922c93f76f4a00

Mediawiki strips trailing newlines from the text of a page upon save, so the our code wasn't finding a full match when the already-added template was the last thing on the page.
