### ISSUE TITLE
In Category list, 'last update' should indicate when a Category has never been updated

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3590]
### What is happening?
For an ArticleScopedCourse, the list of Categories includes data on how recently each one's list of articles has been updated, based on the record's `updated_at` attribute.

This is misleading for cases when it has only been updated at the time it was created, as from the user's perspective it hasn't been updated at all (and will still indicate 0 articles).

### Expected behavior
Indicate 'never' or "—" in the updated_at column if the updated_at value is the same as created_at.

**Comment by pranaykgupta** [comment]
I will like to work on it.

**Comment by ragesoss** [comment]
@pranaykgupta go for it, and let us know if you run into any problems.

**Comment by noordean** [comment]
@pranaykgupta Are you working on this yet? I would like to take it if you are not.

**Comment by pranaykgupta** [comment]
@noordean you can take it

**Comment by noordean** [comment]
@ragesoss Can you please shed more light on this ticket? I am on the "Articles Edited" page, and I can see the list of categories I created, but I can't see anywhere with "number of articles".
 
Also, I think it would be helpful if we attach screenshots/page-links to the issues we are creating as it would make it easy for newcomers to navigate the codebase quickly.

<img width="1187" alt="Screenshot 2019-12-26 at 11 42 34 AM" src="https://user-images.githubusercontent.com/14357823/71473123-1068a700-27d6-11ea-864d-c04607f885e6.png">

**Comment by ragesoss** [comment]
@noordean it looks like you might not be using the latest version of the project. Here's what it currently looks like:

![latest categories](https://user-images.githubusercontent.com/848483/71596354-158a6680-2af4-11ea-89f8-0c7f762a7443.png)

**Comment by noordean** [comment]
I think you are right @ragesoss. I forked this project some months ago and I don't think I've ever pulled the latest. I will check that. Thanks
