### ISSUE TITLE
Course nav bar  and Articles tab should change "Articles" label depending on course type

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3596]
### Current Behavior:
The navbar always says 'Articles', and that tab's header says 'Articles Edited' (and Assigned Articles, and Available Articles).

### Desired Behavior:
For courses with wikidata as the home wiki, these Article labels should instead say "Items".

For courses with other non-Wikipedia home wikis, the labels should say "Pages".

### Additional context:
We already do similar switching of labels for the Students tab and other interface messages using `course.string_prefix`. The same strategy probably makes sense here. We made need a third prefix for wikidata.

**Comment by Muskan-Mittal** [comment]
Hi, can I take this issue?

**Comment by noordean** [comment]
I would like to work on this @ragesoss . Can I go ahead?

**Comment by ragesoss** [comment]
@noordean go for it

**Comment by sastava007** [comment]
> I would like to work on this @ragesoss . Can I go ahead?

@noordean Any progress?

**Comment by noordean** [comment]
@sastava007 Please go ahead. I have been pretty busy lately.
