### ISSUE TITLE
In Uploads tab, UploadViewer file usage table displays differently depending on view mode

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3643]
### What is happening?
UploadViewer is the component to see details about a single file from the Uploads tab. The Uploads tab has three layout options: gallery, list, and grid. In list mode, the file usage table inherits some of the styling of the Uploads list itself (which is also a table), so the usage table has borders around the cells. In gallery and grid modes, the borders are gone.

### To Reproduce

Create a course with uploads, including some that are in use on Wikipedia articles. (The `populate` script should create such a course.)

Go to the Uploads tab, switch to list view, sort the list by usage count so you can find an upload that is in use, then switch to a different layout and view the same image.

### Expected behavior
The file usage table should have consistent styling regardless of Uploads layout. The borders are preferable to the borderless version (although further design changes to UploadViewer are welcome).

### Screenshots
In list layout:
![list](https://user-images.githubusercontent.com/848483/71853422-3d4b7280-3090-11ea-970a-767321911970.png)

In the other layouts:
![non-list](https://user-images.githubusercontent.com/848483/71853423-3d4b7280-3090-11ea-9a18-7c18bb4a5195.png)

**Comment by shipcy** [comment]
Can I take this issue?

**Comment by ragesoss** [comment]
yes, please do.

**Comment by Harshwp** [comment]
Hello! I'd like to work on this

**Comment by Tripathi-Vaibhav** [comment]
Hi! Can you share the link for its codebase ?

**Comment by ragesoss** [comment]
@Tripathi-Vaibhav this comes from the `uploads` components in `app/assets/javascripts/uploads` and from the corresponding stylesheet code, probably in `app/assets/stylesheets/modules/_uploads.styl`. The `user_roles.md` documentation file has details about how to set up your environment to be able to test this out.

**Comment by soumyaa1804** [comment]
@Tripathi-Vaibhav are you working on this issue? If not, I would like to work on it.

**Comment by sastava007** [comment]
Sorry, @soumyaa1804 . But I'm already working on this. 
Pardon me I haven't left any comment on it, hope you understand.

**Comment by Tripathi-Vaibhav** [comment]
No

**Comment by Tripathi-Vaibhav** [comment]
No Soumya Sharma

**Comment by soumyaa1804** [comment]
Okay, cool! @sastava007 @Tripathi-Vaibhav

**Comment by tichnas** [comment]
Is this issue still open?

**Comment by ragesoss** [comment]
Whoops! Forgot to close it, but Manasa's patch fixed it.
