### ISSUE TITLE
Course revision count should only include revisions from tracked wikis

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3647]
Currently, if there are other edits by the same user on an untracked wiki (typically, because they are being tracked for a different course), those revisions are counted in the total, even though only tracked wikis are counted for the other stats.

**Comment by ciphereck** [comment]
@ragesoss Can I work on this?

**Comment by ragesoss** [comment]
@ciphereck once you've finished the issue you have an open PR for, leave a note here if you take this one up.

**Comment by shashwatkathuria** [comment]
@ragesoss 
Please tell me if I understand it right or wrong.
There is a Course1 and a Course2. Same user makes edits on both courses but the revision counts of the specific courses are counted in total rather than individual.
Or can you please explain it once to me so that I can reproduce it and work on it?

**Comment by ragesoss** [comment]
@shashwatkathuria 

There are two courses. One is on en.wikipedia.org (and has that as the only tracked wiki), and another is on www.wikidata.org (and has that as the only tracked wiki).

The user makes revisions on both wikis, and the revision count for each course should include only the revisions for the wiki that course is tracking.

Currently, the course revision count will include all edits in the Dashboard database made by students during the course period, even if they are not edits to wikis tracked by that course.

**Comment by shashwatkathuria** [comment]
@ragesoss Do I need to change def tracked_revisions at app/models/course.rb:266 and include some filter of having only those revisions included in course.wikis (wiki_ids) for solving this issue? I wanted to know if I'm going inthe right path, because this is kind of confusing me.

**Comment by ragesoss** [comment]
Yes, I think that makes sense as the place to implement limiting the counted revisions to tracked wikis.
