### ISSUE TITLE
disordered timeline page in mobile phones

### ISSUE THREAD

**Issue by Manasa2850** [WikiEducationFoundation/WikiEduDashboard#3648]
This is how the timeline page for each course looks in mobile phones.
![Before](https://user-images.githubusercontent.com/43354059/71980512-3e260500-3246-11ea-917c-dc932222fc3c.jpeg)

**Comment by kunalthedev** [comment]
@ragesoss  To solve this, should i just add some relevant margin's in CSS or something else?

**Comment by ragesoss** [comment]
I think the ideal solution to this would be based on using the media queries system that we already use to provide mobile-friendly layouts. (Look for `+above(` and `+below(` in the .styl files.) The desktop layout should remain the same, but whatever adjustments need to be make to improve the mobile layout should apply at lower widths. It will be easiest to understand and modify later if, where possible, it uses the same CSS properties that are already being used to style the classes of a given component, just with different values for the mobile version.

**Comment by kunalthedev** [comment]
@ragesoss this can be closed now
