### ISSUE TITLE
Editing the training modules of a block is buggy when multiple types are present

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3653]
If there is more than one type of module present (training / exercise / discussion) then in edit mode, there are two inputs for adding / removing modules.

1. Both have the same label (unlike in view mode).
2. All the modules are available for each input, not just the corresponding type.
3. Adding or removing modules from the second input and saving just deletes all the modules that are not in the first input.
4. Some modules (ones with individual vs group) have the same name and there's no way to tell which you've selected.

**Comment by Kartik1397** [comment]
Hi @ragesoss Can you please tell how to create/load training moudles and edit them?
because I see this when I open training section.
![Screenshot from 2020-01-13 02-30-24](https://user-images.githubusercontent.com/24036721/72225559-d573bb00-35ac-11ea-8e30-42ae4184c93a.png)

**Comment by ragesoss** [comment]
@Kartik1397 to load the training modules, include `wiki_education: 'true'` in your application.yml (which will make the system use the `wiki_ed` set of training modules from the codebase), and then visit http://localhost:3000/reload_trainings?module=all to load the records.

After that, you'll need to set up a course with training modules in order to replicate the bugs.

**Comment by Kartik1397** [comment]
Only one input for adding/removing modules will ok?

**Comment by ragesoss** [comment]
That could work, as long as all of the modules across multiple categories are displayed in that one input (and still rendered in separate places when you're not in edit mode).
