### ISSUE TITLE
Link to completed training module in a timeline block says 'Continue'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3654]
In the timeline, if a block has an assigned training module that you have already completed, there's no indication that it has been completed; the link says 'Continue'.

**Comment by Manasa2850** [comment]
@ragesoss can I work on this?

**Comment by Manasa2850** [comment]
@ragesoss could I work on this?

**Comment by ragesoss** [comment]
@Manasa2850 I think Wes and I are going to make sure this gets fixed today.

**Comment by bwreid** [comment]
This was solved by PR #3679
