### ISSUE TITLE
User revision not showing up in student drawer as expected

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#366]
There's a revision that's not showing up as expected, for user MYao, here: http://dashboard.wikiedu.org/courses/Rice_University/Poverty,_Justice,_and_Capabilities_%28Fall_2015%29/students

The edit is to the page 'Talk:Health in China', and it shows up in the /activity view for the whole class, but not in the drawer for MYao.  Revision.id is 679332246, article.id is 701327, user.id is 26150432.

I can't see any reason why this edit is getting filtered out, as it's in our database and similar edits are showing up for other users.

**Comment by thenickcox** [comment]
```ruby
2.1.5 :005 > Revision.find(679332246).article
 => #<Article id: 701327, title: "Health_in_China", views: 0, updated_at: "2015-09-08 07:54:40", created_at: "2015-09-03 23:04:11", character_sum: 0, revision_count: 0, views_updated_at: nil, namespace: 1, rating: nil, rating_updated_at: nil, deleted: false, language: nil, average_views: nil, average_views_updated_at: nil>
2.1.5 :006 > ArticlesCourses.where(article_id: 701327)
 => #<ActiveRecord::Relation []>
```

**Comment by ragesoss** [comment]
Aha! I wonder, then, why there is no AC for that page, but there are ACs for the talk page edits made by other students. I'll look into it when I have a chance.

**Comment by ragesoss** [comment]
I don't think ArticlesCourses are relevant to the way these lists get created.

A classmate's drawer includes a talk page edit to 'Talk:Milwaukee', which similarly has no ArticlesCourses.

**Comment by thenickcox** [comment]
It was a red herring!

**Comment by ragesoss** [comment]
Well... Now this revision shows up. And I still can't think of any reason why it didn't before, as it was in our database and showing up in the course activity list.

**Comment by thenickcox** [comment]
Maybe it _was_ caching. So…close?

**Comment by ragesoss** [comment]
Yeah, I guess so. We don't have caching, right? I'll keep an eye out for similar cases. In my 10 minutes of searching, I couldn't find any other instances of this issue currently.

**Comment by ragesoss** [comment]
This is happening again for User:Anushbonam in this course:
http://dashboard.wikiedu.org/courses/North_Carolina_State_University/Object_Oriented_Design_and_Development_%28Fall_2015%29/students

The sum of userspace contributions listed there, 152, represents just the first two (automatic) edits to the userpage and sandbox page (which are filtered out of the drawer as 'system edits'), but the rest of the edits from the last several days are not showing up: https://en.wikipedia.org/wiki/Special:Contributions/Anushbonam
