### ISSUE TITLE
replace jquery with vanilla JS in `nav.jsx`

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3675]
The navbar component, `nav.jsx`, uses global jquery (`$`) to extract data from the hmtl and to find the window dimensions. These things can and should be done with vanilla JavaScript instead, as part of the gradual effort to remove the need for jquery in the codebase.

**Comment by Vinit-Dantkale** [comment]
Can I give this a try? I'll inform about the status if any issue arises

**Comment by ragesoss** [comment]
@Vinit-Dantkale go for it

**Comment by pranaykgupta** [comment]
I would like to take this up
