### ISSUE TITLE
Marking an exercise as complete isn't course-specific

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3680]
Unlike with completing a training module, if a user completes an exercise during one course and then takes another course that also uses that exercise, we should not use the completion of the exercise from the earlier course to count... exercise completion, unlike training module completion, is a course-specific concept.

One possible solution would be to update how the data for marking completion gets stored on a TrainingModulesUsers record: the flags field should record completion on a course-by-course basis rather than as a singular yes/no status.

**Comment by Kartik1397** [comment]
Hi @ragesoss, I like to work on this issue. Can you please provide some more details about this?

**Comment by ragesoss** [comment]
@Kartik1397 this relates to the `EXERCISE` kind of `TrainingModule`. If a course has one of these exercise modules assigned, then an enrolled student will see an interface for recording completion of the exercise from the Home tab of their course.

Currently, we handle that record of completion by storing it on the corresponding `TrainingModulesUsers` record, which is for keeping track of information about which users have made it through which training modules. For most modules, there's no point in having someone complete the module more than once, so if a student takes a second course with the same training module assigned, they'll already have credit for completing it from the earlier course.

The exercises, however, are the sorts of activities that would need to be done again for a second course, as they are part of the specific series of things that a student does in preparing to work on a particular article. Currently, marking an exercise as complete would _also_ show that it was already completed if a student took a second course with the same exercise.

To fix this and make exercise completion tied to a particular course, we need to tweak both the frontend and backend to record which course any given exercise completion is associated with.

**Comment by Kartik1397** [comment]
Is it ok if I add `course_id` attribute to `training_module_user` table to make exercise course-specific?
