### ISSUE TITLE
Improve cell padding and text overflow for tables/lists

### ISSUE THREAD

**Issue by bmathews** [WikiEducationFoundation/WikiEduDashboard#369]
![image](https://cloud.githubusercontent.com/assets/848347/9742883/093707fe-5618-11e5-964a-07f66ce73ada.png)

**Comment by bmathews** [comment]
Related:

![image](https://cloud.githubusercontent.com/assets/848347/11602662/d444436e-9a90-11e5-9d78-a4614e034d8e.png)

**Comment by ragesoss** [comment]
This is very different now, and there are a few other bugs for the current, similar table layout issues.
