### ISSUE TITLE
Error in running the server.

### ISSUE THREAD

**Issue by Swayamsvk** [WikiEducationFoundation/WikiEduDashboard#3693]
The server starts with the command `guard`.When the server starts instead of loading the website it shows
"500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong."
![Screenshot from 2020-01-23 02-54-16](https://user-images.githubusercontent.com/42679893/72935811-1083a480-3d8c-11ea-900d-00be9a4eb0ff.png)

System Information
 - OS: Ubuntu 18.04.3
 - Browser: Chrome

**Comment by ragesoss** [comment]
@Swayamsvk hi! You should look at the terminal where you are running`guard` to find details about what went wrong. That terminal should show a stack trace with details of the error you ran into (and possibly suggestion for fixing it).

If you find the stack trace and you're still stuck, please post it here.

**Comment by Swayamsvk** [comment]
$`guard`
15:29:38 - INFO - Bundle already up-to-date
15:29:38 - INFO - [Guard::Rails] will start the default web server on port 3000 in development.
15:29:38 - INFO - Starting Rails...

=> Booting Puma
=> Rails 6.0.0 application starting in development 
=> Run `rails server --help` for more startup options
W, [2020-01-23T15:29:47.194637 #5593]  WARN -- Skylight: [SKYLIGHT] [4.2.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Puma starting in single mode...
* Version 4.3.1 (ruby 2.5.1-p57), codename: Mysterious Traveller
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
Use Ctrl-C to stop
15:29:50 - INFO - Rails started, pid 5593

15:29:50 - INFO - Guard::RSpec is running
15:29:52 - INFO - Guard is now watching at '/media/swayam/A:/gsoc2020new/wiki/WikiEduDashboard'
[1] guard(main)> [2020-01-23 15:29:58.619 INFO ] Started GET "/" for ::1 at 2020-01-23 15:29:58 +0530
[2020-01-23 15:29:58.681 FATAL] Mysql2::Error (Access denied for user 'wiki'@'localhost'):
  
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `connect'
mysql2 (0.5.3) lib/mysql2/client.rb:90:in `initialize'
activerecord (6.0.0) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
activerecord (6.0.0) lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:879:in `new_connection'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:923:in `checkout_new_connection'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:902:in `try_to_checkout_new_connection'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:863:in `acquire_connection'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:587:in `checkout'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `connection'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:1111:in `retrieve_connection'
activerecord (6.0.0) lib/active_record/connection_handling.rb:231:in `retrieve_connection'
activerecord (6.0.0) lib/active_record/connection_handling.rb:199:in `connection'
activerecord (6.0.0) lib/active_record/migration.rb:562:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (6.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
skylight-core (4.2.1) lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.1) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.1) lib/rack/runtime.rb:24:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/static.rb:126:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.1) lib/rack/sendfile.rb:113:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
sentry-raven (2.13.0) lib/raven/integrations/rack.rb:51:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (6.0.0) lib/rails/engine.rb:526:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
puma (4.3.1) lib/puma/configuration.rb:228:in `call'
puma (4.3.1) lib/puma/server.rb:681:in `handle_request'
puma (4.3.1) lib/puma/server.rb:472:in `process_client'
puma (4.3.1) lib/puma/server.rb:328:in `block in run'
puma (4.3.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
[2020-01-23 15:29:58.706 INFO ] Processing by ErrorsController#internal_server_error as HTML
[2020-01-23 15:29:58.707 INFO ] Completed 500 Internal Server Error in 1ms (Allocations: 392)
Error during failsafe response: Devise could not find the `Warden::Proxy` instance on your request environment.
Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
  /home/swayam/.rvm/gems/ruby-2.5.1/gems/devise-4.7.1/lib/devise/controllers/helpers.rb:143:in `warden'
  /home/swayam/.rvm/gems/ruby-2.5.1/gems/devise-4.7.1/lib/devise/controllers/helpers.rb:126:in `current_user'
  /media/swayam/A:/gsoc2020new/wiki/WikiEduDashboard/app/controllers/application_controller.rb:76:in `check_for_expired_oauth_credentials'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:429:in `block in make_lambda'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:202:in `block in halting'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `block in invoke_before'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `each'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `invoke_before'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:110:in `block in run_callbacks'
  /home/swayam/gems/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `instance_exec'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:139:in `run_callbacks'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `block in instrument'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  /home/swayam/gems/gems/activerecord-6.0.0/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:136:in `process'
  /home/swayam/gems/gems/actionview-6.0.0/lib/action_view/rendering.rb:39:in `process'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_controller/metal.rb:191:in `dispatch'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_controller/metal.rb:252:in `dispatch'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:33:in `serve'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:49:in `block in serve'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `each'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `serve'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:837:in `call'
  /home/swayam/gems/gems/skylight-core-4.2.1/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
  /home/swayam/gems/gems/skylight-core-4.2.1/lib/skylight/core/fanout.rb:25:in `instrument'
  /home/swayam/gems/gems/skylight-core-4.2.1/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/railties-6.0.0/lib/rails/rack/logger.rb:38:in `call_app'
  /home/swayam/gems/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `block in call'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
  /home/swayam/gems/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /home/swayam/gems/gems/skylight-core-4.2.1/lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/rack-2.1.1/lib/rack/method_override.rb:24:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/rack-2.1.1/lib/rack/runtime.rb:24:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/activesupport-6.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/middleware/static.rb:126:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/rack-2.1.1/lib/rack/sendfile.rb:113:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/actionpack-6.0.0/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/sentry-raven-2.13.0/lib/raven/integrations/rack.rb:51:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/railties-6.0.0/lib/rails/engine.rb:526:in `call'
  /home/swayam/gems/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  /home/swayam/gems/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
  /home/swayam/gems/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
  /home/swayam/gems/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
  /home/swayam/gems/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
  /home/swayam/gems/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'

**Comment by Swayamsvk** [comment]
This is everything that is shown in the terminal

**Comment by ragesoss** [comment]
The error that starts it all off is `Mysql2::Error (Access denied for user 'wiki'@'localhost')`. It looks like you need to set up a mysql user and/or add the password for that user in `database.yml`.
