### ISSUE TITLE
Dashboard - Some counts for "student editors who have completed training" are wrong

### ISSUE THREAD

**Issue by bmathews** [WikiEducationFoundation/WikiEduDashboard#372]
![image](https://cloud.githubusercontent.com/assets/848347/9793353/ec565238-5799-11e5-902f-cac96d4320ee.png)

![image](https://cloud.githubusercontent.com/assets/848347/9793384/0cccb28c-579a-11e5-8394-6b31f60083e9.png)

![image](https://cloud.githubusercontent.com/assets/848347/9793393/18a7017a-579a-11e5-8e6a-adec59f617e1.png)

http://dashboard.wikiedu.org/courses/Brigham_Young_University/Biophysics_(Fall_2015)

**Comment by ragesoss** [comment]
This is probably related to the fix for #259
