### ISSUE TITLE
Wikidata: one reference with several statements counted as multiple references

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3774]
See https://phabricator.wikimedia.org/T244229

Is this a bug with the Dashboard, or does it come from the ORES data and represent a potential bug with how ORES models references?

**Comment by jproft** [comment]
Is it possible that `feature.len(<datasource.wikidatawiki.revision.references>)` is not the number of unique references but rather the number of statements added to the references?

**Comment by ragesoss** [comment]
This should be fixed now with our new method of calculating refs.
