### ISSUE TITLE
During Wiki Education course creation, ask instructor whether they have TAs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3775]
We want to:
a) ask instructors during course creation whether they have TA support; and
b) send reminder emails after a week if no additional instructor (ie, the TA) has been added to the course yet, for courses that do have a TA.

The first step (this issue) is to collect that information. It should probably be stored in the form of a tag.

After that, we can create a new alert type and alert manager to trigger emails to be sent out.

**Comment by YanaNirvana** [comment]
I'd like to work on this
