### ISSUE TITLE
Course page should inform user when a save action fails

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#378]
When a course page or timeline or other post of course data fails, the UI still behaves as if it succeeded; the updated data is reflected in the rendered view (until the page is refreshed and the old data returns), and the UI does not inform the user that their action failed.

Even just a popup and refresh... or a popup and displaying the unsaved data... would be a nice improvement, and help us make sure that users are aware of, and report, when the system is failing to save.

**Comment by mattfordham** [comment]
I think I'm on to something for this, but assigning to myself as I may not wrap up today.

**Comment by mattfordham** [comment]
I got this mostly working, with some duct tape, and then started to get bad feelings about it. The bad feelings led me towards a deeper issue with the way React Actions are being handled in a few places. For the greater good, I'm going to work on refactoring the data flow a little and adding error notification in a separate branch. Will keep you posted with my progress, and will likely be something to discuss as a group on Friday.

**Comment by mattfordham** [comment]
But, I'm in complete agreement with this error handling being a major need. We are making lot of "optimistic" API calls and assuming the best.

**Comment by ragesoss** [comment]
Sounds great!

**Comment by thenickcox** [comment]
Closed via @bmathews's great work!
