### ISSUE TITLE
Edit button on timeline Block floats above training module selector dropdown

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3792]
When another block is beneath the one you are editing, the Edit button renders on top of the active select dropdown.

![module select](https://user-images.githubusercontent.com/848483/75278562-f3912580-57be-11ea-81b6-c25d8633b077.png)

**Comment by shashwatkathuria** [comment]
Can you please help me how to create training modules to the list or link me to some doc for the same? I am not able to reproduce the issue as my Training module dropdown list does not have any options and is displaying only 'No options' which is not sufficient to override the edit button.

**Comment by ragesoss** [comment]
@shashwatkathuria:

1. in `application.yml`, make sure you have `wiki_education: 'true'` set.
2. load the training modules by going to `/reload_trainings?module=all`
