### ISSUE TITLE
'e.responseJSON is undefined' javascript error in Firefox

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#380]
This one appears to be exclusive to Firefox: http://sentry.ragesoss.com:8080/wiki-ed/production/group/577/

**Comment by thenickcox** [comment]
Investigated this a bit. Unable to duplicate, even with the same browser version (Firefox 39), OS (Win7), and URL as [this one](http://sentry.ragesoss.com:8080/wiki-ed/production/group/577/).

Here's my console:
![screen shot 2015-09-22 at 1 18 50 pm](https://cloud.githubusercontent.com/assets/702327/10030827/7fb19b58-612e-11e5-998a-0017408c5d05.png)

Another case where we could null check [the line in question](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/utils/api.coffee#L29), but it's definitely possible this isn't affecting any users in a significant way.

**Comment by ragesoss** [comment]
Resolved with the merge of #478
