### ISSUE TITLE
'Cannot read property 'childNodes' of undefined' javascript error in Chrome

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#381]
This one appears to be limited to Chrome: http://sentry.ragesoss.com:8080/wiki-ed/production/group/580/events/16714/

**Comment by thenickcox** [comment]
This only occurs on 404 pages (that I could find–I tried clicking the links for about 15 of the errors to make sure). Our `list.js` is still trying to make a list out of elements, which it's unable to do. I move to close.

**Comment by ragesoss** [comment]
Rather than close, for things like this I'd like to create a new label that basically means: this is causing noise on Sentry, but otherwise isn't a problem. It would still be very nice to fix these kinds of things, eventually, because it will make Sentry much more useful for catching new problems quickly.

**Comment by thenickcox** [comment]
A good follow-up to this would be to find where list.js is called. I can't find where it is. It's possible that it's dead code, and we can eliminate it. It might throw a _different_, more helpful error.

**Comment by bmathews** [comment]
Lists are created in `source/app/assets/javascripts/utils/course.coffee`

**Comment by ragesoss** [comment]
This particular error seems to have gotten fixed at some point.
