### ISSUE TITLE
Minor bug in permissions statement (onboarding).

### ISSUE THREAD

**Issue by shashwatkathuria** [WikiEducationFoundation/WikiEduDashboard#3816]
### What is happening?
Two times 'to' is written.

### To Reproduce

   1. Go to onboarding, follow till permissions page.
   2. See error

### Expected behavior
One time 'to'.

### Screenshots
![Screenshot from 2020-02-28 17-16-05](https://user-images.githubusercontent.com/37243661/75546434-87c4ec00-5a4e-11ea-823b-454be42449cf.png)

### System Information

 - OS: Ubuntu 18.04
 - Browser Chrome
 - Latest Version

**Comment by ragesoss** [comment]
Nice catch!
