### ISSUE TITLE
DYK list should be sorted by revision datetime

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#383]
Currently, the DYK eligible feed is sorted by Article id, by default. It should instead be sorted by revision datetime (most recent edits first).

**Comment by ragesoss** [comment]
@thenickcox Do you know how to solve this with like a quick one-line change? I thought it would be straightforward, but I quickly got lost trying to figure out how the React keys and default sorting work.

**Comment by thenickcox** [comment]
@ragesoss We should probably order the scope coming back from the controller that way, not handle it on the client.

**Comment by ragesoss** [comment]
@thenickcox That's a little tricky, though, because the datetime comes from the latest revision (which if fetched in the jbuilder), but the controller just generates the list of articles.

Is there a way to sort the array that the jbuilder makes? I tried but could not figure out how to do so.

**Comment by thenickcox** [comment]
@ragesoss There is, but it's not _super_ efficient to sort it in memory. Is this something you're wanting me to drop #384 and pick up?

**Comment by ragesoss** [comment]
@thenickcox No, I'll keep working on it. I just pinged you cuz I got stuck. So, I guess I'll try to handle the sorting within the RevisionAnaltyicsService.

**Comment by ragesoss** [comment]
( @thenickcox I'm guessing the efficiency of a small to medium array sorting in memory shouldn't trouble us much. If you have any links pointing me in the right direction for sorting that array in the jbuilder, toss 'em to me!)

**Comment by thenickcox** [comment]
Try something like

```ruby
...
revision = article.revisions.sort_by { |a, b| a.created_at < b.created_at }.last
```
Play around with the comparison operators.

**Comment by ragesoss** [comment]
Here's the context: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/views/revision_analytics/dyk_eligible.json.jbuilder

The revisions aren't actually part of the array that the jbuilder makes, and what I can't figure out is how to sort that array of article data by revision_datetime after (or during the process of) building it via `json.array!`

**Comment by thenickcox** [comment]
What if you proxied the sorting into another object. The responsibility of the `RevisionAnalyticsService` should be to _get_ the records, and the jbuilder to _display_ them. Perhaps sorting should be the domain of an intermediary object.
