### ISSUE TITLE
Course navbar flashes 'missing message' briefly before rendering 'Articles' link

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3849]
I think this bug was introduced with https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/3772

When you load a course page, it briefly shows the fallback text for a missing i18n message in the navbar instead of the appropriate Articles/Items/Pages text. This is most apparent if you do a hard refresh, for example on https://dashboard.wikiedu.org/courses/McMaster_University/Selected_Topics_in_the_Sociology_of_Education_(Winter)

This is because the `wiki_string_prefix` value isn't available until the `course` data is received from the server; the navbar renders before any course data is received, based on the initial default state of the `course` reducer in Redux.

The right solution here is probably to not render the navbar at all until course data is received.

**Comment by TaimurAzhar** [comment]
Hi, can I be assigned this issue? I am an Outreachy applicant. Looking for getting started as soon as possible.

**Comment by ragesoss** [comment]
Go for it. We don't typically assign issues, but please post again if you stop working on it.

**Comment by TaimurAzhar** [comment]
Great. Thanks.
