### ISSUE TITLE
Rubocop line length metric does more harm than good

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#385]
Breaking up lines [like this](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/controllers/courses_controller.rb#L37-L39) sacrifices readability. Rubocop should work for us based on the way we want to work, not the other way around. I'd _strongly_ vote to disable the line length metric and strive for lines under a certain number of characters when possible, and disregard it when it doesn't make sense.

**Comment by ragesoss** [comment]
How about we change it to 100?
