### ISSUE TITLE
Center align the contain of the div

### ISSUE THREAD

**Issue by rajat2502** [WikiEducationFoundation/WikiEduDashboard#3850]
> Center Align the hero div using flexbox for better user experience.

### What is happening?
> In the Hero div of the main page the content is left aligned which is giving it an inconsistent look from the other contents of the page.

### Expected behavior
> The content should be center-aligned using flexbox or any other CSS styles.

### Screenshots
![image](https://user-images.githubusercontent.com/42200276/76241626-46f18200-625b-11ea-969e-b6e6ddef1465.png)

### System Information

 - OS: [Linux 19.04]
 - Browser [chrome]

**Comment by ClintonEnyinna** [comment]
I'm an Outreachy applicant and I'm interested in working on this issue. Please can it be assigned to me?

**Comment by rajat2502** [comment]
Hey @ragesoss can I work on this issue?

**Comment by ragesoss** [comment]
@rajat2502 sure. I'm not sure that I see the problem, but having a before/after comparison will certainly help.

**Comment by ClintonEnyinna** [comment]
Still workin on this? @rajat2502
