### ISSUE TITLE
Add the number of results

### ISSUE THREAD

**Issue by rajat2502** [WikiEducationFoundation/WikiEduDashboard#3851]
> In the Search field on the explore page, the result can also have the feature of the total number of results related to that particular search.

### Current Behavior:
> Currently, It only shows "Results for ${SeachItem}"

### Desired Behavior:
>Add the Total number of results found to it.
It should be like "Total ${number} Results for ${SearchItem}.

### Additional context:
> 
![image](https://user-images.githubusercontent.com/42200276/76242699-24606880-625d-11ea-9b55-ae78818b229d.png)

**Comment by ClintonEnyinna** [comment]
I'm an Outreachy applicant and I'm interested in working on this issue. Please can it be assigned to me?

**Comment by ragesoss** [comment]
Hi. We don't formally assign issues for this project, but feel free to work on this. You should work on one issue at a time, and leave a note if you stop working on it.

**Comment by ClintonEnyinna** [comment]
I created a pull request for the issue

**Comment by YanaNirvana** [comment]
Sorry if this sounds obvious:  The merged PR looks like it resolves this issue... is there a reason for that this is still open?  / Are there additional work to be done?

**Comment by ragesoss** [comment]
Nope, the automatic closing just didn't trigger when the PR closed.
