### ISSUE TITLE
Replace usage of Timecop in tests

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3864]
We have a handful of tests that use `Timecop`, a gem to manipulate system time.

It looks like Rails now includes some time-related features that could be used instead: https://frontdeveloper.pl/2020/03/how-we-migrated-from-timecop-to-built-in-rails-5-2-time-helpers/

Replace as much of our Timecop usage as possible with Rails time helpers — and ideally, completely remove the `timecop` gem as a dependency.

**Comment by vineshpersaud** [comment]
I'm an Outreachy applicant  and I would like to work o this.

**Comment by vineshpersaud** [comment]
I submitted a pull request .
