### ISSUE TITLE
Course creator should jump straight to new course if no cloneable old courses are available

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#387]

**Comment by thenickcox** [comment]
Just to clarify. Did we decide that there were any criteria for cloneability other than previously existing?

**Comment by ragesoss** [comment]
Previously existing and listed. And now that I think of it, only non-legacy courses should count... because legacy courses won't have timelines to clone, even though some instructors do have legacy courses in the system.
