### ISSUE TITLE
Dead code in timeline controller and grading component?

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#388]
I think the index, gradeable_params, and update_gradeables methods in the timeline controller are all dead code: https://codeclimate.com/github/WikiEducationFoundation/WikiEduDashboard/coverage/55fda673090fb12fc204e6fd

The course creation spec includes checking `gradeable` on a new block as well as adjusting the value, and saving. These steps do not hit those controller methods.

We initially starting merging the Timeline and Gradeable editing into the same thing here: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/21b41bcb76fb64438665f1d4fe0239f84b143b3e

At that point, we'd already disabled some of the functions of the grading component: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/fc5af1c26364eef882d58ecbafe2aa4bc0d07900

@ntdb: do the gradeables just get updated through TimelineController#update_block, and skip the gradeables methods altogether? And is the TimelineController#index a leftover from before the switch to React?

**Comment by ntdb** [comment]
I think you're right on all points here, @ragesoss. Gradeables are updated along with the rest of the timeline (#update_block). The "gradeables" and "index" methods are just leftovers.
