### ISSUE TITLE
UI Breaking on pasting content while creating note on ticket

### ISSUE THREAD

**Issue by hardy1334** [WikiEducationFoundation/WikiEduDashboard#3889]
When we paste data from external source, like if you are trying to paste some html type content, if that content is too wide, it comes out of the block assigned for that purpose. It requires fix at the css end.
![Screen Shot 2020-03-24 at 2 56 43 AM](https://user-images.githubusercontent.com/31733278/77365134-99629080-6d7b-11ea-8595-b7f542f14b1e.png)

**Comment by prashulkale** [comment]
if you assign me the task I will fix it  for u by  adding a line in CSS - overflow:  hidden

**Comment by ragesoss** [comment]
I don't think simply hiding the overflow is a good solution to this; we need to be able to see all the content.
