### ISSUE TITLE
`e.list is undefined` javascript error when visiting nonexistent dashboard url

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#389]
It looks like this one is related to hitting a 404: http://sentry.ragesoss.com:8080/wiki-ed/production/group/582/

**Comment by thenickcox** [comment]
Should've been fixed by a573c0d.

**Comment by ragesoss** [comment]
It looks like I can't replicate the error anymore, so I think that did it.
