### ISSUE TITLE
Links to "Edit" a survey Question Group do different things in different places

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3905]
If you're editing surveys and want to change a Question Group, there are two places you can do that from: the Question Groups list, which has an 'Edit' button for each group, and the Survey 'edit' view, which includes an 'Edit' link for each group included in that survey.

Clicking 'Edit' from the Question Groups index view opens an edit view includes both the questions that are part of the group and also the settings for the group itself (name, tags, etc).

![edit question group good](https://user-images.githubusercontent.com/848483/77572788-d4081e00-6e8c-11ea-8905-efb672f30916.png)

The 'Edit' link from the Survey only has the questions, and is less useful. It should behave the same way as the other 'Edit' link.

![question group edit bad](https://user-images.githubusercontent.com/848483/77572886-fef27200-6e8c-11ea-9653-7520a8702975.png)

Also, the 'preview question group' link only appears in the view that lacks the other details.

**Comment by shashwatkathuria** [comment]
@ragesoss I am working on this issue.

**Comment by ragesoss** [comment]
Thanks @swathi-0901
