### ISSUE TITLE
Meetings component uses course_creator text in 'Edit Course Dates' modal

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#391]
The Meetings component is reused between the form panel of the course creator and the Edit Course Dates modal on the timeline. The copy indicates that the purpose is to allow the wizard to space out your assignments appropriately, which only applies before you've gone through the wizard to create your assignment.

The copy should be different in the Edit Course Dates modal. I guess the right solution is to pass in the text as props for the Meetings component, @thenickcox? That way, we can set different text for each context? If that sounds right, I'll tackle that.

**Comment by thenickcox** [comment]
@ragesoss That'd be the approach I'd take.

**Comment by ragesoss** [comment]
Fixed with 7b439189e305d933927297f78526f0448fd64ce0
