### ISSUE TITLE
Update MacOS setup script

### ISSUE THREAD

**Issue by swathi-0901** [WikiEducationFoundation/WikiEduDashboard#3914]
### What is happening?
There is a problem in the MacOSX setup script in line 105

### To Reproduce
just run the setup.py file in mac osx.
Setup is aborting just because of this line.

### Expected behavior
Setup should not be aborted and it should continue.

### Screenshots
![Screen Shot 2020-03-27 at 2 46 10 AM](https://user-images.githubusercontent.com/43814493/77718921-19058f00-700a-11ea-8871-61f3389b64ea.png)

### System Information

 - OS: Mac OSX

**Comment by ragesoss** [comment]
@swathi-0901 did the rest of the setup go smoothly once you fixed that bit of the script?

**Comment by swathi-0901** [comment]
Yes, Rest of the script worked fine for me :)

**Comment by swathi-0901** [comment]
> @swathi-0901 did the rest of the setup go smoothly once you fixed that bit of the script?



> @swathi-0901 did the rest of the setup go smoothly once you fixed that bit of the script?

Yes, Rest of the script worked fine for me :)
