### ISSUE TITLE
Articles that start as sandboxes aren't counted as 'new' if the first edit is a template added by another editor

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3941]
For example, this article was originally a sandbox, and the template was added by _User:Elysia (Wiki Ed)_ https://en.wikipedia.org/wiki/Dental_aerosol

It does not appear as 'new': https://dashboard.wikiedu.org/courses/University_of_Cincinnati/Occupational_Epidemiology_2020_(Spring_2020)/articles/edited

Elysia's edit was subsequently deleted, but this does not trigger recategorizing the article as new.

Ideally, the check for whether to call an article `new` would be based on the first non-automated edit being by a student, rather than just the first edit.

**Comment by shashwatkathuria** [comment]
@ragesoss I am working on this issue
