### ISSUE TITLE
DiscretionarySanctionsMonitor should create alerts based on Assignments (in addition to edited articles)

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3943]
DiscretionarySanctionsMonitor checks for articles that have been edited by students (represented by ArticlesCourses records) that are under 'discretionary sanctions' on Wikipedia, meaning they are controversial topics and come under extra scrutiny. It creates alerts to notify Wiki Experts when such an article is edited.

In addition to alerting us when such an article is edited, it would be a nice improvement to also alert us when such an article is chosen as an assignment by a student. The alert messages should differentiate between edited articles and (merely) assigned articles.

**Comment by shashwatkathuria** [comment]
@ragesoss I am workng on this issue.
