### ISSUE TITLE
Course Clone Modal should have a cancel button that deletes the clone

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#395]
The clone workflow should act as much like the create new course workflow as possible, which means that it should essentially act you haven't really created the course until you click 'Save'.

So:
a) Let the user cancel, and delete the course that they created.
b) If the user leaves without clicking cancel but without saving, we should also destroy the course.

**Comment by ragesoss** [comment]
I think just having a way to delete a cloned course is a good start for this. I'm not 100% convinced that the automatic deletion is a good idea.

**Comment by bwreid** [comment]
@ragesoss To be clear, you're thinking of just option A? So something like the following:
![image](https://user-images.githubusercontent.com/1316902/53917350-2b84e300-4019-11e9-902d-e4ca5261fe6f.png)

**Comment by ragesoss** [comment]
Yes, exactly.
