### ISSUE TITLE
Build passes but deployment fails if Capistrano version is updated without changing deploy.rb

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3955]
Our Capistrano version is locked using a config line at the beginning of `deploy.rb`, which makes Capistrano stop deploying if a different version is being used. However, the automated pull requests to bump the version of Capistrano don't change the `deploy.rb`, so we often end up merging one of these changes without updating `deploy.rb`, and then the builds fail until we notice (which might not be immediately, because the builds still pass even though the after-build deployments from travis-ci fail).

**Comment by shashwatkathuria** [comment]
I am working on this issue. The solution I have thought of is basically run a system command, extract the version and then put it inside lock.

**Comment by shashwatkathuria** [comment]
I am working on this issue. The solution I have thought of is basically <code>Gemname::VERSION::STRING</code>.
