### ISSUE TITLE
HighQualityArticleMonitor should create alerts based on Assignments (in addition to edited articles)

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3971]
This is basically the same concept as https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/3943, but for "HighQualityArticleMonitor" instead, so that Wiki Education staff will get alerts whenever a student in a current course has been assigned to a Good Article or Featured Article.

**Comment by shashwatkathuria** [comment]
I am working on this.
