### ISSUE TITLE
article lookup for assign button appears to be pointless

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#399]
We have a potentially rather expensive lookup for LookupController.article that returns the titles of every single live mainspace article: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/controllers/lookups_controller.rb#L25

This gets called, via the Lookup component, from the AssignButton component. But as far as I can tell, it doesn't actual need that lookup data for anything. I tested out modifying the controller method to just set @key, @model, and @values to nil, and it doesn't seem to affect the functionality of the AssignButton: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/components/students/assign_button.cjsx

Assignments still work. The assignments only take in article_title, user_id, course_id, and role anyway, so I'm unclear about what this lookup is supposed to be doing.

Can you shed any light on this, @ntdb?

**Comment by ntdb** [comment]
This was originally meant to help instructors choose articles for assignments but we decided not to actually turn it on. I can see it being useful for assigning reviewers: it could auto-complete with article titles from existing assignments in that course.

**Comment by ragesoss** [comment]
Thanks @ntdb, that's helpful. I imagine we could just autocomplete that from an assignment store, though, without a separate lookup. (The lookup route doesn't have a course-specific param, so if I understand correctly, in it's current for it's only good for getting system-wide lookups like available tags and available cohorts.)

As a start, I've just committed the stubbing out of the 'articles' method. Next step would be to remove the lookup altogether.
