### ISSUE TITLE
Layout is broken on Windows

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4]
I received this screenshot from a Windows user. He says both Firefox and Chrome display this excess whitespace on his Windows desktop (while Safari and Chrome on Mac are fine).

![screenshot_2015-02-04_12 05 06](https://cloud.githubusercontent.com/assets/848483/6088634/68f70076-ae0d-11e4-8db6-11cc479564f3.png)

**Comment by ragesoss** [comment]
I've confirmed that, on Windows 7 at least, this layout breakage happens for me as well, on Internet Explorer, Firefox and Chrome.

The app is essentially unusable on Windows right now.

**Comment by mattfordham** [comment]
Something is up with the Icon Font on Windows. @ntdb is investigating

**Comment by ntdb** [comment]
There seems to be a problem with out icon font. I've just regenerated and committed in 257d95c03c6c7053a665e12c80d66060b06af496. My dev environment is in bad shape, is it safe to do a staging push to give this fix a try?

**Comment by ragesoss** [comment]
@ntdb I pushed to staging soon after your made the commit, but it didn't fix it.

**Comment by ragesoss** [comment]
@ntdb feel free to push to staging at any time, though.

**Comment by ntdb** [comment]
Switched to using FontAwesome (via their CDN) and the issue is resolved. Their icons aren't identical to ours but they're very close.

**Comment by ragesoss** [comment]
@ntdb Awesome! Confirmed, that fixed it. I'll push to production.
