### ISSUE TITLE
articles assigned to other students in the class don't show up as 'other edited articles'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4022]
### Current Behavior:
The details view on the Students tab shows all the assigned articles for the selected student, as well as the articles they have signed up to peer review, and a list of other unassigned articles they've made edits to.

However, if a student has edited an article that is not assigned to them but is assigned to a classmate, it won't show up at all on this view.

For example, this student has edited "Eugenics in the United States", which is assigned to a classmate:
![assigned](https://user-images.githubusercontent.com/848483/81452147-f30bf800-913a-11ea-82f2-e1fad8b2fbfb.png)

### Desired Behavior:
The Students details view should show every mainspace article that student has edited, either in the assigned articles list or in the 'other articles edited' list. An article being assigned to a classmate shouldn't affect this.

**Comment by BaileyMcKelway** [comment]
Looking into this!

**Comment by rahahahat** [comment]
I would like to work on this bug.

**Comment by Bam92** [comment]
Hi @rahahahat!

Are you already working on this issue? If not, let me know.

**Comment by rahahahat** [comment]
@Bam92 working on it.

**Comment by rahahahat** [comment]
@Bam92 progress has been a bit slower bit definitely working on it

**Comment by rahahahat** [comment]
@ragesoss should the fix take into consideration all available articles as well all those articles that have been assigned to students, or only those that have been assigned to other classmates but have been edited by some who aren't assigned to them.

**Comment by ragesoss** [comment]
Basically, every article edited by a student that shows up in the Articles tab should also be shown in the Students view when looking at that student. So if it's not one of that student's assigned articles, it should show up in the 'other articles edited' section. That includes both classmates' assignments and available articles.

**Comment by rahahahat** [comment]
> Basically, every article edited by a student that shows up in the Articles tab should also be shown in the Students view when looking at that student. So if it's not one of that student's assigned articles, it should show up in the 'other articles edited' section. That includes both classmates' assignments and available articles.

thanks for the input, i'll get to work

**Comment by rahahahat** [comment]
@ragesoss Apologies for the late update, i've been working on the bug wanted to know whether an assigned article should come up under other edited articles as well?

**Comment by ragesoss** [comment]
No, it should not if it's assigned to that user. If it's only assigned to
someone else, it should show up.

**Comment by rahahahat** [comment]
@ragesoss I have opened a pull request. Please, review it.

**Comment by rahahahat** [comment]
@ragesoss any reviews on the pull request?

**Comment by ragesoss** [comment]
It's on my todo list; I hope to have a look either tomorrow or early next week.

**Comment by rahahahat** [comment]
@ragesoss thanks alot, in the meanwhile can I please take up another issue?

**Comment by ragesoss** [comment]
Yeah, go for it!
