### ISSUE TITLE
In ArticleViewer, I should be able to scroll to the next section of highlighted text

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4024]
### Current Behavior:
On long articles, ArticleViewer may take quite a bit of scrolling before you find the highlighted part contributed by a student. For example: 
https://dashboard.wikiedu.org/courses/Georgetown_University/Culture_Medicine_and_Gender_(Spring_2020)/students/articles/Ddanaie2021?showArticle=51302794

There's no way to scroll straight to the position of the highlighting, so it can take a bit of trial and error.

### Desired Behavior:
It would be useful to be able to easily jump straight to the first part of the article that is being hightlighted, and to easily navigate from one such highlighted section to the next.

**Comment by aryamanpuri** [comment]
Hi @ragesoss 
Can I take up this issue and would be helpful for me if you can explain the work to be done in this issue.

**Comment by ragesoss** [comment]
Hi! I haven't thought through exactly how it might be implemented, but the place to start exploring is the `ArticleViewer` component. If you'd like to try it, I suggest first setting up a development environment where you can recreate the situation locally, and then start playing around with it.

If you have any specific questions about how ArticleViewer works, I can try to explain it.

**Comment by BaileyMcKelway** [comment]
Going to look into this.

**Comment by BaileyMcKelway** [comment]
> It would be useful to be able to easily jump straight to the first part of the article that is being highlighted and to easily navigate from one such highlighted section to the next.

For the navigation do you have any suggestions? Maybe if the user clicks an editor's name in the "Edits By:" the article viewer will jump to the highlighted text?

**Comment by ragesoss** [comment]
I think the UI of `find in page` features in browsers may be good place to draw from. Like, ideally from a UI perspective, you'd have `forward` and `backward` arrows along with the count of different highlighted sections. Unfortunately that may be tough to implement, since there are separate nodes for contiguous contributions (which only look like a single section of highlighting because the spaces in between words are also highlighted).

![find in page](https://user-images.githubusercontent.com/848483/93139454-a2cb1680-f695-11ea-8c7b-6a7d82c6d51b.png)

Maybe a good option that draws from the concept of `find in page` UIs would be to just have a `forward` arrow next to each highlighted name, and clicking it will take you to the next text down the page attributed to that user. That way if you have a paragraph by one editor, then later down the page, one by a different editor, then another by the first editor, you could navigate to each section by clicking one button, then the other, then first again.

**Comment by BaileyMcKelway** [comment]
Wow neat! Ok cool. I'm gonna dig around and see if I can find any good examples and edge cases.

**Comment by BaileyMcKelway** [comment]
![Screen Shot 2020-09-18 at 7 45 18 PM](https://user-images.githubusercontent.com/25776618/93653585-84438300-f9e7-11ea-80fc-b987f6f7955e.png)

What about something like this?

- The user clicks the bottom right button
- This opens the "Find in page" tool
- There is a drop-down list of users in the tool
- Up and down arrows will scroll to the section the users' edits is in (sections will be determined by h3 titles in the article)

**Comment by ragesoss** [comment]
I think this may not be discoverable enough; I think the place it makes the most sense to connect this feature to is the highlighted name. I was thinking something more like:

Edits by: _User1_ ▼, _User2_ ▼, User3

**Comment by BaileyMcKelway** [comment]
It seems I will have to use an external library [https://www.npmjs.com/package/react-scroll](react-scroll) Is it ok to use external libraries?

I tried to create the scroll event without an external library by assigning refs to the highlighted text but it doesn't seem possible.

**Comment by ragesoss** [comment]
Yes, that seems reasonable, and the react-scroll library looks reasonably well-supported.

**Comment by BaileyMcKelway** [comment]
I have the basic functionality working. I have a couple of questions about the finer details about the scrolling event.

- Referencing the picture above if the user scrolls to 'Section 2 User 1' and then clicks the scroll button for User 2 should the page scroll back up to Section 1 or continue to 'Section 2 User 2'?

- If the user clicks the scroll button until they are on the last edit should clicking the scroll button again take them back up to the first edit, or should it stay in place?

**Comment by ragesoss** [comment]
Good questions...

I think what makes the most sense is to preserve the mental model of being a specific place on the page, which is what the `find on page` features do. So in rthe first scenario, it should continue to Section 2 User 2.

Scrolling back to the top once you've reached the last instance is also how `find on page` behaves, so I think that will be intuitive here.

**Comment by yunjuc** [comment]
Hello @ragesoss and @BaileyMcKelway 👋 

Didn't mean to backtrack on the implementation, but is it possible when the authorship data is loaded, the page jumps to the first highlighted section? Once users discover the use of the highlighted texts, it should be easy for them to use the scrollbar to find others. Just my two cents.

**Comment by BaileyMcKelway** [comment]
Heyo @yunjuc ! Just finished up a prototype of the scrolling feature. 

Here is the PR.
#4224

Everyone give it a test and let me know what you think

**Comment by yunjuc** [comment]
I tested it and it worked. Two things I noticed:

- The edits in the reference section are not included in the scroll. 
- The scroll only works the first time the viewer is launched. After the second time, you need to refresh the page to make it works again.

**Comment by BaileyMcKelway** [comment]
Solid! Thank you. Both those things can be fixed.

Do you mind sharing the article and class you were using for testing?

**Comment by yunjuc** [comment]
I tested with the same article - https://dashboard.wikiedu.org/courses/Georgetown_University/Culture_Medicine_and_Gender_(Spring_2020)/students/articles/Ddanaie2021?showArticle=51302794

I created a demo course, added the three students from that article to the demo course, manually pulled the data, and the article can be viewed under My dashboard > demo course > articles.

**Comment by BaileyMcKelway** [comment]
> * The edits in the reference section are not included in the scroll.
I have a solution for this. However, it might be unnecessary. Do we want to include references in the scroll? How important are they? 

![Screen Shot 2020-10-06 at 9 35 39 PM](https://user-images.githubusercontent.com/25776618/95277595-2b178400-081c-11eb-8486-4743d4eb2c48.png)



> * The scroll only works the first time the viewer is launched. After the second time, you need to refresh the page to make it works again.

This one is fixed!

**Comment by ragesoss** [comment]
The references are fairly important. Sometimes, they are the only thing an editor added.

**Comment by BaileyMcKelway** [comment]
Both issues are fixed now!

![Screen Shot 2020-10-07 at 11 41 23 PM](https://user-images.githubusercontent.com/25776618/95412282-a3eb0e80-08f6-11eb-8869-9d5ed6b4fc06.png)

I'm going to look into adding an on hover for the button to better improve the UX. It helps show the user name and arrow have separate functionality.

**Comment by BaileyMcKelway** [comment]
Just pushed to PR. Test are passing

**Comment by yunjuc** [comment]
The fixes work great :) I especially like the mouse-over touch, I did click on the wrong target many times earlier.

**Comment by BaileyMcKelway** [comment]
Just pushed the final commit for the Scrolling feature. However, my branch is missing part of my previous commit where I added a hover message to a user's name if there wasn't highlighting. Specifically the I18n.t message and some CSS.

For the I18n.t() messages, what is the process for creating one in every language?
