### ISSUE TITLE
Leaving the number of days blank on a survey assignment notification schedule causes the results page to crash

### ISSUE THREAD

**Issue by jproft** [WikiEducationFoundation/WikiEduDashboard#4036]
### What is happening?
When the `#survey_assignment_send_date_days` input field on the survey assignment editor page is left blank (or a value is given and then subsequently deleted), attempting to visit the survey results page causes an internal server error.

### To Reproduce
1. Create a survey assignment.
2. Leave the number of days blank.
3. Save the assignment.
4. Navigate to `/surveys/results`.
5. The page should display "500 — internal server error."

### Expected behavior
The survey results should be shown.

### Error trace
```
[2020-05-14 12:40:46.737 FATAL] ActionView::Template::Error (undefined method `days' for nil:NilClass):
    4:     %strong.name= survey.name
    5:   .survey__admin-row__col
    6:     .contextual Status
    7:     %div= survey.status
    8:   .survey__admin-row__col
    9:     .contextual Groups | Questions
   10:     %strong= survey_question_stats(survey)
  
app/models/course.rb:177:in `will_be_ready_for_survey'
app/models/surveys/survey_assignment.rb:110:in `block in courses_with_pending_notifications'
app/models/surveys/survey_assignment.rb:110:in `collect'
app/models/surveys/survey_assignment.rb:110:in `courses_with_pending_notifications'
app/models/surveys/survey_assignment.rb:102:in `active?'  
app/models/surveys/survey.rb:42:in `map'
app/models/surveys/survey.rb:42:in `status' 
app/views/surveys/_survey_results_index_item.html.haml:7
app/views/surveys/results_index.html.haml:4 
```

### System Information
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 76.0.01

### Additional context
There are actually two problematic methods: `will_be_ready_for_survey` and `ready_for_survey`. Neither of these methods check if `days_offset` is nil.

**Comment by chepyego** [comment]
hey, can I work on this?

**Comment by ragesoss** [comment]
Yes, go for it.

**Comment by buildwithallan** [comment]
@rageross Hey, has this been worked on already? I followed the steps to reproduce the expected error trace but the survey results is shown.

**Comment by ragesoss** [comment]
Looks like I fixed this with https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/4bc40dc1f24a9177e4d6ea2047ed7b793c44acf4
