### ISSUE TITLE
ArticleViewer authorship highlighting does not work for user with `+` in username

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4048]
### What is happening?
In ArticleViewer, a user named `Latinx+art38` does not have their edits highlighted, even though the whocolor data includes text attributed to that user.

This is probably related to the Dashboard showing that username as `Latinx art38`, because at some point it gets interpreted as a URL and the plus sign gets turned into a space.

The student's username is show correctly elsewhere in the Dashboard (such as on the Students page), but not at the bottom of ArticleViewer.

### To Reproduce

View this article with authorship highlighting:

https://dashboard.wikiedu.org/courses/Fort_Lewis_College/ENG_177_(Spring_2020)/articles/edited?showArticle=52231339

### Expected behavior

Some text, such as the text added [here](https://en.wikipedia.org/w/index.php?title=Josefina_Niggli&diff=945214708&oldid=929279441&diffmode=source), should be highlighted.

**Comment by devil-cyber** [comment]
can I work on this? I am new to open source

**Comment by ragesoss** [comment]
@devil-cyber go for it. This is a good first issue. :-)

If you'd like to join our slack, send me an email.

If you have any questions about how to get set up or how to replicate the issue locally, you can ask here or on slack.

**Comment by devil-cyber** [comment]
I have sent you the mail please check out @ragesoss

**Comment by ragesoss** [comment]
@devil-cyber that email didn't come through. Can you try to sage@wikiedu.org?

**Comment by devil-cyber** [comment]
how to replicate the issue locally?will you please provide me some insight
of this issue?

**Comment by ragesoss** [comment]
Once you have your dev environment set up, you can replicate this by creating a course that matches the start and end dates of the one linked in the description, then add `Latinx+art38` as a student. Then you can do a data update on your course (see [here](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/user_roles.md#populating-a-course-with-data)), and then you should be able to find that same article in your course.

**Comment by devil-cyber** [comment]
ok I am going to work on this

**Comment by BaileyMcKelway** [comment]
Got my dev environment setup and was going to take a look into this if it is still open. 👍

**Comment by BaileyMcKelway** [comment]
#4133

**Comment by BaileyMcKelway** [comment]
#4133

**Comment by BaileyMcKelway** [comment]
Squashed my commits and fixed the prettier issue on this pull request.
#4133
