### ISSUE TITLE
Timeline/course page edits will fail repeatedly if client has out-of-date course data

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#414]
Failed edits are also not surface to the user in this context, so things appear to be working normally to the user.

**Comment by mattfordham** [comment]
An example to reproduce : open same course in two windows, make edits to both. The second "saver" will cause an error.

**Comment by mattfordham** [comment]
@ragesoss I tried to reproduce this with no luck in reproducing the error. Here's what I did:

- opened the same course overview in two windows.
- changed the course description in both. 
- saved both
- results in no errors. The last "save" wins. 

Am I attempting to reproduce correctly?

**Comment by ragesoss** [comment]
I can no longer replicate this either, but it was definitely happening at the time I reported it.

**Comment by ragesoss** [comment]
I may have changed the behavior when I started meddling with the timeline controller: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/8ccd0e5ac9a22855a553bd54102fcd2b246a2c9a

**Comment by mattfordham** [comment]
I'll keep poking at it. Were there any actions other than simply changing the content of fields on the overview that would trigger it?

**Comment by ragesoss** [comment]
The way I had encountered and replicated it was editing timeline blocks (eg, the same timeline block) in two different windows.

**Comment by mattfordham** [comment]
I'll try that. Thanks!

**Comment by ragesoss** [comment]
I tried it, though, and can't replicate the problem any longer. I really was happening 17 days ago, but not now.

**Comment by ragesoss** [comment]
Even checking out the version from like 18 days ago, I still can't replicate it now. Sigh.
