### ISSUE TITLE
Assigned articles that do not exist should have a different rating icon than 'unrated'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#416]

**Comment by peiyush13** [comment]
hey @ragesoss ! I am interested to solve this issue but I am new, so can u guide me through this.
I think it can be solved by comparing a instance variable and updating the view respectively .

**Comment by ragesoss** [comment]
Hi @peiyush13!

The basic idea is to add a fallback of 'unrated' to the method that searches the wikitext of a talk page to try to find the article's class : https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/helpers/article_helper.rb#L70

Currently, if not matches are found by that method, it returns `nil`, which is also the default value before the article has been checked.

After that, we need a new icon to use for unrated articles.

If you haven't yet, you should start by setting up a development environment: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md

Please let me know if you run into any problems!
