### ISSUE TITLE
Course cloning does not save term

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#419]
When you create a cloned course, there are some weird things going on.

In the browser console, it says both "Saved course!" and "Couldn't save course!". There are two PUTs in a row to the cloned course, like `/courses/school/title_(CLONED_FROM_term).json`, and the second one hits a 404.

After that you get redirected to the new slug, and everything appears to be correct... except that the `term` field is blank (even though the updated term appears in the slug). Then, if you subsequently update the course, the slug will be updated based on the empty term.

**Comment by thenickcox** [comment]
@ragesoss Fixed. Could you please verify? If you're happy with it, I can deploy.

**Comment by ragesoss** [comment]
@thenickcox awesome, that did it. Please deploy.

**Comment by thenickcox** [comment]
@ragesoss You got it, boss.
