### ISSUE TITLE
Rubocop style violations: multi-line lambdas and multi-line {...} blocks

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#420]
After chipping away at rubocop violations for a while now, we're down to just 5 offenses for two issues:

```
app/models/course.rb:55:24: C: Use the lambda method for multi-line lambdas.
  has_many :revisions, -> (course) {
                       ^^
app/models/course.rb:55:36: C: Avoid using {...} for multi-line blocks.
  has_many :revisions, -> (course) {
                                   ^
app/models/course.rb:58:22: C: Use the lambda method for multi-line lambdas.
  has_many :uploads, -> (course) {
                     ^^
app/models/course.rb:58:34: C: Avoid using {...} for multi-line blocks.
  has_many :uploads, -> (course) {
                                 ^
app/models/course.rb:81:30: C: Use the lambda method for multi-line lambdas.
  scope :unsubmitted_listed, -> {
                             ^^
```
I suggest that we resolves these last ones by either changing the syntax, or disabling those cops.

My slight preference would be to switch to to/end for all the multiline {...} blocks. I don't really have an opinion either way for lambdas, except that I'm generally in favor of following the rubocop defaults as much as possible, for the sake of following prevailing style conventions.

I already had added the `lambda` method in place of `->` in a few places — and now on reflection, I'm not completely confident in those changes, since in some cases the same syntax change broke tests — but I couldn't figure out the proper syntax for lines 55 and 58 of course.rb, because of the `, through: :foo` bits at the end.

@thenickcox What are your thoughts?

**Comment by ragesoss** [comment]
Here's some good discussion on the issue: https://github.com/bbatsov/ruby-style-guide/issues/270

Perhaps one thing to think about — this seems pretty appealing to me — would be to convert the more complex scopes into regular class methods. But that still leaves the `has_many` issues.

**Comment by ragesoss** [comment]
From that discussion, I at least figured out some valid syntax. Following the rubocop rule could mean something like this:

```ruby
  has_many :revisions, (lambda do |course|
    where('date >= ?', course.start).where('date <= ?', course.end)
  end), through: :students
```

**Comment by thenickcox** [comment]
Yikes. In that case, I'd vote for disabling.

**Comment by ragesoss** [comment]
I kept staring at it, and liked the lambda format more and more for the sake if readability. I also realized that those two cops, for multiline lambdas and for multiline blocks, apply more broadly than just these edge cases, so we'd lose the checks for other multiline `{...}` blocks if we disabled these cops (and there's not a good way to disable one without the other).
