### ISSUE TITLE
Wikipedia URLs for nonexistent articles are not handled properly

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4213]
### What is happening?

The article assignment flow allows users to enter either an article title or a full article URL, and if it's a URL it will automatically be parsed to extract the title (and the wiki language/project). However, if a user pastes the URL they get from following a redlink on Wikipedia (for an article that hasn't been created yet), the Dashbaord doesn't detected and parse it as an article title, so it ends up creating an assignment where the article title is the entire URL.

For example, https://en.wikipedia.org/w/index.php?title=Redlink&action=edit&redlink=1

### To Reproduce

One way:

1. In the student or instructor role, click 'Assign myself an article'
2. Paste in a URL like https://en.wikipedia.org/w/index.php?title=Redlink&action=edit&redlink=1

### Expected behavior
The Dashboard should correctly parse a URL that uses the `/w/index.php?title=ArticleTitle` format rather than the `/wiki/ArticleTitle` format, and assign the intended article title.

### Additional context

This can probably be solved by changing the `articleFromTitleInput` function in `course_utils.js`, along with adding appropriate test examples in `course_utils.spec.js`

**Comment by rahahahat** [comment]
Hello, I would like to work on this issue.

**Comment by rahahahat** [comment]
Is there a specific time period i'd have to resolve the issue in?

**Comment by ragesoss** [comment]
Nope, just please leave a note here if you're no longer working on it.

**Comment by rahahahat** [comment]
Hi, 
I am getting this big fat error while trying to setup the development environment, ive been searching on the internet for hours to solve this problem.Please, could share some insights.
`Fetching mysql2 0.5.3
Installing mysql2 0.5.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/rahat/.gem/gems/mysql2-0.5.3/ext/mysql2
/snap/ruby/181/bin/ruby -I /snap/ruby/181/lib/ruby/2.7.0 -r
./siteconf20200925-22249-m3k54t.rb extconf.rb
checking for rb_absint_size()... no
checking for rb_absint_singlebit_p()... no
checking for rb_wait_for_single_fd()... no
-----
Using mysql_config at /usr/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for SSL_MODE_DISABLED in mysql.h... yes
checking for SSL_MODE_PREFERRED in mysql.h... yes
checking for SSL_MODE_REQUIRED in mysql.h... yes
checking for SSL_MODE_VERIFY_CA in mysql.h... yes
checking for SSL_MODE_VERIFY_IDENTITY in mysql.h... yes
checking for MYSQL.net.vio in mysql.h... yes
checking for MYSQL.net.pvio in mysql.h... no
checking for MYSQL_ENABLE_CLEARTEXT_PLUGIN in mysql.h... yes
checking for SERVER_QUERY_NO_GOOD_INDEX_USED in mysql.h... yes
checking for SERVER_QUERY_NO_INDEX_USED in mysql.h... yes
checking for SERVER_QUERY_WAS_SLOW in mysql.h... yes
checking for MYSQL_OPTION_MULTI_STATEMENTS_ON in mysql.h... yes
checking for MYSQL_OPTION_MULTI_STATEMENTS_OFF in mysql.h... yes
checking for my_bool in mysql.h... no
-----
Setting libpath to /usr/lib/x86_64-linux-gnu
-----
creating Makefile

current directory: /home/rahat/.gem/gems/mysql2-0.5.3/ext/mysql2
make "DESTDIR=" clean

current directory: /home/rahat/.gem/gems/mysql2-0.5.3/ext/mysql2
make "DESTDIR="
compiling client.c
In file included from client.c:13:
wait_for_single_fd.h: In function ‘my_wait_for_single_fd’:
wait_for_single_fd.h:32:10: warning: implicit declaration of function
‘rb_thread_select’; did you mean ‘rb_thread_fd_select’?
[-Wimplicit-function-declaration]
   32 |   return rb_thread_select(fd + 1, rfds, wfds, efds, tvp);
      |          ^~~~~~~~~~~~~~~~
      |          rb_thread_fd_select
client.c: In function ‘rb_mysql_query’:
client.c:787:14: warning: passing argument 1 of ‘rb_rescue2’ from incompatible
pointer type [-Wincompatible-pointer-types]
787 |   rb_rescue2(do_send_query, (VALUE)&args, disconnect_and_raise, self,
rb_eException, (VALUE)0);
      |              ^~~~~~~~~~~~~
      |              |
      |              VALUE (*)(void *) {aka long unsigned int (*)(void *)}
In file included from /snap/ruby/181/include/ruby-2.7.0/ruby.h:33,
                 from ./mysql2_ext.h:10,
                 from client.c:1:
/snap/ruby/181/include/ruby-2.7.0/ruby/ruby.h:1988:18: note: expected ‘VALUE
(*)(VALUE)’ {aka ‘long unsigned int (*)(long unsigned int)’} but argument is of
type ‘VALUE (*)(void *)’ {aka ‘long unsigned int (*)(void *)’}
 1988 | VALUE rb_rescue2(VALUE(*)(VALUE),VALUE,VALUE(*)(VALUE,VALUE),VALUE,...);
      |                  ^~~~~~~~~~~~~~~
client.c:795:16: warning: passing argument 1 of ‘rb_rescue2’ from incompatible
pointer type [-Wincompatible-pointer-types]
795 |     rb_rescue2(do_query, (VALUE)&async_args, disconnect_and_raise, self,
rb_eException, (VALUE)0);
      |                ^~~~~~~~
      |                |
      |                VALUE (*)(void *) {aka long unsigned int (*)(void *)}
In file included from /snap/ruby/181/include/ruby-2.7.0/ruby.h:33,
                 from ./mysql2_ext.h:10,
                 from client.c:1:
/snap/ruby/181/include/ruby-2.7.0/ruby/ruby.h:1988:18: note: expected ‘VALUE
(*)(VALUE)’ {aka ‘long unsigned int (*)(long unsigned int)’} but argument is of
type ‘VALUE (*)(void *)’ {aka ‘long unsigned int (*)(void *)’}
 1988 | VALUE rb_rescue2(VALUE(*)(VALUE),VALUE,VALUE(*)(VALUE,VALUE),VALUE,...);
      |                  ^~~~~~~~~~~~~~~
client.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-used-but-marked-unused’
cc1: warning: unrecognized command line option ‘-Wno-static-in-inline’
cc1: warning: unrecognized command line option ‘-Wno-reserved-id-macro’
cc1: warning: unrecognized command line option
‘-Wno-missing-variable-declarations’
cc1: warning: unrecognized command line option
‘-Wno-documentation-unknown-command’
cc1: warning: unrecognized command line option ‘-Wno-disabled-macro-expansion’
cc1: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1: warning: unrecognized command line option ‘-Wno-conditional-uninitialized’
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
compiling infile.c
compiling mysql2_ext.c
compiling result.c
compiling statement.c
statement.c: In function ‘my_big2ll’:
statement.c:209:9: warning: implicit declaration of function ‘RBIGNUM_LEN’; did
you mean ‘RBIGNUM_SIGN’? [-Wimplicit-function-declaration]
  209 |   len = RBIGNUM_LEN(bignum) * SIZEOF_BDIGITS;
      |         ^~~~~~~~~~~
      |         RBIGNUM_SIGN
statement.c:209:31: error: ‘SIZEOF_BDIGITS’ undeclared (first use in this
function); did you mean ‘SIZEOF_INT’?
  209 |   len = RBIGNUM_LEN(bignum) * SIZEOF_BDIGITS;
      |                               ^~~~~~~~~~~~~~
      |                               SIZEOF_INT
statement.c:209:31: note: each undeclared identifier is reported only once for
each function it appears in
statement.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-used-but-marked-unused’
cc1: warning: unrecognized command line option ‘-Wno-static-in-inline’
cc1: warning: unrecognized command line option ‘-Wno-reserved-id-macro’
cc1: warning: unrecognized command line option
‘-Wno-missing-variable-declarations’
cc1: warning: unrecognized command line option
‘-Wno-documentation-unknown-command’
cc1: warning: unrecognized command line option ‘-Wno-disabled-macro-expansion’
cc1: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1: warning: unrecognized command line option ‘-Wno-conditional-uninitialized’
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
make: *** [Makefile:245: statement.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/rahat/.gem/gems/mysql2-0.5.3 for
inspection.
Results logged to
/home/rahat/.gem/extensions/x86_64-linux/2.7.0/mysql2-0.5.3/gem_make.out

An error occurred while installing mysql2 (0.5.3), and Bundler cannot
continue.
Make sure that `gem install mysql2 -v '0.5.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  ticket_dispenser was resolved to 0.1.0, which depends on
    mysql2
`

**Comment by ragesoss** [comment]
It looks like you don't have the prerequisites to build the `mysql` gem on your system. In particular, you probably need to install `libmysqlclient-dev`.

**Comment by rahahahat** [comment]
> It looks like you don't have the prerequisites to build the `mysql` gem on your system. In particular, you probably need to install `libmysqlclient-dev`.

thanks a lot for the help, the problem was with my installation of ruby. Ive started working on the issue.

**Comment by rahahahat** [comment]
Hello,
I've been working on the issue and as of now, the function `acticleFromTitleInput` correctly parses and passes all the tests for URL's of the format:
- `https://en.wikipedia.org/w/index.php?title=Redlink&action=edit&redlink=1`
- `https://en.m.wikipedia.org/w/index.php?title=Redlink&action=edit&redlink=1`
- `https://incubator.wikimedia.org/w/index.php?title=Redlink&action=edit&redlink=1`
- `https://en.wikipedia.org/w/index.php?title=Jalape%C3%B1o&action=edit&redlink=1`

I looked around the internet and found another redlink of the below format, the function also parses that correctly. All tests for this format also pass.
 - `https://en.wikipedia.org/w/index.php?title=Mesut%20%C3%96zil:REDLINK&redirect=no`

However, I was wondering if you could give me some more redlink examples to optimize the regex, so that it is able to handle all cases. Also, should I included functionality for `wikisource` URL's.

**Comment by ragesoss** [comment]
If it is matching all those examples properly, and handling `title` when passed as a parameter and properly excluding all the rest of the parameters, then it should be good to go.

Here are a few variations:
* The edit link for an older revision: https://en.wikipedia.org/w/index.php?title=72nd_Primetime_Emmy_Awards&oldid=980777920&action=edit
* Section edit link: https://en.wikipedia.org/w/index.php?title=Sweetwater_Formation&action=edit&section=2
* Old version of the page: https://en.wikipedia.org/w/index.php?title=Smedsb%C3%B6le_Radio_Mast&oldid=479392613
* Old version edit link using VisualEditor: https://en.wikipedia.org/w/index.php?title=Christian_Social_Party_of_Obwalden&oldid=886780353&veaction=editsource

**Comment by rahahahat** [comment]
Hello, thanks a lot for providing the above URL's. I have tested all the variations and all of the tests have been passed. With the expection of `wikisource` URL's , the `articleFromTitleInput` function handles `wikipedia` and `wikimedia` redlinks.

**Comment by ragesoss** [comment]
Great. I think that should be fine. I don't think anyone is likely to use this for a redlink URL from wikisource.

**Comment by rahahahat** [comment]
Hello, i have submitted the pull request highlighting the changes made,
Thanks a lot for helping me throughout the process.
