### ISSUE TITLE
Editors CSV should include number of articles edited, and number of articles created, for each user

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4217]
### Current Behavior:

The CSV of editor data for a course, which can be downloaded via the 'Download stats' modal, includes the following columns: `username	enrollment_timestamp	registered_at	revisions_during_project	mainspace_bytes_added	userpace_bytes_added	draft_space_bytes_added	references_added	registered_during_project`

### Desired Behavior:
Users have requested data on how many articles each editor has edited, and how many articles each editor has created. Columns for those values should be added to the CSV output.

### Related Files & Code:

`lib/analytics/course_students_csv_builder.rb`

**Comment by RuthNjeri** [comment]
@ragesoss I would like to pick this issue, please assign it to me?

**Comment by ragesoss** [comment]
Go for it. We don't generally assign issues; just leave another message here if you're no longer working on it.

**Comment by RuthNjeri** [comment]
Oh alright @ragesoss 

Based on the CoursesUsers model, it seems that the columns to use are:
1. total_uploads for `how many articles each editor has created`
2. revision_count for `how many articles each editor has edited`
Is this correct?

Also, when I access the 'Download stats' model, I get another pop up, 
![Screenshot 2020-10-12 at 18 52 26](https://user-images.githubusercontent.com/7622875/95766611-2e978900-0cbc-11eb-9484-f82315de6158.png)

Which one is related to the CV with the columns related to this issue?

**Comment by RuthNjeri** [comment]
I have downloaded each CSV above and can't find one with these headers `username enrollment_timestamp registered_at revisions_during_project mainspace_bytes_added userpace_bytes_added draft_space_bytes_added references_added registered_during_project` I am testing it locally using the dummy data generated..

**Comment by ragesoss** [comment]
No, neither of the metrics for this issue correspond directly to columns in the CoursesUsers model.

total_uploads is the number of files uploaded to Wikimedia Commons (tracked by CommonsUpload records).

revision_count is the number of edits the Dashboard has recorded for the user during the course (tracked by Revision records). The number of unique articles (unique pages in namespace 0) edited is different.

The popup you have in the screenshot is from a Campaign (which is a collection of Courses). You should probably start from a Course, which has a similar popup, although I think the solution for this issue will affect the CSVs for both Courses and Campaigns.

**Comment by RuthNjeri** [comment]
So far, what I know is that I should use the courses_users in determining what articles the course_user has edited and created.

I've seen the articles_courses joins table contains a row of user_ids as a list, I am not sure what that list of users_ids means in relation to edits or creation...

Also, the articles are not linked to a user_id so I'm not sure how to link which user created an article..

I'm stuck 😅

**Comment by RuthNjeri** [comment]
Is it perhaps tied to the revisions model? I see a new_article column and the revision model is linked to a user?

**Comment by ragesoss** [comment]
A user created an article during a course if a revision within the scope of the course is the first revision in the history of the article. This is represented in the database by the `new_article` attribute of a Revision record.

An ArticlesCourses record represents an article that was edited during a course, and the `user_ids` field is an array of all the users (aka editors) in that course who edited the article during the course. The `new_article` field on that record should be true when one of those editors created the article during the course.

**Comment by RuthNjeri** [comment]
Thanks @ragesoss  this makes it very clear. I'll begin working on the task and get more feedback on the PR I'll create...
I was wondering if there is a documention detailing the process/what each model represents? I don't want to bombard you with so many questions... :)

**Comment by ragesoss** [comment]
The model classes should have some inline documentation, but not a lot of detail. Feel free to open an issue for listing things that you find need more/better documentation (such as maybe a doc that lists the main models and what they represent).

**Comment by RinkiyaKeDad** [comment]
Hey @ragesoss! I see from #4248 that no one is working on this issue. If that's the case I'd like to work on it. I'm new to Rails and Wiki Education Dashboard development 😅 so is there some discord / slack channel I could join for some help? Or do discussions take place on Github itself?
