### ISSUE TITLE
FAQ loads without default questions

### ISSUE THREAD

**Issue by rajat2502** [WikiEducationFoundation/WikiEduDashboard#4234]
> Thanks for reporting a problem! Please delete any line that begins with a '>' (including this one) and replace with your own content.

### What is happening?
> The FAQ page loads without any default questions if the search icon in the navbar is clicked without any search text.

### To Reproduce

> Steps to reproduce the behavior:
> 1. Go to 'https://dashboard.wikiedu.org/'
> 2. Click on 'Search icon'
> 3. FAQs page will open in a new tab without any questions

### Expected behavior
> Show the default questions or the top questions.

### Screenshots
> Here is a video showing the same. 
https://dashboard.wikiedu.org/

**Comment by dldisha** [comment]
I'll work on this issue.

**Comment by prathamVaidya** [comment]
I think this Issue can be closed. Looks like UI has already been updated.

**Comment by prathamVaidya** [comment]
Also @ragesoss  can you send me a slack invite. Can't find a untouched issue to work on. 
Email: iamprathamvaidya@gmail.com

**Comment by ragesoss** [comment]
@prathamVaidya this issue is still present. Compare:

* https://dashboard.wikiedu.org/faq - shows default questions
* https://dashboard.wikiedu.org/faq?utf8=%E2%9C%93&search=&source=nav_ask_form - no default questions shown for empty search

I've sent a slack invite.

**Comment by prathamVaidya** [comment]
Ok, I can work on this issue.
