### ISSUE TITLE
Dashboard may not work on IE 10

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#429]
A user reported not being able to use any of the dashboard features (critically, the 'create course' feature) on IE10. There were no breaking issues known previously with IE 10, but we may have introduced some, or it may be something besides (just) IE 10 that went wrong.

We should put the dashboard through its paces on IE 10, and update the configuration for unsupported browsers if it's now brokenon IE 10.

**Comment by bmathews** [comment]
There may be other issues, but I noticed the use of `HTMLElement.dataset` this morning. It's only IE11+. 
https://github.com/WikiEducationFoundation/WikiEduDashboard/search?utf8=%E2%9C%93&q=dataset

**Comment by bmathews** [comment]
http://caniuse.com/#feat=dataset
