### ISSUE TITLE
A dot in course title breaks things

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#43]
@ntdb Looks like a problem with how CoursesController parses course names.

Here's the relevant error log:

App 8348 stdout: [2015-03-12 14:42:11.692 INFO ] Started GET "/courses/California_Maritime_Academy/LIB100.2_-_Information_Fluency_in_the_Digital_World_(Spring_2015)" for 67.161.126.166 at 2015-03
-12 14:42:11 -0300
App 8348 stdout: [2015-03-12 14:42:11.693 INFO ] Processing by CoursesController#students as
App 8348 stdout: [2015-03-12 14:42:11.693 INFO ] Parameters: {"id"=>"California_Maritime_Academy/LIB100"}
App 8348 stdout: [2015-03-12 14:42:11.694 INFO ] Completed 500 Internal Server Error in 1ms
App 8348 stdout: [2015-03-12 14:42:11.696 FATAL] NoMethodError (undefined method `users' for nil:NilClass):
App 8348 stdout:   app/controllers/courses_controller.rb:30:in `students'
App 8348 stdout: [2015-03-12 14:42:11.697 INFO ] Processing by ErrorsController#internal_server_error as
App 8348 stdout: [2015-03-12 14:42:11.697 INFO ] Parameters: {"id"=>"California_Maritime_Academy/LIB100"}
App 8348 stdout: [2015-03-12 14:42:11.698 INFO ] Rendered errors/internal_server_error.html.erb within layouts/application (0.2ms)
App 8348 stdout: [2015-03-12 14:42:11.700 INFO ] Completed 200 OK in 3ms (Views: 2.6ms | ActiveRecord: 0.0ms)

**Comment by ragesoss** [comment]
@ntdb Looks like this is maybe the solution? http://devblog.avdi.org/2010/06/18/rails-3-resource-routes-with-dots-or-how-to-make-a-ruby-developer-go-a-little-bit-insane/

**Comment by ragesoss** [comment]
@ntdb Does this look right to you? I tested it locally and it fixes the problem.

**Comment by ragesoss** [comment]
I deployed this.

**Comment by ntdb** [comment]
@ragesoss looks solid, thanks!

**Comment by ragesoss** [comment]
This seems to have reappeared on staging: http://dashboard-testing.wikiedu.org/courses/California_Maritime_Academy/LIB100.2_-_Information_Fluency_in_the_Digital_World_%28Spring_2015%29
