### ISSUE TITLE
Assignments template isn't working as expected

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#430]
The assignment talk page updates have been doing pairs of updates that add and then remove users. See the history of this page, for example: https://en.wikipedia.org/w/index.php?title=Talk:Lasioglossum_figueresi&action=history

**Comment by ragesoss** [comment]
Possibly this is related to #421

**Comment by ragesoss** [comment]
@mattfordham FYI, this has become the top priority issue, and it's related to #421 and #422. It's  being caused by the case-variant issue: we have users in the same class who are assigned to case variants of the same article. So when the WikiEdits.update_assignments function loops through the assignments grouped by title, it finds two different groups for the same title, and runs the talk page update separate for each case variant, replacing the users assigned to one case variant with the users assigned to the other.

We can probably fix most of the current database situation, if not all, by creating a cleaner to update the article titles of all assignments that have article_ids so that the article_title matches the title in the actual article.

Then we need to implement better handling of the article title input... beginning with upcasing the first letter, since all articles will start with a capital letter. And then maybe we run that cleaner on a regular basis to catch any other cases where a case variant gets saved... although for other cases it probably won't be the same article id, since only the first letter of an article title is necessarily capitalized and aliased to the lower case equivalent.

I'm going to work on the cleaner, but if you've still got some time to hack on the dashboard today, @mattfordham, it'd be great if you could make a migration or somesuch to switch our database to case-sensitive collation.

**Comment by mattfordham** [comment]
I'm attempting to wrap my brain around this. I probably won't be able to understand things well enough to get to a solution today, but will keep looking into it. How did the cleaner go?

**Comment by mattfordham** [comment]
So, let me see if I'm understanding... the core issue is that the `WikiEdits.update_assignments` function thinks that one article is actually two if the assignments are captured with slightly different capitalization. True?

If this is the case, shouldn't the "database collation" be switched to be case *insensitive*, verses *sensitive*, as you are suggesting? The app should see them as the same article regardless of case... true?

**Comment by ragesoss** [comment]
You're right that I've conflated some issues. The database collation *should* be case sensitive, but it's not, because "Rage Sauce" and "Rage sauce" would be considered different articles on Wikipedia, and if we're doing `find_by(title: 'Rage sauce')`, we only want to find the second one. That's not as relevant as I thought it was here.

For assignment (and article titles), the matter at hand is more one of capitalizing the titles that come from user input before we save them.

**Comment by ragesoss** [comment]
So, in answer to your earlier question... it took several tries, but I got the cleaner working.

I think if we sanitize the inputs by both converting spaces to underscores and capitalizing the first letter, then that will fix the source of the problem.

**Comment by ragesoss** [comment]
We match an assignment title to an Article id using Article.find_by here: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/lib/assignments_manager.rb#L10

So the database collation is still a relevant issue. But the fixes I just made to run Utils.format_article_title before saving assignments should put a bow on this issue.

**Comment by mattfordham** [comment]
Nice work! Let's discuss the database collation thing on Friday. A discussion will help me understand things a little clearer, I think.
