### ISSUE TITLE
Article Viewer should have a Print feature

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4313]
The Article Viewer's authorship highlighting is useful for evaluating and sharing the changes made to a Wikipedia article, and some instructors want to be able to print this or save it as a PDF (so that, for example, they can annotate it by hand, or simply save a record of it).

Using built-in browser print features doesn't provide a usable print version, because of the modal layout of the Article Viewer over the rest of the page. The default print version also doesn't render the authorship highlighting.

We could probably implement a printable version by:
* Using a popup window with just the article viewer HTML
* Using a stylesheet designed for print to style the popup window (or adding print styling to the main stylesheet)

**Comment by anjali1102** [comment]
@ragesoss  taking up this issue

**Comment by ragesoss** [comment]
Awesome!

**Comment by tnwoodard** [comment]
Hi @ragesoss. Can I work on this issue?  Thanks!

**Comment by ragesoss** [comment]
@tnwoodard yes... although I'm not sure how big of a challenge this ticket will be.

**Comment by tnwoodard** [comment]
I understand. I will work on my previous issue and come back to this later. Thanks Sage.
