### ISSUE TITLE
There should be a way to see the problems for an individual course: Alerts, possible plagiarism, and deleted articles

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4314]
### Current Behavior:
We generate a lot of different information about problems that come up during a course, including `Alert` records, automatically detected edits that might be plagiarism, and deleted revisions and articles. There's no UI to see this stuff, however.

### Desired Behavior:
This probably makes sense as a new tab of the Course component, maybe as a subtab of Activity, and could be implemented in several stages:

1. Show the `Alerts` for a course. We already have components to do this, which are used in the Campaign Alerts tab and the admin-only `alerts_list` page. This should work just like the Campaign Alerts page, except showing only the alerts for that course. Admins should get all alerts, while other users should only get public alerts.
2. Show edits that might be plagiarism, ie, course revisions that have an `ithenticate_id` attribute. For each one, it should include a link to the revision, a link to the article, and (only for admins or instructors) a link to the plagiarism report.
3. Deleted revisions and articles

**Comment by Gchahm** [comment]
Ok I've done my initial check for the first part and here's what I think needs to be done for it.
### Rails
1. add method alert in courses_controller (similar to the existing campains_controller method)
2. create the routes
3. add view / json builder for the method here the json builder will be different from what already exists in campains because it needs to return course.alerts for admins and course.public_alerts for non admins

### React
I'm not so sure of this yet but I suppose the steps are something like
1. add new tab item for courses alert
2. load alerts from the new method in redux and let the container do the rest (?)

I'll start working on this today can you assign this to me please?

**Comment by ragesoss** [comment]
Yep, that sounds like the right shape of things!

**Comment by Gchahm** [comment]
Hey Ros,

I can see potential for some refactor on the [alert_actions](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/actions/alert_actions.js)

Basically for this work I'll need to add 2 new functions in this file **fetchCourseAlertsPromise** and **fetchCourseAlerts**

They will be pretty similar to **fetchCampaignAlertsPromise** and **fetchCampaignAlerts** the only real difference would be the url they access.

So the first part would be to create a function **requestAlerts** like the below and have all the promisses including **fetchAdminAlertsPromise** to call this

```js
const requestAlerts = (url) => {
  return request(url, {
    credentials: 'include'
  }).then(fetchResponseToJSON)
    .catch((error) => {
      logErrorMessage(error);
      return error;
    });
};

const fetchAdminAlertsPromise = () => requestAlerts('/alerts_list.json');
const fetchCampaignAlertsPromise = slug => requestAlerts(`/campaigns/${slug}/alerts.json`);
const fetchCourseAlertsPromise = slug => requestAlerts(`/courses/${slug}/alerts.json`);
```

the other improvement would be create 2 functions that handle then and catch as this is duplicate in all fetch

```js
const receiveAlerts = (dispatch) => (data) => dispatch({ type: types.RECEIVE_ALERTS, data });
const apiFail = (dispatch) => (response) => (dispatch({ type: types.API_FAIL, data: response }));

export const fetchCampaignAlerts = campaignSlug => (dispatch) => {
  return (
    fetchCampaignAlertsPromise(campaignSlug)
      .then(receiveAlerts(dispatch))
      .catch(apiFail(dispatch))
  );
};
```

Would this be relevant, if so is it Ok to get it done in this pull request or should it be a separate request?

The other alternative would be copying and pasting the existing **fetchCampaignAlertsPromise** and **fetchCampaignAlerts**  rename Campaing to course and change the url.

**Comment by ragesoss** [comment]
Doing the refactor in the same PR is fine, and looks like a good idea to me.

**Comment by Gchahm** [comment]
Ok, that's done now.

Moving to item 2
- should I use course.revision, course.all_revisions or course.tracked_revisions ?
- Is there already a component that does this or is it a new component alltogether?

**Comment by ragesoss** [comment]
I suggest getting the whole thing working with Alerts before moving on to the plagiarism revisions (but when you get there, `course.revisions` is probably the best option).

The existing component for displaying alerts is `AlertsHandler`, which you can see used in the `CampaignAlerts` and `AdminAlerts` components.

**Comment by Gchahm** [comment]
I have the first part completed already, I'll get send a pull request so you can review that part.

**Comment by Gchahm** [comment]
I'll start the second part today.

> Show edits that might be plagiarism, ie, course revisions that have an ithenticate_id attribute. For each one, it should include a link to the revision, a link to the article, and (only for admins or instructors) a link to the plagiarism report.

Backend 
1. Create a new method in Course class ithenticated_revisions that returns possible plagiarism
2. Create a new method in CoursesController that returns ithenticated_revisions
3. Create route
4. Create json builder (in here add logic to now return the report if the user is not a manager)

Frontend
1. Add new tab in activity
The new table can be similar to the existing recent activity table but removing the chars added and references added and adding the link to the plagiarism report for managers

![image](https://user-images.githubusercontent.com/24531739/104758373-3dc42200-5756-11eb-9993-6afc58ff0cec.png)

**Comment by ragesoss** [comment]
That seems largely correct. The `Course` method is probably simplest to implement as a scope that builds on `#revisions`. It should be named something like `possible_plagiarism_revisions`; ithenticate is specific to the 3rd party system we're using to identify possible plagiarism, but it's not a concept that is central to the idea of selecting a set of revisions that might be plagiarism.

On the frontend, this will mean going back to a set of `SubNavigation` links for all users (and only including the Alerts one for admins).

**Comment by Gchahm** [comment]
That makes sense.

I've reviewed the front end and there's already a redux store for "suspected plagiarism" which I'll use for this. Might be a good idea to stick to the same naming. I'll also refactor RevisionAnalyticsService.suspected_plagiarism to use the new scope.

**Comment by Gchahm** [comment]
Deleted revisions and articles
Should we have this into a single tab and show a table that has a column to identify if the item deleted is a revision or an article or should it be 2 separate views?

**Comment by ragesoss** [comment]
Hmm... good question. I think it makes sense to only have a single view for this, but I'm not sure how best to combine that information. In most cases, if there is a deleted article, there will also be deleted revisions to that article... but the table shouldn't show both of those things separately.

I think think a structure like this could work:

Article | Users | Deleted revisions
Existing Article [link to article] | User1 [link to user] | 2 [link to article history]
Deleted Article (deleted) [link to article, article title in red to indicated it was deleted, "(deleted)" after title as well] | User1, User2 | 6 [link to Wikipedia page logs, eg https://en.wikipedia.org/wiki/Special:Log?type=&user=&page=List+of+snowclones&wpdate=&tagfilter=&subtype= ]

**Comment by Gchahm** [comment]
I think I get it.

So each line will represent a revision, I'm not familiar with how wikipedia works, is there going to be a case where the article has been deleted and there are no revisions deleted? Or deleting an article cascade into revisions and set them all to deleted?

**Comment by ragesoss** [comment]
On Wikipedia, admins can delete an entire article (and all its revisions) or just delete specific revisions from the history while leaving the article in place.

Each line will represent an article, but an article could have one or more of its revisions deleted without the article itself being deleted (or the whole article and all of the student's revisions could be deleted).

If an article gets deleted, I don't think the Dashboard necessarily sets the revisions as deleted as well, so I think that number would probably just be the total count of revisions to that article under the assumption that all of them are deleted along with the article itself.

**Comment by Gchahm** [comment]
Got it.

So an article will show only once in the table, no matter how many deleted revisions. The actual revisions deleted will be seen in the article history.

There's currently no method to retrieve articles that are either deleted or have deleted revisions, so I will add a scope for that in Article.

The front end should be similar to what was done with plagiarism so for now I don't have any questions on that.

**Comment by ragesoss** [comment]
This is done, just forgot to close it. :)
