### ISSUE TITLE
yarn build script doesn't work on Windows

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4319]
Among other possible problems, `prepare.js` calls `rm` to remove any existing assets before building new ones, but the `rm` command is not available on Windows.

**Comment by YusufAbdelaziz** [comment]
I guess removing is working in windows.
![image](https://user-images.githubusercontent.com/43118820/103969147-f7772d80-516d-11eb-8375-255d86fc053b.png)
But unfortunately, I couldn't understand the reason why "robocopy" is not working.
![image](https://user-images.githubusercontent.com/43118820/103969160-fe05a500-516d-11eb-8b58-9d4f5b003aec.png)

**Comment by ragesoss** [comment]
This works on Windows via Ubuntu / WSL 2, so that's how we'll recommend people set up a dev environment on Windows going forward.
