### ISSUE TITLE
setup.py is not working on ubuntu 20.04 with python 3.8.5 and ruby 2.7.1p83

### ISSUE THREAD

**Issue by UmerMIB** [WikiEducationFoundation/WikiEduDashboard#4328]
### What is happening?
 I am setting up a development environment on `ubuntu 20.04` with `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]` and `Python 3.8.5`, run  `python3 setup.py` and got this error 

`Please install ruby-2.7.1 before running this script.
Sorry! Your operating is not supported by this script. Please refer https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/ docs/setup.md for manual setup instructions.`

### System Information
Ubuntu 20.04.1 LTS

### Additional context
> Also the link in error `https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/ docs/setup.md` have spaces in between `https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/` `docs/setup.md`

Your little guidance is highly appreciated

**Comment by ragesoss** [comment]
@marklocklear please do! thanks!
