### ISSUE TITLE
Index articles on title

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#433]
`UsersController#save_assignments` calls `Article.find_by_title`, which is crazy slow:

<img width="1064" alt="screen shot 2015-10-22 at 10 12 47 am" src="https://cloud.githubusercontent.com/assets/702327/10672521/98cbd3ae-78a5-11e5-931e-068230ad8c37.png">

Indexing that table on `title` should help that a good bit.

**Comment by KarmaHater** [comment]
@thenickcox @ragesoss I know this issue is old but better late then never :) 

https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1457

**Comment by ragesoss** [comment]
Hmm... I think this actually got addressed a while ago (with the index on title + wiki + namespace). I think we no longer do any queries on just article title.
