### ISSUE TITLE
When cloning a course, instructor should have the option to copy Available Articles list

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4331]
### Current Behavior:
Cloning a course creates a copy of an old course's timeline, but with no Available Articles.

### Desired Behavior:
Some instructors want to re-use the set of available articles from a previous course. When they clone a course, they should have an option to copy over the available articles as part of the cloning process.

### Related Files & Code:

* Backend: `course_clone_controller.rb` and  `course_clone_manager.rb`
* Frontend: `course_clone_button.jsx` and/or `course_cloned_modal.jsx` and/or `reuse_existing_course.jsx`

**Comment by rohitgeddam** [comment]
Hey, this looks interesting,  I would like to work on this!

**Comment by carlwcheung** [comment]
Hey @rohitgeddam, are you still working on this? If not, I'd like to start taking a look

**Comment by ragesoss** [comment]
@carlwcheung I haven't heard from rohitgeddam in a little while. Feel free to work on this.

**Comment by ragesoss** [comment]
See also `docs/course_update_scripts/copy_assignments` which is how I've been doing this task for already existing courses when an instructor requests it.
