### ISSUE TITLE
Remove trailing space from the message "course passcode"

### ISSUE THREAD

**Issue by amire80** [WikiEducationFoundation/WikiEduDashboard#4341]
### What is happening?
The message `course_passcode` in the `config/locales/en.yml` file has a trailing space. I've never actually seen it as a user, but as far as I can see in the code, it is used in two places in jsx files, and in both of them, immediately after the message, there's a `<b>` element (bold text) in which the passcode is filled.

In translatewiki, it's impossible to translate a message with trailing space. The best way to address this is to add the passcode value as a parameter to the `course_passcode` message itself.

Without this, it will (probably) appear like this in all user interface languages but English:
Passcode:<b>12345</b>

**Comment by ragesoss** [comment]
This, along with all the other trailing whitespace messages we identified, should be fixed now.
