### ISSUE TITLE
The message courses.active_courses should be split

### ISSUE THREAD

**Issue by amire80** [WikiEducationFoundation/WikiEduDashboard#4342]
The message courses.active_courses currently says `Active %{course_type}`, which `%{course_type}` can be "courses" or "campaigns". This works in English, and it _happens_ to work in Hebrew, but it's also possible that it wouldn't work, if the word "campaigns" would be in a different grammatical gender from "courses". In this case, the word "Active" would have to be different. It's quite possible that it already doesn't work correctly in some languages, although I cannot check them all.

I strongly recommend splitting this messages to two: "Active courses" and "Active campaigns".

**Comment by Sahethi** [comment]
Hey, I would like to work on this issue.

**Comment by ragesoss** [comment]
@Sahethi go for it. :-)

**Comment by Sahethi** [comment]
Hello! I apologise if this is too trivial of a doubt but I wanted to know if I'm dealing with it correctly. Like I think it deals with this element on the frontend 
<img width="1235" alt="Screenshot 2022-01-18 at 6 22 14 PM" src="https://user-images.githubusercontent.com/40771676/149940774-0719598e-77cf-4505-8511-c9bb1986f60f.png">

 
but I'm not exactly sure if I even have to implement this part while setting up the dev env, because does the Active Courses deal with the WikiEdits feature cause it mentions that it's responsible for course creation 
<img width="1112" alt="Screenshot 2022-01-18 at 6 17 02 PM" src="https://user-images.githubusercontent.com/40771676/149940072-4e546f79-cb57-404b-87c1-33f3b98e3016.png">

**Comment by ragesoss** [comment]
@Sahethi no, you don't need to go through any OAuth setup steps for this issue. That's only necessary for letting your dev environment make edits on Wikipedia, which is not necessary for creating courses or doing anything related to this issue.

**Comment by Sahethi** [comment]
@ragesoss very well, thank you!

**Comment by Sahethi** [comment]
also wanted to confirm if I'm dealing with the correct element in the frontend as mentioned in the previous comment for the message `Active %{course_type}` where its Active Campaigns here

**Comment by Sahethi** [comment]
Hey, I had been going through the code, but on the development side I can't see this section (one the screenshot), where the issue exists. I'm not sure how to create new courses, I can only active campaigns but can't see active courses below it in the dashboard

This screenshot is from [https://dashboard.wikiedu.org/explore](https://dashboard.wikiedu.org/explore)
![image](https://user-images.githubusercontent.com/40771676/153725030-6867ddf3-9086-4bea-9a8f-f696ecc7f872.png)

**Comment by ragesoss** [comment]
Looks like that only shows up in `wiki_education: 'true'` mode. If you set that in `application.yml`, you should see this section.

**Comment by Sahethi** [comment]
> Looks like that only shows up in `wiki_education: 'true'` mode. If you set that in `application.yml`, you should see this section.

oh, thank you
i'll try doing that

**Comment by Sahethi** [comment]
Hey, I was able to see the section I queried about previously and I submitted the PR #4799 
I have only updated **config/locales/en.yml** and wasn't sure if the same has to be done for the rest of the files in **config/locales**

**Comment by ragesoss** [comment]
@Sahethi it should also update the qqq.yml file, which is for descriptions of the interface messages to help translators understand the context and usage of each message. The others don't need to be changed; they get updated periodically based on translation updates that people contribute to translatewiki.net.

**Comment by Sahethi** [comment]
@ragesoss Thank you! I have made the necessary changes in the PR #4799
