### ISSUE TITLE
Wikidata stats should be download option for an entire campaign

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4345]
### Current Behavior:
For courses that are tracking Wikidata, the 'download stats' modal has an option to download Wikidata-specific stats. However, there's no way to download the aggregate Wikidata stats for an entire campaign (except by downloading the Wikidata stats for each course and adding them together yourself).

### Desired Behavior:
The 'Download stats' modal on a campaign Home tab should provide a Wikidata option.

### Related Files & Code:
* `CourseWikidataCsvBuilder`
* `CampaignStatsDownloadModal`
* `CampaignsController`

### Additional context:
Follow the pattern used by other campaign stats data flows: build on top of the course CSV builder to compile data for all the courses in a campaign.

**Comment by cyrillefr** [comment]
Hello @ragesoss , may I work on this one ?

**Comment by ragesoss** [comment]
@1v4n4 would you like to let cyrillefr take this on? (Ivana is working on Wikidata stats for her Outreachy internship, and might otherwise take this on pretty soon.)

**Comment by 1v4n4** [comment]
I was thinking to add Wikidata stats to a campaign.json as a next step. I think that would  impact this issue. Otherwise, I don't mind.

**Comment by ragesoss** [comment]
Cool. I think doing it in campaign.json will basically be independent of this task. What impact do you foresee?

**Comment by 1v4n4** [comment]
well, i thought about it and it wouldn't. except it will generate the same data as csv

**Comment by ragesoss** [comment]
Great. Go for it, @cyrillefr .
