### ISSUE TITLE
On P&E Dashboard, update info should show up before the first update

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4347]
### Current Behavior:
Once a course has gone through its first stats update, the 'Last statistics update' detail shows up beneath the stats on the Home tab, with a 'see more' modal that includes additional information about the update process and things that may go wrong with it.

However, between the start of a course and its first update, there's no indication of how long you may need to to wait before an update, and this is a common source of questions and confusion — especially for long courses that initially get sorted into the 'long_update' queue and may take several days before they are first updated.

### Desired Behavior
An update info message should show up even before the first update, and the 'see more' modal should provide info about roughly when to expect an update.

**Comment by gauransh7** [comment]
I had some doubts regarding this issue - 
1. What should be the update info message that we need to show?
2. I ran the `updateCourseStats` function manually to update activities of my course, but how should we provide info about roughly when to expect an update.

**Comment by ragesoss** [comment]
The update message should be something like: "The Dashboard hasn't imported any data for this program yet. It has been added to an update queue that currently takes about [X time] for a program to receive its first update."

The actual time to show there should be based on the Sidekiq queue latency for whatever queue it is sorted into initially.

See `CheckCourseJobs` for related code. Basically, you'll need to figure out the right way to use `Sidekiq::Queue` to find the current latency for a particular queue.

**Comment by 1v4n4** [comment]
I'd like to try to figure out this issue if no one's on it

**Comment by ragesoss** [comment]
@1v4n4 great! Go for it.
