### ISSUE TITLE
Student's list of trainings and exercises should be ordered by due date, and divided by already-due vs not-yet-due

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4359]
### Current Behavior:
On the Students tab when viewing the Trainings & Exercises for a student, the trainings and exercises are shown in an arbitrary order that makes it difficult to gauge whether the student is all up-to-date with trainings or has overdue trainings that haven't been completed yet.

### Desired Behavior:
The trainings and exercises should be ordered by due date, with some kind of indication of the division between already-due trainings and exercises vs not-yet-due trainings and exercises.

### Related Files & Code:
`StudentExercisesList.jsx`

**Comment by gauransh7** [comment]
Hey @ragesoss,
 
Trainings are not sorted by the due date, but exercises are already sorted within their respective categories(unread, complete, incomplete). So, we need to sort trainings only and show some indication of the division between already-due training and exercises vs. not-yet-due training and exercises?

**Comment by ragesoss** [comment]
I think we want to sort both trainings and exercises by due date (and not by unread/complete/incomplete). I think it probably still makes sense to show trainings separately from exercises.

**Comment by gauransh7** [comment]
Thanks for the explanation @ragesoss.
I would like to work on this issue.

I am planning to change the `ExerciseRows` and `generateRow` function in the [ExerciseRows.jsx](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/ec1bcb59a262ae83bf85c0d5295681bacb31aa02/app/assets/javascripts/components/students/shared/StudentList/StudentDrawer/TrainingStatus/ExerciseRows.jsx#L19) file such that the unread, complete and incomplete exercises are all sorted at once.
For sorting the trainings, we can add a sort function in the [TrainingModuleRows.jsx](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/components/students/shared/StudentList/StudentDrawer/TrainingStatus/TrainingModuleRows.jsx) file.

Does that look right?
Also, I wanted to ask what kind of indication can we show between over-due and not-yet-due trainings and exercises? Will a background-color change be a good idea ?

**Comment by ragesoss** [comment]
Yes, I think a background change is fine. It can be very subtle, such as a slightly darker background for not-yet-due ones.

Your plan sounds reasonable.
