### ISSUE TITLE
Article Viewer throws errors when article doesn't exist

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4363]
### What is happening?
When viewing a student in the Assignments & Exercises view on the Students tab, if the student has an assigned article then there is an Article Viewer icon for it. However, if the assigned article doesn't exist yet, this is useless and just shows an error message when viewed.

### To Reproduce

* In a course, assign someone an article title that doesn't exist.
* View that user from the Students tab and click the Article Viewer for that assignment

### Expected behavior

Article Viewer should not be clickable if the article doesn't exist yet, and mousing over it should show a message indicating that the article doesn't exist.

**Comment by rohitgeddam** [comment]
I would like to work on it!

**Comment by rohitgeddam** [comment]
Isn't it better to prevent assigning an article title that doesn't exist in the first place? rather than making the link not clickable.

**Comment by ragesoss** [comment]
The reason we want to disable it here rather than prevent users from assigning articles that don't exist is because students are sometimes creating new articles for their Wikipedia writing assignments. Putting in an assignment title that doesn't exist on Wikipedia yet is a signal that the student plans on creating that article, and the Dashboard handles that accordingly.

**Comment by rohitgeddam** [comment]
> The reason we want to disable it here rather than prevent users from assigning articles that don't exist is because students are sometimes creating new articles for their Wikipedia writing assignments. Putting in an assignment title that doesn't exist on Wikipedia yet is a signal that the student plans on creating that article, and the Dashboard handles that accordingly.

ok, got it
