### ISSUE TITLE
Users with invalid usernames added to a course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4387]
I discovered a course — [this one](https://outreachdashboard.wmflabs.org/courses/Culture_Laurentides/Atelier_1_(9_mars_2021_de_15_à_17h_EST)) — where all the users had invalid usernames like "Fr:User:Misspixels". (I replaced them with the valid usernames, by removing the "Fr:User:" prefix.)

It should not be possible to add invalid usernames like that, and I don't know how it happened. Normally the data flow for adding a new user involves getting info about that user from a wiki, so usernames get validated before a `User` or `CoursesUsers` record is created.

The normal enrollment flows include:
* self-enrollment, where a user joins a course by following an enrollment link while logged in
* instructor enrollment, where an admin or course instructor adds the username of an editor via the Students/Editors tab
* mass enrollment, where an admin or instructor pastes a list of usernames to add all at once

Find out how invalid usernames could have been added, fix it, and write a test for it.

**Comment by ragesoss** [comment]
I still have no idea how this happened in production, or how to replicate. The first step to a fix here would be to replicate it (or come up with a plausible mechanism, so that we could see if it was possible in 2021 and whether the responsible code got changed to prevent it in the meantime).

It's a little mystery.

**Comment by singhavs** [comment]
@ragesoss is this mechanism taking place in new_account_actions.js?

**Comment by ragesoss** [comment]
@singhavs I doubt it. The creation of `User` records takes place on server-side. I have not investigated whether this might have happened via the Requested Accounts feature, which is related to new_account_actions.js.

This has not happened again since two years ago, though, so I'm very uncertain whether there is any extant bug or not.

**Comment by ragesoss** [comment]
I haven't seen this again, so closing.
