### ISSUE TITLE
Font sizes are inconsistent between browsers

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#439]
This happens with some fonts in particular, depending on how Firefox / Iceweasel decide to substitute fror nonfree fonts.This seems to be especially an issue with the new font introduced for the training. I think we worked around this for similar font issues in the past. Ring a bell, @ntdb?

The main problem here is that the layout gets broken for "TABLE OF CONTENTS (10)".

### Iceweasel
![font handling on iceweasel](https://cloud.githubusercontent.com/assets/848483/10772024/1da7ab3e-7cb1-11e5-9b90-1dd9471785ee.png)

### Chromium
![fonts on chromium](https://cloud.githubusercontent.com/assets/848483/10772051/412e5de6-7cb1-11e5-920c-de95307a0080.png)

**Comment by ntdb** [comment]
@ragesoss Unfortunately no, I don't recall tackling FF/Chrome font substitution issues. Sorry!

**Comment by thenickcox** [comment]
I recently fixed a problem related to this that was due to an oversight on my part, not actually loading Source Sans Pro through Google webfonts, which was fixed in d5c0e9d. I'd be interested if you're still seeing this. You shouldn't be.

**Comment by ragesoss** [comment]
@thenickcox Yeah, looks like that was the cause of it. Maybe same issue but different font: Here's how the arrow navigation guider looks in Iceweasel (with text cut off).
![text in arrow nav guider](https://cloud.githubusercontent.com/assets/848483/11013439/aa922eac-84c2-11e5-86e3-4067cdbdf67a.png)

**Comment by thenickcox** [comment]
This was a different issue, but is closed via 449ee99
