### ISSUE TITLE
Table of participants jumps wildly when scrolling just few pixels up/down

### ISSUE THREAD

**Issue by dvorapa** [WikiEducationFoundation/WikiEduDashboard#4426]
### What is happening?
If I scroll a table of participants page up/down, at one point the page makes weird jumps. I want to see it in the middle of my screen, but the table can be only on top of the screen or bottom, not in between. See the following captures. Pay attention to scrolling distance of the pointer/scrollbar - just few pixels:

https://user-images.githubusercontent.com/5113916/116111589-1535b780-a6b7-11eb-9c15-f3c903df8271.mp4

_Can't scroll to the bottom of the page at all, scrolling breaks at one point and page jumps wildly (more than screen capture software was able to handle)._

https://user-images.githubusercontent.com/5113916/116110147-b6bc0980-a6b5-11eb-9dc9-ad1a91146c18.mp4

_Specific point where this wild jumping happens on page._

### To Reproduce

1. Go to https://outreachdashboard.wmflabs.org/courses/Technick%C3%A1_univerzita_v_Liberci/Liberec,_jaro_2021,_za%C4%8D%C3%A1te%C4%8Dn%C3%ADci/students/overview using Mozilla Firefox (not far from v88 - that's mine) at 1366x768 screen resolution
2. Scroll down using scrollbar
3. See weird behavior

### Expected behavior
Scrolling should be smooth

### Screenshots
_See the captures above._

### System Information

 - OS: Arch Linux (I think it happens to me also in Windows, but I need to restart my PC to check)
 - Browser: Firefox
 - Version: 88

### Additional context
I believe this is caused by the sticky table header, which behaves somewhat broken and makes the page jump wildly.

**Comment by KhanFiza896** [comment]
@dvorapa  can i work on this?

**Comment by ragesoss** [comment]
@KhanFiza896 yes. Please work on one issue at a time and leave a message on the one you're working on.

**Comment by FIZA-khan7** [comment]
Okk thanku...I am working on this..
