### ISSUE TITLE
Standarize the usage of icons in the UI

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4466]
Icons are implemented in different ways throughout the app. There's an 'icon font' (`app/assets/fonts`) which hasn't been updated in a long while but it still used for some icons, via CSS classes. There are also a variety of SVG icons (`app/assets/images`) which are used as background images for CSS classes, and there are some SVG icons defined directly in JSX components (eg, `enroll_card.jsx`).

Identify the best pattern for handling icons throughout the app and standardize it so that all icons are implemented the same way.

### Related Files & Code:

* `app/assets/stylesheets/_icons.styl`

**Comment by aaditya9899** [comment]
we can use fontawesome for that i think so?

**Comment by aaditya9899** [comment]
yeah I thought so while implementing fontawesome but installing it will bring all the icons from the library which might reduce page efficiency and better alternative might be using react-icons library as it will just import the necessary icons and that too from different websites!! 

here's the link , do tell me how this sounds to you.

[https://react-icons.github.io/react-icons]

**Comment by aaditya9899** [comment]
yeah I get to know while implementing fontawesome that installing it will bring all the icons from the library which will reduce page performance and better alternative might be using react-icons library as it will just import only the necessary icons we use in the page and also provide one additional functionality of choosing icons from different library as well like fontAwesome, Feather, Bootstrap etc !!!

here's the link , do tell me how this sounds to you.

https://react-icons.github.io/react-icons

**Comment by ragesoss** [comment]
We want to keep the current icons we're using, and just standardize how they are implemented. It looks like `react-icons` is a library for importing from an existing collection of icons, not taking custom icons and integrating them into an app.

**Comment by aaditya9899** [comment]
Oh okay understood i will tell you if i start working on this one.

**Comment by prashulkale** [comment]
if you allow me to contribute on the feature, I will update it with REMIX ICON

**Comment by ragesoss** [comment]
I don't know anything about Remix Icon. If it can be used for any icon assets (so that we can continue using the current icons we have, and just standardize them via this library), then I'm open to it. I suggest starting with a demo showing how it would be implemented for a single icon, one of the ones we already use.

**Comment by ujjwalpathaak** [comment]
There are ways the icons are being used as per the issue - 
**1. icons directly mentioned in JSX components -** identify JSX components to find instances where icons are directly mentioned. Convert these icons to SVG files and use them just like other SVGs being used.
**2. icons being used from the font files -** Convert these font-based icons to SVG format and using them as using font files is an outdated method.
**3. icons already being used from SVG files -** "images" folder as mentioned contains GIFs, PNGs and SVGs which lead to wrongly named directories. Create 2 new folders within the "assets" folder, separating GIFs and SVGs into distinct folders for better organization and clarity. While keeping the PNG images in “images” folder.

**Comment by Alone-Y154** [comment]
@ragesoss  I would like to work on this issue

**Comment by ragesoss** [comment]
> 
> Should I try handling icons this way to see if it's feasible?

Sorry, I missed replying to this earlier. This sounds very reasonable. If you're still interested, go for. It's fine to work on it incrementally; small PRs will be easy to handle.

**Comment by Nikuunj** [comment]
I have some experience in programming languages like html , css , js , react . I am passionate about open-source and have recently participated in Hacktoberfest 2023. I am now seeking mentorship to improve my skills in open-source development. I am keen to contribute to your projects and would appreciate your guidance on how to get started.
