### ISSUE TITLE
Nonexistent pages in the /training path should give a 404, not a 500

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#450]

**Comment by thenickcox** [comment]
Closed via 2c2858f

**Comment by thenickcox** [comment]
Oh, it raises, which is a 500. * facepalm *

**Comment by thenickcox** [comment]
Wait, this _does_ throw a 404. What's not working the way you'd expect?

![screen shot 2016-01-04 at 10 11 04 am](https://cloud.githubusercontent.com/assets/702327/12096638/88d1a298-b2cb-11e5-99ab-85425be953f2.png)

**Comment by thenickcox** [comment]
Confirmed same behavior both for not-found slides and modules:

![screen shot 2016-01-04 at 10 11 57 am](https://cloud.githubusercontent.com/assets/702327/12096647/a3a92d02-b2cb-11e5-97c6-ed02c0b1e4a3.png)

**Comment by ragesoss** [comment]
Try this: https://dashboard-testing.wikiedu.org/training/students/editing-basics/foobar

**Comment by thenickcox** [comment]
Ah. Gotcha.
