### ISSUE TITLE
Replace react-motion with react-spring

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4510]
We currently use the unmaintained `react-motion` library to provide animations for when a user is reordering blocks in a course Timeline. (See `week.jsx`.) It throws warnings right now, and is likely to stop working with a future version of React.

It looks like `react-spring` provides the same sort of functionality — it's similarly based on the `spring` concept — and it is actively maintained.

Convert `week.jsx` to use `react-spring` instead of `react-motion`.

**Comment by TheTrio** [comment]
This can be closed as well.
