### ISSUE TITLE
Add username to "Articles data" export in Outreach Dashboard

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4528]
See https://phabricator.wikimedia.org/T284762

**Comment by FatimaJaffal** [comment]
@ragesoss I opened a PR for this https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/4885.

**Comment by FatimaJaffal** [comment]
@ragesoss can you review it please.
