### ISSUE TITLE
In Tickets interface, 'delete' icon for a Note isn't rendering

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4538]
### What is happening?

Broken icon:
![delete icon](https://user-images.githubusercontent.com/848483/123669202-b0025d80-d7f0-11eb-803f-603a10a8074d.png)

### To Reproduce

1. Log in as an admin
2. Create  a Ticket (you may need to do this from the rails console)
3. Navigate to the ticket, enter a message, and click 'Create note'

### Additional context
I'm not sure exactly when this broke.

**Comment by chepyego** [comment]
I have started working on this issue

**Comment by chepyego** [comment]
can i work on this ticket?

**Comment by ragesoss** [comment]
Not yet. It may be a little while, as I'm traveling this week.

**Comment by chepyego** [comment]
okay no problem you will check them when you have time

**Comment by ragesoss** [comment]
The Ticket may need an associated Message.
