### ISSUE TITLE
istanbul coverage report does not include .cjsx or .jsx files

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#454]
Only the coffeescript coverage is included.

**Comment by thenickcox** [comment]
[This NPM module](https://github.com/zordius/gulp-jsx-coverage) might give us what we want. It looks to include .cjsx files.

**Comment by ragesoss** [comment]
@thenickcox it does now! https://github.com/zordius/gulp-jsx-coverage/issues/19

**Comment by ragesoss** [comment]
By 'switch to ES6', do you mean also convert all of our existing coffeescript and .cjsx to ES6? If so, I assume there's some transpiler to do that automagically?

**Comment by ragesoss** [comment]
Fixed with a62fce7add4bacd7e9abdfeca9bb73af464dc13f and prior commits.
