### ISSUE TITLE
training slide style: next arrow, and images that extend out of main slide region

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#455]
@thenickcox Maybe we need a "clear:both" at the end of slide content. And it looks like there was a mixup of the icons.

![training slide image overlap](https://cloud.githubusercontent.com/assets/848483/11043002/5a9210fc-86cf-11e5-9fa3-3b6278dba232.png)

**Comment by thenickcox** [comment]
Closed via a couple commits, namely b2636da
