### ISSUE TITLE
Improve the course approval user interface

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4561]
### Current Behavior:
When Wiki Education staff review and approve a submitted course, they must:

* Click 'Edit Details'
* Add the program manager in the staff role
* Add the wiki expert in the staff role
* (sometimes) Add additional tags to the course
* Select the campaign corresponding to the current or upcoming term and add it to the course

### Desired Behavior:

Instead of these separate steps (and process that isn't explicit in the UI), when a course is submitted there should be a single dedicated interface for an admin to efficiently do all the steps of course approval.

**Comment by ragesoss** [comment]
It should be easy within this approval workflow to add additional campaigns as well. There should probably be a default campaign, which is the upcoming campaign as defined by the "recruiting term" setting, but we often need to add additional campaigns at the point of approval as well.

**Comment by vaidehi44** [comment]
@ragesoss, can you mention steps to reproduce this? I am not able to get to a point where I can approve submitted courses.

**Comment by vaidehi44** [comment]
Okay. And, how can I login as Admin?

**Comment by vaidehi44** [comment]
This seems interesting to me @ragesoss. Can I work on this?

**Comment by ragesoss** [comment]
@vaidehi44 sure, go for it.

**Comment by vaidehi44** [comment]
Hey @ragesoss. A few questions after looking at the present UI (haven't actually seen the code yet) -

- After clicking on 'View Course Page' the wiki education staff reviewer gets the same interface as it is when some instructor creates a course. This gives the reviewer ability to even edit the course page. Is this deliberately done? If not, then I think first step would be to present the course details in such a way that the reviewer can only read/review it and not edit. Then, we should have a separate section which the reviewer easily identifies as their area of adding program manager, wiki expert, etc.
- Who is the program manager? How does the wiki education staff identify them?

**Comment by ragesoss** [comment]
The program manager is typically also the person who is reviewing a submitted course page (Helaine — https://wikiedu.org/about-us). Within the Dashboard, they are identified by having the `classroom_program_manager` Special User role (via /settings). The review sometimes needs to make edits to a course before approving it, and in general, an admin should be able to edit a course no matter what state it's in with respect to approval. But I think a separate section — perhaps an extra component that shows up at the top, with a form for submitting all the approval-related updates at once — would make sense.

**Comment by vaidehi44** [comment]
Okay. Will work on the new section then and let you know.

**Comment by vaidehi44** [comment]
Hi @ragesoss, I was thinking to implement something like this -

![image](https://user-images.githubusercontent.com/56690165/160231646-c4d6a25b-1668-4a82-8528-b8141dde5d4b.png)

However, I think, for this to work correctly, i.e. the users for `Program Manager` and `Wiki Expert` are different, we will have to explicitly define separate roles in the database too. I don't think this should be done though, and the current role of `WIKI_ED_STAFF_ROLE` should include both these roles . Want to know your opinion.

**Comment by vaidehi44** [comment]
Actually, here my intention was to make it clear to the reviewers what people(program manager and wiki expert) they are adding to the staff role. Hence, I also have this doubt, whether `Program Manager` and `Wiki Expert` are the only two sub-roles in `staff` or there can be more people joining?

**Comment by ragesoss** [comment]
Thanks for the update and illustration, @vaidehi44!

The main goal for this is to simplify the workflow for the admin who is reviewing and approving the course. A simpler workflow would be something like this:

1. the program manager clicks an 'approve course' button, which opens a form
2. the form only lets you add one program manager and one wiki expert, and the choice of which user to add is in a dropdown select, with a user selected by default for each of these.
3. the form lets you add only one campaign as well. Ideally, the default selected campaign is inferred from the course dates, so (if such a campaign exists) a course that starts in January 2023 will default to `spring_2023` term.
4. The form lets add additional tags
5. The button to submit the form says something like 'Approve for Spring 2023' (or whatever the campaign is)

In this workflow, the simplest approval workflow would be just two clicks: one button click to open the form, and then the essential parts all have default values (program manager, wiki expert, campaign), so you can just click 'Approve for term' to submit it and add all those roles.

**Comment by ragesoss** [comment]
The people to populate in the 'program manager' and 'wiki expert' roles come from `SpecialUsers.classroom_program_manager` and `SpecialUsers.wikipedia_experts` on the server (which can be set from /settings if you are a super-admin).

**Comment by vaidehi44** [comment]
Thank you @ragesoss for the detailed description of what is expected. This sounds cool. Will approach it accordingly.
