### ISSUE TITLE
figures that aren't full-width are styled awkwardly

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#457]
If an image is intended to take up the whole row, but it's not actually wide enough, then it gets left-aligned within the full-width figure box.

It would be better if we could center such images — and center-align the captions — and have the size of the figure border only be as wide as it needs to be to pad the image.
![image alignment](https://cloud.githubusercontent.com/assets/848483/11044088/b88668ac-86d4-11e5-8f3d-e6e64224005e.png)

**Comment by thenickcox** [comment]
@ragesoss This is closed via f87b330, but in order for it two work, the markdown requires two hard returns after the `<figure>` element (see the diff), or the text below it won't be wrapped in a `<p>` element, and will be center aligned. :thumbsup:

**Comment by ragesoss** [comment]
@thenickcox great! I found markdown also doesn't render the formatting after the `<figure>` element anyway, so I added double empty lines after all the images already.
