### ISSUE TITLE
Many views don't work for users with usernames that include certain characters

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4604]
### What is happening?
Wikipedia users can have usernames ending in `?` or `%`. For example:
* https://en.wikipedia.org/wiki/User:CaesSion%3F
* https://en.wikipedia.org/wiki/User:Wikster808%

(It might be a general problem with any account that includes these characters.)

If such a user is added to a course, clicking their username from the 'Students' tab does not load the details view for the user, and manually constructing such a URL (eg, `http://localhost:3000/courses/test/test_long_course_(test)/students/articles/CaesSion%3F`) does not work either.

The JSON calls from the user profile page (eg, `http://localhost:3000/users/CaesSion%3F`) also result in errors, likely because the user record is not found (probably because it hasn't been converted out of URL encoding).

### To Reproduce

1. Create a course
2. Add `CaesSion?` as a student
3. Use the students page and the user profile page

### Expected behavior

Usernames with a question mark should work the same way as any other username.

### Screenshots

![select student](https://user-images.githubusercontent.com/848483/133154568-a256998f-0d08-475a-8cb3-00e69ce63ca0.png)

![user profile](https://user-images.githubusercontent.com/848483/133154573-83590d43-a913-4542-958f-5f25550a4c0c.png)

**Comment by ragesoss** [comment]
I've done a partial fix, covering most of the problems with usernames like `Wikster808%`, but not `CaesSion?`.

For `Wikster808%`, navigating directly to the student articles view still doesn't work, but clicking the username from the students list does.

**Comment by ragesoss** [comment]
With the latest change, I think this is probably still a problem for a few other restricted characters. See the commit message for https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/772a2619b724b36e35bad12852ceb2df20d84b5d

**Comment by KhanFiza896** [comment]
@ragesoss can i work on this?

**Comment by ragesoss** [comment]
@KhanFiza896 yes, but I only recommend working on it if you are pretty comfortable with React. I think fixing it will require migration to a newer version of react-router.

**Comment by ragesoss** [comment]
I think this is as fixed as it's going to get now that we've upgraded React Router in #4869. `Wikster808%` now works everywhere, including direct navigation to a student articles page, and links/navigation work properly for `CaesSion?`. Loading a page directly via URL still doesn't work if `CaesSion?` is in the URL rather than `CaesSion%3F`, but that's probably a fundamental limitation (and is also the case with Wikipedia URLs) because the question mark marks the start of URL params.
