### ISSUE TITLE
Milestones component doesn't always number weeks the same way as Timeline

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4621]
### What is happening?
The Timeline for a course lists all the Weeks for the course, and also accounts for weeks where the course is not meeting and weeks before the start of the Wikipedia assignment. For example, a Timeline might start with Week 2 (because the course `timeline_start` is a week after the course `start`, and then have an empty vacation week, following by Week 4, even though there are only two Week records for the course.

The Timeline component handles all of this correctly. However, the Milestones component used on the Overview tab does not account for empty vacation weeks, so the week numbering for where the Milestone blocks occur can be different from the week numbering on the Timeline.

### To Reproduce

1. Create course with a timeline, add time between the course start and the timeline start, and set the meeting days so that there is a week with no meetings at some point after the timeline start.
2. Add a few Milestone blocks throughout the timeline.
3. Look at the week numbering on the Timeline tab vs. the Milestones component of the Overview tab.

### Expected behavior
All the week labels should match between tabs.

### Additional context
The right way to fix this is probably to create a canonical representation of the timeline — including the dates, week labels and empty weeks — outside of the individual components that process the timeline. This probably means implementing a selector that combines `course` and `weeks` data using the same approach currently found in the `timeline.jsx` component. Then this selector can be used in both the Timeline and Milestones components.

**Comment by subhangi2731** [comment]
hello i am an outreachy applicant. I am interested to contribute. can u please guide me here and can I take up this issue

**Comment by ragesoss** [comment]
@subhangi2731 yes, you can work on this. It's at the more complex end of the ones I've marked newcomer friendly, as it involves a refactor of multiple components and the use of Redux and selectors.

**Comment by ragesoss** [comment]
@subhangi2731 have you reproduced the problem locally yet?

**Comment by vaidehi44** [comment]
@ragesoss, I was able to reproduce this bug. Can I work on it?

**Comment by ragesoss** [comment]
yes, go for it.

**Comment by vaidehi44** [comment]
Hi @ragesoss, I got the reason why this is happening. I want to know what you mean by 'selector' in the description of issue.

**Comment by vaidehi44** [comment]
> Hi @ragesoss, I got the reason why this is happening. I want to know what you mean by 'selector' in the description of issue.

Okay, I found the selectors folder which lists all the selectors. So, got an idea of implementing it.

**Comment by vaidehi44** [comment]
Hey @ragesoss. I have a opened a PR. Please have a look.

**Comment by vaidehi44** [comment]
@ragesoss, shouldn't this be closed now?

**Comment by ragesoss** [comment]
Yes!
