### ISSUE TITLE
Upgrade to webpack version 5

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4633]
We're using webpack 4 currently. The changes for webpack 5 are relatively minor, but not trivial, and we might have some dependencies on abandoned packages that don't play nicely with version 5.

**Comment by aaditya9899** [comment]
can i work on this?

**Comment by Biki-das** [comment]
will be happy to pull this out.

**Comment by ragesoss** [comment]
Ruby is very easy to learn as you go, especially if you're familiar with JavaScript. Biggest tip is just, whenever you get stuck or confused about something in Ruby, ask!

**Comment by TheTrio** [comment]
This can be closed now.
