### ISSUE TITLE
content on assessment slide is center-aligned

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#464]
@thenickcox 

![centered text on assessment](https://cloud.githubusercontent.com/assets/848483/11072233/ca7d5064-8799-11e5-851d-fccaffad3952.png)

**Comment by thenickcox** [comment]
If I fix this, it'll left align the YouTube videos. It has to do with the `display: table` in the CSS, which we added to support the various image layouts. If you want to center align the YouTube videos, we can add a class for that that you can add via HTML in the markdown.

**Comment by ragesoss** [comment]
@thenickcox That solution works for me.

**Comment by thenickcox** [comment]
@ragesoss Meaning you want the YouTube class?

**Comment by ragesoss** [comment]
@thenickcox yeah, a YouTube class or 100% wide; anything like that is fine with me.

**Comment by thenickcox** [comment]
Closed via a combination of 7b47e8f and 6fadc5c
