### ISSUE TITLE
Improve UX for Article Scoped Programs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4658]
It should be intuitive to set up a program that will track a specific scope of articles, using one or more of the scoping methods already available (assignments, categories, templates, PetScan, PagePile).

The user interface should explicitly note the methods for scoping a course at the point of choosing the program type, it should guide users who have created an ArticleScopedProgram that doesn't have any in-scope articles yet on how to set up the desired scoping, and it should make the current scoping settings more obvious (eg, as part of the Home tab) when viewing such a program.

**Comment by vaidehi44** [comment]
Hi @ragesoss. I was just going through this issue. It seems that new, enhanced UX for `Article Scoped Program` has not been implemented at all. It looks similar to other types of programs when we are creating a program. Am I right?

**Comment by ragesoss** [comment]
@vaidehi44 that's correct, there is almost nothing related to this issue that has been implemented so far.
