### ISSUE TITLE
Add Alerts for "de-userfying" edits

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4677]
When new users move a sandbox into mainspace on Wikipedia, the edits are automatically tagged `de-userfying`. Here's a recent changes feed of such edits on English Wikipedia: https://en.wikipedia.org/w/index.php?hidebots=1&hidecategorization=1&hideWikibase=1&tagfilter=de-userfying&limit=500&days=30&title=Special:RecentChanges&urlversion=2

The Wiki Education version of the Dashboard should monitor recent de-userfying edits, match the usernames to users in current Courses, and generate Alerts that send email to Wiki Expert (aka content expert) for the course.

### Related Files & Code:

This is similar to other feeds that we monitor and generate alerts for via `UpdateCycleAlertGenerator`, and should follow the pattern the other alert manager or monitor files.

The outline for completing this is something like:

* build an equivalent API query that returns a feed of edits tagged `de-userfying`.
* turn that query into a call to `WikiApi`
* build a monitor class that uses that query to generate a set of recent de-userfying edits (including the username, article, and revision id for each one)
* write an ActiveRecord query to get all the usernames of students in current Courses.
* filter the edits list to find any edits made by the Users in current Courses.
* for each of the matched edits, create a new Alert and send the email for that Alert, unless an Alert for that user/article/course combination already exists.
* write tests that verify the monitor works as expected.

**Comment by cyrillefr** [comment]
Hello @ragesoss, can i work on this one ?

**Comment by ragesoss** [comment]
@cyrillefr sure! let me know if you have any questions.

**Comment by cyrillefr** [comment]
Hello @ragesoss , I am almost done.
Though, I do not know how to link the article title I get from the api call with a model/table.
In my dev environment, I have assigned a student to a wikipedia article, hoping to populate the courses_users.assigned_article_title field to get a match, but it did not change.
I have a new line in Assignment and Article though.
Which model/join should I use to match the article title ?

**Comment by ragesoss** [comment]
Hmm... without seeing your code, I'm not sure exactly what you're trying to do. If you open a work-in-progress PR, I can take a look.

I don't think `Assignment` will need to be part this feature. `Article#title` is a relevant attribute for matching titles you get from the API, although I think in some cases, the Dashboard won't yet have an `Article` record that corresponds to the newly de-userfied page.

**Comment by cyrillefr** [comment]
Hello @ragesoss ,
I just opened a [WIP] PR.
I have a create_alerts method that try to get the correct matches user/article/course/revision from the API and the DB.
Not sure if this is correct.
