### ISSUE TITLE
Filter settings in Articles Edited view of course page should be reflected in URL

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4685]
The Articles Edited list can be filtered by wiki, new vs existing article, and tracked vs untracked.

It would be useful if these filter settings (if not default) were reflected in URL parameters, so that users could share a link to the exact filtered view they see. (ie, https://commons.wikimedia.org/wiki/File:Screenshot_Programs_Events_Dashboard.png)

See https://meta.wikimedia.org/w/index.php?title=Talk:Programs_%26_Events_Dashboard&oldid=22391543#adding_unique_URL_for_each_view_in_statistics

**Comment by TheTrio** [comment]
Was thinking about trying this. How should I import the articles data so I could try this out locally? Is [this](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/user_roles.md#copy-a-course-from-production) enough?

**Comment by ragesoss** [comment]
Yes, that is probably a good way to do it.
