### ISSUE TITLE
Generate an Alert when a WikiProject Medicine article is assigned for a course that doesn't have the medical content training module

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4693]
Most existing articles that relate to medicine — and which fall under the strict sourcing rules covered in [this training module](https://dashboard.wikiedu.org/training/students/editing-medical-topics) — have the WikiProject Medicine banner template on their talk page. In `wiki_education` mode only, we should generate an alert whenever one of these articles is assigned — but only if the course does not have the medical topics training module assigned.

The point is to catch cases where a class that wasn't expected to work on medical topics tries to do so, so that we can point them to the relevant training module or intervene some other way.

## Related Files & Code:

This is similar to other feeds that we monitor and generate alerts for via `UpdateCycleAlertGenerator`, and should follow the pattern the other alert manager or monitor files. `HighQualityArticleMonitor` is probably the most relevant one, as it does something very similar.

**Comment by cyrillefr** [comment]
Hello @ragesoss, may I work on this one ?

**Comment by ragesoss** [comment]
@cyrillefr yes! I was hoping you might take this one on.

**Comment by cyrillefr** [comment]
Hi @ragesoss , I cannot find the way to assign a training module to a course.(wiki_education mode on and off, my perm is 1(admin)).

**Comment by ragesoss** [comment]
To add a training module:

* Go to the Timeline tab of a course. If it doesn't have a Timeline tab, enable the timeline via Edit Details on the Home tab.
* Add a Week to the Timeline, then add a Block, and from the Block, select a training module. Then save it.
* If there are no training modules available to select, you need to load them. Make sure `wiki_education: 'true'` is set in `application.yml`, then visit `/reload_trainings?module=all`.

Alternatively, if you are already in `wiki_education` mode, when you create a new course, you'll be taken through the assignment wizard. Choose the 'research and write articles' path, and at the end it will generate a timeline automatically that includes many training modules (possibly including the medical topics module, depending on your choices in the assignment wizard).

**Comment by cyrillefr** [comment]
Thank you. Regarding training modules, which I had not, I did TrainingBase.reload_all in the console. In both mode, guess I have them all by now(that was before your post). But I have the one about medical articles editing.
