### ISSUE TITLE
Training system does not handle undefined due dates well

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#470]
@thenickcox 

For most timelines, there is no defined due date for an assignment block. (The interface, by default, lists the assignment as due 'in 1 week' or something similar.)

The training system does not use the timeline / calculated week dates to infer a default due date when there is not one specified.

**Comment by thenickcox** [comment]
Why are we allowing undefined due dates?

**Comment by ragesoss** [comment]
@thenickcox Because by default, the entire timeline is based on relative dates.

If we wanted to change that, we would need to calculate default dates based on the course start/end dates, blackout dates, and timeline weeks — which logic lives mainly on the frontend at this point — and save a default due date when one is not explicitly specified.

The problem comes in, though, when users change the start/end dates of the course or add new weeks or move blocks. We'd need to account for that and shift due dates on the fly. Currently, explicit due dates are only used when an instructor has a really clear idea of their timeline and they are trying to make the dashboard reflect that, so they want to start an assignment at one point, but have it due at a specific time.

My guess is that handling empty due dates on the frontend for the training (just as we already do for non-training assignments) will be the path of least resistance. But if you've got a great idea for handling due dates in a way that won't force users to manually change them (or have nonsensical ones) when timelines get shifted...

**Comment by thenickcox** [comment]
Shouldn't those due dates get created with the timeline, then updated when an associated model (e.g., the course start/end dates) change?

**Comment by ragesoss** [comment]
Maybe. There are a lot of moving parts, though. Course start/end dates can change, and blocks can also get moved from place to place in the timeline.

**Comment by thenickcox** [comment]
Where can I see an example of an "inferred" due date?

**Comment by ragesoss** [comment]
All the due dates that come out of the wizard, by default. Here's a live example where some of the due dates are specified, and some inferred. The inferred ones say "due next week".

https://dashboard.wikiedu.org/courses/Xavier_University_of_Louisiana/Black_Politics_%28Fall_2015%29/timeline

**Comment by thenickcox** [comment]
Right. So that says "due next week" on an assignment for the week of 9/13. There's not really a ton of value there. But if you want it to say "due next week" if the block is gradeable with no due date, I can make that happen.

**Comment by ragesoss** [comment]
@thenickcox No, not hugely valuable. What we really need to happen for the training is to have the dashboard also track 'almost due' and 'overdue' status for those. It was less important previously, but now that the system also has knowledge of what the assignment is and whether it's been completed, we need to handle that situation a little more robustly.

So maybe we do need to save default due dates, calculated initially from the (derived) week dates.

**Comment by thenickcox** [comment]
Then just punt on handling if course start/end dates change?

**Comment by ragesoss** [comment]
Yeah, I'm okay with punting in the short term, although it's a moderately high priority to get it working by the new year. Maybe a solution for that will emerge — or become necessary — out of the Timeline UX work.

**Comment by thenickcox** [comment]
Gotcha. So when would a module become "overdue" in this new system?

**Comment by ragesoss** [comment]
Overdue the first day of the week *after* the following week, I guess.

**Comment by thenickcox** [comment]
Well, this affects what I'm currently working on, which is the number of "Student Editors" with up-to-date training. Let me think about the implications of this change a bit more.

**Comment by thenickcox** [comment]
Closed via 2c3f8664b3fc7d5968943c398a53a45f4f505d39, I hope.
