### ISSUE TITLE
Translations missing on dashboard-testing for Course Activity table

### ISSUE THREAD

**Issue by bmathews** [WikiEducationFoundation/WikiEduDashboard#471]
https://dashboard-testing.wikiedu.org/courses/University_of_North_Carolina,_Chapel_Hill/CCO_History_140_-_The_World_Since_1945_(Summer_2015)/activity

![image](https://cloud.githubusercontent.com/assets/848347/11108239/116342e4-889a-11e5-9090-86ee5a857e07.png)

**Comment by ragesoss** [comment]
Whoops. I missed that when I merged https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/4e0181284bc59bfa187badd49c93b53bb3620d40

It looks like it's just that revision.foo needs to become revisions.foo in ` app/assets/javascripts/components/revisions/revision_list.cjsx`
