### ISSUE TITLE
ArticleViewer tries to get data from wikis where WikiWho data isn't available

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4716]
For example, a French Wikipedia article listed on the Dashboard still tries to fetch WikiWho data for authorship highlighting, even though French isn't one of the languages that WikiWho supports. (Hopefully, we'll add support for more languages at some point, but meanwhile the Dashboard should be aware of which languages do have support and which don't, and reflect this in the UI.)

**Comment by Florence-Njeri** [comment]
Hi @ragesoss , can I pick this task?

**Comment by ragesoss** [comment]
@Florence-Njeri yes, go for it.

**Comment by ragesoss** [comment]
Hi @Florence-Njeri! Are you still working on this? Let us know if you have any questions.

**Comment by marklocklear** [comment]
Spent some time trying to understand this issue. I found `fetchParsedArticle()` in `app/assets/javascripts/components/common/ArticleViewer/containers/ArticleViewer.jsx` and also `const supported = ['de', 'en', 'es', 'eu', 'tr'];` in `isWhocolorLang()` in this same file. Is this in the ballpark @ragesoss ?

**Comment by ragesoss** [comment]
@marklocklear yes, it sounds like you're on the right track.

**Comment by cyrillefr** [comment]
Hello @ragesoss , I have been playing a bit with this issue.

When displaying an article in French, I cannot see any sign of bug in the browser console (obviously no lines appear highlighted).
Furthermore, when looking in the network, I see a call to /en/whocolor/... for an article in English, but no such call for the one in french (which seems good to me).
What am i missing here? 
(Should articles that cannot be highlighted be excluded ?)

**Comment by ragesoss** [comment]
hmm... I think I was mistaken, and this bug doesn't exist. I remember filing this bug, and I think I had noticed some kind of behavior like it describes, but there's code that was already there when I filed it that works to prevent making such useless requests. Sorry about that!
