### ISSUE TITLE
permissions problems in the cache directory may crash the dashboard upon deployment

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#472]
This happened when we first deployed the training branch to staging, and again the other day on staging when we were debugging fixes for the course_creator gray screen bug.

**Comment by thenickcox** [comment]
I agree this is serious, but we'll have to see if it happens again. Right now, both production and staging share the `cache` directory, and since it's owned by root and is 777, we should be good:

```
root@dashboard:/var/www/dashboard/shared/tmp# ls -al
total 16
drwxr-xr-x 3 root root 4096 Nov 13 14:30 .
drwxr-xr-x 7 root root 4096 Aug 12 13:46 ..
-rw-r--r-- 1 root root    6 Nov 13 14:30 batch_update_constantly.pid
drwxrwxrwx 2 root root 4096 Sep 16 12:08 cache
-rw-r--r-- 1 root root    0 Nov  2 12:46 restart.txt
```

**Comment by ragesoss** [comment]
They shouldn't share the same cache directory. On staging, it's under `/var/www/dashboard-testing/`. Which is why I expect this to happen on production when we deploy.

Is the 777 permission on the cache directory a security problem? The problem seems to be that user 'nobody' is the one that uses that directory.

**Comment by thenickcox** [comment]
Oh, I misread the symlink:

```
lrwxrwxrwx  1 root root    37 Nov 13 16:10 tmp -> /var/www/dashboard-testing/shared/tmp
```
