### ISSUE TITLE
Configure tests to run on GitHub Actions instead of travis-ci

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4727]
### Current Behavior:
Our CI is configured to run on travis, via `.travis.yml`. However, Travis-CI now has limited support for open source projects, and switching to GitHub Actions is probably going to be a more reliable way to run the tests.

### Desired Behavior:

Add a GitHub Actions config to run the complete test suite.

### Related Files & Code:

Here's an example CI config for a Rails project: https://github.com/diaspora/diaspora/blob/develop/.github/workflows/ci.yml

**Comment by RishiKumarRay** [comment]
I would like to work on this

**Comment by ragesoss** [comment]
@RishiKumarRay please do! Give me a ping if you run into any problems.

**Comment by aaditya9899** [comment]
Hey @ragesoss I too working on this issue and made some progress ....i want to know what this command does to be exact 
`sudo apt-add-repository -y ppa:rael-gc/rvm` ?

**Comment by ragesoss** [comment]
@aaditya9899 that command is only necessary on WSL; it's for installing the right Ruby version. It looks like it gets configured directly via the `ruby` value in ci.yml.

**Comment by aaditya9899** [comment]
hey @ragesoss I have written this much code till now , i know there also some mistakes and few more things to add , could you tell me in brief what i have to do next?
`name: CI

on: [push]

jobs:

  build:

      runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
      os:
          - ubuntu-latest
        ruby:
          - 2.7.1
        
        node-version: [16.x,17.x]
        redis-server:
        mariadb:

          
        db:
          - mysql
          - mariadb
      
      env:
        DB: ${{ matrix.db }}
        RAILS_ENV: test


        services:
        - redis-server
        

      steps:
         if: matrix.os == 'Linux'
      - name: Updating packages
        run: sudo apt-get update
        
      - name: Install dependencies
        run: sudo apt-get install -y redis-server mariadb-server libmariadb-dev rvm nodejs npm pandoc

      - name: Installing Yarn Globally
        run: sudo npm install --global yarn

         - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
          -
            vendor
            node_modules


      - name: Start MySQL
        run: sudo service mysql start

        if: matrix.db == 'mysql'
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v2.7.1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true


          deployment
      - run: mkdir tmp -m 777
      - run: cp config/database.travis.yml config/database.yml
      - run: sudo mysql -e "SET Password=PASSWORD('rootpassword')"
      - run: >-
          sudo mysql -e "CREATE DATABASE test DEFAULT CHARACTER SET utf8 DEFAULT
          COLLATE utf8_general_ci;"
      - run: 'bundle exec rake db:migrate RAILS_ENV=test'
      - run: yarn build
      - run: yarn test
      - run: >-
          COVERAGE=true bundle exec rspec --color --profile --format
          documentation
      - run: bundle exec rubocop
      - run: yarn lint-non-build
      - run: ./travis-deploy-staging.sh

      `

**Comment by ragesoss** [comment]
@aaditya9899 I don't know! I've never done this before.

**Comment by aaditya9899** [comment]
Okay no problem , i do some finish up and test it on another branch👍

**Comment by RishiKumarRay** [comment]
@aaditya9899 Hey aditya, I was too working on this, But I see you have done much of it. So @ragesoss  i leave this issue to him. Let me know if you can't solve this.

**Comment by aaditya9899** [comment]
@RishiKumarRay hey rishi, i had deal with github actions before and that's why i just give it a try, its not done yet  nor completely bug free but sure if i couldn't solve this in a few days , i would hand it over to you. Thankx👍

**Comment by ragesoss** [comment]
Fixed in #4779
