### ISSUE TITLE
Module index has no description for logged out user after clicking Done to complete module

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#473]
* As a logged out user, I go to a training module index page.
* I click Start and proceed to the end.
* I click Done
* I return to the module index, but it does not render the description (only the TOC)
* Hard refresh fixes this.

![no info upon completion](https://cloud.githubusercontent.com/assets/848483/11154609/431785c8-89f5-11e5-91d4-f21774281b0a.png)

**Comment by ragesoss** [comment]
The nav bar is also the same nav bar from the slides. So it looks like it's only re-rendering the react part of that page, but not loading the haml portion until refresh.

**Comment by ragesoss** [comment]
On staging, the behavior currently is that the Done button does not work at all for logged out users.

**Comment by ragesoss** [comment]
This happens for both logged in and logged out users, actually. (And now it happens on staging.)

**Comment by ragesoss** [comment]
@thenickcox ping to make sure you've seen this.

**Comment by thenickcox** [comment]
@ragesoss Yep. Looking into it now.

**Comment by thenickcox** [comment]
@ragesoss FYI, if a quiz is the last slide, you can't currently disable the 'Done' button. You can only disable the 'Next Page' button because it's rendered in a React component. This would be a great place for that conclusion slide you talked about.
