### ISSUE TITLE
"Join course" button in Actions component should not be shown if the EnrollCard is being shown

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4752]
If a user follows an enrollment link (with ?enroll=passcode) to a course page, the EnrollCard component is rendered, letting the user click 'Join' to automatically join the course without entering the passcode manually. However, there is also a 'Join course' button in the Actions section. Users who click the 'Join course' button will be prompted for a passcode, but in most cases will not know that the passcode is embedded in the URL. This is confusing. Removing the 'Join course' button when the EnrollCard is active would likely cut down on confusion and questions from users about how to enroll / what the passcode is.

**Comment by vaidehi44** [comment]
Hey @ragesoss, can I work on this?

**Comment by ragesoss** [comment]
@vaidehi44 yes

**Comment by Ankit-Gupta18** [comment]
Is this issue still open to work or has been resolved?

**Comment by vaidehi44** [comment]
Yeah. @Ankit-Gupta18, am still working on this one.

**Comment by vaidehi44** [comment]
@ragesoss, I have opened a PR(#4754) for this issue. Please have a look.
