### ISSUE TITLE
Unused training code

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#477]
@thenickcox: I've been working on getting test coverage for the last few bits of the Ruby side of the training. I came across a couple bits that appear to be unused.

In TrainingModulesController, there are methods of `by_id` and `for_block`. These have routes, and corresponding methods in the React API and ServerActions. However, it doesn't look like there are any calls to `ServerActions.fetchTrainingModuleById` or `ServerActions.fetchTrainingModuleForBlock`.

Conversely, there's what appears to be an unused component, `CourseTrainingHandler`, that has a call to `ServerActions.fetchTrainingModulesForCourse` — which does not exist, and has no corresponding API, route, or controller methods.

Is this all dead code?

**Comment by ragesoss** [comment]
Also, `TrainingLibrary#modules` does not appear to be used anywhere, and as far as I can tell from playing with it on the command line, it does not work. I always get a NoMethod error at `raw_modules.include?`.

**Comment by thenickcox** [comment]
Yeah. This is a bummer. This is left over from refactoring from Training Modules being a block to them _belonging to_ a block. I'll look into this and make sure this code is safe to delete.

**Comment by thenickcox** [comment]
Closed via 1a19879

**Comment by ragesoss** [comment]
@thenickcox What about the code in training_module.rb and training_modules_controller.rb?

**Comment by ragesoss** [comment]
Also, in api.coffee.

**Comment by thenickcox** [comment]
Good catch. Except that `TrainingModule#find` is still used, so I'm leaving that in.
