### ISSUE TITLE
Pull week meeting moment.js calculation out of TimelineHandler

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#480]
Rationale:

* Through some testing, @bmathews has discovered that moment.js is quite slow. Moving this to the server should improve the performance of `render`, since part of the calculations are done on each call to `render`
* Moving this to the server would add to our test coverage and confidence
* Adding tests to these methods will improve the documentation of what they do and decrease future confusion for all developers
* Taking the calculations out of the component will simplify it greatly (currently, the calculations in the file make up a full 100% of non-React-lifecycle methods)

**All the above are secondary benefits to the primary benefit, which is that moving the blackout week calculation will correct the calculations of due dates for training modules for blocks with no due dates.**

Commit forthcoming.

**Comment by ragesoss** [comment]
+1

**Comment by thenickcox** [comment]
@ragesoss The one benefit to this I realized is that we'll have to refetch the course dates if the user changes any of the course or timeline dates. I don't think we currently do this.

**Comment by thenickcox** [comment]
@ragesoss This does apparently [improve performance](https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/480) of that `render` call. I've also verified that the display is the same. I'd love for you to check out what's on [staging](https://dashboard-testing.wikiedu.org/courses/University_of_North_Carolina_School_of_the_Arts/History_of_Musical_Styles_I_and_II_(Fall_2015,_Spring_2016)/timeline) and what's on [prod](https://dashboard.wikiedu.org/courses/University_of_North_Carolina_School_of_the_Arts/History_of_Musical_Styles_I_and_II_(Fall_2015,_Spring_2016)/timeline) for the same course. If they look identical, this is good to go.
