### ISSUE TITLE
In Articles Edited view, filter settings don't match UI after navigating away and back

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4805]
### What is happening?
The Articles Edited view on a course page — eg, https://dashboard.wikiedu.org/courses/Brigham_Young_University/The_United_States_Since_1877_(Winter_2021)/articles/edited — lets you filter the list. (There are up to three filter parameters, but just one in that example.) If you change one of the default settings (for example, filter the example to only show `New` articles), then you navigate to a different tab of the course, then back to the Articles tab, the filter selector shows the default filter values (`New and existing`) even though the list is still filtered with the previously-set parameters (`New`).

### Expected behavior
When you navigate away and then return to the Articles tab, the filter selectors should reflect the currently-active filters.

### Additional context
This probably needs to be solved by pushing more state into Redux.

**Comment by TheTrio** [comment]
Am working on this.
