### ISSUE TITLE
npm install is broken

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#483]
Since yesterday, `npm install` fails, and all our travis builds error. I think this is because of our dependency on https://github.com/ntdb/react-datepicker

It looks like @ntdb synced that repo with upstream (which had merged his patches a while ago), and now there are broken dependencies.

**Comment by ntdb** [comment]
Sorry about that! Updating the dependency to `"react-datepicker": "0.12.0"` will be the quickest fix.

**Comment by thenickcox** [comment]
@ntdb It's our fault for not picking a specific version!

**Comment by thenickcox** [comment]
closed via dc9793f

**Comment by ragesoss** [comment]
npm install doesn't error, but we still have problems.

**Comment by ragesoss** [comment]
Well, that was not fun.
