### ISSUE TITLE
Order of libraries on /training is not deterministic

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#487]
Sometimes the Instructor library is on the left, sometimes the student library is. I assume it depends on the order in which the libraries get loaded when Rails initializes.

**Comment by thenickcox** [comment]
What _should_ the order be?

**Comment by ragesoss** [comment]
Instructor, Student.

**Comment by thenickcox** [comment]
@ragesoss I've never seen them load out of order, so I can't _totally_ confirm, but this _should_ fix it.
