### ISSUE TITLE
Unexpected line breaks in quiz questions

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#488]
The lines for short questions break when they should not. (This appears to be related to the 'float' property, but removing that float results in the wrapping for longer questions not aligning properly.)

![bad wrapping of quiz questions](https://cloud.githubusercontent.com/assets/848483/11348027/eaab6b52-91d8-11e5-9c53-078e143d42d9.png)

**Comment by ragesoss** [comment]
I'm guessing that the same thing is responsible for this.
![true false](https://cloud.githubusercontent.com/assets/848483/11514081/84ec1d76-982b-11e5-8960-c791f35c090e.png)

@thenickcox @bmathews could one of you poke at this when you get a chance?

**Comment by thenickcox** [comment]
@ragesoss Unfortunately, this is a symptom of the accommodation of different layouts and images, etc. We may have to rethink that.
