### ISSUE TITLE
Unable to login to wikipedia on dev machine

### ISSUE THREAD

**Issue by marklocklear** [WikiEducationFoundation/WikiEduDashboard#4908]
### What is happening?
After starting the rails server and browsing to localhost:3000 I click the "Log In with Wikipedia" link and get the message:

Login Error
It looks like there was an problem with the sign in process. (Sorry about that! It happens occasionally.) Please try logging in or enrolling again.

In the console I see:
[2022-04-06 15:22:11.794 INFO ] Started POST "/users/auth/mediawiki" for 10.0.2.2 at 2022-04-06 15:22:11 +0000
D, [2022-04-06T15:22:12.076456 #8387] DEBUG -- omniauth: (mediawiki) Request phase initiated.
E, [2022-04-06T15:22:12.078790 #8387] ERROR -- omniauth: (mediawiki) Authentication failure! Failed to open TCP connection to .wikipedia.org:443 (getaddrinfo: Name or service not known): SocketError, Failed to open TCP connection to .wikipedia.org:443 (getaddrinfo: Name or service not known)
[2022-04-06 15:22:12.114 INFO ] Processing by OmniauthCallbacksController#failure as HTML

This is a vagrant box so possibly some issue with ssh ports being forarded

### To Reproduce
See above

### Expected behavior
Should be able to authenticate via Wikipedia

### System Information
Vagrant box
 - OS: Ubuntu 21.x
 - Browser: Chrome

### Additional context
NA

**Comment by marklocklear** [comment]
The environment variables in config/initializers/devise.rb all appear to be nil. Specifically ENV['wikipedia_token'], ENV['wikipedia_secret'] and ENV['wiki_language']. Could this be the issue and how should these be set?

**Comment by marklocklear** [comment]
Renamed config/application.example.yml to config/application.yml and this resolved the issue.

**Comment by ragesoss** [comment]
Yes, copying the example config to `application.yml` is the intended way to get those credentials in a dev environment. (You want to copy rather than move to avoid accidentally committing a change that removes the example file.)

**Comment by marklocklear** [comment]
@ragesoss thanks! Good call on copying vs. renaming 🙏
