### ISSUE TITLE
Create a way for admins to copy courses from a production instance of the Dashboard

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4911]
We have a script for copying the core data of one program on a public instance of the Dashboard to another instance: `setup/copy_course_from_production.rb`. However this can only be used manually from a rails console.

A good step forward would be to add a controller and very simple frontend for this functionality, so that it's really easy for a developer to copy a course from production for testing.

This will also require a thorough refactor of the script into something that looks more like one of the `app/services` files, along with comprehensive tests for the controller and service.

One bug to fix and test for is the conversion of the course `flags` has. We use integer keys within the `update_logs` portion of the flags, but these get converted into strings when the go through JSON. (And then, this causes an error if you run an update on the same course.)

**Comment by anirudh-t-d** [comment]
Hi @ragesoss I would like to start working on this. But I am new to this, so it might take me a bit of time.

**Comment by enelesmai** [comment]
Hello @ragesoss do you think I can work on this issue? Or should I take another one? I'm an applicant for outreachy program

**Comment by enelesmai** [comment]
> Hi @ragesoss I would like to start working on this. But I am new to this, so it might take me a bit of time.

Sorry I didn't saw your message and started to work on it, but we can collaborate and work in the same branch if you want. Maybe I can guide you :)

**Comment by enelesmai** [comment]
> > Hi @ragesoss I would like to start working on this. But I am new to this, so it might take me a bit of time.
> 
> I'm sorry @anirudh-t-d I didn't saw your message before and started to work on it, but we can collaborate and work in the same branch if you want. Maybe I can guide you :)

**Comment by anirudh-t-d** [comment]
It's ok @enelesmai I couldn't start to work on it as I had to take care of my Mum. You can work on it. I hope things will get better by tomorrow and work on another issue. And @ragesoss can you please add me to the slack channel?

**Comment by Kingstalux** [comment]
Hello @ragesoss , since this issue has not yet been resolved can I start working on it too?

**Comment by marklocklear** [comment]
In case others stumble across this and its not clear, there is a PR addressing this issue here https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/4914

**Comment by gabina** [comment]
Can I work on this? I see there is already a (closed) PR for this, maybe I can take it as a guide.

**Comment by ragesoss** [comment]
Go for it!
