### ISSUE TITLE
Update article_finder_actions.js and related files with accurate variable names

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4916]
I noticed while reviewing #4905 that in `article_finder_actions.js` and related files that use it, `fetchKeywordResults` and some other functions take a `home_wiki` parameter. However, wiki object passed to it are not necessarily the home wiki for a course. The variable names are misleading, and this code will be easier to understand and modify if variable and prop names are updated where appropriate. `home_wiki` should only be used in situations where it actually is the home_wiki property of a course. Otherwise, `wiki` will be more general and accurate.

**Comment by anirudh-t-d** [comment]
@ragesoss I would like to work on this
