### ISSUE TITLE
Add 'News' feature to the Dashboard

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4933]
### Current Behavior:

Currently, there's no good way to keep users informed of recent changes and other important news/information related to the Dashboard. We occasionally use the `sitenotice` feature to add a banner about particularly important announcements, but this shows up on every page all the time and cannot be dismissed, so it's not suitable for something like "Zoom office hours for Dashboard users will happen on such-and-such date" (except for in the few days immediately before).

The closest alternative is to post on the News section of the Meta page: https://meta.wikimedia.org/wiki/Programs_%26_Events_Dashboard#News_and_recent_changes

However, that isn't easy to follow or discover. 

### Desired Behavior:

There should be a News feature in the navbar that lets users quickly see a small feed of recent news items, along with a way for admins to edit the news items. Ideally, it might also show highlighting when the news has been updated recently, so that it's easy to discover a new update.

### Related Files & Code:

One possible way to build this would be to make the news content come from a special FAQ record, so that the editing/updating part of it is basically free since we've already implemented the FAQ system that can be edited by admins.

Another possibility would be to build it on top of the training module system, where the news content is basically a special TrainingSlide with content — and translations — pulled from Meta.

**Comment by vaidehi44** [comment]
For this feature, I guess a simple pop up kind of thing, like the one which exists for `Get Help` button, would be enough, @ragesoss ?

**Comment by ragesoss** [comment]
Yes, something like that might work well... although layout would probably be a little different, to flexibly accommodate a lot or a little text. The admin notification bell might also be a good pattern to follow, in terms of the non-popped-up state... I think the ideal situation would be to show some kind of subtle indicator for unread news, which would use a cookie (with some kind of hash indicating the version, so that updating the news content would automatically make it re-activate) to remember that a given user has already looked at it.

**Comment by rajat99-default** [comment]
I would like to work on this issue
also I need some guidance on how to do this because this can be my first open source contribution

**Comment by ragesoss** [comment]
@rajat99-default I think the other issue you posted on will be a better first contribution. If you'd like an invite to our slack channel, please let me know your email address.

**Comment by rajat99-default** [comment]
My email is 
rajatsujane6@gmail.com

**Comment by Abishekcs** [comment]
@ragesoss i can work on this issue

**Comment by ragesoss** [comment]
> @ragesoss i can work on this issue

Great!

**Comment by Abishekcs** [comment]
![Screenshot from 2024-02-04 13-16-24](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/2edceacd-4ffa-43d8-aa9d-709b7377a1cf)
![Screenshot from 2024-02-04 13-16-05](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/2075202d-7ce6-43b6-8d15-5b23710b1331)

@ragesoss for the UI will something like this work near the admin notification bell ?

**Comment by ragesoss** [comment]
@Abishekcs this looks great! I assume it will work as follows:
* Only admins will have the controls to add/delete/edit news.
* The notification count will be based on a cookie recording the last time that user opened the news compared with the number of news items with timestamps after that last-opened time? Or maybe something else? In any case, I think that opening the news should make the red number disappear.
* It would be useful to include a link somewhere in the modal that points to a news list outside of the dashboard (perhaps at the bottom of the list). For P&E Dashboard, this would be configured to point to https://meta.wikimedia.org/wiki/Programs_%26_Events_Dashboard#News_and_recent_changes and for Wiki Education Dashboard, it would probably be https://wikiedu.org/blog/

**Comment by ragesoss** [comment]
@Abishekcs yes, the news content will be different. I assume all the content will just be added manually by an admin (typically me) on the respective website.

**Comment by ragesoss** [comment]
This looks great! I will test it out soon.

**Comment by Abishekcs** [comment]
> special FAQ record

@ragesoss, I will open a PR for it soon. There is still some backend work left to do. I have one question: by `special FAQ record,` I hope you mean the exisiting  `faqs` table

**Comment by ragesoss** [comment]
@Abishekcs yes, that's what i must have meant, although I'm not sure how well your design (with an arbitrary number of separate entires with separate timestamps) lines up with the structure of the `faqs` table. I think I was imagining a situation where one specific FAQ entry would get used to provide the content for a simple one-slot news feature, so that you'd just edit that FAQ as if it was any other entry and there would be no new UI needed for editing it.

For what you have designed, I think a Setting record might be more appropriate, as you can have more structure within the `value` hash and you can hard-code the `key` to link it to this feature.

**Comment by Abishekcs** [comment]
> @Abishekcs yes, that's what i must have meant, although I'm not sure how well your design (with an arbitrary number of separate entires with separate timestamps) lines up with the structure of the `faqs` table. I think I was imagining a situation where one specific FAQ entry would get used to provide the content for a simple one-slot news feature, so that you'd just edit that FAQ as if it was any other entry and there would be no new UI needed for editing it.
> 
> For what you have designed, I think a Setting record might be more appropriate, as you can have more structure within the `value` hash and you can hard-code the `key` to link it to this feature.

@ragesoss 

a) In the `faqs record`, I was keeping the` faqs- title` as `"Wiki Education Dashboard News" or "Programs & Event Dashboard News"` to make sure to display the correct `news` according to the respective ` Dashboard`.

b) and `faqs- content`   for storing the news details, respectively and I'm thinking of storing the `titles "Wiki Education Dashboard News" and "Programs & Event Dashboard" ` as ENV.

c) Also, if I use this approach, then I will add some `method`  in the `controller` to check that the news FAQs  don't mix with the other FAQs.

Will this kind of approach work?

![FAQ news](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/f6428644-0a5e-430a-b578-93a2c0188421)

**Comment by Abishekcs** [comment]
> It might work, but how it will handle having more than one entry with separate timestamps, as shown in your design?

@ragesoss 

Hmm😅, I think for more than one entry, it won't have trouble with separate timestamps, as shown in the recording below:

https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/0373bd95-5f20-4928-b5c3-6468289ae6f6


![Screenshot from 2024-02-28 23-26-49](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/64a1dc69-fc97-4ea9-b18f-d9fb52b0bd55)


As for the date format, I am currently using the one from the DB - 2024-02-28T17:09:14.543Z. I plan to change it later

**Comment by Abishekcs** [comment]
@ragesoss, I wasn't able to work on this feature last week, so I wanted to provide a quick update on its status 😁:

a) The front-end is almost done; only formatting of the date is left.

b) The back-end is completed.

c) I implemented the notification count based on a cookie recording the last time the user opened the news, compared with the number of news items with timestamps after that last-opened time (as suggested by you).

d) The notification count is visible and disappears when the user clicks on the new icon, as shown in the recording.

e) The only problem is that the `nav component` doesn't have access to the `Redux store`, which causes an error when navigating to other nav pages like `/admin`. I initially gave access to the `store` only to the `newFeature Component`, which is placed under the `nav component`. (The Error related to this is also in the recording).

f) The only thing left to do is to figure out how to solve the problem mentioned in point (e), which I am currently working on."

https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/1160079e-8b76-4193-a627-4dcbb21fb52e

**Comment by Abishekcs** [comment]
.
