### ISSUE TITLE
Add a way to reach specific training modules and slides via ID numbers

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4940]
For the training system on Programs & Events Dashboard, we use wiki pages on Meta to specify training content that gets imported into the Dashboard's database, including unique IDs as the primary keys. However, there's no way to load a module index or an individual slide by ID, only by slug. Adding a similar redirect functionality to translate a URL with module/slide IDs into a working training URL would be useful.

For context, see https://meta.wikimedia.org/w/index.php?title=User_talk:Sage_(Wiki_Ed)&oldid=23169149#Wikidata_training_modules?

**Comment by sharon-kathambi** [comment]
Hi @ragesoss  Can I work on this one?

**Comment by ragesoss** [comment]
sure, please do.

**Comment by sharon-kathambi** [comment]
Okay, i have a question, you would like the ID of the articles to be stored on the URL as well?

**Comment by ragesoss** [comment]
I'm not sure what you mean.

**Comment by sharon-kathambi** [comment]
In the training modules controller, we find modules by slug.. is the issue supposed to find training modules by ID? because when you click on a training module it redirects you to the specific module...and that's the functionality we want...or what exactly is the issue?

**Comment by ragesoss** [comment]
The idea is, if you know the ID of a training module or slide — because you're editing the source on Meta, eg, slide 10815 https://meta.wikimedia.org/wiki/Training_modules/dashboard/slides/10815-using-a-talk-page — you should be able to use that to reach the slide on the Dashboard. This could be one similarly to the `find_course` route: `/find_training_slide/10815` could redirect to the URL of that slide ( https://outreachdashboard.wmflabs.org/training/editing-wikipedia/editing-basics/using-a-talk-page ). And similarly, `/find_training_module/:id` could do the same thing for finding the index URL for that TrainingModule.

**Comment by gabina** [comment]
Hey @ragesoss, I am an outreachy applicant. I would like to apply for the Wikimedia Project "Improve how Wiki Education Dashboard counts references added".
I was reading the description and the discussion for this issue, and I think it's a good first step to start contributing. WDYT?
I already have my development environment working. Do you mind sending me a Slack invite?

**Comment by ragesoss** [comment]
> Hey @ragesoss, I am an outreachy applicant. I would like to apply for the Wikimedia Project "Improve how Wiki Education Dashboard counts references added". I was reading the description and the discussion for this issue, and I think it's a good first step to start contributing. WDYT? I already have my development environment working. Also, do you mind sending me a Slack invite?

Send me an email so that I know what address to send the Slack invite to.

**Comment by gabina** [comment]
Oh sorry, for some reason I thought my github username was enough. My email address is gabinaluz@gmail.com

**Comment by gabina** [comment]
Hey @ragesoss, I would like to be sure we're on the same page regarding the scope of this issue (especially since the code is new to me).

ATM training modules and individual slides are only reachable by slug.

For example, let's suppose I'm working on a training module with` id=6` and `slug=images-and-media`, belonging to a training library with `id=2` and `slug=students`.
Then, I'm able to reach the training module content using the `/training/students/images-and-media` URL.

We would like to have the ability to reach a training module also by their id.

So, in our example, we should be able to manually write a URL like `/find_training_module/6`, and the web-app should automatically redirect us to `/training/students/images-and-media`. At a high level, that involves, from a training module id, to get the library slug in which the module is, in addition to the slug for the training module itself.

I understand that URLs like `/find_training_module/images-and-media` (searching by training module slug) or `/find_training_module/6-images-and-media` (searching by training module id and slug) should have the same behavior.


We also want to do a similar thing for individual slides.

Does it sound right for you?

**Comment by pppery** [comment]
As the author of this issue, personally I only care that one of the three formats work, not that all of them do. Ragesoss may think differently of course. And nice to see someone working on this 18 months later.

**Comment by ragesoss** [comment]
@gabina that all sounds right to me. Yes, we would want to be able to find individual slides by ID as well.

**Comment by ragesoss** [comment]
> I understand that URLs like `/find_training_module/images-and-media` (searching by training module slug) or `/find_training_module/6-images-and-media` (searching by training module id and slug) should have the same behavior.
> 

I think we only really need to be able to do `/find_training_module/6` and `/find_training_slide/632`.

**Comment by gabina** [comment]
Hey @ragesoss do you mind "approving the workflow" and taking a look at the PR? #5502 
Let me know if I can help clarifying something.

@pppery I uploaded a short video about how the redirect works if you want to double-check it.

**Comment by pppery** [comment]
When will this be deployed? I'm still getting a 404 error going to https://dashboard.wikiedu.org/find_training_slide/13001 for instance.

**Comment by ragesoss** [comment]
I will probably be able to deploy it tomorrow.

**Comment by ragesoss** [comment]
@pppery it's deployed now: https://outreachdashboard.wmflabs.org/find_training_slide/13001

(That slide number does not exist on dashboard.wikiedu.org)

**Comment by gabina** [comment]
Great to see this is already in production! Is there anything I am expected to monitor now that it's deployed?

**Comment by ragesoss** [comment]
> Great to see this is already in production! Is there anything I am expected to monitor now that it's deployed?

Nope! Thanks!

**Comment by pppery** [comment]
Works for me. And apologies for conflating dashboard.wikiedu.org and outreachdashboard.wmflabs.org above. I'm surely not the only person to make that mistake.
