### ISSUE TITLE
Add an easy way to see a student's edits in a particular namespace

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4961]
### Current Behavior:

The Assignments & Articles view of the Students shows a list of recent edits, a list of assigned and other edited articles, and links to a) an on-wiki list of the user's sandboxes, and b) the on-wiki contribution history.

Sometimes, though, instructors want to check for specific kinds of edits, for example, edits to Talk pages to find article critiques that have been posted there.

### Desired Behavior:

The Students tab should make it easy find specific kinds of edits. Maybe could best be done with a filter option for the Revisions list. 

### Notes

The example use case might be ideally be solved through adding the ability for the Dashboard to keep track of where each exercise should be completed and whether or not edits to that page have been made, so that instead of a more generic filter for talk page edits, the instructor could easily find the specific page where the student posted work for that particular exercise.

However, more powerful filtering of revisions (for both the Activity tab and the Students tab) would still be useful as well.

**Comment by vaidehi44** [comment]
@ragesoss, the links which you mentioned - 
>a) an on-wiki list of the user's sandboxes, and b) the on-wiki contribution history. 

Are you referring to these links?

![wikiedu](https://user-images.githubusercontent.com/56690165/168664305-28dd2462-fb58-4e52-b986-4740eedfee02.png)

**Comment by ragesoss** [comment]
Yes, exactly.

**Comment by vaidehi44** [comment]
Okk...I am not getting where the filter option would go. You said to have a filter option for Revision list. Does it mean for the `Revisions` table. 
![image](https://user-images.githubusercontent.com/56690165/168667071-74090bb6-fdc0-4dc0-9a94-dbf86efb0da4.png)

Or, should it filter the results for entire page (the `Assignments & Exericises` tab)?

**Comment by vaidehi44** [comment]
Okay. But that wouldn't affect the above links, right. So, we'll have to add a section, probably a column ,in the table for links corresponding to the filter?

**Comment by ragesoss** [comment]
Something like that. I think the same kind of UI above the table that we use on the Articles tab — for example https://outreachdashboard.wmflabs.org/courses/Wikimedia_Ghana_Entertainment_Community/3Music_Awards/articles/edited?newness=new&tracked=both — would probably work.

**Comment by vaidehi44** [comment]
Okay. And, what kind of filters can we have? One is talk pages. And, you mentioned in the description of having deeper filters by tracking where an exercise should be completed. I am guessing this can be inferred from the assignment which is assigned or which user is working on.

**Comment by ragesoss** [comment]
I think for this issue, the only easy and useful thing to implement would be a namespace filter. That could be used to isolate Talk edits, as well as User (ie, sandbox) edits.

Tracking which exercises have been completed is a more complex problem that take some significant server-side work to prepare for.

**Comment by vaidehi44** [comment]
Got it.
Right now, the Revisions list already shows the edit data for article, user and draft namespace. I guess then talk namespace can simply be added there, instead of a filter on Revisions table. Same for the contribution links too.

Am I getting it right?

**Comment by ragesoss** [comment]
The screenshot you show doesn't actually have any revisions in the table, so it's just the summary.

The actual table (which is shown if you click on that row) has details about individual revisions. See for example https://dashboard.wikiedu.org/courses/University_of_California,_Berkeley/African_Politics_(Spring_2022)/students/articles/Aguerrero427

The idea would be that if you are viewing that table, you could use to the filter to replace the current set of revisions you're seeing with a list that is just in the selected namespace.

**Comment by vaidehi44** [comment]
Okk....And, here the `Date/Time` column and the last column shows the difference in revisions which will then show the edits for filtered namespace, right?

**Comment by ragesoss** [comment]
I think everything about the table itself and how individual Revision rows are rendered would remain the same, it's just that using the filter would load a different set of Revisions to display in the table.

**Comment by vaidehi44** [comment]
So, its just about implementing the filter. Which namespaces should the filter have. Article, User and Talk? Or something else?

**Comment by ragesoss** [comment]
I think those three to start out with would be fine.
