### ISSUE TITLE
When top-line statistics change because of new edits, changes to Articles Edited are not reflected until a page refresh

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4977]
### What is happening?

Course pages automatically poll for updates to the topline course stats by re-fetching course.json once per minute. (See `details.jsx` for the implementation.) This means the 'last updated at, next update expected' text below the main stats — along with the stats themselves — stay up-to-date (for up to 12 hours) without requiring a full page refresh. If one of these updates changes the values of the topline stats (for example, increasing the count of total edits and articles edited), there is also a subtle animation to draw attention to the stats change.

However, even when the topline numbers have changed, indicating (for example) that an additional article has been edited, the list on the Articles tab is not re-fetched, so any newly edited articles will not appear there until a full page refresh.

It would be nice to automatically refetch Articles and Users whenever a refetch of course.json indicates that the counts for either of those has changed.

**Comment by vasconsaurus** [comment]
@ragesoss do you think maybe `useEffect` could be used to solve this?

**Comment by ragesoss** [comment]
Yes, that's probably one way to do it.

**Comment by vasconsaurus** [comment]
If it's ok I'll try to solve this one 🙂

**Comment by ragesoss** [comment]
Fixed with #5228
