### ISSUE TITLE
Add a way for users to trigger a username update for a renamed user

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4978]
### Current Behavior:

If a user gets their account renamed on Wikipedia, the Dashboard does not automatically detect this. That means, after the name change, the Dashboard continues to look for new revisions by the old username.

The username gets updated on the Dashboard if the user logs out (of the Dashboard) and then back in again, because the OAuth login flow for an unknown username includes a step checking whether the same global user ID is already associated with a different (previous) username. See `UserImporter.new_from_username`, and specifically, `.update_username_for_global_id`.

### Desired Behavior:

When an instructor knows that their student has changed usernames, they (or Wiki Education staff) should be able to easily trigger a username update, without needing to pass along instructions to the student to log out and back in again.

I think this could be done via a simple Rails form that allows a user to enter the new username of a user who changed usernames; upon submission, it would do the same thing as the login process, calling `UserImporter.update_username_for_global_id` for that username. The new username would then automatically be reflected on the student's course page, and the Dashboard would resume pulling in new edits for that user during the regular update cycle (along with any edits that were missed since the name change)

Once such a form is live, we can create an FAQ entry to point instructors to it.

**Comment by iLynette** [comment]
Hi @ragesoss I would like to work on this issue. Can I?

**Comment by ragesoss** [comment]
Yes. (Please stick to one issue at a time, though.)

**Comment by iLynette** [comment]
Got it, thank you.)

**Comment by tnwoodard** [comment]
Hi @ragesoss and @iLynette. I'd like to try to fix this issue if it is still open. Thanks!

**Comment by ragesoss** [comment]
@iLynette thanks. please post on slack if you'd like any help with the setup process.

**Comment by tnwoodard** [comment]
Ok I understand. That sounds good. @ragesoss and @iLynette I will check back in a day or so, and if it is still open I'll ask again. Thanks.
