### ISSUE TITLE
IE 11 errors since React upgrade

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#499]
A set of errors that appear limited to IE 11 have appeared since the upgrade to React 0.14.

http://sentry.ragesoss.com:8080/wiki-ed/production/group/1449/

http://sentry.ragesoss.com:8080/wiki-ed/production/group/1450/

http://sentry.ragesoss.com:8080/wiki-ed/production/group/1451/

**Comment by thenickcox** [comment]
Able to duplicate. Looking.
