### ISSUE TITLE
Wikidata revision analysis is not correct for multi-part revisions

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4999]
### What is happening?

We calculate the `www.wikidata.org` stats for a Course by importing the edit summary of each Wikidata edit and parsing it to determine what the edit did (eg, adding a claim, adding a label, etc.).

However, some edits make changes to multiple fields of Wikidata item in one revision. For example, https://www.wikidata.org/w/index.php?title=Q111269579&diff=1596238100&oldid=1596236983

That edit creates a claim (as represented in the edit summary) but it also adds qualifiers and a reference. Only the 'claim created' aspect will be reflected in Dashboard stats, so qualifiers and references will be undercounted.

### Additional context
I think the best solution to this will be to switch from analyzing edit summaries to analyzes diffs between the JSON representations of the Wikidata item (ie, between a given revision and the previous one). That could probably be released as its own library.

**Comment by cyrillefr** [comment]
Hello @ragesoss, 
I would like to work on that one.

Are we talking about these stats ?
`http://localhost:3000/courses/Stanford_Law_School/Advanced_Legal_Research_Winter_2020_(Winter)` (course)
Then click on  `Edits data` or `Common uploads data` or `Revisions data` etc.
Which one is going to be impacted ? On which mode ?

If I Copy a/some course(s) from production ( § "Getting data and switching configurations" from the docs), will that be enough for me to test ?

**Comment by ragesoss** [comment]
@cyrillefr this is one that I'm about to try to recruit an Outreachy intern to work on... I think the ideal way to deal with it will be to write a new Ruby gem for parsing Wikidata JSON diffs, and then publish the gem and use that to fix the issue.

**Comment by ragesoss** [comment]
@cyrillefr this is a related issue that you might like: https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/4283

**Comment by satyadev2** [comment]
@ragesoss 
Hello sir, I'm Satya kushwaha , i have cleared the initial application round of Outreachy intern, I have a strong proficiency in Ruby ,please assign this project to me and let me try to resolve this issue. 
Thank you.

**Comment by ragesoss** [comment]
Hi @satyadev2. This is not a good first issue to tackle; it's going to depend on completing the project I've listed for Outreachy.
