### ISSUE TITLE
Course pages do not show any revisions or sums in student rows

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#50]
This issue seems to have appeared after the recent refactor of course roles, in which we moved role data from Users to CoursesUsers.

**Comment by ragesoss** [comment]
@ntdb I've confirmed what you suggested, that it's part of the update process that temporarily zeroes out the revisions. Specifically, course:update_courses (which simply runs Course.update_all_courses) is where the zeroes get introduced, and the values get restored with cache_update_caches.... spefically, the CoursesUsers.update_all_caches step.

**Comment by ragesoss** [comment]
To narrow it down a bit more... it looks like all the CoursesUsers are being deleted and then re-added (without any cached data) within Course.import_assignments. It's this block of code that deletes them:

          ```unless course.users.empty?
            unenrolled = (existing_flat - new_flat).map { |u| u['id'] }
            course.users.delete(course.users.find(unenrolled))
          end```

**Comment by ragesoss** [comment]
And the reason for that is that existing_flat and new_flat values have different formats for role:

{"id"=>21484356, "role"=>0}
vs
{"id"=>"21484356", "role"=>"student"}

So unenrolled = all the users.

**Comment by ntdb** [comment]
@ragesoss good find and fix. :)

**Comment by ragesoss** [comment]
In the switch of wiki api gems, we switched to fetching integers instead of strings. So that original fix needed to be reverted.
