### ISSUE TITLE
number of available weeks does not get refreshed if user deletes weeks

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#500]
If a user has a full timeline, then deletes all the weeks and relaunches the wizard, they have choices marked unavailable because of insufficient weeks, even though they deleted enough weeks (such as all of them) to make room. Upon manually refreshing the page, the options become available.

**Comment by thenickcox** [comment]
Closed; we're no longer allowing "relaunching the wizard," assuming you mean creating another assignment.
