### ISSUE TITLE
Training slides should scroll to the top on each page load

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#502]
For longer slides, the user may be scrolled down far enough that the top of the page is cut off. If the next slide is also long, then the user needs to scroll up to see the the top content, and is likely to simply start from whatever content is at the top of the screen and miss the actual beginning content of the slide.

This is also potentially something we should address by breaking up long slides, but even so, the system should be able to accommodate long ones.

**Comment by thenickcox** [comment]
@ragesoss This broke the jump links in Safari on the timeline. :confused:

**Comment by ragesoss** [comment]
@thenickcox Can we instead add that same little javascript call to the Next button?

**Comment by ragesoss** [comment]
(I liked how this also resets the scroll when switching between the tabs of a course, but that could go either way.)

**Comment by thenickcox** [comment]
cc @bmathews what do you think?

**Comment by bmathews** [comment]
I think I found a solution (https://github.com/rackt/scroll-behavior), will check it out

**Comment by bmathews** [comment]
Fixed via 84fd29e

**Comment by thenickcox** [comment]
:tada:
