### ISSUE TITLE
Descenders are truncated in onboarding real name field

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#504]
@bmathews 

Also, the bubble selectors are ugly and not necessary. Can we just have button color indicate the selected value?
![descenders](https://cloud.githubusercontent.com/assets/848483/11570876/5b771688-99ae-11e5-84cf-6f7a961925d6.png)

**Comment by ragesoss** [comment]
This got fixed in the 'styleguide' push.

**Comment by bmathews** [comment]
:clap:
