### ISSUE TITLE
When entering 'Edit Details' mode on a Course page, the campaign.json and tag.json lookup requests each happens twice

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5041]
### What is happening?

There appears to be a duplicate request to the `all campaigns` lookup endpoint, which occurs when entering 'Edit Details' mode.

### To Reproduce

1. Load a course page
2. Click 'Edit Details'
3. There are two separate GET requests to the `/lookups/campaign.json` endpoint, as well as two requests to the `lookups/tag.json` endpoint. Similarly, there are two instances each of the `RECEIVE_ALL_TAGS` and `RECEIVE_ALL_CAMPAIGNS` redux actions.

### Expected behavior

Only one hit to each of these endpoints is needed, to fetch the list of all available campaigns and tags that might be added to a course when it's in Edit mode.

I'm not sure what is causing this duplication.

**Comment by vasconsaurus** [comment]
Hi @ragesoss! I was taking a look at this one and I noticed that we fetch the campaigns inside `campaign_actions.js`, but we also have a `GET` for this in our routes.

I commented out the get in our routes, and though it shows an error, it still works. I can edit and save the course.

Could the issue be linked to this?

1. Edit Page
<img width="849" alt="Screen Shot 2022-10-20 at 11 50 04" src="https://user-images.githubusercontent.com/87862340/196983606-0e0bd0f0-dd74-4ca4-be55-89000ecc4fd7.png">

2. Edit the course with an error message
<img width="832" alt="Screen Shot 2022-10-20 at 11 50 20" src="https://user-images.githubusercontent.com/87862340/196983689-d3896f01-1eee-4378-8195-6223cf7ab5d8.png">

3. Edited course is saved
<img width="834" alt="Screen Shot 2022-10-20 at 11 50 43" src="https://user-images.githubusercontent.com/87862340/196983741-65ef3bf3-3eb6-453c-ae8b-c4ab568e1969.png">

4. The gets inside the router
![Screen Shot 2022-10-20 at 11 55 20](https://user-images.githubusercontent.com/87862340/196983824-31e0fc0b-b03b-4b33-a5d4-6333d2bd5dd5.png)

**Comment by ragesoss** [comment]
Hmm... I'm not sure whether that's related or not. Can you post the error details (from the rails server log as well as the browser console, ideally)?

**Comment by vasconsaurus** [comment]
Do these help?

<img width="1624" alt="Screen Shot 2022-10-20 at 20 14 18" src="https://user-images.githubusercontent.com/87862340/197076768-5b08e2db-8d0b-481f-946f-733bfb807725.png">
<img width="1624" alt="Screen Shot 2022-10-20 at 20 15 06" src="https://user-images.githubusercontent.com/87862340/197076795-53102608-8449-4a55-8a51-178d9af91e72.png">
<img width="800" alt="Screen Shot of server log" src="https://user-images.githubusercontent.com/87862340/197076914-35466458-f694-4df3-b2ff-61541bcf0554.png">

They say it's not found, but the page does render, and I'm able to update the details.

**Comment by ragesoss** [comment]
That's unexpected. I can't think of a reason why that `lookups/campaign.json` route would cause a routing error; it works for me locally (even if I delete all the campaigns, in which case it returns an empty array but it's still a 200 rather than a 404).

I'm currently stumped. :-(

**Comment by ragesoss** [comment]
Oh wait... did you comment out those parts in routes.rb? If so, that would explain the errors.

**Comment by vasconsaurus** [comment]
> Oh wait... did you comment out those parts in routes.rb? If so, that would explain the errors.

Yes! 

> I noticed that we fetch the campaigns inside campaign_actions.js, but we also have a GET for this in our routes.

> I commented out the get in our routes, and though it shows an error, it still works. I can edit and save the course.

I don't know if this has to do with anything, but I thought the 2 gets could maybe explain a duplicated request, since they seemed to get the same route 😅

**Comment by vasconsaurus** [comment]
@ragesoss I was wondering why it still worked, even though errors appeared (and the line was commented out)

**Comment by ragesoss** [comment]
It doesn't work. Those two requests get the lists of all campaigns and all
tags in the database, to populate picklists in Edit Details mode. Both will
be empty when the route is disabled.
