### ISSUE TITLE
Create account flow does not work

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#505]
I never actually tested creating a new account until today, with the omniauth signup pathway. It looks like the "returntoquery" needs to be further mangled, because only the first parameter of it comes through, resulting in an error after the user clicks Allow.

**Comment by ragesoss** [comment]
@bmathews I discovered this bug during user testing today, and I believe I've fixed it with an update to my omniauth-mediawiki fork. Please do a 'bundle update omniauth-mediawiki` on your onboarding branch(es) to update to the working version.

**Comment by bmathews** [comment]
Awesome! Will do! Thanks for your work on that.
