### ISSUE TITLE
onboarding welcome message does not use wiki_id

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#506]
@bmathews 

The onboarding flow should greet the user by their wiki_id, not their real name. If they are being onboarded, then we won't know their real name, so it looks like this:

![hi](https://cloud.githubusercontent.com/assets/848483/11576807/3b14160a-99ce-11e5-8ad6-2cdfffa52403.png)

**Comment by bmathews** [comment]
Resolved via 164c3f6
