### ISSUE TITLE
When students go through training very quickly, show a popup emphasizing the importance of the training content

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5069]

**Comment by Chaitanyarai899** [comment]
I can create this feature! I would like to work on this, I hope that's fine.

**Comment by ragesoss** [comment]
@Chaitanyarai899 go for it. I'd prefer to do it without adding a new library.

**Comment by Chaitanyarai899** [comment]
@ragesoss Okay! I'll try my best!

**Comment by ragesoss** [comment]
@Chaitanyarai899 if you'd like to join our slack chat, please email me sage @ wikiedu dot org.

**Comment by Chaitanyarai899** [comment]
@ragesoss Yes! that would be great. Thank you!

**Comment by Chaitanyarai899** [comment]
@ragesoss Hey! It would be great if you could provide some more description about the enhancement.
Basically, I've created an alert which will popup when a student hits the Next Page button(in the training slides) twice in a period of 10 seconds. 
It won't popup every time the student is going through the training slides too fast, but only two times and then stop. Will it be better if the alert pops up only once?
Please check the attached screen recording and tell me the exact requirements.
Thank you very much!
Ps. This is not the final version, I will also style the component by the specifies rules provided and write a better description for the popup. 

https://user-images.githubusercontent.com/95732261/213798655-e02e1539-fa6a-42d6-b025-d6bc90f1403e.mp4

**Comment by vaidehi44** [comment]
Hi @ragesoss . This looks interesting. Was thinking to give a try. Can I go ahead, or @Chaitanyarai899 still working on this one?

**Comment by ragesoss** [comment]
@vaidehi44 Chaitanya is still working on it, trying to iron out the tests.

**Comment by ragesoss** [comment]
See https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5244

**Comment by vaidehi44** [comment]
oh okay!
