### ISSUE TITLE
Dashboard is broken for Safari users since React upgrade

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#508]
@thenickcox @bmathews See also the recent issue for IE 11 since the React upgrade.

There are related issues on sentry; Safari appears to be pretty broken, not displaying any students on a course's Students tab.

**Comment by bmathews** [comment]
I'm not able to reproduce any of the errors on Safari 9. I'll see if I can get an older version and reproduce.

**Comment by thenickcox** [comment]
#499 is the IE11

**Comment by thenickcox** [comment]
I wouldn't be surprised if 4777ac2 fixed this as well, but if @bmathews isn't able to duplicate, we'll just have to keep an eye on it.

**Comment by ragesoss** [comment]
User reports it's fixed in Safari.
