### ISSUE TITLE
Default campaign should be determined automatically

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5082]
### Current Behavior:

The default term, which is used for the (logged out) home page and the explore page, is set via `/settings` and needs to be changed twice a year for Wiki Education Dashboard. We routinely create spring and fall terms for each year, but we must also update the default term whenever it's time to change terms.

### Desired Behavior:

The default term should be automatically updated at standard dates each year (with a fallback in case the expected new default term does not exist as a Campaign).

**Comment by gabina** [comment]
I'm currently working on this issue. The approach will be to create a `DefaultCampaignUpdateWorker` that will execute  at every March, 21st and September, 21st, based on the beginning of the spring and fall in northern hemisphere. Please, double check these dates.

The worker will update the `default_campaign` setting value to "spring_`$current-year`" or "fall_ spring_`$current-year`" depending on the current month (March or September) and the current year. If the given campaign doesn't exist, it will set the default campaign to [TBD].
