### ISSUE TITLE
SSL certs are not trusted by some browsers

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#509]
I got a report from a user today, with screenshot, of Chrome on OSX telling her that dashboard.wikiedu.org is not secure.

One of the SSL checker sites raises a flag about an issue with intermediate certs that may be behind this: https://www.sslshopper.com/ssl-checker.html#hostname=dashboard.wikiedu.org

**Comment by bmathews** [comment]
SSL checker doesn't report a chain issue now that we've added the `SSLCertificateChainFile` to the apache conf

**Comment by ragesoss** [comment]
Affected user reports that it works in Chrome for them now.
