### ISSUE TITLE
`/training` should explain how to load training content if none is available

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5094]
### Current Behavior:

When a developer visits `/training` in their development environment, no training content is shown by default. Training content is loaded into the database — either quickly from .yml files in the `training_content` directory if it's in `wiki_education` mode, or slowly by pulling in wiki page content and translations from meta.wikimedia.org if it's not in `wiki_education` mode — when you trigger a training update by visiting `/reload_trainings?module=all` (or in the case of pulling from MetaWiki, `?module=<slug>` to import a single module).

### Desired Behavior:

When there are no training modules already loaded in the database, visiting `/training` should display some documentation explaining how to load training content (or maybe even a button link to the reload_trainings URL).

**Comment by cyrillefr** [comment]
Hello @ragesoss , I would like to work on that one.

I would go for a link to the reload_trainings URL.
But no idea of the proper text to go along.

**Comment by ragesoss** [comment]
There should be two variants, one for if the app is in `wiki_education` mode and one if not.

`wiki_education` mode:

> There are no TrainingLibrary records in the database. Click here to load training data from the `training_content/` yaml files.

non-wiki_education mode:

> There are no TrainingLibrary records in the database.
