### ISSUE TITLE
stat_display boxes are mis-aligned in mobile view

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#51]
@ntdb When the stat boxes go to the two-row format, the first box has a border of 0px on the left, while the leftmost box on the second row has a border of 1px.

**Comment by ntdb** [comment]
@ragesoss could you send a screenshot of what it looks like for you? I've been trying to finesse that little module into perfection.

**Comment by ragesoss** [comment]
![Real screenshot from my phone](https://cloud.githubusercontent.com/assets/848483/6744348/85b97b9e-ce65-11e4-8619-e1703210742f.png)
![Fake one from my browser](https://cloud.githubusercontent.com/assets/848483/6744358/a34d7160-ce65-11e4-83ec-b902cfba7f74.png)

**Comment by ntdb** [comment]
Interesting, I added margins to compensate for a one-pixel shift in the opposite direction in Chrome and on iOS. I'll look at it again. :)
