### ISSUE TITLE
For courses with large numbers of edited articles, the student details view list of articles is incomplete

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5106]
### What is happening?
When a user tries to see the list of pages they have edited for a course, such as [here](https://outreachdashboard.wmflabs.org/courses/Black_Lunch_Table_and_Igbo_Wikimedians_User_Group/Black_artists_in_history_and_contemporary_Contest_(2022-06-04)/students/articles/Kingsley%20Nkem), the list is based on the shared articles redux store that powers the Articles tab. We only load 500 edited articles by default, so the user details view shows only the articles that user edited from among the 500 articles that got loaded (unless additional articles are loaded via the 'See more' button on the Articles tab).

However, unlike on the Articles tab, there is no indication that this is a partial list. This is confusing for users, who think that missing articles they've edited are not being counted.

### Expected behavior

I think some UI to indicate that the list is incomplete, along with a 'See more' button that does the same thing as on the Articles tab, would alleviate the problem.

**Comment by kamzzy** [comment]
@ragesoss can i work on this

**Comment by ragesoss** [comment]
Go for it.

**Comment by Fiewor** [comment]
is @kamzzy still working on this? @ragesoss or can I work on it?

**Comment by ragesoss** [comment]
@Fiewor you can work it. :-)

**Comment by Fiewor** [comment]
Alright. Can I reach out to you if/when I face challenges

> @Fiewor you can work it. :-)

**Comment by ragesoss** [comment]
Yes, please do!

**Comment by Fiewor** [comment]
Hey @ragesoss I've been having series of issues while trying to follow the [guide](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/ubuntu_wsl_setup.md) to setting up on WSL.

This is the latest:

![image](https://user-images.githubusercontent.com/30049719/207610400-311a0d6c-9f50-4f23-8e58-6833f4769379.png)

Any help?

**Comment by Fiewor** [comment]
> Hey @ragesoss I've been having series of issues while trying to follow the [guide](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/ubuntu_wsl_setup.md) to setting up on WSL.
> 
> This is the latest:
> 
> ![image](https://user-images.githubusercontent.com/30049719/207610400-311a0d6c-9f50-4f23-8e58-6833f4769379.png)
> 
> Any help?

I'm alternatively trying to follow [this]() other guide but I seem to have downloaded the wrong Ruby version.

![image](https://user-images.githubusercontent.com/30049719/207615011-62d7801e-64cd-49f1-a41e-5f011838ce09.png)


I just checked http://rubyinstaller.org/downloads and I can't find the specified 3.1.2

![image](https://user-images.githubusercontent.com/30049719/207614862-531367b5-ee2c-413d-8f2d-e904c633d744.png)

**Comment by ragesoss** [comment]
@Fiewor if you just change the Ruby version in the Gemfile (without committing that change), everything will probably work on Ruby 3.1.3-1. It's a point release, so there should not be any compatibility change from Ruby 3.1.2.

However, working through the WSL problems is likely to be the best option. There's likely a build dependency that you don't have installed yet, which is preventing the `rvm` installation from working.

**Comment by bogisushrith** [comment]
Hi @ragesoss 
Can I work on this Issue?

**Comment by ragesoss** [comment]
> Hi @ragesoss Can I work on this Issue?

Sure, go for it. If you'd like an invite to our slack channel, please email me at sage at wikiedu.org.

**Comment by Suvam12345** [comment]
@ragesoss
There is no change in 'Editors' tab if I click 'See more' in 'Articles' tab. So, what is the connection between 'Editors' and 'Articles' tabs?
Finally, where do you want changes, in 'Editors' tab?

**Comment by ragesoss** [comment]
> @ragesoss There is no change in 'Editors' tab if I click 'See more' in 'Articles' tab. So, what is the connection between 'Editors' and 'Articles' tabs? Finally, where do you want changes, in 'Editors' tab?

The 'Editors' tab, when you click on an individual user, will include a section 'Other Edited Articles'. This shows all of the articles edited that user, as a subset of all the articles that have been loaded in to the `articles` redux state (which is primarily used for storing data for the Articles tab). So for the example in the issue description, you can first look at the list of articles for  user `Kingsley Nkem`, and it will be 20-something articles. Then you can go to the Articles tab, click 'See more' several times, and navigate back to that same user, and now there will be more articles for that user. The problem is that, when you view the user's 'Other Edited Articles', you don't know that this list might be incomplete (because there are additional Articles to load, which might or might not have also been edited by this user).

**Comment by Suvam12345** [comment]
@ragesoss 
Thanks! Got it. Trying to solve this.

**Comment by Aminehassou** [comment]
I've sent in a pull request for this issue
