### ISSUE TITLE
Import many Wikidata edit summaries at once

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5108]
### Current Behavior:

We import Wikidata edit summaries one at a time (one API request per revision) via ImportWikidataSummariesWorker and UpdateWikidataStats. This is too slow.

The mediawiki API supports fetching up to 50 edit summaries per request, eg: https://www.wikidata.org/w/api.php?action=query&prop=revisions&revids=10000|10001|10002|10003|10004|10005|10006|10007|10008|10009|10010|10011|10012|10013|10014|10015|10016|10017|10018|10019|10020|10021|10022|10023|10024|10025|10026|10027|10028|10029|10030|10031|10032|10033|10034|10035|10036|10037|10038|10039|10040|10041|10042|10043|10044|10045|10046|10047|10048|10049&rvprop=comment|ids

### Desired Behavior:

ImportWikidataSummariesWorker and UpdateWikidataStats, and related code, should be rewritten to fetch and update edit summaries in batches of 50.

**Comment by TheTrio** [comment]
Can be closed now I think

**Comment by ragesoss** [comment]
Done in https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/4071d4aaa7977124dc4dc77864961915a7ec3b51
