### ISSUE TITLE
Update React to version 18

### ISSUE THREAD

**Issue by TheTrio** [WikiEducationFoundation/WikiEduDashboard#5130]
We are currently using React 17. Upgrading to React 18 might involve some work, as outlined [here](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/future.md#react)

**Comment by prashulkale** [comment]
if you assign me the test i will  Upgrade the react version

**Comment by TheTrio** [comment]
There's no need to assign it. Just leave a message when you start/stop working on the issue.

**Comment by TheTrio** [comment]
Solved by https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5437
