### ISSUE TITLE
Cannot find module ‘worker_threads’

### ISSUE THREAD

**Issue by arka1002** [WikiEducationFoundation/WikiEduDashboard#5144]
### What is happening?
> While setting up the local development environment in WSL 2, everything worked fine until `yarn` was hit & this error popped up.

### To Reproduce

> Steps to reproduce the behavior:
> 1. Every step written [here](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/ubuntu_wsl_setup.md) until 5.vi.

### Screenshots
![This is an image](https://iili.io/PIJaPn.png)

### Additional context
> Tried to solve it by writing `--experimental-worker` in package.json suggested [here](https://support.glitch.com/t/cannot-find-module-worker-threads/44787) but it didn't work.

**Comment by ragesoss** [comment]
Hmm... my best guess is that this is an incompatibility with the `nodejs` version you're running. Which version of node do you have? (Run `nodejs -v` from a terminal.)

**Comment by arka1002** [comment]
v10.19.0

**Comment by ragesoss** [comment]
you need a newer version of node, 14 or 16
