### ISSUE TITLE
Tickets should be searchable by email and by username

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5152]

**Comment by cyrillefr** [comment]
Hello @ragesoss , can I work on this one ?

**Comment by ragesoss** [comment]
@cyrillefr yes. :-)

**Comment by cyrillefr** [comment]
Browsing issues still open, I came across a bit similar issue #3588.
In it, @epleaner describes how to set up a dev environment, I will follow his guidelines to work.

Do you want me to get inspiration from one of existing component ?
My first intention would be a search input with autocompletion (fuzzy from a prepopulated list?) and maybe merge data from both usernames and emails. I have got not a good knowledge of the React front-end, so I do not know what is feasible or not.

**Comment by ragesoss** [comment]
I don't think autocompletion is an important feature to include (although it would be fine, if you can get it working efficiently).

My suggestion for an overall approach to this this would probably be to a) create a query object similar to what you did for training search, b) make a json endpoint for return search results (and only admins should be able to access it), c) add a search bar to the ticketing dashboard (`/tickets/dashboard`), d) upon executing a search, use a new reducer to keep the search results in the Redux store (independently of any tickets that were loaded before the search), and e) load a new component that re-uses the UI for the ticketing dashboard's filters and list of tickets but does not include any filters by default and displays the search results.

(That's not the only way to do it well, it's just the type of strategy I would use myself.)
