### ISSUE TITLE
Lists of students, articles, assignments can get out of date when tab is left open

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5165]
### What is happening?

If a user keeps a Dashboard window open (for example, perpetually throughout a course) without reloading, then the lists of users, articles and assignments are not refreshed from the server. This can lead to confusion wherein a student joins but is not shown to the instructor because they've only been navigating from tab-to-tab of the course page without a full page reload.

### Expected behavior

When a user navigates away from one of these tabs and then back to it, the key data associated with it should be refreshed from the server. However, we should make sure that we aren't double-fetching the same data when a page is initially loaded.

**Comment by iLynette** [comment]
Hi, @ragesoss I would like to work on this issue. Can I?

**Comment by ragesoss** [comment]
This one is probably too complex for a good first issue.

**Comment by iLynette** [comment]
Alright.)

**Comment by TheTrio** [comment]
One quick and simple way to solve this would be to refresh the data every few minutes - say something like this in `app/assets/javascripts/components/students/containers/StudentsTabHandler.jsx`

```jsx
...
componentDidMount() {
  this.interval = setInterval(() => {
    this.props.fetchUsers(this.props.course.slug);
  }, 1000 * 60);
},

componentWillUnmount() {
  clearInterval(this.interval);
},
...
```

Another way might be to refresh the data only when the user switches tabs. Something like this

```
let firstMount = true;
const StudentsTabHandler = createReactClass({
  displayName: 'StudentsTabHandler',
  ...
  componentDidMount() {
    if (!firstMount) {
      this.props.fetchUsers(this.props.course.slug);
    } 
      firstMount = false;
      // don't fetch since this is the first mount
    }
  },
```

This however doesn't work if the user is on the same tab for a long time - so I guess a combination of both of these approaches would provide the best experience. What do you think?
