### ISSUE TITLE
There are no links to the training library from nav header or My Dashboard

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#517]
Access to the training modules, especially for instructors to browse after they were initially onboarded, is important.

Do we already have a design for how users can access the training library? In any case, we need to find some way to make it accessible from the My Dashboard view. One option is making them accessible from *anywhere* by adding them to the nav header.

@bmathews @rileywho

**Comment by bmathews** [comment]
@ragesoss Riley and I worked on getting the training link in the navigation and making sure there was enough space. Any thoughts or concerns on this? 

cc @rileywho 

![image](https://cloud.githubusercontent.com/assets/848347/11884739/c799fd62-a4d0-11e5-868f-a8b8c987e26d.png)

![image](https://cloud.githubusercontent.com/assets/848347/11884744/cfd77e82-a4d0-11e5-9475-86c5293687ad.png)

**Comment by rileywho** [comment]
+1

**Comment by ragesoss** [comment]
That nav bar is getting crowded, but this looks good to me for now.

**Comment by ragesoss** [comment]
Now implemented.
