### ISSUE TITLE
training quiz question font is too small

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#518]
Eryk makes this suggestion: Increase the size of the question text to match the answer text, but add bold formatting to the question text.

cc @bmathews

**Comment by bmathews** [comment]
Current implementation for reference:

![image](https://cloud.githubusercontent.com/assets/848347/11642356/4f5d9696-9cf2-11e5-8262-adaf225caa5f.png)

cc @rileywho

**Comment by rileywho** [comment]
@bmathews Increase font-size to 24px. Increase mb to 20px.
