### ISSUE TITLE
Backup server gets filled up and stops saving backups

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#519]
I checked in on the backups server, and found it was full. (It's a 20GB virtual server.) There were 16GB worth of backup in the 'daily' directory, stretching from September until December 4 (which the disk became full, I assume). I cleared out all the ones from September, October and November.

We should change that directory to only store up to about 3 weeks worth of daily backups. @thenickcox where/how is this configured? We should document our backup setup.

**Comment by thenickcox** [comment]
Yeah, I anticipated this happening, though not this quickly. It's not really "configured" anywhere, it's just a crontab. 

I'm thinking we could just also write a script to delete ones older than x weeks, and run that just prior to the backup crontab.

**Comment by ragesoss** [comment]
Ah, okay. I thought it was already set to delete ones older than X, and that we just had X set too large.

It's a crontab on production, I assume?

**Comment by thenickcox** [comment]
Sorry, it looks like there is a config at `/etc/automysqlbackup/automysqlbackup`.

**Comment by ragesoss** [comment]
I've added the --delete option to rsync, and also added the relevant config files and documentation to git. I tested out the script with the --delete option, and although there is an error message related to permissions when I run `runmysqlbackup`, the deletion feature now seems to be working, so this should keep the backup server from filling up again any time soon.
