### ISSUE TITLE
Add a button to for instructors to add all students' talk pages to their watchlist

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5199]
### Desired Behavior:
Some instructors want to use their Wikipedia watchlists to keep an eye on the Talk pages of all their students. There's no automatic way to add all your students to your watchlist, though. As an instructor, I want to be to click a button on my Course page to have the Dashboard automatically add all the User pages of my students' to my watchlist.

(This is at the harder end of a 'newcomer friendly' task. It involves a fair amount of work, from adding a frontend UI to a Rails Controller to some logic in turning a set of Users into a set of user page titles, to editing a user's watchlist through the MediaWiki API, to writing tests for the new feature. However, each of these parts on their own should be relatively straightforward to implement by following examples of related functionality that already exists. The hard parts will be finding all the relevant examples to follow and understanding enough about the app to understand the use case. Feel free to ask for pointers for any of those hard parts.)

**Comment by twinsfan421** [comment]
I can work on this

**Comment by ragesoss** [comment]
> I can work on this

Great! Let me know if you'd like to join our Slack to chat about anything related.

**Comment by twinsfan421** [comment]
> > I can work on this
> 
> Great! Let me know if you'd like to join our Slack to chat about anything related.

Yes, joining your slack channel sounds good. Thanks

**Comment by ragesoss** [comment]
YGM

**Comment by twinsfan421** [comment]
@ragesoss would you like the add all students/editors to watchlist button on the courses home page, maybe under "Actions"?  or under the Editors page(students/overview)?  Also, for the "editing a user's watchlist through the MediaWiki API", is there a relevant example for that you recommend?   Thanks

**Comment by ragesoss** [comment]
Good questions. I think `students/overview` is probably the best place.

For editing the watchlist, the closest things are probably the methods that call `api_post` in `lib/wiki_edits.rb`. I expect this will look similar, in terms of figuring out the right parameters to post to the general MediaWiki API in order to make watchlist changes. See https://en.wikipedia.org/w/api.php?action=help&modules=watch

For testing this locally and changing your own watchlist via API, you might also need to register your own OAuth consumer. See `docs/oauthmd`.

**Comment by Chaitanyarai899** [comment]
Hello! I would like to work on this enhancement! I hope that's ok.

**Comment by reachaadrika** [comment]
@ragesoss  Hey can I work on this issue , I have to create a dev environment on my system and after that I will start working on this !

**Comment by ragesoss** [comment]
@reachaadrika go for it.

**Comment by reachaadrika** [comment]
@ragesoss I don't have any knowledge of rails so can you guide me on how can I study rails and solve this issue ?

**Comment by Shurtu-gal** [comment]
@ragesoss Is anyone still working on this issue.

**Comment by ragesoss** [comment]
@Shurtu-gal no, I don't believe so.

**Comment by Shurtu-gal** [comment]
Then I would like to work on this issue.
Can you give some brief guidance regarding the same?

**Comment by akanshajais** [comment]
@ragesoss can we use mw-api  package that makes it easier to interact with the MediaWiki API ?

**Comment by ragesoss** [comment]
@akanshajais the dashboard already has code for interacting with the MediaWiki API, so  adding an additional package is likely to make things harder rather than easier. If you find that not to be the case, I'd be willing to see what it would look like to use that package.

**Comment by Abishekcs** [comment]
@ragesoss May I work on this issue if no one else is currently working on it?

**Comment by Abishekcs** [comment]
@ragesoss  Can you give me some pointers on how to retrieve the names of students enrolled in a course? I am having difficulty on that part.

**Comment by ragesoss** [comment]
> @ragesoss Can you give me some pointers on how to retrieve the names of students enrolled in a course? I am having difficulty on that part.

In the Rails server environment, `course.students` will query for all the User records of students in the `course`.

**Comment by Abishekcs** [comment]
@ragesoss should the `watchlist button` be visible only to the instructors?

**Comment by ragesoss** [comment]
Yes.
