### ISSUE TITLE
Firefox borks icon font

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#522]
Not sure why this is occurring. @ragesoss Are you seeing this on master using iceweasel?

(Firefox left, Chrome right)

![screen shot 2015-12-09 at 2 07 50 pm](https://cloud.githubusercontent.com/assets/702327/11700367/44bf6f60-9e7e-11e5-9634-fcbce4a41ac3.png)

**Comment by bmathews** [comment]
not a cache issue?

**Comment by thenickcox** [comment]
That was my first thought. @ragesoss?

**Comment by ragesoss** [comment]
Happening for me locally and on staging, at least since yesterday.

-Sage

**Comment by thenickcox** [comment]
I don't think this is an issue anymore. Clearing cache and rerunning `gulp` seems to fix it.
