### ISSUE TITLE
Tickets should be searchable by Course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5224]
When viewing a course, or viewing a single ticket, it would be really useful for an admin to be able to view all the other tickets associated with the same course. For a ticket (`TicketDispenser::Ticket`), the `project_id` is the ID of the associated course (and calling `Ticket#project` will return a `Course` object).

Ideally, this would be implemented as an additional ticket search mode, taking a course slug as input, then loading the associated course record and its ID and finding all tickets with the matching `project_id`. Then we could easily add links that include the course slug as a query parameter, both from the ticket `show` view and from a course page, which would load all that course's ticket's when followed.

**Comment by ragesoss** [comment]
@cyrillefr ^

**Comment by cyrillefr** [comment]
Hello @ragesoss.
I take that one, (continuation of #5152 issue #5210 PR).

I can add a link @ the ticket show, right under the Course Page
Regarding the link @ the course show page, I do not know where to put it (maybe under Actions ?)

**Comment by ragesoss** [comment]
I think Actions is a fine place for it.

**Comment by cyrillefr** [comment]
Hello @ragesoss,

I guess it will not be a LIKE search for the course slug (dashboard view)

So, either there will a simple text input, up to the admin to copy/paste.
Either, we can have a select populated with every slug courses, then with the autocompletion feature, it is easy to search.

But, I have no idea of how many courses there will be.
50 courses is OK
10,000 courses, may be not

Sooo, simple input or select ?

**Comment by ragesoss** [comment]
I think simple input and expecting an exact match with the slug is good for
this. 10k is the right order of magnitude for total courses.
