### ISSUE TITLE
Cannot remove final training from a block

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#525]
Adding and removing trainings to/from blocks works fine in most cases, but if a block has trainings and you remove them, then they will still be there after you click save.

@thenickcox

**Comment by thenickcox** [comment]
Yep. I was working on this last night. Hoping to have a fix soon.

**Comment by thenickcox** [comment]
@ragesoss Well, that was rough.

Feel free to test. Should we deploy this?

**Comment by ragesoss** [comment]
If you're confident it doesn't seriously break anything, go for it.
