### ISSUE TITLE
There is no easy way to navigate to an individual FAQ question

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5293]
The FAQ system will show a set of search results when you do a search from the nav bar. However, it's a little tedious if you want to first search, and then get the URL for an individual entry that shows up in the results.

There should be some kind of link from each search result to the individual entry.

**Comment by saha23s** [comment]
Hi @ragesoss I want to work on this issue - Can you guide me a little more about what skills should be necessary for fixing this? Currently, my faq page looks like this. 
![image](https://user-images.githubusercontent.com/93749279/226130440-28cf9797-38d4-4594-a219-bea1be2f3cc9.png)

**Comment by ragesoss** [comment]
You should start by adding some FAQ entries. You can do this from the `/admin` page (which you need to log in and give your account admin permissions to access... see `docs/user_roles.md`).

**Comment by saha23s** [comment]
@ragesoss I could successfully set up the entries. First of all, I am curious why there's no nav item called "help" or "FAQs" in the navbar where I can click and see all the FAQs. Because as a user I was confused about how to access faqs.
Besides, can you clarify the expected behavior when you mentioned "There should be some kind of link from each search result to the individual entry"
Also, I want to continue working on this issue!

**Comment by Titilola2** [comment]
@ragesoss , I'd like to know if I can work on this big or only one person is allowed to work on it at a time?

**Comment by saha23s** [comment]
@ragesoss If I understand your explanation correctly, then it means I will aim to create an individual page for every FAQ entry when a user clicks on a FAQ they are interested in. Right now, toggling is the way to see the details. Let me know if I am thinking it right.
![image](https://user-images.githubusercontent.com/93749279/227572915-b87babdd-b37d-489b-8e30-6c1b12652813.png)

**Comment by ragesoss** [comment]
@saha23s the individual pages already exist, they just aren't easy to navigate to. As an admin, the way I currently do it is to use the `edit` link next to the title of an entry, and then remove `/edit` from the end of the url.

One possible way to do this would be to simply turn the title itself into a link. Another way would be to add a 'permalink' link or similar, next to each one.
