### ISSUE TITLE
Debian setup script is out of date

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5294]
The main python setup script (setup.py) calls different setup scripts, depending on which platform it's being run on. For Debian and related distros (Ubuntu, Elementary), it calls `setup/deb-setup.sh`. This script is out of date, and may not successfully result in a working Dashboard development environment without some manual steps.

Run the script on a Debian or Ubuntu system, post a comment in this issue for anything that you find does not work correctly on the first try without any extra steps, and then update the script to make it work correctly.

**Comment by singhavs** [comment]
@ragesoss can I work on this issue.

**Comment by singhavs** [comment]
@ragesoss  can you add me to the slack Outreachy community channel.
I am trying since two days. Email: as.aayushi11@gmail.com
Thanks!

**Comment by ragesoss** [comment]
Invite sent!

**Comment by Shurtu-gal** [comment]
@ragesoss Can we have a script for arch based linux distros also?

**Comment by ragesoss** [comment]
@Shurtu-gal if you would like to work on one, you are welcome to do so. I've never used Arch, so I wouldn't be of much help with the specifics.

I think, though, that rather than adding more and more separate scripts, the best situation in the long run would be to refactor them to share as much logic as possible so that they work on a wider array of systems. That would probably involve separating the set of requirements from the specific install commands.

**Comment by sharon-odhiambo** [comment]
Hi @ragesoss , I'd like to attempt this one. A quick question, this should only focus on debian right?

**Comment by ragesoss** [comment]
> Hi @ragesoss , I'd like to attempt this one. A quick question, this should only focus on debian right?

Yes!

**Comment by sharon-odhiambo** [comment]
Hi @ragesoss . Sorry I have slacked on this. Things came up on my end that were out of my control. So today I have tested this on a debian laptop and everything ran smoothly. With all the prerequisites everything is okay. I was wondering whether we can close this issue because I didn't find much to do with it.
