### ISSUE TITLE
Windows setup script is not written for WSL

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5295]
The main python setup script (setup.py) calls different setup scripts, depending on which platform it's being run on. For Windows, it calls `setup/win-setup.bat`. This script is badly out of date, as it does work via WSL 2 — which is currently the best way we know of to run a Dashboard dev environment on Windows.

Create a new script that automates the setup of a dev environment on Windows, using WSL. (It may require user interaction, such as printing out instructions for enabling WSL 2 and other system-level requirements, if those can't easily be automated within the script. I'm not sure how completely the whole process can be automated, but the more the better.)

**Comment by RedWing0021** [comment]
Hello,
I want to contribute to this bug. Please guide me further to fix this.

**Comment by ragesoss** [comment]
@RedWing0021 check out the setup.md doc, then likely you'll need to go through the manual setup process, and compare all the things you have to do to get it set up manually with with the script does. I'm personally not experienced with Windows scripting, but the more details you can provide in comments here about what steps are necessary and which ones are accounted for or not accounted for in the current script, the closer we'll get.

**Comment by RedWing0021** [comment]
@ragesoss Thanks for the help !!
Can you please send a Slack invite to email - naitikpatel.np2004@gmail.com as I am not getting how to join.

**Comment by sharon-odhiambo** [comment]
Hi @RedWing0021, did you manage to work on this issue?

**Comment by ragesoss** [comment]
I've added a slight tweak to the setup script and updated the WSL setup doc, so now the debian script can be used with Ubuntu WSL to successfully set up the project. We'll be deleting the Windows script.
