### ISSUE TITLE
Grading link from Timeline right-hand weeks box does not work

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#530]
It looks like it's only affecting the overall timeline scroll region, and not the left-hand timeline blocks column specifically... even though the grading is part of that left-hand column. So the effect is that clicking "Grading" does not  actually put the grading section into the viewable portion of the window.

cc @thenickcox

**Comment by ragesoss** [comment]
See for example https://dashboard-testing.wikiedu.org/courses/Wake_Forest_University/Race,_Class_Gender_and_Sexuality_%28Spring_2016%29/timeline

**Comment by thenickcox** [comment]
Oops. This is a firefox-only issue. We haven't gotten to cross-browser testing in QA yet, but we'll definitely clear this up.

**Comment by thenickcox** [comment]
closed via 674651a
