### ISSUE TITLE
Fix warnings in jest test suite

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5300]
Our JavaScript files have a set of corresponding tests in the `test` directory, which are run during the GitHub actions build in the 'JavaScript test suite' step (eg, [here is a recent build](https://github.com/WikiEducationFoundation/WikiEduDashboard/actions/runs/4404784394/jobs/7714845683#step:12:1)) or locally via `yarn test`.

There are a number of warnings and console errors issued by the test suite, which don't break the build because the tests still pass, but which result noisy test output and may represent real code problems.

Fix one or more of these warnings/errors.

**Comment by brauliorivas** [comment]
Hello @ragesoss, I would like to work in this issue.

**Comment by RedWing0021** [comment]
Hello,
If no one is working on this issue, I would like to work. Please assign this to me.

**Comment by ragesoss** [comment]
@RedWing0021 brauliorivas is working on it and has an open PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5312
