### ISSUE TITLE
More than one nav element shows highlighted

### ISSUE THREAD

**Issue by saha23s** [WikiEducationFoundation/WikiEduDashboard#5326]
### What is happening?
If you click on the "Users" nav element, more than one nav element shows highlighted.
### To Reproduce
[on the wiki-education mode]
1. Go to 'Admin'
2. Click on 'Users'
3. See the error

### Expected behavior
When clicking on Users, only the "Users" nav element should be highlighted, not the "Account Requests" and "Tickets".

### Screenshots
![image](https://user-images.githubusercontent.com/93749279/227705896-3c197668-639e-485e-87b4-869fb1be1c1b.png)

**Comment by singhavs** [comment]
@ragesoss can I work on this issue?

**Comment by ragesoss** [comment]
@singhavs yes, go for it.

**Comment by kowais915** [comment]
@singhavs Are you still working on it? I am interested in this issue.

**Comment by Johnadibe** [comment]
Hello, Is there anyone still working on this issue? I want to to work on it now.

**Comment by ragesoss** [comment]
Anyone may work on this. I expect the fix will be very simple, so I'm not worried much about wasting effort from multiple people trying it at once for this particular issue; if you figure out a fix, please open a PR.

**Comment by Bharadwajshivam28** [comment]
@ragesoss Please assign to me sir i want to work on this issue

**Comment by ragesoss** [comment]
@Bharadwajshivam28 we don't assign issues, but you're welcome to open a PR for this.

**Comment by Bharadwajshivam28** [comment]
> I don't think we have any good documentation on using gitpod for it, and I'm not familiar with that. But we have an open issue about it, which would be a good place to post the details about what problems you've run into with it. https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/3856

Can you share some resources how can I set it in my code editor and run locally

**Comment by ragesoss** [comment]
Check out https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md

**Comment by Bharadwajshivam28** [comment]
thanks

**Comment by Bharadwajshivam28** [comment]
@ragesoss
This is my terminal after running the command 'python3 setup.py'

![Screenshot from 2023-05-08 23-00-43](https://user-images.githubusercontent.com/108119109/236891663-cbca62f9-3009-43c8-9ee7-3dc0517a4a26.png)

but i not got any localhost link to run the page what should i do next?? please help

**Comment by Bharadwajshivam28** [comment]
How can i get local server link to host

**Comment by Bharadwajshivam28** [comment]
@ragesoss I am facing issue that where is the admin and user section in the page..

can you just help like under which button or section this admin and user comes..

or how can i react these 2 section

**Comment by ragesoss** [comment]
the admin page is at `/admin`

**Comment by Bharadwajshivam28** [comment]
oh thanks

**Comment by Bharadwajshivam28** [comment]
beside the whole project

**Comment by Bharadwajshivam28** [comment]
@ragesoss
