### ISSUE TITLE
Adding blackout weeks after course creation can result in more Weeks than available calendar weeks

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#533]
Credit to @bmathews for finding this one.

Currently, if the timeline is created and a particular week contains blocks, if you make that week a blackout week (by pressing "Edit Course Dates" on the timeline), the week just doesn't get shown, and the blocks don't get redistributed. Adding course meetings back to that week causes the week to display again, and everything is happy. But if you then add a week later, the course dates get confused.

It seems like if you make a blackout week from a previously existing week, we should delete the week and its blocks.

@ragesoss does this make sense?

**Comment by ragesoss** [comment]
'make a blackout week' how? By going back to the calendar and adding new dates when the course does not meet? If that's what you mean by adding a blackout week, then the behavior should be that it shifts the dates of that week and its blocks, pushing all subsequent week dates back one week.

**Comment by thenickcox** [comment]
What if there's not enough room?

**Comment by ragesoss** [comment]
The previous, not-great behavior was that it would push the last week past the timeline end date. An slightly better alternative might be to move all the affected blocks to the following week (combining them with the ones that are already there).

**Comment by thenickcox** [comment]
That _sounds_ great, but what if you make the last week a blackout week? I agree, it's not a likely scenario, but it's certainly possible.

**Comment by thenickcox** [comment]
@ragesoss Please look at those two commits and see if that does what you're looking for.

**Comment by ragesoss** [comment]
@thenickcox you haven't deployed this to staging yet, right? Because on staging it seems to be working just like it did before, where if you black out a week, it shifts the weeks and their blocks appropriately (since blackout weeks don't have a Week object).

**Comment by ragesoss** [comment]
@thenickcox @bmathews I can't replicate the initial bug described.

**Comment by thenickcox** [comment]
@ragesoss What were the steps to redistribute the blocks? For @bmathews, it was creating an "add images" timeline, course starting 12/1, ending 1/3, meeting on Wednesdays, submitting, editing timeline, blacking out the last week.

**Comment by ragesoss** [comment]
I did it on this course, initially with no blackout dates: https://dashboard-testing.wikiedu.org/courses/test/wizard_test_%28test%29/timeline

The first content in the timeline is "Wikipedia essentials", and it always goes to the first non-blacked-out week, with other Weeks extending the listed weeks in the right-hand column.

**Comment by ragesoss** [comment]
@thenickcox @bmathews Okay, I'm able to replicate the bug... it only happens for weeks that have been pushed past the end of the timeline. (The timeline actually shows blackout weeks that are past the end of the course... but not the Week content that is after *that*, like before).

So, I think the solution is probably to keep the warning popup, but only trigger it when adding that new blackout week would mean that there are more Weeks than available nonblackout calendar weeks.

**Comment by thenickcox** [comment]
@ragesoss Any chance you're able to give me the assignment type, course dates, and timeline dates to replicate this?

**Comment by ragesoss** [comment]
@thenickcox you can replicate it following @bmathews's recipe above, if you black out all the meeting days but one.

**Comment by thenickcox** [comment]
Closed via afa2773

(thanks, @bmathews)
