### ISSUE TITLE
For Ticket system, add search and filtering by Alert type

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5330]
### Current Behavior:
As of recently, tickets are searchable via several modes. However, if you are looking at a long list of tickets and want to see just the ones that represent a certain type of common issue (ie, an Alert type), there's no quick and easy way to do that.

### Desired Behavior:
Users of the ticketing system should be able to select an alert type to filter by. It might also be useful to be able to list all the alerts of a given type.

### Additional context:
The actual alert types that triggered the corresponding tickets are not included as structured fields in the Ticket or Message records, but the alert type names should generally be present in the subject and/or body, so I'm guessing this would be best accomplished by adding some frontend UI specific for alerts, but implementing the search using one of the already-implemented search modes on the backend.

**Comment by kessio** [comment]
@rageross do I need an admin account to view the ticketing system?

**Comment by ragesoss** [comment]
@kessio yes. See `docs/user_roles.md`.

**Comment by kessio** [comment]
Ok thanks

**Comment by ragesoss** [comment]
After talking this over with Wiki Education staff, I think the ticket search already does what we wanted out of this. There's a low priority related issue that we could improve, which I'll open a new issue for.
