### ISSUE TITLE
Default sorting of Students list is not ideal, and resorting state is not retained when navigating between tabs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5343]
### What is happening?

On the Students (aka Editors) tab of a course page, students are listed by default in the order in which they joined the Course (I think). They can be resorted using either the sorting dropdown menu at the top of the Students list, or by clicking one of the headers in the Students tab. (Some sorting methods, such as sorting by last name, are only available via the dropdown.)

Sorting by last name and falling back to username would be a better default.

If a user re-sorts the list, by last name for example, then it retains that sorting while the user navigates between tabs... until a data refresh occurs (which happens when you change course tabs and it's been more than a minute since the last fetch), and then the users go back to default sorting.

If a user has set a value for sorting the users, then this sorting should be re-applied after user data gets refreshed.

### Additional context

The core of this bug is a Redux problem, and can be thought of primarily in terms of redux actions and state. In particular, the RECEIVE_USERS and SORT_USERS actions are the relevant ones here.

However, there's a related code quality problem that will need to be fixed first in order to leave us with a pure redux state-management problem, which is that the current user sorting feature offers options of 'first name' and 'last name', but these don't come directly from the server and are instead set client-side in components via the `setRealName` functions that are present in StudentExerciseRow and StudentRow components. These functions are actually mutating the Redux state without using a reducer, which means that the sorting options mostly work, but aren't easy to reason about. So I think the first thing will be to move the setting of those first and last name values into the reducer path for RECEIVE_USERS instead of the current situation where it happens during rendering as a side effect. Once that's fixed, it should be relatively easy from there to make sorting behave properly in conjunction with re-fetching of user data.

**Comment by sharon-odhiambo** [comment]
HI @ragesoss , a quick one on this. Just clarifying whether it's the course page or the campaign page?

**Comment by ragesoss** [comment]
Course page.

**Comment by sharon-odhiambo** [comment]
This is what I'm getting on the course page
![Screenshot from 2023-04-11 10-30-26](https://user-images.githubusercontent.com/88780311/231196102-5828dbde-e302-4c40-b76c-f0d3f777b6df.png)
And this on the campaign page
![Screenshot from 2023-04-11 10-30-56](https://user-images.githubusercontent.com/88780311/231196222-94110868-782d-4632-bc2e-f8e199a9737b.png)

**Comment by sharon-odhiambo** [comment]
Hi @ragesoss , in the students tab I can mostly see just the username. Should I make the default sorting the username? When I try to check the redux store I'm finding a null for the first name and last name pins. Also could you kindly guide whether this sorting should preferably be done the reducer for SORT_USERS action or the List component?

**Comment by ragesoss** [comment]
Yes, the real name fields are only sent if the user is the instructor of the course, or an admin. The name fields are only populated, normally, when a user enrolls in the course themselves rather than being added via username. However, you can manually add real names to the CoursesUsers records, via console, for testing.

**Comment by sharon-odhiambo** [comment]
Oh okay, so this way I can add the desired default sorting and test with the added names ?

**Comment by ragesoss** [comment]
Okay, I'm realizing that first_name and last_name are not by default included in the `users` store, but they get added (derived from the real_name) via the `setRealName` function used in two components. So this is a case of mutating redux state without using a reducer, and ought to be fixed by moving the setting of first_name and last_name into the reducer itself, so that these values get set during the RECEIVE_USERS action.

Also, a solution to this issue needs to take into account sorting direction, so that no matter what sorting is set by the user, a new RECEIVE_USERS action with the same user data from the server should result in no change to the sorting order.

**Comment by ragesoss** [comment]
> @ragesoss i can work on this smiley

sure!
