### ISSUE TITLE
Invalid html and warnings in timeline block editor

### ISSUE THREAD

**Issue by bmathews** [WikiEducationFoundation/WikiEduDashboard#536]
`React.findDOMNode` and invalid `p` nesting

![image](https://cloud.githubusercontent.com/assets/848347/11848170/e7676e78-a3d5-11e5-98d8-f16cf7711739.png)

**Comment by bmathews** [comment]
Invalid `p` nesting fixed.

React.findDOMNode coming from react-select. Solution TBD

**Comment by ragesoss** [comment]
This doesn't seem to be happening any more.
