### ISSUE TITLE
in Arrange mode, Blocks without titles should show a truncated version of block content

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#538]
By default, the Milestone blocks don't have titles, and many custom blocks are likely to not have titles either. In that case, it would make arrangement easier if the interface showed a truncated version of the block content (such as the first X characters of the actual milestone, in the case of Milestone blocks by default... enough to actually show which milestone it is).

**Comment by rileywho** [comment]
+1 We should truncate the body text in the arrange mode. 

@bmathews Could we also make the default title for all milestones be "Milestone". A little weird but it gets rid of the awkward negative space.

![pasted image at 2015_12_17 05_42 pm](https://cloud.githubusercontent.com/assets/2120466/11887149/288bf426-a4e6-11e5-92aa-3800fca4f987.png)

**Comment by ragesoss** [comment]
We've switched to having titles by default for all blocks that come out of the wizard, so I'm closing this.
