### ISSUE TITLE
In Firefox, entering the details view for a user from the Students tab sometimes fails to reset scroll position

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5389]
### What is happening?
When viewing the Students Overview, if the list of students is long then a user will need to scroll down to see students below the fold. Clicking on any student row navigates to the details view for that student, and the content for that student is supposed to automatically scroll into view.

In Firefox, when viewing a course as an instructor or admin, clicking on a student while scrolled down will sometimes not trigger that scroll-into-view behavior, so the screen shows no content except the navbar at the top.

Relatedly, it's possible (in both Firefox and Chrome) to scroll down until there is no content in view on the Students tab.  While logged out, the page height matches the size of the rendered content, so this problem does not occur. I don't know why the page height is larger than it should be while logged in. (I haven't tested the case of being logged in but not being an admin or instructor for that course.)

We observed this first here: https://dashboard.wikiedu.org/courses/Hunter_College,_CUNY/CHEM_378_-_Biochemistry_Lab_-_spring_2023_(Spring_2023)/students/articles/Idonthaveone321

**Comment by Aminehassou** [comment]
Is this a wiki_education only thing? Can't seem to recreate it locally on chrome/firefox

**Comment by Aminehassou** [comment]
I created a PR that should fix the issue
