### ISSUE TITLE
Small screens cannot access the last weeks in a long course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#539]
@thenickcox @bmathews 

There is no way to reach the links beneath the weeks list, because the right-hand section does not scroll or extend the window size.

Even on large screens, too many weeks results in an unusable layout: https://dashboard-testing.wikiedu.org/courses/test/wizard_test_%28test%29/timeline

But many courses will have 12-16 calendar weeks, which will trigger this issue on smaller screens.

**Comment by bmathews** [comment]
cc @rileywho

**Comment by thenickcox** [comment]
closed via 7494c46
