### ISSUE TITLE
Dashboard does not handle pages that got deleted

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#54]
Sometimes student editors will create pages that get deleted, for example, the "new" article here: http://dashboard-testing.wikiedu.org/courses/Saint_Louis_University/Developmental_Biology_%28Spring_2015%29/articles

In this case, Mmilldev/sandbox was mistakenly created in mainspace instead of as a userspace sandbox, and it was subsquently moved to userspace with no redirect.

Here the course still says 1 article created and lists it as "(new)". Instead, the dashboard should identify that the article got deleted, and indicate that.

**Comment by ragesoss** [comment]
The characters added, articles edited, and article views should also not include the totals from deleted articles.

Ideally, articles that were deleted should be displayed in a separate section (maybe something like a duplicate of the Articles Edited list, but lower down). As we develop the 'just-in-time help' features, we'll be surfacing a lot of things similar to deleted articles, so we should devote some design time to the general area and think things out more fully.

**Comment by ntdb** [comment]
How does this query look for finding articles that exist from a given set of ids? It doesn't seem quite right, telling me that more than half the articles on my development database have been deleted..

http://quarry.wmflabs.org/query/2785

**Comment by ragesoss** [comment]
Page_ids are not immutable. Many common actions, such as deleting an article an then restoring it with some of the revisions redacted, result in changing the id. We should base any checking for deleted articles on page title.

**Comment by ntdb** [comment]
@ragesoss excellent, thanks!

**Comment by ragesoss** [comment]
Okay, maybe not *many* common actions. But deleting an article and then restoring it does change the id. On the other hand, the page id remains the same if the page gets moved (ie, retitled). Sigh.

Maybe we should start with page_id, and then fall back to searching by title in the case of missing ids? Page moves will be more common than page_id changes.
