### ISSUE TITLE
In CourseClonedModal, it isn't clear why save button is disabled

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5403]
### What is happening?
After a course is cloned, the course page is loaded with the CourseClonedModal form rendered so that the user can update the necessary details to finish the cloning process. Some fields are pre-populated with the values from the original course, but some are blanked because the form assumes they need to change for a new instance of the course. These include Term and all the date-related fields. Until all the fields are filled, including meeting dates and holidays, the form can be submitted. However, users don't get a clear indication of which field(s) haven't been filled out, when the submit button is still disabled.

The Term field, in particular, can appear filled out because the placeholder text ("Term") looks very similar to a filled field.

### Expected behavior

Ideally, all the empty fields would have some kind of highlighting so that it's more obvious which ones need to be interacted with in order to proceed.

It might also be good to make the visual difference between placeholder text and input text more obvious, if that can be done without introduce accessibility problems due to low contrast.

**Comment by mapra99** [comment]
thanks, will do!
