### ISSUE TITLE
On Timeline tab, 'Add Week' button is disabled when there is room for another week

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5438]
### What is happening?

When building a Timeline from scratch, you must use the 'Add Week' button to add weeks to the timeline, and then add Blocks to those weeks. The course dates — in particular, the Assignment Start and Assignment End — determine how many weeks a course timeline can hold. However, at least for short timelines that span just a few weeks from Assignment Start to Assignment End, the 'Add Week' button is disabled even when there is at least (part of) one week available at the end.

In the example from this screenshot (below) that I made while replicating this bug locally, the Assignment End is July 6, while the last week shown on the Timeline ends July 1. There is room for another week (which would only go to July 6, rather than July 8), but the 'Add Week' button is disabled. I'm guessing this is because the logic for calculating whether to disable that button is different from the rest of places where we handle timeline dates, because I can adjust the Assignment End, add a week, and then change it back, and this works as it should (without displaying the warning that the timeline extends beyond the assignment end date).

![disabled Add Week](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/848483/8c3c112d-d2bf-4baa-a07a-b4b46680085e)

**Comment by Abishekcs** [comment]
I can work on this

**Comment by Abishekcs** [comment]
I can work on this
