### ISSUE TITLE
Improve pagination controls on Articles tab

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5446]
Currently, if there are no edited articles, the Articles tab still renders the Prev and Next buttons, and says "Showing 1 - 0 of 0".

It also throws a console warning: `(react-paginate): The forcePage prop provided is greater than the maximum page index from pageCount prop (0 > -1).`

In the case of zero articles, it would be best to simply not render the controls or the "Showing" message.

For larger numbers, the "Showing message" is based on the total number of articles, and if a filter is used (eg, only showing New articles), the total does not update. This can be confusing because you can reach the final page but the "Showing" message implies that there ought to be more pages.

**Comment by subhamkumarr** [comment]
I would like to work on this please assign it to me
