### ISSUE TITLE
Sign Up link should be removed from the top nav.

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#545]
The only place to go through the Sign Up version should be the homepage. @bmathews

**Comment by rileywho** [comment]
I would recommend keeping the Sign Up in the navigation. There are a couple areas where the user might try to sign up from.
- Training
- Explore
- Course page without using emailed link

If the issue is the O-Auth process not being clear to users, a explanation modal could appear when a user hovers over Sign Up for 1 or 2 seconds.

**Comment by ragesoss** [comment]
@rileywho the issue is that 'sign up' really means 'create a Wikipedia account'. If all you want to do is sign up *for* the dashboard, then 'Sign In' is the link you want unless you lack a Wikipedia account. And if you do lack a Wikipedia account, the Sign In link will still allow you to do that; you just have to click Create Account at the bottom of the sign in form once you reach Wikipedia.

**Comment by bmathews** [comment]
Here were some ideas we had:

Add a hover popup to login that explains creating an account on Wikipedia first.
![image](https://cloud.githubusercontent.com/assets/848347/11944934/277c17d4-a7ff-11e5-85df-738c36fc0d98.png)
![login](https://cloud.githubusercontent.com/assets/848347/11944935/2931de88-a7ff-11e5-8603-e87179f82cec.gif)

@rileywho had another idea with a dedicated login page that could be an option too.

**Comment by ragesoss** [comment]
I like this change of copy for the home page, in any case.I think the hover popup is the better option for the nav bar, instead of always sending the user to an intermediate page before they can log in. Most logins from the nav header will be returning users.
