### ISSUE TITLE
Migrate from Redux to Context API for State Management

### ISSUE THREAD

**Issue by punithnayak** [WikiEducationFoundation/WikiEduDashboard#5459]
### Current Behavior:
The project is using Redux as the state management library for handling application state.

### Desired Behavior:
The goal is to replace Redux with the Context API, a built-in state management solution provided by React. This will help simplify the state management process and eliminate the need for an external npm package.

**Comment by punithnayak** [comment]
Hey, @ragesoss is this issue relevant if yes I would be like to work on it

**Comment by punithnayak** [comment]
Hey @ragesoss context Api literally the same and will surely help reduce bundle size

**Comment by ragesoss** [comment]
You mean Create React App? We are not using that.

For switching to Context API, I'm open to it potentially, but it really depends on how much code change would be involved and how much bundle size would actually be reduced. I thought Redux had a very small footprint, but I might be misremembering.

**Comment by Aminehassou** [comment]
I think migrating to the context API is a lot more trouble than it's worth. Redux has a very specific structure and it focuses on maintaining a global state, while the context API still uses component-level state with useReducer. Yes, you can manage global state with the context API but that's usually done for smaller projects. Here's a snippet from the official react docs about the use cases for the context API:

> Theming: If your app lets the user change its appearance (e.g. dark mode), you can put a context provider at the top of your app, and use that context in components that need to adjust their visual look.

> Current account: Many components might need to know the currently logged in user. Putting it in context makes it convenient to read it anywhere in the tree. Some apps also let you operate multiple accounts at the same time (e.g. to leave a comment as a different user). In those cases, it can be convenient to wrap a part of the UI into a nested provider with a different current account value.

> Routing: Most routing solutions use context internally to hold the current route. This is how every link “knows” whether it’s active or not. If you build your own router, you might want to do it too.

> Managing state: As your app grows, you might end up with a lot of state closer to the top of your app. Many distant components below may want to change it. It is common to [use a reducer together with context](https://react.dev/learn/scaling-up-with-reducer-and-context) to manage complex state and pass it down to distant components without too much hassle.

We already manage all of these things with a pretty well-made redux implementation. So I don't think the migration is worth it.
