### ISSUE TITLE
Users should be returned to My Dashboard when they complete a training

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#546]
Currently, we send them back to the Training index, with no guidance on where they should go from there. @thenickcox @bmathews

**Comment by thenickcox** [comment]
@ragesoss If not logged in, where should they go?

**Comment by ragesoss** [comment]
@thenickcox Back to the training index as now, I guess.

**Comment by thenickcox** [comment]
@ragesoss Any sort of notification or message?

**Comment by ragesoss** [comment]
@thenickcox I don't think that's necessary for now.

**Comment by thenickcox** [comment]
closed via 9c7bd0a
