### ISSUE TITLE
Add fallback check for when no contributions are highlighted in ArticleViewer

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5461]
### Current Behavior:
The ArticleViewer's authorship highlighting feature shows which parts of the current version of an article were originally added by course participants. This is reliable for highlighting prose contributions, but typically does not work for cases where the wikitext is exclusively templates (including ref templates). I think this is because the WhoColor system works by adding span tags around each token in the wikitext to embed authorship metadata, then sends it through Wikipedia for rendering to HTML, but templates and other specially-rendered markup elements strip such tags from the rendered output.

Here's an example where two users made contributions (both of which are still present in the live article as of July 26, 2023): https://dashboard.wikiedu.org/courses/UCSF/Foundations_II_(Summer_2023)/articles/edited?showArticle=52655504

In this example, user CarUCSF2025 added a reference, but the ArticleViewer detects no contributions.

### Desired Behavior:

Since the Dashboard already knows which users made edits to an article (at least, when ArticleViewer is used in the context of the Articles tab of a course), we could do a fallback check against the WikiWho API (for example https://wikiwho-api.wmcloud.org/en/api/v1.0.0-beta/latest_rev_content/Atrial_fibrillation/?o_rev_id=true&editor=true&token_id=true&out=true&in=true )to get the wikitext metadata of the current revision to see if a user who doesn't have any attributed HTML contributions actually does still have extant wikitext contributions or not. Then, instead of the current behavior where that user just doesn't get a highlight color, we could show a mouseover or similar message for that user to indicate the situation, eg, "There are contributions from this user in the latest version of the article, but they cannot be highlighted. This usually means that the contributions consist of references or templates, which can't be accurately attributed in HTML."

We only want to make an extra request like that when the first WhoColor request doesn't return any attributed content for one of the course participants who edited that article.

**Comment by Abishekcs** [comment]
@ragesoss i can work on this

**Comment by ragesoss** [comment]
great!
