### ISSUE TITLE
Add-to-watchlist feature fails for a large class

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5462]
The recently-implemented add-to-watchlist feature, accessible via a button on the Students tab of a course page, fails for this course: https://dashboard.wikiedu.org/courses/UCSF/Foundations_II_(Summer_2023)/home

This is probably because there are too many student user pages to be handled in a single request. It can probably be fixed by determining a reasonable maximum number of pages per request, and breaking large courses up across multiple requests.

**Comment by ragesoss** [comment]
@Abishekcs would you like to work on this?

**Comment by Abishekcs** [comment]
@ragesoss Sure :+1:
