### ISSUE TITLE
Create a system for discouraging assignment of specific articles

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5477]
### Current Behavior:
Some specific Wikipedia articles — like [[Boba]] — are subject to repeated assignment by students, but rarely lead to significant improvement. We don't have a way to discourage a student from choosing one of these articles to work on, and it annoys the editors of such articles.

### Desired Behavior:
We need a way that both Wiki Education staff and other Wikipedia editors can mark a specific articles such that it either cannot be assigned for a Wiki Education course at all, or in a way that a student will be actively discouraged from choosing that article (but can still choose to work on it if they acknowledge the warning first).

### Additional context:

One way to implement this would be to use one or two hidden categories on Wikipedia, and have the Dashboard collect the articles in those categories and check against them whenever a new assignment is created.

**Comment by Abishekcs** [comment]
I can work on this @ragesoss.

**Comment by Abishekcs** [comment]
@ragesoss for this should a new hidden category be created on Wikipedia for this purpose, or should an existing hidden category be used?

**Comment by ragesoss** [comment]
A new one!

**Comment by Abishekcs** [comment]
> A new one!

will `Category:Undesirable Wiki Education Articles` be a suitable name for it?

**Comment by pppery** [comment]
https://en.wikipedia.org/wiki/Category:Undesirable_Wiki_Ed_Articles was just deleted at CfD.

**Comment by ragesoss** [comment]
sorry @Abishekcs, I lost track of this and forgot to reply... I suggest making it configurable via application.yml.

We'll need to do some on-wiki discussion before putting into use, but you can use any existing category for testing it out while working on it.

**Comment by ragesoss** [comment]
> https://en.wikipedia.org/wiki/Category:Undesirable_Wiki_Ed_Articles was just deleted at CfD.

Thanks for the note!

**Comment by Abishekcs** [comment]
@ragesoss  No problem, I have just started working on this problem today. As for testing, I will use an existing category, as you mentioned.
