### ISSUE TITLE
Course update info is misleading for non-current courses

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5489]
### What is happening?
On course pages, a small message below the header stats shows info about the update process: when the last update was completed, and (if it's in the future) when the next update is expected.

For a course that ended and stopped receiving updates, but then was updated via a manual update or via the 'Schedule Data Update' button, after the update is complete, the update info says something like "Next estimated update: in 6 days." This happens because it takes the average time between updates for the last 10 updates to estimate the time of next update, but for a course that has ended and is no longer in the update window (by default, 30 days after the end of the course, based on a setting in application.yml), this is misleading because no further updates are expected.

**Comment by ShivangRawat30** [comment]
I would like to work on this issue

**Comment by ragesoss** [comment]
@ShivangRawat30 go for it! let me know if you would like an invite to our Slack chat.

**Comment by ShivangRawat30** [comment]
@ragesoss I would like to join the slack channel.

**Comment by ShivangRawat30** [comment]
@ragesoss can you please link the url to the current problem, it would be really helpful.

**Comment by ragesoss** [comment]
@ShivangRawat30 let me know your email (or send me an email per https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md) so I can send you the Slack invite.

I don't have a link to an example of the problem, but you can replicate it locally by creating a course, running several manual updates on it to generate the update logs, then changing the end date to be at least 30 days ago so that the course is out of update range. You could also manually set the update logs and/or related data for a course. All the relevant data lives in the `flags` column of a course, and here's an example of flags data that includes update logs: https://outreachdashboard.wmflabs.org/courses/wikidata/Ober%C3%B6sterreich_(2023)/course.json

**Comment by ShivangRawat30** [comment]
@ragesoss it's rawatshivang30@gmail.com

**Comment by ShivangRawat30** [comment]
@ragesoss I've sent a mail to contact@wikiedu.org

**Comment by ragesoss** [comment]
> @ragesoss it's [rawatshivang30@gmail.com](mailto:rawatshivang30@gmail.com

Invite sent!

**Comment by aaditya9899** [comment]
To fix this issue, i think we could modify the logic that calculates the next update. we could add a condition to check if the course is still within its update window before calculating and displaying the next update. and i found the code in `statistics_update_modal.jsx` and this shall fix it ig   `if (!isNextUpdateAfter || !futureUpdatesRemaining) ` currently there is only 
`if (!isNextUpdateAfter`...Am i going in right direction @ragesoss

**Comment by aaditya9899** [comment]
i am not able to replicate the issue but can i make the pull request if its okay...

**Comment by ragesoss** [comment]
> i am not able to replicate the issue but can i make the pull request if its okay...

I'd prefer that you figure out how to replicate the issue first. It ought to be possible by manually updating a course record with update logs (for example, by copying them from the example I linked above) and then editing those logs.

Replicating it is necessary to provide before/after screenshots in the PR, and those screenshots are really helpful in providing context for the code when we forget what it does and why it was changed in the future.

**Comment by aaditya9899** [comment]
sure makes sense , on it now !

**Comment by aaditya9899** [comment]
not able to find the flags column....

**Comment by ragesoss** [comment]
```ruby
course = Course.find 1
course.flags
course.update(flags: { ... } )
```

**Comment by aaditya9899** [comment]
ohh they are ruby scripts command i thought it will be something in UI got it now thankx ....but still manually updating it like in this command `course.update(flags: { ... } )`  i will pasting that example log file here complete or can i just put some texts there few times in the same command which will update it  and replicate the bug...

**Comment by aaditya9899** [comment]
I am able to run these commands..
![Uploading sage.jpg…]()

**Comment by aaditya9899** [comment]
hey i tried updating the course description ,event start time end time many timess but still not able to see the last statistics update message under the header..

![Uploading c1.png…]()

**Comment by ragesoss** [comment]
This is based on the `UpdateCourseStats` process, not updates to the attributes like description.

**Comment by MauryanKansara** [comment]
> This is based on the `UpdateCourseStats` process, not updates to the attributes like description.

hey @ragesoss can you send the slack invite? I want to start contributing to this repo. here is my mail: mauryankansaramk@gmail.com

**Comment by ragesoss** [comment]
@MauryanKansara invite sent!

**Comment by alishad846** [comment]
sir please add me in slack channel

**Comment by himadeepthi1** [comment]
@ragesoss , is this issue still open ? I would like to work on this issue .

**Comment by ragesoss** [comment]
@himadeepthi1 sure go for it

**Comment by himadeepthi1** [comment]
@ragesoss  , to check how the update works I created a course manually , but I'm not finding the details of the past update below the header , can you please help on this 
![Screenshot from 2023-12-19 23-25-31](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/133694562/ba1c1a70-356f-4116-aa19-4164c165bad1)

**Comment by fillingtothemomo** [comment]
hey @himadeepthi1 are you still working on this issue? If not I would like to give this a try.

**Comment by ragesoss** [comment]
@himadeepthi1 how did you 'create a few manual updates'?

Normally, after a course goes through the `UpdateCourseStats` process, the `flags` column of the Course record gets updated to include details about the recent stats update cycle. The presence of that update data is what determines the frontend behavior for the update info. Your screenshot suggests that no update data is present.
