### ISSUE TITLE
Use LiftWing instead of ORES in ArticleFinder

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5492]
We need to use the new LiftWing API instead of the now-disabled ORES API, when fetching article quality data from the React frontend.

See `article_finder_actions.js`.

The migration from ORES to LiftWing was recently completed for server-side uses; see `lift_wing_api.rb` for some details on usage, as well as https://wikitech.wikimedia.org/wiki/Machine_Learning/LiftWing/Usage

**Comment by ragesoss** [comment]
> hi @ragesoss can you please help on how i can start contributing in these issues, how to setup project locally

Hi @codebreaker0001 . Instructions for setting up the project locally are in https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md

**Comment by sharon-kathambi** [comment]
Hi @ragesoss, I would like to attempt this issue

**Comment by justiceotuya** [comment]
@ragesoss how do we get to know which model is available? i have tried converting to Liftwing and I am getting this error

https://api.wikimedia.org/service/lw/inference/v1/models/enwiki-articlequality:predict?models=wp10&revids=1175222458%7C1178717228%7C1173765883%7C908481996%7C1177872320%7C1114447757%7C1022916502%7C1167068313%7C1178263693%7C1162049025&callback=jsonp_1696603447179_28957

```
{
  "error": "Model with name enwiki-articlequality:predict does not exist."
}
```

**Comment by justiceotuya** [comment]
i have constructed the poat request but it I am getting an API cors error @ragesoss

**Comment by justiceotuya** [comment]
@ragesoss https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5501
