### ISSUE TITLE
Fully translate the ‘Igbo’ version of the description of the programs and events dashboard.

### ISSUE THREAD

**Issue by Ukwuezepascaline** [WikiEducationFoundation/WikiEduDashboard#5499]
What is happening?

The Igbo translation that explains ‘the Programs and Events dashboard features, has some texts that are yet to be translated.

To Reproduce

 Steps to find the texts:
 1. Go to https://meta.wikimedia.org/wiki/Programs_%26_Events_Dashboard/Using_the_Dashboard
 2. Navigate to the programs and events dashboard section.
3. Locate the ‘Igbo’ translation 
4. Scroll down to Nkowa okwu nke okwu.

 Expected Behaviour 

 All the description is expected to be translated to Igbo language for a more detailed and better understanding of the information.

**Comment by ragesoss** [comment]
Thanks @Ukwuezepascaline! We don't tracking missing translations on GitHub, as we just rely on the translation features on Meta (for documentation) and on translatewiki.net (for interface messages), and translators don't generally interact with the codebase directly.
