### ISSUE TITLE
Add more visual instructions at the "Training Library -> Create a Campaign" guide

### ISSUE THREAD

**Issue by Ibom99** [WikiEducationFoundation/WikiEduDashboard#5500]
### What is happening?
At the "Optional: Create a Program Template" step, it no longer has visual instructions only written instructions, even till the end of the guide.

### To Reproduce

1.  Go to  [Programs and Events Dashboard](https://outreachdashboard.wmflabs.org/)
2. Click on "Training"
3. Scroll down to "Learning and Evaluation"
4. Click on "Create a Campaign"
5. Click on "Start"
6. Then navigate to "Next Page" and follow the guide till "Optional: Create a Program Template"

### Expected behavior
The training steps should continue to display visual instructions till the end of the guide.  After the "Enter Campaign details" step, the following 3 pages had only written instructions, making it take a few seconds longer to identify the buttons instructed to click on.

### Screenshots
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/cb83e4e3-307f-40c7-a5fc-06e95450be40)

![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/020ab08b-f873-4f80-b530-dbc872def9a0)
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/3c89b3e7-ccb7-484f-9362-29039d1b22a4)
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/f6092379-d45d-49ac-9b9a-bf6094eeda17)

**Comment by Ibom99** [comment]
Hi @ragesoss I just created a new issue and I'll love if you can check it out!

**Comment by justiceotuya** [comment]
@Ibom99 so if i understand you well you want that just like how the image is shown in the "enter campaign details page", all other guides should have images that shows what should be done?

it should have both written texts and visual images?

**Comment by Ibom99** [comment]
@justiceotuya Yes. (referring to this particular training module, "Create a Campaign")

**Comment by OnolexTim** [comment]
@Ibom99 and @ragesoss I want to work on this issue. Can I?

**Comment by ragesoss** [comment]
@Ibom99 thanks for opening this issue! Are you working on it?

**Comment by Ibom99** [comment]
@ragesoss  Yes, I’m working on it.

**Comment by Ibom99** [comment]
Hi @ragesoss  here are the visual instructions and some additional written instructions I came up with for the  "Create a Campaign" training module.

Firstly the UI for the "Enter Campaign Details" has changed. The current UI has some more input fields. Such as "Default program type", this displays a drop down menu with the following options; "BasicCourse, Editathon & ArticleScopedProgram". Another new input field are the passcode status for the new programs in the campaign "no passcode, a random passcode & default passcode".


![create campaign new UI](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/6b43f422-46b8-44e7-89c2-23e53e1ac105)

### 
Visual instructions for the "Optional: Create a Program Template" stage.

Step 1 & 2

![Step 1(28)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/8c9f4c19-e5ec-492e-a857-2e95d35d4db7)

Step 3

![Step 2 (29)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/b15b2eb6-fd5a-4384-87d8-7e8ace4a22a3)

Step 4 


![step 3(32)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/3d282fe6-921b-420f-8f36-1d455f3f0a8f)


Visual and additional written instructions for "Create a Program within the Campaign" stage

On the "Create a Program within the Campaign" page,
Follow the first instruction.(Click on "Create Program +")

![step 4 (33)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/7136f8d2-644a-4387-ba9c-059a97886077)

2. Click on the most preferrable program type.(This demo selects the Basic Program type )


![page 2 step 1(35)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/4793f9f7-2f4e-4ce2-809c-3db73afecc42)


3. Fill in the inputs with the appropriate entries and click on "Next".
![page 2 step 2(37)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/96ec1225-193e-47dd-a51e-d6162494a8b6)

4. Enter the starting and ending dates for your program. Fill in the other fields if applicable.
5. Click on "Create my Program!" - Done.


![page 2 step 3 (39)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/2eb35d12-aff8-4f8b-af2b-81196e3097c7)

Visual instructions for the "Add an existing Program to your Campaign" stage.

Step 1 

![page 3 step 1](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/5e510dcb-9e94-4b89-9d57-317766533689)

Step 2 
![page 3 step 2](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/b0f76d9c-0f81-4f29-90df-27007a938079)

![page 3 step 3 (44)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/c3c92dde-2961-477c-90b3-34cb89930aec)

**Comment by ragesoss** [comment]
@Ibom99 thank you! These look pretty good. I would recommend cropping the screenshots to reduce the amount of empty space so that the important parts will be easier to see. If these get added to the training module, the maximum size is not going to be full resolution, so reading some of the text will be hard.

A next step would be to upload screenshots to Wikimedia Commons and then add them to the on-wiki training modules (via the 'wiki source' links on each slide), and then use the 'reload from source' link on the training module index page to refresh the content.

**Comment by Ibom99** [comment]
@ragesoss Thank you! I'll crop the images right away. Should I forward the cropped screenshots here for feedback or I should go ahead and upload them, once they've been cropped?

**Comment by ragesoss** [comment]
@Ibom99 post them here please

**Comment by justiceotuya** [comment]
well done @Ibom99

**Comment by Ibom99** [comment]
@justiceotuya Thank you! 
@ragesoss Please find below the cropped images for review.

![Step 1(28)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/fc8cfc40-2e5f-4d5e-9ca8-a8ea7c2771fc)

![Step 2 (29)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/428b4ac6-a41a-450a-95f8-0dd401b1faab)

![step 3(32)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/7a216a9f-d609-4fda-9a7f-a68d4b1feb11)

![step 4 (33)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/a01f4e41-54c6-4408-ad15-f3ea2dbcc8d5)


![page 2 step 1(35)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/f8df2127-2fc4-4f11-8361-42e85b42e0a9)

![page 2 step 2(37)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/0882ca3e-0a26-42ec-9f33-cc3546ced559)

![page 2 step 3 (39)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/55633dab-dfbc-423e-af31-6ab5baddfa47)


![page 3 step 1](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/d1685e67-9815-4101-9afd-e7ac8073cc27)


![page 3 step 2](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/8d133dcb-f6a2-4bd8-9c42-d9431ea7fd03)


![page 3 step 3 (44)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/62e10107-efb7-4d2b-8daf-39e4b6e20e67)

**Comment by ragesoss** [comment]
Cool, thanks! Please give updating the training modules a try!

**Comment by Ibom99** [comment]
@ragesoss thank you!  I will get started on that. 

I will also like your feedback on [#5505](https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/5505) please.

**Comment by Ibom99** [comment]
Hi @ragesoss I have successfully updated the training module slides, I would like your feedback, please.
https://outreachdashboard.wmflabs.org/training/learning-and-evaluation/create-a-campaign

My visual guides start from here:
https://outreachdashboard.wmflabs.org/training/learning-and-evaluation/create-a-campaign/create-a-program-template

**Comment by ragesoss** [comment]
These look great! Nice work.

**Comment by Ibom99** [comment]
@ragesoss Thank you so much for your guidance!!
