### ISSUE TITLE
Inconsistent Page Highlighting in Campaign Navigation Bar

### ISSUE THREAD

**Issue by justiceotuya** [WikiEducationFoundation/WikiEduDashboard#5514]
### What is happening?
There is an issue on the campaign page where the navigation bar does not consistently indicate the current page the user is viewing. The navigation menu includes items such as Home, Courses, Articles, Students, ORES, and Alerts, but only the "ORES" and "Alerts" pages are highlighted when the user is on those respective pages.

### To Reproduce

To replicate this issue, follow these steps:

- Navigate to the "Explore" menu in the navigation bar.
- Scroll down to the "New Campaign" table and select any row.
- On the subsequent page, observe that the "courses" tab on the campaign page is not marked as active or highlighted.
- Click on the other tabs, and you will notice that only the "ORES" and "Alerts" tabs are highlighted.

### Expected behaviour

The campaign navigation bar should consistently highlight the page the user is currently viewing by applying the "active" or selected state to the corresponding navigation item

### Screenshots
<img width="1800" alt="Screenshot 2023-10-19 at 7 42 43 AM" src="https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/17678464/c1e7dd51-bba2-45ea-b3cc-e25876089662">

<img width="1800" alt="Screenshot 2023-10-19 at 7 44 51 AM" src="https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/17678464/a7abf551-3432-4d80-8356-00bcee0f7cd6">

### System Information

 - OS: Mac Os
 - Browser Chrome
 - Version Sonoma 14.1

**Comment by RWUBAKWANAYO** [comment]
@justiceotuya and @ragesoss, I'd like to handle this issue.  May I proceed?
