### ISSUE TITLE
Documentation Inconsistency: Cloning a Program

### ISSUE THREAD

**Issue by Chioma-data-analytics** [WikiEducationFoundation/WikiEduDashboard#5515]
**What is happening?**
I observed that the instruction of cloning a program in the Documentation does not match the actual process particularly in Line 2 and Line 7 of Cloning a Program. 

The documentation shows in line 2 and 7:
•	Click “Create New Program”
•	Click “Create my Program!”

The actual process is:
•	Click **“Create an Independent Program”**
•	Click **“save”**

**Comment by Chioma-data-analytics** [comment]
@ragesoss Can I make the changes?

**Comment by ragesoss** [comment]
@Chioma-data-analytics yes, please do!

**Comment by Chioma-data-analytics** [comment]
Thanks @ragesoss changes effected.
