### ISSUE TITLE
Issue with Conditional Question Options Display

### ISSUE THREAD

**Issue by Abishekcs** [WikiEducationFoundation/WikiEduDashboard#5517]
### What is happening?

When selecting a question for which the conditional question should appear and subsequently changing the question, the dashboard continues to display the options (answers for which the conditional question should appear) for the initially selected question in addition to the options for the newly selected question. This behavior is unexpected, as it should only show the options to reflect the currently selected question for the conditional question.

### To Reproduce

Make sure you're logged in and have administrator permissions

1. Go to `/surveys`.
2. Click on the "Question Groups" tab.
3. Click "New Question Group."
4. Create the question group (group details are irrelevant).
5. Edit the question group, create two questions (e.g., Q1 and Q2).
6. While creating the third question (e.g., Q3), choose the `Conditionally show this question.`
7. From the `Select a question`, select any question (e.g., Q1) out of the two previously created questions.
8. Then again select a different question (e.g., Q2).
9. After that, click on `Select an Answer` ,and it will show the answers for both Q2 and Q1.

### Expected behavior

The conditional question options should show only the answer related to the currently selected question

### Screenshots

https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/8e5f56eb-3564-406e-8ed4-d17ba115acd5

![Bug](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/239fbe50-bc4f-45b4-8b95-74dd6bebbf96)

### System Information

 - OS: Ubuntu 22.04.3 LTS
 - Browser: Google Chrome Version 116.0.5845.187 (Official Build) (64-bit)

**Comment by ragesoss** [comment]
This bug likely lives in the survey admin JavaScript or a related file... essentially a big ball of jquery spaghetti code. Fixing it could be a fun adventure for someone who wants to dive into jquery.

**Comment by Abishekcs** [comment]
> This bug likely lives in the survey admin JavaScript or a related file... essentially a big ball of jquery spaghetti code. Fixing it could be a fun adventure for someone who wants to dive into jquery.

I will try to fix it.
