### ISSUE TITLE
Missing Labels for "Assign an Article" and "Assign a Review"

### ISSUE THREAD

**Issue by Chioma-data-analytics** [WikiEducationFoundation/WikiEduDashboard#5520]
### What is happening?
There are no visible labels for **"Assign an Article"** and **"Assign a Review."** Instead, only tooltips provide information about these functions.

### To Reproduce

1. Go to My Dashboard
2. Click on Program that has an Editor
3. Click on Editor's Tab
4. Click on the Editor's name

**You will find the unlabelled buttons represented with the symbol "?"** right under the "Add/Remove Editors"
Note: assign to an editor other than yourself 

### Expected behavior
Provide clear labels for both buttons 

### Screenshots
Screenshot attached

### System Information

 - OS: [Windows 11 Pro]
 - Browser [Chrome]
 - Version [10.0.22621 Build 22621]

### Additional context
To improve user accessibility, it's important to make the buttons for "Assign an Article" and "Assign a Review" **more readily visible and easy to find.**

![Screenshot (672)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/113908370/15c9b8af-0d65-4fc4-a9fd-26b790b4d127)

**Comment by ragesoss** [comment]
Hmmm... I'm not sure what is causing this for you. The way it's supposed to be is like this:

![assign remove](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/848483/b7092528-5df8-4b0b-83bf-4378b32e0ada)

**Comment by Chioma-data-analytics** [comment]
@ragesoss Okay, will check it through. Thanks

**Comment by Chioma-data-analytics** [comment]
@ragesoss It's good now, just had to close and open the dashboard again. Thanks
![Screenshot (673)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/113908370/4529334f-9b8a-4c89-bbf6-622206cf91ac)
