### ISSUE TITLE
Admins should be able to email the instructors of a course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5524]
### Current Behavior:

When a Wiki Education staff members wants to contact all the instructors of a course, the easiest way is currently to copy each of their email address and use a separate email client. It would be more convenient to be able to send an email message directly from the course page.

### Desired Behavior:
There should be a button in Actions that opens a text box and allows an admin to write a message that will be emailed to all the instructors of the course. The email should look good, with minimal formatting using similar styling to existing emails sent by the Dashboard, and should have a reply-to for the admin who sends the message.

**Comment by tushar-glitch** [comment]
Hi @ragesoss, looks like an interesting one to solve! Can I work on this issue?

**Comment by ragesoss** [comment]
@tushar-glitch sure go for it.

**Comment by prathamVaidya** [comment]
@ragesoss are editors and instructors same? What page do you want the Button to send notification to instructors. I was thinking maybe here (if editor means instructors):

![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/61202986/c8c1ea82-f9ff-460d-a3cf-60d98c267d48)

**Comment by ragesoss** [comment]
@prathamVaidya there are two main production contexts: Programs & Events Dashboard ( outreachdashboard.wmflabs.org, corresponding to the `wiki_education: false` setting) and Wiki Education Dashboard (dashboard.wikiedu.org, corresponding to `wiki_education: true`). There is some different terminology between them.

'Editor' on P&E Dashboard is the same as 'Student' in Wiki Education Dashboard (role 0 in a CoursesUsers record), while 'Instructor' is the same as 'Facilitator' (role 1 in a CoursesUsers record).

For this issue, the feature is only intended for Wiki Education Dashboard, and the Home tab (probably in the Actions section) is where I think the button should go.

**Comment by ragesoss** [comment]
(I think that FAQ is still accurate; it is specifically for Wiki Education Dashboard.)

**Comment by prathamVaidya** [comment]
Thanks @ragesoss, Please check the PR.

**Comment by Brajesh1213** [comment]
I would like to work on this issue may i

**Comment by ragesoss** [comment]
@Brajesh1213 there is already an open PR that I have not reviewed yet. Issue #5530 is a good one. Please only work on one at a time.

**Comment by prathamVaidya** [comment]
Issue can be closed. Feature added in https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/5545
