### ISSUE TITLE
Add admin-only Notes feature for courses

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5526]
### Current Behavior:
There is no way within the Dashboard for Wiki Education admins to record notes about courses they are supporting.

### Desired Behavior:

There should be a way for an admin to edit a Notes field related to a course, see that existing notes are already present from the Home tab.

### Related Files & Code:

It think the best option for implementing this would be to add a new CourseNote model and table, and use a single editable field to record the notes for a given course.

**Comment by Abishekcs** [comment]
I am working on this

**Comment by Abishekcs** [comment]
@ragesoss, for this feature on the Home tab, how about adding a button under `Actions`  labeled  'Course notes,' as shown in the screenshot? Clicking on it would take the admin to a dedicated notes page, displaying existing notes and providing options to create new ones. Will something like this work?

![Screenshot from 2023-12-11 15-43-54](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/8d1f2560-3e51-4840-892e-d8610d607c80)

**Comment by ragesoss** [comment]
I was imagining something a little more prominent, such as an icon in the course navbar next to the Get Help button, but I'll ask my colleague to have a look.

**Comment by iramjohn** [comment]
@Abishekcs - I think it would be easiest to use if it was in the upper right corner in the box with the "Greet Students" and "Mark as Reviewed" buttons. 

@ragesoss - could we trim the explanatory text about the "Mark as Reviewed" button to something like "Not yet reviewed"? I'd prefer if that box didn't get much bigger, since as it currently is I can see it all without scrolling most of the time (and as absurd as it sounds, not having to scroll saves a non-trivial amount of time and effort, especially when you're looking at a large number of course pages at once.

<img width="1140" alt="Screenshot 2023-12-11 at 2 14 07 PM" src="https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/4268892/3bf2a562-d46d-40bd-8a05-5b3e51e3c1db">

**Comment by Abishekcs** [comment]
@iramjohn Okay, I will move the button to the upper right corner.

@ragesoss  about this part  (Clicking on it will take the admin to a dedicated notes page, where they can view existing notes and create new ones) will this be okay,  or something else?

**Comment by ragesoss** [comment]
@Abishekcs ideally, I think it ought to open a model rather than navigating to a different page. but if it's significantly easier to implement as a separate page, that's okay; it ought to be possible to switch the UI later.

**Comment by Abishekcs** [comment]
@ragesoss  should the Notes field have a rich text or plain text editor?

**Comment by ragesoss** [comment]
@Abishekcs I think plain text is fine.

**Comment by Abishekcs** [comment]
> @Abishekcs I think plain text is fine.

Okay

**Comment by Abishekcs** [comment]
@ragesoss For the notes feature, only the admin should be able to create them, and students should only be able to read them?

**Comment by ragesoss** [comment]
The notes are internal notes only intended for admins — either as reminders for the admin writing them, or to share information between admins.

**Comment by Abishekcs** [comment]
> @Abishekcs - I think it would be easiest to use if it was in the upper right corner in the box with the "Greet Students" and "Mark as Reviewed" buttons.
> 
> @ragesoss - could we trim the explanatory text about the "Mark as Reviewed" button to something like "Not yet reviewed"? I'd prefer if that box didn't get much bigger, since as it currently is I can see it all without scrolling most of the time (and as absurd as it sounds, not having to scroll saves a non-trivial amount of time and effort, especially when you're looking at a large number of course pages at once.
> 
> <img alt="Screenshot 2023-12-11 at 2 14 07 PM" width="1140" src="https://private-user-images.githubusercontent.com/4268892/289645210-3bf2a562-d46d-40bd-8a05-5b3e51e3c1db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjUzNzEsIm5iZiI6MTcwNTc2NTA3MSwicGF0aCI6Ii80MjY4ODkyLzI4OTY0NTIxMC0zYmYyYTU2Mi1kNDZkLTQwYmQtOGEwNS01YjNlNTFlM2MxZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMTUzNzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTIzYjMzOWMxNTRkN2RhYjlmZGRhODllMDE2N2NjM2EwNGJmNDYyMWNjYTk4MGExMDMyNzMyMWRmYmQ2ZjIyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rnsp_x7DuQpf7gv4si10Mf2HPiTBZTQ1U_0jABo8QL8">

@ragesoss  Regarding the `admin note` icon/button, if it were placed in the upper right corner along with the "Greet Students" and "Mark as Reviewed" buttons as mentioned by @iramjohn, then the `admin note` icon/button would only be accessible to`Wiki Ed Staff`, not the admin. I am confused about this because in the UI, only `Wiki Ed Staff` have access to the upper right corner box. So, should the user be an `admin and a Wiki Ed Staff` or only `admin` to access the admin notes.

**Comment by Abishekcs** [comment]
@ragesoss and @iramjohn, could you please check this video and let me know if it works for the UI -


https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/24f08d85-0de2-4416-b554-32707490bd50

**Comment by ragesoss** [comment]
@Abishekcs yes, your question is clear! I think the right way to handle this would be to change the condition for rendering AdminQuickActions to look for admin rather than staff, and then only render the 'Mark as Reviewed' and 'Greet students' buttons for staff. All staff will be admins, but some admins won't be assigned to the course (which is what isStaff is based on). The new feature should apply to all admins, but the other two buttons are specific to the people assigned to support that course.

**Comment by ragesoss** [comment]
The UI looks fine to me!
