### ISSUE TITLE
"Arrange Blocks" button should be renamed "Rearrange Timeline"

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#553]
It's not necessarily clear to users what a "block" is, and that this is how they would reorder the things in their timeline.

**Comment by rileywho** [comment]
Would "Arrange Timeline" work? Trying to avoid the word rearrange. It implies that you already did something.

**Comment by bmathews** [comment]
I think I'd vote for `Arrange Timline`, if we were having a vote.

**Comment by ragesoss** [comment]
Arrange Timeline works for me.
