### ISSUE TITLE
Create an Independent Program - quits when trying to select hours/minutes before the date.

### ISSUE THREAD

**Issue by ujjwalpathaak** [WikiEducationFoundation/WikiEduDashboard#5532]
### What is happening?
When trying to create a new program and selecting dates for start/end of activity tracking etc... when not done in CHRONOLOGICAL ORDER quits the process and returns to main screen.

### To Reproduce

> Steps to reproduce the behavior:
> 1. Go to 'Dashboard'
> 2. Click on 'Create an Independent Program'
> 3. Click on 'Basic Program'
> 4. Fill in details. Click Next
> 5. Try selecting minutes before selecting the hours or hours before selecting the date.
> 6. See error - it would quit the process

![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/92005669/86233b1f-b870-4451-b55a-f894f8a8d685)

### Expected behavior
> The other fields should be disabled while the prerequisite isn't met

**Comment by ujjwalpathaak** [comment]
Can I work on this issue? I have figured out the problem and thinking about a solution for the same.

**Comment by ujjwalpathaak** [comment]
Hi @ragesoss can you have a look at this and provide any feedback necessary

**Comment by ragesoss** [comment]
Nice job spotting this bug! I'm surprised we never caught it before.
