### ISSUE TITLE
In Arrange mode, 'Add Block' should not be an option.

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#554]
When you add a block in this mode, there is no way to title it or add content, and it violates the separation between editing content and rearranging content. We could also get rid of 'Delete Week' in that mode, although it makes a little more sense. What do you think, @rileywho ?

**Comment by rileywho** [comment]
Yes. We plan on having the add block action be disabled in the mode. I think the delete week action should stay because its still relevant to the primary action. (If I'm deleting week 2, but I want to save a block. I can go into arrange mode, move the block, then immediately delete the week)
