### ISSUE TITLE
Overlapping of campaign_navbar at the desktop view on language selector

### ISSUE THREAD

**Issue by Sahityaaryan** [WikiEducationFoundation/WikiEduDashboard#5546]
### What is happening?
 Overlapping of campaign_navbar at the desktop view over the language selector at the campaign page

### Expected behavior
 The language selector should be over the campaign navbar

### Screenshots
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/115429795/d1f4acfb-5aeb-4af3-b548-249b62336964)

**Comment by Sahityaaryan** [comment]
@ragesoss verify it and I will make a PR.

**Comment by ragesoss** [comment]
Yeah, I've seen this happen before. The sticky navbars are tricky to make play nicely with the main navbar. A PR is welcome!

**Comment by Sahityaaryan** [comment]
Sure

**Comment by himadeepthi1** [comment]
Hello ! @ragesoss , can I work on this ?

**Comment by ragesoss** [comment]
We already have an open PR for this, which I have not reviewed yet but likely fixes the issue.

**Comment by himadeepthi1** [comment]
OK , then I will look into other issues , @ragesoss  please send slack invite, it would be really helpful

**Comment by himadeepthi1** [comment]
My email address is himadeepthisayani@gmail.com

**Comment by himadeepthi1** [comment]
Hi , @ragesoss , can you please send me slack invite, my email address is himadeepthisayani@gmail.com
