### ISSUE TITLE
Grading should be folded into blocks, instead of handled separately.

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#555]
We should probably get rid of the Gradeable model altogether and store the grades on the blocks. And UI-wise, they should be editable from the normal block editing mode, rather than separately at the bottom.

**Comment by thenickcox** [comment]
+1 This would simplify a good number of things.

**Comment by ragesoss** [comment]
Also, when this change gets made we should also let blocks specify their units for the grading value: points or percent.

**Comment by ragesoss** [comment]
Done! (The points vs percent feature has not been implemented, but I'm not sure it's really necessary.)
