### ISSUE TITLE
Comment for UntrainedStudentsAlert is wrong

### ISSUE THREAD

**Issue by pppery** [WikiEducationFoundation/WikiEduDashboard#5551]
https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/dc125aaccb2e2e5b69b5c7174ab8154e2a40e2dd/app/models/alert_types/untrained_students_alert.rb#L23

This seems to have been copied from somewhere else and doesn't make sense here

**Comment by nitish-singh07** [comment]
I am interested in working on this issue.
