### ISSUE TITLE
Improvement in Language Picker

### ISSUE THREAD

**Issue by PR4NJ41** [WikiEducationFoundation/WikiEduDashboard#5557]
### What is happening?
The Language Picker gets hidden due to Campaign Navigator.

<img width="1470" alt="s1" src="https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/96368921/a46ce4b1-30bb-4268-a073-c2615c1691ec">

### To Reproduce

1. Go to https://outreachdashboard.wmflabs.org/campaigns/wmes_2024/overview
2. Click on Drop down Menu of Language Picker.

### Expected behavior

<img width="1470" alt="s2" src="https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/96368921/4b34e7b5-79cf-489e-ae95-6e210ab923a6">

**Comment by ragesoss** [comment]
@PR4NJ41 there's already an open PR that I haven't had a chance to test yet which addresses this bug.

**Comment by ragesoss** [comment]
see  #5546

**Comment by ragesoss** [comment]
closing as duplicate
