### ISSUE TITLE
Responsive UI for the 'Training' Page in Mobile View

### ISSUE THREAD

**Issue by PR4NJ41** [WikiEducationFoundation/WikiEduDashboard#5558]
### What is happening?

Currently the UI is not Optimized for mobile view & looks cluttered as shown in the following Picture.

<img width="904" alt="s3" src="https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/96368921/46b359b2-173f-4848-bcc9-4828cc680b46">

### To Reproduce

1. Go to [Training Page](https://dashboard.wikiedu.org/training)
2. Use Inspection Mode and Select any Mobile device. I Used iPhone XR for this Purpose

### Expected behavior

This is the UI i am proposing. It looks much better & less cluttered.

<img width="902" alt="s4" src="https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/96368921/1289469c-3e52-4e2d-82fc-839a60bd5f53">

**Comment by ragesoss** [comment]
@PR4NJ41 yes, please do

**Comment by akashwarrior** [comment]
can i fix this issue, or anyone is assigned to fix this issue?
