### ISSUE TITLE
On the P&E Dashboard "Articles" tab of a Program add  informative text to the "See more" button on hover 

### ISSUE THREAD

**Issue by Ibom99** [WikiEducationFoundation/WikiEduDashboard#5569]
### Current Behavior:
Currently on the Dashboard before a user can see or navigate through large sets of articles available in a program using pagination, the "See more" button needs to be selected before the pagination reflects the following number of subset articles (500 more articles). After the subset of 500 articles is reflected in the pagination and the user still wants to navigate through more articles, they need to select the "See more" button again, before the pagination reflects the next set of articles and so on till all articles have loaded (the "See more" button disappears, once the full set of articles have loaded) and are reflected in the pagination.

### Desired Behavior:
On the "Articles" tab of a program the "See more" button on hover should have informative text, informing the user of the relationship between the button and the pagination beside it reflecting more loaded articles. 
POSSIBLE INFORMATIVE TEXT ="Click "See more" to load the next subset of 500 articles and continue the seamless navigation through the articles with the pagination on the left."

### Additional context:
![Screenshot (88)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/4879f5bf-5549-4422-b499-1dc7fd936179)

In the image below the "See more" button has been clicked on. The pagination range on the left increases and the numbers under the "See more" button increase as well. This shows that the next subset of articles have loaded and the pagination on the left reflects the loaded subset of articles.

![Screenshot (89)](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/104465078/67d4f176-7440-4d22-9114-890a4d1234c8)

**Comment by Ibom99** [comment]
Hi @ragesoss @Aminehassou what file in the codebase can this feature be implemented?

**Comment by ragesoss** [comment]
@Ibom99 the 'Articles Edited' view is from the `ArticleList` component (`article_list.jsx`), and the pagination UI is the `PaginatedArticleControls` component (`PaginatedArticleControls.jsx`) within the list component.

**Comment by MrBlackGhostt** [comment]
@Ibom99 i want to contribute on this can i work on it

**Comment by ragesoss** [comment]
Sure. I think the text will need some changes, but if you open a PR that will make it easy to discuss the wording.
