### ISSUE TITLE
Responsive Design needed (Log in with Wikipedia  & Sign up with Wikipedia are not centered inside the button )

### ISSUE THREAD

**Issue by shruti862** [WikiEducationFoundation/WikiEduDashboard#5577]
![Screenshot from 2024-01-08 23-55-33](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/135260908/b04ed8bf-ceb4-49d9-afa9-dc2aa036daf6)

**Comment by ragesoss** [comment]
Looks like you have an asset problem with your development environment; there are supposed to be "W" logos in that blank space on the left of each button.
