### ISSUE TITLE
Trix does not load on Debian development environment

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#559]
I started poking around locally with the timeline revamp for the first time, and even after deleting and reinstalling my node modules, I'm finding that the WYSIWYG editor does not load at all for me.

This is on both Iceweasel and Chromium. There are no console errors.
![no trix](https://cloud.githubusercontent.com/assets/848483/11905781/0ca1bb82-a57d-11e5-8cd1-a3474e8d5b67.png)

**Comment by bmathews** [comment]
You'll have to do a `bower install` to get trix. Let me know if that doesn't fix it for you!

**Comment by ragesoss** [comment]
Aha!

**Comment by ragesoss** [comment]
That was it.
