### ISSUE TITLE
sometimes calendar day clicks don't select/deselect dates

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#560]
In Iceweasel (but not Chromium) I'm seeing a new weird behavior with the calendar datepicker.

Some dates are not responding to clicks, depending on which other dates are in which states. I seem to be able to replicate it consistent by choosing one day of the week (eg, Wednesday) and then try to black out any of those dates. However, if I mark another date in that week (say, Thursday) and then try the Wednesday again, it works as expected. Super weird.

**Comment by thenickcox** [comment]
When you say "new," I assume you mean you haven't seen this before. This could be related to afa2773. I'll see if I can replicate on OSX Firefox.

**Comment by ragesoss** [comment]
That's right. New to me... but I definitely would have noticed it if it was there before last week or so on staging.

**Comment by thenickcox** [comment]
Unfortunately, not able to replicate on OSX.

**Comment by ragesoss** [comment]
I can only replicate it during course creation. If I edit the dates afterwards, this does not occur.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/848483/11938842/8d884408-a7d2-11e5-9691-19305e0bb383.gif)
