### ISSUE TITLE
Duplicated zh-hans, zh-hant, zh-CN, zh-TW in config/locales since f3ef1b4

### ISSUE THREAD

**Issue by winstonsung** [WikiEducationFoundation/WikiEduDashboard#5627]
### To Reproduce

* Go to https://dashboard.wikiedu.org
* Click on the language selector
* Scroll down to "中文"
* See error (Picture 1)

### Expected behavior

Only "zh-hans and zh-hant" or "zh-CN and zh-TW" options (Picture 2)

### Screenshots

Picture 1:

![Duplicated entries](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/52590365/693e9bc9-4492-4909-9650-07b5df4cdcbf)

Picture 2:

![Expected](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/52590365/0358cc62-856d-4663-b276-0d9ed4e7e053)

### System Information

* OS: Windows 10 (x64)
* Browser: Chrome, Firefox

### Additional context

* Started from f3ef1b44bc9bc6f92eae03369c0bc97430a3e8da

**Comment by ragesoss** [comment]
@winstonsung can you explain more about why this is the expected behavior? The set of supported languages is based on the locale files which come from @translatewiki, and it appears we've had translators contributing to all four locales, but I don't have a clear understanding of the overlap between them.

**Comment by winstonsung** [comment]
translatewiki already disabled zh-cn and zh-tw a long time ago (August 9, 2012) and the 2 files won't receive any further updates, thus become outdated translations.

https://github.com/wikimedia/translatewiki/blob/b90deeb/mw-config/TranslateSettings.php#L208-L209

https://github.com/wikimedia/translatewiki/commit/94541c3#diff-df22c35f95d7cce966011d7a2c9ea556d7feda5145f53415420f02f687aa1da3R236

**Comment by ragesoss** [comment]
Ah! Thank you!

**Comment by winstonsung** [comment]
My apologies, translatewiki actually export zh-CN and zh-TW by using the YAML config file.

https://gerrit.wikimedia.org/g/translatewiki/+/e2a5459/groups/Wikimedia/WikiEduDashboard.yaml#14

We should do it in the opposite way.

**Comment by winstonsung** [comment]
Finally passed:

https://github.com/winstonsung/WikiEduDashboard/actions/runs/8092196645

**Comment by winstonsung** [comment]
(status: check after deployment)

**Comment by ragesoss** [comment]
I've deployed this now.

**Comment by winstonsung** [comment]
Duplicated issue fixed.

Just discovered that it doesn't recognize BCP 47 `zh-Hans-CN`/`zh-Hant-TW` and only detect legacy `zh-CN`/`zh-TW`.
