### ISSUE TITLE
Adding a new week fails.

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#563]
Not sure when this regression was introduced. Fixing.

**Comment by thenickcox** [comment]
This was following the removal of week titles. A new week was sending a title attribute, which wasn't recognized by the API, so the save failed.

**Comment by ragesoss** [comment]
It'd be great to have a mocha test for that.

**Comment by thenickcox** [comment]
It spans across too many components, so how about this: e73a3d0

**Comment by ragesoss** [comment]
LGTM.
