### ISSUE TITLE
Refactor and fix replica_spec 'API Requests > returns a list of existing articles'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5647]
### What is happening?
In `spec/lib/replica_spec.rb`, the 'returns a list of existing articles' (currently starting on line 88) does too many things and is unreliable.

See the TODO comment for more details. It should be broken up into a separate test for each article and should more explicitly look for the expected namespaces of each article.

It's also currently broken (and marked pending), so along the way to fixing it you will likely figure out which article title is currently causing a problem and fix that.

**Comment by om-chauhan1** [comment]
@ragesoss 
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/1cdce9f4-28df-4614-835f-1e5345fbdc33)

Sir, as clearly shown in the image that the api is returning all the existing articles in response irrespective of which article title is provided in the parameter. 
I addressed this issue by implementing a filter to include only the articles requested and also modularized the test into smaller tests, each focusing on individual articles.
Kindly let me know if i am missing anything.

**Comment by ragesoss** [comment]
@om-chauhan1 I suspect that you are seeing a replayed VCR response. You need to delete the `fixtures` directory and/or use a different cassette name to force VCR to record a new response. I guess because it's a POST request, VCR does not treat it as a different request when only the POST data changes.

**Comment by om-chauhan1** [comment]
@ragesoss  thanks, now i understand that's why i was seeing a list of previously fetched articles again and again.
Now, after giving unique cassette name to each test case, i found that it was only "Autism" article that is leading to the failure of previous test case. As it now only exists in  2 namespaces and in previous test case we are looking for it in 3 namespaces.
