### ISSUE TITLE
`namespace_stats_spec.rb` is slow and flaky

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5660]
The feature spec `namespace_stats_spec.rb` takes too long to run (eg, 39 seconds for me locally, after deleting VCR fixtures) and sometimes fails on CI because of a net timeout error. This is likely because of all the network requests that happen during the `manual_update` that happens at the start of the test. (It runs very quickly if the network requests are already recorded in a VCR fixture from an earlier test run.)

Since this is a frontend test intended to make sure the namespace stats are rendered properly, and we're confident that the backend side of pulling in data and generating records for namespace stats is okay, the best option to fix this test would probably be to generate appropriate namespace data directly during test setup instead of relying on pulling data from production servers during the test via `manual_update`.

**Comment by cyrillefr** [comment]
Hello @ragesoss ,

May I work on this one ?

**Comment by ragesoss** [comment]
@cyrillefr sure!
