### ISSUE TITLE
Improvement in the UI of Difference Viewer

### ISSUE THREAD

**Issue by PR4NJ41** [WikiEducationFoundation/WikiEduDashboard#5663]
### Current Behavior:
Date section looks cluttered. If we move the Date section downward then it will look more nice and stuctured. It can be made bold if desired.

### Before
![Before](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/96368921/7bae80b8-ba27-41aa-a536-aa00e194ff50)

### After
![After](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/96368921/c5008f87-a551-46a2-8b01-09720cf3c847)

**Comment by ragesoss** [comment]
I like it!
