### ISSUE TITLE
Training - Misc. Changes

### ISSUE THREAD

**Issue by rileywho** [WikiEducationFoundation/WikiEduDashboard#567]
- h1: Decrease margin bottom to 10px
- Training category h3: remove letter spacing
- Training category p: change line-height to 1.5
-  Card padding: 15px global
- Icon-container: padding = 10px 11px

![wiki_education_foundation_dashboard](https://cloud.githubusercontent.com/assets/2120466/11945630/e5c83586-a806-11e5-91f0-1747757461bc.png)

**Comment by ragesoss** [comment]
Looks good to me. @rileywho: note that this also modifies the header spacing of the module overview pages, both for the name and description, and for the table of contents. Is that intended and/or okay?

## Before:
![old training style](https://cloud.githubusercontent.com/assets/848483/12869565/6751eaac-ccd8-11e5-81cb-3f20038e9205.png)

## After:
![new training style](https://cloud.githubusercontent.com/assets/848483/12869568/7358c0aa-ccd8-11e5-9f28-e2ab84a98c21.png)

**Comment by AbdealiJK** [comment]
@ragesoss I was worried about that too - but wasn't sure if the design team wanted them to be different or not.
Would you like me to modify the pull request to have 2 distinct css classes for these two cases ?

**Comment by ragesoss** [comment]
Yeah, that'd be great!
