### ISSUE TITLE
Moving a block, then deleting the week it was in, then saving, results in error and loss of block

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#570]
@thenickcox @bmathews

Similar to #541 

1. In a course with a timeline, click 'Arrange'
2. Move the all the blocks from the first week into the second week.
3. Delete the now-empty first week.
4. Save.

This results in an error, and upon refreshing you will find that the blocks from the first week got destroyed.

At least for now, I think the solution is to disabled 'Delete Week' in Arrange mode. Then a follow-on enhancement (but not high priority) would be to enable a working version of Delete Week in Arrange mode. (Per the earlier discussion with @rileywho, all else equal, it makes sense to be able to delete a week from Arrange mode.)

**Comment by ragesoss** [comment]
That's untested, but should do it.

**Comment by thenickcox** [comment]
@ragesoss Is there an issue filed for the enhancement? I don't see it.

**Comment by ragesoss** [comment]
@thenickcox Not yet. I will now.
