### ISSUE TITLE
'Email Instructors' feature should have 'BCC to Salesforce' option just like Ticket replies

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5700]
We recently added an option to email instructors from the course page. It would be very useful to also add 'BCC to Salesforce' to this by default, as that will help us keep track of communication we do with a given instructor more easily.

(It should work the same way as in the Ticket system, where 'BBC to Salesforce' is checked by default in the UI but can be unchecked to disable it for an individual message.)

**Comment by psankhe28** [comment]
@ragesoss Can i work on this issue ?

**Comment by ragesoss** [comment]
@psankhe28 sure. look at the way this works on the Ticket system (`/tickets/dashboard`) for the example to follow.

**Comment by psankhe28** [comment]
Can you please confirm if the file where the changes need to be done is `/app/mailers/instructor_notification_mailer.rb`. I am not sure if I have found the right file.

**Comment by ragesoss** [comment]
@psankhe28 yes, that's one place that will need to be changed. it should be optional (enabled by default), though, just like on tickets.

**Comment by psankhe28** [comment]
> @psankhe28 yes, that's one place that will need to be changed. it should be optional (enabled by default), though, just like on tickets.

Okay, thanks!

**Comment by psankhe28** [comment]
Hello @ragesoss, I apologize for my recent inactivity as I had been occupied with mid-semester exams. Could you please guide me on accessing a course page? I've encountered an issue where I created a program using one account but couldn't find the option to join it using another account, particularly in sending emails. Can you assist me with this matter?

**Comment by psankhe28** [comment]
Thanks, I will try this.

**Comment by psankhe28** [comment]
I've created one user as an instructor who has created a course, and another user as an admin. However, I'm unable to locate any options for sending emails. I understand this might be a lot to ask, but could you please assist me? Thank you!

**Comment by ragesoss** [comment]
@psankhe28 sure. This feature is only enabled in Wiki Education mode, and I think you are not using that mode. Change the `wiki_education` value in `application.yml` and see if that gives you access to the feature.

**Comment by psankhe28** [comment]
It worked, thanks!

**Comment by prathamVaidya** [comment]
Looks like no one is active. I'll take the task.

**Comment by Formasitchijoh** [comment]
@ragesoss can i take up this issue,

**Comment by ragesoss** [comment]
I lost track of this and I can't tell why the build failed. I recommend starting from @prathamVaidya's open PR and seeing if it is in working shape.

**Comment by Formasitchijoh** [comment]
Alright, thank you, @ragesoss  Please I would like to confirm .
- Is alert in this case is done by the  `InstructorNotificationMailer`?
if so I have tried sending an email to the instructors of a course i have created i get the success alert but the emails are not received, I realized mail_gun is used for testing the email sending process is there a configuration i need to do, or any step to help me proceed

**Comment by ragesoss** [comment]
Yes, this is done by `InstructorNotificationMailer`.

Yes, I think it's fine for the alert to have no target user, although I suppose we could use that field to indicate which user did the sending of the message.

**Comment by Formasitchijoh** [comment]
Alright, then

**Comment by ragesoss** [comment]
"regarding the alert not being received by the instructors in their emails" - I'm not sure what you're referring to here.

**Comment by Formasitchijoh** [comment]
> "regarding the alert not being received by the instructors in their emails" - I'm not sure what you're referring to here.

I mean the alerts are not received by the instructors of the course when they are sent, and i am guessing they receive it through email.

**Comment by ragesoss** [comment]
That's correct.

**Comment by prathamVaidya** [comment]
Regarding my existing PR, I think it was working and the build was failing for an unrelated reason.

 @Formasitchijoh can you try rebasing it and pushing it again to check if its still failing and what is causing it.
 
 Also, if you are asking why you are not able to see the sent emails in your email client, you can try using the Rails Mailer Preview feature.
 
This file defines a mailer preview -
 
 https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/626aa73dc7fab43608fe2ef6a390e5b781a48a29/spec/mailers/previews/instructor_notification_preview.rb#L2C23-L3C1
 
Visit `http://localhost:3000/rails/mailers/instructor_notification` to check the sent emails.

I remember a real email was also sent in the dev environment, I'd suggest try checking the spams folder as well.

**Comment by Formasitchijoh** [comment]
Thank you for the clarification @prathamVaidya , I haver rebased and pushed to see the actual failing test,

Also I have check the sent email at `http://localhost:3000/rails/mailers/instructor_notification` and it actually references all the instructors of that course as expected.
