### ISSUE TITLE
Calender not rendering correctly in date-picker in Course Creator

### ISSUE THREAD

**Issue by PR4NJ41** [WikiEducationFoundation/WikiEduDashboard#5701]
### What is happening?
In `date-picker` dates are not rendering correctly. The disabled dates must render whenever we are choosing the dates. But they are rendering later.

### To Reproduce

In the course creator make changes as shown in the video

### Expected behavior
The disabled dates must render whenever we are choosing the dates.

### Screenshots

https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/96368921/f4da0cc8-95a8-4c58-a288-79a43c170256

**Comment by claire256** [comment]
Hello @ragesoss, i'm taking up this issue.
