### ISSUE TITLE
In namespace-specific stats, 'users' label always uses 'wiki_education' version

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5703]
For example:

<img width="1147" alt="Screenshot 2024-03-08 at 10 00 00 AM" src="https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/848483/785cc3dc-f75c-4705-bf4b-a29a1bb1f221">

The label for the main stats on Programs & Events Dashboard courses is 'editors' (based on course type), but the label within the namespace stats is 'student editors'. That component should work the same way as elsewhere in terms of using the appropriate label based on the course type.

**Comment by silambarasan-rd** [comment]
@ragesoss I'd like to work on this issue.

**Comment by ragesoss** [comment]
@silambarasan-rd we don't assign issues, but feel free to work on this.

**Comment by yashrajdhamale** [comment]
@ragesoss  could you please explain the issue I am not getting it.
After setting the local dev environment and running the program my home page looks like this 
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/134129335/52a9e2e1-d462-425d-8ff6-282edfd31450)

**Comment by yashrajdhamale** [comment]
Got it thanks
