### ISSUE TITLE
Training Page : No records issue

### ISSUE THREAD

**Issue by psankhe28** [WikiEducationFoundation/WikiEduDashboard#5705]
### What is happening?
On the training page, if there are no training programs, the message seen is "There are no TrainingLibrary records in the database."

![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/84843461/acfc6e91-5039-419f-a51b-1b2c4461a78a)

### To Reproduce

> Steps to reproduce the behavior:
> 1. Go to 'training' in navbar
> 2. See the message

### Expected behavior
I think the message should be "There are no Training Library records in the database."

### System Information

 - OS: Windows
 - Browser Brave

**Comment by ragesoss** [comment]
This is primarily a message aimed at developers, so the lack of a space in `TrainingLibrary` is intentional, as that is the model name. However, I welcome any wording change that would make this clearer and more useful for developers.

**Comment by psankhe28** [comment]
Alright, understood. I don't have any suggestions at the moment
