### ISSUE TITLE
Enhancement of Landing Page Explore Link

### ISSUE THREAD

**Issue by psankhe28** [WikiEducationFoundation/WikiEduDashboard#5706]
### Current Behavior:
Instead of the link, we can have a button which can make the UI more better.

![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/84843461/646754a9-cde0-47f7-a06d-8eb435d7a2ef)

### Desired Behavior:

A button instead of just text with an underline
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/84843461/e6543223-917e-4d2a-a578-015fea20f236)

### Related Files & Code:
File: `app/views/dashboard/index.html.haml`

**Comment by ragesoss** [comment]
Anything that is a button will compete for attention with the existing buttons, and I think this link is a relatively low priority compared with the other buttons that exist already. I would prefer to keep this as a plain link.
