### ISSUE TITLE
Final day of timeline is counted as a blackout day

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#571]
1. Find/create a course that meets M/W.
2. Choose a Wednesday as the end date of the timeline
3. Choose the Monday of the final week as a blackout day.
4. View the timeline. The last week will be marked 'no class meetings' and will not have 'Add Block' enabled.

**Comment by ragesoss** [comment]
I think this error is on the frontend rather than in CourseMeetingsManager. I changed the CourseMeetingsManager spec to test for the end date being one of the course meeting days, and in that case, it does include it.

**Comment by ragesoss** [comment]
Well, maybe it is with CourseMeetingManager. On the frontend, when this bug is in effect, the Timeline component has a week_meetings prop that has one fewer week than it should.

**Comment by ragesoss** [comment]
@thenickcox Any ideas?

**Comment by bmathews** [comment]
I'm takin a look!

**Comment by ragesoss** [comment]
Thanks @bmathews I realize now that the week_meetings prop isn't actually the output of CourseMeetingManager (which is itself a code quality issue, since we have different algorithms on the server and client to calculate the same data). So it probably is somewhere at the client end.

**Comment by bmathews** [comment]
Fixed via 2c8a297164c29dcd3f8f574e700c6aee07397fbc.

**Comment by thenickcox** [comment]
Yeah, in my head that was a soft deprecation, but we can take it out now.
