### ISSUE TITLE
Button not translating

### ISSUE THREAD

**Issue by WikiM0tty** [WikiEducationFoundation/WikiEduDashboard#5710]
### What is happening?
The button "Find articles" on the "Articles>Available Articles" page do not translate himself in any language despite being translated on translatewiki. Others buttons are properly translated when changing the language in the language selector.

Oddly, the same "Find articles" button but on the home page of a project is properly translated.

### To Reproduce

1. Go to any project
2. Go on Articles>Available Articles
3. See the button "Find articles"
4. Change the language using the language selector
5. The button is not translated.

### Expected behavior
The button should be translated the same way the others are.

### Screenshots
![Capture d’écran du 2024-03-19 18-38-59](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/16276048/af361ccb-866f-4842-83c9-916e32a65bd3)
![Capture d’écran du 2024-03-19 18-39-09](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/16276048/785ee7ba-1c6e-4b44-89cf-5ba79c033e85)
![Capture d’écran du 2024-03-19 18-39-16](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/16276048/8ab90491-1ea4-435e-a1af-9ec8ae128be8)

### System Information

 - OS: Ubuntu 23.10
 - Browser: Firefox
 - Version: 124.0

**Comment by UniqueSumitAn** [comment]
I think I can fix this bug .
please give me the repositry of the related bug .

**Comment by ragesoss** [comment]
> I think I can fix this bug . please give me the repositry of the related bug .

This is the repository.
