### ISSUE TITLE
In Article Viewer, add option to show the last student revision

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5729]
### Current Behavior:
The Article Viewer always loads the current version of an article, and then fetches authorship highlighting data for the current version. However, sometimes it is more useful to see the last version that one of the students edited, rather than the current version (for example, if the student work was reverted).

### Desired Behavior:
Add a button in Article Viewer to switch to the latest revision by one of the students in the course, and load authorship highlighting data for that version.

### Additional context:

This is simple to describe, but likely somewhat complex to implement.

**Comment by om-chauhan1** [comment]
Working on this

**Comment by om-chauhan1** [comment]
@ragesoss sir, kindly see this [Link](https://excalidraw.com/#json=dNJxoSJ-C6H_u1USHh9-M,J88rNl_xPtXyrxioZ4dluw)
Am I getting it right or missing anything?

**Comment by om-chauhan1** [comment]
Sir, for any edited article we can easily get its last revsion_id and page_id:
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/4d185396-0e2b-4bc6-b735-12a36d21f742)
But is there any way/API to fetch the article data based on a particular revision ID?

**Comment by ragesoss** [comment]
I think your diagram conveys the right idea.

For the base article, we can get the article HTML at a particular ID using the same 'parse' API action, by supplying the `oldid` parameter instead of the `page` parameter.

For example...

Current version: https://en.wikipedia.org/w/api.php?action=parse&disableeditsection=true&format=json&page=China%20National%20Center%20for%20the%20Performing%20Arts%20Orchestra&origin=*
Old version: https://en.wikipedia.org/w/api.php?action=parse&oldid=745586211&disableeditsection=true&format=json&origin=*


Similarly, for the wikiwho-api that provides the authorship highlighting markup...

Current version is requested by using `0` as the revision ID: https://wikiwho-api.wmcloud.org/en/whocolor/v1.0.0-beta/China%20National%20Center%20for%20the%20Performing%20Arts%20Orchestra/0/?origin=*

Old version replaces 0 with the ID: https://wikiwho-api.wmcloud.org/en/whocolor/v1.0.0-beta/China%20National%20Center%20for%20the%20Performing%20Arts%20Orchestra/745586211/?origin=*
