### ISSUE TITLE
Course flag for 'academic system' is `nil` when default selection is not changed in Course Creator

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5730]
In the Course Creator in Wiki Education mode, the `AcademicSystem` component lets the user choose which academic system their school uses: semester, quarter, or other. The default selection is 'semester', but if the user does not change the default selection, it comes through as `nil` upon course creation. It only takes a value if the choice gets changed. It ought to come through correctly as 'semester' when the default is not changed.

(This option is not part of the Course Creator in `wiki_education: false` mode, and should remain as `nil` in that case.)

**Comment by om-chauhan1** [comment]
working on this
