### ISSUE TITLE
Deleting a week doesn't delete associated gradeables in UI

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#576]
It deletes them on the server, but not in the UI. Then clicking "Edit," then "Cancel" on grading puts the week back. Then, upon refreshing, the week is gone again.

**Comment by thenickcox** [comment]
Deleting a block just removes the associated gradeable title, not the gradeable itself.

Presumably this stuff worked when the timeline was globally editable.

**Comment by ragesoss** [comment]
Yep. I noticed this, and filed #555 instead of this exact bug. :-)

**Comment by thenickcox** [comment]
@ragesoss Right. So…we've talked about this before. But remind me why gradables are polymorphic, but only blocks use them? Was it initially thought that more items would be gradeable? It seems like we should just add two columns to blocks: `gradeable`, and `point_value`. Then we could just add a migration to populate those from the gradeables table and delete the table. Agreed?

**Comment by ragesoss** [comment]
I don't remember. Something like that.

Anyhow, yes, agreed. While we're at it, maybe we should make it just `value`, have it be a string, and then it can handle points, percents, freeform "one gold star", etc. When we migrate, we can append `%` to all the existing ones.

**Comment by ragesoss** [comment]
The above change didn't actually fix the bug described. It doesn't render them if the *block* is deleted directly, but it still does if the week is deleted (and the block with it).

**Comment by ragesoss** [comment]
Now fixed, after the recent re-do of data flow during the removal of the Gradeable model.
