### ISSUE TITLE
Truncation of training modules loses important content

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#578]
![screen shot 2015-12-23 at 4 15 26 pm](https://cloud.githubusercontent.com/assets/702327/11987239/6e5d3128-a990-11e5-832a-b13b6f7ee33f.png)

cc @rileywho

**Comment by thenickcox** [comment]
Here, the status is the longest it could be (2 char %, 'Complete', YYYY-MM-DD date). We could just truncate the module name sooner. @ragesoss is this acceptable?

![screen shot 2015-12-23 at 4 17 15 pm](https://cloud.githubusercontent.com/assets/702327/11987261/c1902ae4-a990-11e5-9ef5-004d5301e250.png)

**Comment by ragesoss** [comment]
Truncate all the time, or only if it's overdue? In non-overdue cases, it won't be an issue.

**Comment by thenickcox** [comment]
The above screenshot gives us 27 characters. 7/15 have more than 27.

It _will_ be an issue in non-overdue cases, because of the truncation. The table doesn't adjust. The width values are hard-coded.

**Comment by ragesoss** [comment]
How about we just remove "overdue"? If you can see the due date and it's red, you can piece together the overdue status.

**Comment by ragesoss** [comment]
"33% Complete (due 2015/12/19)"

**Comment by thenickcox** [comment]
Great. That gives us the truncation we have now, and has the whole date. Is the truncation length we have now acceptable?

![screen shot 2015-12-23 at 4 27 06 pm](https://cloud.githubusercontent.com/assets/702327/11987324/136ad868-a992-11e5-95c6-6f2c2e47c248.png)

**Comment by ragesoss** [comment]
We can remove 'on' between 'due' and the date, to get two more characters of the module names. But yeah, works for me.

**Comment by thenickcox** [comment]
Sounds good!
