### ISSUE TITLE
Clicking through the training too fast causes errors, doesn't record completion

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#579]
Seems like it's possible to click faster than the API can keep up with.

**Comment by bmathews** [comment]
It would be worth checking if this also happens when editing a course's dates, since API calls are triggered on each click of a day.

**Comment by ragesoss** [comment]
I couldn't get it to error with some very frantic clicking on the calendar.

It may be, rather than the API not handling it, that the client moves on to another page before it hits the API, and so steps get skipped. Anyhow, it's an edge case and not a priority.

**Comment by ragesoss** [comment]
I haven't seen this happen in a long while; it may not happen at all any more.
