### ISSUE TITLE
Assigned articles list badly formatted

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5799]
When there are many assigned articles, the list of them from the Students tab is unreadable:

![Screenshot 2024-04-24 at 11 50 57 AM](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/848483/19a574d1-0efa-44d1-a37a-f44dcbb9d7b1)

Here's the live example: https://dashboard.wikiedu.org/courses/New_York_University/Research_Process_and_Methodology_-_SP24_-_Sect_201_-_Thu_(Spring)/students/overview

**Comment by PR4NJ41** [comment]
Working on this.
