### ISSUE TITLE
daily and constant updates interfere with each other: Mysql2::Error: Lock wait timeout exceeded

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#58]
When a daily update and a constant update run at the same time, they sometimes lock one another out of the database for too long.

[2015-03-28 06:17:18.818 ERROR] Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: UPDATE `articles_courses` SET `updated_at` = '2015-03-28 09:16:27', `
view_count` = 4925 WHERE `articles_courses`.`id` = 2145
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: UPDATE `articles_courses` SET `updated_at` = '2015-03-28 09:16:27', `
view_count` = 4925 WHERE `articles_courses`.`id` = 2145

...

/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/var/www/dashboard-testing/releases/20150326212155/app/models/articles_courses.rb:47:in `update_all_caches'
/var/www/dashboard-testing/releases/20150326212155/lib/tasks/cache.rake:9:in `block (2 levels) in <top (required)>'
/var/www/dashboard-testing/releases/20150326212155/lib/tasks/batch.rake:46:in `block (2 levels) in <top (required)>'
Tasks: TOP => cache:update_caches
(See full trace by running task with --trace)

**Comment by ntdb** [comment]
This should be resolved by 61e6ca1f5130c9a82930caf5baf9035311ff778d: update_daily will wait until update_constantly finishes then block it from starting again until it's done.
