### ISSUE TITLE
Capybara screenshots generated by travis are not accessible

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#580]
Since many of the feature spec problems we run into are intermittent and happen more often on travis than locally, it'd be convenient if the screenshots generated by Capybara were accessible. Maybe we can automagically upload somewhere?

**Comment by bmathews** [comment]
Whoops, never noticed this issue. Images for failed tests are uploaded to imgur. URLs can be found at the bottom of the travis output.
