### ISSUE TITLE
Add redirect for JSON and HTML requests for the current term of Alerts

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5800]
### Current Behavior:

There is a public feed of Alerts for each campaign, available as both JSON and a web page:

* https://dashboard.wikiedu.org/campaigns/spring_2024/alerts.json
* https://dashboard.wikiedu.org/campaigns/spring_2024/alerts

However, the place to go for the current term changes every semester.

### Desired Behavior:

Add a redirect path so that bookmarks and/or software can reliably access the alerts for the current default term (`Campaign.default_campaign`).

### Note

This was requested by User:Mathglot on en.wikipedia.

**Comment by cyrillefr** [comment]
Hello @ragesoss ,

May I work on this issue ?

**Comment by ragesoss** [comment]
@cyrillefr sure!
