### ISSUE TITLE
DiffViewer relies on a Revisions table query

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5806]
One of the unanticipated effects of deleting the Revisions table is that the DiffViewer feature is broken. It relies on a call to ArticlesController#details, which looks for a `first revision` and `last revision` of an edited article, and if those revisions are not found, there will be a JS error.

In this case, we should probably rework the frontend so that it does not rely on the Dashboard server to get the data it needs to render the diff from the earliest student revision to the latest one, perhaps by fetching the revision history of the article (within the date range of the course) and using that to find the earliest and latest revision.

**Comment by ragesoss** [comment]
@gabina this is relevant for you.

**Comment by gabina** [comment]
Took note of this :+1:
