### ISSUE TITLE
add a parameter to override the lack of 'instructor' role to let a user create a course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5812]
We encourage people who have taken a Scholars & Scientists course with Wiki Education to then teach in our Wikipedia Student Program. If a user first signed in to the Dashboard via an enrollment link, then the 'onboarding' flow does not let them indicate they are an instructor, and their user permissions will be `0`. That means they won't be shown the link to the instructor orientation or the 'create a course' button on the Dashboard home page.

We should add a parameter (such as ?teach) that overrides this to show the instructor version of the landing page, so that fewer users get stuck and need to ask about how to reset their instructor status (via /onboarding) before creating a course.

**Comment by STSonyThomas** [comment]
Hey can I be assigned this issue?

**Comment by ragesoss** [comment]
@STSonyThomas we don't usually assign issues, but you are welcome to work on this.

**Comment by Abishekcs** [comment]
Working on this.

**Comment by Abishekcs** [comment]
> I think we could also optionally also automatically set the role from student to instructor, but the place to do that would be upon completion of the instructor orientation training module.

@ragesoss  for this do you mean the entire https://dashboard.wikiedu.org/training/instructors or only https://dashboard.wikiedu.org/training/instructors/new-instructor-orientation

**Comment by ragesoss** [comment]
Only the latter.
