### ISSUE TITLE
nonexistent training slides generate server error, not 404 page

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#582]

**Comment by thenickcox** [comment]
dup of https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/450

Did that not fix it?

**Comment by ragesoss** [comment]
Ah... slightly diffferent. #450 covered the cases of nonexistent libraries and modules. What I meant here is a nonexistent slide of an existing module, such as https://dashboard-testing.wikiedu.org/training/students/editing-basics/foobar
