### ISSUE TITLE
Translation issues with future_updates_remaining

### ISSUE THREAD

**Issue by Nikerabbit** [WikiEducationFoundation/WikiEduDashboard#5820]
### What is happening?

Some i18n strings are not properly processed at translatewiki.net.

```
future_updates_remaining:
      true: The stats will continue to be updated until %{date}.
      false: The stats for this program are no longer being updated regularly.
```

True and false are booleans in yaml and at least our yaml parser (phpyaml) fails to handle them properly in array keys. This means these strings don't get proper translations from translatewiki.net.

Can you add quotes around the keys or use different keys?

**Comment by ragesoss** [comment]
Thank you @Nikerabbit !
