### ISSUE TITLE
On P&E Dashboard, 'When' field validation is overzealous

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5837]
Per bug report on Meta: "If you empty the “when” field, this will not be saved and will result in an error "This field has invalid characters". knowing that I don't want to make this modification because it impacts the event title which in turn causes a change to the event link I want to add in my event tool"

On Wiki Education Dashboard, 'term' is a required field, but we don't require it on P&E Dashboard so it should be possible to blank that field.

**Comment by akshaya9999** [comment]
@ragesoss Just to be clear, you want the institution box in the attached ss to be not mandatory?
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/116485510/2730e08a-bcc4-4cb8-8da6-d84bdc19afbf)

**Comment by ragesoss** [comment]
@akshaya9999 correct. But only for the 'Create an Independent Program' version, which is used in `wiki_education: 'false'`  mode (via `application.yml`). It should still be required in the `wiki_education: 'true'` case.

**Comment by Formasitchijoh** [comment]
working on this

**Comment by Formasitchijoh** [comment]
@ragesoss I have a quick question on this, task, since the institution field in the P&E dashboard is used to construct the slug or the event title which in turn causes a change to the event link, should there be a generic name used in this scenario or the title should be constructed with just the  title in case the institution is not provided

**Comment by ragesoss** [comment]
Hmm... I must have been confused in my earlier comment. The 'institution' field does need to remain mandatory. It's just the 'when' (aka 'term') field that we want to relax the validation for.

**Comment by Formasitchijoh** [comment]
Alright thank you for the clarification
