### ISSUE TITLE
The message settings.special_users.new.confirm_remove_special_user appears to be unused

### ISSUE THREAD

**Issue by amire80** [WikiEducationFoundation/WikiEduDashboard#5844]
### What is happening?
I noticed that the message settings.special_users.new.confirm_remove_special_user may be problematic: it looks like it's supposed to have a parameter (probably a username), but it doesn't.

However, when I searched for it in the code, I found nothing. It appears to be used only in translation files and not in code.

If it's not actually used, it should be removed from the English messages file.

**Comment by osujipius** [comment]
I am working on this @ragesoss
