### ISSUE TITLE
javascript errors with @state.slides.length

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#585]
The most common javascript errors coming through Sentry lately are cases where, within the training, @state.slides.length gets called and something is undefined.

From what I can tell, this seems to happen mainly, possibly exclusively, when users transition from one module to another via buttons in a slide (which opens a second module in a new tab, in some cases). I haven't figured out how to replicate it, but it does seem to happen is several different browsers — possibly only Webkit.

Not sure if this is causing any actual problems for users.

Here are some of the Sentry items:
* http://sentry.ragesoss.com:8080/wiki-ed/production/group/1628/
* http://sentry.ragesoss.com:8080/wiki-ed/production/group/1585/
* http://sentry.ragesoss.com:8080/wiki-ed/production/group/1605/

**Comment by thenickcox** [comment]
Double good news. I was able to reproduce this on Safari, but it wasn't causing user problems. AND it was fixed by cc72102. :tada:

**Comment by ragesoss** [comment]
I take it cc72102 is something you have locally, but haven't pushed?

**Comment by thenickcox** [comment]
Oops. Make that 19a84a9
