### ISSUE TITLE
On course pages, 'Updated at' does not automatically refresh when stats are re-fetched

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5925]
On the Home tab of a course page, the frontend will refetch course data once per minute. This results in automatically updating the course stats (which is nice during a live event, as leaving the page open lets you see the stats as they increase throughout the event). This is configured in the `details.jsx` component.

When the course data is refetched, however, it does not update the StatisticsUpdateInfo component, which displays the time of the last update and the next expected update... so the course stats may be actually refreshed and based on new update, while this component still says 'last update 1 day ago' or similar.

This is probably a pretty easy fix via one of the Redux reducer functions.

**Comment by Abishekcs** [comment]
I am working on this
