### ISSUE TITLE
User#can_edit? may prevent editing by a user who has multiple roles in a course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5948]
### What is happening?
The facilitator for this event, who is also participating as an editor, reports an permissions error when trying to edit the tracked wikis: https://outreachdashboard.wmflabs.org/courses/Wikimedians_of_Kerala/Wiki_Loves_Onam_2024/home

I think this is because of the implementation of `User#role`, which looks for a single CoursesUsers record, so if the wrong one is found the user will be treated as a 'student' rather than 'instructor'.

### Additional context

A fix for this should include a unit test for `#can_edit?` that fails with the current implementation but passes with a fixed implementation.

**Comment by TunrayoIlawole** [comment]
I am currently trying to set up my development environment @ragesoss. I will get started on the issue as soon as i get it running

**Comment by TunrayoIlawole** [comment]
Hi @ragesoss , please I am having trouble finding where the unit tests are. Can you help point me to the directory?

**Comment by Formasitchijoh** [comment]
Hi @TunrayoIlawole which unit test are you looking for?

**Comment by TunrayoIlawole** [comment]
Thank you @Formasitchijoh

**Comment by crocmons** [comment]
I would like to work on this! @ragesoss

**Comment by ragesoss** [comment]
@crocmons someone else is actively working on this already. I recommend choosing a different issue.
