### ISSUE TITLE
Improve `tagged_courses` view

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5952]
The 'tagged_courses' view is available to admins. In `wiki_education` mode, it is used by Wiki Education staff to see a list of courses that share a given `Tag`.

Currently, the tagged_courses view recycles the view templates for the campaign programs view. It should probably be forked into a separate set of view templates, before implementing each of these. (Forking the templates should be done in the same PR as the first item. Additional PRs can address the other items afterwards.)

- [ ]  Add a column to display which Wiki Expert(s) is assigned to each course. (In implementing this, take care to avoid N+1 queries.)
- [ ] Add a stats summary to the top of the page, in the same way as on the Campaign views. This will require changes to the React app; try to make the necessary changes as minimal as possible.
- [ ] Add an option to download a CSV with equivalent data to the table in the tagged_courses view.

**Comment by Abishekcs** [comment]
I'm working on this 😃.

**Comment by ragesoss** [comment]
I think a button with a text label would be better here.

**Comment by ragesoss** [comment]
This is an admin-only view, so being verbose and clear is much preferred. Admins easily get used to the amount of visual information, and filter out what they don't need, but for infrequently-used features like this, having a clear text label will be really useful for the times when it does get used.

**Comment by ragesoss** [comment]
(Also, a button without a new icon helps keep the code concise.)
