### ISSUE TITLE
Replace Non-functional 'Back' Button with 'Cancel' Button on First Panel of 'Create a New Course' Modal

### ISSUE THREAD

**Issue by Abishekcs** [WikiEducationFoundation/WikiEduDashboard#5982]
### Issue Description

The `Back` button on the first panel of the `Create a New Course` modal serves no purpose and does not function at all. Since this is the first panel, it should not have a "Back" button. Instead, the button should be replaced with a "Cancel" button that allows the user to exit the modal if needed.

### Steps to Reproduce

1. Open the "Create a New Course" modal.
2. Observe the "Back" button on the first panel.
3. Notice that the "Back" button doesn't work or serve any meaningful purpose.

Refer to the recording below for further details (In case you don't have admin access, which is required to access the button as an instructor or as an admin at some level.):  

https://github.com/user-attachments/assets/b2edcf5c-f1b0-4aff-9960-f86c4a314dc9

### Expected Behaviour

1. The first panel of the "Create a New Course" modal should display a `Cancel` button instead of a "Back" button.
2. The "Back" button should only be present on subsequent panels, as it is irrelevant to have it on the first panel where there is no previous panel screen to return to.

### Screenshots

![Screenshot from 2024-10-06 13-29-55](https://github.com/user-attachments/assets/cb2f6431-9fe9-4ef8-ac52-f66cc804889a)

### System Information

 - OS: Ubuntu 22.04.5 LTS
 - Browser: Version 129.0.6668.89 (Official Build) (64-bit)

**Comment by Formasitchijoh** [comment]
I am working on an issue concerning this form i will just fix this up before I proceed.

**Comment by Abishekcs** [comment]
@Formasitchijoh, regarding your doubts, I realized there were some mistakes in my previous description of the issue. Here’s the corrected explanation for future reference if the issue remains unresolved:

The options for creating a course or program vary depending on the user's role (admin, instructor, or Wiki Ed staff):

The issue needs to be addressed only when the user is an Instructor in the Wiki Education Dashboard:

`When the user is only an instructor, the "Create a New Course" modal opens directly, without any prior panel. Therefore, a cancel button should be added here instead of a back button. However, the subsequent panel should include a back button, since it does have a previous panel to return to.`


https://github.com/user-attachments/assets/da860cd9-3fbd-4a2d-8b1a-7a9377b3d928

**Comment by Formasitchijoh** [comment]
@Abishekcs Thank you for the clarification, i think i ensured this "`When the user is only an instructor, the "Create a New Course" modal opens directly, without any prior panel. Therefore, a cancel button should be added here instead of a back button. However, the subsequent panel should include a back button, since it does have a previous panel to return to`"
If you refer to the video i sent. I will have to verify this for a Normal user,

And also i have a blocker, my build hasn't been passing lately I have tried uninstalling my bundler installing a new one but it still does not solve it, I will appreciate you help if you have an idea on what i can do to fix this.

<img width="1792" alt="Screenshot 2024-10-07 at 14 34 55" src="https://github.com/user-attachments/assets/68dd8a72-7bcf-4ab9-9950-fc640b97cb08">

**Comment by Abishekcs** [comment]
> @Abishekcs Thank you for the clarification, i think i ensured this "`When the user is only an instructor, the "Create a New Course" modal opens directly, without any prior panel. Therefore, a cancel button should be added here instead of a back button. However, the subsequent panel should include a back button, since it does have a previous panel to return to`" If you refer to the video i sent. I will have to verify this for a Normal user,

Yes, but if you look at your first `After video`, you implemented a close button where there should have been a back button, since there is a previous panel. What if the user wanted to go back to the previous panel?

Make sure you are only an Instructor and not Wiki Ed staff on the Wiki Ed dashboard. Then, when you click the 'Create Course' button, the correct panel opens up as shown in the video in the issue.

**Comment by Formasitchijoh** [comment]
I understand now,I will update that
