### ISSUE TITLE
On Programs & Events Dashboard, allow deleting a program before removing campaigns

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6012]
The requirement to remove campaigns before deleting a course is the behavior we want in `wiki_education` mode, but it's confusing and unnecessary to require it for pages on Programs & Events Dashboard.

Implementing this will resolve https://phabricator.wikimedia.org/T378013

**Comment by empty-codes** [comment]
I would like to work on this!
