### ISSUE TITLE
DeUserfyingEditAlertMonitor should detect when instructors move pages live (not just students)

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6013]
DeUserfyingEditAlertMonitor queries Wikipedia for recent 'de-userfying' changes, matching the usernames to a query of student usernames from the dashboard database.

We want to generate these alerts for instructors as well as students.

**Comment by TunrayoIlawole** [comment]
Hi @ragesoss , I will work on this
