### ISSUE TITLE
layout bug on Articles Edited table

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6014]
On at least one page, the two "Assessment tools" icons are misaligned and the table spacing is disrupted.

You can see the bug currently on this course page: https://dashboard.wikiedu.org/courses/University_of_Michigan-Dearborn/Environmental_Politics_(Fall_2024)/articles/edited?

![icon spacing](https://github.com/user-attachments/assets/a467976f-74ab-4721-a8ad-8e3566d758e4)

It is being triggered by long article title (Assistant Secretary of State for Oceans and International Environmental and Scientific Affairs) present on the page.

Any number of quick hacks could fix this issue (including reducing the padding on either of the icons from 24px to 23px), but an ideal solution would address the root cause without arbitrarily adjusting the styling in a way that affects other pages.

**Comment by Formasitchijoh** [comment]
working on this

**Comment by empty-codes** [comment]
Would like to take a look at this! @ragesoss
