### ISSUE TITLE
Inconsistency in the size of clone previous course button and the Color of the cancel button 

### ISSUE THREAD

**Issue by Formasitchijoh** [WikiEducationFoundation/WikiEduDashboard#6018]
> Thanks for reporting a problem! Please delete any line that begins with a '>' (including this one) and replace with your own content.

### What is happening?
In both the Wiki Education Dashboard and the P&E Dashboard:
The "Clone Previous Course" button appears smaller than the standard button size used across the platform.
The "Cancel" button on the "Choose a Course" form uses a different color than the standard color applied to similar buttons throughout the system.### To Reproduce

### Expected behavior
> Both the clone a previous course button and the cancel button should utilize the standard size and color appropriately

### Screenshots
> If applicable, add screenshots to help explain your problem.
<img width="1792" alt="Screenshot 2024-10-29 at 13 38 18" src="https://github.com/user-attachments/assets/eaadede6-1d33-4626-a66a-8223fae28721">

<img width="1792" alt="Screenshot 2024-10-29 at 13 44 17" src="https://github.com/user-attachments/assets/473704cb-8ac7-47e5-a080-5f33407a32c6">

**Comment by ragesoss** [comment]
This is an intentional change we made recently to de-emphasize the clone option and make the 'new course' path more of a default.
