### ISSUE TITLE
Update for a Wikidata course errors when WikidataDiffAnalyzer is called

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6032]
This course has been errorring during every data update: https://outreachdashboard.wmflabs.org/courses/Wikimedia_Indonesia/Datathon_12TahunWikidata_(28_-_30_Oktober_2024)

Here's the relevant portion of the stack trace:

```
NoMethodError: undefined method `each' for nil:NilClass

            revisions.each do |revision|
                     ^^^^^
  from wikidata-diff-analyzer (2.0.2) lib/wikidata/diff/api.rb:37:in `block in get_revision_contents'
  from wikidata-diff-analyzer (2.0.2) lib/wikidata/diff/api.rb:33:in `each'
  from wikidata-diff-analyzer (2.0.2) lib/wikidata/diff/api.rb:33:in `get_revision_contents'
  from wikidata-diff-analyzer (2.0.2) lib/wikidata/diff/large_batches_analyzer.rb:12:in `block in handle_large_batches'
  from wikidata-diff-analyzer (2.0.2) lib/wikidata/diff/large_batches_analyzer.rb:10:in `each'
  from wikidata-diff-analyzer (2.0.2) lib/wikidata/diff/large_batches_analyzer.rb:10:in `each_slice'
  from wikidata-diff-analyzer (2.0.2) lib/wikidata/diff/large_batches_analyzer.rb:10:in `handle_large_batches'
  from wikidata-diff-analyzer (2.0.2) lib/wikidata-diff-analyzer.rb:75:in `analyze'
  from app/services/update_wikidata_stats.rb:91:in `update_summary_with_stats'
  from app/services/update_wikidata_stats.rb:74:in `initialize'
  from app/workers/update_wikidata_stats_worker.rb:11:in `new'
  from app/workers/update_wikidata_stats_worker.rb:11:in `perform'
```

This error happens in the WikidataDiffAnalyzer gem: https://github.com/WikiEducationFoundation/wikidata-diff-analyzer/blob/main/lib/wikidata/diff/api.rb#L42

I guess it is related to the shape of the API response, which maybe includes a 'page' entry without a 'revisions' property.

Working around it by adding a guard statement in that block (eg, `next unless revisions`) might fix the issue, but I'd like to understand exactly why it's happening and what the API response looks like first. Replicate the bug, identify the API query that triggers it, and then we can decide on the best way to fix it.

**Comment by ragesoss** [comment]
@saha23s it took a while, but it looks like we finally uncovered a bug in your gem.

**Comment by empty-codes** [comment]
I would like to work on this! @ragesoss

**Comment by ragesoss** [comment]
Great! So I think just adding a guard statement is an appropriate fix. @empty-codes would you like to implement the fix in the gem codebase?

**Comment by empty-codes** [comment]
@ragesoss I can do that! I'll create an issue for it now and start working on it.

**Comment by empty-codes** [comment]
@ragesoss Done! Here's the PR Link: https://github.com/WikiEducationFoundation/wikidata-diff-analyzer/pull/32
