### ISSUE TITLE
Activity tab should show real names and addition to usernames, when available

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6034]
### Current Behavior:
For users who are allowed to see the real names of students, the Students tab shows both real names and usernames. However, the Activity tab only shows usernames.

### Desired Behavior:

If real names have already been received and are available in the redux store, they should be used on the Activity tab alongside usernames.

**Comment by shishiro26** [comment]
@ragesoss  I would like to work on this issue..

**Comment by TunrayoIlawole** [comment]
Hi @ragesoss , please i would like to work on this

**Comment by ragesoss** [comment]
This is mostly done. One remaining issue: the usernames should be links to the students tab view for each user. (Currently, the usernames are underlined and look like links but are not links.)

**Comment by shishiro26** [comment]
@ragesoss I would like to work on this issue.
