### ISSUE TITLE
Refactor common logic for navigating to the single-student view within a Course page

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6045]
We have at least two places that use username links to navigate to the individual student view of the Students tab of a course page. See https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/6042#pullrequestreview-2459488373

We also have username links in the MyArticles section and other places that show the group members for an assigned article. The ones that link to user profile pages (/users/USERNAME) should link to the individual student view within the course instead.

**Comment by TunrayoIlawole** [comment]
Hi @ragesoss, please i would like to work on this
