### ISSUE TITLE
Make it easy for Wiki Education staff to see when a course has been closed

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6050]
### Current Behavior:

Wiki Education staff go through a process of 'closing out' courses at the end of each term, which uses the `closed_date` flag to add a timestamp for when the course was closed. (This indicates that there is nothing left to do in terms of reviewing work, moving good sandbox drafts into Wikipedia mainspace, updating the end date to capture any student edits that happened soon after the original end date, evaluating the average quality of student work, and logging any major problems.)

The closing process happens in Salesforce and gets logged on the course flags via the `UpdateCourseFromSalesforce`, and there is no UI related to it on the Dashboard side.

### Desired Behavior:
When an admin on Wiki Education Dashboard views a course that has already been closed out, it should be obvious that it has been closed.

#### ~~On the course page~~ (done)

The Admin Quick Actions component is probably the best place to indicate this. It should be prominent, eg, by affecting the background color in addition to a text indicator.

#### On the campaign course list

Closed courses could be highlighted similarly to the way we highlight just-started courses, soon-to-end courses, and private courses. This highlighting feature should only affect admins, and it should be implemented similarly to the existing highlights, which use methods from course_helper.rb to determine whether to apply a CSS class that applies the color to the row for that course.

**Comment by yash1378** [comment]
hi @ragesoss  can i work on this issue ?

**Comment by ragesoss** [comment]
@yash1378 sure

**Comment by vishwamohini15** [comment]
> ### Current Behavior:
> Wiki Education staff go through a process of 'closing out' courses at the end of each term, which uses the `closed_date` flag to add a timestamp for when the course was closed. (This indicates that there is nothing left to do in terms of reviewing work, moving good sandbox drafts into Wikipedia mainspace, updating the end date to capture any student edits that happened soon after the original end date, evaluating the average quality of student work, and logging any major problems.)
> 
> The closing process happens in Salesforce and gets logged on the course flags via the `UpdateCourseFromSalesforce`, and there is no UI related to it on the Dashboard side.
> 
> ### Desired Behavior:
> When an admin on Wiki Education Dashboard views a course that has already been closed out, it should be obvious that it has been closed.
> 
> The Admin Quick Actions component is probably the best place to indicate this. It should be prominent, eg, by affecting the background color in addition to a text indicator.

Hello Sir,

I am interested in contributing to the [WikiEduDashboard](https://github.com/WikiEducationFoundation/WikiEduDashboard) project. However, I am facing issues getting the project to run on my laptop. Could you please guide me to the resources or documentation that detail the dependencies and necessary steps to set up this project successfully?

Thank you for your time !

**Comment by empty-codes** [comment]
> Could you please guide me to the resources or documentation that detail the dependencies and necessary steps to set up this project successfully?

Setup docs: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md
Contribution docs: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/CONTRIBUTING.md

If going through these does not solve your problem, ask on Slack. Hope this helps!

**Comment by bhushan354** [comment]
@ragesoss  If no one is currently working on this, I would like to take on this issue.

**Comment by ragesoss** [comment]
@bhushan354 go for it.

**Comment by bhushan354** [comment]
@ragesoss  Thanks! Also, could I please get a Slack invite? My email is deshmukhbhushan380@gmail.com

**Comment by swayam-agrahari** [comment]
Hello @ragesoss ,
 I’m excited to contribute to this project!  I’d love any additional guidance on the approach or anything specific you’d want to see in this pr. 

Thanks in advance for your help, and I look forward to contributing!

**Comment by Jay2006sawant** [comment]
Hello @ragesoss ,
I’m excited to contribute to this project! . Can you please assign this issue to me?

**Comment by ragesoss** [comment]
@Jay2006sawant we already have an open PR for this one.
