### ISSUE TITLE
DiffViewer breaks if article has been moved

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6056]
The DiffViewer tool is available on the Articles Edited view of a course page (as well as a few other places).

If an article gets subsequently moved to a new title, and the Dashboard hasn't updated that article to reflect the move, then attempting to use the DiffViewer results in JS console error (and the DiffViewer doesn't render).

The DiffViewer should be updated to handle this situation. Ideally, it should be able to follow redirects and still show diffs for moved articles, but just showing a message like 'could not find article' would be okay (and probably necessary for the case where an article was deleted or moved without a redirect).

**Comment by Abishekcs** [comment]
Working on this.

**Comment by ragesoss** [comment]
@Abishekcs be sure to start from the latest code as of now; I just merged some significant changes to DiffViewer.

**Comment by Abishekcs** [comment]
just an update even the ArticlerViewer along with the reported DiffViewer breaks if article has been moved !


![Screenshot from 2024-12-13 23-50-13](https://github.com/user-attachments/assets/0b2afa52-3091-4b30-abe5-e974eb46ed7d)

**Comment by ragesoss** [comment]
I think that's okay behavior for the Article Viewer, as it still renders the component and shows the error.

**Comment by Abishekcs** [comment]
> I think that's okay behavior for the Article Viewer, as it still renders the component and shows the error.

Okay, I got it. Thank you😄 

> Ideally, it should be able to follow redirects and still display diffs for moved articles.

I attempted this approach by using the MediaWiki page ID of the article ( as the MediaWiki page ID remain the same even if the article is moved).  to fetch the current title through the API endpoint:
https://en.wikipedia.org/w/api.php?action=query&pageids=${article_mw_page_id}&format=json&origin=*.

Example: 
https://en.wikipedia.org/w/api.php?action=query&pageids=1639997&format=json.

I then compared the fetched title with the current article title. If they were different, I updated the article name in the Redux store and fetched the revision details  (i.e., the first and last revisions) with the current updated title.

> but just showing a message like 'could not find article' would be okay (and probably necessary for the case where an article was deleted or moved without a redirect).

Or would it be better to stick with this approach?

**Comment by ragesoss** [comment]
If you can make it successfully load a moved page, that's definitely better than a 'could not find' message. Using the page ID is a fine strategy. There are cases where that might fail even while following a redirect would succeed, but that will also work in some cases where there is no redirect, so that's probably actually a little better than the redirect-based approach.
