### ISSUE TITLE
On Programs & Events Dashboard user profile pages, links to courses should not use education-specific terminology

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#6057]
The user profile page lists courses/programs/events that a user has participated in, eg: https://outreachdashboard.wmflabs.org/users/Ragesoss

Each link is labeled "View Course Page". That terminology is appropriate for Wiki Education Dashboard, but Programs & Events Dashboard should use a more generic label, perhaps simply "View Page".

**Comment by sumana-2705** [comment]
hello @ragesoss 

I'm Angajala Sumana Sree pursuing my masters in IIT(BHU). I want to fix this word in dashboard, Can I work on this issue?

**Comment by ragesoss** [comment]
@sumana-2705 go for it.

**Comment by bhushan354** [comment]
Hello @ragesoss ,
I’ve been working on this issue and, since I have my local repo and database set up, I’ve pushed a fix to update the label. 
Thanks !

**Comment by bhushan354** [comment]
@ragesoss ,
https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/6061
Take a look !

**Comment by sumana-2705** [comment]
Hello @ragesoss 

I guess @bhushan354  has opened a valid PR to solve the issue, I will find another one to contribute. Thank you
