### ISSUE TITLE
Social media course page gets disrupted by AdBlock Plus

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#614]
I get a flood of errors when I try to load this page on Iceweasel 38.5: https://dashboard.wikiedu.org/courses/North_Dakota_State_University/Social_Media_and_Participatory_Culture_%28Spring_2016%29

It's fine on Ubuntu / Firefox, and on Chromium.

![errors](https://cloud.githubusercontent.com/assets/848483/12311048/586c1706-ba09-11e5-9617-381eb4d70d08.png)

**Comment by bmathews** [comment]
Can't reproduce on Debian with Iseweasel 38.2. I'll try upgrading

**Comment by ragesoss** [comment]
Here's what those error notifications say:

`There was an error: [Exception... "<no message>" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: https://dashboard.wikiedu.org/assets/javascripts/vendor.js :: .send :: line 3" data: no]`

**Comment by bmathews** [comment]
Do you have an adblock extension installed?

**Comment by ragesoss** [comment]
Yes. Disabling that made it go away.

I get the same error on that page on Firefox for Android (without an adblock extension). But other pages besides this one don't give an error. Maybe some keywords in the course content that triggered it?

**Comment by bmathews** [comment]
Hm... That wouldn't really explain why it's failing on FF for android, but maybe. Maybe it's because the url contains `social_media` or something

**Comment by ragesoss** [comment]
Oh, actually I do have adblock on the android one.

**Comment by bmathews** [comment]
Might be worth tracking down the list/regex's for whatever adblock extension you're using and file an issue with them?

**Comment by ragesoss** [comment]
Yeah.

**Comment by ragesoss** [comment]
Yeah, it's at the level of a filter list (one which may or may not be enabled by default when you install ABP on different systems). Having `/social_media` in the url seems to be the main thing. Nothing we can really do about it, so...
