### ISSUE TITLE
Extra space between top bar and stats area

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#62]
On staging (presumably since 4223571ca5ea4325ceedd9d0666c9308de7c1b6b ) there is too much space between the white (login) bar and course / dashboard title.

**Comment by ragesoss** [comment]
Here's how it looks for me in Firefox and Chrome.

![screenshot from 2015-04-06 16 16 54](https://cloud.githubusercontent.com/assets/848483/7014327/6bcfa412-dc78-11e4-81b1-f2956b79aba1.png)
![screenshot from 2015-04-06 16 16 35](https://cloud.githubusercontent.com/assets/848483/7014326/6b74ab34-dc78-11e4-9d39-21f524b9c984.png)

**Comment by ntdb** [comment]
Resolved in aa7ff8b8c038ffe1c7e7011929ff96f8d2df6fb8
