### ISSUE TITLE
User attributes `character_sum` and `view_sum` are not used.

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#621]
We cache these on User, but we don't use them for anything.

I'm not even sure we use `revision_count`, `article_count`, or course_count.

These cache methods contribute heavily to to the time updates take.

**Comment by ragesoss** [comment]
It looks like `RevisionImporter.users_with_no_revisions` is the only place that uses User#revision_count. It might as well use CoursesUsers#revision_count anyway, so with that, we should be clear to get rid of Use#revision_count as well.

**Comment by ragesoss** [comment]
And `User#article_count` appears to be unused as well.

**Comment by ragesoss** [comment]
`User#course_count` also appears to be unused. I think we can get rid of *all* the caching on Users!

**Comment by ragesoss** [comment]
@thenickcox can you do a short sanity check on this? Make sense to you?

**Comment by thenickcox** [comment]
I'd sure feel _way_ better if I could read the commit message on the commit that removed where they're used. But it's possible it'd take too long to track that down.

**Comment by ragesoss** [comment]
I'm not sure if they were *ever* used. Most of them shouldn't have been. I think they were mostly added proactively, on the assumption that we might want to do something with them.

**Comment by thenickcox** [comment]
That seems to be a trend in this codebase, which makes it exceedingly difficult to identify what's safe to remove. YAGNI should be the attitude going forward, it seems. That said, everything you've said here _seems_ right, and upon a cursory glance for the usage of each of those methods, yeah, I couldn't find them. There's a lot in the `spec`s about them. Let's be sure to take those out, too.
