### ISSUE TITLE
apache2 error.log is very noisy

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#63]
Every single time a page gets accessed, the error log gets filled up with INFO details. Maybe something is getting sent to stdout that shouldn't be?

For example:

App 1956 stdout: [2015-04-06 19:32:28.310 INFO ] Started GET "/courses/DePaul_University/Introduction_to_Psychology_(Spring_2015)" for <IP address> at 2015-04-06 19:32:28 -0300
App 1956 stdout: [2015-04-06 19:32:28.334 INFO ] Processing by CoursesController#students as */*
App 1956 stdout: [2015-04-06 19:32:28.334 INFO ] Parameters: {"id"=>"DePaul_University/Introduction_to_Psychology_(Spring_2015)"}
App 1956 stdout: [2015-04-06 19:32:28.401 INFO ] Rendered courses/_nav.html.erb (3.1ms)
App 1956 stdout: [2015-04-06 19:32:28.530 INFO ] Rendered courses/_header.html.erb (126.3ms)
App 1956 stdout: [2015-04-06 19:32:28.534 INFO ] Rendered users/_list_header.html.erb (1.1ms)
App 1956 stdout: [2015-04-06 19:32:28.591 INFO ] Rendered users/_detail.html.erb (1.9ms)
App 1956 stdout: [2015-04-06 19:32:28.591 INFO ] Rendered users/_row.html.erb (8.0ms)
App 1956 stdout: [2015-04-06 19:32:28.594 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.594 INFO ] Rendered users/_row.html.erb (2.6ms)
App 1956 stdout: [2015-04-06 19:32:28.596 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.597 INFO ] Rendered users/_row.html.erb (2.5ms)
App 1956 stdout: [2015-04-06 19:32:28.599 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.599 INFO ] Rendered users/_row.html.erb (2.5ms)
App 1956 stdout: [2015-04-06 19:32:28.602 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.602 INFO ] Rendered users/_row.html.erb (2.5ms)
App 1956 stdout: [2015-04-06 19:32:28.605 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.605 INFO ] Rendered users/_row.html.erb (2.4ms)
App 1956 stdout: [2015-04-06 19:32:28.607 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.607 INFO ] Rendered users/_row.html.erb (2.6ms)
App 1956 stdout: [2015-04-06 19:32:28.610 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.610 INFO ] Rendered users/_row.html.erb (2.5ms)
App 1956 stdout: [2015-04-06 19:32:28.621 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.621 INFO ] Rendered users/_row.html.erb (11.1ms)
App 1956 stdout: [2015-04-06 19:32:28.624 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.624 INFO ] Rendered users/_row.html.erb (2.6ms)
App 1956 stdout: [2015-04-06 19:32:28.627 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.627 INFO ] Rendered users/_row.html.erb (2.3ms)
App 1956 stdout: [2015-04-06 19:32:28.629 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.629 INFO ] Rendered users/_row.html.erb (2.4ms)
App 1956 stdout: [2015-04-06 19:32:28.632 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.632 INFO ] Rendered users/_row.html.erb (2.4ms)
App 1956 stdout: [2015-04-06 19:32:28.634 INFO ] Rendered users/_detail.html.erb (0.6ms)
App 1956 stdout: [2015-04-06 19:32:28.634 INFO ] Rendered users/_row.html.erb (2.5ms)
App 1956 stdout: [2015-04-06 19:32:28.635 INFO ] Rendered courses/students.html.erb within layouts/application (240.3ms)
App 1956 stdout: [2015-04-06 19:32:28.649 INFO ] Completed 200 OK in 315ms (Views: 132.1ms | ActiveRecord: 135.0ms)

**Comment by ntdb** [comment]
Resolved in 2a36be9799bfbea99e0d0a27dd9ebb7f4e1cad9f
