### ISSUE TITLE
react-tools is deprecated

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#634]
```
npm WARN deprecated react-tools@0.12.1: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
```

Facebook suggests migrating to Babel, I guess?

**Comment by thenickcox** [comment]
Where are you seeing this error message?

**Comment by ragesoss** [comment]
Shows up during npm install when setting up from nothing, I think. Also, looks like we need to bump react modules to 0.14.7. I thought we'd pinned down all the react-dependencies, but it doesn't appear so.

**Comment by ragesoss** [comment]
Not sure this is still relevant, but if so, it's basically covered under #596
