### ISSUE TITLE
Two tests failing

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#638]
This is almost certainly my fault, but for the record I have two test failures I don't understand yet:

```

  1) the course page overview displays title, tab links, stats, description, school, term, dates, milestones
     Failure/Error: expect(page.find('#articles-created')).to have_content new_articles
       expected to find text "10" in "0 Articles Created"
     # ./spec/features/course_page_spec.rb:126:in `block (3 levels) in <top (required)>'

  2) RevisionImporter.users_with_no_revisions does not return users who have revisions for the course
     Failure/Error: expect(described_class.users_with_no_revisions(course_1)).to be_empty
       expected `#<ActiveRecord::AssociationRelation [#<User id: 4543197, wiki_id: "Ragesock", created_at: "2016-02-03 20:06:31", updated_at: "2016-02-03 20:06:31", trained: false, global_id: nil, remember_created_at: nil, remember_token: nil, wiki_token: nil, wiki_secret: nil, permissions: 0, real_name: nil, email: nil, onboarded: true, greeted: false, greeter: false>]>.empty?` to return true, got false
     # ./spec/lib/importers/revision_importer_spec.rb:88:in `block (3 levels) in <top (required)>'
```

**Comment by thenickcox** [comment]
That first one definitely isn't your fault; it's been flaky for a while. I'm hoping to get a chance to take a look at it this week. I don't, however, recognize that second one.

**Comment by ragesoss** [comment]
That first one is flaky in the sense that, if it's happening locally consistently for you, it's probably a javascript error. Showing 0 instead of 10 is what happens if that component gets broken during render after it renders the default state.

The second one is a new test that I added last week in #627. I'm at a loss as to why it would be failing. My code is flawless, I say. Flawless!

**Comment by thenickcox** [comment]
@ragesoss Doesn't seem like a JS error. Sticking a `binding.pry` in the `jbuilder` for course gives 0 for the article count. So there's something else going on. Investigating now.

**Comment by thenickcox** [comment]
Well, 0b93af6 fixed the first one.

**Comment by thenickcox** [comment]
FTFY!

**Comment by adamwight** [comment]
Works for me!
> 536 examples, 0 failures, 7 pending

**Comment by thenickcox** [comment]
Of course, there are still intermittently some tests that [Travis doesn't like](https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/107022954).
