### ISSUE TITLE
Node giving error installing acorn package

### ISSUE THREAD

**Issue by AbdealiJK** [WikiEducationFoundation/WikiEduDashboard#642]
I'm currently using:
 - nodejs v5.5.0
 - npm v3.3.12
 - nvm v0.30.2 was used to set those up

I'm trying a fresh install of the dashboard. I seem to keep getting this error:
```
npm ERR! path ../acorn/bin/acorn
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../acorn/bin/acorn' -> '/home/ajk/Documents/wiki/WikiEduDashboard/node_modules/.bin/acorn'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, symlink '../acorn/bin/acorn' -> '/home/ajk/Documents/wiki/WikiEduDashboard/node_modules/.bin/acorn']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../acorn/bin/acorn',
npm ERR!   dest: '/home/ajk/Documents/wiki/WikiEduDashboard/node_modules/.bin/acorn',
npm ERR!   parent: 'WikiEduDashboard' }
npm ERR! 
```

Is this possibly because of https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/596 ?
Also, although a ruby version is mentioned in the [readme-setup](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md) there is no version for nodejs mentioned. Am I using a compatible version ?

**Comment by bmathews** [comment]
Which command are you running?  `npm install`? 

I think most of us have been using node `v4.2.*`, but this particular error is not likely related to your npm/node versions.

**Comment by AbdealiJK** [comment]
Yes, in using npm install
Let me try 4.2.x

-----Original Message-----

**Comment by AbdealiJK** [comment]
The issue persisted with 4.2.x but after reinstalling node from nvm it worked fine.
