### ISSUE TITLE
Firefox error when running browser tests

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#645]
When running all specs from within guard, one of the first browser tests causes an alert popup, somewhere around this number of dots:
> 11:51:06 - INFO - Running all specs
> .....................................................................................Qt: Session management error: Could not open network socket
> .........

The error dialog says,
> An error occurred while loading or saving configuration information for firefox. Some of your configuration settings may not work properly.

Debian 8.3, FF 44.0

**Comment by ragesoss** [comment]
I've not seen this recur. Let's reopen if it pops up again, but if it's browser specific, developers will have moved on to later versions.
