### ISSUE TITLE
Article title fields should autocomplete

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#649]
Do a prefix (or better) search against the wiki API to populate autocomplete.

**Comment by adamwight** [comment]
Might be some relation to #399.

**Comment by ragesoss** [comment]
Might not be usable, but here's some similar functionality from the playlist app: https://github.com/WikiEducationFoundation/Wiki-Playlist/blob/master/app/react/actions/SearchAPI.js

**Comment by medhabansal** [comment]
@ragesoss Have been investigating on this issue and have a few questions about API usage, could we discuss the expected design?

**Comment by ragesoss** [comment]
Sure. The short answer is that it would work similarly to this: http://playlist.wiki/

It would make calls to the Wikipedia API from the client, showing a list of suggested titles based on what the user has typed so far. This would be within the AssignButton component.

I'm around on IRC if you want to chat in more depth.

**Comment by hjhimanshu01** [comment]
@ragesoss , may I work on this if it's available , i have worked on similar one before?

**Comment by hjhimanshu01** [comment]
@ragesoss , unable to comprehend the AssignButton link in this enhancement , would like to have a chat on IRC?

**Comment by bwreid** [comment]
@hjhimanshu01 Sage will be out this week. Do you have access to the Slack? We could chat over that if you like.

**Comment by hjhimanshu01** [comment]
@bwreid , Yes , let's have a conversation over slack  , also could you add me there , I'm not currently added on slack.

**Comment by bwreid** [comment]
@hjhimanshu01 Great! Please just send me an email at wes@wikiedu.org
