### ISSUE TITLE
web server crashes

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#65]
There was another crash that required a restart of apache. I can't get to the relevant logs in cron.log because it chokes 'less', but it looks like there was a mysql error during an import_revisions task on staging.

I also note that the staging cron.log has grown to 26MB while the production log is like 1.6MB.

**Comment by ragesoss** [comment]
And it was down again this morning.

**Comment by ntdb** [comment]
@ragesoss I'm seeing 'Mysql2::Error: Out of memory' errors on both staging and production. I'm going to add some logic to reduce the memory strain on Mysql (at the expense of update speed) and see if that straightens things out.

**Comment by ntdb** [comment]
In 6a9124b4163519cff3331dc65120479cdf834e13 I updated the revisions to be imported in batches: hopefully this reduces the memory strain. Let's leave this open until we're sure that the error has gone away.

**Comment by ntdb** [comment]
This morning I configured a swap file on the staging/production server using (this process)[https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04]. This will give us some low-performance breathing room on memory usage.

**Comment by ntdb** [comment]
We need to maintain a good balance between CPU load (more sql queries) and memory load (fewer sql queries). Currently we err on the side of memory load and a 4gb swap file has resolved the server crashes.
