### ISSUE TITLE
Course creator slug should only update when data is valid

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#654]
Generally, there should be indication in this dialog of which fields are required.  For this bug, there is a string "/()" in the lower left corner, which shows the course slug once course title, school, and term are filled out.  I would suggest not displaying the slug until there is data in all of these fields.  Update interval could be much longer as well, like a second.

**Comment by ragesoss** [comment]
The update is just handled by React (and refreshed any time the state changes), so that might be complex and probably isn't necessary. But just not rendering it at all if it's not valid would be good.

**Comment by sejalkhatri** [comment]
Hello  adamwight!
Initially nothing displayed and once all the fields are filled then the slug is displayed, _doubt_ - After that if user changes the fields than it just updates the data and displays Right?

**Comment by ragesoss** [comment]
@sejalkhatri yeah, that sounds right to me.

**Comment by sejalkhatri** [comment]
Ok Thanks @ragesoss:), I'll commit the working patch by tomorrow.
