### ISSUE TITLE
Entering dates by keyboard causes failure to popdown calendar

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#656]
In step 1 of the course creation wizard, enter '2016-01-01' into the start field, by manually typing.  Key another date into the end date.  You'll have two calendars popped up.

![calendarlap](https://cloud.githubusercontent.com/assets/819437/12863120/2574ceda-cc27-11e5-8822-dab11ba39ef5.png)

**Comment by ragesoss** [comment]
This was fixed with the switch to the new DatePicker in #891
