### ISSUE TITLE
Student rows are much too wide on Windows

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#66]
Here is what staging looks like on Chrome and IE on Windows. (Production layout is fine.)

![screenshot 4](https://cloud.githubusercontent.com/assets/848483/7077389/4a8ad138-dec5-11e4-851a-09951a607d43.png)

![screenshot 5](https://cloud.githubusercontent.com/assets/848483/7077363/0e3baefa-dec5-11e4-828a-8c713bef263d.png)

**Comment by ntdb** [comment]
Resolved in d314395e6e0b7c6dd5e22f2c214f05a957666500 by switching back to FontAwesome.
