### ISSUE TITLE
School name should be optional?

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#661]
I'm not certain about the UX here, but it seems like course.school should be an optional field.  This would require changing course slug generation and routing.

**Comment by adamwight** [comment]
This was declined during an IRL discussion.

**Comment by AndrewGreen** [comment]
@adamwight, any more details? I guess the reason for suggesting it be optional would be for things that aren't courses? If it's not optional, then it'll be the organizer or some kind of connected institution when "school" doesn't quite apply?
