### ISSUE TITLE
Enrollment / onboarding flow is broken

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#674]
@thenickcox I missed a regression with the react-router upgrade: during the signup/onboarding/enrollment flow, when a user finishes onboarding they are redirected to `/onboarding/NaN` instead of back to the enroll link where they started from.

This is tested (with a spec marked `pending` because it flickers on travis) here: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/spec/features/student_role_spec.rb#L144

**Comment by ragesoss** [comment]
The return-to params appears to be set right up until the 'Finish' step when it renders a placeholder before (normally) loading the course page.

cc @bmathews

**Comment by thenickcox** [comment]
@ragesoss Sounds like we should roll back until we can more fully investigate this on Monday?

**Comment by ragesoss** [comment]
@thenickcox yeah, I rolled back production already.

**Comment by ragesoss** [comment]
It looks like the return_to param is going through multiple encodings...
at the first step, it's `%2Fcourses%2FUniversity%2FAn_Example_Course_(Term)%3Fenroll%3Dpasscode`
and then it becomes `%252Fcourses%252FUniversity%252FAn_Example_Course_%2528Term%2529%253Fenroll%253Dpasscode`
