### ISSUE TITLE
It should be easier to add articles (/assignments) to a course

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#678]
If I want to assign myself an article, currently I have to navigate to the "Students" tab.  This is not the first thing I'd try.  I'd like to also have a way to add articles from the "Articles" tab.

**Comment by ragesoss** [comment]
This is part of #297. See also https://trello.com/c/0UlcWcM2/4-dashboard-logged-in-homepage-should-show-personal-stats-and-relevant-links-tools-for-students

Hoping to get some designs ready very soon, and then squeeze in implementation bit by bit as we get a chance.
