### ISSUE TITLE
Course clone form moves cursor when you edit the middle of a field

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#697]
I tried to add something to the middle of the Title field, and after the first character, my cursor always moves to the end.

**Comment by mattfordham** [comment]
Hoping this is solved by: https://github.com/WikiEducationFoundation/WikiEduDashboard/tree/CourseClonedFieldsFix

This fix may address some of the other issues in this "project". Will see tomorrow ;)

**Comment by mattfordham** [comment]
Tests passed. Gonna leave open though until I've look into the other related issues.
