### ISSUE TITLE
Assigned article listed for the wrong course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#7]
User Huimin Zhong has been in a Fall 2014 course and a Spring 2015. They had an assigned article for the Fall 2014 course, but not for the Spring 2015 course.

Production, which does not include the Fall 2014 course in any cohorts, correctly lists the user as "no assigned article": http://dashboard.wikiedu.org/courses/Louisiana_State_University/CHEM_4558:_Mass_Spectrometry_(Spring_2015)

Staging incorrectly lists the assigned article "Environmental effects of laundry wastewater" for the Spring 2015 course: http://dashboard-testing.wikiedu.org/courses/Louisiana_State_University/CHEM_4558:_Mass_Spectrometry_(Spring_2015)

That article is also listed (correctly) on Staging for the Fall 2014 course: http://dashboard-testing.wikiedu.org/courses/Louisiana_State_University/CHEM_4150_Environmental_Chemistry_(Fall_2014)

**Comment by ntdb** [comment]
FYI in cases of multiple assignments for one user in a single course only the newest assigned article will be shown. When multiple assignments are imported at the same time the one listed first on the course page will be used.
