### ISSUE TITLE
Survey javascripts don't work on staging or on my development environment

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#717]
@hudakdidit 

From `surveys.html.haml`
``` 
  - if Rails.env == "production"
    = javascript_include_tag fingerprinted('/assets/javascripts/', 'survey.js')
    - if can_administer?
      = javascript_include_tag fingerprinted('/assets/javascripts/', 'survey_admin.js')
  - else 
    = javascript_include_tag 'http://localhost:8080/static/survey.js'
    - if can_administer?
      = javascript_include_tag 'http://localhost:8080/static/survey_admin.js'  
```

This doesn't work on staging (where `staging` is the Rails env), and it also doesn't work for me locally. What tool opens up port 8080 (as opposed to the normal port 3000 for guard)?

I also don't like having so much development-oriented code in that layout. Can we push that logic into application helper, like we already do with the favicon?

**Comment by hudakdidit** [comment]
@ragesoss 

This should be addressed in ed7e5b569eee87e3b061eae67461ac3fa0deb0f3 and dfc9c8918591656b80f49cfd81defaa6ccc1dafc

The conditional is now only for dev to deliver non-timestamped and hot assets falling back to production built assets.

The [development webpack setup serves](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/surveys/config/webpack/webpack.config.dev.js) the javascript with webpack-dev-server which is available on port 8080. The thought is we might eventually port over the rest of the javascript compilation to webpack which is faster to compile. Hot loading for react component should also significantly improve the dev workflow. *Hot loading doesn't work with normal coffeescript compilation (the coffee-loader doesn't seem to accomodate it) so it fallback to a livereload-style automatic page refresh on javascript changes.
