### ISSUE TITLE
Add 'I need help' button for instructors and students

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#730]
We'd like to make it easier for users — instructors and students in particular — to request help in a low-friction way from the dashboard.

The idea would be to take some action — either send an email or create a notification for the Wiki Ed staff assigned to the course — if a user clicks some highly discoverable button on the course dashboard.

**Comment by thenickcox** [comment]
Would there be a message with the "I need help" message, or would it really just signal to the admin to check in with that user?

**Comment by ragesoss** [comment]
I guess I never moved the details from discussion to writing...

This should bring up a modal (cc @rileywho) that has an area for messaging — I'll get a draft together shortly — that tries to help the user help themselves, and then at the bottom, has buttons to contact any of the Wiki Ed staff assigned to the course.

**Comment by ragesoss** [comment]
I'm pretty sure it will also need to show a different message for students vs. non-students.

**Comment by ragesoss** [comment]
The content expert for a course is the nonstudent user in the course with both `permissions: 1` and `greeter: true`. The program manager for a course is the nonstudent user with `permissions: 1` and `greeter: false`.

**Comment by mattfordham** [comment]
@ragesoss Will there *always* be a “content expert” and a “program manager" based on this criteria? In other words, should there be a fallback contact(s)?

**Comment by ragesoss** [comment]
There is not guaranteed to be one, although for our programs there always will be as a matter of how we run them. The fallback should maybe just omit the user contact bit altogether.

**Comment by mattfordham** [comment]
Cool, that makes sense. 

Also, if the current user is a student, they should only see the "content expert". If the user is an instructor, they should see both roles (assuming they exist). Is this true?

**Comment by ragesoss** [comment]
Correct.

**Comment by ragesoss** [comment]
Merged this last week
