### ISSUE TITLE
REST endpoint to get JSON summary of assigned articles

### ISSUE THREAD

**Issue by ftrotter** [WikiEducationFoundation/WikiEduDashboard#735]
I would love to be able to build tools specifically for medical students who are taking a given class, right beside the WikiEduDashboard.

To do that I really need to be able to get a json data source with the following data

- name of course
- array of username(s) of teacher(s)
- start and end date of the course
- array of articles, each article contains:

1.        array of assigned editors usernames
2.        array of assigned reviewers usernames

the id of the revision where the student started editing the page would be nice, but i can figure that out using other api calls.

Using this I can build additional functionality that will only be useful for medical students but still respect the dashboards notion of what a class is (exactly). That means I will not have to try and manually replicate the work that the the dashboard automatically does by hand. 

Essentially I want a JSON data equivalent of this: https://dashboard.wikiedu.org/courses/Saint_Louis_University/Advanced_Evolution_(Spring_2016)/articles

thanks
-ft

**Comment by ragesoss** [comment]
That data is currently spread across several endpoints:
* https://dashboard.wikiedu.org/courses/Saint_Louis_University/Advanced_Evolution_%28Spring_2016%29/course.json
* https://dashboard.wikiedu.org/courses/Saint_Louis_University/Advanced_Evolution_%28Spring_2016%29/users.json
* https://dashboard.wikiedu.org/courses/Saint_Louis_University/Advanced_Evolution_%28Spring_2016%29/assignments.json
* https://dashboard.wikiedu.org/courses/Saint_Louis_University/Advanced_Evolution_%28Spring_2016%29/revisions.json

If that doesn't get you where you want to be, I could probably toss together an ad-hoc temporary API that brings all that stuff together, for you to use in the short term.

We plan to create a more general API for extracting data from the dashboard, probably within the next year, but in the short term, let me know if the existing front-end APIs are good enough to hold you over.

**Comment by ragesoss** [comment]
@ftrotter ping. Let me know if the existing endpoints will work for you.

**Comment by ftrotter** [comment]
I will not have time to work on this for a bit... but I am confident this is what I need. 

Thanks for building it "open by default"... that is kinda awesome.

Closing the ticket now...
