### ISSUE TITLE
Conditional questions based on checkbox answers are always displayed

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#736]
@hudakdidit I'm trying to set up a pair of questions that first asks which of a set of resources were used, and then (as a matrix) asks for how useful each selected resource was. So the idea is that one line of the matrix is shown for each of the checkbox options chosen in the first question.

All the conditional matrix questions show up, no matter what checkboxes are selected in the first question.

See https://dashboard-testing.wikiedu.org/rapidfire/question_groups/4/answer_groups/new

**Comment by hudakdidit** [comment]
@ragesoss gotcha. I know the cause. Thanks for the report

**Comment by ragesoss** [comment]
Fixed along with #759
