### ISSUE TITLE
Formatting options for question prompts are limited

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#737]
I'm trying to put together a question that includes both some contextual info and a specific question, and the question should be the focus. Something like this:

----

<small>This term, new Wikipedia editors — including your students — were given the option to edit articles with traditional wikicode or with the new VisualEditor. The new VisualEditor is a "WYSIWYG" software that enabled students to edit Wikipedia articles similar to how they would edit text in a word processing software like Microsoft Word, without having to use wikicode.</small>

### Did you instruct your students to use VisualEditor?

----

This doesn't appear to be possible.

**Comment by hudakdidit** [comment]
@ragesoss did you try using the 'text' type question? It isn't really a question, but uses the Trix Editor.

Earlier on, I attempted to use the trix editor for survey questions, but the html output was causing some issues. I can take another pass at it though.

Another alternative would be to add an optional **question introduction** field. Thought?

**Comment by ragesoss** [comment]
@hudakdidit Trix is really limited in the kinds of formatting it can do. In particular, it can't do headers, or changes in text size, or horizontal rules. Using a Text question would be the alternative, but that separates it from the question itself. I'm not sure if using markdown would make things any easier, but that would provide a lot of flexibility. A question introduction field would be an okay alternative, but I'd rather avoid that added complexity of the question creation UX.

**Comment by hudakdidit** [comment]
@ragesoss 

You can now use markdown for question text!

https://dashboard-testing.wikiedu.org/surveys/rapidfire/question_groups/12/answer_groups/new?preview

I've added a markdown editing tab with a html preview, and html source preview in the question form
