### ISSUE TITLE
Checkbox and Select Type Questions Don't Work Properly

### ISSUE THREAD

**Issue by hudakdidit** [WikiEducationFoundation/WikiEduDashboard#739]
Changing the checkbox or select answers in the first question creates difficult navigation from one question to the next. The biggest issue is that it becomes impossible to reveal the submit button.

@rileywho just pinging you on this as we were discussing it earlier. I'll track progress on this ticket.

Checkbox example: https://wiki-dashboard-surveys.herokuapp.com/rapidfire/question_groups/312/answer_groups/new

Multi-Select: https://wiki-dashboard-surveys.herokuapp.com/rapidfire/question_groups/302/answer_groups/new

**Comment by ragesoss** [comment]
This is resolved now, @hudakdidit ?

**Comment by hudakdidit** [comment]
Yes, this is no longer an issue with the new Question navigation UI
