### ISSUE TITLE
loading a manual_update directly results in an Apache "Not Found" message

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#74]
I went here: http://dashboard.wikiedu.org/courses/University_of_California,_Davis/BIS_98_(W15)/manual_update

Eventually, I got this:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /courses/University_of_California,_Davis/BIS_98_(W15) was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at dashboard.wikiedu.org Port 80</address>
</body></html>

This was the url I got sent back to:

http://dashboard.wikiedu.org/courses/University_of_California,_Davis%2FBIS_98_(W15)

Note that the slash got turned into a "%2F", and apparently rails did't know how to handle this at all. (Unlike previously, there was no exception logged on Sentry now.)

**Comment by ntdb** [comment]
Should be resolved in cdc189d08b772b69166e8561333cdd2e36773cd1

**Comment by ntdb** [comment]
Resolved in cdc189d.

Note: need an integration test for the manual update button.
