### ISSUE TITLE
Wiki Ed blog should be easily accessible from the dashboard

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#742]
We've got a lot of relevant content going up onto the wikiedu.org blog, but the dashboard provides no obvious paths to discover. How can we tie the blog closer to the dashboard?

cc @rileywho @owwls

**Comment by thenickcox** [comment]
@rileywho Any recommendations for placement?

**Comment by ragesoss** [comment]
Finished a couple of weeks ago
