### ISSUE TITLE
Admins should be able to change course type 

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#747]
Currently, the only ways to modify the type of a course are via the backend. There should be a way for an admin to change the course type in the Details component.

**Comment by ragesoss** [comment]
@thenickcox @bmathews I'm working on a selector to allow admins to change the course type.

I started with this: b1296ae4c28151af097024c66202837b487078be

I'm not sure what to do next to make the data flow properly. I'd like it to work the same way as the `TextInput` fields like passcode, which takes `@updateDetails` as the `onChange` prop and thereby uses CourseActions to update the data, and then waits for Save to send it on. But how `TextInput` utilizes that update method is opaque to me, and it's a very complex component for something as seemingly simple as text input. Any pointers appreciated.

**Comment by ragesoss** [comment]
Oh, the other thing I'm confused about is the lint validation errors:

`'course' is missing in props validation`

etc.

**Comment by bmathews** [comment]
The lint error is saying that you need to specify what props your component accepts. Before your render method, add:
```
propTypes: {
  course: React.PropTypes.object,
  editable: React.PropTypes.bool
}
```

**Comment by ragesoss** [comment]
Cool, thanks. I was looking at notifications.jsx as an example, but I guess it doesn't require that because it doesn't use any props, just state.

**Comment by bmathews** [comment]
Looking at the `details.cjsx` `updateDetails` method, it expects a key and a value as arguments, and then it uses that to directly update the course object.  So in our `course_type_selector`, we can follow the same pattern as the `TextInput` and take that `value_key` as a property. (the React Way :tm: is to use camel case and our linter will enforce that for jsx components). 

Let me know if that helps or if I'm misunderstanding the question! 

```
// course_type_selector.js

handleChange(e) {
  // call the onChange property and pass in the valueKey and new select value)
  this.props.onChange(this.props.valueKey, e.target.value)
},

render() {
  return (
    <select onChange={this.handleChange} value={this.props.value} >
        ...
    </select>
  )
}
```

```
// details.cjsx
render() {
  <CourseTypeSelector onChange={@upateDetails} value={@props.course.course_type}  valueKey="course_type" />
}

```

**Comment by ragesoss** [comment]
@bmathews thanks! That is super helpful. I cut a level of complexity and just implemented the call to CourseActions within CourseTypeSelector: 424f222a3f86a18fed2b1dd43d62769222d95c39

Now I think I just need to get the data to Rails and it will be all set!

**Comment by bmathews** [comment]
That works! :+1:
