### ISSUE TITLE
Revisions and Users should join without relying on user.id == rev_user

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#753]
@adamwight @AndrewGreen 

Currently, join Revisions and Users based on User#id and and Revision#user_id.  The revision user_id attribute gets imported from Replica based on the `rev_user` id, which is the mediawiki user id. To enable multiwiki support, we need to decouple User#id from the mediawiki user id.

How should we do that? One option would be to look up the user via username and store *that* id. That's probably the easiest to implement; I'm not sure whether it would have a significant performance cost, though. The revision import is already the main bottleneck of the update cycle.

I guess I'll go ahead and do it that way, and then we can sort out any performance stuff later.

**Comment by adamwight** [comment]
I would join on User.id, which will become an autoincrement column.  When
we fetch the revision, pull the username column and then look that up
locally to get the User primary key.  Pulling username should be efficient,
I believe it's the rev_user column on the MW revision table.

**Comment by ragesoss** [comment]
Thanks @adamwight It's rev_user_text, I think, that has the username. We already get it via Replica, although we don't use it. I took a pass at it in an experimental branch yesterday, and assuming the lookup to get User primary key is efficient as well, I think it'll work fine. There are still some couplings that break tests that I haven't pinned down, though.

**Comment by ragesoss** [comment]
Okay, I think I've fixed that. Next step should be to remove user ids from all examples created in the specs the specs and see if anything breaks.

**Comment by ragesoss** [comment]
@adamwight @thenickcox @bmathews 
I ran into something very surprising. Update time dropped from 4 hours to 1 hour after I deployed yesterday. Revision import has always been the bottleneck, and here are the relevant changes I made:

71b0d358fb68252636d87d873b28c0553fb4bd66
a76f00201616a25ea8dca73542e16e2cdb4f8c2c

Does that make sense? If so, how? It seems to good to be true, as I wasn't even trying to speed this up.

**Comment by ragesoss** [comment]
Nick helped me figure out the reason; see fbcb580d4cf9eb2bdbdda0224e44c921b13cbd2b

**Comment by ragesoss** [comment]
Okay, I think this is taken care of. However, the update times are still much faster than previously. I guess somehow in this case, Article.import was taking a lot longer than creating new records one at a time. (Perhaps that's because the number of actually new articles is small.)
