### ISSUE TITLE
Remaining JS components without tests

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#755]
This issue is to keep track of the remaining JS components that have 0 tests. (A check denotes that the component has at least one test.)
- [x] app/assets/javascripts/components/activity/activity_table.jsx
- [x] app/assets/javascripts/components/activity/activity_table_row.jsx
- [x] app/assets/javascripts/components/activity/did_you_know_handler.jsx
- [x] app/assets/javascripts/components/activity/plagiarism_handler.jsx
- [x] app/assets/javascripts/components/activity/recent_activity_handler.jsx
- [x] app/assets/javascripts/components/activity/recent_edits_handler.jsx
- [x] app/assets/javascripts/components/articles/article.jsx
- [x] app/assets/javascripts/components/articles/article_list.jsx
- [x] app/assets/javascripts/components/articles/articles_handler.jsx
- [ ] app/assets/javascripts/components/assignments/assignment.cjsx
- [ ] app/assets/javascripts/components/assignments/assignment_list.cjsx
- [ ] app/assets/javascripts/components/common/affix.cjsx
- [ ] app/assets/javascripts/components/common/calendar.cjsx
- [x] app/assets/javascripts/components/common/checkbox.jsx
- [ ] app/assets/javascripts/components/common/course_link.cjsx
- [ ] app/assets/javascripts/components/common/list.cjsx
- [ ] app/assets/javascripts/components/common/loading.cjsx
- [ ] app/assets/javascripts/components/common/lookup.cjsx
- [ ] app/assets/javascripts/components/common/lookup_select.cjsx
- [x] app/assets/javascripts/components/common/modal.cjsx
- [x] app/assets/javascripts/components/common/notifications.jsx
- [ ] app/assets/javascripts/components/common/popover.cjsx
- [ ] app/assets/javascripts/components/common/select.cjsx
- [ ] app/assets/javascripts/components/common/text_area_input.cjsx
- [ ] app/assets/javascripts/components/common/text_input.cjsx
- [x] app/assets/javascripts/components/course_creator/course_creator.jsx
- [x] app/assets/javascripts/components/course.cjsx
- [x] app/assets/javascripts/components/high_order/conditional.jsx
- [ ] app/assets/javascripts/components/high_order/editable.cjsx
- [ ] app/assets/javascripts/components/high_order/expandable.cjsx
- [ ] app/assets/javascripts/components/high_order/lookup_wrapper.cjsx
- [ ] app/assets/javascripts/components/high_order/popover_button.cjsx
- [ ] app/assets/javascripts/components/high_order/reorderable.cjsx
- [ ] app/assets/javascripts/components/onboarding/index.cjsx
- [ ] app/assets/javascripts/components/overview/actions.cjsx
- [x] app/assets/javascripts/components/overview/cohort_button.cjsx
- [x] app/assets/javascripts/components/overview/course_cloned_modal.cjsx
- [ ] app/assets/javascripts/components/overview/description.cjsx
- [ ] app/assets/javascripts/components/overview/details.cjsx
- [ ] app/assets/javascripts/components/overview/grading.cjsx
- [ ] app/assets/javascripts/components/overview/inline_users.cjsx
- [x] app/assets/javascripts/components/overview/milestones.cjsx
- [ ] app/assets/javascripts/components/overview/overview_handler.cjsx
- [x] app/assets/javascripts/components/overview/tag_button.cjsx
- [ ] app/assets/javascripts/components/overview/this_week.cjsx
- [x] app/assets/javascripts/components/timeline/block.jsx
- [x] app/assets/javascripts/components/timeline/empty_week.cjsx
- [ ] app/assets/javascripts/components/timeline/gradeable.cjsx
- [ ] app/assets/javascripts/components/timeline/grading.cjsx
- [ ] app/assets/javascripts/components/timeline/meetings.cjsx
- [ ] app/assets/javascripts/components/timeline/orderable_block.cjsx
- [ ] app/assets/javascripts/components/timeline/timeline.cjsx
- [ ] app/assets/javascripts/components/timeline/timeline_handler.cjsx
- [x] app/assets/javascripts/components/timeline/week.cjsx
- [ ] app/assets/javascripts/components/training_modules.cjsx
- [ ] app/assets/javascripts/components/uploads/upload.cjsx
- [ ] app/assets/javascripts/components/uploads/upload_list.cjsx
- [ ] app/assets/javascripts/components/uploads/uploads_handler.cjsx
- [ ] app/assets/javascripts/components/wizard/form_panel.cjsx
- [ ] app/assets/javascripts/components/wizard/option.cjsx
- [ ] app/assets/javascripts/components/wizard/panel.cjsx
- [ ] app/assets/javascripts/components/wizard/summary_panel.cjsx
- [ ] app/assets/javascripts/components/wizard/timeline_panel.cjsx
- [ ] app/assets/javascripts/components/wizard/wizard.cjsx
- [ ] app/assets/javascripts/training/components/quiz.cjsx
- [x] app/assets/javascripts/training/components/slide_link.cjsx
- [x] app/assets/javascripts/training/components/slide_menu.cjsx
- [ ] app/assets/javascripts/training/components/training_app.cjsx
- [ ] app/assets/javascripts/training/components/training_library_handler.cjsx
- [ ] app/assets/javascripts/training/components/training_module_handler.cjsx
- [ ] app/assets/javascripts/training/components/training_slide_handler.cjsx

**Comment by ragesoss** [comment]
I don't aspire to having a test for each React component anymore. Our strategy is to focus on browser tests, with coverage data based on those tests to identify components and codepaths that don't get used during the tests, with supplementary component tests only when it seems worthwhile on a case-by-case basis.
