### ISSUE TITLE
Implement hamburger menu for mobile

### ISSUE THREAD

**Issue by rileywho** [WikiEducationFoundation/WikiEduDashboard#756]
@ragesoss Since the survey supports mobile, I was thinking that it would be a good idea to update the mobile design make it easier to log in and navigate to the survey. I'll be attempting to find specific actions and will log them into github. Thoughts?

Current mobile experience:
![img_0515 png](https://cloud.githubusercontent.com/assets/2120466/14370325/0c4b5af0-fce2-11e5-892d-0662b7a8a451.jpeg)

**Comment by ragesoss** [comment]
It's not quite so bad for non-admins. The nav bar is disrupted, but there is no overlap of links and it is usable.

This would be nice to fix, but it's not urgent.
![img_1116](https://cloud.githubusercontent.com/assets/848483/14683668/c50b47c8-06e0-11e6-957d-dc535fdf281d.PNG)
