### ISSUE TITLE
Mobile login error

### ISSUE THREAD

**Issue by rileywho** [WikiEducationFoundation/WikiEduDashboard#757]
(iphone chrome) The first time you try to log in from the dashboard on a mobile device, I get the following error: (see image). You can bypass the error by going back to the dashboard and loging in for the second time.

![img_0517 png](https://cloud.githubusercontent.com/assets/2120466/14370701/6804a8b2-fce5-11e5-9bba-f288b8177f7d.jpeg)

**Comment by ragesoss** [comment]
Do you mean with a new account? I couldn't replicate on iPhone / Safari with an existing account. Maybe Chrome is more aggressibe about forcing the mobile view?

**Comment by ragesoss** [comment]
I hit this sometimes, but not others. It's possibly related to this, but I'm not sure: https://phabricator.wikimedia.org/T112730
