### ISSUE TITLE
Mobile Wikipedia login flow

### ISSUE THREAD

**Issue by rileywho** [WikiEducationFoundation/WikiEduDashboard#758]
Is it possible to use Wikipedia's mobile version of the login page when loging in on a mobile device? @ragesoss 

![img_0518 png](https://cloud.githubusercontent.com/assets/2120466/14370755/c52539c6-fce5-11e5-8d1a-ca7761042dd2.jpeg)

**Comment by ragesoss** [comment]
Not at this time. I'll file some bugs and remind some folks about the problems with OAuth login on mobile, though.

**Comment by ragesoss** [comment]
This works now.
