### ISSUE TITLE
Layout bugs with long-ish matrix options

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#760]
@rileywho @hudakdidit 

https://dashboard-testing.wikiedu.org/surveys/14?preview

![survey matrix layout bug](https://cloud.githubusercontent.com/assets/848483/14470030/313c9dac-009c-11e6-8751-248268fb622e.png)

**Comment by hudakdidit** [comment]
@rileywho I can force the title to break with CSS

**Comment by rileywho** [comment]
@hudakdidit I would go ahead and do that. I'm planning on adjusting the overall scale of the matrix module in the current design pass

**Comment by hudakdidit** [comment]
this one has some long-ish titles https://dashboard-testing.wikiedu.org/surveys/15?utf8=%E2%9C%93&preview=true&course_slug=University_of_Oklahoma%2FHSCI_3013%3A_History_of_Science_to_the_Age_of_Newton_%28Summer_2014%29&commit=Start+Survey
