### ISSUE TITLE
phantomjs install often breaks npm install on travis

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#761]
It looks like travis has frequent troubles with the phantomjs install. The error message says it needs to install version 1.9.7 because the system version is 1.9.8, and then there is some sort of network issue that causes it to fail a lot.

Can we change our dependencies so that they can use 1.9.8? That would probably make our builds more reliable and maybe speed them up a bit.

cc @hudakdidit @bmathews

**Comment by hudakdidit** [comment]
Yes! This has been annoying. Adding it to my todos

**Comment by ragesoss** [comment]
Nope, that didn't do it. Still thinks it needs 1.9.7-15.

**Comment by hudakdidit** [comment]
This seems to have fixed it https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/18240b0dec4028c54e62cb7ab976236eeaf564d9

**Comment by ragesoss** [comment]
I'm not sure that it did, but that might be just because gulp-mocha-phantomjs (the version that specifies the outdated phantomjs binary) is still in the shrinkwrap file. On travis I still see the phantomjs install happining during `npm install`. This one just happened to have not broken.

**Comment by ragesoss** [comment]
Also, what was the point of that `gulp/tasks/tests.js` file? Was it doing anything we cared about?

**Comment by hudakdidit** [comment]
I believe tests.js task was a remnant of our default gulp scaffold. Nate included it in the original repo.
It wasn't being called anywhere.

@bmathews recommended re-shrink-wrapping trying that nwo

**Comment by ragesoss** [comment]
This particular error hasn't happened in a while.
