### ISSUE TITLE
Empty matrix question is shown if no conditional questions are activated

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#763]
@hudakdidit 

If I have a checkbox question followed by a matrix question that has options corresponding to the checked options, the matrix question will still show up even if none of the component questions that make up the matrix are present.

![empty matrix](https://cloud.githubusercontent.com/assets/848483/14473452/fb6f4d6c-00ac-11e6-912a-2e34179513dc.png)

**Comment by ragesoss** [comment]
@hudakdidit I think you're working on this, but just wanted to note a few things related to the current state of it, based on testing https://dashboard-testing.wikiedu.org/surveys/rapidfire/question_groups/25/answer_groups/new?preview

1. Instead of an empty matrix question, it now just shows nothing at all. You can proceed from the empty screen with forward or back arrows.
2. If you go back and select an option (or multiple options) then proceed, it switches into the mobile view:

![mobile wat](https://cloud.githubusercontent.com/assets/848483/14504152/5bcdd528-0168-11e6-9665-5241359879cc.png)

**Comment by hudakdidit** [comment]
Ugh.. thanks for the report

**Comment by hudakdidit** [comment]
I think I've got this fixed now!
