### ISSUE TITLE
home_page_spec fails intermittently on navigation to a course page

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#77]
For example, here's the failure I just got. When I ran `rake spec` again immediately, everything passed. I'm not sure, but I think I tend to get failures when my dev environment has something else going on at the same time. I've tried to puzzle it out, and I've got no idea why this sometimes fails. The test logic seems pretty straightforward.

Failures:

  1) the home page course rows should allow navigation to a course page
     Failure/Error: expect(current_path).to eq(course_path(first_course))
       
       expected: "/courses/course_1"
            got: "/courses/course_6"
       
       (compared using ==)
     # ./spec/features/home_page_spec.rb:134:in `block (3 levels) in <top (required)>'

**Comment by ragesoss** [comment]
This happened for the first time on a travis ci build today.

**Comment by ragesoss** [comment]
I commented out that test, but it'd be nice to solve the problem and reenable it.

**Comment by ntdb** [comment]
This test was re-enabled in 45e00c8f602a050e6547f8fee89bcd3b67c8d718. We recently updated to qt5 and have done a lot of work that touches route handling since this first appeared. Optimistically closing for now. :)
