### ISSUE TITLE
When editing an already-created question with a conditional, the conditional shows as blank

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#770]
It looks like the conditional didn't get saved, but that doesn't appear to be the case.

**Comment by hudakdidit** [comment]
This should be fixed now. Ones that are currently blank most likely need to be re-saved due to updates for handling single and double quotes as well as html in answer text.

Working example: https://dashboard-testing.wikiedu.org/surveys/rapidfire/question_groups/4/questions/24/edit
