### ISSUE TITLE
Conditional based on an answer that include an apostrophe do not work

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#771]
@hudakdidit 

Try selecting the last answer here: https://dashboard-testing.wikiedu.org/surveys/rapidfire/question_groups/25/answer_groups/new?preview

The conditional question connected to that answer does not appear. It works properly if I do it without the apostrophe.

**Comment by hudakdidit** [comment]
Single (and double) quotes should be safe to use now
