### ISSUE TITLE
Start button does not work

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#776]
@hudakdidit If a survey has a course selector at the beginning, then it shows a confirmation screen with "Current Selected Course" and a Start button. Clicking the start button does not work. (The workaround is to use the right arrow.)

**Comment by ragesoss** [comment]
@hudakdidit What do the `data-next-survey-block` and `data-no-validate` parameters do here? Is that patch okay? I'm guessing not, but I don't understand  what's going on in this template.

**Comment by hudakdidit** [comment]
`data-next-survey-block` generally validates the current  question block.
https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/surveys/modules/Survey.js#L76

If it validates it navigates to the next question.

Your patch works fine, ideally the button would have a different data attribute that simply called the `nextBlock` method
