### ISSUE TITLE
Circular dependency error

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#78]
@ntdb This showed up on Sentry last night, only on production. Seems to be connected to your grade-grubbing change 966d3a5ed3063b8a8d483d4b4a8c29e3a0ff8789

Stacktrace (most recent call first):

  active_support/dependencies.rb:478:in `load_missing_constant'
    raise "Circular dependency detected while autoloading constant #{qualified_name}"
  active_support/dependencies.rb:180:in `const_missing'
    Dependencies.load_missing_constant(from_mod, const_name)
  active_support/dependencies.rb:512:in `load_missing_constant'
    return parent.const_missing(const_name)
  active_support/dependencies.rb:180:in `const_missing'
    Dependencies.load_missing_constant(from_mod, const_name)
  lib/grok.rb:15:in `views_for_article'
    data = Utils.parse_json(data)
  app/models/article.rb:132:in `block (3 levels) in update_views'
    views[a.id] = Grok.views_for_article(a.title, since)

**Comment by ragesoss** [comment]
Actually, can't be related to that change, as that one isn't on production. This error has happened now on both staging and production during daily updates, though, including breaking two in a row on production.

**Comment by ntdb** [comment]
Believed to be resolved in 56ef7284560a4bfc1cff9bc807a08784189de5b7.
