### ISSUE TITLE
Convert remaining cjsx/coffee files to jsx/js

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#780]
### .coffee
- [x] ./app/assets/javascripts/surveys/modules/SurveyAdmin.coffee
- [x] ./app/assets/javascripts/surveys/modules/SurveyAssignmentAdmin.coffee
- [x] ./app/assets/javascripts/surveys/modules/SurveyUtils.coffee
- [x] ./app/assets/javascripts/surveys/survey-admin.coffee
- [x] ./app/assets/javascripts/utils/api.coffee
- [x] ./app/assets/javascripts/utils/course.coffee
- [x] ./app/assets/javascripts/utils/course_date_utils.coffee
- [x] ./app/assets/javascripts/utils/date_calculator.coffee
### .cjsx
- [x] ./app/assets/javascripts/components/assignments/assignment.cjsx
- [x] ./app/assets/javascripts/components/assignments/assignment_list.cjsx
- [x] ./app/assets/javascripts/components/common/affix.cjsx
- [x] ./app/assets/javascripts/components/common/calendar.cjsx
- [x] ./app/assets/javascripts/components/common/course_link.cjsx
- [x] ./app/assets/javascripts/components/common/list.cjsx
- [x] ./app/assets/javascripts/components/common/loading.cjsx
- [x] ./app/assets/javascripts/components/common/lookup.cjsx
- [x] ./app/assets/javascripts/components/common/lookup_select.cjsx
- [x] ./app/assets/javascripts/components/common/modal.cjsx
- [x] ./app/assets/javascripts/components/common/popover.cjsx
- [x] ./app/assets/javascripts/components/common/select.cjsx
- [x] ./app/assets/javascripts/components/common/text_area_input.cjsx
- [x] ./app/assets/javascripts/components/common/text_input.cjsx
- [x] ./app/assets/javascripts/components/course.cjsx
- [x] ./app/assets/javascripts/components/high_order/conditional.cjsx
- [x] ./app/assets/javascripts/components/high_order/editable.cjsx
- [x] ./app/assets/javascripts/components/high_order/expandable.cjsx
- [x] ./app/assets/javascripts/components/high_order/lookup_wrapper.cjsx
- [x] ./app/assets/javascripts/components/high_order/popover_button.cjsx
- [x] ./app/assets/javascripts/components/high_order/reorderable.cjsx
- [x] ./app/assets/javascripts/components/onboarding/index.cjsx
- [x] ./app/assets/javascripts/components/overview/actions.cjsx
- [x] ./app/assets/javascripts/components/overview/cohort_button.cjsx
- [x] ./app/assets/javascripts/components/overview/course_cloned_modal.cjsx
- [x] ./app/assets/javascripts/components/overview/description.cjsx
- [x] ./app/assets/javascripts/components/overview/details.cjsx
- [x] ./app/assets/javascripts/components/overview/inline_users.cjsx
- [x] ./app/assets/javascripts/components/overview/milestones.cjsx
- [x] ./app/assets/javascripts/components/overview/overview_handler.cjsx
- [x] ./app/assets/javascripts/components/overview/tag_button.cjsx
- [x] ./app/assets/javascripts/components/overview/this_week.cjsx
- [x] ./app/assets/javascripts/components/revisions/revision.cjsx
- [x] ./app/assets/javascripts/components/revisions/revision_list.cjsx
- [x] ./app/assets/javascripts/components/revisions/revisions_handler.cjsx
- [x] ./app/assets/javascripts/components/students/assign_button.cjsx
- [x] ./app/assets/javascripts/components/students/assign_cell.cjsx
- [x] ./app/assets/javascripts/components/students/enroll_button.cjsx
- [x] ./app/assets/javascripts/components/students/student.cjsx
- [x] ./app/assets/javascripts/components/students/student_drawer.cjsx
- [x] ./app/assets/javascripts/components/students/student_list.cjsx
- [x] ./app/assets/javascripts/components/students/students_handler.cjsx
- [x] ./app/assets/javascripts/components/timeline/block.cjsx
- [x] ./app/assets/javascripts/components/timeline/empty_week.cjsx
- [x] ./app/assets/javascripts/components/timeline/gradeable.cjsx
- [x] ./app/assets/javascripts/components/timeline/grading.cjsx
- [x] ./app/assets/javascripts/components/timeline/meetings.cjsx
- [x] ./app/assets/javascripts/components/timeline/orderable_block.cjsx
- [x] ./app/assets/javascripts/components/timeline/timeline.cjsx
- [x] ./app/assets/javascripts/components/timeline/timeline_handler.cjsx
- [x] ./app/assets/javascripts/components/timeline/week.cjsx
- [x] ./app/assets/javascripts/components/training_modules.cjsx
- [x] ./app/assets/javascripts/components/uploads/upload.cjsx
- [x] ./app/assets/javascripts/components/uploads/upload_list.cjsx
- [x] ./app/assets/javascripts/components/uploads/uploads_handler.cjsx
- [x] ./app/assets/javascripts/components/wizard/form_panel.cjsx
- [x] ./app/assets/javascripts/components/wizard/option.cjsx
- [x] ./app/assets/javascripts/components/wizard/panel.cjsx
- [x] ./app/assets/javascripts/components/wizard/summary_panel.cjsx
- [x] ./app/assets/javascripts/components/wizard/timeline_panel.cjsx
- [x] ./app/assets/javascripts/components/wizard/wizard.cjsx
- [x] ./app/assets/javascripts/mixins/input_mixin.cjsx
- [x] ./app/assets/javascripts/training/components/quiz.cjsx
- [x] ./app/assets/javascripts/training/components/slide_link.cjsx
- [x] ./app/assets/javascripts/training/components/slide_menu.cjsx
- [x] ./app/assets/javascripts/training/components/training_app.cjsx
- [x] ./app/assets/javascripts/training/components/training_module_handler.cjsx
- [x] ./app/assets/javascripts/training/components/training_slide_handler.cjsx
- [x] ./test/components/common/modal.spec.cjsx
- [x] ./test/components/course.spec.cjsx
- [x] ./test/components/overview/cohort_button.spec.cjsx
- [x] ./test/components/overview/course_cloned_modal.spec.cjsx
- [x] ./test/components/overview/milestones.spec.cjsx
- [x] ./test/components/overview/tag_button.spec.cjsx
- [x] ./test/components/training/slide_link.spec.cjsx
- [x] ./test/components/training/slide_menu.spec.cjsx
### Stores
- [x] ./app/assets/javascripts/stores/article_store.coffee
- [x] ./app/assets/javascripts/stores/assignment_store.coffee
- [x] ./app/assets/javascripts/stores/block_store.coffee
- [x] ./app/assets/javascripts/stores/cohort_store.coffee
- [x] ./app/assets/javascripts/stores/course_store.coffee
- [x] ./app/assets/javascripts/stores/did_you_know_store.coffee
- [x] ./app/assets/javascripts/stores/gradeable_store.coffee
- [x] ./app/assets/javascripts/stores/lookup_store.coffee
- [x] ./app/assets/javascripts/stores/notification_store.coffee
- [x] ./app/assets/javascripts/stores/recent_edits_store.coffee
- [x] ./app/assets/javascripts/stores/recent_uploads_store.coffee
- [x] ./app/assets/javascripts/stores/revision_store.coffee
- [x] ./app/assets/javascripts/stores/stock_store.coffee
- [x] ./app/assets/javascripts/stores/suspected_plagiarism_store.coffee
- [x] ./app/assets/javascripts/stores/tag_store.coffee
- [x] ./app/assets/javascripts/stores/ui_store.coffee
- [x] ./app/assets/javascripts/stores/upload_store.coffee
- [x] ./app/assets/javascripts/stores/user_assignment_store.coffee
- [x] ./app/assets/javascripts/stores/user_courses_store.coffee
- [x] ./app/assets/javascripts/stores/user_store.coffee
- [x] ./app/assets/javascripts/stores/validation_store.coffee
- [x] ./app/assets/javascripts/stores/week_store.coffee
- [x] ./app/assets/javascripts/stores/wizard_store.coffee
- [x] ./app/assets/javascripts/training/stores/training_store.coffee

---

Our istanbul code coverage reports appear to be based on Babel output rather than mapped to the original source code. This makes it hard to see what is really covered or not covered.

Is there any way to get coverage that is mapped to the original .js and .jsx files?

![istanbul coverage](https://cloud.githubusercontent.com/assets/848483/14539261/89f46ddc-0234-11e6-8125-e18663d16619.png)

**Comment by ragesoss** [comment]
Maybe babel-istanbul could help? https://github.com/jmcriffey/babel-istanbul

**Comment by bmathews** [comment]
I looked into it last week, and from what I remember it won't be possible
until we get rid of the cjsx/coffee completely. Or run separate test tools
for the jsx/js vs the cjsx/coffee.

On Thu, Apr 14, 2016 at 11:46 AM, Sage Ross <notifications@github.com>
wrote:

> Maybe babel-istanbul could help?
> https://github.com/jmcriffey/babel-istanbul
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/780#issuecomment-210095012>
>



-- 
*W* *I* *N* *T* *R*  |  Brian Mathews  |  Interactive Developer  |  o.
206.783.4570  |  wintr.us

**Comment by ragesoss** [comment]
Cool. So, that'll be a great milestone to shoot for!

**Comment by thenickcox** [comment]
Because the code coverage doesn't affect the stores, we can still punt on that.

[ ] ./app/assets/javascripts/surveys/modules/Survey.coffee
[ ] ./app/assets/javascripts/surveys/modules/SurveyAdmin.coffee
[ ] ./app/assets/javascripts/surveys/modules/SurveyAssignmentAdmin.coffee
[ ] ./app/assets/javascripts/surveys/modules/SurveyUtils.coffee
[ ] ./app/assets/javascripts/surveys/survey-admin.coffee
[ ] ./app/assets/javascripts/training/stores/training_store.coffee
[ ] ./app/assets/javascripts/utils/api.coffee
[ ] ./app/assets/javascripts/utils/course.coffee
[ ] ./app/assets/javascripts/utils/course_date_utils.coffee
[ ] ./app/assets/javascripts/utils/date_calculator.coffee

**Comment by ragesoss** [comment]
Cool beans. Coffeescript is better supported for tooling than cjsx.

**Comment by thenickcox** [comment]
Actually, the stores apparently _do_ affect the code coverage.

![screen shot 2016-05-12 at 11 03 26 am](https://cloud.githubusercontent.com/assets/702327/15225016/3333b148-1831-11e6-8a68-b8bd7f99e69c.png)

**Comment by ragesoss** [comment]
Ah, yeah. I thought you just meant that they were working properly with coffeescript source maps. But I see that's not the case.

(Obviously we do want to see coverage results for the stores.)

**Comment by ragesoss** [comment]
Here are some of the ones I've gotten a bit stuck on:

- [ ] ./app/assets/javascripts/components/onboarding/index.cjsx
- [ ] ./app/assets/javascripts/components/high_order/reorderable.cjsx

**Comment by ragesoss** [comment]
Done!

**Comment by mattfordham** [comment]
Woah!!! 🍾🍻👏

**Comment by bmathews** [comment]
🙌👏🎉🎉
