### ISSUE TITLE
Survey content below the visible window is cut off and inaccessible

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#785]
There's still a problem with content below the fold. It's a little different after c91586886b2cd660f92e7aca80bc05da01d84677 but it still doesn't let a user scroll down to see the rest of of a long question. Resizing the window will let you see more, but you cannot see down much further than the height of the window.

![scroll broken](https://cloud.githubusercontent.com/assets/848483/14614850/d3de04aa-0557-11e6-8678-01a0421d2357.png)

**Comment by ragesoss** [comment]
cc @hudakdidit

**Comment by hudakdidit** [comment]
@ragesoss should be fixed now.
