### ISSUE TITLE
After taking survey, the notification on the course does not go away

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#788]

**Comment by ragesoss** [comment]
@hudakdidit I think the issue is that in Survey.js, `this.surveyNotificationId` is undefined, so `updateSurveyNotification` does not send the update.

**Comment by hudakdidit** [comment]
@ragesoss thanks. Yeah eslint told me to change that variable name since it wasn't camel cased. Will fix

**Comment by ragesoss** [comment]
Fixed, presumably, with 83df563a5ae51aa272584dc10bb2274f9bdb94bf
