### ISSUE TITLE
production reports only 68 courses (out of 118 expected)

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#79]
As of today, production is reporting only about half the expected courses and half the expected students.

**Comment by ragesoss** [comment]
This resolved itself after the next update started. I think it was caused by this:

[2015-05-02 22:17:40.977 WARN ] Caught Network is unreachable - connect(2) for "en.wikipedia.org" port 80 with options {"action"=>"liststudents", "courseids"=>"481|484|491|493|494|499|500|503|504|506|507|508|509|510|511|512|514|515|516|517|518|519|521|524|525|530|533|534|535|537|538|539|540|541|542|543|545|547|548|550|551|552|553|554|555|557|558|559|560|561", "group"=>"", "format"=>"xml", :maxlag=>10, "maxlag"=>5}

When the attempt to get the cohorts failed because of network errors, the dashboard removed all the courses it failed to get. Network errors like this should not cause removal of courses from cohorts.

**Comment by ntdb** [comment]
I have two potential solutions.

1) Whenever `api_get` returns `nil` for the `liststudents` endpoint (only happens on errors), build the result array manually from the database and let the course update process continue as normal. The `update_all_courses` task would only update courses for which `liststudents` did not fail.

2) Whenever `api_get` returns `nil` for the `liststudents` endpoint (only happens on errors), cancel the entire `update_all_courses` task. The `update_all_courses` task would update no courses for that day.

**Comment by ragesoss** [comment]
Either would be fine. This is rare, and mostly a non issue in the future.
On May 4, 2015 11:38 AM, "Nate Bailey" <notifications@github.com> wrote:

I have two potential solutions.

1) Whenever api_get returns nil for the liststudents endpoint (only happens
on errors), build the result array manually from the database and let the
course update process continue as normal. The update_all_courses task would
only update courses for which liststudents did not fail.

2) Whenever api_get returns nil for the liststudents endpoint (only happens
on errors), cancel the entire update_all_courses task. The
update_all_courses task would update no courses for that day.

—
Reply to this email directly or view it on GitHub
<https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/79#issuecomment-98808696>
.
