### ISSUE TITLE
Add reminder option to survey email notifications

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#790]
In addition to an initial survey email, we'd like to be able to send reminder emails (eg, two weeks after the first email) to users who still have not completed a survey.

**Comment by ragesoss** [comment]
Also, change `email_sent` into a datetime. Existing `SurveyNotification` records can use `created_at` to approximate the datetime, if `email_sent` is current `true`.

**Comment by thenickcox** [comment]
@ragesoss Just to confirm, it looks like the sending of emails is currently available by clicking a button, and there's a rake task written, but it's not used anywhere in the app. Is that your understanding? So this needs to be put on the schedule and, in conjunction with https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/791, only run M-R?

**Comment by ragesoss** [comment]
This will also require some interface. Here are the deets:

* Add a checkbox for a survey assignment to enable/disable sending emails. If disabled, no emails should be sent for that survey assignment.
* Add a checkbox for a survey assignment to enable/disable followup emails. If disabled, no followup emails will be sent for that survey assignment.
* On the M-R schedule (once per day, at, say 10:15 am Pacific time), run the create notifications task and the send emails task, but these should respect the per-assignment email options above.

**Comment by ragesoss** [comment]
I think X days after the first email would make the most sense. Your `for_reminder` scope vision sounds good to me.

**Comment by ragesoss** [comment]
The main thing I mean by configurable per-survey, though, is being able to configure whether they get sent at all. If it's somehow easier to configure the number of days globally rather than per-survey, that's not a big deal, although it seems like it would be pretty straight-forward to do it per-survey following the same pattern we have already for the initial notification scopes.

**Comment by thenickcox** [comment]
@ragesoss Do we need checkboxes? I mean, if those fields get set to nil, that's easy to check for in a scope or something. Seems like the user could just leave it blank if they didn't want a notification or followup, right?

**Comment by ragesoss** [comment]
As long as it's clear to the admin who is creating/editing/viewing the SurveyAssignment that it is set to send, or not send, initial emails and/or followup emails, it'll do fine.

**Comment by thenickcox** [comment]
![screen shot 2016-05-03 at 11 48 07 am](https://cloud.githubusercontent.com/assets/702327/14994459/edff6260-1124-11e6-8bac-82ca66647095.png)

This is my "simplicity FTW" approach. Feedback welcome.

**Comment by ragesoss** [comment]
Cool beans, works for me. :-)

**Comment by thenickcox** [comment]
Another question. Right now, notifications are sent manually. Which of the following should happen?

A) Follow-ups should also be able to be sent manually with a button click
B) Follow-ups and notifications should be able to be sent with a button click or on a scheduled job
B) Both notifications and follow-ups should just go on a schedule, with no manual intervention

**Comment by ragesoss** [comment]
I'll add a third B)...

B) Notifications can still be created manually and initial emails can still be sent manually (in addition to being automatic), but follow-up emails are only automatic.

Oh! I realized something important. We need at least some additional options beyond the "simplicity FTW" version above. The idea is that you would be able to create Notifications independently of sending the emails. So if you create the notifications without sending emails, users would still get the notification banner if they visit their course, and they would still be allowed to take the survey. They just wouldn't ever get emailed about it.

**Comment by thenickcox** [comment]
How do you mean "create notifications without sending emails"?

On Tue, May 3, 2016 at 2:46 PM, Sage Ross <notifications@github.com> wrote:

> I'll add a third B)...
>
> B) Notifications can still be created manually and initial emails can
> still be sent manually (in addition to being automatic), but follow-up
> emails are only automatic.
>
> Oh! I realized something important. We need at least some additional
> options beyond the "simplicity FTW" version above. The idea is that you
> would be able to create Notifications independently of sending the emails.
> So if you create the notifications without sending emails, users would
> still get the notification banner if they visit their course, and they
> would still be allowed to take the survey. They just wouldn't ever get
> emailed about it.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/790#issuecomment-216674503>
>



-- 
*W* *I* *N* *T* *R*  |  Nick Cox |  Lead Engineer |  o. 206.783.4570  |
wintr.us

**Comment by ragesoss** [comment]
There are two buttons there now. One says 'Create Notifications', and this creates SurveyNotification records (ie, notifications). There's another that say 'Send Emails', and this sends emails for all the SurveyNotifications where `email_sent` is false.

**Comment by thenickcox** [comment]
Haha, just got your third B joke. So just to clarify, it's basically exactly what we have now, but just with automatic email reminders at the configured time with nothing manual about them.

**Comment by thenickcox** [comment]
Also, what's the copy for the reminder email?

**Comment by ragesoss** [comment]
@thenickcox yes, that notifications-without-emails thing described above.

Copy for the reminder email... I'll likely update it before we actually start using it, but for now, here's some:

```
Hello, %{username}.

This is a reminder about the survey for your course, %{course_title}. Feedback from this survey helps us to improve our support for Wikipedia assignments like yours.

[link]

Sincerely,
the Wiki Ed Team
```
