### ISSUE TITLE
Survey Assignments are sending too many notifications

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#793]
It'd be helpful to see how many notifications *would be* created for a given assignment.

**Comment by ragesoss** [comment]
Maybe it does this already? I guess I was just expecting fewer courses to be ready for surveys already from spring 2016.

**Comment by hudakdidit** [comment]
@ragesoss yeah somethings up. Looks like only 30 should be notify-able in the SurveyAssignment you created. Looking into it

**Comment by ragesoss** [comment]
@hudakdidit possibly it's the scopes on course. I couldn't figure out how they were doing what they were supposed to do (using the course dates); maybe they don't.

**Comment by hudakdidit** [comment]
Yeah I think at some point when refactoring to create notifications only for unique `survey_id + courses_user+id` combinations, I lost the `Course.ready_for_survey` scope, its no longer being called.
