### ISSUE TITLE
Filtering question groups by tags is not working

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#812]
@hudakdidit 

At least when doing previews, but I think for real surveys as well, question groups that have tags are still being shown to all classes whether or not they have tags.

**Comment by hudakdidit** [comment]
These should be working as expected now. with this commit. I've confirmed locally https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/083ec718c1c457cc5e6bcbd2cd53a49bbdd1539d
