### ISSUE TITLE
Javascript error with slick

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#815]
https://sentry.wikiedu.org/wikiedu/production/issues/519/

@hudakdidit

**Comment by hudakdidit** [comment]
@ragesoss I'm pretty sure this is related to https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/816

**Comment by ragesoss** [comment]
@hudakdidit I don't think so. The report on Sentry is for this course: https://dashboard.wikiedu.org/courses/Canisius_College/EDU122_%28Spring_2016%29

That course has a returning instructor, while the blank question group bug affected courses tagged first_time_instructor only.

**Comment by hudakdidit** [comment]
@ragesoss ok I'm seeing this on staging. You're right about it not being related to the missing question group. The js error doesn't seem to disrupt the user's experience or prevent navigation though.

**Comment by ragesoss** [comment]
Looks like maybe this is the Firefox equivalent: https://sentry.wikiedu.org/wikiedu/production/issues/545/

I'm seeing entry from myself as well, in preview mode when I didn't notice any problems.
