### ISSUE TITLE
Empty question group prevents user from completing survey

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#816]
At least one user sent us a bug report saying they got stuck after a couple questions in a state with a blank page and now next button.

This is a bug I've hit a couple times, although I've not been able to replicate it consistently.

But I think it may have to do with keyboard navigation. Can we disable keyboard navigation for this survey altogether?

@hudakdidit

**Comment by ragesoss** [comment]
Actually, this bug seems to be specific to the survey and course, possibly because of unhandled empty data or somesuch.

https://dashboard-testing.wikiedu.org/surveys/1?utf8=%E2%9C%93&preview=true&course_slug=Ohio_University%2FQueer_Theory_WGSS_4610_5610_%28Spring_2016%29&commit=Start+Survey

**Comment by ragesoss** [comment]
The issue was that we had an empty question group. (We removed the only question from one question group for first time instructors, but never removed the question group itself.)

**Comment by hudakdidit** [comment]
@ragesoss ok. I can definitely disable the keyboard navigation and tabbing.

**Comment by ragesoss** [comment]
@hudakdidit I think disabling keyboard navigation is a good idea anyway, although per my last comment, that's unrelated to this particular case, it turned out.

**Comment by hudakdidit** [comment]
Empty QuestionGroups added to surveys will no longer break the user's experience. A QuestionGroup will not be rendered if it doesn't have any questions. 

Survey with an empty question group demo:
https://dashboard-testing.wikiedu.org/surveys/3?preview
