### ISSUE TITLE
New Answers and AnswerGroups created even in preview mode

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#819]
Preview mode should not save any responses to the database.

**Comment by hudakdidit** [comment]
What survey are you seeing this on?

**Comment by ragesoss** [comment]
Everywhere. I just replicated it on staging. I go through a survey in preview mode, and after I submit there are 6 new records in `Rapidfire::AnswerGroup`.

On production, there are recorded responses from 7 unique users, all Wiki Ed staff, and they are the ones who took it in preview mode.

Actually, I haven't confirmed that records get saved `outside` of preview mode. There are still no responses from the live survey.

**Comment by ragesoss** [comment]
Okay, confirmed that it seems to work fine via email.

**Comment by hudakdidit** [comment]
With this simple survey no new AnswerGroups or Answers are created upon submitting in preview mode 

https://dashboard-testing.wikiedu.org/surveys/2?preview

Are we sure these surveys are being taken with the preview url param?

**Comment by ragesoss** [comment]
Only happens if course chooser is enabled. I added a second question group, and still no new records, but then when I enabled course picker and did it again, two new ones.

**Comment by hudakdidit** [comment]
Ah! Ok, hmm the url param isn't being passed then. Ok thanks that helps track down the cause.

**Comment by hudakdidit** [comment]
@ragesoss found the cause. This commit should fix. I've confirmed locally.
