### ISSUE TITLE
Cannot specify default cohort

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#82]
I added a new cohort today on both production and staging. On staging, the new cohort is not the default cohort (which is what I want, in this case), while on production, the new cohort has become the default one.

**Comment by ntdb** [comment]
My latest implementation of cohort defaults was really bad: it modified the rails routes with a default cohort parameter. This means that if you add a new cohort it isn't reflected on the site until Rails restarts. Pushing a fix where the default cohort is resolved in the courses controller.
