### ISSUE TITLE
Windows 10 / Edge browser — cannot select any course articles

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#822]
@hudakdidit 

I tried testing it with this: https://dashboard-testing.wikiedu.org/surveys/1?utf8=%E2%9C%93&preview=true&course_slug=Bucknell_University%2FToo_Much_Information_%28Fall_2014%29&commit=Start+Survey

On Windows and Edge browser, I could not complete the survey because I couldn't get past the checkbox question with course articles. Clicking any article (as well as None of the above) does nothing.

Chrome and Firefox worked fine on the same computer.
![screenshot 2016-04-26 12 21 24](https://cloud.githubusercontent.com/assets/848483/14831440/a5fc09d4-0baa-11e6-97a8-011d86d66cd3.png)

**Comment by hudakdidit** [comment]
@ragesoss this should be resolved with the commit referenced above. The whole row is not clickable (like it is in all other browsers) but the checkbox/radio button itself it check-able.
