### ISSUE TITLE
Pressing tab can make crazy things happen on the survey

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#823]
I was able to accidentally get into this state, on Windows 10 / Edge browser, in part by pressing the tab key. It have been that in combination with something related to focus, because I couldn't recreate it. (Tab does otherwise cycle through the links in the top nav in a way that is a little broken, but it's not unusable when that happens.)
![screenshot 2016-04-26 12 20 40](https://cloud.githubusercontent.com/assets/848483/14831532/09e1aaa8-0bab-11e6-9cf6-593e4c1eea05.png)

**Comment by hudakdidit** [comment]
@ragesoss the commits referenced above should address the majority of the craziness. Surveys on staging should now be tab-navigable.

Looks like the matrix radio and matrix rangeinput questions are still not accessible from keyboard-only users. I'll look into a solution for those.

cc: @mattfordham

**Comment by hudakdidit** [comment]
I'm going to close this now that the stated issue _should_ be resolved. I'll open a ticket for matrix radio and rangeinput issues mentioned above.
