### ISSUE TITLE
Survey Notification not updated when non-admin takes survey

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#824]
@hudakdidit 

It looks like survey submission now works, but there's a 401 on the survey_assignment endpoint when a non-admin submits.

**Comment by ragesoss** [comment]
@hudakdidit This is okay, right? 1aa27555a4f2ca5bab3a86bdf3b807a34369458f

**Comment by hudakdidit** [comment]
@ragesoss yep. I just confirmed that commit fixed it on staging.
