### ISSUE TITLE
Active course for survey should be visible throughout survey

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#825]
Although we note the course on the first slide, it is easy to overlook that. The survey should display the course title, institution and term throughout the survey experience, so that users do not mistakenly fill it out for the wrong class.

**Comment by hudakdidit** [comment]
@ragesoss how about we put it here?

![wiki_ed_dashboard](https://cloud.githubusercontent.com/assets/1223821/14864496/f48f0dca-0c6e-11e6-8fb7-8782c37cf6fc.png)

**Comment by ragesoss** [comment]
@hudakdidit Yep, totes.
