### ISSUE TITLE
Results view should not show Text non-questions

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#826]

**Comment by hudakdidit** [comment]
@ragesoss could you clarify this one? It should not show blank answers?

**Comment by hudakdidit** [comment]
@ragesoss nevermind. Understood

**Comment by ragesoss** [comment]
This is the results view for a "Text" type question, which is not really a question — it's just informational text with no opportunity for input. Instead of showing nothing at all, it shows empty responses from every user who completed the survey.

![text question](https://cloud.githubusercontent.com/assets/848483/14866472/cfee9274-0c78-11e6-8fb1-04b036836296.png)
