### ISSUE TITLE
Followup questions not included in results view or individual question CSVs

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#827]
No data gets saved from followup question fields.

@hudakdidit

**Comment by ragesoss** [comment]
Actually, I think it's being saved, but it doesn't show up in the CSVs or the results view.

**Comment by hudakdidit** [comment]
@ragesoss I just exported the instructor survey csv from production and it includes the follow up answers. It just seems many are not being filled out?

Also it looks like from the console there are 5 answers with `follow_up_answer_text` which aren't empty or null.

The results index view does not include the follow up question answers yet. I'll implement that today. Still high-importance?

**Comment by ragesoss** [comment]
@hudakdidit I had been looking in the CSV for the individual question. It's high-importance in that we definitely need that, but if it's part of the implementation of such info within views, then carry on.

**Comment by hudakdidit** [comment]
@ragesoss got it. I'll include in the individual question csv. no prob.
