### ISSUE TITLE
Clicking 'show title' and updating the survey does not save the update

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#830]
It looks like the 'Show Title' checkbox got disconnected from the SurveysQuestionGroupsController at some point.

We're not actually using this, anyway. Maybe we should get rid of 'show_title', along with that controller, altogether. What do you think, @hudakdidit?

**Comment by hudakdidit** [comment]
Yep sounds good. I'll remove today
