### ISSUE TITLE
There's no way to delete a Survey Assignment

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#831]
/me shakes fist

@rileywho!!!!!

**Comment by rileywho** [comment]
Should be at the bottom of an edit/create assignment page
![image](https://cloud.githubusercontent.com/assets/2120466/14905318/5fb7ac38-0d64-11e6-96f1-c36940d2917f.png)

**Comment by rileywho** [comment]
@hudakdidit

**Comment by bmathews** [comment]
riley who, hudak did it

**Comment by rileywho** [comment]
@ragesoss I did remove it from the index page. The plan was to move it to the edit view as per the comps.
