### ISSUE TITLE
Convert inline CSS in mailers to use premailer gem

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#833]
The inline CSS in mailers will get out of control quickly, especially if there's even a single design change. The [`premailer-rails`](https://github.com/fphilipe/premailer-rails) gem will allow us to write the styles in sass and will inline them for us. That'll be much more maintainable going forward.

**Comment by ragesoss** [comment]
@thenickcox can you estimate this?

**Comment by thenickcox** [comment]
2-3 hours, maybe.
