### ISSUE TITLE
If the final question of survey is conditional, survey is not submitted.

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#836]
Some situations, such as there being no answers available — like selecting articles from the course articles list, if it is empty — mean that the question gets automatically skipped.

If it's the last question, this means that the previous question has a button that says "Next" but it really acts as "Submit Survey".

If it's the only question, then it simply displays nothing and the user cannot submit.

**Comment by ragesoss** [comment]
It actually doesn't act as 'submit survey', in that it does not submit the answers. So you have to make sure the final question is not a conditional one.

**Comment by mattfordham** [comment]
The above commit fixes the issue when users see the conditional question. Working now on submitting if they don't end up down the conditional branch.

**Comment by mattfordham** [comment]
Okay. Here is a hopeful fix: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/1d9fc034651a49260f268c1605e886eb94eea8aa

It is not the "smartest" solution, but it is simple. It uses the calculation of percentage complete that is already being used for the progress bar. If a user gets to 100% progress and the forms have not been submitted, then submit them. The only reason I can think of for them NOT being submitted by then, is the case in question with this issue.

**Comment by ragesoss** [comment]
So this relies on the progress reaching 100% *after* the 'submit' step. Makes sense to me.

**Comment by ragesoss** [comment]
It's failing CI because the eslint gods are displeased.

**Comment by mattfordham** [comment]
Ah, damn them. I'll make the appropriate sacrifice and push again ;)

**Comment by ragesoss** [comment]
Thanks. I would have done it myself, but one's relationship to one's gods is such a personal thing.
