### ISSUE TITLE
Syllabus File Upload Modal

### ISSUE THREAD

**Issue by kristi-wintr** [WikiEducationFoundation/WikiEduDashboard#838]
Turn component into modal that can be accessed by putting a syllabus parameter in course URL, and can invite someone to do that from Survey email. 

https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/fbce0e3ffdd2e4e08a15b66cc02394e70ef6c827#diff-ccae56500d093d28fae552ede2e2d23bR99

**Comment by ragesoss** [comment]
@thenickcox Thanks! This is good for now.
