### ISSUE TITLE
Some revisions do not show up on the dashboard as expected.

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#85]
Reports from my team that we should investigate:

-------

[This student](https://en.wikipedia.org/wiki/Special:Contributions/Mtbabcock)'s edits to an article created in mainspace, [OlegSlabynko](https://en.wikipedia.org/wiki/Oleg_Slabynko), don't show up on [this course](http://dashboard.wikiedu.org/courses/University_of_Southern_Indiana/Intro_to_Mass_Comm_(Spring_2015)). 

-------

[BIOL 345 Human Ecology](http://dashboard.wikiedu.org/courses/University_of_British_Columbia/BIOL_345_Human_Ecology_(Winter_2015))

Attt7 - 0 mainspace characters on Dashboard; [several thousand actually added](https://en.wikipedia.org/w/index.php?limit=500&tagfilter=&title=Special%3AContributions&contribs=user&target=Attt7&namespace=0&tagfilter=&year=2015&month=-1). Draft article moved to mainspace on the last day the course was active. 

[Bosancich123](https://en.wikipedia.org/wiki/Special:Contributions/Bosancich123) - 0 mainspace edits on Dashboard; draft article was moved to mainspace after the end of the course, but it stood above 8k bytes before that date. *This one is issue #86*

OK, this is pretty consistent across this course - their draft articles were moved to mainspace after the end of the course, and were not registered by the Dashboard.

------

[Biological Clocks - Genes](http://dashboard.wikiedu.org/courses/Washington_University_in_St._Louis/Biological_Clocks_-_Genes_(Spring_2015))

This one's harder to figure out. While several articles showed up, these didn't (course is still active)

* [Linnecou](https://en.wikipedia.org/w/index.php?limit=500&tagfilter=&title=Special%3AContributions&contribs=user&target=Linnecou&namespace=0&tagfilter=&year=2015&month=-1) - zero on dashboard 
* [Primadohnut](https://en.wikipedia.org/w/index.php?limit=500&tagfilter=&title=Special%3AContributions&contribs=user&target=Primahdonut&namespace=0&tagfilter=&year=2015&month=-1) - 355 on dashboard
* [SnydeEcology](https://en.wikipedia.org/w/index.php?limit=500&tagfilter=&title=Special%3AContributions&contribs=user&target=SnydeEcology&namespace=0&tagfilter=&year=2015&month=-1) - 26 on dashboard
* [Traesongz](https://en.wikipedia.org/w/index.php?limit=500&tagfilter=&title=Special%3AContributions&contribs=user&target=Traesongz&namespace=0&tagfilter=&year=2015&month=-1) - zero on dashboard

**Comment by ntdb** [comment]
I'll spend more time investigating this but it might just be time to do a new database initialization. There's a good chance that some of these were simply lost along the way as we updated import methods.

**Comment by ragesoss** [comment]
I broke out the first report to #86, which we understand the reason for. (Fix won't be trivial, but should be possible.)

**Comment by ragesoss** [comment]
I still need to go through the rest of the reports to see what did and didn't get resolved, but between regenerating the database and the fixes related to #86, what remains is not a critical problem. The total that now shows for bytes added is consistent with what Wikimetrics reports.

**Comment by ragesoss** [comment]
Okay, it looks like all of these examples have been resolved by the database regeneration, and hopefully our improvements to the article import and article status update pipelines will prevent similar issues going forward.
