### ISSUE TITLE
dashboard.wikiedu.org interactions with wikimedia API is extremely slow

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#853]
As of this morning, it takes longer than 30 seconds to do queries against the MediaWiki. This means that login and editing actions on the dashboard time out.

I'm able to get data back *eventually* when making queries to Commons or Wikipedia on the rails console, but it takes a very long time. Staging and other instances are not affected, just dashboard.wikiedu.org.

**Comment by mattfordham** [comment]
I was able to login just now and experienced no delays or issues. Is the issue still happening for you @ragesoss ?

**Comment by ragesoss** [comment]
Nope! Appears to have resolved itself. I'll keep an eye on it, but carry on with whatever else was supposed to be going on today!

**Comment by mattfordham** [comment]
Haha. How odd! We're standing by if it pops up again 👻

**Comment by thenickcox** [comment]
@ragesoss Did you try turning MediaWiki on and off again?
