### ISSUE TITLE
Onboarding is missing secondary text

### ISSUE THREAD

**Issue by rileywho** [WikiEducationFoundation/WikiEduDashboard#855]
<img width="427" alt="wiki_education_foundation_dashboard" src="https://cloud.githubusercontent.com/assets/2120466/15188290/b52fcb06-1759-11e6-8e42-ed83a9aa14e0.png">

**Comment by rileywho** [comment]
Looks like the font color got changed to white (#ffffff)

**Comment by ragesoss** [comment]
@rileywho what color is it supposed to be? Black?

**Comment by ragesoss** [comment]
(I think I changed it to white when I was hacking my way through making the terms of use footer appear.)

**Comment by rileywho** [comment]
@ragesoss The color should be #666666
