### ISSUE TITLE
Feature specs won't run in hot-dev mode

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#868]
The lack of `rev-manifest.json` means that feature specs all break until a non-hot-dev gulp gets run. 

cc @bmathews, if you get a chance.

**Comment by bmathews** [comment]
The situation you're describing is when application.yml has `hot_loading` enabled, `gulp hot-dev` _isn't_ running, and then you try to run the feature specs, right?

**Comment by ragesoss** [comment]
@bmathews just so.

**Comment by ragesoss** [comment]
@bmathews 

err... no, it happens even if `gulp hot-dev` is running.

**Comment by bmathews** [comment]
Hm, okay! I'll check it out!

**Comment by ragesoss** [comment]
@bmathews have you have a chance to poke at this yet?

**Comment by bmathews** [comment]
Not yet! 👎 I'll check it out today/tomorrow.

**Comment by bmathews** [comment]
It looks like you set `config/environments/test.rb` in c1f26c89 to always set `hot_loading` to false. That intended?

**Comment by ragesoss** [comment]
Aha! I'm sure it was intended at the time, because my commit message seems pretty confident. I vaguely remember that I was addressing problems where other developers who were not using hot-loading would run into trouble, but I'm not sure what those were. I'll remove that. Thanks @bmathews!
