### ISSUE TITLE
Message [[Wikimedia:Wikiedudashboard-courses.creator.course language/en]] needs documentation.

### ISSUE THREAD

**Issue by Purodha** [WikiEducationFoundation/WikiEduDashboard#873]
Please provide message documentation.
URL: https://translatewiki.net/wiki/Wikimedia:Wikiedudashboard-courses.creator.course language/qqq

**Comment by ragesoss** [comment]
I added documentation in this commit: 73d56b34ccf4154eb13385db38fc509d4739ef54

It should make its way to translatewiki.net soon. For that particular message, the documentation is "The Wikimedia project language code for the course or program's home wiki"
