### ISSUE TITLE
Having both the old and new ids for an article with merged or edited revision history breaks ArticleImporter.update_article_status

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#89]
In the last two days, this has appeared twice, caused by Article.update:

ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '46349871' for key 'PRIMARY': UPDATE `articles` SET `id` = 46349871, `updated_at` = '2015-05-13 07:45:38', `views` = 0 WHERE `articles`.`id` = 2262715

**Comment by ragesoss** [comment]
This has broken the last two daily updates on staging (but not constant updates), and may be the reason that it's showing much lower numbers than expected since the deploys that broke, then fixed, course listings ( c81d9bae7a2e593e511398b5c6755d31603f25b4 )

**Comment by ragesoss** [comment]
This is probably from the new ArticleImporter.update_article_status flow.

**Comment by ragesoss** [comment]
I think I've pinned it down some. In this case, we have two article ids (2262715 and 46349871) for the same page, Kostanay, because there was a history merge that changed the id, but the new id got added before ArticleImporter.update_article_status ran. So now when ArticleImporter.update_article_status tries to update the id of the record that matches the title and namespace, it finds two entries.

**Comment by ragesoss** [comment]
After deploying the fix to production and resuming updates, this key collision error popped up again the first time update_article_status got run. I replicated this locally.

**Comment by ragesoss** [comment]
Here's the case I get causing problems locally. 
Article.where(title: 'Cyber-Ethnography', namespace: 1) >
```
#<ActiveRecord::Relation [#<Article id: 3914927, title: "Cyber-ethnography", views: 0, updated_at: "2015-05-14 17:59:38", created_at: "2015-05-14 17:59:38", character_sum: 0, revision_count: 0, views_updated_at: nil, namespace: 1, rating: nil, rating_updated_at: nil, deleted: true>, #<Article id: 46394760, title: "Cyber-Ethnography", views: 0, updated_at: "2015-05-14 17:59:38", created_at: "2015-05-14 17:59:38", character_sum: 0, revision_count: 0, views_updated_at: nil, namespace: 1, rating: nil, rating_updated_at: nil, deleted: false>]>
```

Notice the difference in capitalization. Maybe active record is flexible with capitalization, while the string comparisons we do for title are not?

**Comment by ragesoss** [comment]
It looks like the problem was that we're using case-insensitive collation in our database. @ntdb do you think we should change the collation for the places where we store strings, like username and article title?

**Comment by ntdb** [comment]
@ragesoss Wherever we're dealing with a string that is case sensitive on Wiki then we should also maintain case sensitivity on our end. Is that currently limited to usernames and article titles?

**Comment by ragesoss** [comment]
@ntdb Yes, I think that's right, just usernames and page titles (including assignments that aren't attached to article_ids).

**Comment by ragesoss** [comment]
This has appeared again on staging, this time with this article (which was just moved to a new title, causing the error I think) https://en.wikipedia.org/w/index.php?title=Y%C5%8Dji_Sakate_(playwright)&action=history

The new id is 46745170. The old id is 46364485.

This page has been moved twice, once from sandbox, and then a second time to a new title in mainspace. I can't find anything else relevant in the article's history or logs.

**Comment by ragesoss** [comment]
In this new case, the situation is that the database has an underscore in the title for 46364485, but a space in the title for 46745170. So, update_article_status doesn't detect them as the same article.

We should always be storing page titles with underscores, since that's the format they take inside MediaWiki.

**Comment by ragesoss** [comment]
In both staging and production, there are small numbers of articles with spaces instead of underscores in the titles, while the great majority have only underscores. I can't find a pattern for why some are like this. A fair number of them are deleted articles, but not all.

@ntdb Ideas on how the spacey titles are getting into the database, and how we should fix it?

**Comment by ragesoss** [comment]
This is back on staging.

Here's the article's log showing the series of actions that our updater didn't handle: https://en.wikipedia.org/w/index.php?title=Special:Log&page=Brian+Boland+%28footballer%29

**Comment by ragesoss** [comment]
Here are the relevant article rows:

'46801260', 'Brian_Boland_(footballer)', '0', '2015-05-29 08:01:57', '2015-05-26 13:37:34', '10', '1', NULL, '0', 'stub', '2015-05-29 08:01:57', '0'

'46813254', 'Brian_Boland_(footballer)', '0', '2015-05-29 08:24:11', '2015-05-28 19:38:52', '0', '0', NULL, '0', 'stub', '2015-05-29 08:24:11', '0'
