### ISSUE TITLE
DatePicker fields may submit invalid dates

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#892]
The new DatePicker fields need to be validated. It is possible to save with an invalid date, which results in a course with start or end of `nil`.

In the case of the Meetings component, the component tries to send an update to the server with every change — which means every keystroke. This results is glitchy behavior if you type more quickly that the server actions resolve. Related: https://sentry.wikiedu.org/wikiedu/staging/issues/742/

Ideally, the Meetings component should only update the server upon clicking 'Done', but if that causes too much trouble, it could just ensure a valid date before updating the server.

**Comment by mattfordham** [comment]
On it!

**Comment by mattfordham** [comment]
This should do it. Check it out https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/5bcb8ec4cb59fca52789beff224f0dcd50477e1a

**Comment by mattfordham** [comment]
Meetings component updates upon clicking "done" now. Added validation to a few other spots too.

**Comment by mattfordham** [comment]
Another note... I opted to use `alert` is a few spots to notify user of form errors. The global notifications in those cases were often off-screen and not evident enough. Open to alternative ideas.

**Comment by ragesoss** [comment]
Fixed. I can't repro any more cases where a null date gets saved, although I should poke at it more to be sure.
