### ISSUE TITLE
User role inconsistency

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#9]
If a user is signed up as both instructor and student, they may show up on the Dashboard as either instructor or student. The instructor role takes precedence, so any user who is an instructor for a course should not be listed as a student for that course.

Currently, user ProfTAH shows up as a student in production, and as the instructor on staging: 
http://dashboard.wikiedu.org/courses/College_of_DuPage/ENGLI1102-057S_(Spring_2015)

http://dashboard-testing.wikiedu.org/courses/College_of_DuPage/ENGLI1102-057S_(Spring_2015)

**Comment by ragesoss** [comment]
See also: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/models/user.rb#L74

**Comment by ntdb** [comment]
@ragesoss I agree with your note. When I built the role functionality it didn't occur to me that users might have different roles in different courses. On this next.

**Comment by ntdb** [comment]
Pushed a fix for this in 7defcd7321e6ea879cf05a58185075e17e59160f. Let's make sure to test it pretty well on staging before pushing to production. I'm particularly interested in making sure that the migration and updates work as expected.

**Comment by ragesoss** [comment]
@ntdb Confirmed that the issue itself is fixed, but I batches on staging seem to be taking several times longer after this update.
