### ISSUE TITLE
Error notifications disrupt placement of sticky header

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#905]
Things don't behave as intended if a notification is present.

![sticky menu](https://cloud.githubusercontent.com/assets/848483/16507571/9b045f46-3edf-11e6-97dc-5a7aa63db4c9.png)
![floating sticky menu](https://cloud.githubusercontent.com/assets/848483/16507573/9d773c26-3edf-11e6-911f-989dda14e31c.png)

**Comment by ragesoss** [comment]
See also  #234

**Comment by bmathews** [comment]
Fixed via https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/ee6638cd140bb6e3474bc0eb84a1036a391436dd
