### ISSUE TITLE
Popup rendering for cohort button is broken

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#910]
@mattfordham likely related to the styleguide tweaks?

![button bug](https://cloud.githubusercontent.com/assets/848483/16626087/39a5b264-435c-11e6-8bc2-d574959ac115.png)

**Comment by mattfordham** [comment]
Hmm... could be. Will investigate today.

**Comment by mattfordham** [comment]
Hopefully fixed by https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/0c01e546661ab0a6765b2d6e633cf2d9debaed04

**Comment by ragesoss** [comment]
Yep.
