### ISSUE TITLE
Selecting an assigned article should involve a message indicating that it was selected successfully

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#912]
It's currently a very subtle change as the article moves from Available to Assigned, and a user may not noticed that they succeeded.

**Comment by ragesoss** [comment]
This can be done with a call to `NotificationActions.addNotification` (see EnrollButton for an example) from the same function that updates the assignment to move it to a user (in AvailableArticle).

**Comment by arreche** [comment]
I am going to start working on this issue in a fork.

@ragesoss gave some details in https://agileventures.slack.com/messages/wiki_edu_dashboard/

> To set up for it, you should:
> 
> 1. log in
> 2. create a course
> 3. go to the Articles tab of the course
> 4. Add an 'Available article'
> 5. add a different user as the instructor and remove yourself.
> 6. join the course as a student
> 7. select the article from the articles tab
> 
> Now that I think through it, setting up the situation is more complicated than the solution will probably be.
> 
> but that will let you see how the system works, from a UX perspective.

**Comment by arreche** [comment]
This is what an student see after selecting an assigned article.

![screen shot 2016-12-10 at 15 36 30](https://cloud.githubusercontent.com/assets/459813/21074347/98fee8bc-beee-11e6-9b6a-83e23d8256a6.png)

**Comment by ragesoss** [comment]
The situation that has particular potential for confusion is when there already several other Assigned Articles and also several Available Articles. In that case, basically when you click to choose an available article, it disappears from Available and appears in Assigned. But since they both have the same layout and rows have the same size, it's easy to overlook that you succeeded in selected the article.

**Comment by ragesoss** [comment]
(There's also another issue related to the same user interaction:  #913)
