### ISSUE TITLE
Personal training status is shown to user despite not being apart of the course

### ISSUE THREAD

**Issue by rileywho** [WikiEducationFoundation/WikiEduDashboard#924]
I'm not enrolled in the HIST course but my training completion status is present in the course's timeline. Not entirely sure if this is a bug because it helps students avoid repeating any training they may have done in a previous course. Though, maybe your status should only show up if you're enrolled in the course?

![screen shot 2016-07-23 at 5 31 38 pm](https://cloud.githubusercontent.com/assets/2120466/17081024/671ae564-50fb-11e6-9eb5-f05774a23692.png)

![screen shot 2016-07-23 at 5 41 54 pm](https://cloud.githubusercontent.com/assets/2120466/17081054/ce0e304a-50fc-11e6-8a6c-cc3c8bd68602.png)

**Comment by ragesoss** [comment]
The training completion status is intentionally not tied to a particular course, to account for students who take more than one. But I suppose it makes slightly more sense to only show completion status in this context if you are enrolled.

**Comment by enelesmai** [comment]
Hello @ragesoss, can I take this issue?

**Comment by ragesoss** [comment]
@enelesmai yes.

**Comment by enelesmai** [comment]
@ragesoss how can I get to this view? I already enrolled my user, but can't see the status info
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/5160907/164107079-ead08251-b8c4-42ab-8e3c-02b740f99649.png">

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/5160907/164107170-4483af71-fdbf-49ef-a0f8-b3098e2652b9.png">

**Comment by ragesoss** [comment]
You may need to load the training modules first. See `user_roles.md`.

**Comment by lavish123409** [comment]
Hello everyone,

I am not able to reproduce the bug. The steps which I followed are as follows -

- Created two courses, named "Finding Bug" and "Course Completion", and added "Wikipedia Policies" training to both the courses
- Enrolled in the "Course Completion" course as a student from a different account
- Completed some portion of "Wikipedia Policies" training in "Course Completion" course
- Viewed the page of "Finding Bug" course

### Screenshot of "Course Completion" (Enrolled) course
![image](https://user-images.githubusercontent.com/57138717/228285649-400205ab-791c-4c05-9ed9-2230a92f1c0e.png)

### Screenshot of "Finding Bug" (Not Enrolled) course
![image](https://user-images.githubusercontent.com/57138717/228285316-810967cb-1077-4b19-8950-68a9ea3e5ee7.png)

As it is visible, the status is not shown in "Finding Bug" course, only the button text is changed from "Start" to "Continue". Am I missing something to reproduce the bug?
