### ISSUE TITLE
blackout dates are no longer crossed out in calendar

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#940]
Maybe this happened when I updated ReactDayPicker. Now dates that are part of the default weekday selection but are unselected are just rendered like other unselected dates, rather than the crossed out holiday styling that they should have.

**Comment by ragesoss** [comment]
@mattfordham heads up that DatePicker is undergoing some changes in #951.

**Comment by ragesoss** [comment]
@mattfordham we're close to merging #951, so if you find the cause of this, fixing it on top of the PR branch would be ideal.

**Comment by mattfordham** [comment]
Sure thing. I've got a one line fix. Will push within the hour.

**Comment by ragesoss** [comment]
Cool. You can just post fix here, if you like.

**Comment by mattfordham** [comment]
I think this guard clause got flipped around during the jsx conversion:

https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/components/common/calendar.jsx#L113

A solution is...

`if (!this.props.course.day_exceptions || !this.props.course.weekdays) { return false; }`

**Comment by ragesoss** [comment]
Nice. That doesn't conflict, so you can push that straight to master.
