### ISSUE TITLE
CourseCloneModal sometimes hangs on 'checking for uniqueness'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#954]
It's happened a few times locally for me, and today at least two users ran into this issue on production.

**Comment by mattfordham** [comment]
@ragesoss I'm having a tough time reproducing this issue, or imagining how it might happen. Any more details to go on?

**Comment by ragesoss** [comment]
@mattfordham I don't have a recipe to reproduce it, but I've hit it a handful of times locally, and it's happened with at least two users that we know of. If you don't see any likely culprits, maybe we could add some logging.

I figured it was related to the `setTimeout` in `saveCourse` and/or the hacky way we determine `isNewCourse`.

If it's the latter, then slow networks would explain it... if the server takes more than 10 seconds, then isNewCourse will never be true and it won't redirect to the new slug. But I didn't understand what was going on with the setTimeout bit, which is why I lobbed it to you.

**Comment by mattfordham** [comment]
I'm guessing the `setTimeout` is to allow the Validation action to go through. That said, it's not clear why that's needed. 

Do you see any harm in raising 10 to 30? I can't think of any cases where the course would have been otherwise updated.

**Comment by ragesoss** [comment]
What would happen if the user took less than 30 seconds to complete the form?

**Comment by mattfordham** [comment]
Hmm. Prior to saving this form the course should have no edits since being created (right?) which would mean `created_at` and `updated_at` would be the same. Maybe we could change the check to look for a difference between `created_at` and `updated_at`. That seem like it could work?

**Comment by ragesoss** [comment]
What if, instead of @updateCourse('cloned_status', @cloneCompletedStatus), we did that update of course.cloned_status inline (but not in the store), and then checked for getting course.cloned_status == 2 back from the server? (We'd need to add cloned_status to course.json.)

That way, we'd have an unambiguous signal from the server that the course got updated.

**Comment by ragesoss** [comment]
@mattfordham that sounds like a dangerous assumption to make about how the deep_cloneable gem and the CourseCloneManager work. It's conceivable that there are multiple database writes that could happen during the setup of the clone records. (I don't think there are right now, but it seems dangerous.)

**Comment by ragesoss** [comment]
Actually, there are multiple saves... first @clone.save and then @clone.update_cache. So those timestamps could differ.

**Comment by mattfordham** [comment]
I'll give your idea a go. I'll be offline for a couple of hours, but back on later this PM.

**Comment by ragesoss** [comment]
I'm going to optimistically close this, on the assumption that the fixes we put in will work. Will reopen if users report it happening again.
