### ISSUE TITLE
Instructors should have an option to delete the entire timeline of an unsubmitted course

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#955]
Many times, instructors need to delete each week in a timeline so that they can go through the wizard again. For unsubmitted courses, we should provide an easy way to reset the timeline and launch the wizard fresh. (For submitted courses, the assumption is that they will only change incrementally; we don't want to miss total rewrites after a course has been approved.)

**Comment by hin101** [comment]
For this ticket, do we simply want to delete the unsubmitted courses, or retain them and just hide it from the view?

**Comment by ragesoss** [comment]
@hin101 The story is like this:

1. Instructor creates a course, using the assignment wizard to create a timeline.
2. The instructor has not yet clicked submit. Upon reviewing the timeline, the instructor decides they want to make some different choices. They want to scrap the entire timeline and go through the assignment wizard again.
3. Instead of needing to delete every week in that timeline (the current flow), the instructor sees a button to 'Delete timeline and start over'.
4. Clicking this button destroys all the `Week` records for that course (and the child `Block` records).
5. Now the user can restart the wizard.

**Comment by ragesoss** [comment]
@medhabansal since you've got a few other things on your plate, how about we leave this for Hinesh for now?

@hin101 I had forgotten that Medha was going to work on this one, but I don't think she's started yet. Keep us updated, though; if you're not able to tackle it, we'll pass it back to Medha or myself, since I'm hoping to get this one done within the next few weeks. And if you get stuck or have questions, give a ping!

**Comment by hin101** [comment]
@ragesoss Thanks, I will give it a go and keep you updated

**Comment by medhabansal** [comment]
@ragesoss Cool, I had just begun with my investigation and made only a few basic changes. I'll work on the issues we discussed yesterday.

**Comment by ragesoss** [comment]
done
