### ISSUE TITLE
date form for course gets confused around the end of the month

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#96]
Sometimes, I put in a date that is the first day of a month, and when I save, the date shows as the last day of the previous month. Sometimes, it gets so confused that it lists a day that doesn't exist, like the December 32.

**Comment by ntdb** [comment]
This should be resolved in fb95e8b34bef8a9d97571208aa1a747640b9332e. I added a small JS library to take the pain out of JS date handling.
