### ISSUE TITLE
StudentDrawer border has a gap when there are no training modules

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#967]
I added a tweak so that the training status table does not show up when there are not entries. There's a design wrinkle:

![gap](https://cloud.githubusercontent.com/assets/848483/18690972/fb368438-7f45-11e6-933c-76ae0743e8f4.png)

@mattfordham do you see an easy way around this? If not, I'm okay with letting it be.

**Comment by mattfordham** [comment]
@ragesoss Think I fixed it here: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/68a027e8839746c94e5c11cc75ae22c6ced47158

**Comment by ragesoss** [comment]
Yep! Thanks!
