### ISSUE TITLE
Articles view for a course should be filterable by 'new'

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#97]
The Articles view for a course should be able to be filtered to only new articles.

**Comment by ntdb** [comment]
This is dependent upon a general implementation of filtering on tables.

**Comment by ragesoss** [comment]
We have some easy-to-replicate examples of doing filtering on tables of Redux data now, so this should be straightforward to implement. See UploadsHandler and UploadsList, and the associated reducer and actions, for good examples.

**Comment by ragesoss** [comment]
Done!
