### ISSUE TITLE
Input fields in CourseCreator and CourseCloneModal are laggy

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#975]

**Comment by mattfordham** [comment]
@ragesoss When you get a sec, could you try this out? https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/0f23fe34d4c33e4fb77a291f032012e98950cd26

Feel less laggy?

**Comment by ragesoss** [comment]
Yes, that definitely cuts the lag considerably. (It's more severe in development, by far, so this might make it go away completely in production.) Nice!

**Comment by mattfordham** [comment]
Excellent! Hopefully it doesn't cut functionality ;) 

It's a kinda a widespread update, as the InputMixin is used lots. The only potential issue I see is if the "shallow" compare is missing "deep", and important, changes to incoming props or state. I looked for situations like this but didn't find any. Worth keeping an eye on. 

I'll keep working on this branch for the existence check issue.
