### ISSUE TITLE
Wizard doesn't scroll back up to the top on step advance

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#98]
If a long step requires me to scroll down to see all the content, then the window should scroll up to the top when I advance to the next step.

**Comment by ntdb** [comment]
Additionally, the vertical spacing on the wizard is strangely sticky when expanding options on the first panel.

**Comment by ragesoss** [comment]
Fixed with 549ff29654d4526a0f39c86559040f504780902e
