### ISSUE TITLE
Feedback Form Response index should show more of response body

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#990]
Maybe twice as much as it shows now

**Comment by nmartinez23** [comment]
Hi ragesoss, I would like to work on this and also #989. The other day you messaged me about the setup guide for the dev environment, although I don't see a link included.  Is there a specific guide or should I just follow the instructions at https://www.mediawiki.org/wiki/How_to_become_a_MediaWiki_hacker ?
Thanks!

**Comment by ragesoss** [comment]
@nmartinez23 hi! This project, the dashboard, is separate from MediaWiki. Here's the guide to getting a development environment set up: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md

And here are some of the relevant places related these tasks:
* https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/controllers/feedback_form_responses_controller.rb
* https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/views/feedback_form_responses/index.html.haml
* https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/views/alerts_list/index.html.haml
